swagger: '2.0'
basePath: /
info:
  version: '1.0'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /app/as_code/import_config/:
    post:
      operationId: as_code_import_config
      description: 导入 AsCode 配置
      tags:
      - as_code
      - external_api
      - app_verify
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/as_code/import_config/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: import AsCode config
  /app/as_code/export_config/:
    post:
      operationId: as_code_export_config
      description: 导出 AsCode 配置
      tags:
      - as_code
      - external_api
      - app_verify
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/as_code/export_config/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: export AsCode config
