swagger: '2.0'
basePath: /
info:
  version: '1.0'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /v2/monitor_v3/batch_create_action/:
    post:
      operationId: batch_create_action
      description: 批量创建处理事件
      tags:
      - action
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/action_instance/batch_create_action/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: batch_create_action
  /v2/monitor_v3/save_action_config/:
    post:
      operationId: save_action_config
      description: 保存处理套餐
      tags:
      - action
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/action_config/save/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: save_action_config
  /v2/monitor_v3/get_action_config/:
    get:
      operationId: get_action_config
      description: 获取单个处理套餐
      tags:
      - action
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/action_config/detail/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: get_action_config
  /v2/monitor_v3/search_action_config/:
    get:
      operationId: search_action_config
      description: 批量获取处理套餐
      tags:
      - action
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/action_config/search/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: search_action_config
  /v2/monitor_v3/edit_action_config/:
    post:
      operationId: edit_action_config
      description: 编辑处理套餐
      tags:
      - action
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/action_config/edit/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: edit_action_config
  /v2/monitor_v3/delete_action_config/:
    post:
      operationId: delete_action_config
      description: 删除处理套餐
      tags:
      - action
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/action_config/delete/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: delete_action_config
  /v2/monitor_v3/search_action/:
    post:
      operationId: search_action
      description: 查询处理记录
      tags:
      - action
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/search_action/search_action/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: search_action
  /v2/monitor_v3/get_action_params_by_config/:
    post:
      operationId: get_action_params_by_config
      description: 根据套餐ID获取当前告警处理参数
      tags:
      - action
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/action_instance/get_action_params_by_config/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: null
