swagger: '2.0'
basePath: /
info:
  version: '1.0'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /v2/monitor_v3/search_alert/:
    post:
      operationId: search_alert
      description: 查询告警记录
      tags:
      - alert
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/search_alert/search_alert/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: search_alert
  /v2/monitor_v3/get_experience/:
    get:
      operationId: get_experience
      description: 获取告警处理经验
      tags:
      - alert
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/alert/alert/get_experience/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: get_experience
  /v2/monitor_v3/assign/search_rule_groups/:
    post:
      operationId: search_rule_groups
      description: 查询分派组
      tags:
      - alert
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/alert_assign/search_rule_groups/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: search assign group
  /v2/monitor_v3/assign/save_rule_group/:
    post:
      operationId: save_rule_group
      description: 保存分派组
      tags:
      - alert
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/alert_assign/save_rule_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: save assign group
  /v2/monitor_v3/assign/delete_rule_group/:
    post:
      operationId: delete_rule_group
      description: 删除分派组
      tags:
      - alert
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/alert_assign/delete_rule_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: delete assign group
