swagger: '2.0'
basePath: /
info:
  version: '1.0'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /v2/monitor_v3/custom_time_series/:
    get:
      operationId: custom_time_series
      description: 自定义指标列表
      tags:
      - custom_time_series
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/custom_metric/custom_time_series/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: custom_time_series
  /v2/monitor_v3/custom_time_series_detail/:
    get:
      operationId: custom_time_series_detail
      description: 自定义指标详情
      tags:
      - custom_time_series
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/custom_metric/custom_time_series_detail/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: custom_time_series_detail
  /v2/monitor_v3/create_custom_time_series/:
    post:
      operationId: create_custom_time_series
      description: 创建自定义指标
      tags:
      - custom_time_series
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/custom_metric/create_custom_time_series/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: create_custom_time_series
  /v2/monitor_v3/modify_custom_time_series/:
    post:
      operationId: modify_custom_time_series
      description: 修改自定义指标
      tags:
      - custom_time_series
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/custom_metric/modify_custom_time_series/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: modify_custom_time_series
  /v2/monitor_v3/delete_custom_time_series/:
    post:
      operationId: delete_custom_time_series
      description: 删除自定义指标
      tags:
      - custom_time_series
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/custom_metric/delete_custom_time_series/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: delete_custom_time_series
