swagger: '2.0'
basePath: /
info:
  version: '1.0'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /v2/monitor_v3/search_duty_rules/:
    post:
      operationId: search_duty_rules
      description: 查询轮值规则组
      tags:
      - duty_rule
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/duty_rule/search/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: search user group latest
  /v2/monitor_v3/search_duty_rule_detail/:
    post:
      operationId: search_duty_rule_detail
      description: 查询单个轮值规则的详情
      tags:
      - duty_rule
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/duty_rule/search_detail/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: search duty rule detail
  /v2/monitor_v3/delete_duty_rules/:
    post:
      operationId: delete_duty_rules
      description: 批量删除轮值规则
      tags:
      - duty_rule
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/duty_rule/delete/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: delete duty rules
  /v2/monitor_v3/save_duty_rule/:
    post:
      operationId: save_duty_rule
      description: 保存轮值规则
      tags:
      - duty_rule
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/duty_rule/save/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: save duty rule
  /v2/monitor_v3/preview_duty_rule/:
    post:
      operationId: preview_duty_rule
      description: 预览轮值规则
      tags:
      - duty_rule
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/duty_rule/preview/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: preview duty rule
