swagger: '2.0'
basePath: /
info:
  version: '1.0'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /v2/monitor_v3/metadata_get_event_group/:
    get:
      operationId: metadata_get_event_group
      description: 查询事件分组具体内容
      tags:
      - event
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v3/meta/get_event_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: metadata get event group
  /v2/monitor_v3/metadata_delete_event_group/:
    post:
      operationId: metadata_delete_event_group
      description: 删除事件分组
      tags:
      - event
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/meta/delete_event_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: metadata delete event group
  /v2/monitor_v3/metadata_modify_event_group/:
    post:
      operationId: metadata_modify_event_group
      description: 修改事件分组
      tags:
      - event
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/meta/modify_event_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: metadata modify event group
  /v2/monitor_v3/metadata_create_event_group/:
    post:
      operationId: metadata_create_event_group
      description: 创建事件分组
      tags:
      - event
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/meta/create_event_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: metadata create event group
  /v2/monitor_v3/metadata_query_event_group/:
    get:
      operationId: metadata_query_event_group
      description: 查询事件分组
      tags:
      - event
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v3/meta/query_event_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: metadata query event group
  /v2/monitor_v3/get_event_log/:
    get:
      operationId: get_event_log
      description: 查询事件流转记录
      tags:
      - event
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/event/event_log/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: get event log
  /v2/monitor_v3/search_event/:
    post:
      operationId: search_event
      description: 查询事件
      tags:
      - event
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/event/search/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: search event
  /v2/monitor_v3/ack_event/:
    post:
      operationId: ack_event
      description: 告警事件确认
      tags:
      - event
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/event/ack_event/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: ack_event
  /v2/monitor_v3/proxy_host_info/:
    get:
      operationId: proxy_host_info
      description: 获取自定义上报的proxy主机信息
      tags:
      - event
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/custom_event/proxy_host_info/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: proxy host info
  /v2/monitor_v3/query_custom_event_group/:
    get:
      operationId: query_custom_event_group
      description: 获取业务下自定义事件列表
      tags:
      - event
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/custom_event/query_custom_event_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: query_custom_event_group
  /v2/monitor_v3/get_custom_event_group/:
    get:
      operationId: get_custom_event_group
      description: 获取自定义事件详情
      tags:
      - event
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/custom_event/get_custom_event_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: get_custom_event_group
  /v2/monitor_v3/validate_custom_event_group_name/:
    get:
      operationId: validate_custom_event_group_name
      description: 校验自定义事件名称是否合法
      tags:
      - event
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/custom_event/validate_custom_event_group_name/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: validate_custom_event_group_name
  /v2/monitor_v3/create_custom_event_group/:
    post:
      operationId: create_custom_event_group
      description: 创建自定义事件
      tags:
      - event
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/custom_event/create_custom_event_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: create_custom_event_group
  /v2/monitor_v3/modify_custom_event_group/:
    post:
      operationId: modify_custom_event_group
      description: 修改自定义事件
      tags:
      - event
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/custom_event/modify_custom_event_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: modify_custom_event_group
  /v2/monitor_v3/delete_custom_event_group/:
    post:
      operationId: delete_custom_event_group
      description: 删除自定义事件
      tags:
      - event
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/custom_event/delete_custom_event_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: delete_custom_event_group
  /v2/monitor_v3/search_alert_by_event/:
    post:
      operationId: search_alert_by_event
      description: 根据event获取告警处理信息
      tags:
      - event
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/alert_info/search_alert_by_event/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: search alert by event
  /v2/monitor_v3/query_apm_event/:
    post:
      operationId: query_apm_event
      description: 查询APM相关事件信息
      tags:
      - event
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /apm_api/v1/application/query_event/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: query apm event
  /v2/monitor_v3/deploy_event_plugin/:
    post:
      operationId: deploy_event_plugin
      description: 部署告警源插件
      tags:
      - event
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/event_plugin/deploy_event_plugin/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: deploy event plugin
