swagger: '2.0'
basePath: /
info:
  version: '1.0'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /v2/monitor_v3/get_statistics_by_json/:
    get:
      operationId: get_statistics_by_json
      description: 查询运营数据
      tags:
      - render_image
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/mail_report/get_statistics_by_json/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: get statistics by json
  /v2/monitor_v3/test_report_mail/:
    post:
      operationId: test_report_mail
      description: 订阅报表测试
      tags:
      - render_image
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/mail_report/test_report_mail/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: test report mail
  /v2/monitor_v3/send_report_mail/:
    post:
      operationId: send_report_mail
      description: 发送订阅报表
      tags:
      - render_image
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/mail_report/send_report_mail/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: send report mail
  /v2/monitor_v3/start_render_image_task/:
    post:
      operationId: start_render_image_task
      description: 启动渲染图片任务
      tags:
      - render_image
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/render_image/render/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: start render image task
  /v2/monitor_v3/get_render_image_task_result/:
    get:
      operationId: get_render_image_task_result
      description: 获取渲染图片结果
      tags:
      - render_image
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/render_image/result/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: get render image task result
  /v2/monitor_v3/send_report/:
    post:
      operationId: send_report
      description: 发送订阅报表
      tags:
      - render_image
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/new_report/send_report/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: send report
  /v2/monitor_v3/group_list/:
    get:
      operationId: group_list
      description: 查询组内人员
      tags:
      - render_image
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/mail_report/group_list/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: group list
  /v2/monitor_v3/is_superuser/:
    get:
      operationId: is_superuser
      description: 判断用户是否超级管理员
      tags:
      - render_image
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/mail_report/is_superuser/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: is superuser
  /v2/monitor_v3/get_setting_and_notify_group/:
    get:
      operationId: get_setting_and_notify_group
      description: 获取配置管理员及其业务、告警接收人及其业务
      tags:
      - render_image
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/mail_report/get_setting_and_notify_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: get setting and notify group
