swagger: '2.0'
basePath: /
info:
  version: '1.0'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /v2/monitor_v3/get_uptime_check_task_list/:
    get:
      operationId: get_uptime_check_task_list
      description: 拨测任务列表
      tags:
      - uptime_check
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v3/models/uptime_check_task/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: get uptime check task list
  /v2/monitor_v3/get_uptime_check_node_list/:
    get:
      operationId: get_uptime_check_node_list
      description: 拨测节点列表
      tags:
      - uptime_check
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v3/models/uptime_check_node/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: get uptime check node list
  /v2/monitor_v3/uptime_check_node_info/:
    get:
      operationId: uptime_check_node_info
      description: 获取拨测节点信息
      tags:
      - uptime_check
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v3/models/uptime_check_node/{node_id}/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: uptime check node info
  /v2/monitor_v3/edit_uptime_check_node/:
    post:
      operationId: edit_uptime_check_node
      description: 编辑拨测节点信息
      tags:
      - uptime_check
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/models/uptime_check_node/edit/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: edit uptime check node info
  /v2/monitor_v3/delete_uptime_check_node/:
    post:
      operationId: delete_uptime_check_node
      description: 删除拨测节点
      tags:
      - uptime_check
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/models/uptime_check_node/delete/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: delete uptime check node
  /v2/monitor_v3/create_uptime_check_node/:
    post:
      operationId: create_uptime_check_node
      description: 创建拨测节点
      tags:
      - uptime_check
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/models/uptime_check_node/add/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: create uptime check node
  /v2/monitor_v3/uptime_check_task_info/:
    get:
      operationId: uptime_check_task_info
      description: 获取拨测任务信息
      tags:
      - uptime_check
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v3/models/uptime_check_task/{task_id}/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: uptime check task info
  /v2/monitor_v3/create_uptime_check_task/:
    post:
      operationId: create_uptime_check_task
      description: 创建拨测任务
      tags:
      - uptime_check
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/models/uptime_check_task/add/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: create uptime check task
  /v2/monitor_v3/edit_uptime_check_task/:
    post:
      operationId: edit_uptime_check_task
      description: 编辑拨测任务信息
      tags:
      - uptime_check
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/models/uptime_check_task/edit/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: edit uptime check task info
  /v2/monitor_v3/delete_uptime_check_task/:
    post:
      operationId: delete_uptime_check_task
      description: 删除拨测任务
      tags:
      - uptime_check
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/models/uptime_check_task/delete/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: delete uptime check task
  /v2/monitor_v3/test_uptime_check_task/:
    post:
      operationId: test_uptime_check_task
      description: 测试连通性
      tags:
      - uptime_check
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/models/uptime_check_task/test/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: test uptime check task
  /v2/monitor_v3/deploy_uptime_check_task/:
    post:
      operationId: deploy_uptime_check_task
      description: 下发拨测任务
      tags:
      - uptime_check
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/models/uptime_check_task/deploy/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: deploy uptime check task
  /v2/monitor_v3/change_uptime_check_task_status/:
    post:
      operationId: change_uptime_check_task_status
      description: 启停拨测任务
      tags:
      - uptime_check
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/models/uptime_check_task/change_status/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: change uptime check task status
  /v2/monitor_v3/create_uptime_check_group/:
    post:
      operationId: create_uptime_check_group
      description: 创建拨测任务组
      tags:
      - uptime_check
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/models/uptime_check_group/add/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: create uptime check group
  /v2/monitor_v3/delete_uptime_check_group/:
    post:
      operationId: delete_uptime_check_group
      description: 删除拨测任务组
      tags:
      - uptime_check
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/models/uptime_check_group/delete/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: delete uptime check group
  /v2/monitor_v3/edit_uptime_check_group/:
    post:
      operationId: edit_uptime_check_group
      description: 编辑拨测任务组信息
      tags:
      - uptime_check
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/models/uptime_check_group/edit/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: edit uptime check group info
  /v2/monitor_v3/uptime_check_group_info/:
    get:
      operationId: uptime_check_group_info
      description: 获取拨测任务组信息
      tags:
      - uptime_check
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v3/models/uptime_check_group/{group_id}/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: uptime check group info
  /v2/monitor_v3/get_uptime_check_group_list/:
    get:
      operationId: get_uptime_check_group_list
      description: 拨测任务组列表
      tags:
      - uptime_check
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v3/models/uptime_check_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: get uptime check group list
  /v2/monitor_v3/uptime_check_group_add_task/:
    post:
      operationId: uptime_check_group_add_task
      description: 拨测任务组新增拨测任务
      tags:
      - uptime_check
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/models/uptime_check_group/add_task/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: uptime check group add task
  /v2/monitor_v3/uptime_check_group_remove_task/:
    post:
      operationId: uptime_check_group_remove_task
      description: 拨测任务组移除拨测任务
      tags:
      - uptime_check
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/models/uptime_check_group/remove_task/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: uptime check group remove task
