swagger: '2.0'
basePath: /
info:
  version: '1.0'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /v2/monitor_v3/search_user_groups/:
    post:
      operationId: search_user_groups
      description: 查询用户组(新版)
      tags:
      - user_group
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/user_group/search/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: search user group latest
  /v2/monitor_v3/search_user_group_detail/:
    post:
      operationId: search_user_group_detail
      description: 查询单个用户组详情
      tags:
      - user_group
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/user_group/search_detail/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: search user group detail
  /v2/monitor_v3/delete_user_groups/:
    post:
      operationId: delete_user_groups
      description: 批量删除用户组
      tags:
      - user_group
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/user_group/delete/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: delete user groups
  /v2/monitor_v3/save_user_group/:
    post:
      operationId: save_user_group
      description: 保存用户组
      tags:
      - user_group
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/user_group/save/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: save user group
  /v2/monitor_v3/preview_user_group/:
    post:
      operationId: preview_user_group
      description: 预览一个组的轮值规则
      tags:
      - user_group
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/user_group/preview/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: preview duty user group
