# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2020-05-12 09:39


from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0059_merge_20200416_1159"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSeriesGroup",
            fields=[
                ("bk_data_id", models.IntegerField(verbose_name="数据源ID", db_index=True)),
                ("bk_biz_id", models.IntegerField(verbose_name="业务ID", db_index=True)),
                ("table_id", models.CharField(max_length=128, verbose_name="结果表ID")),
                ("label", models.CharField(default="others", max_length=128, verbose_name="事件标签")),
                ("is_enable", models.BooleanField(default=True, verbose_name="是否启用")),
                ("is_delete", models.BooleanField(default=False, verbose_name="是否删除")),
                ("creator", models.CharField(max_length=255, verbose_name="创建者")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("last_modify_user", models.CharField(max_length=32, verbose_name="最后更新者")),
                ("last_modify_time", models.DateTimeField(auto_now=True, verbose_name="最后更新时间")),
                ("time_series_group_id", models.AutoField(primary_key=True, serialize=False, verbose_name="分组ID")),
                ("time_series_group_name", models.CharField(max_length=255, verbose_name="自定义时序分组名")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TimeSeriesMetric",
            fields=[
                ("group_id", models.IntegerField(verbose_name="自定义时序所属分组ID")),
                ("field_id", models.AutoField(primary_key=True, serialize=False, verbose_name="自定义时序字段ID")),
                ("field_name", models.CharField(max_length=255, verbose_name="自定义时序字段名称")),
                ("tag_list", bkmonitor.utils.db.fields.JsonField(default=[], verbose_name="Tag列表")),
                ("last_modify_time", models.DateTimeField(auto_now=True, verbose_name="最后更新时间")),
            ],
            options={
                "verbose_name": "自定义时序描述记录",
                "verbose_name_plural": "自定义时序描述记录表",
            },
        ),
        migrations.AlterUniqueTogether(
            name="timeseriesmetric",
            unique_together={("group_id", "field_name")},
        ),
    ]
