# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2020-04-16 03:59


from django.db import migrations
from django.db.models import Q


"""
预处理内置指标字段单位
去除中文无意义单位： 次，个， 条
更新中文单位： 秒->s, 次/s->cps, 个/s->cps
"""


def pre_change_unit(apps, schema_editor):
    ResultTableField = apps.get_model("metadata", "ResultTableField")
    target_fileds = ResultTableField.objects.filter(
        Q(table_id__contains="system.") | Q(table_id__contains="beat_monitor.") | Q(table_id__contains="uptimecheck.")
    )

    change_tasks = [
        ("次", ""),
        ("个", ""),
        ("条", ""),
        ("秒", "s"),
        ("次/s", "cps"),
        ("个/s", "cps"),
    ]
    for _from, _to in change_tasks:
        target_fileds.filter(unit=_from).update(unit=_to)


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0059_merge_20200416_1159"),
    ]

    operations = [migrations.RunPython(pre_change_unit)]
