# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2020-08-31 08:08


from django.db import migrations, models


def update_default_mq_cluster_register_to_gse(apps, schema_editor):
    ClusterInfo = apps.get_model("metadata", "ClusterInfo")
    mq_cluster = ClusterInfo.objects.filter(cluster_type="kafka", is_default_cluster=True)
    if mq_cluster.exists():
        mq_cluster.update(is_register_to_gse=True)


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0067_datasource_consul_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusterinfo",
            name="gse_stream_to_id",
            field=models.IntegerField(default=-1, verbose_name="GSE接收端配置ID"),
        ),
        migrations.AddField(
            model_name="clusterinfo",
            name="is_register_to_gse",
            field=models.BooleanField(default=False, verbose_name="是否需要往GSE注册"),
        ),
        migrations.RunPython(update_default_mq_cluster_register_to_gse),
    ]
