# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2020-08-19 12:45


from django.db import migrations, models

from bkmonitor.strategy.upgrade import UPDATE_METRICS


def update_metric_unit_and_name(apps, *args, **kwargs):
    """更新部分内置指标单位 none-> short"""
    ResultTableField = apps.get_model("metadata", "ResultTableField")

    for metric in UPDATE_METRICS:
        ResultTableField.objects.filter(table_id=metric["table_id"], field_name=metric["field_name"]).update(
            unit=metric["unit"], description=metric["description"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0084_auto_20210322_1536"),
    ]

    operations = [
        migrations.RunPython(update_metric_unit_and_name),
    ]
