# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-08-04 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0088_add_custom_report_aggate_dataid"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventgroup",
            name="is_split_measurement",
            field=models.BooleanField(default=False, verbose_name="是否需要单个指标单表存储"),
        ),
        migrations.AddField(
            model_name="timeseriesgroup",
            name="is_split_measurement",
            field=models.BooleanField(default=False, verbose_name="是否需要单个指标单表存储"),
        ),
        migrations.AddField(
            model_name="timeseriesmetric",
            name="table_id",
            field=models.CharField(default="", max_length=255, verbose_name="table名"),
        ),
        migrations.AlterField(
            model_name="bkdatastorage",
            name="etl_json_config",
            field=models.TextField(verbose_name="清洗配置"),
        ),
        migrations.AlterField(
            model_name="datasourceoption",
            name="name",
            field=models.CharField(max_length=128, verbose_name="option名称"),
        ),
        migrations.AlterField(
            model_name="eventgroup",
            name="table_id",
            field=models.CharField(db_index=True, max_length=128, null=True, verbose_name="结果表ID"),
        ),
        migrations.AlterField(
            model_name="timeseriesgroup",
            name="table_id",
            field=models.CharField(db_index=True, max_length=128, null=True, verbose_name="结果表ID"),
        ),
    ]
