# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2021-12-07 11:11

from django.db import migrations

UPDATE_METRICS = [
    {
        "table_id": "system.mem",
        "field_name": "buffer",
        "unit": "bytes",
        "description": "内存buffered大小",
        "suffix": "Mi",
    },
    {"table_id": "system.mem", "field_name": "cached", "unit": "bytes"},
    {"table_id": "system.mem", "field_name": "free", "unit": "bytes"},
    {"table_id": "system.mem", "field_name": "total", "unit": "bytes"},
    {"table_id": "system.mem", "field_name": "usable", "unit": "bytes"},
    {"table_id": "system.mem", "field_name": "used", "unit": "bytes"},
    {"table_id": "system.mem", "field_name": "psc_used", "unit": "bytes"},
    {"table_id": "system.disk", "field_name": "free", "unit": "bytes"},
    {"table_id": "system.disk", "field_name": "total", "unit": "bytes"},
    {"table_id": "system.disk", "field_name": "used", "unit": "bytes"},
    {"table_id": "system.proc", "field_name": "mem_res", "unit": "bytes"},
    {"table_id": "system.proc", "field_name": "mem_virt", "unit": "bytes"},
    {"table_id": "system.swap", "field_name": "free", "unit": "bytes"},
    {"table_id": "system.swap", "field_name": "total", "unit": "bytes"},
    {"table_id": "system.swap", "field_name": "used", "unit": "bytes"},
    {"table_id": "uptimecheck.http", "field_name": "content_length", "unit": "bytes"},
]


def update_unit_from_metadata(apps, *args, **kwargs):
    """
    修改元信息中的相关数据
    """
    ResultTableField = apps.get_model("metadata", "ResultTableField")

    for metric in UPDATE_METRICS:
        ResultTableField.objects.filter(table_id=metric["table_id"], field_name=metric["field_name"]).update(
            unit=metric["unit"]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0091_merge_20210717_1517"),
    ]

    operations = [
        migrations.RunPython(update_unit_from_metadata),
    ]
