# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-17 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0092_update_unit_decbytes_to_bytes"),
        ("metadata", "0092_influxdbstorage_enable_refresh_rp"),
    ]

    operations = []
