# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-10-19 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import metadata.models.storage


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0092_auto_20210809_1544"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArgusStorage",
            fields=[
                ("table_id", models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name="结果表名")),
                ("storage_cluster_id", models.IntegerField(verbose_name="存储集群")),
                ("tenant_id", models.CharField(max_length=64, verbose_name="argus租户ID")),
            ],
            bases=(models.Model, metadata.models.storage.StorageResultTable),
        ),
    ]
