# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-09-14 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0092_merge_20210803_1738"),
        ("metadata", "0089_auto_20210804_1612"),
    ]

    operations = []
