# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-09-22 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0093_merge"),
    ]

    operations = [
        migrations.CreateModel(
            name="BCSClusterInfo",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cluster_id", models.IntegerField(verbose_name="集群ID")),
                ("bcs_api_cluster_id", models.CharField(db_index=True, max_length=128, verbose_name="bcs-api集群ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务ID")),
                ("project_id", models.IntegerField(verbose_name="项目ID")),
                ("domain_name", models.CharField(max_length=512, verbose_name="集群链接域名")),
                ("port", models.IntegerField(verbose_name="集群链接端口")),
                ("server_address_path", models.CharField(max_length=512, verbose_name="集群请求根路径")),
                ("api_key_type", models.CharField(default="authorization", max_length=128, verbose_name="身份认证信息类型")),
                ("api_key_content", models.CharField(max_length=128, verbose_name="身份认证信息")),
                ("api_key_prefix", models.CharField(default="Bearer", max_length=128, verbose_name="身份认证信息前缀")),
                ("is_skip_ssl_verify", models.BooleanField(default=True, verbose_name="是否跳过SSL认证")),
                ("cert_content", models.TextField(default=None, null=True, verbose_name="认证证书信息")),
                ("k8s_metric_data_id", models.IntegerField(default=0, verbose_name="k8s指标data_id")),
                ("custom_metric_data_id", models.IntegerField(default=0, verbose_name="自定义指标data_id")),
                ("k8s_event_data_id", models.IntegerField(default=0, verbose_name="k8s事件data_id")),
                ("custom_event_data_id", models.IntegerField(default=0, verbose_name="自定义事件data_id")),
                ("system_log_data_id", models.IntegerField(default=0, verbose_name="系统日志data_id")),
                ("custom_log_data_id", models.IntegerField(default=0, verbose_name="应用或自定义日志data_id")),
                ("creator", models.CharField(max_length=32, verbose_name="创建者")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("last_modify_user", models.CharField(max_length=32, verbose_name="最后更新者")),
                ("last_modify_time", models.DateTimeField(auto_now=True, verbose_name="最后更新时间")),
            ],
        ),
        migrations.CreateModel(
            name="PodMonitorInfo",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cluster_id", models.IntegerField(verbose_name="集群ID")),
                ("namespace", models.CharField(max_length=512, verbose_name="归属命名空间名")),
                ("name", models.CharField(max_length=128, verbose_name="资源名")),
                ("bk_data_id", models.BigIntegerField(db_index=True, max_length=128, verbose_name="数据源ID")),
                ("is_custom_resource", models.BooleanField(default=True, verbose_name="是否自定义资源")),
                ("is_common_data_id", models.BooleanField(default=True, verbose_name="是否使用公共data_id")),
                ("record_create_time", models.DateTimeField(verbose_name="资源记录创建时间")),
                ("resource_create_time", models.DateTimeField(verbose_name="资源在集群中创建时间")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceMonitorInfo",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cluster_id", models.IntegerField(verbose_name="集群ID")),
                ("namespace", models.CharField(max_length=512, verbose_name="归属命名空间名")),
                ("name", models.CharField(max_length=128, verbose_name="资源名")),
                ("bk_data_id", models.BigIntegerField(db_index=True, max_length=128, verbose_name="数据源ID")),
                ("is_custom_resource", models.BooleanField(default=True, verbose_name="是否自定义资源")),
                ("is_common_data_id", models.BooleanField(default=True, verbose_name="是否使用公共data_id")),
                ("record_create_time", models.DateTimeField(verbose_name="资源记录创建时间")),
                ("resource_create_time", models.DateTimeField(verbose_name="资源在集群中创建时间")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterUniqueTogether(
            name="servicemonitorinfo",
            unique_together={("cluster_id", "namespace", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="podmonitorinfo",
            unique_together={("cluster_id", "namespace", "name")},
        ),
    ]
