# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-10-21 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0093_auto_20211019_1617"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resulttable",
            name="default_storage",
            field=models.CharField(
                choices=[
                    ("influxdb", "influxDB"),
                    ("kafka", "kafka"),
                    ("redis", "redis"),
                    ("elasticsearch", "elasticsearch"),
                    ("argus", "argus"),
                ],
                max_length=32,
                verbose_name="默认存储方案",
            ),
        ),
    ]
