# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-07 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0094_auto_20211021_1500"),
        ("metadata", "0092_update_unit_decbytes_to_bytes"),
    ]

    operations = []
