# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-10-26 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0092_merge_20210803_1738"),
        ("metadata", "0094_auto_20211021_1500"),
    ]

    operations = []
