# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-11-09 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0092_influxdbstorage_enable_refresh_rp"),
        ("metadata", "0094_auto_20211021_1500"),
    ]

    operations = []
