# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-09-26 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0094_auto_20210922_2038"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bcsclusterinfo",
            name="cluster_id",
            field=models.CharField(max_length=128, verbose_name="集群ID"),
        ),
        migrations.AlterField(
            model_name="bcsclusterinfo",
            name="project_id",
            field=models.CharField(max_length=128, verbose_name="项目ID"),
        ),
        migrations.AlterField(
            model_name="podmonitorinfo",
            name="cluster_id",
            field=models.CharField(max_length=128, verbose_name="集群ID"),
        ),
        migrations.AlterField(
            model_name="servicemonitorinfo",
            name="cluster_id",
            field=models.CharField(max_length=128, verbose_name="集群ID"),
        ),
    ]
