# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-17 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0093_merge_20211217_1642"),
        ("metadata", "0095_merge_20211109_1012"),
        ("metadata", "0095_merge_20211207_1140"),
    ]

    operations = []
