# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-09-30 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0096_merge_20210928_1920"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bcsclusterinfo",
            old_name="custom_event_data_id",
            new_name="CustomEventDataID",
        ),
        migrations.RenameField(
            model_name="bcsclusterinfo",
            old_name="custom_log_data_id",
            new_name="CustomLogDataID",
        ),
        migrations.RenameField(
            model_name="bcsclusterinfo",
            old_name="custom_metric_data_id",
            new_name="CustomMetricDataID",
        ),
        migrations.RenameField(
            model_name="bcsclusterinfo",
            old_name="k8s_event_data_id",
            new_name="K8sEventDataID",
        ),
        migrations.RenameField(
            model_name="bcsclusterinfo",
            old_name="k8s_metric_data_id",
            new_name="K8sMetricDataID",
        ),
        migrations.RenameField(
            model_name="bcsclusterinfo",
            old_name="system_log_data_id",
            new_name="SystemLogDataID",
        ),
    ]
