# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-02-17 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0097_merge_20211230_1521"),
    ]

    operations = [
        migrations.AddField(
            model_name="pingserversubscriptionconfig",
            name="ip",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="IP地址"),
        ),
    ]
