# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-10-27 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0095_merge_20211026_1640"),
        ("metadata", "0097_auto_20210930_1507"),
    ]

    operations = []
