# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-11-09 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0098_merge_20211027_1132"),
        ("metadata", "0095_merge_20211109_1012"),
    ]

    operations = []
