# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-02-24 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0098_pingserversubscriptionconfig_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pingserversubscriptionconfig",
            name="bk_cloud_id",
            field=models.IntegerField(verbose_name="云区域ID"),
        ),
        migrations.AlterField(
            model_name="pingserversubscriptionconfig",
            name="subscription_id",
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name="节点管理订阅ID"),
        ),
        migrations.AlterUniqueTogether(
            name="pingserversubscriptionconfig",
            unique_together={("bk_cloud_id", "ip")},
        ),
    ]
