# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-11-02 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0098_merge_20211027_1132"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplaceConfig",
            fields=[
                (
                    "rule_name",
                    models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name="replace规则名"),
                ),
                ("is_common", models.BooleanField(db_index=True, max_length=128, verbose_name="是否是通用replace配置")),
                ("source_name", models.CharField(max_length=128, verbose_name="数据源名称")),
                ("target_name", models.CharField(max_length=128, verbose_name="replace目标名称")),
                (
                    "replace_type",
                    models.CharField(
                        choices=[("dimension", "dimension"), ("metric", "metric")],
                        max_length=128,
                        verbose_name="replace类型",
                    ),
                ),
                (
                    "custom_level",
                    models.CharField(
                        choices=[("cluster", "cluster"), ("resource", "resource"), (None, "none")],
                        default=None,
                        max_length=128,
                        verbose_name="自定义影响层级",
                    ),
                ),
                ("cluster_id", models.CharField(db_index=True, default=None, max_length=128, verbose_name="集群id")),
                ("resource_name", models.CharField(db_index=True, default=None, max_length=128, verbose_name="资源名")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("ServiceMonitor", "ServiceMonitor"), ("PodMonitor", "PodMonitor"), (None, "none")],
                        db_index=True,
                        default=None,
                        max_length=128,
                        verbose_name="资源类型",
                    ),
                ),
                (
                    "resource_namespace",
                    models.CharField(db_index=True, default=None, max_length=128, verbose_name="资源命名空间"),
                ),
            ],
        ),
    ]
