# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-11-10 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0099_merge_20211109_1037"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogCollectorInfo",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cluster_id", models.CharField(max_length=128, verbose_name="集群ID")),
                ("namespace", models.CharField(max_length=512, verbose_name="归属命名空间名")),
                ("name", models.CharField(max_length=128, verbose_name="资源名")),
                ("bk_data_id", models.BigIntegerField(db_index=True, max_length=128, verbose_name="数据源ID")),
                ("is_custom_resource", models.BooleanField(default=True, verbose_name="是否自定义资源")),
                ("is_common_data_id", models.BooleanField(default=True, verbose_name="是否使用公共data_id")),
                ("record_create_time", models.DateTimeField(verbose_name="资源记录创建时间")),
                ("resource_create_time", models.DateTimeField(verbose_name="资源在集群中创建时间")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterUniqueTogether(
            name="logcollectorinfo",
            unique_together={("cluster_id", "namespace", "name")},
        ),
    ]
