# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-11-11 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0100_auto_20211110_1631'),
        ('metadata', '0099_auto_20211109_2047'),
    ]

    operations = [
    ]
