# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-11-11 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0100_auto_20211104_1652'),
        ('metadata', '0100_auto_20211104_1903'),
        ('metadata', '0101_merge_20211111_1602'),
    ]

    operations = [
    ]
