# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-11-11 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0101_merge_20211111_1602"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeseriesmetric",
            name="label",
            field=models.CharField(default="", max_length=255, verbose_name="指标监控对象"),
        ),
    ]
