# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-11-12 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0103_merge_20211112_1018"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replaceconfig",
            name="cluster_id",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=128, null=True, verbose_name="集群id"
            ),
        ),
        migrations.AlterField(
            model_name="replaceconfig",
            name="custom_level",
            field=models.CharField(
                blank=True,
                choices=[("cluster", "cluster"), ("resource", "resource")],
                default=None,
                max_length=128,
                null=True,
                verbose_name="自定义影响层级",
            ),
        ),
        migrations.AlterField(
            model_name="replaceconfig",
            name="resource_name",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=128, null=True, verbose_name="资源名"
            ),
        ),
        migrations.AlterField(
            model_name="replaceconfig",
            name="resource_namespace",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=128, null=True, verbose_name="资源命名空间"
            ),
        ),
        migrations.AlterField(
            model_name="replaceconfig",
            name="resource_type",
            field=models.CharField(
                blank=True,
                choices=[("ServiceMonitor", "ServiceMonitor"), ("PodMonitor", "PodMonitor")],
                db_index=True,
                default=None,
                max_length=128,
                null=True,
                verbose_name="资源类型",
            ),
        ),
    ]
