# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-11-22 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0104_auto_20211112_1019'),
        ('metadata', '0103_add_label_info'),
    ]

    operations = [
    ]
