# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-07 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0105_merge_20211122_2243"),
        ("metadata", "0096_merge_20211207_1142"),
    ]

    operations = []
