# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-13 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0106_merge_20211207_1145'),
        ('metadata', '0106_merge_20211208_1123'),
    ]

    operations = [
    ]
