# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-30 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0108_merge_20211217_1714"),
        ("metadata", "0097_merge_20211230_1521"),
    ]

    operations = []
