# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-01-20 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0109_merge_20211230_1614"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeseriesmetric",
            name="last_index",
            field=models.IntegerField(default=0, verbose_name="上次consul的modify_index"),
        ),
    ]
