# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-02-17 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0110_timeseriesmetric_last_index"),
        ("metadata", "0110_edit_label_info_k8s"),
    ]

    operations = []
