# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-02-17 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0111_merge_20220217_1143"),
        ("metadata", "0098_pingserversubscriptionconfig_ip"),
    ]

    operations = []
