# Generated by Django 1.11.23 on 2022-03-30 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0113_merge_20220217_2208"),
    ]

    operations = []
