# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-03-30 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0113_merge_20220217_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownsampledContinuousQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(max_length=128, verbose_name='数据库名')),
                ('measurement', models.CharField(default='__all__', max_length=128, verbose_name='表名')),
                ('fields', models.CharField(max_length=128, verbose_name='字段列表')),
                ('aggregations', models.CharField(max_length=128, verbose_name='聚合函数')),
                ('source_rp', models.CharField(max_length=128, verbose_name='来源RP')),
                ('target_rp', models.CharField(max_length=128, verbose_name='目标RP')),
            ],
            options={
                'verbose_name': 'downsampled 表信息配置',
            },
        ),
        migrations.CreateModel(
            name='DownsampledDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(max_length=128, unique=True, verbose_name='数据库名')),
                ('tag_name', models.CharField(blank=True, max_length=128, verbose_name='维度KEY')),
                ('tag_value', models.CharField(blank=True, max_length=128, verbose_name='维度值')),
                ('enable', models.BooleanField(default=False, verbose_name='是否开启')),
            ],
            options={
                'verbose_name': 'downsampled数据库信息配置',
            },
        ),
        migrations.CreateModel(
            name='DownsampledRetentionPolicies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(max_length=128, verbose_name='数据库名')),
                ('name', models.CharField(max_length=128, verbose_name='RP名称')),
                ('resolution', models.IntegerField(default=0, verbose_name='RP精度')),
                ('duration', models.CharField(max_length=120, verbose_name='保存时间')),
                ('replication', models.IntegerField(default=1, verbose_name='副本数')),
            ],
            options={
                'verbose_name': 'downsampled rp 信息配置',
            },
        ),
        migrations.AlterUniqueTogether(
            name='downsampledretentionpolicies',
            unique_together=set([('database', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='downsampledcontinuousqueries',
            unique_together=set([('database', 'measurement', 'source_rp', 'target_rp')]),
        ),
    ]
