# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-14 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0114_auto_20220330_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downsampledcontinuousqueries',
            options={'verbose_name': '降精度策略配置', 'verbose_name_plural': '降精度策略配置'},
        ),
        migrations.AlterModelOptions(
            name='downsampleddatabase',
            options={'verbose_name': '降精度数据库配置', 'verbose_name_plural': '降精度数据库配置'},
        ),
        migrations.AlterModelOptions(
            name='downsampledretentionpolicies',
            options={'verbose_name': '降精度rp配置', 'verbose_name_plural': '降精度rp配置'},
        ),
        migrations.AddField(
            model_name='downsampledcontinuousqueries',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downsampledcontinuousqueries',
            name='last_modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AddField(
            model_name='downsampleddatabase',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downsampleddatabase',
            name='last_modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AddField(
            model_name='downsampledretentionpolicies',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downsampledretentionpolicies',
            name='last_modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
    ]
