# Generated by Django 1.11.23 on 2022-04-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0114_auto_20220330_2008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logcollectorinfo",
            name="bk_data_id",
            field=models.BigIntegerField(db_index=True, verbose_name="数据源ID"),
        ),
        migrations.AlterField(
            model_name="podmonitorinfo",
            name="bk_data_id",
            field=models.BigIntegerField(db_index=True, verbose_name="数据源ID"),
        ),
        migrations.AlterField(
            model_name="servicemonitorinfo",
            name="bk_data_id",
            field=models.BigIntegerField(db_index=True, verbose_name="数据源ID"),
        ),
    ]
