# Generated by Django 1.11.23 on 2022-04-14 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0114_auto_20220330_2008"),
    ]

    operations = []
