# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-15 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import logging
from metadata.migration_util import models, add_datasource_option
from metadata import config

logger = logging.getLogger("metadata")


def add_bkunifylogbeat_datasource_option(apps, *args, **kwargs):
    # 获取APP models
    for model_name in list(models.keys()):
        models[model_name] = apps.get_model("metadata", model_name)

    # 数据库记录的操作员
    user = "system"
    # 数据id，用于整个链路的数据流转标识
    common_data_id = 1100006
    task_data_id = 1100007

    common_datasource_option = [
        {
            "name": "metrics_report_path",
            "value": "{}/influxdb_metrics/{}/time_series_metric".format(config.CONSUL_PATH, common_data_id),
            "value_type": "string",
        }
    ]
    task_datasource_option = [
        {
            "name": "metrics_report_path",
            "value": "{}/influxdb_metrics/{}/time_series_metric".format(config.CONSUL_PATH, task_data_id),
            "value_type": "string",
        }
    ]

    # 补充指标自动发现的datasource_option
    add_datasource_option(models, common_data_id, user, common_datasource_option)
    add_datasource_option(models, task_data_id, user, task_datasource_option)


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0115_auto_20220415_1635"),
    ]

    operations = [
        migrations.RunPython(add_bkunifylogbeat_datasource_option),
    ]
