# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-19 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0115_auto_20220414_1651'),
        ('metadata', '0115_auto_20220415_1635'),
    ]

    operations = [
    ]
