# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-05-13 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0116_auto_20220422_1707"),
        ("metadata", "0116_merge_20220419_1348"),
    ]

    operations = []
