# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-19 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0116_merge_20220419_1348"),
        ("metadata", "0115_auto_20220415_1956"),
    ]

    operations = []
