# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-05-26 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0117_merge_20220513_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcsclusterinfo',
            name='status',
            field=models.CharField(default='running', max_length=50, verbose_name='集群状态'),
        ),
    ]
