# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-27 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0116_auto_20220422_1707"),
        ("metadata", "0117_merge_20220419_1611"),
    ]

    operations = []
