# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-06-08 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0118_add_statisitcs_report_data_id"),
        ("metadata", "0118_bcsclusterinfo_status"),
    ]

    operations = []
