# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-05-17 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0118_merge_20220427_1734"),
        ("metadata", "0117_merge_20220513_1550"),
    ]

    operations = []
