# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-06-14 07:48
from __future__ import unicode_literals

from django.db import migrations, models

import bkmonitor.utils.db.fields
from metadata.utils.bcs import get_bcs_dataids

INITIAL_MONITOR_OPTION_VALUE = '["bk_monitor_name"]'
OPTION_CUSTOM_REPORT_DIMENSION_VALUES = "dimension_values"


def create_service_monitor_options(apps, schema_editor):
    """创建 Service Monitor 结果表选项"""
    result_table_option_cls = apps.get_model("metadata", "ResultTableOption")
    time_series_group_cls = apps.get_model("metadata", "TimeSeriesGroup")

    data_ids, _ = get_bcs_dataids()
    for table_id in time_series_group_cls.objects.filter(is_delete=False, bk_data_id__in=data_ids).values_list(
        "table_id", flat=True
    ):
        result_table_option_cls.objects.get_or_create(
            table_id=table_id,
            name=OPTION_CUSTOM_REPORT_DIMENSION_VALUES,
            value_type="list",
            value=INITIAL_MONITOR_OPTION_VALUE,
            creator="system",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0122_merge_20220613_1645"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSeriesTag",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group_id", models.IntegerField(verbose_name="自定义时序所属分组ID")),
                ("metric_id", models.IntegerField(verbose_name="自定义时序Schema ID")),
                ("name", models.CharField(max_length=128, verbose_name="标签(维度)")),
                ("values", bkmonitor.utils.db.fields.JsonField(default=[], verbose_name="维度值列表")),
                ("last_modify_time", models.DateTimeField(auto_now=True, verbose_name="最后更新时间")),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="timeseriestag",
            unique_together={("group_id", "metric_id", "name")},
        ),
        migrations.RunPython(create_service_monitor_options),
    ]
