# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-07-22 00:30
from __future__ import unicode_literals

from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0122_merge_20220613_1645"),
    ]

    operations = [
        migrations.CreateModel(
            name="Space",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建者")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="更新者")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("space_type_id", models.CharField(max_length=64, verbose_name="空间类型 ID")),
                ("space_id", models.CharField(help_text="空间类型下唯一", max_length=128, verbose_name="空间 ID")),
                ("space_name", models.CharField(help_text="空间类型下唯一", max_length=128, verbose_name="空间中文名称")),
                (
                    "space_code",
                    models.CharField(
                        blank=True,
                        help_text="针对容器和研发类型，会多存储存储code这个字段",
                        max_length=64,
                        null=True,
                        verbose_name="空间英文名称",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("normal", "正常"), ("disabled", "停用")],
                        default="normal",
                        max_length=32,
                        verbose_name="空间状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "空间信息",
                "verbose_name_plural": "空间信息",
            },
        ),
        migrations.CreateModel(
            name="SpaceDataSource",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建者")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="更新者")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("space_type_id", models.CharField(max_length=64, verbose_name="空间类型英文名称")),
                ("space_id", models.CharField(max_length=128, verbose_name="Space 英文名称")),
                ("bk_data_id", models.IntegerField(verbose_name="数据源 ID")),
                ("from_authorization", models.BooleanField(default=False, verbose_name="是否来源于授权")),
            ],
            options={
                "verbose_name": "空间与数据源关系配置",
                "verbose_name_plural": "空间与数据源关系配置",
            },
        ),
        migrations.CreateModel(
            name="SpaceResource",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建者")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="更新者")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("space_type_id", models.CharField(max_length=64, verbose_name="空间类型英文名称")),
                ("space_id", models.CharField(max_length=128, verbose_name="空间英文名称")),
                (
                    "resource_type",
                    models.CharField(help_text="关联的资源类型，必须属于某个空间类型", max_length=128, verbose_name="资源类型"),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        help_text="关联的资源的唯一标识，如关联BCS项目ID，BKCC业务ID等",
                        max_length=64,
                        null=True,
                        verbose_name="关联的资源唯一标识",
                    ),
                ),
                (
                    "dimension_values",
                    bkmonitor.utils.db.fields.JsonField(
                        default=[],
                        help_text="关键维度值，格式如[{'project_id': 'testproject', 'cluster_id': 'BCS-K8S-1000', 'namespace': 'test'}]",
                        verbose_name="关键维度对应的值",
                    ),
                ),
            ],
            options={
                "verbose_name": "空间资源",
                "verbose_name_plural": "空间资源详情",
            },
        ),
        migrations.CreateModel(
            name="SpaceType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建者")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="更新者")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("type_id", models.CharField(max_length=64, unique=True, verbose_name="空间类型英文名称")),
                ("type_name", models.CharField(max_length=64, unique=True, verbose_name="类型中文名称")),
                ("description", models.CharField(blank=True, max_length=128, null=True, verbose_name="类型描述")),
                ("allow_merge", models.BooleanField(default=True, verbose_name="是否可以合并的")),
                ("allow_bind", models.BooleanField(default=True, verbose_name="是否可以绑定资源")),
                (
                    "dimension_fields",
                    bkmonitor.utils.db.fields.JsonField(
                        default=[],
                        help_text="需要的校验的关键字段，格式如['project_id', 'cluster_id', 'namespace']",
                        verbose_name="关键校验字段",
                    ),
                ),
            ],
            options={
                "verbose_name": "空间类型",
                "verbose_name_plural": "空间类型信息",
            },
        ),
        migrations.AddField(
            model_name="datasource",
            name="is_platform_data_id",
            field=models.BooleanField(default=False, help_text="如果为平台级 ID，则认为全量可以访问", verbose_name="是否为平台 ID"),
        ),
        migrations.AlterUniqueTogether(
            name="spaceresource",
            unique_together={("space_type_id", "space_id", "resource_type", "resource_id")},
        ),
        migrations.AlterUniqueTogether(
            name="spacedatasource",
            unique_together={("space_type_id", "space_id", "bk_data_id")},
        ),
        migrations.AlterUniqueTogether(
            name="space",
            unique_together={("space_type_id", "space_id"), ("space_type_id", "space_name")},
        ),
    ]
