# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-07-22 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0123_auto_20220620_2053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resulttableoption",
            name="name",
            field=models.CharField(
                choices=[
                    ("cmdb_level_config", "cmdb_level_config"),
                    ("es_unique_field_list", "es_unique_field_list"),
                    ("group_info_alias", "group_info_alias"),
                    ("dimension_values", "dimension_values"),
                ],
                max_length=128,
                verbose_name="option名称",
            ),
        ),
    ]
