# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-07-26 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0124_auto_20220722_1436"),
        ("metadata", "0123_auto_20220722_0830"),
    ]

    operations = []
