# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-08-03 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0124_auto_20220722_1436"),
    ]

    operations = [
        # 该操作移到0045_auto_20191123_1148.py创建表的初始化操作中。
        # 新增索引操作可能会引起部署超时，量级不大情况下可以不考虑bk_biz_id，bk_data_id的索引。
        # migrations.AlterField(
        #     model_name="eventgroup",
        #     name="bk_biz_id",
        #     field=models.IntegerField(db_index=True, verbose_name="业务ID"),
        # ),
        # migrations.AlterField(
        #     model_name="eventgroup",
        #     name="bk_data_id",
        #     field=models.IntegerField(db_index=True, verbose_name="数据源ID"),
        # ),
        # migrations.AlterField(
        #     model_name="timeseriesgroup",
        #     name="bk_biz_id",
        #     field=models.IntegerField(db_index=True, verbose_name="业务ID"),
        # ),
        # migrations.AlterField(
        #     model_name="timeseriesgroup",
        #     name="bk_data_id",
        #     field=models.IntegerField(db_index=True, verbose_name="数据源ID"),
        # ),
    ]
