# Generated by Django 1.11.23 on 2022-08-15 03:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0125_add_processbeat_metrics"),
    ]

    operations = []
