# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-08-15 03:13
from __future__ import unicode_literals

from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0125_add_processbeat_metrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownsampleByDateFlow",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("space_uid", models.CharField(blank=True, max_length=128, null=True, verbose_name="空间唯一标识")),
                ("table_id", models.CharField(max_length=128, unique=True, verbose_name="结果表名")),
                ("bk_biz_id", models.IntegerField(default=100147, help_text="降精度流程使用的业务", verbose_name="业务 ID")),
                (
                    "project_id",
                    models.IntegerField(default=8259, help_text="数据开发部分使用的项目，项目需要预先在计算平台创建", verbose_name="计算平台项目 ID"),
                ),
                ("hdfs_cluster", models.CharField(default="testOnline", max_length=32, verbose_name="离线计算使用的存储集群")),
                ("hdfs_expire_days", models.IntegerField(default=3, verbose_name="离线计算存储数据的过期天数")),
                (
                    "influxdb_db_name",
                    models.CharField(blank=True, max_length=128, null=True, verbose_name="计算后数据写入 influxdb 的db名称"),
                ),
                (
                    "influxdb_rp_config",
                    bkmonitor.utils.db.fields.JsonField(
                        default={
                            "influxdb_rp_12h": "12h",
                            "influxdb_rp_1h": "1h",
                            "influxdb_rp_1m": "1m",
                            "influxdb_rp_5m": "5m",
                        },
                        verbose_name="RP 配置",
                    ),
                ),
                ("flow_id", models.IntegerField(blank=True, null=True, verbose_name="计算任务的 ID")),
                ("status", models.CharField(default="no-access", max_length=32, verbose_name="计算任务的状态")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("last_modify_time", models.DateTimeField(auto_now=True, verbose_name="最后更新时间")),
            ],
            options={
                "verbose_name": "降精度计算配置",
                "verbose_name_plural": "降精度计算配置",
            },
        ),
    ]
