# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-08-30 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0125_add_processbeat_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="bcsclusterinfo",
            name="bk_cloud_id",
            field=models.IntegerField(default=None, null=True, verbose_name="云区域ID"),
        ),
    ]
