# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-08-30 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0125_add_processbeat_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='influxdbhostinfo',
            name='backup_rate_limit',
            field=models.FloatField(default=40, verbose_name='备份恢复速率限制'),
        ),
        migrations.AddField(
            model_name='influxdbhostinfo',
            name='status',
            field=models.BooleanField(default=False, verbose_name='是否禁用'),
        ),
        migrations.AlterField(
            model_name='resulttableoption',
            name='name',
            field=models.CharField(
                choices=[
                    ('cmdb_level_config', 'cmdb_level_config'),
                    ('es_unique_field_list', 'es_unique_field_list'),
                    ('group_info_alias', 'group_info_alias'),
                    ('dimension_values', 'dimension_values'),
                    ('segmented_query_enable', '分段查询开关'),
                    ('is_split_measurement', '是否为单指标单表'),
                ],
                max_length=128,
                verbose_name='option名称',
            ),
        ),
    ]
