# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-09-01 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0126_add_datalink_stats_data_id'),
        ('metadata', '0126_auto_20220830_1920'),
    ]

    operations = [
    ]
