# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-08-22 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0125_add_processbeat_metrics"),
        ("metadata", "0127_spacestickyinfo"),
    ]

    operations = []
