# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-08-31 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0128_merge_20220822_1630"),
        ("metadata", "0126_add_datalink_stats_data_id"),
    ]

    operations = []
