# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-09-02 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0128_modify_datalink_stats_table_id"),
        ("metadata", "0125_auto_20220803_1803"),
    ]

    operations = []
