# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-09-05 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0129_merge_20220902_1703"),
        ("metadata", "0129_merge_20220831_1554"),
    ]

    operations = []
