# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-09-02 09:03
from __future__ import unicode_literals

from django.db import migrations

from metadata.migration_util import models, add_resulttablefield


def add_system_mem_shared_to_result_table(apps, *args, **kwargs):
    """添加共享内存结果表数据"""
    # 获取APP models
    for model_name in list(models.keys()):
        models[model_name] = apps.get_model("metadata", model_name)
    table_id = "system.mem"
    field_item_list = [
        {"field_name": "shared", "field_type": "int", "unit": "decbytes", "tag": "metric", "description": "共享内存使用量"},
    ]
    user = "system"
    add_resulttablefield(models, table_id, field_item_list, user)


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0129_merge_20220902_1703"),
    ]

    operations = [
        migrations.RunPython(add_system_mem_shared_to_result_table),
    ]
