# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-09-20 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0131_modify_datalink_stats_influxdb_storage_database'),
        ('metadata', '0126_auto_20220830_1649'),
    ]

    operations = []
