# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-09-20 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0133_merge_20220906_2129'),
        ('metadata', '0132_merge_20220920_1441'),
    ]

    operations = []
