# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-09-22 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0133_merge_20220920_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcsclusterinfo',
            name='bk_env',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='配置来源标签'),
        ),
    ]
