# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-09-23 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0133_merge_20220920_1552'),
        ('metadata', '0134_merge_20220920_2100'),
    ]

    operations = []
