# Generated by Django 1.11.23 on 2022-10-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0135_add_hostname_for_system_load"),
    ]

    operations = [
        migrations.AlterField(
            model_name="influxdbhostinfo",
            name="backup_rate_limit",
            field=models.FloatField(default=0, verbose_name="备份恢复速率限制"),
        ),
    ]
