# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-10-18 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0136_merge_20220928_1800'),
        ('metadata', '0135_add_hostname_for_system_load'),
    ]

    operations = []
