# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-11-12 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0136_auto_20221024_1432'),
        ('metadata', '0137_merge_20221018_1507'),
    ]

    operations = []
