# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-11-14 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0138_merge_20221112_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='is_bcs_valid',
            field=models.BooleanField(default=False, verbose_name='BCS 是否可用'),
        ),
        migrations.AlterField(
            model_name='downsamplebydateflow',
            name='hdfs_cluster',
            field=models.CharField(default='testOnline', max_length=32, verbose_name='离线计算使用的存储集群'),
        ),
    ]
