# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-14 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0139_auto_20221114_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='space_type_id',
            field=models.CharField(
                db_index=True,
                default='all',
                help_text='数据源属于的空间类型，允许授权给对应空间类型',
                max_length=64,
                null=True,
                verbose_name='所属的空间类型',
            ),
        ),
    ]
