# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-09 04:03
from __future__ import unicode_literals

import bkmonitor.utils.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0139_auto_20221114_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogGroup',
            fields=[
                ('bk_data_id', models.IntegerField(db_index=True, verbose_name='数据源ID')),
                ('bk_biz_id', models.IntegerField(db_index=True, verbose_name='业务ID')),
                ('table_id', models.CharField(db_index=True, max_length=128, null=True, verbose_name='结果表ID')),
                ('max_rate', models.IntegerField(default=-1, verbose_name='上报速率限制')),
                ('label', models.CharField(default='others', max_length=128, verbose_name='事件标签')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('creator', models.CharField(max_length=255, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_user', models.CharField(max_length=32, verbose_name='最后更新者')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_split_measurement', models.BooleanField(default=False, verbose_name='是否需要单个指标单表存储')),
                ('log_group_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='分组ID')),
                ('log_group_name', models.CharField(db_index=True, max_length=255, verbose_name='日志分组名')),
                ('bk_data_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='上报Token')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogSubscriptionConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_biz_id', models.IntegerField(default=int, verbose_name='业务id')),
                ('log_name', models.CharField(blank=True, max_length=128, verbose_name='日志名称')),
                ('subscription_id', models.IntegerField(default=int, verbose_name='节点管理订阅ID')),
                ('config', bkmonitor.utils.db.fields.JsonField(verbose_name='订阅配置')),
            ],
            options={
                'verbose_name': '自定义日志订阅',
                'verbose_name_plural': '自定义日志订阅',
            },
        ),
        migrations.AlterIndexTogether(
            name='logsubscriptionconfig',
            index_together=set([('bk_biz_id', 'log_name')]),
        ),
    ]
