# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-16 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0140_auto_20221209_1203'),
        ('metadata', '0140_datasource_space_type_id'),
    ]

    operations = []
