# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-01-05 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0140_alter_field_collate'),
        ('metadata', '0141_merge_20221216_1058'),
    ]

    operations = []
