# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-01 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0144_auto_20230224_1432'),
        ('metadata', '0145_add_all_agent_id_host_id_biz_id'),
    ]

    operations = []
