# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-22 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0145_auto_20230301_1640'),
    ]

    operations = [
        migrations.RunSQL("alter table metadata_space modify space_name varchar(256) not null collate utf8_bin;")
    ]
