# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-02 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0145_auto_20230301_1640'),
        ('metadata', '0146_merge_20230301_1936'),
    ]

    operations = []
