# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-24 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0146_update_service_monitor_option'),
        ('metadata', '0146_auto_20230322_1536'),
    ]

    operations = []
