# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-04-11 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0147_merge_20230324_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='influxdbstorage',
            name='vm_table_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='VM 结果表 ID'),
        ),
    ]
