# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-28 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0147_merge_20230324_1100'),
        ('metadata', '0148_auto_20230322_1521'),
    ]

    operations = []
