# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-28 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0149_merge_20230328_1830'),
        ('metadata', '0148_auto_20230321_1657'),
    ]

    operations = []
