# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-04-19 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0150_merge_20230328_1836'),
        ('metadata', '0148_auto_20230411_2004'),
    ]

    operations = []
