# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-05-04 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0149_auto_20230424_1502'),
        ('metadata', '0151_merge_20230419_1451'),
    ]

    operations = []
