# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-05-19 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0153_update_agent_id_host_id_biz_id'),
    ]

    operations = []
