# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-05-10 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0153_update_agent_id_host_id_biz_id'),
        ('metadata', '0150_auto_20230425_1612'),
    ]

    operations = []
