# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-05-24 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0154_merge_20230510_1504'),
        ('metadata', '0154_auto_20230519_1738'),
    ]

    operations = []
