# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-05-24 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0155_merge_20230524_1109'),
        ('metadata', '0155_accessvmrecord'),
    ]

    operations = []
