# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-06-01 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0156_add_icmp_result_table_feild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessvmrecord',
            name='vm_cluster_id',
            field=models.IntegerField(blank=True, help_text='因为查询 vm 集群已经统一，不需要再单独记录', null=True, verbose_name='集群ID'),
        ),
        migrations.AlterField(
            model_name='downsamplebydateflow',
            name='hdfs_cluster',
            field=models.CharField(default='testOnline', max_length=32, verbose_name='离线计算使用的存储集群'),
        ),
        migrations.AlterField(
            model_name='influxdbstorage',
            name='vm_table_id',
            field=models.CharField(
                blank=True,
                default='',
                help_text='此字段废弃，vm 结果表 ID 可以通过 AccessVMRecord 获取',
                max_length=128,
                verbose_name='VM 结果表 ID',
            ),
        ),
    ]
