# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-05-31 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0156_add_icmp_result_table_feild'),
        ('metadata', '0156_merge_20230524_1510'),
    ]

    operations = []
