# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-06-02 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0157_merge_20230531_1737'),
        ('metadata', '0157_auto_20230601_1609'),
    ]

    operations = []
