# Generated by Django 1.11.23 on 2023-06-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0159_auto_20230606_2140"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pingserversubscriptionconfig",
            name="bk_host_id",
            field=models.IntegerField(db_index=True, default=None, null=True, verbose_name="主机ID"),
        ),
    ]
