# Generated by Django 1.11.23 on 2023-06-15 03:38

from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0159_auto_20230606_2140"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusterinfo",
            name="default_settings",
            field=bkmonitor.utils.db.fields.JsonField(default={}, null=True, verbose_name="集群的默认配置"),
        ),
        migrations.AddField(
            model_name="clusterinfo",
            name="label",
            field=models.CharField(default="", max_length=32, null=True, verbose_name="用途标签"),
        ),
        migrations.AlterField(
            model_name="resulttable",
            name="default_storage",
            field=models.CharField(
                choices=[
                    ("influxdb", "influxDB"),
                    ("kafka", "kafka"),
                    ("redis", "redis"),
                    ("elasticsearch", "elasticsearch"),
                    ("argus", "argus"),
                    ("victoria_metrics", "victoria_metrics"),
                ],
                max_length=32,
                verbose_name="默认存储方案",
            ),
        ),
    ]
