# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-06-15 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0160_auto_20230615_1138'),
        ('metadata', '0160_auto_20230615_1551'),
    ]

    operations = []
