# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-06-27 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0163_migrate_custom_report_subscription_config'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customreportsubscription',
            table='custom_report_subscription_config_v2',
        ),
    ]
