# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-06-19 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0164_auto_20230627_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttablefield',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否禁用'),
        ),
    ]
