# Generated by Django 3.2.15 on 2023-07-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0164_auto_20230627_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceVMInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('space_type', models.CharField(max_length=64, verbose_name='空间类型英文名称')),
                ('space_id', models.CharField(max_length=128, verbose_name='空间英文名称')),
                ('vm_cluster_id', models.IntegerField(help_text='关联 clusterinfo 表中存储的 vm 集群信息', verbose_name='集群ID')),
                (
                    'vm_retention_time',
                    models.CharField(blank=True, default='30d', max_length=16, null=True, verbose_name='保存时间'),
                ),
                ('status', models.CharField(blank=True, max_length=16, null=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '空间接入 VM 信息',
                'verbose_name_plural': '空间接入 VM 信息',
            },
        ),
    ]
