# Generated by Django 3.2.15 on 2023-07-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0165_spacevminfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingserversubscriptionconfig',
            name='plugin_name',
            field=models.CharField(default='bkmonitorproxy', max_length=32, verbose_name='插件名称'),
        ),
        migrations.AlterUniqueTogether(
            name='pingserversubscriptionconfig',
            unique_together={('bk_host_id', 'bk_cloud_id', 'ip', 'plugin_name')},
        ),
    ]
