# Generated by Django 3.2.15 on 2023-08-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0166_auto_20230803_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterinfo',
            name='extranet_domain_name',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='集群外网域名'),
        ),
        migrations.AddField(
            model_name='clusterinfo',
            name='extranet_port',
            field=models.IntegerField(default=0, max_length=128, null=True, verbose_name='集群外网端口'),
        ),
    ]
