# Generated by Django 3.2.15 on 2023-08-07 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0165_add_rt_disabled_field'),
        ('metadata', '0167_auto_20230803_2019'),
    ]

    operations = []
