# Generated by Django 3.2.15 on 2023-08-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0166_auto_20230726_1750'),
        ('metadata', '0168_merge_20230807_1125'),
    ]

    operations = []
