# Generated by Django 3.2.15 on 2023-08-08 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0166_datasource_belong_space'),
        ('metadata', '0168_merge_20230807_1125'),
    ]

    operations = []
