# Generated by Django 3.2.15 on 2023-08-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0169_merge_20230808_1154'),
        ('metadata', '0169_merge_20230814_2101'),
    ]

    operations = []
