# Generated by Django 3.2.15 on 2023-08-03 07:45

from django.db import migrations, models

model_dict = {
    "TimeSeriesGroup": None,
    "ResultTableOption": None,
    "BCSClusterInfo": None,
}

NEW_MONITOR_OPTION_VALUE = '["bk_monitor_namespace/bk_monitor_name", "bk_monitor_name"]'
DIMENSION_VALUES = "dimension_values"


def refresh_bcsclusterinfo(apps, schema_editor):
    for model_name in list(model_dict.keys()):
        model_dict[model_name] = apps.get_model("metadata", model_name)

    TimeSeriesGroup = model_dict["TimeSeriesGroup"]
    ResultTableOption = model_dict["ResultTableOption"]
    BCSClusterInfo = model_dict["BCSClusterInfo"]
    data_ids = []
    for cluster in BCSClusterInfo.objects.only("K8sMetricDataID", "CustomMetricDataID"):
        data_ids.extend([cluster.K8sMetricDataID, cluster.CustomMetricDataID])

    table_ids = TimeSeriesGroup.objects.filter(bk_data_id__in=data_ids).values_list("table_id", flat=True)
    ResultTableOption.objects.filter(table_id__in=table_ids, name=DIMENSION_VALUES).update(
        value=NEW_MONITOR_OPTION_VALUE
    )


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0170_merge_20230815_1602'),
    ]

    operations = [
        migrations.RunPython(refresh_bcsclusterinfo),
    ]
