# Generated by Django 3.2.15 on 2023-07-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0170_merge_20230815_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttable',
            name='data_label',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='数据标签'),
        ),
    ]
