# Generated by Django 3.2.15 on 2024-01-23 09:30
from django.db import migrations, models


def add_status_field_if_not_exists(apps, schema_editor):
    """Add the ``status`` field to Essnapshot table if it does not already exist."""
    Essnapshot = apps.get_model("metadata", "Essnapshot")
    table_name = Essnapshot._meta.db_table
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table_name)
    existing_column_names = {column.name for column in description}
    if "status" in existing_column_names:
        # 字段已存在，跳过添加
        print("Field 'status' already exists in table '{}', skipping addition.".format(table_name))
        return
    field = models.CharField(
        blank=True,
        default="running",
        max_length=16,
        null=True,
        verbose_name="快照状态",
    )
    field.set_attributes_from_name("status")
    schema_editor.add_field(Essnapshot, field)


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0170_merge_20230815_1602'),
    ]

    # 禁用事务以支持DDL操作
    atomic = False

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    code=add_status_field_if_not_exists,
                    reverse_code=migrations.RunPython.noop,
                )
            ],
            # state_operations kept empty to avoid re-adding the status field
            state_operations=[
                migrations.AddField(
                    model_name='essnapshot',
                    name='status',
                    field=models.CharField(
                        max_length=16,
                        blank=True,
                        null=True,
                        default='running',
                        verbose_name='快照状态',
                    ),
                )
            ],
        )
    ]
