# Generated by Django 3.2.15 on 2023-08-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0171_resulttable_data_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterinfo',
            name='extranet_port',
            field=models.IntegerField(default=0, null=True, verbose_name='集群外网端口'),
        ),
        migrations.AlterField(
            model_name='resulttableoption',
            name='name',
            field=models.CharField(
                choices=[
                    ('cmdb_level_config', 'cmdb_level_config'),
                    ('es_unique_field_list', 'es_unique_field_list'),
                    ('group_info_alias', 'group_info_alias'),
                    ('dimension_values', 'dimension_values'),
                    ('segmented_query_enable', '分段查询开关'),
                    ('is_split_measurement', '是否为单指标单表'),
                    ('enable_field_black_list', '是否开启指标黑名单'),
                ],
                max_length=128,
                verbose_name='option名称',
            ),
        ),
    ]
