# Generated by Django 3.2.15 on 2025-11-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0171_essnapshot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essnapshot',
            name='table_id',
            field=models.CharField(max_length=128, verbose_name='结果表id'),
        ),
        migrations.AddField(
            model_name='essnapshot',
            name='id',
            field=models.AutoField(primary_key=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='essnapshot',
            unique_together={('table_id', 'target_snapshot_repository_name')},
        ),
    ]
