# Generated by Django 3.2.15 on 2025-11-07 05:58

from django.db import migrations, models


def populate_repository_name(apps, schema_editor):
    """补充历史数据 EsSnapshotRestore 表的 repository_name 字段"""
    EsSnapshotRestore = apps.get_model('metadata', 'EsSnapshotRestore')
    EsSnapshot = apps.get_model('metadata', 'EsSnapshot')

    # 获取所有需要填充的回溯记录
    restores = EsSnapshotRestore.objects.all()
    table_ids = list(restores.values_list('table_id', flat=True))
    snapshots = EsSnapshot.objects.filter(table_id__in=table_ids)
    snapshots_map = {snapshot.table_id: snapshot for snapshot in snapshots}

    for restore in restores:
        if restore.table_id not in snapshots_map:
            continue
        restore.repository_name = snapshots_map[restore.table_id].target_snapshot_repository_name
        restore.save(update_fields=['repository_name'])

def reverse_populate_repository_name(apps, schema_editor):
    """回滚操作：清空 repository_name 字段"""
    EsSnapshotRestore = apps.get_model('metadata', 'EsSnapshotRestore')
    EsSnapshotRestore.objects.all().update(repository_name=None)


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0172_auto_20251104_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='essnapshotrestore',
            name='repository_name',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='repository_name'),
        ),
        # 填充历史数据数据的仓库名
        migrations.RunPython(populate_repository_name, reverse_populate_repository_name),
    ]
