# Generated by Django 3.2.15 on 2023-08-31 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0171_add_bklog_k8s_heartbeat_data_id'),
        ('metadata', '0172_auto_20230821_1440'),
    ]

    operations = []
