# Generated by Django 3.2.15 on 2023-09-04 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0171_refresh_bcsclusterinfo'),
        ('metadata', '0173_merge_20230831_1946'),
    ]

    operations = []
