# Generated by Django 3.2.15 on 2023-11-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0174_merge_20230904_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessvmrecord',
            name='data_type',
            field=models.CharField(choices=[('bcs_cluster_k8s', 'BCS 集群k8s指标'), ('bcs_cluster_custom', 'BCS 集群自定义指标'), ('user_custom', '用户自定义指标'), ('access_vm', '接入 VM 指标')], default='bcs_cluster_k8s', max_length=32, verbose_name='数据类型'),
        ),
        migrations.AlterField(
            model_name='accessvmrecord',
            name='result_table_id',
            field=models.CharField(help_text='结果表ID', max_length=128, verbose_name='结果表ID'),
        ),
    ]
