# Generated by Django 3.2.15 on 2023-11-30 02:36

from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0175_auto_20231102_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterMetric',
            fields=[
                (
                    'metric_name',
                    models.CharField(max_length=512, primary_key=True, serialize=False, verbose_name='指标名称'),
                ),
                ('tags', bkmonitor.utils.db.fields.JsonField(default=[], verbose_name='维度字段列表')),
            ],
            options={
                'verbose_name': '集群指标配置',
                'verbose_name_plural': '集群指标配置',
            },
        ),
    ]
