# Generated by Django 3.2.15 on 2024-01-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0177_add_gather_up_dataid'),
    ]

    operations = [
        migrations.AddField(
            model_name='essnapshot',
            name='status',
            field=models.CharField(blank=True, default='running', max_length=16, null=True, verbose_name='快照状态'),
        ),
    ]
