# Generated by Django 3.2.15 on 2024-01-23 09:30

from django.db import migrations, models, DatabaseError


def add_status_field_if_not_exists(apps, schema_editor):
    try:
        # 尝试添加字段
        Essnapshot = apps.get_model('metadata', 'Essnapshot')
        field = models.CharField(blank=True, default='running', max_length=16, null=True, verbose_name='快照状态')
        field.set_attributes_from_name('status')
        schema_editor.add_field(Essnapshot, field)
        print("字段 'status' 添加成功")
    except DatabaseError as e:
        # 捕获数据库错误，如果是重复字段错误则忽略
        if "Duplicate column name 'status'" in str(e) or "duplicate column name: status" in str(e):
            print("字段 'status' 已存在，跳过添加操作")
        else:
            # 其他数据库错误重新抛出
            raise e


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0177_add_gather_up_dataid'),
    ]

    # 禁用事务以支持DDL操作
    atomic = False

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    code=add_status_field_if_not_exists,
                    reverse_code=migrations.RunPython.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='essnapshot',
                    name='status',
                    field=models.CharField(
                        max_length=16,
                        blank=True,
                        null=True,
                        default='running',
                        verbose_name='快照状态',
                    ),
                )
            ],
        )
    ]

    # operations = [
    #     migrations.RunPython(
    #         code=add_status_field_if_not_exists,
    #         reverse_code=migrations.RunPython.noop,  # 回滚时不做操作
    #     )
    # ]
