# Generated by Django 3.2.15 on 2023-12-20 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0176_add_system_event'),
        ('metadata', '0178_add_gather_up_dataid'),
    ]

    operations = []
