# Generated by Django 3.2.15 on 2024-03-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0178_essnapshot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttablefield',
            name='field_name',
            field=models.CharField(db_collation='utf8_bin', max_length=255, verbose_name='字段名'),
        ),
        migrations.AlterField(
            model_name='resulttablefieldoption',
            name='field_name',
            field=models.CharField(db_collation='utf8_bin', max_length=255, verbose_name='字段名'),
        ),
        migrations.AlterField(
            model_name='timeseriesmetric',
            name='field_name',
            field=models.CharField(db_collation='utf8_bin', max_length=255, verbose_name='自定义时序字段名称'),
        ),
    ]
