# Generated by Django 3.2.15 on 2024-04-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0179_auto_20240326_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='BcsFederalClusterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal_cluster_id', models.CharField(max_length=64, verbose_name='bcs federal cluster id')),
                ('host_cluster_id', models.CharField(max_length=64, verbose_name='host cluster id')),
                ('sub_cluster_id', models.CharField(max_length=64, verbose_name='sub cluster id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('creator', models.CharField(default='system', max_length=32, verbose_name='creator')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('updater', models.CharField(default='system', max_length=32, verbose_name='updater')),
            ],
            options={
                'verbose_name': 'BCS联邦集群信息',
                'verbose_name_plural': 'BCS联邦集群信息',
            },
        ),
    ]
