# Generated by Django 3.2.15 on 2023-12-26 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0177_add_gather_up_dataid'),
        ('metadata', '0179_merge_0176_add_system_event_0178_add_gather_up_dataid'),
    ]

    operations = []
