# Generated by Django 3.2.15 on 2024-04-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0179_auto_20240326_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcsclusterinfo',
            name='status',
            field=models.CharField(default='RUNNING', max_length=50, verbose_name='集群状态'),
        ),
    ]
