# Generated by Django 3.2.15 on 2024-04-19 04:17

from django.db import migrations

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0180_recordrule_resulttableflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordrule',
            name='rule_metrics',
            field=bkmonitor.utils.db.fields.JsonField(default={}, verbose_name='指标转换信息'),
        ),
    ]
