# Generated by Django 3.2.15 on 2024-05-15 04:00

from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0180_alter_bcsclusterinfo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('space_type', models.CharField(max_length=64, verbose_name='空间类型')),
                ('space_id', models.CharField(max_length=128, verbose_name='空间ID')),
                ('table_id', models.CharField(max_length=128, verbose_name='结果表名')),
                ('record_name', models.CharField(max_length=128, verbose_name='预计算名称')),
                ('rule_type', models.CharField(default='prometheus', max_length=32, verbose_name='规则类型')),
                ('rule_config', bkmonitor.utils.db.fields.JsonField(blank=True, null=True, verbose_name='原始规则配置')),
                ('bk_sql_config', bkmonitor.utils.db.fields.JsonField(blank=True, null=True, verbose_name='转换后的SQL配置')),
                ('rule_metrics', bkmonitor.utils.db.fields.JsonField(default={}, verbose_name='指标转换信息')),
                ('src_vm_table_ids', bkmonitor.utils.db.fields.JsonField(default=[], verbose_name='源数据VM结果表列表')),
                ('vm_cluster_id', models.IntegerField(blank=True, null=True, verbose_name='集群ID')),
                ('dst_vm_table_id', models.CharField(help_text='VM 结果表rt', max_length=64, verbose_name='VM 结果表rt')),
                ('status', models.CharField(default='created', max_length=32, verbose_name='状态')),
            ],
            options={
                'verbose_name': '预计算规则',
                'verbose_name_plural': '预计算规则',
            },
        ),
        migrations.CreateModel(
            name='ResultTableFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('table_id', models.CharField(max_length=128, verbose_name='结果表名')),
                ('flow_id', models.IntegerField(default=-1, verbose_name='计算流程ID')),
                ('config', bkmonitor.utils.db.fields.JsonField(blank=True, null=True, verbose_name='计算配置')),
                ('status', models.CharField(default='no-start', max_length=32, verbose_name='计算状态')),
            ],
            options={
                'verbose_name': '结果表计算流程记录',
                'verbose_name_plural': '结果表计算流程记录',
            },
        ),
    ]
