# Generated by Django 3.2.15 on 2024-05-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0181_recordrule_resulttableflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="bcsclusterinfo",
            name="DefaultAppLogDataId",
            field=models.IntegerField(default=0, verbose_name="collector 默认应用 Log DataId (自定义上报提供)"),
        ),
        migrations.AddField(
            model_name="bcsclusterinfo",
            name="DefaultAppMetricDataId",
            field=models.IntegerField(default=0, verbose_name="collector 默认应用 Metric DataId (APM提供)"),
        ),
        migrations.AddField(
            model_name="bcsclusterinfo",
            name="DefaultAppProfileDataId",
            field=models.IntegerField(default=0, verbose_name="collector 默认应用 Profile DataId (APM提供)"),
        ),
        migrations.AddField(
            model_name="bcsclusterinfo",
            name="DefaultAppTraceDataId",
            field=models.IntegerField(default=0, verbose_name="collector 默认应用 Trace DataId (APM提供)"),
        ),
    ]
