# Generated by Django 3.2.15 on 2024-05-23 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0181_recordrule_resulttableflow"),
    ]

    operations = []
