# Generated by Django 3.2.15 on 2024-05-23 07:46

from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0181_recordrule_resulttableflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLinkResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('data_id_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据源名称')),
                ('vm_table_id_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='结果表名称')),
                ('vm_binding_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='vm 存储绑定名称')),
                ('data_bus_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据总线名称')),
            ],
            options={
                'verbose_name': '数据链路资源',
                'verbose_name_plural': '数据链路资源表',
            },
        ),
        migrations.CreateModel(
            name='DataLinkResourceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('kind', models.CharField(max_length=32, verbose_name='资源类型')),
                ('name', models.CharField(max_length=48, verbose_name='资源名称')),
                ('namespace', models.CharField(default='bkmonitor', max_length=64, verbose_name='命名空间')),
                (
                    'value',
                    bkmonitor.utils.db.fields.JsonField(
                        blank=True, help_text='比如针对dataid资源记录申请到的数据源ID', null=True, verbose_name='记录对应的资源信息'
                    ),
                ),
                ('status', models.CharField(default='ok', max_length=32, verbose_name='状态')),
                ('content', bkmonitor.utils.db.fields.JsonField(blank=True, null=True, verbose_name='资源配置')),
            ],
            options={
                'verbose_name': '数据源资源配置',
                'verbose_name_plural': '数据源资源配置表',
            },
        ),
    ]
