# Generated by Django 3.2.15 on 2024-07-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0184_auto_20240611_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='created_from',
            field=models.CharField(default='bkgse', max_length=16, verbose_name='数据源ID来源'),
        ),
    ]
