# Generated by Django 3.2.15 on 2024-08-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0185_datasource_created_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttable',
            name='is_builtin',
            field=models.BooleanField(default=False, verbose_name='是否内置'),
        ),
    ]
