# Generated by Django 3.2.15 on 2024-08-16 06:58

from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0186_resulttable_is_builtin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BcsFederalClusterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('fed_cluster_id', models.CharField(max_length=32, verbose_name='代理集群 ID')),
                ('host_cluster_id', models.CharField(max_length=32, verbose_name='HOST 集群 ID')),
                ('sub_cluster_id', models.CharField(max_length=32, verbose_name='子集群 ID')),
                ('fed_namespaces', bkmonitor.utils.db.fields.JsonField(default=[], verbose_name='命名空间列表')),
                (
                    'fed_buildin_metric_table_id',
                    models.CharField(blank=True, max_length=128, null=True, verbose_name='内置指标结果表'),
                ),
                (
                    'fed_buildin_event_table_id',
                    models.CharField(blank=True, max_length=128, null=True, verbose_name='内置指标结果表'),
                ),
            ],
            options={
                'verbose_name': 'BCS联邦集群拓扑信息',
                'verbose_name_plural': 'BCS联邦集群拓扑信息',
            },
        ),
        migrations.AddField(
            model_name='datalinkresource',
            name='conditional_sink_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='条件节点名称'),
        ),
    ]
