# Generated by Django 3.2.15 on 2024-08-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0187_auto_20240816_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='esstorage',
            name='need_create_index',
            field=models.BooleanField(default=True, verbose_name='是否需要创建索引'),
        ),
    ]
