# Generated by Django 3.2.15 on 2024-09-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0188_esstorage_need_create_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='token',
            field=models.CharField(default='', max_length=256, verbose_name='上报校验token'),
        ),
    ]
