# Generated by Django 3.2.15 on 2024-09-18 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0189_alter_datasource_token'),
        ('metadata', '0189_auto_20240909_1134'),
    ]

    operations = [
    ]
