# Generated by Django 3.2.15 on 2024-10-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0191_auto_20241016_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionalSinkConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(default='bkmonitor', max_length=64, verbose_name='命名空间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('status', models.CharField(max_length=64, verbose_name='状态')),
                ('data_link_name', models.CharField(max_length=64, verbose_name='数据链路名称')),
                ('name', models.CharField(max_length=64, verbose_name='条件处理配置名称')),
            ],
            options={
                'verbose_name': '条件处理配置',
                'verbose_name_plural': '条件处理配置',
            },
        ),
        migrations.CreateModel(
            name='DataBusConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(default='bkmonitor', max_length=64, verbose_name='命名空间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('status', models.CharField(max_length=64, verbose_name='状态')),
                ('data_link_name', models.CharField(max_length=64, verbose_name='数据链路名称')),
                ('name', models.CharField(max_length=64, verbose_name='清洗任务名称')),
                ('data_id_name', models.CharField(max_length=64, verbose_name='关联消费数据源名称')),
            ],
            options={
                'verbose_name': '清洗任务配置',
                'verbose_name_plural': '清洗任务配置',
            },
        ),
        migrations.CreateModel(
            name='DataIdConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(default='bkmonitor', max_length=64, verbose_name='命名空间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('status', models.CharField(max_length=64, verbose_name='状态')),
                ('data_link_name', models.CharField(max_length=64, verbose_name='数据链路名称')),
                ('name', models.CharField(max_length=64, verbose_name='数据源名称')),
            ],
            options={
                'verbose_name': '数据源配置',
                'verbose_name_plural': '数据源配置',
            },
        ),
        migrations.CreateModel(
            name='VMResultTableConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(default='bkmonitor', max_length=64, verbose_name='命名空间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('status', models.CharField(max_length=64, verbose_name='状态')),
                ('data_link_name', models.CharField(max_length=64, verbose_name='数据链路名称')),
                ('name', models.CharField(max_length=64, verbose_name='结果表名称')),
                ('data_type', models.CharField(default='metric', max_length=64, verbose_name='结果表类型')),
            ],
            options={
                'verbose_name': 'VM结果表配置',
                'verbose_name_plural': 'VM结果表配置',
            },
        ),
        migrations.CreateModel(
            name='VMStorageBindingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(default='bkmonitor', max_length=64, verbose_name='命名空间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('status', models.CharField(max_length=64, verbose_name='状态')),
                ('data_link_name', models.CharField(max_length=64, verbose_name='数据链路名称')),
                ('name', models.CharField(max_length=64, verbose_name='存储配置名称')),
                ('vm_cluster_name', models.CharField(max_length=64, verbose_name='VM集群名称')),
            ],
            options={
                'verbose_name': 'VM存储配置',
                'verbose_name_plural': 'VM存储配置',
            },
        ),
    ]
