# Generated by Django 3.2.15 on 2024-10-28 10:18

from django.db import migrations


def update_data_label(apps, schema_editor):
    ResultTable = apps.get_model('metadata', 'ResultTable')
    ResultTable.objects.filter(table_id__in=['process.perf', 'process.port']).update(data_label='process')


class Migration(migrations.Migration):
    dependencies = [
        (
            'metadata',
            '0192_bkbaseresulttable_conditionalsinkconfig_databusconfig_dataidconfig_datalink_vmresulttableconfig_vmst',
        ),
    ]

    operations = [
        migrations.RunPython(update_data_label),
    ]
