# Generated by Django 3.2.15 on 2024-10-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'metadata',
            '0192_conditionalsinkconfig_databusconfig_dataidconfig_vmresulttableconfig_vmstoragebindingconfig',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='BkBaseResultTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_link_name', models.CharField(max_length=255, verbose_name='链路名称')),
                ('bkbase_data_name', models.CharField(max_length=128, verbose_name='计算平台数据源名称')),
                ('bkbase_table_id', models.IntegerField(blank=True, null=True, verbose_name='计算平台结果表ID')),
                (
                    'storage_type',
                    models.CharField(
                        choices=[
                            ('influxdb', 'influxDB'),
                            ('kafka', 'kafka'),
                            ('redis', 'redis'),
                            ('elasticsearch', 'elasticsearch'),
                            ('argus', 'argus'),
                            ('victoria_metrics', 'victoria_metrics'),
                        ],
                        default='victoria_metrics',
                        max_length=32,
                        verbose_name='存储类型',
                    ),
                ),
                ('storage_cluster_id', models.CharField(max_length=32, verbose_name='存储集群ID')),
                ('monitor_table_id', models.CharField(max_length=128, verbose_name='监控平台结果表ID')),
            ],
            options={
                'verbose_name': '接入计算平台记录表',
                'verbose_name_plural': '接入计算平台记录表',
            },
        ),
    ]
