# Generated by Django 3.2.15 on 2024-10-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'metadata',
            '0192_bkbaseresulttable_conditionalsinkconfig_databusconfig_dataidconfig_datalink_vmresulttableconfig_vmst',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalink',
            name='storage_type',
        ),
        migrations.AlterField(
            model_name='bkbaseresulttable',
            name='bkbase_data_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='计算平台数据源名称'),
        ),
    ]
