# Generated by Django 3.2.15 on 2024-10-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0193_process_data_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkbaseresulttable',
            name='bkbase_table_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='计算平台结果表ID'),
        ),
    ]
