# Generated by Django 3.2.15 on 2024-10-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0193_bkbaseresulttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLink',
            fields=[
                (
                    'data_link_name',
                    models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='链路名称'),
                ),
                (
                    'data_link_strategy',
                    models.CharField(
                        choices=[
                            ('bk_standard_v2_time_series', '标准单指标单表时序数据链路'),
                            ('bcs_federal_proxy_time_series', '联邦代理时序数据链路'),
                            ('bcs_federal_subset_time_series', '联邦子集时序数据链路'),
                        ],
                        max_length=255,
                        verbose_name='链路策略',
                    ),
                ),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('storage_type', models.CharField(max_length=255, verbose_name='存储类型')),
            ],
            options={
                'verbose_name': '数据链路',
                'verbose_name_plural': '数据链路',
            },
        ),
    ]
