# Generated by Django 3.2.15 on 2024-10-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0193_auto_20241028_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkbaseresulttable',
            name='bkbase_data_name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='计算平台数据源名称'),
        ),
        migrations.AlterField(
            model_name='bkbaseresulttable',
            name='monitor_table_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='监控平台结果表ID'),
        ),
        migrations.AlterField(
            model_name='bkbaseresulttable',
            name='storage_cluster_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='存储集群ID'),
        ),
    ]
