# Generated by Django 3.2.15 on 2024-10-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0194_alter_bkbaseresulttable_bkbase_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bkbaseresulttable',
            name='bkbase_rt_name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='计算平台结果表名称'),
        ),
    ]
