# Generated by Django 3.2.15 on 2024-11-04 03:39

from django.db import migrations


def update_data_label(apps, schema_editor):
    ResultTable = apps.get_model('metadata', 'ResultTable')
    ResultTable.objects.filter(
        table_id__in=['uptimecheck.udp', 'uptimecheck.icmp', 'uptimecheck.tcp', 'uptimecheck.http']
    ).update(data_label='uptimecheck')


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0195_bkbaseresulttable_bkbase_rt_name'),
    ]

    operations = [
        migrations.RunPython(update_data_label),
    ]
