# Generated by Django 3.2.15 on 2024-11-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0196_uptimecheck_data_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcsfederalclusterinfo',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
    ]
