# Generated by Django 3.2.15 on 2024-11-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0197_bcsfederalclusterinfo_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='esstorage',
            name='archive_index_days',
            field=models.IntegerField(default=0, null=True, verbose_name='索引归档天数'),
        ),
    ]
