# Generated by Django 3.2.15 on 2024-12-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0199_esfieldqueryaliasoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkAppSpaceRecord',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bk_app_code', models.CharField(max_length=255, verbose_name='蓝鲸应用app_code')),
                ('space_uid', models.CharField(max_length=255, verbose_name='空间UID')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('creator', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('updater', models.CharField(blank=True, max_length=255, null=True, verbose_name='更新人')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '蓝鲸应用空间授权记录',
                'verbose_name_plural': '蓝鲸应用空间授权记录',
                'unique_together': {('bk_app_code', 'space_uid')},
            },
        ),
    ]
