# Generated by Django 3.2.15 on 2024-12-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0200_bkappspacerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcsclusterinfo',
            name='is_allow_view_history',
            field=models.BooleanField(default=False, verbose_name='是否允许查看历史数据'),
        ),
    ]
