# Generated by Django 3.2.15 on 2024-12-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0200_bkappspacerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcsclusterinfo',
            name='is_deleted_allow_view',
            field=models.BooleanField(default=False, verbose_name='已下线集群是否允许查看数据'),
        ),
    ]
