# Generated by Django 3.2.15 on 2024-12-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0201_bcsclusterinfo_is_deleted_allow_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='created_from',
            field=models.CharField(db_index=True, default='bkgse', max_length=16, verbose_name='数据源ID来源'),
        ),
    ]
