# Generated by Django 3.2.15 on 2024-12-06 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0202_alter_datasource_created_from'),
        ('metadata', '0202_esfieldqueryaliasoption_path_type'),
    ]

    operations = []
