# Generated by Django 3.2.15 on 2024-12-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0203_merge_20241206_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESStorageClusterRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(db_index=True, max_length=128, verbose_name='采集项结果表名')),
                ('cluster_id', models.BigIntegerField(db_index=True, verbose_name='存储集群ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除/停用')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否是当前最新存储集群')),
                ('creator', models.CharField(max_length=128, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('enable_time', models.DateTimeField(blank=True, null=True, verbose_name='启用时间')),
                ('disable_time', models.DateTimeField(blank=True, null=True, verbose_name='停用时间')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
            ],
            options={
                'unique_together': {('table_id', 'cluster_id', 'enable_time')},
            },
        ),
    ]
