# Generated by Django 3.2.15 on 2024-12-11 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0204_esstorageclusterrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ESStorageClusterRecord',
            new_name='StorageClusterRecord',
        ),
    ]
