# Generated by Django 3.2.15 on 2025-01-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0206_resulttable_bk_biz_id_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordrule',
            name='count_freq',
            field=models.IntegerField(default=60, verbose_name='计算频率(秒)'),
        ),
    ]
