# Generated by Django 3.2.25 on 2025-02-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0207_recordrule_count_freq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttablefield',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='字段描述'),
        ),
    ]
