# Generated by Django 3.2.25 on 2025-03-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0208_alter_resulttablefield_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterinfo',
            name='is_auth',
            field=models.BooleanField(default=False, verbose_name='是否开启鉴权'),
        ),
        migrations.AddField(
            model_name='clusterinfo',
            name='sasl_mechanisms',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='SASL认证机制'),
        ),
        migrations.AddField(
            model_name='clusterinfo',
            name='security_protocol',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='安全协议'),
        ),
    ]
