# Generated by Django 3.2.25 on 2025-03-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0209_auto_20250304_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceRelatedStorageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_type_id', models.CharField(max_length=64, verbose_name='空间类型 ID')),
                ('space_id', models.CharField(help_text='空间类型下唯一', max_length=128, verbose_name='空间ID')),
                (
                    'storage_type',
                    models.CharField(
                        choices=[
                            ('influxdb', 'influxDB'),
                            ('kafka', 'kafka'),
                            ('redis', 'redis'),
                            ('elasticsearch', 'elasticsearch'),
                            ('argus', 'argus'),
                            ('victoria_metrics', 'victoria_metrics'),
                        ],
                        max_length=32,
                        verbose_name='存储类型',
                    ),
                ),
                ('cluster_id', models.IntegerField(help_text='ClusterInfo中的cluster_id', verbose_name='存储集群ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
