# Generated by Django 3.2.25 on 2025-04-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0211_auto_20250326_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceTypeToResultTableFilterAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_type', models.CharField(max_length=64, verbose_name='空间类型')),
                ('table_id', models.CharField(max_length=128, verbose_name='结果表名')),
                ('filter_alias', models.CharField(max_length=128, verbose_name='过滤条件别名')),
                ('status', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'unique_together': {('space_type', 'table_id')},
            },
        ),
    ]
