# Generated by Django 3.2.25 on 2025-04-02 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0212_auto_20250311_1943"),
    ]

    operations = []
