# Generated by Django 3.2.25 on 2025-03-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0211_auto_20250311_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafkastorage',
            name='table_id',
            field=models.CharField(max_length=128, verbose_name='结果表名'),
        ),
        migrations.AlterField(
            model_name='resulttable',
            name='table_id',
            field=models.CharField(db_index=True, max_length=128, verbose_name='结果表名'),
        ),
        migrations.AddField(
            model_name='cmdblevelrecord',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='bk_tenant_id',
            field=models.CharField(db_index=True, default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
        migrations.AddField(
            model_name='datasourceoption',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
        migrations.AddField(
            model_name='datasourceresulttable',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
        migrations.AddField(
            model_name='esfieldqueryaliasoption',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
        migrations.AddField(
            model_name='kafkastorage',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
        migrations.AddField(
            model_name='kafkastorage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
        migrations.AddField(
            model_name='resulttable',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
        migrations.AddField(
            model_name='resulttable',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resulttablefield',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
        migrations.AddField(
            model_name='resulttablefieldoption',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
        migrations.AddField(
            model_name='resulttableoption',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
        migrations.AddField(
            model_name='resulttablerecordformat',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='data_name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='数据源名称'),
        ),
        migrations.AlterUniqueTogether(
            name='cmdblevelrecord',
            unique_together={('source_table_id', 'cmdb_level', 'bk_tenant_id')},
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('data_name', 'bk_tenant_id')},
        ),
        migrations.AlterUniqueTogether(
            name='datasourceresulttable',
            unique_together={('bk_data_id', 'table_id', 'bk_tenant_id')},
        ),
        migrations.AlterUniqueTogether(
            name='kafkastorage',
            unique_together={('table_id', 'bk_tenant_id')},
        ),
        migrations.AlterUniqueTogether(
            name='resulttable',
            unique_together={('table_id', 'bk_tenant_id')},
        ),
        migrations.AlterUniqueTogether(
            name='resulttablefield',
            unique_together={('table_id', 'field_name', 'bk_tenant_id')},
        ),
        migrations.AlterUniqueTogether(
            name='resulttablerecordformat',
            unique_together={('table_id', 'metric', 'dimension_list', 'bk_tenant_id')},
        ),
    ]
