# Generated by Django 3.2.25 on 2025-03-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0211_auto_20250326_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
        migrations.AddField(
            model_name='spacedatasource',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
        migrations.AddField(
            model_name='spaceresource',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
    ]
