# Generated by Django 3.2.25 on 2025-04-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0212_spacetypetoresulttablefilteralias'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='max_future_time_offset',
            field=models.IntegerField(default=-1, verbose_name='上报最大时间偏移'),
        ),
        migrations.AddField(
            model_name='loggroup',
            name='max_future_time_offset',
            field=models.IntegerField(default=-1, verbose_name='上报最大时间偏移'),
        ),
        migrations.AddField(
            model_name='timeseriesgroup',
            name='max_future_time_offset',
            field=models.IntegerField(default=-1, verbose_name='上报最大时间偏移'),
        ),
    ]
