# Generated by Django 3.2.25 on 2025-04-27 11:54

from django.db import migrations, models
import metadata.models.storage


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0213_auto_20250409_1650"),
    ]

    operations = [
        migrations.CreateModel(
            name="DorisStorage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("table_id", models.CharField(max_length=128, verbose_name="结果表ID")),
                ("bk_tenant_id", models.CharField(default="system", max_length=256, null=True, verbose_name="租户ID")),
                ("bkbase_table_id", models.CharField(max_length=128, null=True, verbose_name="bkbase表名")),
                ("source_type", models.CharField(default="log", max_length=32, verbose_name="数据源类型")),
                ("index_set", models.TextField(blank=True, null=True, verbose_name="索引集")),
                (
                    "table_type",
                    models.CharField(default="primary_table", max_length=128, null=True, verbose_name="物理表类型"),
                ),
                ("field_config_mapping", models.TextField(null=True, verbose_name="字段/分词配置")),
                ("expire_days", models.IntegerField(default=30, null=True, verbose_name="过期天数")),
                ("storage_cluster_id", models.IntegerField(verbose_name="存储集群")),
            ],
            options={
                "verbose_name": "Doris存储表",
                "verbose_name_plural": "Doris存储表",
            },
            bases=(models.Model, metadata.models.storage.StorageResultTable),
        ),
        migrations.AlterField(
            model_name="bkbaseresulttable",
            name="storage_type",
            field=models.CharField(
                choices=[
                    ("influxdb", "influxDB"),
                    ("kafka", "kafka"),
                    ("redis", "redis"),
                    ("elasticsearch", "elasticsearch"),
                    ("argus", "argus"),
                    ("victoria_metrics", "victoria_metrics"),
                    ("doris", "doris"),
                ],
                default="victoria_metrics",
                max_length=32,
                verbose_name="存储类型",
            ),
        ),
        migrations.AlterField(
            model_name="resulttable",
            name="default_storage",
            field=models.CharField(
                choices=[
                    ("influxdb", "influxDB"),
                    ("kafka", "kafka"),
                    ("redis", "redis"),
                    ("elasticsearch", "elasticsearch"),
                    ("argus", "argus"),
                    ("victoria_metrics", "victoria_metrics"),
                    ("doris", "doris"),
                ],
                max_length=32,
                verbose_name="默认存储方案",
            ),
        ),
        migrations.AlterField(
            model_name="spacerelatedstorageinfo",
            name="storage_type",
            field=models.CharField(
                choices=[
                    ("influxdb", "influxDB"),
                    ("kafka", "kafka"),
                    ("redis", "redis"),
                    ("elasticsearch", "elasticsearch"),
                    ("argus", "argus"),
                    ("victoria_metrics", "victoria_metrics"),
                    ("doris", "doris"),
                ],
                max_length=32,
                verbose_name="存储类型",
            ),
        ),
    ]
