# Generated by Django 3.2.25 on 2025-03-19 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0213_auto_20250319_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='bk_tenant_id',
        ),
    ]
