# Generated by Django 3.2.25 on 2025-03-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0215_auto_20250321_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='is_tenant_specific_global',
            field=models.BooleanField(default=False, verbose_name='是否为租户下的全局数据源'),
        ),
    ]
