# Generated by Django 3.2.25 on 2025-03-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0216_datasource_is_tenant_specific_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessvmrecord',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
        migrations.AddField(
            model_name='esstorage',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
        migrations.AddField(
            model_name='storageclusterrecord',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
    ]
