# Generated by Django 3.2.25 on 2025-03-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0217_auto_20250327_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='redisstorage',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
    ]
