# Generated by Django 3.2.25 on 2025-03-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0218_redisstorage_bk_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordrule',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
    ]
