# Generated by Django 3.2.25 on 2025-04-16 04:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0213_auto_20250409_1650'),
        ('metadata', '0220_auto_20250410_1609'),
    ]

    operations = []
