# Generated by Django 3.2.25 on 2025-04-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0221_merge_0213_auto_20250409_1650_0220_auto_20250410_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='argusstorage',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
        migrations.AddField(
            model_name='influxdbstorage',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=256, null=True, verbose_name='租户ID'),
        ),
    ]
