# Generated by Django 3.2.25 on 2025-05-12 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0212_auto_20250311_1943"),
        ("metadata", "0214_auto_20250427_1954"),
        ("metadata", "0222_auto_20250416_1427"),
    ]

    operations = []
