# Generated by Django 3.2.25 on 2025-05-15 03:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0215_auto_20250514_1757"),
        ("metadata", "0224_auto_20250512_2100"),
    ]

    operations = []
