# Generated by Django 3.2.25 on 2025-05-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0225_auto_20250326_1534"),
    ]

    operations = [
        migrations.AddField(
            model_name="esstorage",
            name="long_term_storage_settings",
            field=models.TextField(blank=True, null=True, verbose_name="长期存储配置信息"),
        ),
        migrations.AlterField(
            model_name="bkbaseresulttable",
            name="storage_type",
            field=models.CharField(
                choices=[
                    ("influxdb", "influxDB"),
                    ("kafka", "kafka"),
                    ("redis", "redis"),
                    ("elasticsearch", "elasticsearch"),
                    ("argus", "argus"),
                    ("victoria_metrics", "victoria_metrics"),
                    ("doris", "doris"),
                    ("bkdata", "bkdata"),
                ],
                default="victoria_metrics",
                max_length=32,
                verbose_name="存储类型",
            ),
        ),
        migrations.AlterField(
            model_name="resulttable",
            name="default_storage",
            field=models.CharField(
                choices=[
                    ("influxdb", "influxDB"),
                    ("kafka", "kafka"),
                    ("redis", "redis"),
                    ("elasticsearch", "elasticsearch"),
                    ("argus", "argus"),
                    ("victoria_metrics", "victoria_metrics"),
                    ("doris", "doris"),
                    ("bkdata", "bkdata"),
                ],
                max_length=32,
                verbose_name="默认存储方案",
            ),
        ),
        migrations.AlterField(
            model_name="spacerelatedstorageinfo",
            name="storage_type",
            field=models.CharField(
                choices=[
                    ("influxdb", "influxDB"),
                    ("kafka", "kafka"),
                    ("redis", "redis"),
                    ("elasticsearch", "elasticsearch"),
                    ("argus", "argus"),
                    ("victoria_metrics", "victoria_metrics"),
                    ("doris", "doris"),
                    ("bkdata", "bkdata"),
                ],
                max_length=32,
                verbose_name="存储类型",
            ),
        ),
    ]
