# Generated by Django 3.2.25 on 2025-06-03 12:26

from django.db import migrations


def create_system_base_metric_data_source(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0226_auto_20250526_1644"),
    ]

    operations = [
        migrations.RunPython(create_system_base_metric_data_source),
    ]
