# Generated by Django 3.2.25 on 2025-06-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0227_system_base_data_source_init"),
    ]

    operations = [
        migrations.AddField(
            model_name="essnapshot",
            name="bk_tenant_id",
            field=models.CharField(default="system", max_length=256, null=True, verbose_name="租户ID"),
        ),
        migrations.AddField(
            model_name="essnapshotrepository",
            name="bk_tenant_id",
            field=models.CharField(default="system", max_length=256, null=True, verbose_name="租户ID"),
        ),
        migrations.AddField(
            model_name="essnapshotrestore",
            name="bk_tenant_id",
            field=models.CharField(default="system", max_length=256, null=True, verbose_name="租户ID"),
        ),
    ]
