# Generated by Django 3.2.25 on 2025-06-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0228_auto_20250613_1817"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeseriesmetric",
            name="label",
            field=models.CharField(db_index=True, default="", max_length=255, verbose_name="指标监控对象"),
        ),
    ]
