# Generated by Django 3.2.25 on 2025-06-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0229_auto_20250619_1024"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spacedatasource",
            name="bk_data_id",
            field=models.IntegerField(db_index=True, verbose_name="数据源 ID"),
        ),
        migrations.AlterField(
            model_name="spacedatasource",
            name="space_id",
            field=models.CharField(db_index=True, max_length=128, verbose_name="Space 英文名称"),
        ),
    ]
