# Generated by Django 3.2.25 on 2025-07-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0230_auto_20250619_1813"),
    ]

    operations = [
        migrations.AddField(
            model_name="pingserversubscriptionconfig",
            name="bk_tenant_id",
            field=models.CharField(default="system", max_length=128, verbose_name="租户ID"),
        ),
        migrations.AlterUniqueTogether(
            name="pingserversubscriptionconfig",
            unique_together={("bk_host_id", "bk_cloud_id", "ip", "plugin_name", "bk_tenant_id")},
        ),
    ]
