# Generated by Django 3.2.25 on 2025-07-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0231_auto_20250707_2319"),
    ]

    operations = [
        migrations.AddField(
            model_name="bkbaseresulttable",
            name="bk_tenant_id",
            field=models.CharField(default="system", max_length=256, null=True, verbose_name="租户ID"),
        ),
        migrations.AddField(
            model_name="conditionalsinkconfig",
            name="bk_tenant_id",
            field=models.CharField(default="system", max_length=256, null=True, verbose_name="租户ID"),
        ),
        migrations.AddField(
            model_name="databusconfig",
            name="bk_tenant_id",
            field=models.CharField(default="system", max_length=256, null=True, verbose_name="租户ID"),
        ),
        migrations.AddField(
            model_name="dataidconfig",
            name="bk_tenant_id",
            field=models.CharField(default="system", max_length=256, null=True, verbose_name="租户ID"),
        ),
        migrations.AddField(
            model_name="datalink",
            name="bk_tenant_id",
            field=models.CharField(default="system", max_length=256, null=True, verbose_name="租户ID"),
        ),
        migrations.AddField(
            model_name="vmresulttableconfig",
            name="bk_tenant_id",
            field=models.CharField(default="system", max_length=256, null=True, verbose_name="租户ID"),
        ),
        migrations.AddField(
            model_name="vmstoragebindingconfig",
            name="bk_tenant_id",
            field=models.CharField(default="system", max_length=256, null=True, verbose_name="租户ID"),
        ),
        migrations.AlterField(
            model_name="datalink",
            name="data_link_strategy",
            field=models.CharField(
                choices=[
                    ("bk_standard_v2_time_series", "标准单指标单表时序数据链路"),
                    ("bcs_federal_proxy_time_series", "联邦代理时序数据链路"),
                    ("bcs_federal_subset_time_series", "联邦子集时序数据链路"),
                    ("basereport_time_series_v1", "主机基础采集时序数据链路"),
                ],
                max_length=255,
                verbose_name="链路策略",
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="is_tenant_specific_global",
            field=models.BooleanField(default=False, verbose_name="（废弃）是否为租户下的全局数据源"),
        ),
    ]
