# Generated by Django 3.2.25 on 2025-07-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0232_auto_20250715_2037"),
    ]

    operations = [
        migrations.CreateModel(
            name="ESStorageBindingConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("namespace", models.CharField(default="bkmonitor", max_length=64, verbose_name="命名空间")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("last_modify_time", models.DateTimeField(auto_now=True, verbose_name="最后更新时间")),
                ("status", models.CharField(max_length=64, verbose_name="状态")),
                ("data_link_name", models.CharField(max_length=64, verbose_name="数据链路名称")),
                ("bk_biz_id", models.BigIntegerField(default=0, verbose_name="业务ID")),
                ("bk_tenant_id", models.CharField(default="system", max_length=256, null=True, verbose_name="租户ID")),
                ("name", models.CharField(db_index=True, max_length=64, unique=True, verbose_name="存储配置名称")),
                ("es_cluster_name", models.CharField(max_length=64, verbose_name="ES集群名称")),
                ("timezone", models.IntegerField(default=0, verbose_name="时区设置")),
            ],
            options={
                "verbose_name": "ES存储配置",
                "verbose_name_plural": "ES存储配置",
            },
        ),
        migrations.CreateModel(
            name="LogDataBusConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("namespace", models.CharField(default="bkmonitor", max_length=64, verbose_name="命名空间")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("last_modify_time", models.DateTimeField(auto_now=True, verbose_name="最后更新时间")),
                ("status", models.CharField(max_length=64, verbose_name="状态")),
                ("data_link_name", models.CharField(max_length=64, verbose_name="数据链路名称")),
                ("bk_biz_id", models.BigIntegerField(default=0, verbose_name="业务ID")),
                ("bk_tenant_id", models.CharField(default="system", max_length=256, null=True, verbose_name="租户ID")),
                ("name", models.CharField(db_index=True, max_length=64, unique=True, verbose_name="清洗任务名称")),
                ("data_id_name", models.CharField(max_length=64, verbose_name="关联消费数据源名称")),
            ],
            options={
                "verbose_name": "非指标数据清洗总线配置",
                "verbose_name_plural": "非指标数据清洗总线配置",
            },
        ),
        migrations.CreateModel(
            name="LogResultTableConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("namespace", models.CharField(default="bkmonitor", max_length=64, verbose_name="命名空间")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("last_modify_time", models.DateTimeField(auto_now=True, verbose_name="最后更新时间")),
                ("status", models.CharField(max_length=64, verbose_name="状态")),
                ("data_link_name", models.CharField(max_length=64, verbose_name="数据链路名称")),
                ("bk_biz_id", models.BigIntegerField(default=0, verbose_name="业务ID")),
                ("bk_tenant_id", models.CharField(default="system", max_length=256, null=True, verbose_name="租户ID")),
                ("name", models.CharField(db_index=True, max_length=64, unique=True, verbose_name="结果表名称")),
                ("data_type", models.CharField(default="log", max_length=64, verbose_name="结果表类型")),
            ],
            options={
                "verbose_name": "日志结果表配置",
                "verbose_name_plural": "日志结果表配置",
            },
        ),
    ]
