# Generated by Django 3.2.25 on 2025-07-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0232_auto_20250715_2037"),
    ]

    operations = [
        migrations.AddField(
            model_name="logsubscriptionconfig",
            name="bk_tenant_id",
            field=models.CharField(default="system", max_length=128, verbose_name="租户ID"),
        ),
    ]
