# Generated by Django 3.2.25 on 2025-07-22 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0233_esstoragebindingconfig_logdatabusconfig_logresulttableconfig"),
        ("metadata", "0233_logsubscriptionconfig_bk_tenant_id"),
    ]

    operations = []
