# Generated by Django 3.2.25 on 2025-07-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0234_merge_20250722_1451"),
    ]

    operations = [
        migrations.AddField(
            model_name="esstorage",
            name="origin_table_id",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="原始结果表名"),
        ),
        migrations.AlterField(
            model_name="datalink",
            name="data_link_strategy",
            field=models.CharField(
                choices=[
                    ("bk_standard_v2_time_series", "标准单指标单表时序数据链路"),
                    ("bcs_federal_proxy_time_series", "联邦代理时序数据链路"),
                    ("bcs_federal_subset_time_series", "联邦子集时序数据链路"),
                    ("basereport_time_series_v1", "主机基础采集时序数据链路"),
                    ("base_event_v1", "基础事件链路"),
                ],
                max_length=255,
                verbose_name="链路策略",
            ),
        ),
    ]
