# Generated by Django 3.2.25 on 2025-08-07 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0235_auto_20250724_1948"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="space",
            unique_together={("space_type_id", "space_name", "bk_tenant_id"), ("space_type_id", "space_id")},
        ),
    ]
