# Generated by Django 3.2.25 on 2025-08-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0236_auto_20250807_2145"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusterinfo",
            name="bk_tenant_id",
            field=models.CharField(default="system", max_length=64, verbose_name="租户ID"),
        ),
    ]
