# Generated by Django 3.2.25 on 2025-08-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0236_auto_20250807_2145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datalink",
            name="data_link_strategy",
            field=models.CharField(
                choices=[
                    ("bk_standard_v2_time_series", "标准单指标单表时序数据链路"),
                    ("bk_exporter_time_series", "采集插件时序数据链路"),
                    ("bk_standard_time_series", "STANDARD采集插件时序数据链路"),
                    ("bcs_federal_proxy_time_series", "联邦代理时序数据链路"),
                    ("bcs_federal_subset_time_series", "联邦子集时序数据链路"),
                    ("basereport_time_series_v1", "主机基础采集时序数据链路"),
                    ("base_event_v1", "基础事件链路"),
                    ("system_proc_perf", "系统进程性能链路"),
                    ("system_proc_port", "系统进程端口链路"),
                ],
                max_length=255,
                verbose_name="链路策略",
            ),
        ),
    ]
