# Generated by Django 3.2.25 on 2025-08-20 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0237_auto_20250815_0000"),
        ("metadata", "0237_auto_20250818_1926"),
    ]

    operations = []
