# Generated by Django 3.2.25 on 2025-08-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0238_merge_0237_auto_20250815_0000_0237_auto_20250818_1926"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clusterinfo",
            name="cluster_name",
            field=models.CharField(max_length=128, verbose_name="集群名称"),
        ),
        migrations.AlterUniqueTogether(
            name="clusterinfo",
            unique_together={("bk_tenant_id", "cluster_name")},
        ),
    ]
