# Generated by Django 3.2.25 on 2025-09-17 02:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0239_auto_20250821_1456"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="clusterinfo",
            unique_together={("bk_tenant_id", "cluster_type", "cluster_name")},
        ),
    ]
