# Generated by Django 3.2.25 on 2025-10-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0240_auto_20250917_1047"),
    ]

    operations = [
        migrations.CreateModel(
            name="DorisStorageBindingConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("namespace", models.CharField(default="bkmonitor", max_length=64, verbose_name="命名空间")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("last_modify_time", models.DateTimeField(auto_now=True, verbose_name="最后更新时间")),
                ("status", models.CharField(max_length=64, verbose_name="状态")),
                ("data_link_name", models.CharField(max_length=64, verbose_name="数据链路名称")),
                ("bk_biz_id", models.BigIntegerField(verbose_name="业务ID")),
                ("bk_tenant_id", models.CharField(default="system", max_length=256, null=True, verbose_name="租户ID")),
                (
                    "name",
                    models.CharField(db_index=True, max_length=64, unique=True, verbose_name="Doris存储绑定配置名称"),
                ),
            ],
            options={
                "verbose_name": "Doris存储绑定配置",
                "verbose_name_plural": "Doris存储绑定配置",
            },
        ),
        migrations.AlterField(
            model_name="conditionalsinkconfig",
            name="bk_biz_id",
            field=models.BigIntegerField(verbose_name="业务ID"),
        ),
        migrations.AlterField(
            model_name="databusconfig",
            name="bk_biz_id",
            field=models.BigIntegerField(verbose_name="业务ID"),
        ),
        migrations.AlterField(
            model_name="dataidconfig",
            name="bk_biz_id",
            field=models.BigIntegerField(verbose_name="业务ID"),
        ),
        migrations.AlterField(
            model_name="datalink",
            name="data_link_strategy",
            field=models.CharField(
                choices=[
                    ("bk_standard_v2_event", "标准自定义事件链路"),
                    ("bk_standard_v2_time_series", "标准单指标单表时序数据链路"),
                    ("bk_exporter_time_series", "采集插件时序数据链路"),
                    ("bk_standard_time_series", "STANDARD采集插件时序数据链路"),
                    ("bcs_federal_proxy_time_series", "联邦代理时序数据链路"),
                    ("bcs_federal_subset_time_series", "联邦子集时序数据链路"),
                    ("basereport_time_series_v1", "主机基础采集时序数据链路"),
                    ("base_event_v1", "基础事件链路"),
                    ("system_proc_perf", "系统进程性能链路"),
                    ("system_proc_port", "系统进程端口链路"),
                    ("bk_log", "日志链路"),
                ],
                max_length=255,
                verbose_name="链路策略",
            ),
        ),
        migrations.AlterField(
            model_name="esstoragebindingconfig",
            name="bk_biz_id",
            field=models.BigIntegerField(verbose_name="业务ID"),
        ),
        migrations.AlterField(
            model_name="logdatabusconfig",
            name="bk_biz_id",
            field=models.BigIntegerField(verbose_name="业务ID"),
        ),
        migrations.AlterField(
            model_name="logresulttableconfig",
            name="bk_biz_id",
            field=models.BigIntegerField(verbose_name="业务ID"),
        ),
        migrations.AlterField(
            model_name="resulttableconfig",
            name="bk_biz_id",
            field=models.BigIntegerField(verbose_name="业务ID"),
        ),
        migrations.AlterField(
            model_name="vmstoragebindingconfig",
            name="bk_biz_id",
            field=models.BigIntegerField(verbose_name="业务ID"),
        ),
        migrations.AlterUniqueTogether(
            name="conditionalsinkconfig",
            unique_together={("bk_tenant_id", "namespace", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="databusconfig",
            unique_together={("bk_tenant_id", "namespace", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="dataidconfig",
            unique_together={("bk_tenant_id", "namespace", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="dorisstoragebindingconfig",
            unique_together={("bk_tenant_id", "namespace", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="logresulttableconfig",
            unique_together={("bk_tenant_id", "namespace", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="resulttableconfig",
            unique_together={("bk_tenant_id", "namespace", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="vmstoragebindingconfig",
            unique_together={("bk_tenant_id", "namespace", "name")},
        ),
    ]
