# Generated by Django 3.2.25 on 2025-10-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0242_merge_datalink_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="is_global",
            field=models.BooleanField(default=False, verbose_name="跨业务管理可用"),
        ),
    ]
