# Generated by Django 3.2.25 on 2025-11-05 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0243_space_is_global"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomRelationStatus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建者")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="更新者")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name="唯一标识符"
                    ),
                ),
                (
                    "generation",
                    models.BigIntegerField(default=1, help_text="跟踪资源规格变更次数", verbose_name="世代号"),
                ),
                ("namespace", models.CharField(db_index=True, max_length=128, verbose_name="命名空间")),
                ("name", models.CharField(max_length=128, verbose_name="资源名称")),
                ("labels", models.JSONField(default=dict, verbose_name="资源标签")),
                ("from_resource", models.CharField(max_length=128, verbose_name="源资源")),
                ("to_resource", models.CharField(max_length=128, verbose_name="目标资源")),
            ],
            options={
                "verbose_name": "自定义关联关系状态",
                "verbose_name_plural": "自定义关联关系状态",
                "unique_together": {("namespace", "name")},
            },
        ),
    ]
