# Generated by Django 3.2.25 on 2025-11-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0244_customrelationstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusterinfo",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="集群显示名称"),
        ),
        migrations.AlterField(
            model_name="clusterinfo",
            name="cluster_name",
            field=models.CharField(max_length=128, verbose_name="集群英文名"),
        ),
    ]
