# Generated by Django 3.2.25 on 2025-11-21 07:10

from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0244_customrelationstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusterinfo",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="集群显示名称"),
        ),
        migrations.AlterField(
            model_name="clusterinfo",
            name="cluster_name",
            field=models.CharField(max_length=128, verbose_name="集群英文名"),
        ),
        migrations.AddField(
            model_name="clusterinfo",
            name="registered_to_bkbase",
            field=models.BooleanField(default=False, verbose_name="是否已经注册到bkbase平台"),
        ),
        migrations.CreateModel(
            name="ClusterConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_tenant_id", models.CharField(max_length=255, verbose_name="租户ID")),
                ("namespace", models.CharField(max_length=255, verbose_name="命名空间")),
                ("name", models.CharField(max_length=255, verbose_name="集群名称")),
                ("kind", models.CharField(max_length=255, verbose_name="集群类型")),
                (
                    "origin_config",
                    bkmonitor.utils.db.fields.SymmetricJsonField(default=dict, verbose_name="原始配置"),
                ),
            ],
            options={
                "verbose_name": "集群配置",
                "verbose_name_plural": "集群配置",
                "unique_together": {("bk_tenant_id", "namespace", "kind", "name")},
            },
        ),
    ]
