# Generated by Django 3.2.25 on 2025-11-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0245_auto_20251118_1452"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeseriesgroup",
            name="metric_group_dimensions",
            field=models.JSONField(default=[], verbose_name="指标分组的维度key配置"),
        ),
    ]
