# Generated by Django 3.2.25 on 2025-11-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0246_timeseriesgroup_metric_group_dimensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeseriesscope",
            name="create_from",
            field=models.CharField(
                choices=[("data", "数据自动创建"), ("user", "用户手动创建")],
                db_index=True,
                default="data",
                max_length=10,
                verbose_name="创建来源",
            ),
        ),
        migrations.AlterField(
            model_name="timeseriesmetric",
            name="field_scope",
            field=models.CharField(
                db_collation="utf8_bin", default="default", max_length=255, verbose_name="指标字段数据分组名"
            ),
        ),
    ]
