# Generated by Django 3.2.25 on 2025-12-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0246_migrate_cluster_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeseriesmetric",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, help_text="指标是否在计算服务中活跃", verbose_name="是否活跃"
            ),
        ),
    ]
