# Generated by Django 3.2.25 on 2026-01-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0246_migrate_cluster_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="databusconfig",
            name="bk_data_id",
            field=models.IntegerField(default=0, verbose_name="数据源ID"),
        ),
        migrations.AddField(
            model_name="dataidconfig",
            name="bk_data_id",
            field=models.IntegerField(default=0, verbose_name="数据源ID"),
        ),
        migrations.AddField(
            model_name="datalink",
            name="bk_data_id",
            field=models.IntegerField(default=0, verbose_name="关联数据源ID"),
        ),
        migrations.AddField(
            model_name="datalink",
            name="table_ids",
            field=models.JSONField(default=list, verbose_name="关联结果表ID列表"),
        ),
        migrations.AddField(
            model_name="dorisstoragebindingconfig",
            name="table_id",
            field=models.CharField(default="", max_length=255, verbose_name="结果表ID"),
        ),
        migrations.AddField(
            model_name="esstoragebindingconfig",
            name="table_id",
            field=models.CharField(default="", max_length=255, verbose_name="结果表ID"),
        ),
        migrations.AddField(
            model_name="resulttableconfig",
            name="table_id",
            field=models.CharField(default="", max_length=255, verbose_name="结果表ID"),
        ),
        migrations.AddField(
            model_name="vmstoragebindingconfig",
            name="table_id",
            field=models.CharField(default="", max_length=255, verbose_name="结果表ID"),
        ),
    ]
