# Generated by Django 3.2.25 on 2025-12-03 09:16

from django.db import migrations, models
from django.db.models import Min


def backfill_metric_create_time(apps, schema_editor):
    """回填 TimeSeriesMetric 的创建时间"""
    TimeSeriesMetric = apps.get_model("metadata", "TimeSeriesMetric")
    CustomTSField = apps.get_model("monitor_web", "CustomTSField")

    # 构建映射：(group_id, field_name) -> create_time
    metric_create_time_map = {}
    for field in (
        CustomTSField.objects.filter(
            type="metric",  # CustomTSField.MetricType.METRIC
            create_time__isnull=False,
        )
        .values("time_series_group_id", "name")
        .annotate(earliest_create_time=Min("create_time"))
    ):
        key = (field["time_series_group_id"], field["name"])
        metric_create_time_map[key] = field["earliest_create_time"]

    # 查询需要更新的记录
    metrics_to_update = TimeSeriesMetric.objects.filter(create_time__isnull=True)
    total_count = metrics_to_update.count()

    if total_count == 0:
        return

    # 批量更新
    batch_size = 500
    updated_count = 0
    batch_records = []

    for metric in metrics_to_update.iterator(chunk_size=batch_size):
        key = (metric.group_id, metric.field_name)
        if key in metric_create_time_map:
            metric.create_time = metric_create_time_map[key]
            batch_records.append(metric)

            if len(batch_records) >= batch_size:
                TimeSeriesMetric.objects.bulk_update(batch_records, ["create_time"], batch_size=batch_size)
                updated_count += len(batch_records)
                batch_records = []

    # 更新剩余记录
    if batch_records:
        TimeSeriesMetric.objects.bulk_update(batch_records, ["create_time"], batch_size=batch_size)
        updated_count += len(batch_records)


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0247_auto_20251125_1811"),
        ("monitor_web", "__latest__"),  # 依赖 monitor_web 应用的 CustomTSField 模型
    ]

    operations = [
        migrations.AddField(
            model_name="timeseriesmetric",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="创建时间"),
        ),
        migrations.RunPython(backfill_metric_create_time, reverse_code=migrations.RunPython.noop),
    ]
