# Generated by Django 3.2.25 on 2025-12-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0247_add_custom_time_series_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeseriesgroup",
            name="metric_group_dimensions",
            field=models.JSONField(default=dict, verbose_name="指标分组的维度key配置"),
        ),
    ]
