# Generated by Django 3.2.25 on 2026-01-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0247_timeseriesmetric_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="databusconfig",
            name="bk_data_id",
            field=models.IntegerField(default=0, verbose_name="数据源ID"),
        ),
        migrations.AddField(
            model_name="dataidconfig",
            name="bk_data_id",
            field=models.IntegerField(default=0, verbose_name="数据源ID"),
        ),
        migrations.AddField(
            model_name="datalink",
            name="bk_data_id",
            field=models.IntegerField(default=0, verbose_name="关联数据源ID"),
        ),
        migrations.AddField(
            model_name="datalink",
            name="table_ids",
            field=models.JSONField(default=list, verbose_name="关联结果表ID列表"),
        ),
        migrations.AddField(
            model_name="dorisstoragebindingconfig",
            name="table_id",
            field=models.CharField(default="", max_length=255, verbose_name="结果表ID"),
        ),
        migrations.AddField(
            model_name="esstoragebindingconfig",
            name="table_id",
            field=models.CharField(default="", max_length=255, verbose_name="结果表ID"),
        ),
        migrations.AddField(
            model_name="resulttableconfig",
            name="table_id",
            field=models.CharField(default="", max_length=255, verbose_name="结果表ID"),
        ),
        migrations.AddField(
            model_name="vmstoragebindingconfig",
            name="table_id",
            field=models.CharField(default="", max_length=255, verbose_name="结果表ID"),
        ),
        migrations.AlterField(
            model_name="conditionalsinkconfig",
            name="name",
            field=models.CharField(db_index=True, max_length=64, verbose_name="条件处理配置名称"),
        ),
        migrations.AlterField(
            model_name="databusconfig",
            name="name",
            field=models.CharField(db_index=True, max_length=64, verbose_name="清洗任务名称"),
        ),
        migrations.AlterField(
            model_name="dataidconfig",
            name="name",
            field=models.CharField(db_index=True, max_length=64, verbose_name="数据源名称"),
        ),
        migrations.AlterField(
            model_name="dorisstoragebindingconfig",
            name="name",
            field=models.CharField(db_index=True, max_length=64, verbose_name="Doris存储绑定配置名称"),
        ),
        migrations.AlterField(
            model_name="esstoragebindingconfig",
            name="name",
            field=models.CharField(db_index=True, max_length=64, verbose_name="存储配置名称"),
        ),
        migrations.AlterField(
            model_name="eventgroup",
            name="status",
            field=models.CharField(
                choices=[("normal", "正常"), ("sleep", "休眠")], default="normal", max_length=16, verbose_name="状态"
            ),
        ),
        migrations.AlterField(
            model_name="resulttableconfig",
            name="name",
            field=models.CharField(db_index=True, max_length=64, verbose_name="结果表名称"),
        ),
        migrations.AlterField(
            model_name="timeseriesmetric",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, help_text="指标是否活跃", verbose_name="是否活跃"),
        ),
        migrations.AlterField(
            model_name="vmstoragebindingconfig",
            name="name",
            field=models.CharField(db_index=True, max_length=64, verbose_name="存储配置名称"),
        ),
    ]
