# Generated by Django 3.2.25 on 2026-02-02 00:00

import logging

from django.db import migrations

logger = logging.getLogger("metadata.migrations")


def dedupe_esfield_query_alias_option(apps, schema_editor):
    """清理重复的 ES 字段别名配置（可重入）。

    说明：
        - is_deleted=True 的记录直接硬删除。
        - is_deleted=False 的重复记录只做软删除，避免误删。
        - 多次执行结果一致，可安全重入。

    Args:
        apps: Django migration apps registry。
        schema_editor: Django schema editor。
    """
    model = apps.get_model("metadata", "ESFieldQueryAliasOption")
    queryset = model.objects.all().order_by(
        "table_id",
        "bk_tenant_id",
        "query_alias",
        "-update_time",
        "-id",
    )
    seen_keys: set[tuple[str, str, str]] = set()
    delete_ids: list[int] = []
    soft_delete_ids: list[int] = []

    for record in queryset.iterator(chunk_size=1000):
        # 已软删除记录直接硬删除。
        if record.is_deleted:
            logger.info(
                "dedupe_esfield_query_alias_option: hard delete soft-deleted record id=%s table_id=%s bk_tenant_id=%s query_alias=%s field_path=%s",
                record.pk,
                record.table_id,
                record.bk_tenant_id,
                record.query_alias,
                record.field_path,
            )
            delete_ids.append(record.pk)
            continue
        # 相同别名仅保留最新一条（排序已保证先遇到的是最新）。
        key = (record.table_id, record.bk_tenant_id, record.query_alias)
        if key in seen_keys:
            logger.info(
                "dedupe_esfield_query_alias_option: soft delete duplicated record id=%s table_id=%s bk_tenant_id=%s query_alias=%s field_path=%s",
                record.pk,
                record.table_id,
                record.bk_tenant_id,
                record.query_alias,
                record.field_path,
            )
            soft_delete_ids.append(record.pk)
            continue
        seen_keys.add(key)

    if delete_ids:
        model.objects.filter(id__in=delete_ids).delete()
    if soft_delete_ids:
        model.objects.filter(id__in=soft_delete_ids).update(is_deleted=True)


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0248_auto_20260119_0334"),
    ]

    operations = [
        migrations.RunPython(dedupe_esfield_query_alias_option, reverse_code=migrations.RunPython.noop),
    ]
