# Generated by Django 3.2.25 on 2026-02-02 00:00

from django.db import migrations


def dedupe_esfield_query_alias_option(apps, schema_editor):
    """硬删除重复的 ES 字段别名配置（可重入）。

    说明：
        - 直接删除 is_deleted=True 的记录，避免历史软删除残留影响唯一约束。
        - 同一 (table_id, bk_tenant_id, query_alias) 只保留最新一条。
        - 多次执行结果一致，可安全重入。

    Args:
        apps: Django migration apps registry。
        schema_editor: Django schema editor。
    """
    model = apps.get_model("metadata", "ESFieldQueryAliasOption")
    queryset = model.objects.all().order_by(
        "table_id",
        "bk_tenant_id",
        "query_alias",
        "-update_time",
        "-id",
    )
    seen_keys: set[tuple[str, str, str]] = set()
    delete_ids: list[int] = []

    for record in queryset.iterator(chunk_size=1000):
        # 软删除记录直接清理，避免污染唯一键约束。
        if record.is_deleted:
            delete_ids.append(record.pk)
            if len(delete_ids) >= 1000:
                model.objects.filter(id__in=delete_ids).delete()
                delete_ids = []
            continue
        # 相同别名仅保留最新一条（排序已保证先遇到的是最新）。
        key = (record.table_id, record.bk_tenant_id, record.query_alias)
        if key in seen_keys:
            delete_ids.append(record.pk)
            if len(delete_ids) >= 1000:
                model.objects.filter(id__in=delete_ids).delete()
                delete_ids = []
            continue
        seen_keys.add(key)

    if delete_ids:
        model.objects.filter(id__in=delete_ids).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0248_auto_20260119_0334"),
    ]

    operations = [
        migrations.RunPython(dedupe_esfield_query_alias_option, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="esfieldqueryaliasoption",
            unique_together={("table_id", "bk_tenant_id", "query_alias")},
        ),
    ]
