# Generated by Django 4.2.27 on 2026-03-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0173_essnapshotrestore_repository_name'),
        ('metadata', '0248_auto_20260119_0334'),
    ]

    operations = [
    ]
