# Generated by Django 3.2.25 on 2025-12-08 01:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0246_migrate_cluster_name"),
        ("metadata", "0248_timeseriesmetric_create_time"),
    ]

    operations = []
