# Generated by Django 3.2.25 on 2025-12-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0248_auto_20260119_0334"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeseriesgroup",
            name="metric_group_dimensions",
            field=models.JSONField(default=list, verbose_name="指标分组的维度key配置"),
        ),
        migrations.AddField(
            model_name="timeseriesmetric",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="创建时间"),
        ),
        migrations.AddField(
            model_name="timeseriesmetric",
            name="field_config",
            field=models.JSONField(default=dict, verbose_name="字段其他配置"),
        ),
        migrations.AddField(
            model_name="timeseriesmetric",
            name="field_scope",
            field=models.CharField(
                db_collation="utf8_bin", default="default", max_length=255, verbose_name="指标字段数据分组名"
            ),
        ),
        migrations.AddField(
            model_name="timeseriesmetric",
            name="scope_id",
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name="时序分组ID"),
        ),
        migrations.AlterField(
            model_name="timeseriesmetric",
            name="field_id",
            field=models.AutoField(primary_key=True, serialize=False, verbose_name="字段ID"),
        ),
        migrations.AlterField(
            model_name="timeseriesmetric",
            name="field_name",
            field=models.CharField(db_collation="utf8_bin", max_length=255, verbose_name="指标字段名称"),
        ),
        migrations.AlterField(
            model_name="timeseriesmetric",
            name="group_id",
            field=models.IntegerField(db_index=True, verbose_name="自定义时序数据源ID"),
        ),
        migrations.AlterUniqueTogether(
            name="timeseriesmetric",
            unique_together={("group_id", "field_scope", "field_name")},
        ),
        migrations.CreateModel(
            name="TimeSeriesScope",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group_id", models.IntegerField(db_index=True, verbose_name="自定义时序数据源ID")),
                ("scope_name", models.CharField(db_collation="utf8_bin", max_length=255, verbose_name="指标分组名")),
                ("dimension_config", models.JSONField(default={}, verbose_name="分组下的维度配置")),
                ("auto_rules", models.JSONField(default=[], verbose_name="自动分组的匹配规则列表")),
                (
                    "create_from",
                    models.CharField(
                        choices=[("data", "数据自动创建"), ("user", "用户手动创建"), ("default", "默认分组")],
                        db_index=True,
                        default="data",
                        max_length=10,
                        verbose_name="创建来源",
                    ),
                ),
                ("last_modify_time", models.DateTimeField(auto_now=True, verbose_name="最后更新时间")),
            ],
            options={
                "verbose_name": "自定义时序数据分组记录",
                "verbose_name_plural": "自定义时序数据分组记录表",
                "unique_together": {("group_id", "scope_name")},
            },
        ),
        migrations.RunSQL(
            sql=[
                # 为 TimeSeriesMetric 表的 field_scope 字段设置默认值
                "ALTER TABLE metadata_timeseriesmetric ALTER COLUMN field_scope SET DEFAULT 'default'",
                # 为已存在的记录更新 field_scope 字段
                "UPDATE metadata_timeseriesmetric SET field_scope = 'default' WHERE field_scope IS NULL OR field_scope = ''",
                # 为已存在的记录更新 field_config 字段 (JSON类型,MySQL不支持设置默认值)
                "UPDATE metadata_timeseriesmetric SET field_config = '{}' WHERE field_config IS NULL",
                # 为已存在的记录更新 metric_group_dimensions 字段 (JSON类型,MySQL不支持设置默认值)
                "UPDATE metadata_timeseriesgroup SET metric_group_dimensions = '[]' WHERE metric_group_dimensions IS NULL",
                # 为 TimeSeriesScope 表的 create_from 字段设置默认值
                "ALTER TABLE metadata_timeseriesscope ALTER COLUMN create_from SET DEFAULT 'data'",
            ],
            reverse_sql=[
                "ALTER TABLE metadata_timeseriesmetric ALTER COLUMN field_scope DROP DEFAULT",
                "ALTER TABLE metadata_timeseriesscope ALTER COLUMN create_from DROP DEFAULT",
            ],
        ),
    ]
