# Generated by Django 4.2.27 on 2026-02-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0249_esfieldqueryaliasoption_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="databusconfig",
            name="sink_names",
            field=models.JSONField(default=list, help_text="格式为kind:name，便于检索", verbose_name="处理配置列表"),
        ),
        migrations.AddField(
            model_name="dorisstoragebindingconfig",
            name="bkbase_result_table_name",
            field=models.CharField(default="", max_length=255, verbose_name="BKBase结果表名称"),
        ),
        migrations.AddField(
            model_name="dorisstoragebindingconfig",
            name="doris_cluster_name",
            field=models.CharField(default="", max_length=255, verbose_name="Doris集群名称"),
        ),
        migrations.AddField(
            model_name="esstoragebindingconfig",
            name="bkbase_result_table_name",
            field=models.CharField(default="", max_length=255, verbose_name="BKBase结果表名称"),
        ),
        migrations.AddField(
            model_name="resulttableconfig",
            name="bkbase_table_id",
            field=models.CharField(default="", max_length=255, verbose_name="BKBase结果表ID"),
        ),
        migrations.AddField(
            model_name="vmstoragebindingconfig",
            name="bkbase_result_table_name",
            field=models.CharField(default="", max_length=255, verbose_name="BKBase结果表名称"),
        ),
        migrations.AlterField(
            model_name="conditionalsinkconfig",
            name="data_link_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="数据链路名称"),
        ),
        migrations.AlterField(
            model_name="databusconfig",
            name="data_link_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="数据链路名称"),
        ),
        migrations.AlterField(
            model_name="dataidconfig",
            name="data_link_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="数据链路名称"),
        ),
        migrations.AlterField(
            model_name="dorisstoragebindingconfig",
            name="data_link_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="数据链路名称"),
        ),
        migrations.AlterField(
            model_name="esfieldqueryaliasoption",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除(已废弃)"),
        ),
        migrations.AlterField(
            model_name="esstoragebindingconfig",
            name="data_link_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="数据链路名称"),
        ),
        migrations.AlterField(
            model_name="logdatabusconfig",
            name="data_link_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="数据链路名称"),
        ),
        migrations.AlterField(
            model_name="logresulttableconfig",
            name="data_link_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="数据链路名称"),
        ),
        migrations.AlterField(
            model_name="resulttableconfig",
            name="data_link_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="数据链路名称"),
        ),
        migrations.AlterField(
            model_name="resulttableoption",
            name="name",
            field=models.CharField(
                choices=[
                    ("cmdb_level_config", "cmdb_level_config"),
                    ("es_unique_field_list", "es_unique_field_list"),
                    ("group_info_alias", "group_info_alias"),
                    ("dimension_values", "dimension_values"),
                    ("segmented_query_enable", "分段查询开关"),
                    ("is_split_measurement", "是否为单指标单表"),
                    ("enable_field_black_list", "是否开启指标黑名单"),
                    ("binding_bcs_cluster_id", "绑定BCS集群ID"),
                ],
                max_length=128,
                verbose_name="option名称",
            ),
        ),
        migrations.AlterField(
            model_name="vmstoragebindingconfig",
            name="data_link_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="数据链路名称"),
        ),
    ]
