# Generated by Django 3.2.25 on 2025-12-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0249_merge_20251208_0938"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeseriesscope",
            name="manual_list",
        ),
        migrations.AddField(
            model_name="timeseriesmetric",
            name="scope_id",
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name="时序分组ID"),
        ),
    ]
