# Generated by Django 3.2.25 on 2026-02-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0173_essnapshotrestore_repository_name'),
        ('metadata', '0249_esfieldqueryaliasoption_unique'),
    ]

    operations = [
    ]
