# Generated by Django 3.2.25 on 2025-12-09 04:00

import logging
import time

from django.db import migrations

logger = logging.getLogger("metadata")

METRIC_TYPE_METRIC = "metric"
METRIC_TYPE_DIMENSION = "dimension"
DEFAULT_DATA_SCOPE_NAME = "default"
METRIC_CONFIG_FIELDS = ["alias", "unit", "hidden", "aggregate_method", "function", "interval", "disabled"]
CREATE_FROM_DEFAULT = "default"
CREATE_FROM_USER = "user"

# 批处理配置
BULK_BATCH_SIZE = 500  # bulk_create 的批次大小


def migrate_custom_ts_field_to_time_series(apps, schema_editor):
    """将数据从 CustomTSField 迁移到 TimeSeriesMetric 和 TimeSeriesScope"""

    # 获取模型
    CustomTSTable = apps.get_model("monitor_web", "CustomTSTable")
    CustomTSField = apps.get_model("monitor_web", "CustomTSField")
    CustomTSGroupingRule = apps.get_model("monitor_web", "CustomTSGroupingRule")

    # 统计信息
    stats = {
        "total_groups": 0,
        "skipped_groups": 0,
        "processed_groups": 0,
        "scopes_created": 0,
        "scopes_updated": 0,
        "metrics_created": 0,
        "metrics_updated": 0,
    }

    migration_start = time.time()

    # 获取所有 (bk_tenant_id, time_series_group_id) 组合,使用 values_list 减少内存
    ts_table_list = list(
        CustomTSTable.objects.values_list("bk_tenant_id", "time_series_group_id", "table_id").distinct()
    )
    stats["total_groups"] = len(ts_table_list)

    logger.info(f"[迁移开始] 找到 {stats['total_groups']} 个 CustomTSTable")

    # 逐个处理每个 CustomTSTable
    for idx, (bk_tenant_id, group_id, table_id) in enumerate(ts_table_list, 1):
        group_start = time.time()

        try:
            # 只加载当前 group 的 CustomTSField 数据,使用 values 减少内存
            custom_fields = list(
                CustomTSField.objects.filter(time_series_group_id=group_id).values(
                    "id", "name", "type", "description", "config", "disabled", "create_time", "update_time"
                )
            )

            if not custom_fields:
                logger.warning(
                    f"[跳过 {idx}/{stats['total_groups']}] Group {group_id} (table_id={table_id}): 没有找到字段数据"
                )
                stats["skipped_groups"] += 1
                continue

            metric_fields = [f for f in custom_fields if f.get("type") == METRIC_TYPE_METRIC]
            dimension_fields = [f for f in custom_fields if f.get("type") == METRIC_TYPE_DIMENSION]

            logger.info(
                f"[处理中 {idx}/{stats['total_groups']}] Group {group_id} (table_id={table_id}), "
                f"指标: {len(metric_fields)}, 维度: {len(dimension_fields)}"
            )

            # 加载当前 group 的分组规则,使用 values 减少内存
            grouping_rules = list(
                CustomTSGroupingRule.objects.filter(time_series_group_id=group_id).values("name", "auto_rules")
            )

            # 迁移 Scope 和 Metric
            scope_name_to_id = migrate_scope(
                apps, bk_tenant_id, dimension_fields, group_id, metric_fields, table_id, grouping_rules, stats
            )
            migrate_metric(apps, group_id, metric_fields, scope_name_to_id, table_id, stats)

            stats["processed_groups"] += 1

            group_cost = time.time() - group_start

            # 清理局部变量
            del custom_fields
            del metric_fields
            del dimension_fields
            del grouping_rules
            del scope_name_to_id

            logger.info(f"[成功 {idx}/{stats['total_groups']}] Group {group_id} 迁移完成, 耗时: {group_cost:.2f}s")

        except Exception as e:
            group_cost = time.time() - group_start

            logger.error(
                f"[失败 {idx}/{stats['total_groups']}] Group {group_id} (table_id={table_id}) 迁移失败: {str(e)}, "
                f"耗时: {group_cost:.2f}s",
                exc_info=True,
            )
            stats["skipped_groups"] += 1

    total_cost = time.time() - migration_start

    summary = (
        f"组: {stats['processed_groups']}/{stats['total_groups']} "
        f"(跳过: {stats['skipped_groups']})\n"
        f"Scope: 新建 {stats['scopes_created']}, 更新 {stats['scopes_updated']}\n"
        f"Metric: 新建 {stats['metrics_created']}, 更新 {stats['metrics_updated']}\n"
        f"总耗时: {total_cost:.2f}s"
    )
    logger.info(f"[迁移完成] {summary}")


def migrate_scope(apps, bk_tenant_id, dimension_fields, group_id, metric_fields, table_id, grouping_rules, stats):
    """迁移 Scope 数据"""
    TimeSeriesScope = apps.get_model("metadata", "TimeSeriesScope")
    ResultTableField = apps.get_model("metadata", "ResultTableField")

    # 收集所有配置信息到统一的数据结构
    scope_info = {}

    # 收集所有需要查询的维度名称
    dim_field_dict = {dim_field.get("name"): dim_field for dim_field in dimension_fields if dim_field.get("name")}
    all_needed_dimension_names = set(dim_field_dict.keys()) | {
        dim for field in metric_fields for dim in field.get("config", {}).get("dimensions", [])
    }

    # 只查询需要的字段,使用 values 减少内存
    rt_fields_dict = {}
    if all_needed_dimension_names:
        rt_fields_dict = {
            item["field_name"]: item["description"]
            for item in ResultTableField.objects.filter(
                table_id=table_id, bk_tenant_id=bk_tenant_id, field_name__in=all_needed_dimension_names
            ).values("field_name", "description")
        }

    # 收集所有维度的配置信息
    dim_configs = {}
    for dim_name in all_needed_dimension_names:
        config = {}
        # 如果维度在 dim_field_dict 中,提取其配置
        if dim_name in dim_field_dict:
            dim_field_config = dim_field_dict[dim_name].get("config", {})
            config = {k: v for k, v in dim_field_config.items() if k in ["common", "hidden"]}
        # 添加 alias
        if description := rt_fields_dict.get(dim_name):
            config["alias"] = description
        else:
            if field := dim_field_dict.get(dim_name):
                config["alias"] = field.get("description", "")

        dim_configs[dim_name] = config

    # 确保默认分组一定会被创建
    scope_info[DEFAULT_DATA_SCOPE_NAME] = {"is_default": True, "dim_configs": {}, "auto_rules": []}

    # 收集 scope 信息和维度使用情况
    for field in metric_fields:
        scope_name = get_scope_name(field, DEFAULT_DATA_SCOPE_NAME)

        if scope_name not in scope_info:
            scope_info[scope_name] = {"is_default": False, "dim_configs": {}, "auto_rules": []}

        scope_info[scope_name]["is_default"] = scope_name == DEFAULT_DATA_SCOPE_NAME

        # 获取该指标使用的维度列表,并将维度配置合并进来
        for dim_name in field.get("config", {}).get("dimensions", []):
            if dim_name in dim_configs:
                scope_info[scope_name]["dim_configs"][dim_name] = dim_configs[dim_name]

    # rule.get("name") 对应 scope_name
    for rule in grouping_rules:
        rule_name = rule.get("name")
        if rule_name and rule_name in scope_info:
            scope_info[rule_name]["auto_rules"] = rule.get("auto_rules", [])

    existing_scope_names = {
        item["scope_name"]: item["id"]
        for item in TimeSeriesScope.objects.filter(group_id=group_id, scope_name__in=scope_info.keys()).values(
            "scope_name", "id"
        )
    }

    # 批量创建所有 Scope
    scopes_to_create = []
    scopes_to_update = []
    for scope_name, info in scope_info.items():
        if scope_name in existing_scope_names:
            scopes_to_update.append(
                TimeSeriesScope(
                    id=existing_scope_names[scope_name],
                    group_id=group_id,
                    scope_name=scope_name,
                    dimension_config=info["dim_configs"],
                    auto_rules=info["auto_rules"],
                    create_from=CREATE_FROM_DEFAULT if info["is_default"] else CREATE_FROM_USER,
                )
            )
        else:
            scopes_to_create.append(
                TimeSeriesScope(
                    group_id=group_id,
                    scope_name=scope_name,
                    dimension_config=info["dim_configs"],
                    auto_rules=info["auto_rules"],
                    create_from=CREATE_FROM_DEFAULT if info["is_default"] else CREATE_FROM_USER,
                )
            )

    if scopes_to_create:
        TimeSeriesScope.objects.bulk_create(scopes_to_create, batch_size=BULK_BATCH_SIZE)
        stats["scopes_created"] += len(scopes_to_create)

    if scopes_to_update:
        TimeSeriesScope.objects.bulk_update(
            scopes_to_update,
            ["dimension_config", "auto_rules", "create_from"],
            batch_size=BULK_BATCH_SIZE,
        )
        stats["scopes_updated"] += len(scopes_to_update)

    # 只查询需要的字段,减少内存占用
    return {
        item["scope_name"]: item["id"]
        for item in TimeSeriesScope.objects.filter(group_id=group_id, scope_name__in=scope_info.keys()).values(
            "scope_name", "id"
        )
    }


def migrate_metric(apps, group_id, metric_fields, scope_name_to_id, table_id, stats):
    """迁移 Metric 数据"""
    TimeSeriesMetric = apps.get_model("metadata", "TimeSeriesMetric")

    # 只查询当前 group 的已存在指标,使用 only 减少内存
    existing_metrics_qs = TimeSeriesMetric.objects.filter(group_id=group_id).only(
        "field_id", "field_scope", "field_name", "scope_id", "field_config", "create_time"
    )
    existing_metrics = {(metric.field_scope, metric.field_name): metric for metric in existing_metrics_qs}

    # 处理指标字段,创建或更新 Metric
    metrics_to_create = []
    metrics_to_update = []

    for field in metric_fields:
        scope_name = get_scope_name(field, DEFAULT_DATA_SCOPE_NAME)
        tag_list = field.get("config", {}).get("dimensions", [])

        # 构建字段配置
        field_config = {"disabled": field.get("disabled", False)}
        if field_description := field.get("description"):
            field_config["alias"] = field_description

        field_config_data = field.get("config", {})
        for key in METRIC_CONFIG_FIELDS:
            if key in field_config_data:
                field_config[key] = field_config_data[key]

        scope_id = scope_name_to_id.get(scope_name)
        field_name = field.get("name")
        existing = existing_metrics.get((DEFAULT_DATA_SCOPE_NAME, field_name))

        if existing:
            existing.scope_id = scope_id
            existing.field_config = field_config
            existing.field_scope = DEFAULT_DATA_SCOPE_NAME
            existing.create_time = field.get("create_time")
            metrics_to_update.append(existing)
        else:
            metrics_to_create.append(
                TimeSeriesMetric(
                    group_id=group_id,
                    scope_id=scope_id,
                    table_id=table_id,
                    field_scope=DEFAULT_DATA_SCOPE_NAME,
                    field_name=field_name,
                    tag_list=tag_list,
                    field_config=field_config,
                    label="",
                    create_time=field.get("create_time"),
                    last_modify_time=field.get("update_time"),
                )
            )

    # 批量保存 Metric
    if metrics_to_create:
        TimeSeriesMetric.objects.bulk_create(metrics_to_create, batch_size=BULK_BATCH_SIZE)
        stats["metrics_created"] += len(metrics_to_create)
    if metrics_to_update:
        TimeSeriesMetric.objects.bulk_update(
            metrics_to_update,
            ["scope_id", "field_config", "field_scope", "create_time"],
            batch_size=BULK_BATCH_SIZE,
        )
        stats["metrics_updated"] += len(metrics_to_update)


def get_scope_name(field, default_scope):
    """获取字段的 scope 名称"""
    labels = field.get("config", {}).get("label", [])
    return labels[0] if labels else default_scope


class Migration(migrations.Migration):
    dependencies = [
        ("monitor_web", "0076_auto_20250408_1522"),
        ("metadata", "0251_add_custom_time_series_scope"),
    ]

    operations = [
        migrations.RunPython(migrate_custom_ts_field_to_time_series),
    ]
