# Generated by Django to merge conflicting migrations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0249_resourcedefinition_relationdefinition"),
        ("metadata", "0252_migrate_custom_ts_data"),
    ]

    operations = []
