# Generated by Django 4.2.27 on 2026-03-05 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0249_resourcedefinition_relationdefinition"),
        ("metadata", "0252_migrate_custom_ts_data"),
    ]

    operations = []
