# Generated by Django 4.2.7 on 2026-03-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0253_merge_20260305_2143"),
    ]

    operations = [
        migrations.AddField(
            model_name="resulttable",
            name="labels",
            field=models.JSONField(blank=True, default=dict, verbose_name="扩展标签"),
        ),
    ]
