# Generated by Django 4.2.27 on 2026-03-08 21:54

from collections import defaultdict

from django.db import migrations

from metadata.models.space.constants import EtlConfigs


def migrate_plugin_result_table_option(apps, schema_editor):
    """
    迁移插件结果表选项
    """
    DataSource = apps.get_model("metadata", "DataSource")
    DataSourceResultTable = apps.get_model("metadata", "DataSourceResultTable")
    ResultTableOption = apps.get_model("metadata", "ResultTableOption")
    bk_data_ids = list(
        DataSource.objects.filter(
            etl_config__in=[EtlConfigs.BK_EXPORTER.value, EtlConfigs.BK_STANDARD.value]
        ).values_list("bk_data_id", flat=True)
    )

    tenant_table_ids: dict[str, list[str]] = defaultdict(list)
    for dsrt in DataSourceResultTable.objects.filter(bk_data_id__in=bk_data_ids):
        tenant_table_ids[dsrt.bk_tenant_id].append(dsrt.table_id)

    for tenant_id, table_ids in tenant_table_ids.items():
        ResultTableOption.objects.filter(
            bk_tenant_id=tenant_id, name=ResultTableOption.OPTION_ENABLE_PLUGIN_V4_DATA_LINK, table_id__in=table_ids
        ).delete()
        options = [
            ResultTableOption(
                bk_tenant_id=tenant_id,
                table_id=table_id,
                name=ResultTableOption.OPTION_ENABLE_PLUGIN_V4_DATA_LINK,
                value="true",
                value_type=ResultTableOption.TYPE_BOOL,
                creator="system",
            )
            for table_id in table_ids
        ]
        ResultTableOption.objects.bulk_create(options)


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0253_merge_20260305_2143"),
    ]

    operations = [
        migrations.RunPython(migrate_plugin_result_table_option),
    ]
