# Generated by Django 4.2.27 on 2026-03-10 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0250_merge_20260205_1655"),
        ("metadata", "0254_resulttable_labels"),
    ]

    operations = []
