# Generated by Django 4.2.27 on 2026-03-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0254_resulttable_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="BkBaseShortChainResultTable",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_tenant_id", models.CharField(default="system", max_length=256, verbose_name="租户ID")),
                ("table_id", models.CharField(db_index=True, max_length=128, verbose_name="监控平台结果表ID")),
                ("bkbase_rt_id", models.CharField(db_index=True, max_length=128, verbose_name="BKBase结果表ID")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务ID")),
                ("data_label", models.CharField(blank=True, default="", max_length=128, verbose_name="数据标签")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("last_modify_time", models.DateTimeField(auto_now=True, verbose_name="最后更新时间")),
            ],
            options={
                "verbose_name": "BKBase短链路结果表映射",
                "verbose_name_plural": "BKBase短链路结果表映射",
                "unique_together": {("bk_tenant_id", "table_id")},
            },
        ),
    ]
