# Generated by Django 4.2.27 on 2026-03-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0255_merge_20260310_1622'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timeseriesmetric',
            index=models.Index(fields=['group_id', 'field_name'], name='idx_tsmetric_gid_fname'),
        ),
        migrations.AddIndex(
            model_name='timeseriesmetric',
            index=models.Index(fields=['group_id', 'scope_id', 'field_name'], name='idx_tsmetric_gid_sid_fname'),
        ),
        migrations.AddIndex(
            model_name='timeseriesmetric',
            index=models.Index(fields=['group_id', '-last_modify_time'], name='idx_tsmetric_gid_mtime'),
        ),
    ]
