# Generated by Django 4.2.27 on 2026-03-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0255_merge_20260310_1622"),
    ]

    operations = [
        migrations.AddField(
            model_name="bcsclusterinfo",
            name="operator_ns",
            field=models.CharField(
                default="bkmonitor-operator",
                help_text="bkmonitor-operator-stack Helm Chart 的安装 namespace，每个 namespace 对应一套独立部署",
                max_length=128,
                verbose_name="operator 安装 namespace",
            ),
        ),
    ]
