# Generated by Django 4.2.27 on 2026-04-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0257_admin_field_optimization"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="timeseriesmetric",
            index=models.Index(fields=["group_id", "scope_id", "field_name"], name="metadata_ti_group_i_7a4b5e_idx"),
        ),
    ]
