# Generated by Django 4.2.27 on 2026-05-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0263_vmshortlinkrecord_data_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventgroup",
            name="token",
            field=models.CharField(default="", max_length=256, verbose_name="自定义上报 Token"),
        ),
        migrations.AddField(
            model_name="loggroup",
            name="token",
            field=models.CharField(default="", max_length=256, verbose_name="自定义上报 Token"),
        ),
        migrations.AddField(
            model_name="timeseriesgroup",
            name="token",
            field=models.CharField(default="", max_length=256, verbose_name="自定义上报 Token"),
        ),
    ]
