# Generated by Django 4.2.27 on 2026-06-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0265_databusconfig_consumer_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventgroup",
            name="is_need_deploy_collector_config",
            field=models.BooleanField(default=True, verbose_name="是否需要下发 collector 配置"),
        ),
        migrations.AddField(
            model_name="loggroup",
            name="is_need_deploy_collector_config",
            field=models.BooleanField(default=True, verbose_name="是否需要下发 collector 配置"),
        ),
        migrations.AddField(
            model_name="timeseriesgroup",
            name="is_need_deploy_collector_config",
            field=models.BooleanField(default=True, verbose_name="是否需要下发 collector 配置"),
        ),
    ]
