CREATE DATABASE IF NOT EXISTS bk_monitorv3_grafana DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS bkmonitorv3_alert DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
