__implements__ = []

from bk_monitor_base.infras.third_party_api.nodeman.client import (
    CreateExportPluginTask,
    CreatePluginConfigTemplate,
    CreateRegisterPluginTask,
    CreateSubscription,
    GetPluginInfo,
    GetProxies,
    GetProxiesByBiz,
    GetSubscriptionInfo,
    GetSubscriptionTaskResult,
    GetSubscriptionTaskResultDetail,
    PluginOperate,
    PluginSearch,
    QueryExportPluginTask,
    QueryPluginDebug,
    QueryRegisterPluginTask,
    ReleasePlugin,
    ReleasePluginConfigTemplate,
    RenderPluginConfigTemplate,
    RetrySubscription,
    RevokeSubscription,
    RunSubscription,
    StartPluginDebug,
    StopPluginDebug,
    SwitchSubscription,
    UpdateSubscription,
)

_APIGW_PATH_PATCHES = {
    CreatePluginConfigTemplate: "backend/api/plugin/create_config_template/",
    CreateSubscription: "backend/api/subscription/create/",
    CreateExportPluginTask: "backend/api/plugin/create_export_task/",
    GetPluginInfo: "backend/api/plugin/info/",
    QueryExportPluginTask: "backend/api/plugin/query_export_task/",
    QueryPluginDebug: "backend/api/plugin/query_debug/",
    QueryRegisterPluginTask: "backend/api/plugin/query_register_task/",
    CreateRegisterPluginTask: "backend/api/plugin/create_register_task/",
    ReleasePluginConfigTemplate: "backend/api/plugin/release_config_template/",
    ReleasePlugin: "backend/api/plugin/release/",
    RenderPluginConfigTemplate: "backend/api/plugin/render_config_template/",
    RunSubscription: "backend/api/subscription/run/",
    StartPluginDebug: "backend/api/plugin/start_debug/",
    StopPluginDebug: "backend/api/plugin/stop_debug/",
    GetSubscriptionInfo: "backend/api/subscription/info/",
    SwitchSubscription: "backend/api/subscription/switch/",
    GetSubscriptionTaskResultDetail: "backend/api/subscription/task_result_detail/",
    GetSubscriptionTaskResult: "backend/api/subscription/task_result/",
    UpdateSubscription: "backend/api/subscription/update/",
    GetProxies: "api/host/proxies/",
    GetProxiesByBiz: "api/host/biz_proxies/",
    PluginOperate: "api/plugin/operate/",
    RetrySubscription: "backend/api/subscription/retry/",
    RevokeSubscription: "backend/api/subscription/revoke/",
    PluginSearch: "api/plugin/search/",
}

for client_cls, apigw_path in _APIGW_PATH_PATCHES.items():
    client_cls.apigw_path = apigw_path
