# Generated by Django 3.2.15 on 2023-11-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm_ebpf", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterRelation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
                ("cluster_id", models.CharField(max_length=128, verbose_name="集群ID")),
                ("project_id", models.CharField(max_length=128, verbose_name="BCS项目ID")),
                ("last_check_time", models.DateTimeField(verbose_name="最近检查日期")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "BCS集群关联信息表",
            },
        ),
    ]
