# Generated by Django 3.2.15 on 2023-11-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apm_ebpf', '0002_clusterrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepflowworkload',
            name='last_check_time',
            field=models.DateTimeField(verbose_name='最后检查日期'),
        ),
    ]
