# Generated by Django 3.2.15 on 2023-12-11 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('apm_ebpf', '0003_alter_deepflowworkload_last_check_time'),
        ('apm_ebpf', '0003_auto_20231207_1520'),
    ]

    operations = []
