#!/bin/bash

source /root/.bkrc
source $CTRL_DIR/functions

# workon 会自动进入到工程目录
workon bkmonitorv3-monitor || fail "activate virtualenv (monitor) failed."

# 检查是否需要执行 on_migrate
bin/manage.sh check_on_migrate || { echo "skip migrate" ; exit 0 ; }

# 执行 migrate，请勿改动顺序
bin/manage.sh sync_cluster_config
bin/manage.sh sync_zk_config
bin/manage.sh init_influxdb_proxy_storage
bin/manage.sh refresh_influxdb_proxy_config
bin/manage.sh refresh_custom_report_metric_path
bin/manage.sh init_space_data
bin/manage.sh sync_bklog_es_router


# 更新on_migrate版本
bin/manage.sh check_on_migrate --update
