# Generated by Django 3.2.15 on 2023-09-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ApiAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, default='', max_length=32, verbose_name='修改者')),
                (
                    'space_uid',
                    models.CharField(blank=True, db_index=True, default='', max_length=256, verbose_name='空间唯一标识'),
                ),
                ('token', models.CharField(default='JFsMANBMj0xZSZV8', max_length=32, verbose_name='鉴权令牌')),
                ('type', models.CharField(choices=[('Grafana', 'Grafana')], max_length=32, verbose_name='鉴权类型')),
                ('params', models.JSONField(default=dict, verbose_name='鉴权参数')),
                ('expire_time', models.DateTimeField(default=None, null=True, verbose_name='过期时间')),
            ],
            options={
                'verbose_name': 'API鉴权令牌',
                'verbose_name_plural': 'API鉴权令牌',
            },
        ),
    ]
