# Generated by Django 3.2.15 on 2023-10-12 07:29

import apps.log_commons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_commons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiauthtoken',
            name='token',
            field=models.CharField(
                default=apps.log_commons.models.get_random_string_16, max_length=32, verbose_name='鉴权令牌'
            ),
        ),
    ]
