# Generated by Django 3.2.15 on 2023-10-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_commons', '0002_alter_apiauthtoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPermissionApplyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, default='', max_length=32, verbose_name='修改者')),
                (
                    'space_uid',
                    models.CharField(blank=True, db_index=True, default='', max_length=256, verbose_name='空间唯一标识'),
                ),
                ('authorized_users', models.JSONField(default=list, verbose_name='被授权人列表')),
                ('resources', models.JSONField(default=list, verbose_name='资源列表')),
                (
                    'action_id',
                    models.CharField(
                        choices=[('log_search', '日志检索'), ('log_extract', '日志提取')],
                        db_index=True,
                        max_length=32,
                        verbose_name='操作类型',
                    ),
                ),
                (
                    'operate',
                    models.CharField(
                        choices=[('create', '创建'), ('update', '更新'), ('delete', '删除')],
                        db_index=True,
                        max_length=12,
                        verbose_name='操作',
                    ),
                ),
                ('expire_time', models.DateTimeField(default=None, null=True, verbose_name='过期时间')),
                (
                    'approval_sn',
                    models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='审批单号'),
                ),
                (
                    'approval_url',
                    models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='审批地址'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('no_status', '无状态'), ('approval', '审批中'), ('success', '成功'), ('failed', '失败')],
                        default='no_status',
                        max_length=32,
                        verbose_name='状态',
                    ),
                ),
            ],
            options={
                'verbose_name': '外部权限授权记录',
                'verbose_name_plural': '外部权限授权记录',
                'db_table': 'external_permission_apply_record',
            },
        ),
        migrations.CreateModel(
            name='ExternalPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, default='', max_length=32, verbose_name='修改者')),
                (
                    'space_uid',
                    models.CharField(blank=True, db_index=True, default='', max_length=256, verbose_name='空间唯一标识'),
                ),
                ('authorized_user', models.CharField(max_length=64, verbose_name='被授权人')),
                (
                    'action_id',
                    models.CharField(
                        choices=[('log_search', '日志检索'), ('log_extract', '日志提取')],
                        db_index=True,
                        max_length=32,
                        verbose_name='操作类型',
                    ),
                ),
                ('resources', models.JSONField(default=list, verbose_name='资源列表')),
                ('expire_time', models.DateTimeField(default=None, null=True, verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '外部权限',
                'verbose_name_plural': '外部权限',
                'db_table': 'external_permission',
                'index_together': {('authorized_user', 'action_id', 'space_uid')},
            },
        ),
    ]
