# Generated by Django 4.2 on 2025-06-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_commons", "0003_externalpermission_externalpermissionapplyrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiauthtoken",
            name="type",
            field=models.CharField(
                choices=[("Grafana", "Grafana"), ("Search", "Search")], max_length=32, verbose_name="鉴权类型"
            ),
        ),
        migrations.CreateModel(
            name="TokenAccessRecord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, verbose_name="修改者")),
                ("token", models.CharField(max_length=32, verbose_name="鉴权令牌")),
            ],
            options={
                "verbose_name": "API鉴权令牌访问记录",
                "verbose_name_plural": "API鉴权令牌访问记录",
                "db_table": "token_access_record",
                "index_together": {("token", "created_by")},
            },
        ),
    ]
