# Generated by Django 4.2.22 on 2025-09-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_toggle', '0007_set_k8s_deploy_default_storage_20230712'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretoggle',
            name='biz_id_black_list',
            field=models.JSONField(blank=True, null=True, verbose_name='业务黑名单'),
        ),
    ]
