paths:
  /user/action/create_chat_group_action/:
    post:
      operationId: create_chat_group_action
      description: 创建跨业务告警群
      x-bk-apigateway-resource:
        isPublic: false
        matchSubpath: false
        backend:
          name: default
          method: post
          path: /api/v4/action_instance/create_chat_group_action/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: true
          resourcePermissionRequired: true
        descriptionEn: Create an alert chat group
