# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-15 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0002_add_default_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendarmodel",
            name="color",
        ),
        migrations.AddField(
            model_name="calendarmodel",
            name="deep_color",
            field=models.CharField(default="#3A84FF", max_length=7, verbose_name="日历深色底色"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="calendarmodel",
            name="light_color",
            field=models.CharField(default="#E1ECFF", max_length=7, verbose_name="日历浅色底色"),
            preserve_default=False,
        ),
    ]
