# Generated by Django 3.2.25 on 2025-03-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('calendars', '0006_merge_20220609_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarmodel',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=128, verbose_name='租户ID'),
        ),
    ]
