# Generated by Django 3.2.25 on 2025-04-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('calendars', '0007_calendarmodel_bk_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaritemmodel',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=128, verbose_name='租户ID'),
        ),
    ]
