# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-24 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fta_web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertSuggestion",
            fields=[
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="最后修改人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="最后修改时间")),
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(db_index=True, default=0, verbose_name="业务ID")),
                (
                    "type",
                    models.CharField(
                        choices=[("metric", "指标"), ("dimension", "维度")], max_length=32, verbose_name="经验类型"
                    ),
                ),
                ("metric", models.JSONField(default=list, verbose_name="指标ID")),
                ("alert_name", models.TextField(blank=True, default="", verbose_name="告警名称")),
                ("conditions", models.JSONField(default=list, verbose_name="匹配条件")),
                ("description", models.TextField(verbose_name="处理建议")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
