# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-15 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fta_web", "0002_alertsuggestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertFeedback",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="最后修改人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="最后修改时间")),
                ("alert_id", models.CharField(db_index=True, max_length=64, verbose_name="告警ID")),
                ("is_anomaly", models.BooleanField(verbose_name="是否异常")),
                ("description", models.TextField(blank=True, verbose_name="反馈信息")),
            ],
            options={
                "verbose_name": "告警反馈",
                "verbose_name_plural": "告警反馈",
            },
        ),
        migrations.AlterModelOptions(
            name="alertsuggestion",
            options={"verbose_name": "告警处理建议", "verbose_name_plural": "告警处理建议"},
        ),
    ]
