# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-07-22 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fta_web", "0003_auto_20220415_1635"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlarmApplication",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_type", models.CharField(max_length=64, verbose_name="告警源标识")),
                ("cc_biz_id", models.IntegerField(db_index=True, verbose_name="业务编码")),
                ("app_name", models.CharField(max_length=255, verbose_name="应用名称")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("app_url", models.TextField(blank=True, default="", null=True, verbose_name="拉取告警地址")),
                (
                    "app_method",
                    models.CharField(
                        blank=True,
                        choices=[("get", "GET"), ("post", "POST")],
                        default="get",
                        max_length=10,
                        null=True,
                        verbose_name="请求类型",
                    ),
                ),
            ],
            options={
                "db_table": "fta_solutions_app_alarmapplication",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AlarmDef",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_enabled", models.BooleanField(default=False, verbose_name="是否启用")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("category", models.CharField(default="default", max_length=32, verbose_name="告警类型")),
                ("cc_biz_id", models.IntegerField(db_index=True, verbose_name="业务编码")),
                ("alarm_type", models.CharField(max_length=128, verbose_name="告警类型")),
                ("tnm_attr_id", models.TextField(blank=True, default="", null=True, verbose_name="TNM特性ID")),
                ("reg", models.CharField(blank=True, default="", max_length=255, null=True, verbose_name="正则过滤")),
                ("process", models.CharField(blank=True, default="", max_length=255, null=True, verbose_name="进程名称")),
                ("module", models.TextField(blank=True, default="", verbose_name="Module")),
                ("topo_set", models.TextField(blank=True, default="", verbose_name="Set")),
                ("set_attr", models.TextField(blank=True, default="", verbose_name="Set属性")),
                ("idc", models.TextField(blank=True, default="", verbose_name="IDC")),
                ("device_class", models.TextField(blank=True, default="", verbose_name="DeviceClass")),
                ("responsible", models.CharField(blank=True, max_length=255, null=True, verbose_name="额外通知人")),
                ("title", models.CharField(blank=True, max_length=128, null=True, verbose_name="全名")),
                ("description", models.TextField(blank=True, null=True, verbose_name="备注")),
                ("ok_notify", models.BooleanField(default=True, verbose_name="成功后是否通知")),
                ("notify", models.TextField(default="{}", verbose_name="通知配置")),
                ("solution_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("timeout", models.IntegerField(default=40, verbose_name="超时时长")),
                (
                    "source_type",
                    models.CharField(blank=True, default="TNM", max_length=32, null=True, verbose_name="告警源"),
                ),
                ("alarm_attr_id", models.CharField(blank=True, max_length=128, null=True, verbose_name="告警在来源系统的特征ID")),
                ("set_names", models.TextField(blank=True, default="", verbose_name="Set名称")),
                ("module_names", models.TextField(blank=True, default="", verbose_name="Module名称")),
                ("topo_names", models.TextField(blank=True, default="{}", verbose_name="自由拓扑结构的名称")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("create_user", models.CharField(default="", max_length=32, verbose_name="创建人")),
                ("update_user", models.CharField(default="", max_length=32, verbose_name="修改人")),
                ("include_biz_ids", models.TextField(blank=True, default="", null=True, verbose_name="启用业务")),
                ("add_from", models.CharField(default="user", max_length=10, verbose_name="方案来源")),
            ],
            options={
                "db_table": "fta_solutions_app_alarmdef",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AlarmType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cc_biz_id", models.IntegerField(db_index=True, verbose_name="业务编码")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("source_type", models.CharField(db_index=True, max_length=128, verbose_name="告警来源")),
                ("alarm_type", models.CharField(db_index=True, max_length=128, verbose_name="告警类型")),
                ("pattern", models.CharField(max_length=128, verbose_name="匹配模式")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "match_mode",
                    models.IntegerField(choices=[(0, "字符串"), (1, "正则表达式"), (2, "通配符")], default=0, verbose_name="匹配类型"),
                ),
                ("scenario", models.CharField(blank=True, default="", max_length=128, verbose_name="告警类型分类")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
            ],
            options={
                "db_table": "fta_solutions_app_alarmtype",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cc_biz_id", models.IntegerField(db_index=True, verbose_name="业务编码")),
                ("solution_type", models.CharField(default="customized", max_length=128, verbose_name="套餐类型")),
                ("codename", models.CharField(blank=True, max_length=128, null=True, verbose_name="英文名称代号")),
                ("title", models.CharField(max_length=512, verbose_name="全名")),
                ("config", models.TextField(blank=True, null=True, verbose_name="配置(JSON)")),
                ("creator", models.CharField(max_length=255, verbose_name="创建者")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("create_user", models.CharField(max_length=32, verbose_name="创建人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("update_user", models.CharField(max_length=32, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
            ],
            options={
                "db_table": "fta_solutions_app_solution",
                "managed": False,
            },
        ),
    ]
