# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-02-22 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fta_web', '0004_alarmapplication_alarmdef_alarmtype_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricRecommendationFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_user', models.CharField(blank=True, default='', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(blank=True, default='', max_length=32, verbose_name='最后修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('alert_metric_id', models.CharField(max_length=128, verbose_name='告警指标ID')),
                ('recommendation_metric_hash', models.CharField(max_length=32, verbose_name='推荐指标哈希')),
                (
                    'feedback',
                    models.CharField(choices=[('good', '点赞'), ('bad', '点踩')], max_length=16, verbose_name='反馈行为'),
                ),
                ('bk_biz_id', models.IntegerField(verbose_name='业务ID')),
                ('recommendation_metric', models.TextField(verbose_name='推荐指标文本')),
            ],
            options={
                'verbose_name': '指标推荐反馈',
            },
        ),
        migrations.AlterUniqueTogether(
            name='metricrecommendationfeedback',
            unique_together={('alert_metric_id', 'recommendation_metric_hash', 'bk_biz_id', 'create_user')},
        ),
    ]
