# Generated by Django 3.2.25 on 2025-06-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fta_web", "0006_auto_20230613_1211"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchfavorite",
            name="search_type",
            field=models.CharField(
                choices=[("alert", "告警"), ("event", "事件"), ("action", "处理动作"), ("incident", "故障")],
                default="alert",
                max_length=32,
                verbose_name="检索类型",
            ),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="search_type",
            field=models.CharField(
                choices=[("alert", "告警"), ("event", "事件"), ("action", "处理动作"), ("incident", "故障")],
                default="alert",
                max_length=32,
                verbose_name="检索类型",
            ),
        ),
    ]
