"""
Bacula 备份系统相关 Grok 模式数据
对应 pygrok patterns/bacula 文件
"""

PATTERNS = [
    {
        "name": "BACULA_TIMESTAMP",
        "pattern": r"%{MONTHDAY}-%{MONTH} %{HOUR}:%{MINUTE}",
        "sample": "15-Mar 14:30",
        "description": "匹配 Bacula 日志时间戳格式（日-月 时:分）",
    },
    {
        "name": "BACULA_HOST",
        "pattern": r"[a-zA-Z0-9-]+",
        "sample": "backup-server-01",
        "description": "匹配 Bacula 主机名",
    },
    {
        "name": "BACULA_VOLUME",
        "pattern": r"%{USER}",
        "sample": "Vol-0001",
        "description": "匹配 Bacula 存储卷名称",
    },
    {
        "name": "BACULA_DEVICE",
        "pattern": r"%{USER}",
        "sample": "FileStorage",
        "description": "匹配 Bacula 存储设备名称",
    },
    {
        "name": "BACULA_DEVICEPATH",
        "pattern": r"%{UNIXPATH}",
        "sample": "/var/lib/bacula/storage",
        "description": "匹配 Bacula 存储设备路径",
    },
    {
        "name": "BACULA_CAPACITY",
        "pattern": r"%{INT}{1,3}(,%{INT}{3})*",
        "sample": "1,073,741,824",
        "description": "匹配 Bacula 存储容量（带逗号分隔的数字）",
    },
    {
        "name": "BACULA_VERSION",
        "pattern": r"%{USER}",
        "sample": "9.6.7",
        "description": "匹配 Bacula 版本号",
    },
    {
        "name": "BACULA_JOB",
        "pattern": r"%{USER}",
        "sample": "BackupClient1.2024-03-15_14.30.00_01",
        "description": "匹配 Bacula 作业名称",
    },
    {
        "name": "BACULA_LOG_MAX_CAPACITY",
        "pattern": r"User defined maximum volume capacity %{BACULA_CAPACITY} exceeded on device \"%{BACULA_DEVICE:device}\" \(%{BACULA_DEVICEPATH}\)",
        "sample": 'User defined maximum volume capacity 1,073,741,824 exceeded on device "FileStorage" (/var/lib/bacula/storage)',
        "description": "匹配 Bacula 超过用户定义最大卷容量的日志",
    },
    {
        "name": "BACULA_LOG_END_VOLUME",
        "pattern": r"End of medium on Volume \"%{BACULA_VOLUME:volume}\" Bytes=%{BACULA_CAPACITY} Blocks=%{BACULA_CAPACITY} at %{MONTHDAY}-%{MONTH}-%{YEAR} %{HOUR}:%{MINUTE}.",
        "sample": 'End of medium on Volume "Vol-0001" Bytes=1,073,741,824 Blocks=16,384 at 15-Mar-2024 14:30.',
        "description": "匹配 Bacula 存储介质结束的日志",
    },
    {
        "name": "BACULA_LOG_NEW_VOLUME",
        "pattern": r"Created new Volume \"%{BACULA_VOLUME:volume}\" in catalog.",
        "sample": 'Created new Volume "Vol-0002" in catalog.',
        "description": "匹配 Bacula 在目录中创建新卷的日志",
    },
    {
        "name": "BACULA_LOG_NEW_LABEL",
        "pattern": r"Labeled new Volume \"%{BACULA_VOLUME:volume}\" on device \"%{BACULA_DEVICE:device}\" \(%{BACULA_DEVICEPATH}\).",
        "sample": 'Labeled new Volume "Vol-0002" on device "FileStorage" (/var/lib/bacula/storage).',
        "description": "匹配 Bacula 为新卷打标签的日志",
    },
    {
        "name": "BACULA_LOG_WROTE_LABEL",
        "pattern": r"Wrote label to prelabeled Volume \"%{BACULA_VOLUME:volume}\" on device \"%{BACULA_DEVICE}\" \(%{BACULA_DEVICEPATH}\)",
        "sample": 'Wrote label to prelabeled Volume "Vol-0002" on device "FileStorage" (/var/lib/bacula/storage)',
        "description": "匹配 Bacula 为预标签卷写入标签的日志",
    },
    {
        "name": "BACULA_LOG_NEW_MOUNT",
        "pattern": r"New volume \"%{BACULA_VOLUME:volume}\" mounted on device \"%{BACULA_DEVICE:device}\" \(%{BACULA_DEVICEPATH}\) at %{MONTHDAY}-%{MONTH}-%{YEAR} %{HOUR}:%{MINUTE}.",
        "sample": 'New volume "Vol-0002" mounted on device "FileStorage" (/var/lib/bacula/storage) at 15-Mar-2024 14:30.',
        "description": "匹配 Bacula 挂载新卷的日志",
    },
    {
        "name": "BACULA_LOG_NOOPEN",
        "pattern": r"\s+Cannot open %{DATA}: ERR=%{GREEDYDATA:berror}",
        "sample": "  Cannot open /var/lib/bacula/data: ERR=No such file or directory",
        "description": "匹配 Bacula 无法打开文件的错误日志",
    },
    {
        "name": "BACULA_LOG_NOOPENDIR",
        "pattern": r"\s+Could not open directory %{DATA}: ERR=%{GREEDYDATA:berror}",
        "sample": "  Could not open directory /var/lib/bacula/data: ERR=Permission denied",
        "description": "匹配 Bacula 无法打开目录的错误日志",
    },
    {
        "name": "BACULA_LOG_NOSTAT",
        "pattern": r"\s+Could not stat %{DATA}: ERR=%{GREEDYDATA:berror}",
        "sample": "  Could not stat /var/lib/bacula/data/file.dat: ERR=No such file or directory",
        "description": "匹配 Bacula 无法获取文件状态的错误日志",
    },
    {
        "name": "BACULA_LOG_NOJOBS",
        "pattern": r"There are no more Jobs associated with Volume \"%{BACULA_VOLUME:volume}\". Marking it purged.",
        "sample": 'There are no more Jobs associated with Volume "Vol-0001". Marking it purged.',
        "description": "匹配 Bacula 卷中已无关联作业并标记为清除的日志",
    },
    {
        "name": "BACULA_LOG_ALL_RECORDS_PRUNED",
        "pattern": r"All records pruned from Volume \"%{BACULA_VOLUME:volume}\"; marking it \"Purged\"",
        "sample": 'All records pruned from Volume "Vol-0001"; marking it "Purged"',
        "description": "匹配 Bacula 卷中所有记录已修剪并标记为清除的日志",
    },
    {
        "name": "BACULA_LOG_BEGIN_PRUNE_JOBS",
        "pattern": r"Begin pruning Jobs older than %{INT} month %{INT} days .",
        "sample": "Begin pruning Jobs older than 6 month 0 days .",
        "description": "匹配 Bacula 开始修剪过期作业的日志",
    },
    {
        "name": "BACULA_LOG_BEGIN_PRUNE_FILES",
        "pattern": r"Begin pruning Files.",
        "sample": "Begin pruning Files.",
        "description": "匹配 Bacula 开始修剪文件的日志",
    },
    {
        "name": "BACULA_LOG_PRUNED_JOBS",
        "pattern": r"Pruned %{INT} Jobs* for client %{BACULA_HOST:client} from catalog.",
        "sample": "Pruned 5 Jobs for client backup-client-01 from catalog.",
        "description": "匹配 Bacula 已修剪指定客户端作业的日志",
    },
    {
        "name": "BACULA_LOG_PRUNED_FILES",
        "pattern": r"Pruned Files from %{INT} Jobs* for client %{BACULA_HOST:client} from catalog.",
        "sample": "Pruned Files from 5 Jobs for client backup-client-01 from catalog.",
        "description": "匹配 Bacula 已修剪指定客户端文件记录的日志",
    },
    {
        "name": "BACULA_LOG_ENDPRUNE",
        "pattern": r"End auto prune.",
        "sample": "End auto prune.",
        "description": "匹配 Bacula 自动修剪结束的日志",
    },
    {
        "name": "BACULA_LOG_STARTJOB",
        "pattern": r"Start Backup JobId %{INT}, Job=%{BACULA_JOB:job}",
        "sample": "Start Backup JobId 123, Job=BackupClient1.2024-03-15_14.30.00_01",
        "description": "匹配 Bacula 开始备份作业的日志",
    },
    {
        "name": "BACULA_LOG_STARTRESTORE",
        "pattern": r"Start Restore Job %{BACULA_JOB:job}",
        "sample": "Start Restore Job RestoreClient1.2024-03-15_14.30.00_01",
        "description": "匹配 Bacula 开始恢复作业的日志",
    },
    {
        "name": "BACULA_LOG_USEDEVICE",
        "pattern": r"Using Device \"%{BACULA_DEVICE:device}\"",
        "sample": 'Using Device "FileStorage"',
        "description": "匹配 Bacula 使用存储设备的日志",
    },
    {
        "name": "BACULA_LOG_DIFF_FS",
        "pattern": r"\s+%{UNIXPATH} is a different filesystem. Will not descend from %{UNIXPATH} into it.",
        "sample": "  /mnt/data is a different filesystem. Will not descend from /home into it.",
        "description": "匹配 Bacula 跳过不同文件系统的日志",
    },
    {
        "name": "BACULA_LOG_JOBEND",
        "pattern": r"Job write elapsed time = %{DATA:elapsed}, Transfer rate = %{NUMBER} (K|M|G)? Bytes/second",
        "sample": "Job write elapsed time = 00:05:30, Transfer rate = 10.5 M Bytes/second",
        "description": "匹配 Bacula 作业写入完成的统计日志",
    },
    {
        "name": "BACULA_LOG_NOPRUNE_JOBS",
        "pattern": r"No Jobs found to prune.",
        "sample": "No Jobs found to prune.",
        "description": "匹配 Bacula 无可修剪作业的日志",
    },
    {
        "name": "BACULA_LOG_NOPRUNE_FILES",
        "pattern": r"No Files found to prune.",
        "sample": "No Files found to prune.",
        "description": "匹配 Bacula 无可修剪文件的日志",
    },
    {
        "name": "BACULA_LOG_VOLUME_PREVWRITTEN",
        "pattern": r"Volume \"%{BACULA_VOLUME:volume}\" previously written, moving to end of data.",
        "sample": 'Volume "Vol-0001" previously written, moving to end of data.',
        "description": "匹配 Bacula 卷已有写入数据并移到数据末尾的日志",
    },
    {
        "name": "BACULA_LOG_READYAPPEND",
        "pattern": r"Ready to append to end of Volume \"%{BACULA_VOLUME:volume}\" size=%{INT}",
        "sample": 'Ready to append to end of Volume "Vol-0001" size=1073741824',
        "description": "匹配 Bacula 准备追加写入卷的日志",
    },
    {
        "name": "BACULA_LOG_CANCELLING",
        "pattern": r"Cancelling duplicate JobId=%{INT}.",
        "sample": "Cancelling duplicate JobId=456.",
        "description": "匹配 Bacula 取消重复作业的日志",
    },
    {
        "name": "BACULA_LOG_MARKCANCEL",
        "pattern": r"JobId %{INT}, Job %{BACULA_JOB:job} marked to be canceled.",
        "sample": "JobId 456, Job BackupClient1.2024-03-15_14.30.00_01 marked to be canceled.",
        "description": "匹配 Bacula 标记作业为取消的日志",
    },
    {
        "name": "BACULA_LOG_CLIENT_RBJ",
        "pattern": r"shell command: run ClientRunBeforeJob \"%{GREEDYDATA:runjob}\"",
        "sample": 'shell command: run ClientRunBeforeJob "/usr/local/bin/pre-backup.sh"',
        "description": "匹配 Bacula 执行作业前客户端命令的日志",
    },
    {
        "name": "BACULA_LOG_VSS",
        "pattern": r"(Generate )?VSS (Writer)?",
        "sample": "Generate VSS Writer",
        "description": "匹配 Bacula VSS（卷影复制服务）相关日志",
    },
    {
        "name": "BACULA_LOG_MAXSTART",
        "pattern": r"Fatal error: Job canceled because max start delay time exceeded.",
        "sample": "Fatal error: Job canceled because max start delay time exceeded.",
        "description": "匹配 Bacula 因超过最大启动延迟时间而取消作业的致命错误",
    },
    {
        "name": "BACULA_LOG_DUPLICATE",
        "pattern": r"Fatal error: JobId %{INT:duplicate} already running. Duplicate job not allowed.",
        "sample": "Fatal error: JobId 789 already running. Duplicate job not allowed.",
        "description": "匹配 Bacula 检测到重复作业的致命错误",
    },
    {
        "name": "BACULA_LOG_NOJOBSTAT",
        "pattern": r"Fatal error: No Job status returned from FD.",
        "sample": "Fatal error: No Job status returned from FD.",
        "description": "匹配 Bacula 未从文件守护进程返回作业状态的致命错误",
    },
    {
        "name": "BACULA_LOG_FATAL_CONN",
        "pattern": r"Fatal error: bsock.c:133 Unable to connect to (Client: %{BACULA_HOST:client}|Storage daemon) on %{HOSTNAME}:%{POSINT}. ERR=(?<berror>%{GREEDYDATA})",
        "sample": "Fatal error: bsock.c:133 Unable to connect to Client: backup-client-01 on backup-client-01.example.com:9102. ERR=Connection refused",
        "description": "匹配 Bacula 无法连接客户端或存储守护进程的致命错误",
    },
    {
        "name": "BACULA_LOG_NO_CONNECT",
        "pattern": r"Warning: bsock.c:127 Could not connect to (Client: %{BACULA_HOST:client}|Storage daemon) on %{HOSTNAME}:%{POSINT}. ERR=(?<berror>%{GREEDYDATA})",
        "sample": "Warning: bsock.c:127 Could not connect to Client: backup-client-01 on backup-client-01.example.com:9102. ERR=Connection timed out",
        "description": "匹配 Bacula 无法连接客户端或存储守护进程的警告",
    },
    {
        "name": "BACULA_LOG_NO_AUTH",
        "pattern": r"Fatal error: Unable to authenticate with File daemon at %{HOSTNAME}. Possible causes:",
        "sample": "Fatal error: Unable to authenticate with File daemon at backup-client-01.example.com. Possible causes:",
        "description": "匹配 Bacula 无法与文件守护进程认证的致命错误",
    },
    {
        "name": "BACULA_LOG_NOSUIT",
        "pattern": r"No prior or suitable Full backup found in catalog. Doing FULL backup.",
        "sample": "No prior or suitable Full backup found in catalog. Doing FULL backup.",
        "description": "匹配 Bacula 未找到合适的全量备份并执行全量备份的日志",
    },
    {
        "name": "BACULA_LOG_NOPRIOR",
        "pattern": r"No prior Full backup Job record found.",
        "sample": "No prior Full backup Job record found.",
        "description": "匹配 Bacula 未找到先前全量备份记录的日志",
    },
    {
        "name": "BACULA_LOG_JOB",
        "pattern": r"(Error: )?Bacula %{BACULA_HOST} %{BACULA_VERSION} \(%{BACULA_VERSION}\):",
        "sample": "Bacula backup-server-01 9.6.7 (09Mar24):",
        "description": "匹配 Bacula 作业日志头部，包含主机名和版本信息",
    },
    {
        "name": "BACULA_LOGLINE",
        "pattern": r"%{BACULA_TIMESTAMP:bts} %{BACULA_HOST:hostname} JobId %{INT:jobid}: (%{BACULA_LOG_MAX_CAPACITY}|%{BACULA_LOG_END_VOLUME}|%{BACULA_LOG_NEW_VOLUME}|%{BACULA_LOG_NEW_LABEL}|%{BACULA_LOG_WROTE_LABEL}|%{BACULA_LOG_NEW_MOUNT}|%{BACULA_LOG_NOOPEN}|%{BACULA_LOG_NOOPENDIR}|%{BACULA_LOG_NOSTAT}|%{BACULA_LOG_NOJOBS}|%{BACULA_LOG_ALL_RECORDS_PRUNED}|%{BACULA_LOG_BEGIN_PRUNE_JOBS}|%{BACULA_LOG_BEGIN_PRUNE_FILES}|%{BACULA_LOG_PRUNED_JOBS}|%{BACULA_LOG_PRUNED_FILES}|%{BACULA_LOG_ENDPRUNE}|%{BACULA_LOG_STARTJOB}|%{BACULA_LOG_STARTRESTORE}|%{BACULA_LOG_USEDEVICE}|%{BACULA_LOG_DIFF_FS}|%{BACULA_LOG_JOBEND}|%{BACULA_LOG_NOPRUNE_JOBS}|%{BACULA_LOG_NOPRUNE_FILES}|%{BACULA_LOG_VOLUME_PREVWRITTEN}|%{BACULA_LOG_READYAPPEND}|%{BACULA_LOG_CANCELLING}|%{BACULA_LOG_MARKCANCEL}|%{BACULA_LOG_CLIENT_RBJ}|%{BACULA_LOG_VSS}|%{BACULA_LOG_MAXSTART}|%{BACULA_LOG_DUPLICATE}|%{BACULA_LOG_NOJOBSTAT}|%{BACULA_LOG_FATAL_CONN}|%{BACULA_LOG_NO_CONNECT}|%{BACULA_LOG_NO_AUTH}|%{BACULA_LOG_NOSUIT}|%{BACULA_LOG_JOB}|%{BACULA_LOG_NOPRIOR})",
        "sample": '15-Mar 14:30 backup-server-01 JobId 123: Created new Volume "Vol-0002" in catalog.',
        "description": "匹配 Bacula 完整日志行，包含时间戳、主机名、作业ID和各类日志消息",
    },
]
