"""
核心基础 Grok 模式数据
对应 pygrok patterns/grok-patterns 文件
"""

PATTERNS = [
    {
        "name": "USERNAME",
        "pattern": r"[a-zA-Z0-9._-]+",
        "sample": "john.doe-01",
        "description": "匹配用户名，由字母、数字、点号、下划线和连字符组成",
    },
    {
        "name": "USER",
        "pattern": r"%{USERNAME}",
        "sample": "john.doe-01",
        "description": "用户名的别名，等同于 USERNAME",
    },
    {
        "name": "EMAILLOCALPART",
        "pattern": r"[a-zA-Z][a-zA-Z0-9_.+-=:]+",
        "sample": "user.name+tag",
        "description": "匹配电子邮件地址的本地部分（@符号前的部分）",
    },
    {
        "name": "EMAILADDRESS",
        "pattern": r"%{EMAILLOCALPART}@%{HOSTNAME}",
        "sample": "user.name@example.com",
        "description": "匹配完整的电子邮件地址",
    },
    {
        "name": "HTTPDUSER",
        "pattern": r"%{EMAILADDRESS}|%{USER}",
        "sample": "user.name@example.com",
        "description": "匹配 HTTP 服务用户标识，可以是邮箱地址或用户名",
    },
    {
        "name": "INT",
        "pattern": r"(?:[+-]?(?:[0-9]+))",
        "sample": "-42",
        "description": "匹配整数，支持正负号",
    },
    {
        "name": "BASE10NUM",
        "pattern": r"(?<![0-9.+-])(?>[+-]?(?:(?:[0-9]+(?:\.[0-9]+)?)|(?:\.[0-9]+)))",
        "sample": "3.14",
        "description": "匹配十进制数字，包括整数和浮点数",
    },
    {
        "name": "NUMBER",
        "pattern": r"(?:%{BASE10NUM})",
        "sample": "3.14",
        "description": "匹配数字，等同于 BASE10NUM",
    },
    {
        "name": "BASE16NUM",
        "pattern": r"(?<![0-9A-Fa-f])(?:[+-]?(?:0x)?(?:[0-9A-Fa-f]+))",
        "sample": "0x1A3F",
        "description": "匹配十六进制数字，支持可选的 0x 前缀",
    },
    {
        "name": "BASE16FLOAT",
        "pattern": r"\b(?<![0-9A-Fa-f.])(?:[+-]?(?:0x)?(?:(?:[0-9A-Fa-f]+(?:\.[0-9A-Fa-f]*)?)|(?:\.[0-9A-Fa-f]+)))\b",
        "sample": "0x1A.3F",
        "description": "匹配十六进制浮点数",
    },
    {
        "name": "POSINT",
        "pattern": r"\b(?:[1-9][0-9]*)\b",
        "sample": "42",
        "description": "匹配正整数（不含零）",
    },
    {
        "name": "NONNEGINT",
        "pattern": r"\b(?:[0-9]+)\b",
        "sample": "0",
        "description": "匹配非负整数（含零）",
    },
    {
        "name": "WORD",
        "pattern": r"\b\w+\b",
        "sample": "hello",
        "description": "匹配一个单词，由字母、数字和下划线组成",
    },
    {
        "name": "NOTSPACE",
        "pattern": r"\S+",
        "sample": "no-spaces-here",
        "description": "匹配不含空白字符的字符串",
    },
    {
        "name": "SPACE",
        "pattern": r"\s*",
        "sample": "   ",
        "description": "匹配零个或多个空白字符",
    },
    {
        "name": "DATA",
        "pattern": r".*?",
        "sample": "some data here",
        "description": "匹配任意字符（非贪婪模式），通常用于捕获中间内容",
    },
    {
        "name": "GREEDYDATA",
        "pattern": r".*",
        "sample": "anything goes here including spaces and symbols!@#",
        "description": "匹配任意字符（贪婪模式），通常用于捕获剩余全部内容",
    },
    {
        "name": "QUOTEDSTRING",
        "pattern": r"""(?>(?<!\\)(?>"(?>\\.|[^\\"]+)+"|""|(?>'(?>\\.|[^\\']+)+')|''|(?>`(?>\\.|[^\\`]+)+`)|``))""",
        "sample": '"hello world"',
        "description": "匹配带引号的字符串，支持双引号、单引号和反引号",
    },
    {
        "name": "UUID",
        "pattern": r"[A-Fa-f0-9]{8}-(?:[A-Fa-f0-9]{4}-){3}[A-Fa-f0-9]{12}",
        "sample": "550e8400-e29b-41d4-a716-446655440000",
        "description": "匹配 UUID（通用唯一标识符）格式的字符串",
    },
    # 网络相关
    {
        "name": "CISCOMAC",
        "pattern": r"(?:(?:[A-Fa-f0-9]{4}\.){2}[A-Fa-f0-9]{4})",
        "sample": "0a1b.2c3d.4e5f",
        "description": "匹配 Cisco 格式的 MAC 地址（如 0a1b.2c3d.4e5f）",
    },
    {
        "name": "WINDOWSMAC",
        "pattern": r"(?:(?:[A-Fa-f0-9]{2}-){5}[A-Fa-f0-9]{2})",
        "sample": "0A-1B-2C-3D-4E-5F",
        "description": "匹配 Windows 格式的 MAC 地址（如 0A-1B-2C-3D-4E-5F）",
    },
    {
        "name": "COMMONMAC",
        "pattern": r"(?:(?:[A-Fa-f0-9]{2}:){5}[A-Fa-f0-9]{2})",
        "sample": "0a:1b:2c:3d:4e:5f",
        "description": "匹配通用格式的 MAC 地址（如 0a:1b:2c:3d:4e:5f）",
    },
    {
        "name": "MAC",
        "pattern": r"(?:%{CISCOMAC}|%{WINDOWSMAC}|%{COMMONMAC})",
        "sample": "0a:1b:2c:3d:4e:5f",
        "description": "匹配 MAC 地址，支持 Cisco、Windows 和通用格式",
    },
    {
        "name": "IPV6",
        "pattern": r"((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?",
        "sample": "2001:0db8:85a3:0000:0000:8a2e:0370:7334",
        "description": "匹配 IPv6 地址",
    },
    {
        "name": "IPV4",
        "pattern": r"(?<![0-9])(?:(?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5]))(?![0-9])",
        "sample": "192.168.1.1",
        "description": "匹配 IPv4 地址",
    },
    {
        "name": "IP",
        "pattern": r"(?:%{IPV6}|%{IPV4})",
        "sample": "192.168.1.1",
        "description": "匹配 IP 地址，支持 IPv4 和 IPv6",
    },
    {
        "name": "HOSTNAME",
        "pattern": r"\b(?:[0-9A-Za-z][0-9A-Za-z-]{0,62})(?:\.(?:[0-9A-Za-z][0-9A-Za-z-]{0,62}))*(\.?|\b)",
        "sample": "www.example.com",
        "description": "匹配主机名（域名）",
    },
    {
        "name": "IPORHOST",
        "pattern": r"(?:%{IP}|%{HOSTNAME})",
        "sample": "www.example.com",
        "description": "匹配 IP 地址或主机名",
    },
    {
        "name": "HOSTPORT",
        "pattern": r"%{IPORHOST}:%{POSINT}",
        "sample": "www.example.com:8080",
        "description": "匹配主机名或 IP 地址加端口号",
    },
    # 路径相关
    {
        "name": "UNIXPATH",
        "pattern": r"(/([\w_%!$@:.,~-]+|\\.)*)+",
        "sample": "/var/log/syslog",
        "description": "匹配 Unix 文件路径",
    },
    {
        "name": "TTY",
        "pattern": r"(?:/dev/(pts|tty([pq])?)(\w+)?/?(?:[0-9]+))",
        "sample": "/dev/pts/0",
        "description": "匹配终端设备路径（TTY）",
    },
    {
        "name": "WINPATH",
        "pattern": r"(?>[A-Za-z]+:|\\)(?:\\[^\\?*]*)+",
        "sample": r"C:\Windows\System32\config",
        "description": "匹配 Windows 文件路径",
    },
    {
        "name": "PATH",
        "pattern": r"(?:%{UNIXPATH}|%{WINPATH})",
        "sample": "/var/log/syslog",
        "description": "匹配文件路径，支持 Unix 和 Windows 格式",
    },
    # URI 相关
    {
        "name": "URIPROTO",
        "pattern": r"[A-Za-z]+(\+[A-Za-z+]+)?",
        "sample": "https",
        "description": "匹配 URI 协议（如 http、https、ftp）",
    },
    {
        "name": "URIHOST",
        "pattern": r"%{IPORHOST}(?::%{POSINT:port})?",
        "sample": "www.example.com:443",
        "description": "匹配 URI 中的主机部分，可包含端口号",
    },
    {
        "name": "URIPATH",
        "pattern": r"(?:/[A-Za-z0-9$.+!*'(){},~:;=@#%_\-]*)+",
        "sample": "/api/v1/users",
        "description": "匹配 URI 的路径部分",
    },
    {
        "name": "URIPARAM",
        "pattern": r"\?[A-Za-z0-9$.+!*'|(){},~@#%&/=:;_?\-\[\]<>]*",
        "sample": "?page=1&size=10",
        "description": "匹配 URI 的查询参数部分",
    },
    {
        "name": "URIPATHPARAM",
        "pattern": r"%{URIPATH}(?:%{URIPARAM})?",
        "sample": "/api/v1/users?page=1&size=10",
        "description": "匹配 URI 的路径和查询参数部分",
    },
    {
        "name": "URI",
        "pattern": r"%{URIPROTO}://(?:%{USER}(?::[^@]*)?@)?(?:%{URIHOST})?(?:%{URIPATHPARAM})?",
        "sample": "https://www.example.com/api/v1/users?page=1",
        "description": "匹配完整的 URI 地址",
    },
    # 日期时间相关
    {
        "name": "MONTH",
        "pattern": r"\b(?:Jan(?:uary|uar)?|Feb(?:ruary|ruar)?|M(?:a|ä)?r(?:ch|z)?|Apr(?:il)?|Ma(?:y|i)?|Jun(?:e|i)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|O(?:c|k)?t(?:ober)?|Nov(?:ember)?|De(?:c|z)(?:ember)?)\b",
        "sample": "January",
        "description": "匹配月份名称，支持英文全称和缩写",
    },
    {
        "name": "MONTHNUM",
        "pattern": r"(?:0?[1-9]|1[0-2])",
        "sample": "12",
        "description": "匹配月份数字（1-12），前导零可选",
    },
    {
        "name": "MONTHNUM2",
        "pattern": r"(?:0[1-9]|1[0-2])",
        "sample": "03",
        "description": "匹配月份数字（01-12），必须包含前导零",
    },
    {
        "name": "MONTHDAY",
        "pattern": r"(?:(?:0[1-9])|(?:[12][0-9])|(?:3[01])|[1-9])",
        "sample": "15",
        "description": "匹配月份中的日期（1-31）",
    },
    {
        "name": "DAY",
        "pattern": r"(?:Mon(?:day)?|Tue(?:sday)?|Wed(?:nesday)?|Thu(?:rsday)?|Fri(?:day)?|Sat(?:urday)?|Sun(?:day)?)",
        "sample": "Monday",
        "description": "匹配星期名称，支持英文全称和缩写",
    },
    {
        "name": "YEAR",
        "pattern": r"(?>\d\d){1,2}",
        "sample": "2024",
        "description": "匹配年份，支持两位或四位数字",
    },
    {
        "name": "HOUR",
        "pattern": r"(?:2[0123]|[01]?[0-9])",
        "sample": "14",
        "description": "匹配小时数（0-23）",
    },
    {
        "name": "MINUTE",
        "pattern": r"(?:[0-5][0-9])",
        "sample": "30",
        "description": "匹配分钟数（00-59）",
    },
    {
        "name": "SECOND",
        "pattern": r"(?:(?:[0-5]?[0-9]|60)(?:[:.,][0-9]+)?)",
        "sample": "59",
        "description": "匹配秒数（0-60，60 为闰秒），支持小数部分",
    },
    {
        "name": "TIME",
        "pattern": r"(?!<[0-9])%{HOUR}:%{MINUTE}(?::%{SECOND})(?![0-9])",
        "sample": "14:30:59",
        "description": "匹配时间（时:分:秒）",
    },
    {
        "name": "DATE_US",
        "pattern": r"%{MONTHNUM}[/-]%{MONTHDAY}[/-]%{YEAR}",
        "sample": "03/15/2024",
        "description": "匹配美国日期格式（月/日/年）",
    },
    {
        "name": "DATE_EU",
        "pattern": r"%{MONTHDAY}[./-]%{MONTHNUM}[./-]%{YEAR}",
        "sample": "15.03.2024",
        "description": "匹配欧洲日期格式（日.月.年）",
    },
    {
        "name": "ISO8601_TIMEZONE",
        "pattern": r"(?:Z|[+-]%{HOUR}(?::?%{MINUTE}))",
        "sample": "+08:00",
        "description": "匹配 ISO8601 时区偏移（如 Z、+08:00、-0500）",
    },
    {
        "name": "ISO8601_SECOND",
        "pattern": r"(?:%{SECOND}|60)",
        "sample": "59",
        "description": "匹配 ISO8601 秒数，支持闰秒",
    },
    {
        "name": "TIMESTAMP_ISO8601",
        "pattern": r"%{YEAR}-%{MONTHNUM}-%{MONTHDAY}[T ]%{HOUR}:?%{MINUTE}(?::?%{SECOND})?%{ISO8601_TIMEZONE}?",
        "sample": "2024-03-15T14:30:59+08:00",
        "description": "匹配 ISO8601 格式的时间戳",
    },
    {
        "name": "DATE",
        "pattern": r"%{DATE_US}|%{DATE_EU}",
        "sample": "03/15/2024",
        "description": "匹配日期，支持美国和欧洲格式",
    },
    {
        "name": "DATESTAMP",
        "pattern": r"%{DATE}[- ]%{TIME}",
        "sample": "03/15/2024-14:30:59",
        "description": "匹配日期加时间的组合",
    },
    {
        "name": "TZ",
        "pattern": r"(?:[PMCE][SD]T|UTC)",
        "sample": "UTC",
        "description": "匹配时区缩写（如 UTC、EST、PST、CST）",
    },
    {
        "name": "DATESTAMP_RFC822",
        "pattern": r"%{DAY} %{MONTH} %{MONTHDAY} %{YEAR} %{TIME} %{TZ}",
        "sample": "Mon Jan 15 2024 14:30:59 UTC",
        "description": "匹配 RFC822 格式的日期时间戳",
    },
    {
        "name": "DATESTAMP_RFC2822",
        "pattern": r"%{DAY}, %{MONTHDAY} %{MONTH} %{YEAR} %{TIME} %{ISO8601_TIMEZONE}",
        "sample": "Mon, 15 Jan 2024 14:30:59 +0800",
        "description": "匹配 RFC2822 格式的日期时间戳",
    },
    {
        "name": "DATESTAMP_OTHER",
        "pattern": r"%{DAY} %{MONTH} %{MONTHDAY} %{TIME} %{TZ} %{YEAR}",
        "sample": "Mon Jan 15 14:30:59 UTC 2024",
        "description": "匹配其他常见日期时间戳格式",
    },
    {
        "name": "DATESTAMP_EVENTLOG",
        "pattern": r"%{YEAR}%{MONTHNUM2}%{MONTHDAY}%{HOUR}%{MINUTE}%{SECOND}",
        "sample": "20240315143059",
        "description": "匹配事件日志格式的紧凑时间戳（无分隔符）",
    },
    {
        "name": "HTTPDERROR_DATE",
        "pattern": r"%{DAY} %{MONTH} %{MONTHDAY} %{TIME} %{YEAR}",
        "sample": "Fri Mar 15 14:30:59 2024",
        "description": "匹配 Apache HTTPD 错误日志中的日期格式",
    },
    # Syslog 相关
    {
        "name": "SYSLOGTIMESTAMP",
        "pattern": r"%{MONTH} +%{MONTHDAY} %{TIME}",
        "sample": "Mar 15 14:30:59",
        "description": "匹配 Syslog 时间戳格式",
    },
    {
        "name": "PROG",
        "pattern": r"[\x21-\x5a\x5c\x5e-\x7e]+",
        "sample": "sshd",
        "description": "匹配程序名称（可打印 ASCII 字符）",
    },
    {
        "name": "SYSLOGPROG",
        "pattern": r"%{PROG:program}(?:\[%{POSINT:pid}\])?",
        "sample": "sshd[12345]",
        "description": "匹配 Syslog 程序名及可选的进程 ID",
    },
    {
        "name": "SYSLOGHOST",
        "pattern": r"%{IPORHOST}",
        "sample": "myhost.example.com",
        "description": "匹配 Syslog 主机名或 IP 地址",
    },
    {
        "name": "SYSLOGFACILITY",
        "pattern": r"<%{NONNEGINT:facility}.%{NONNEGINT:priority}>",
        "sample": "<13.6>",
        "description": "匹配 Syslog 设施和优先级标识",
    },
    {
        "name": "HTTPDATE",
        "pattern": r"%{MONTHDAY}/%{MONTH}/%{YEAR}:%{TIME} %{INT}",
        "sample": "15/Mar/2024:14:30:59 +0800",
        "description": "匹配 HTTP 日志中的日期格式",
    },
    # 快捷方式
    {
        "name": "QS",
        "pattern": r"%{QUOTEDSTRING}",
        "sample": '"hello world"',
        "description": "带引号字符串的快捷方式，等同于 QUOTEDSTRING",
    },
    # 日志格式
    {
        "name": "SYSLOGBASE",
        "pattern": r"%{SYSLOGTIMESTAMP:timestamp} (?:%{SYSLOGFACILITY} )?%{SYSLOGHOST:logsource} %{SYSLOGPROG}:",
        "sample": "Mar 15 14:30:59 myhost.example.com sshd[12345]:",
        "description": "匹配 Syslog 日志的基础前缀部分（时间戳、主机、程序名）",
    },
    {
        "name": "COMMONAPACHELOG",
        "pattern": r'%{IPORHOST:clientip} %{HTTPDUSER:ident} %{USER:auth} \[%{HTTPDATE:timestamp}\] "(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})" %{NUMBER:response} (?:%{NUMBER:bytes}|-)',
        "sample": '192.168.1.1 - frank [15/Mar/2024:14:30:59 +0800] "GET /api/v1/users HTTP/1.1" 200 1234',
        "description": "匹配 Apache Common 日志格式",
    },
    {
        "name": "COMBINEDAPACHELOG",
        "pattern": r"%{COMMONAPACHELOG} %{QS:referrer} %{QS:agent}",
        "sample": '192.168.1.1 - frank [15/Mar/2024:14:30:59 +0800] "GET /api/v1/users HTTP/1.1" 200 1234 "https://example.com" "Mozilla/5.0"',
        "description": "匹配 Apache Combined 日志格式（在 Common 基础上增加了 Referer 和 User-Agent）",
    },
    {
        "name": "HTTPD20_ERRORLOG",
        "pattern": r"\[%{HTTPDERROR_DATE:timestamp}\] \[%{LOGLEVEL:loglevel}\] (?:\[client %{IPORHOST:clientip}\] ){0,1}%{GREEDYDATA:errormsg}",
        "sample": "[Fri Mar 15 14:30:59 2024] [error] [client 192.168.1.1] File not found: /var/www/html/favicon.ico",
        "description": "匹配 Apache HTTPD 2.0 错误日志格式",
    },
    {
        "name": "HTTPD24_ERRORLOG",
        "pattern": r"\[%{HTTPDERROR_DATE:timestamp}\] \[%{WORD:module}:%{LOGLEVEL:loglevel}\] \[pid %{POSINT:pid}:tid %{NUMBER:tid}\]( \(%{POSINT:proxy_errorcode}\)%{DATA:proxy_errormessage}:)?( \[client %{IPORHOST:client}:%{POSINT:clientport}\])? %{DATA:errorcode}: %{GREEDYDATA:message}",
        "sample": "[Fri Mar 15 14:30:59 2024] [core:error] [pid 12345:tid 139876543210] [client 192.168.1.1:54321] AH00124: Request exceeded the limit",
        "description": "匹配 Apache HTTPD 2.4 错误日志格式",
    },
    {
        "name": "HTTPD_ERRORLOG",
        "pattern": r"%{HTTPD20_ERRORLOG}|%{HTTPD24_ERRORLOG}",
        "sample": "[Fri Mar 15 14:30:59 2024] [error] [client 192.168.1.1] File not found: /var/www/html/favicon.ico",
        "description": "匹配 Apache HTTPD 错误日志格式，兼容 2.0 和 2.4 版本",
    },
    # 日志级别
    {
        "name": "LOGLEVEL",
        "pattern": r"([Aa]lert|ALERT|[Tt]race|TRACE|[Dd]ebug|DEBUG|[Nn]otice|NOTICE|[Ii]nfo|INFO|[Ww]arn?(?:ing)?|WARN?(?:ING)?|[Ee]rr?(?:or)?|ERR?(?:OR)?|[Cc]rit?(?:ical)?|CRIT?(?:ICAL)?|[Ff]atal|FATAL|[Ss]evere|SEVERE|EMERG(?:ENCY)?|[Ee]merg(?:ency)?)",
        "sample": "ERROR",
        "description": "匹配日志级别（如 DEBUG、INFO、WARN、ERROR、FATAL 等），大小写不敏感",
    },
]
