"""
Nagios 监控系统相关 Grok 模式数据
对应 pygrok patterns/nagios 文件
"""

PATTERNS = [
    # 时间戳
    {
        "name": "NAGIOSTIME",
        "pattern": r"\[%{NUMBER:nagios_epoch}\]",
        "sample": "[1710489059]",
        "description": "匹配 Nagios 日志时间戳（Unix 纪元时间）",
    },
    # 日志类型常量
    {
        "name": "NAGIOS_TYPE_CURRENT_SERVICE_STATE",
        "pattern": r"CURRENT SERVICE STATE",
        "sample": "CURRENT SERVICE STATE",
        "description": "匹配 Nagios 当前服务状态类型标识",
    },
    {
        "name": "NAGIOS_TYPE_CURRENT_HOST_STATE",
        "pattern": r"CURRENT HOST STATE",
        "sample": "CURRENT HOST STATE",
        "description": "匹配 Nagios 当前主机状态类型标识",
    },
    {
        "name": "NAGIOS_TYPE_SERVICE_NOTIFICATION",
        "pattern": r"SERVICE NOTIFICATION",
        "sample": "SERVICE NOTIFICATION",
        "description": "匹配 Nagios 服务通知类型标识",
    },
    {
        "name": "NAGIOS_TYPE_HOST_NOTIFICATION",
        "pattern": r"HOST NOTIFICATION",
        "sample": "HOST NOTIFICATION",
        "description": "匹配 Nagios 主机通知类型标识",
    },
    {
        "name": "NAGIOS_TYPE_SERVICE_ALERT",
        "pattern": r"SERVICE ALERT",
        "sample": "SERVICE ALERT",
        "description": "匹配 Nagios 服务告警类型标识",
    },
    {
        "name": "NAGIOS_TYPE_HOST_ALERT",
        "pattern": r"HOST ALERT",
        "sample": "HOST ALERT",
        "description": "匹配 Nagios 主机告警类型标识",
    },
    {
        "name": "NAGIOS_TYPE_SERVICE_FLAPPING_ALERT",
        "pattern": r"SERVICE FLAPPING ALERT",
        "sample": "SERVICE FLAPPING ALERT",
        "description": "匹配 Nagios 服务抖动告警类型标识",
    },
    {
        "name": "NAGIOS_TYPE_HOST_FLAPPING_ALERT",
        "pattern": r"HOST FLAPPING ALERT",
        "sample": "HOST FLAPPING ALERT",
        "description": "匹配 Nagios 主机抖动告警类型标识",
    },
    {
        "name": "NAGIOS_TYPE_SERVICE_DOWNTIME_ALERT",
        "pattern": r"SERVICE DOWNTIME ALERT",
        "sample": "SERVICE DOWNTIME ALERT",
        "description": "匹配 Nagios 服务停机告警类型标识",
    },
    {
        "name": "NAGIOS_TYPE_HOST_DOWNTIME_ALERT",
        "pattern": r"HOST DOWNTIME ALERT",
        "sample": "HOST DOWNTIME ALERT",
        "description": "匹配 Nagios 主机停机告警类型标识",
    },
    {
        "name": "NAGIOS_TYPE_PASSIVE_SERVICE_CHECK",
        "pattern": r"PASSIVE SERVICE CHECK",
        "sample": "PASSIVE SERVICE CHECK",
        "description": "匹配 Nagios 被动服务检查类型标识",
    },
    {
        "name": "NAGIOS_TYPE_PASSIVE_HOST_CHECK",
        "pattern": r"PASSIVE HOST CHECK",
        "sample": "PASSIVE HOST CHECK",
        "description": "匹配 Nagios 被动主机检查类型标识",
    },
    {
        "name": "NAGIOS_TYPE_SERVICE_EVENT_HANDLER",
        "pattern": r"SERVICE EVENT HANDLER",
        "sample": "SERVICE EVENT HANDLER",
        "description": "匹配 Nagios 服务事件处理器类型标识",
    },
    {
        "name": "NAGIOS_TYPE_HOST_EVENT_HANDLER",
        "pattern": r"HOST EVENT HANDLER",
        "sample": "HOST EVENT HANDLER",
        "description": "匹配 Nagios 主机事件处理器类型标识",
    },
    {
        "name": "NAGIOS_TYPE_EXTERNAL_COMMAND",
        "pattern": r"EXTERNAL COMMAND",
        "sample": "EXTERNAL COMMAND",
        "description": "匹配 Nagios 外部命令类型标识",
    },
    {
        "name": "NAGIOS_TYPE_TIMEPERIOD_TRANSITION",
        "pattern": r"TIMEPERIOD TRANSITION",
        "sample": "TIMEPERIOD TRANSITION",
        "description": "匹配 Nagios 时间段切换类型标识",
    },
    # 外部检查命令常量
    {
        "name": "NAGIOS_EC_DISABLE_SVC_CHECK",
        "pattern": r"DISABLE_SVC_CHECK",
        "sample": "DISABLE_SVC_CHECK",
        "description": "匹配 Nagios 禁用服务检查命令标识",
    },
    {
        "name": "NAGIOS_EC_ENABLE_SVC_CHECK",
        "pattern": r"ENABLE_SVC_CHECK",
        "sample": "ENABLE_SVC_CHECK",
        "description": "匹配 Nagios 启用服务检查命令标识",
    },
    {
        "name": "NAGIOS_EC_DISABLE_HOST_CHECK",
        "pattern": r"DISABLE_HOST_CHECK",
        "sample": "DISABLE_HOST_CHECK",
        "description": "匹配 Nagios 禁用主机检查命令标识",
    },
    {
        "name": "NAGIOS_EC_ENABLE_HOST_CHECK",
        "pattern": r"ENABLE_HOST_CHECK",
        "sample": "ENABLE_HOST_CHECK",
        "description": "匹配 Nagios 启用主机检查命令标识",
    },
    {
        "name": "NAGIOS_EC_PROCESS_SERVICE_CHECK_RESULT",
        "pattern": r"PROCESS_SERVICE_CHECK_RESULT",
        "sample": "PROCESS_SERVICE_CHECK_RESULT",
        "description": "匹配 Nagios 处理服务检查结果命令标识",
    },
    {
        "name": "NAGIOS_EC_PROCESS_HOST_CHECK_RESULT",
        "pattern": r"PROCESS_HOST_CHECK_RESULT",
        "sample": "PROCESS_HOST_CHECK_RESULT",
        "description": "匹配 Nagios 处理主机检查结果命令标识",
    },
    {
        "name": "NAGIOS_EC_SCHEDULE_SERVICE_DOWNTIME",
        "pattern": r"SCHEDULE_SERVICE_DOWNTIME",
        "sample": "SCHEDULE_SERVICE_DOWNTIME",
        "description": "匹配 Nagios 调度服务停机命令标识",
    },
    {
        "name": "NAGIOS_EC_SCHEDULE_HOST_DOWNTIME",
        "pattern": r"SCHEDULE_HOST_DOWNTIME",
        "sample": "SCHEDULE_HOST_DOWNTIME",
        "description": "匹配 Nagios 调度主机停机命令标识",
    },
    {
        "name": "NAGIOS_EC_DISABLE_HOST_SVC_NOTIFICATIONS",
        "pattern": r"DISABLE_HOST_SVC_NOTIFICATIONS",
        "sample": "DISABLE_HOST_SVC_NOTIFICATIONS",
        "description": "匹配 Nagios 禁用主机服务通知命令标识",
    },
    {
        "name": "NAGIOS_EC_ENABLE_HOST_SVC_NOTIFICATIONS",
        "pattern": r"ENABLE_HOST_SVC_NOTIFICATIONS",
        "sample": "ENABLE_HOST_SVC_NOTIFICATIONS",
        "description": "匹配 Nagios 启用主机服务通知命令标识",
    },
    {
        "name": "NAGIOS_EC_DISABLE_HOST_NOTIFICATIONS",
        "pattern": r"DISABLE_HOST_NOTIFICATIONS",
        "sample": "DISABLE_HOST_NOTIFICATIONS",
        "description": "匹配 Nagios 禁用主机通知命令标识",
    },
    {
        "name": "NAGIOS_EC_ENABLE_HOST_NOTIFICATIONS",
        "pattern": r"ENABLE_HOST_NOTIFICATIONS",
        "sample": "ENABLE_HOST_NOTIFICATIONS",
        "description": "匹配 Nagios 启用主机通知命令标识",
    },
    {
        "name": "NAGIOS_EC_DISABLE_SVC_NOTIFICATIONS",
        "pattern": r"DISABLE_SVC_NOTIFICATIONS",
        "sample": "DISABLE_SVC_NOTIFICATIONS",
        "description": "匹配 Nagios 禁用服务通知命令标识",
    },
    {
        "name": "NAGIOS_EC_ENABLE_SVC_NOTIFICATIONS",
        "pattern": r"ENABLE_SVC_NOTIFICATIONS",
        "sample": "ENABLE_SVC_NOTIFICATIONS",
        "description": "匹配 Nagios 启用服务通知命令标识",
    },
    # 复合日志模式
    {
        "name": "NAGIOS_WARNING",
        "pattern": r"Warning:%{SPACE}%{GREEDYDATA:nagios_message}",
        "sample": "Warning: Service check result was received for host 'web01', but the host could not be found!",
        "description": "匹配 Nagios 警告消息",
    },
    {
        "name": "NAGIOS_CURRENT_SERVICE_STATE",
        "pattern": r"%{NAGIOS_TYPE_CURRENT_SERVICE_STATE:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_service};%{DATA:nagios_state};%{DATA:nagios_statetype};%{DATA:nagios_statecode};%{GREEDYDATA:nagios_message}",
        "sample": "CURRENT SERVICE STATE: web01;HTTP;OK;HARD;1;HTTP OK: HTTP/1.1 200 OK - 0.123 second response time",
        "description": "匹配 Nagios 当前服务状态日志，包含主机名、服务名、状态和消息",
    },
    {
        "name": "NAGIOS_CURRENT_HOST_STATE",
        "pattern": r"%{NAGIOS_TYPE_CURRENT_HOST_STATE:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_state};%{DATA:nagios_statetype};%{DATA:nagios_statecode};%{GREEDYDATA:nagios_message}",
        "sample": "CURRENT HOST STATE: web01;UP;HARD;1;PING OK - Packet loss = 0%, RTA = 0.50 ms",
        "description": "匹配 Nagios 当前主机状态日志",
    },
    {
        "name": "NAGIOS_SERVICE_NOTIFICATION",
        "pattern": r"%{NAGIOS_TYPE_SERVICE_NOTIFICATION:nagios_type}: %{DATA:nagios_notifyname};%{DATA:nagios_hostname};%{DATA:nagios_service};%{DATA:nagios_state};%{DATA:nagios_contact};%{GREEDYDATA:nagios_message}",
        "sample": "SERVICE NOTIFICATION: admin;web01;HTTP;CRITICAL;notify-by-email;Connection refused",
        "description": "匹配 Nagios 服务通知日志",
    },
    {
        "name": "NAGIOS_HOST_NOTIFICATION",
        "pattern": r"%{NAGIOS_TYPE_HOST_NOTIFICATION:nagios_type}: %{DATA:nagios_notifyname};%{DATA:nagios_hostname};%{DATA:nagios_state};%{DATA:nagios_contact};%{GREEDYDATA:nagios_message}",
        "sample": "HOST NOTIFICATION: admin;web01;DOWN;notify-by-email;PING CRITICAL - Packet loss = 100%",
        "description": "匹配 Nagios 主机通知日志",
    },
    {
        "name": "NAGIOS_SERVICE_ALERT",
        "pattern": r"%{NAGIOS_TYPE_SERVICE_ALERT:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_service};%{DATA:nagios_state};%{DATA:nagios_statelevel};%{NUMBER:nagios_attempt};%{GREEDYDATA:nagios_message}",
        "sample": "SERVICE ALERT: web01;HTTP;CRITICAL;SOFT;1;Connection refused",
        "description": "匹配 Nagios 服务告警日志",
    },
    {
        "name": "NAGIOS_HOST_ALERT",
        "pattern": r"%{NAGIOS_TYPE_HOST_ALERT:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_state};%{DATA:nagios_statelevel};%{NUMBER:nagios_attempt};%{GREEDYDATA:nagios_message}",
        "sample": "HOST ALERT: web01;DOWN;SOFT;1;PING CRITICAL - Packet loss = 100%",
        "description": "匹配 Nagios 主机告警日志",
    },
    {
        "name": "NAGIOS_SERVICE_FLAPPING_ALERT",
        "pattern": r"%{NAGIOS_TYPE_SERVICE_FLAPPING_ALERT:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_service};%{DATA:nagios_state};%{GREEDYDATA:nagios_message}",
        "sample": "SERVICE FLAPPING ALERT: web01;HTTP;STARTED;Service appears to have started flapping (24.2% change >= 20.0% threshold)",
        "description": "匹配 Nagios 服务抖动告警日志",
    },
    {
        "name": "NAGIOS_HOST_FLAPPING_ALERT",
        "pattern": r"%{NAGIOS_TYPE_HOST_FLAPPING_ALERT:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_state};%{GREEDYDATA:nagios_message}",
        "sample": "HOST FLAPPING ALERT: web01;STARTED;Host appears to have started flapping (28.5% change >= 20.0% threshold)",
        "description": "匹配 Nagios 主机抖动告警日志",
    },
    {
        "name": "NAGIOS_SERVICE_DOWNTIME_ALERT",
        "pattern": r"%{NAGIOS_TYPE_SERVICE_DOWNTIME_ALERT:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_service};%{DATA:nagios_state};%{GREEDYDATA:nagios_comment}",
        "sample": "SERVICE DOWNTIME ALERT: web01;HTTP;STARTED;Service has entered a period of scheduled downtime",
        "description": "匹配 Nagios 服务停机告警日志",
    },
    {
        "name": "NAGIOS_HOST_DOWNTIME_ALERT",
        "pattern": r"%{NAGIOS_TYPE_HOST_DOWNTIME_ALERT:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_state};%{GREEDYDATA:nagios_comment}",
        "sample": "HOST DOWNTIME ALERT: web01;STARTED;Host has entered a period of scheduled downtime",
        "description": "匹配 Nagios 主机停机告警日志",
    },
    {
        "name": "NAGIOS_PASSIVE_SERVICE_CHECK",
        "pattern": r"%{NAGIOS_TYPE_PASSIVE_SERVICE_CHECK:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_service};%{DATA:nagios_state};%{GREEDYDATA:nagios_comment}",
        "sample": "PASSIVE SERVICE CHECK: web01;HTTP;0;HTTP OK - 200 response in 0.123s",
        "description": "匹配 Nagios 被动服务检查日志",
    },
    {
        "name": "NAGIOS_PASSIVE_HOST_CHECK",
        "pattern": r"%{NAGIOS_TYPE_PASSIVE_HOST_CHECK:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_state};%{GREEDYDATA:nagios_comment}",
        "sample": "PASSIVE HOST CHECK: web01;0;PING OK",
        "description": "匹配 Nagios 被动主机检查日志",
    },
    {
        "name": "NAGIOS_SERVICE_EVENT_HANDLER",
        "pattern": r"%{NAGIOS_TYPE_SERVICE_EVENT_HANDLER:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_service};%{DATA:nagios_state};%{DATA:nagios_statelevel};%{DATA:nagios_event_handler_name}",
        "sample": "SERVICE EVENT HANDLER: web01;HTTP;CRITICAL;HARD;restart-httpd",
        "description": "匹配 Nagios 服务事件处理器日志",
    },
    {
        "name": "NAGIOS_HOST_EVENT_HANDLER",
        "pattern": r"%{NAGIOS_TYPE_HOST_EVENT_HANDLER:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_state};%{DATA:nagios_statelevel};%{DATA:nagios_event_handler_name}",
        "sample": "HOST EVENT HANDLER: web01;DOWN;HARD;restart-host",
        "description": "匹配 Nagios 主机事件处理器日志",
    },
    {
        "name": "NAGIOS_TIMEPERIOD_TRANSITION",
        "pattern": r"%{NAGIOS_TYPE_TIMEPERIOD_TRANSITION:nagios_type}: %{DATA:nagios_service};%{DATA:nagios_unknown1};%{DATA:nagios_unknown2}",
        "sample": "TIMEPERIOD TRANSITION: 24x7;-1;1",
        "description": "匹配 Nagios 时间段切换日志",
    },
    # 外部命令日志行
    {
        "name": "NAGIOS_EC_LINE_DISABLE_SVC_CHECK",
        "pattern": r"%{NAGIOS_TYPE_EXTERNAL_COMMAND:nagios_type}: %{NAGIOS_EC_DISABLE_SVC_CHECK:nagios_command};%{DATA:nagios_hostname};%{DATA:nagios_service}",
        "sample": "EXTERNAL COMMAND: DISABLE_SVC_CHECK;web01;HTTP",
        "description": "匹配 Nagios 禁用服务检查外部命令日志",
    },
    {
        "name": "NAGIOS_EC_LINE_DISABLE_HOST_CHECK",
        "pattern": r"%{NAGIOS_TYPE_EXTERNAL_COMMAND:nagios_type}: %{NAGIOS_EC_DISABLE_HOST_CHECK:nagios_command};%{DATA:nagios_hostname}",
        "sample": "EXTERNAL COMMAND: DISABLE_HOST_CHECK;web01",
        "description": "匹配 Nagios 禁用主机检查外部命令日志",
    },
    {
        "name": "NAGIOS_EC_LINE_ENABLE_SVC_CHECK",
        "pattern": r"%{NAGIOS_TYPE_EXTERNAL_COMMAND:nagios_type}: %{NAGIOS_EC_ENABLE_SVC_CHECK:nagios_command};%{DATA:nagios_hostname};%{DATA:nagios_service}",
        "sample": "EXTERNAL COMMAND: ENABLE_SVC_CHECK;web01;HTTP",
        "description": "匹配 Nagios 启用服务检查外部命令日志",
    },
    {
        "name": "NAGIOS_EC_LINE_ENABLE_HOST_CHECK",
        "pattern": r"%{NAGIOS_TYPE_EXTERNAL_COMMAND:nagios_type}: %{NAGIOS_EC_ENABLE_HOST_CHECK:nagios_command};%{DATA:nagios_hostname}",
        "sample": "EXTERNAL COMMAND: ENABLE_HOST_CHECK;web01",
        "description": "匹配 Nagios 启用主机检查外部命令日志",
    },
    {
        "name": "NAGIOS_EC_LINE_PROCESS_SERVICE_CHECK_RESULT",
        "pattern": r"%{NAGIOS_TYPE_EXTERNAL_COMMAND:nagios_type}: %{NAGIOS_EC_PROCESS_SERVICE_CHECK_RESULT:nagios_command};%{DATA:nagios_hostname};%{DATA:nagios_service};%{DATA:nagios_state};%{GREEDYDATA:nagios_check_result}",
        "sample": "EXTERNAL COMMAND: PROCESS_SERVICE_CHECK_RESULT;web01;HTTP;0;HTTP OK - 200 response",
        "description": "匹配 Nagios 处理服务检查结果外部命令日志",
    },
    {
        "name": "NAGIOS_EC_LINE_PROCESS_HOST_CHECK_RESULT",
        "pattern": r"%{NAGIOS_TYPE_EXTERNAL_COMMAND:nagios_type}: %{NAGIOS_EC_PROCESS_HOST_CHECK_RESULT:nagios_command};%{DATA:nagios_hostname};%{DATA:nagios_state};%{GREEDYDATA:nagios_check_result}",
        "sample": "EXTERNAL COMMAND: PROCESS_HOST_CHECK_RESULT;web01;0;PING OK",
        "description": "匹配 Nagios 处理主机检查结果外部命令日志",
    },
    {
        "name": "NAGIOS_EC_LINE_DISABLE_HOST_SVC_NOTIFICATIONS",
        "pattern": r"%{NAGIOS_TYPE_EXTERNAL_COMMAND:nagios_type}: %{NAGIOS_EC_DISABLE_HOST_SVC_NOTIFICATIONS:nagios_command};%{GREEDYDATA:nagios_hostname}",
        "sample": "EXTERNAL COMMAND: DISABLE_HOST_SVC_NOTIFICATIONS;web01",
        "description": "匹配 Nagios 禁用主机服务通知外部命令日志",
    },
    {
        "name": "NAGIOS_EC_LINE_DISABLE_HOST_NOTIFICATIONS",
        "pattern": r"%{NAGIOS_TYPE_EXTERNAL_COMMAND:nagios_type}: %{NAGIOS_EC_DISABLE_HOST_NOTIFICATIONS:nagios_command};%{GREEDYDATA:nagios_hostname}",
        "sample": "EXTERNAL COMMAND: DISABLE_HOST_NOTIFICATIONS;web01",
        "description": "匹配 Nagios 禁用主机通知外部命令日志",
    },
    {
        "name": "NAGIOS_EC_LINE_DISABLE_SVC_NOTIFICATIONS",
        "pattern": r"%{NAGIOS_TYPE_EXTERNAL_COMMAND:nagios_type}: %{NAGIOS_EC_DISABLE_SVC_NOTIFICATIONS:nagios_command};%{DATA:nagios_hostname};%{GREEDYDATA:nagios_service}",
        "sample": "EXTERNAL COMMAND: DISABLE_SVC_NOTIFICATIONS;web01;HTTP",
        "description": "匹配 Nagios 禁用服务通知外部命令日志",
    },
    {
        "name": "NAGIOS_EC_LINE_ENABLE_HOST_SVC_NOTIFICATIONS",
        "pattern": r"%{NAGIOS_TYPE_EXTERNAL_COMMAND:nagios_type}: %{NAGIOS_EC_ENABLE_HOST_SVC_NOTIFICATIONS:nagios_command};%{GREEDYDATA:nagios_hostname}",
        "sample": "EXTERNAL COMMAND: ENABLE_HOST_SVC_NOTIFICATIONS;web01",
        "description": "匹配 Nagios 启用主机服务通知外部命令日志",
    },
    {
        "name": "NAGIOS_EC_LINE_ENABLE_HOST_NOTIFICATIONS",
        "pattern": r"%{NAGIOS_TYPE_EXTERNAL_COMMAND:nagios_type}: %{NAGIOS_EC_ENABLE_HOST_NOTIFICATIONS:nagios_command};%{GREEDYDATA:nagios_hostname}",
        "sample": "EXTERNAL COMMAND: ENABLE_HOST_NOTIFICATIONS;web01",
        "description": "匹配 Nagios 启用主机通知外部命令日志",
    },
    {
        "name": "NAGIOS_EC_LINE_ENABLE_SVC_NOTIFICATIONS",
        "pattern": r"%{NAGIOS_TYPE_EXTERNAL_COMMAND:nagios_type}: %{NAGIOS_EC_ENABLE_SVC_NOTIFICATIONS:nagios_command};%{DATA:nagios_hostname};%{GREEDYDATA:nagios_service}",
        "sample": "EXTERNAL COMMAND: ENABLE_SVC_NOTIFICATIONS;web01;HTTP",
        "description": "匹配 Nagios 启用服务通知外部命令日志",
    },
    {
        "name": "NAGIOS_EC_LINE_SCHEDULE_HOST_DOWNTIME",
        "pattern": r"%{NAGIOS_TYPE_EXTERNAL_COMMAND:nagios_type}: %{NAGIOS_EC_SCHEDULE_HOST_DOWNTIME:nagios_command};%{DATA:nagios_hostname};%{NUMBER:nagios_start_time};%{NUMBER:nagios_end_time};%{NUMBER:nagios_fixed};%{NUMBER:nagios_trigger_id};%{NUMBER:nagios_duration};%{DATA:author};%{DATA:comment}",
        "sample": "EXTERNAL COMMAND: SCHEDULE_HOST_DOWNTIME;web01;1710489059;1710492659;1;0;3600;admin;Scheduled maintenance",
        "description": "匹配 Nagios 调度主机停机外部命令日志",
    },
    # 完整日志行
    {
        "name": "NAGIOSLOGLINE",
        "pattern": r"%{NAGIOSTIME} (?:%{NAGIOS_WARNING}|%{NAGIOS_CURRENT_SERVICE_STATE}|%{NAGIOS_CURRENT_HOST_STATE}|%{NAGIOS_SERVICE_NOTIFICATION}|%{NAGIOS_HOST_NOTIFICATION}|%{NAGIOS_SERVICE_ALERT}|%{NAGIOS_HOST_ALERT}|%{NAGIOS_SERVICE_FLAPPING_ALERT}|%{NAGIOS_HOST_FLAPPING_ALERT}|%{NAGIOS_SERVICE_DOWNTIME_ALERT}|%{NAGIOS_HOST_DOWNTIME_ALERT}|%{NAGIOS_PASSIVE_SERVICE_CHECK}|%{NAGIOS_PASSIVE_HOST_CHECK}|%{NAGIOS_SERVICE_EVENT_HANDLER}|%{NAGIOS_HOST_EVENT_HANDLER}|%{NAGIOS_TIMEPERIOD_TRANSITION}|%{NAGIOS_EC_LINE_DISABLE_SVC_CHECK}|%{NAGIOS_EC_LINE_ENABLE_SVC_CHECK}|%{NAGIOS_EC_LINE_DISABLE_HOST_CHECK}|%{NAGIOS_EC_LINE_ENABLE_HOST_CHECK}|%{NAGIOS_EC_LINE_PROCESS_HOST_CHECK_RESULT}|%{NAGIOS_EC_LINE_PROCESS_SERVICE_CHECK_RESULT}|%{NAGIOS_EC_LINE_SCHEDULE_HOST_DOWNTIME}|%{NAGIOS_EC_LINE_DISABLE_HOST_SVC_NOTIFICATIONS}|%{NAGIOS_EC_LINE_ENABLE_HOST_SVC_NOTIFICATIONS}|%{NAGIOS_EC_LINE_DISABLE_HOST_NOTIFICATIONS}|%{NAGIOS_EC_LINE_ENABLE_HOST_NOTIFICATIONS}|%{NAGIOS_EC_LINE_DISABLE_SVC_NOTIFICATIONS}|%{NAGIOS_EC_LINE_ENABLE_SVC_NOTIFICATIONS})",
        "sample": "[1710489059] SERVICE ALERT: web01;HTTP;CRITICAL;SOFT;1;Connection refused",
        "description": "匹配 Nagios 完整日志行，包含时间戳和各类事件消息",
    },
]
