CUSTOM_TS_METRIC_GROUPS = {
    "metric_groups": [
        {
            "name": "内置指标",
            "metrics": [
                {
                    "metric_name": "SayHello_request_bytes_count",
                    "alias": "",
                    "dimensions": [
                        {"name": "_group", "alias": "分组"},
                        {"name": "app_name", "alias": ""},
                        {"name": "container_name", "alias": "容器名"},
                        {"name": "env_name", "alias": "用户环境"},
                        {"name": "instance", "alias": "实例"},
                        {"name": "monitor_name", "alias": "监控项名称"},
                        {"name": "namespace", "alias": "物理环境"},
                        {"name": "result_table_id", "alias": "逻辑结果表"},
                        {"name": "scope_name", "alias": "监控分组"},
                        {"name": "sdk_name", "alias": "SDK 名称"},
                        {"name": "service_name", "alias": "服务名"},
                        {"name": "target", "alias": "实体"},
                        {"name": "version", "alias": "SDK 版本"},
                    ],
                },
                {
                    "metric_name": "SayHello_request_count",
                    "alias": "SayHello 接口请求数",
                    "dimensions": [
                        {"name": "_group", "alias": "分组"},
                        {"name": "app_name", "alias": ""},
                        {"name": "container_name", "alias": "容器名"},
                        {"name": "env_name", "alias": "用户环境"},
                        {"name": "instance", "alias": "实例"},
                        {"name": "monitor_name", "alias": "监控项名称"},
                        {"name": "namespace", "alias": "物理环境"},
                        {"name": "result_table_id", "alias": "逻辑结果表"},
                        {"name": "scope_name", "alias": "监控分组"},
                        {"name": "sdk_name", "alias": "SDK 名称"},
                        {"name": "service_name", "alias": "服务名"},
                        {"name": "target", "alias": "实体"},
                        {"name": "version", "alias": "SDK 版本"},
                    ],
                },
                {
                    "metric_name": "bk_apm_count",
                    "alias": "Trace 分钟请求数",
                    "dimensions": [
                        {"name": "apdex_type", "alias": ""},
                        {"name": "app_name", "alias": ""},
                        {"name": "bk_instance_id", "alias": ""},
                        {"name": "db_name", "alias": "DB 名称"},
                        {"name": "db_system", "alias": ""},
                        {"name": "http_favor", "alias": ""},
                        {"name": "http_method", "alias": ""},
                        {"name": "http_scheme", "alias": ""},
                        {"name": "http_server_name", "alias": ""},
                        {"name": "http_status_code", "alias": "HTTP 状态码"},
                        {"name": "kind", "alias": "类型"},
                        {"name": "net_peer_name", "alias": ""},
                        {"name": "net_peer_port", "alias": "对端 Port"},
                        {"name": "result_table_id", "alias": "逻辑结果表"},
                        {"name": "service_name", "alias": "服务名"},
                        {"name": "service_version", "alias": ""},
                        {"name": "span_name", "alias": "Span 名称"},
                        {"name": "status_code", "alias": "Span 状态"},
                        {"name": "target", "alias": "实体"},
                        {"name": "telemetry_sdk_language", "alias": "SDK 语言"},
                        {"name": "telemetry_sdk_name", "alias": "SDK 名称"},
                        {"name": "telemetry_sdk_version", "alias": "SDK 版本"},
                    ],
                },
                {
                    "metric_name": "bk_apm_duration",
                    "alias": "Trace 请求耗时",
                    "dimensions": [
                        {"name": "apdex_type", "alias": ""},
                        {"name": "app_name", "alias": ""},
                        {"name": "bk_instance_id", "alias": ""},
                        {"name": "db_name", "alias": "DB 名称"},
                        {"name": "db_system", "alias": ""},
                        {"name": "http_favor", "alias": ""},
                        {"name": "http_method", "alias": ""},
                        {"name": "http_scheme", "alias": ""},
                        {"name": "http_server_name", "alias": ""},
                        {"name": "http_status_code", "alias": "HTTP 状态码"},
                        {"name": "kind", "alias": "类型"},
                        {"name": "net_peer_name", "alias": ""},
                        {"name": "net_peer_port", "alias": "对端 Port"},
                        {"name": "result_table_id", "alias": "逻辑结果表"},
                        {"name": "scope_name", "alias": "监控分组"},
                        {"name": "service_name", "alias": "服务名"},
                        {"name": "service_version", "alias": ""},
                        {"name": "span_name", "alias": "Span 名称"},
                        {"name": "status_code", "alias": "Span 状态"},
                        {"name": "target", "alias": "实体"},
                        {"name": "telemetry_sdk_language", "alias": "SDK 语言"},
                        {"name": "telemetry_sdk_name", "alias": "SDK 名称"},
                        {"name": "telemetry_sdk_version", "alias": "SDK 版本"},
                    ],
                },
                {
                    "metric_name": "bk_apm_duration_bucket",
                    "alias": "Trace 总请求耗时 bucket",
                    "dimensions": [
                        {"name": "apdex_type", "alias": ""},
                        {"name": "app_name", "alias": ""},
                        {"name": "bk_instance_id", "alias": ""},
                        {"name": "db_name", "alias": "DB 名称"},
                        {"name": "db_system", "alias": ""},
                        {"name": "http_favor", "alias": ""},
                        {"name": "http_method", "alias": ""},
                        {"name": "http_scheme", "alias": ""},
                        {"name": "http_server_name", "alias": ""},
                        {"name": "http_status_code", "alias": "HTTP 状态码"},
                        {"name": "kind", "alias": "类型"},
                        {"name": "le", "alias": ""},
                        {"name": "net_peer_name", "alias": ""},
                        {"name": "net_peer_port", "alias": "对端 Port"},
                        {"name": "result_table_id", "alias": "逻辑结果表"},
                        {"name": "service_name", "alias": "服务名"},
                        {"name": "service_version", "alias": ""},
                        {"name": "span_name", "alias": "Span 名称"},
                        {"name": "status_code", "alias": "Span 状态"},
                        {"name": "target", "alias": "实体"},
                        {"name": "telemetry_sdk_language", "alias": "SDK 语言"},
                        {"name": "telemetry_sdk_name", "alias": "SDK 名称"},
                        {"name": "telemetry_sdk_version", "alias": "SDK 版本"},
                    ],
                },
                {
                    "metric_name": "bk_apm_duration_delta",
                    "alias": "Trace 分钟总请求耗时",
                    "dimensions": [
                        {"name": "apdex_type", "alias": ""},
                        {"name": "app_name", "alias": ""},
                        {"name": "bk_instance_id", "alias": ""},
                        {"name": "db_name", "alias": "DB 名称"},
                        {"name": "db_system", "alias": ""},
                        {"name": "http_favor", "alias": ""},
                        {"name": "http_method", "alias": ""},
                        {"name": "http_scheme", "alias": ""},
                        {"name": "http_server_name", "alias": ""},
                        {"name": "http_status_code", "alias": "HTTP 状态码"},
                        {"name": "kind", "alias": "类型"},
                        {"name": "net_peer_name", "alias": ""},
                        {"name": "net_peer_port", "alias": "对端 Port"},
                        {"name": "result_table_id", "alias": "逻辑结果表"},
                        {"name": "service_name", "alias": "服务名"},
                        {"name": "service_version", "alias": ""},
                        {"name": "span_name", "alias": "Span 名称"},
                        {"name": "status_code", "alias": "Span 状态"},
                        {"name": "target", "alias": "实体"},
                        {"name": "telemetry_sdk_language", "alias": "SDK 语言"},
                        {"name": "telemetry_sdk_name", "alias": "SDK 名称"},
                        {"name": "telemetry_sdk_version", "alias": "SDK 版本"},
                    ],
                },
                {
                    "metric_name": "bk_apm_duration_max",
                    "alias": "Trace 分钟请求最大耗时",
                    "dimensions": [
                        {"name": "apdex_type", "alias": ""},
                        {"name": "app_name", "alias": ""},
                        {"name": "bk_instance_id", "alias": ""},
                        {"name": "db_name", "alias": "DB 名称"},
                        {"name": "db_system", "alias": ""},
                        {"name": "http_favor", "alias": ""},
                        {"name": "http_method", "alias": ""},
                        {"name": "http_scheme", "alias": ""},
                        {"name": "http_server_name", "alias": ""},
                        {"name": "http_status_code", "alias": "HTTP 状态码"},
                        {"name": "kind", "alias": "类型"},
                        {"name": "net_peer_name", "alias": ""},
                        {"name": "net_peer_port", "alias": "对端 Port"},
                        {"name": "result_table_id", "alias": "逻辑结果表"},
                        {"name": "service_name", "alias": "服务名"},
                        {"name": "service_version", "alias": ""},
                        {"name": "span_name", "alias": "Span 名称"},
                        {"name": "status_code", "alias": "Span 状态"},
                        {"name": "target", "alias": "实体"},
                        {"name": "telemetry_sdk_language", "alias": "SDK 语言"},
                        {"name": "telemetry_sdk_name", "alias": "SDK 名称"},
                        {"name": "telemetry_sdk_version", "alias": "SDK 版本"},
                    ],
                },
                {
                    "metric_name": "bk_apm_duration_min",
                    "alias": "Trace 分钟请求最小耗时",
                    "dimensions": [
                        {"name": "apdex_type", "alias": ""},
                        {"name": "app_name", "alias": ""},
                        {"name": "bk_instance_id", "alias": ""},
                        {"name": "db_name", "alias": "DB 名称"},
                        {"name": "db_system", "alias": ""},
                        {"name": "http_favor", "alias": ""},
                        {"name": "http_method", "alias": ""},
                        {"name": "http_scheme", "alias": ""},
                        {"name": "http_server_name", "alias": ""},
                        {"name": "http_status_code", "alias": "HTTP 状态码"},
                        {"name": "kind", "alias": "类型"},
                        {"name": "net_peer_name", "alias": ""},
                        {"name": "net_peer_port", "alias": "对端 Port"},
                        {"name": "result_table_id", "alias": "逻辑结果表"},
                        {"name": "service_name", "alias": "服务名"},
                        {"name": "service_version", "alias": ""},
                        {"name": "span_name", "alias": "Span 名称"},
                        {"name": "status_code", "alias": "Span 状态"},
                        {"name": "target", "alias": "实体"},
                        {"name": "telemetry_sdk_language", "alias": "SDK 语言"},
                        {"name": "telemetry_sdk_name", "alias": "SDK 名称"},
                        {"name": "telemetry_sdk_version", "alias": "SDK 版本"},
                    ],
                },
                {
                    "metric_name": "bk_apm_duration_sum",
                    "alias": "Trace 总请求耗时",
                    "dimensions": [
                        {"name": "apdex_type", "alias": ""},
                        {"name": "app_name", "alias": ""},
                        {"name": "bk_instance_id", "alias": ""},
                        {"name": "db_name", "alias": "DB 名称"},
                        {"name": "db_system", "alias": ""},
                        {"name": "http_favor", "alias": ""},
                        {"name": "http_method", "alias": ""},
                        {"name": "http_scheme", "alias": ""},
                        {"name": "http_server_name", "alias": ""},
                        {"name": "http_status_code", "alias": "HTTP 状态码"},
                        {"name": "kind", "alias": "类型"},
                        {"name": "net_peer_name", "alias": ""},
                        {"name": "net_peer_port", "alias": "对端 Port"},
                        {"name": "result_table_id", "alias": "逻辑结果表"},
                        {"name": "service_name", "alias": "服务名"},
                        {"name": "service_version", "alias": ""},
                        {"name": "span_name", "alias": "Span 名称"},
                        {"name": "status_code", "alias": "Span 状态"},
                        {"name": "target", "alias": "实体"},
                        {"name": "telemetry_sdk_language", "alias": "SDK 语言"},
                        {"name": "telemetry_sdk_name", "alias": "SDK 名称"},
                        {"name": "telemetry_sdk_version", "alias": "SDK 版本"},
                    ],
                },
                {
                    "metric_name": "bk_apm_total",
                    "alias": "Trace 总请求数",
                    "dimensions": [
                        {"name": "apdex_type", "alias": ""},
                        {"name": "app_name", "alias": ""},
                        {"name": "bk_instance_id", "alias": ""},
                        {"name": "db_name", "alias": "DB 名称"},
                        {"name": "db_system", "alias": ""},
                        {"name": "http_favor", "alias": ""},
                        {"name": "http_method", "alias": ""},
                        {"name": "http_scheme", "alias": ""},
                        {"name": "http_server_name", "alias": ""},
                        {"name": "http_status_code", "alias": "HTTP 状态码"},
                        {"name": "kind", "alias": "类型"},
                        {"name": "net_peer_name", "alias": ""},
                        {"name": "net_peer_port", "alias": "对端 Port"},
                        {"name": "result_table_id", "alias": "逻辑结果表"},
                        {"name": "service_name", "alias": "服务名"},
                        {"name": "service_version", "alias": ""},
                        {"name": "span_name", "alias": "Span 名称"},
                        {"name": "status_code", "alias": "Span 状态"},
                        {"name": "target", "alias": "实体"},
                        {"name": "telemetry_sdk_language", "alias": "SDK 语言"},
                        {"name": "telemetry_sdk_name", "alias": "SDK 名称"},
                        {"name": "telemetry_sdk_version", "alias": "SDK 版本"},
                    ],
                },
            ],
            "common_dimensions": [
                {"name": "scope_name", "alias": "监控分组"},
                {"name": "namespace", "alias": "物理环境"},
                {"name": "service_name", "alias": "服务名"},
                {"name": "sdk_name", "alias": "SDK 名称"},
                {"name": "instance", "alias": "实例"},
                {"name": "version", "alias": "SDK 版本"},
                {"name": "env_name", "alias": "用户环境"},
                {"name": "container_name", "alias": "容器名"},
            ],
        }
    ]
}
