export const DEFAULT_FILTER = [
  {
    label: 'caller_service',
    operate: 2,
    values: ['caller.collector.Unknown'],
    value_type: 0,
  },
  {
    label: 'caller_method',
    operate: 1,
    values: ['-'],
    value_type: 0,
  },
  {
    label: 'instance',
    operate: 1,
    values: ['te.15.1.178'],
    value_type: 0,
  },
  {
    label: 'container_name',
    operate: 1,
    values: ['formal.collector.gz100866'],
    value_type: 0,
  },
  {
    label: 'caller_con_setid',
    operate: 1,
    values: ['caller.gz.bmp'],
    value_type: 0,
  },
  {
    label: 'caller_group',
    operate: 1,
    values: ['-'],
    value_type: 0,
  },
  {
    label: 'callee_service',
    operate: 1,
    values: ['http.callee.unknow'],
    value_type: 0,
  },
  {
    label: 'callee_method',
    operate: 1,
    values: ['/api/v1/write'],
    value_type: 0,
  },
  {
    label: 'callee_ip',
    operate: 1,
    values: ['re.146.45.te'],
    value_type: 0,
  },
  {
    label: 'callee_container',
    operate: 1,
    values: ['formal.callee.router'],
    value_type: 0,
  },
  {
    label: 'callee_con_setid',
    operate: 1,
    values: ['callee.cn.*'],
    value_type: 0,
  },
  {
    label: 'env_name',
    operate: 1,
    values: ['formal'],
    value_type: 0,
  },
  {
    label: 'code',
    operate: 1,
    values: ['err_101'],
    value_type: 0,
  },
  {
    label: 'version',
    operate: 1,
    values: ['v0.15.4'],
    value_type: 0,
  },
  {
    label: 'city',
    operate: 1,
    values: ['gz'],
    value_type: 0,
  },
  {
    label: 'canary',
    operate: 1,
    values: ['-'],
    value_type: 0,
  },
  {
    label: 'user_ext1',
    operate: 1,
    values: ['-'],
    value_type: 0,
  },
  {
    label: 'user_ext2',
    operate: 1,
    values: ['-'],
    value_type: 0,
  },
  {
    label: 'user_ext3',
    operate: 1,
    values: ['-'],
    value_type: 0,
  },
];
