export const step4Data = [
  {
    storage_usage: 0,
    storage_total: 0,
    index_count: 0,
    biz_count: 2,
    storage_cluster_id: 21,
    storage_cluster_name: 'bklogtest.sz.es.db',
    storage_version: '7.2.0',
    storage_type: 'elasticsearch',
    priority: 0,
    registered_system: 'log-search-4',
    bk_biz_id: 215,
    enable_hot_warm: false,
    setup_config: {
      retention_days_max: 7,
      retention_days_default: 7,
      number_of_replicas_max: 1,
      number_of_replicas_default: 1,
      es_shards_default: 3,
      es_shards_max: 64,
    },
    admin: ['samuelsheng'],
    description: '',
    source_type: 'private',
    enable_assessment: false,
    enable_archive: false,
    is_platform: true,
    storage_capacity: 0,
    storage_used: 0,
    max_retention: 365,
    permission: {
      manage_es_source_v2: true,
    },
  },
  {
    storage_usage: 0,
    storage_total: 0,
    index_count: 0,
    biz_count: 3,
    storage_cluster_id: 41,
    storage_cluster_name: 'bkaudittest2.sz.es.svr.ehk.db.',
    storage_version: '7.10.2',
    storage_type: 'elasticsearch',
    priority: 0,
    registered_system: 'log-search-4',
    bk_biz_id: 100605,
    enable_hot_warm: false,
    setup_config: {
      retention_days_max: 7,
      retention_days_default: 7,
      number_of_replicas_max: 1,
      number_of_replicas_default: 1,
      es_shards_default: 2,
      es_shards_max: 64,
    },
    admin: ['oaozhang', 'bennychen', 'hailinxiao'],
    description: 'test_oao',
    source_type: 'qcloud',
    enable_assessment: false,
    enable_archive: true,
    is_platform: true,
    storage_capacity: 0,
    storage_used: 0,
    max_retention: 365,
    permission: {
      manage_es_source_v2: true,
    },
  },
  {
    storage_usage: 0,
    storage_total: 0,
    index_count: 0,
    biz_count: 1,
    storage_cluster_id: 42,
    storage_cluster_name: 'bkaudittest_sz_es_svr_ehk_db',
    storage_version: '7.10.2',
    storage_type: 'elasticsearch',
    priority: 0,
    registered_system: 'log-search-4',
    bk_biz_id: 100605,
    enable_hot_warm: true,
    setup_config: {
      retention_days_max: 14,
      retention_days_default: 7,
      number_of_replicas_max: 1,
      number_of_replicas_default: 1,
      es_shards_default: 3,
      es_shards_max: 64,
    },
    admin: ['oaozhang'],
    description: 'bk-audit-test-2qweqw',
    source_type: 'qcloud',
    enable_assessment: false,
    enable_archive: false,
    is_platform: false,
    storage_capacity: 0,
    storage_used: 0,
    max_retention: 365,
    permission: {
      manage_es_source_v2: true,
    },
  },
  {
    storage_usage: 0,
    storage_total: 0,
    index_count: 0,
    biz_count: 0,
    storage_cluster_id: 47,
    storage_cluster_name: 'bk-audit-test-2',
    storage_version: '7.10.2',
    storage_type: 'elasticsearch',
    priority: 0,
    registered_system: 'log-search-4',
    bk_biz_id: 100605,
    enable_hot_warm: true,
    setup_config: {
      retention_days_max: 14,
      retention_days_default: 7,
      number_of_replicas_max: 1,
      number_of_replicas_default: 1,
      es_shards_default: 3,
      es_shards_max: 64,
    },
    admin: ['oaozhang'],
    description: 'bk-audit-test-2qweqw',
    source_type: 'qcloud',
    enable_assessment: false,
    enable_archive: false,
    is_platform: false,
    storage_capacity: 0,
    storage_used: 0,
    max_retention: 365,
    permission: {
      manage_es_source_v2: true,
    },
  },
  {
    storage_usage: 24,
    storage_total: 157967351808,
    index_count: 91,
    biz_count: 1,
    storage_cluster_id: 48,
    storage_cluster_name: 'audit_stag_2',
    storage_version: '7.7.0',
    storage_type: 'elasticsearch',
    priority: 0,
    registered_system: 'log-search-4',
    bk_biz_id: 100605,
    enable_hot_warm: false,
    setup_config: {
      retention_days_max: 15,
      retention_days_default: 15,
      number_of_replicas_max: 1,
      number_of_replicas_default: 1,
      es_shards_default: 3,
      es_shards_max: 64,
    },
    admin: ['admin', 'oaozhang', 'bk-audit', 'jayjhwu'],
    description: 'bkaudit',
    source_type: 'private',
    enable_assessment: false,
    enable_archive: true,
    is_platform: false,
    storage_capacity: 0,
    storage_used: 0,
    max_retention: 365,
    permission: {
      manage_es_source_v2: true,
    },
  },
  {
    storage_usage: 14,
    storage_total: 105311567872,
    index_count: 309,
    biz_count: 1,
    storage_cluster_id: 49,
    storage_cluster_name: 'audit_stag_2l',
    storage_version: '7.10.2',
    storage_type: 'elasticsearch',
    priority: 0,
    registered_system: 'log-search-4',
    bk_biz_id: 100605,
    enable_hot_warm: false,
    setup_config: {
      retention_days_max: 14,
      retention_days_default: 14,
      number_of_replicas_max: 1,
      number_of_replicas_default: 1,
      es_shards_default: 3,
      es_shards_max: 64,
    },
    admin: ['oaozhang', 'v_jinhpeng', 'riverzheng', 'bk-audit'],
    description: 'audit_stag_2l<script>alert(1)</script>',
    source_type: 'qcloud',
    enable_assessment: false,
    enable_archive: true,
    is_platform: false,
    storage_capacity: 0,
    storage_used: 0,
    max_retention: 365,
    permission: {
      manage_es_source_v2: true,
    },
  },
  {
    storage_usage: 0,
    storage_total: 0,
    index_count: 0,
    biz_count: 5,
    storage_cluster_id: 52,
    storage_cluster_name: 'dbmtest',
    storage_version: '7.10.2',
    storage_type: 'elasticsearch',
    priority: 0,
    registered_system: 'log-search-4',
    bk_biz_id: 2005000194,
    enable_hot_warm: false,
    setup_config: {
      retention_days_max: 14,
      retention_days_default: 7,
      number_of_replicas_max: 3,
      number_of_replicas_default: 1,
      es_shards_default: 1,
      es_shards_max: 3,
    },
    admin: ['durantzhang'],
    description: '',
    source_type: 'private',
    enable_assessment: false,
    enable_archive: false,
    is_platform: true,
    storage_capacity: 0,
    storage_used: 0,
    max_retention: 365,
    permission: {
      manage_es_source_v2: true,
    },
  },
  {
    storage_usage: 8,
    storage_total: 633543254016,
    index_count: 1878,
    biz_count: 19,
    storage_cluster_id: 15,
    storage_cluster_name: 'es7_cluster',
    storage_version: '7.10.2',
    storage_type: 'elasticsearch',
    priority: 1,
    registered_system: '_default',
    bk_biz_id: 2005000002,
    enable_hot_warm: false,
    setup_config: {
      retention_days_max: 7,
      retention_days_default: 1,
      number_of_replicas_max: 1,
      number_of_replicas_default: 0,
      es_shards_default: 1,
      es_shards_max: 3,
    },
    admin: ['bondliu', 'jayjhwu'],
    description: '',
    source_type: 'qcloud',
    enable_assessment: false,
    enable_archive: true,
    is_platform: true,
    storage_capacity: 20,
    storage_used: 0.04,
    max_retention: 14,
    permission: {
      manage_es_source_v2: true,
    },
  },
];
