export const detail = {
  created_at: "2025-08-19 19:56:20+0800",
  created_by: "yuxiaogao",
  updated_at: "2025-09-05 03:32:12+0800",
  updated_by: "yuxiaogao",
  is_deleted: false,
  deleted_at: null,
  deleted_by: null,
  bk_biz_id: 100605,
  bkdata_biz_id: null,
  collector_config_id: 3189,
  collector_config_name: "test123321",
  collector_plugin_id: null,
  bk_app_code: "bk_log_search",
  collector_scenario_id: "row",
  custom_type: "log",
  category_id: "host_process",
  target_object_type: "HOST",
  target_node_type: "INSTANCE",
  target_nodes: [
    {
      bk_host_id: 2000058531,
    },
    {
      bk_host_id: 2000058532,
    },
  ],
  target_subscription_diff: {},
  description: "test123321",
  is_active: false,
  data_link_id: 1,
  bk_data_id: 1576248,
  bk_data_name: "100605_bklog_tteeee",
  table_id: "",
  bkbase_table_id: null,
  processing_id: null,
  etl_processor: "transfer",
  etl_config: null,
  subscription_id: 33461,
  task_id_list: ["27876041"],
  bkdata_data_id: null,
  index_set_id: null,
  data_encoding: "UTF-8",
  params: {
    paths: ["/var/log/messages*"],
    exclude_files: [],
    conditions: {
      type: "none",
    },
    encoding: "UTF-8",
  },
  itsm_ticket_sn: null,
  itsm_ticket_status: "not_apply",
  can_use_independent_es_cluster: true,
  collector_package_count: 10,
  collector_output_format: null,
  collector_config_overlay: null,
  storage_shards_nums: null,
  storage_shards_size: null,
  storage_replies: 1,
  bkdata_data_id_sync_times: 0,
  collector_config_name_en: "tteeee",
  environment: "linux",
  bcs_cluster_id: null,
  extra_labels: [],
  add_pod_label: false,
  add_pod_annotation: false,
  yaml_config_enabled: false,
  yaml_config: "",
  rule_id: 0,
  is_display: true,
  log_group_id: null,
  iframe_ticket_url: "",
  ticket_url: "LOG_SEARCH",
  itsm_ticket_status_display: "未申请采集接入",
  index_split_rule: "--",
  target: [
    {
      bk_host_id: 2000058531,
    },
    {
      bk_host_id: 2000058532,
    },
  ],
  collector_scenario_name: "行日志文件",
  storage_cluster_id: null,
  retention: null,
  etl_params: {},
  fields: [
    {
      field_name: "bk_host_id",
      field_type: "int",
      tag: "dimension",
      alias_name: "",
      description: "主机ID",
      option: {
        es_type: "integer",
        es_include_in_all: false,
      },
      is_built_in: true,
      is_time: false,
      is_analyzed: false,
      is_delete: false,
      is_dimension: true,
    },
    {
      field_name: "ext",
      field_type: "object",
      tag: "dimension",
      alias_name: "__ext",
      description: "额外信息字段",
      option: {
        es_type: "object",
        es_include_in_all: false,
      },
      is_built_in: true,
      is_time: false,
      is_analyzed: false,
      is_delete: false,
      is_dimension: true,
    },
    {
      field_name: "cloudid",
      field_type: "int",
      tag: "dimension",
      alias_name: "cloudId",
      description: "云区域ID",
      option: {
        es_type: "integer",
        es_include_in_all: false,
      },
      is_built_in: true,
      is_time: false,
      is_analyzed: false,
      is_delete: false,
      is_dimension: true,
    },
    {
      field_name: "ip",
      field_type: "string",
      tag: "dimension",
      alias_name: "serverIp",
      description: "ip",
      option: {
        es_type: "keyword",
        es_include_in_all: true,
      },
      is_built_in: true,
      is_time: false,
      is_analyzed: false,
      is_delete: false,
      is_dimension: true,
    },
    {
      field_name: "filename",
      field_type: "string",
      tag: "dimension",
      alias_name: "path",
      description: "日志路径",
      option: {
        es_type: "keyword",
        es_include_in_all: true,
      },
      is_built_in: true,
      is_time: false,
      is_analyzed: false,
      is_delete: false,
      is_dimension: true,
    },
    {
      field_name: "gseindex",
      field_type: "long",
      tag: "dimension",
      alias_name: "gseIndex",
      description: "gse索引",
      option: {
        es_type: "long",
        es_include_in_all: false,
      },
      is_built_in: true,
      is_time: false,
      is_analyzed: false,
      is_delete: false,
      is_dimension: true,
    },
    {
      field_name: "iterationindex",
      field_type: "int",
      tag: "dimension",
      alias_name: "iterationIndex",
      description: "迭代ID",
      flat_field: true,
      option: {
        es_type: "integer",
        es_include_in_all: false,
      },
      is_built_in: true,
      is_time: false,
      is_analyzed: false,
      is_delete: false,
      is_dimension: true,
    },
    {
      field_name: "utctime",
      field_type: "string",
      tag: "dimension",
      alias_name: "dtEventTimeStamp",
      description: "数据时间",
      option: {
        es_type: "date",
        es_include_in_all: false,
        es_format: "epoch_millis",
        time_format: "yyyy-MM-dd HH:mm:ss",
        time_zone: 0,
      },
      is_built_in: true,
      is_time: true,
      is_dimension: true,
      is_analyzed: false,
      is_delete: false,
    },
    {
      field_name: "data",
      field_type: "string",
      tag: "metric",
      alias_name: "log",
      description: "original_text",
      option: {
        es_type: "text",
        es_include_in_all: true,
      },
      is_built_in: true,
      is_time: false,
      is_analyzed: true,
      is_dimension: false,
      is_delete: false,
    },
  ],
  category_name: "进程",
  custom_name: "容器日志上报",
  table_id_prefix: "100605_bklog_",
};

export const jsonStr = {
  bizid: 0,
  bk_agent_id: "02000000005254005ae3091720612442569e",
  bk_biz_id: 100605,
  bk_host_id: 2000058532,
  cloudid: 0,
  dataid: 1573999,
  datetime: "2025-09-09 17:30:52",
  ext: {},
  filename: "/tmp/bkc.log",
  gseindex: 531400,
  hostname: "WeTERM-GateWay-02",
  ip: "9.136.163.107",
  items: [
    {
      data: "20250909-173049 INFO|75|log-main start bkmonitorbeat ...",
      iterationindex: 0,
    },
  ],
  time: 1757410252,
  utctime: "2025-09-09 09:30:52",
};
