export const step2 = {
  created_at: "2025-09-09 11:41:06+0800",
  created_by: "keelyzheng",
  updated_at: "2025-09-09 11:41:08+0800",
  updated_by: "keelyzheng",
  is_deleted: false,
  deleted_at: null,
  deleted_by: null,
  bk_biz_id: 100605,
  bkdata_biz_id: null,
  collector_config_id: 3215,
  collector_config_name: "test0909",
  collector_plugin_id: null,
  bk_app_code: "bk_log_search",
  collector_scenario_id: "section",
  custom_type: "log",
  category_id: "host_process",
  target_object_type: "HOST",
  target_node_type: "INSTANCE",
  target_nodes: [
    {
      bk_host_id: 2000059165,
    },
    {
      bk_host_id: 2000061920,
    },
  ],
  target_subscription_diff: {},
  description: "test0909",
  is_active: true,
  data_link_id: 6,
  bk_data_id: 1577330,
  bk_data_name: null,
  table_id: "",
  bkbase_table_id: null,
  processing_id: null,
  etl_processor: "transfer",
  etl_config: null,
  subscription_id: 33551,
  task_id_list: ["28427819"],
  bkdata_data_id: 1577330,
  index_set_id: null,
  data_encoding: "UTF-8",
  params: {
    paths: ["/path", "/log"],
    exclude_files: ["/test/", "/hello"],
    conditions: {
      separator: "|",
      separator_filters: [
        {
          fieldindex: "-1",
          word: "111",
          op: "=",
          logic_op: "and",
        },
        {
          fieldindex: "-1",
          word: "222",
          op: "=",
          logic_op: "and",
        },
        {
          fieldindex: "-1",
          word: "344",
          op: "=",
          logic_op: "or",
        },
        {
          fieldindex: "-1",
          word: "555",
          op: "=",
          logic_op: "and",
        },
      ],
      type: "match",
      match_type: "include",
      match_content: "111",
    },
    multiline_pattern: "test",
    multiline_max_lines: 50,
    multiline_timeout: 2,
    encoding: "UTF-8",
  },
  itsm_ticket_sn: null,
  itsm_ticket_status: "not_apply",
  can_use_independent_es_cluster: true,
  collector_package_count: 10,
  collector_output_format: null,
  collector_config_overlay: null,
  storage_shards_nums: null,
  storage_shards_size: null,
  storage_replies: 1,
  bkdata_data_id_sync_times: 0,
  collector_config_name_en: "test0909",
  environment: "linux",
  bcs_cluster_id: null,
  extra_labels: [
    {
      key: "host.bk_module_id",
      value: "{{cmdb_instance.host.relations[0].bk_module_id}}",
      operator: "=",
    },
    {
      key: "value",
      value: "2",
      operator: "=",
    },
    {
      key: "timestamp",
      value: "11",
      operator: "=",
    },
  ],
  add_pod_label: false,
  add_pod_annotation: false,
  yaml_config_enabled: false,
  yaml_config: "",
  rule_id: 0,
  is_display: true,
  log_group_id: null,
  iframe_ticket_url: "",
  ticket_url: "LOG_SEARCH",
  itsm_ticket_status_display: "未申请采集接入",
  index_split_rule: "--",
  target: [
    {
      bk_host_id: 2000059165,
    },
    {
      bk_host_id: 2000061920,
    },
  ],
  collector_scenario_name: "段日志文件",
  storage_cluster_id: null,
  retention: null,
  etl_params: {},
  fields: [
    {
      field_name: "bk_host_id",
      field_type: "int",
      tag: "dimension",
      alias_name: "",
      description: "主机ID",
      option: {
        es_type: "integer",
        es_include_in_all: false,
      },
      is_built_in: true,
      is_time: false,
      is_analyzed: false,
      is_delete: false,
      is_dimension: true,
    },
    {
      field_name: "ext",
      field_type: "object",
      tag: "dimension",
      alias_name: "__ext",
      description: "额外信息字段",
      option: {
        es_type: "object",
        es_include_in_all: false,
      },
      is_built_in: true,
      is_time: false,
      is_analyzed: false,
      is_delete: false,
      is_dimension: true,
    },
    {
      field_name: "cloudid",
      field_type: "int",
      tag: "dimension",
      alias_name: "cloudId",
      description: "云区域ID",
      option: {
        es_type: "integer",
        es_include_in_all: false,
      },
      is_built_in: true,
      is_time: false,
      is_analyzed: false,
      is_delete: false,
      is_dimension: true,
    },
    {
      field_name: "ip",
      field_type: "string",
      tag: "dimension",
      alias_name: "serverIp",
      description: "ip",
      option: {
        es_type: "keyword",
        es_include_in_all: true,
      },
      is_built_in: true,
      is_time: false,
      is_analyzed: false,
      is_delete: false,
      is_dimension: true,
    },
    {
      field_name: "filename",
      field_type: "string",
      tag: "dimension",
      alias_name: "path",
      description: "日志路径",
      option: {
        es_type: "keyword",
        es_include_in_all: true,
      },
      is_built_in: true,
      is_time: false,
      is_analyzed: false,
      is_delete: false,
      is_dimension: true,
    },
    {
      field_name: "gseindex",
      field_type: "long",
      tag: "dimension",
      alias_name: "gseIndex",
      description: "gse索引",
      option: {
        es_type: "long",
        es_include_in_all: false,
      },
      is_built_in: true,
      is_time: false,
      is_analyzed: false,
      is_delete: false,
      is_dimension: true,
    },
    {
      field_name: "iterationindex",
      field_type: "int",
      tag: "dimension",
      alias_name: "iterationIndex",
      description: "迭代ID",
      flat_field: true,
      option: {
        es_type: "integer",
        es_include_in_all: false,
      },
      is_built_in: true,
      is_time: false,
      is_analyzed: false,
      is_delete: false,
      is_dimension: true,
    },
    {
      field_name: "utctime",
      field_type: "string",
      tag: "dimension",
      alias_name: "dtEventTimeStamp",
      description: "数据时间",
      option: {
        es_type: "date",
        es_include_in_all: false,
        es_format: "epoch_millis",
        time_format: "yyyy-MM-dd HH:mm:ss",
        time_zone: 0,
      },
      is_built_in: true,
      is_time: true,
      is_dimension: true,
      is_analyzed: false,
      is_delete: false,
    },
    {
      field_name: "data",
      field_type: "string",
      tag: "metric",
      alias_name: "log",
      description: "original_text",
      option: {
        es_type: "text",
        es_include_in_all: true,
      },
      is_built_in: true,
      is_time: false,
      is_analyzed: true,
      is_dimension: false,
      is_delete: false,
    },
  ],
  category_name: "进程",
  custom_name: "容器日志上报",
  table_id_prefix: "100605_bklog_",
};

export const windowsEvent = {
  collector_config_name: "windows-events-0928",
  collector_config_name_en: "windows_events_0928",
  collector_scenario_id: "wineventlog",
  description: "windows-events-0928 开发联调",
  environment: "windows",
  data_link_id: 6,
  category_id: "host_process",
  target_node_type: "INSTANCE",
  target_object_type: "HOST",
  target_nodes: [
    {
      bk_host_id: 2000059165,
    },
  ],
  data_encoding: "UTF-8",
  params: {
    winlog_name: ["Application", "Security", "System"],
    winlog_level: ["hello"],
  },
  bk_biz_id: "100605",
};
export const windowsEventEdit = {
  collector_config_name: "windows-events-0928",
  collector_config_name_en: "windows_events_0928",
  collector_scenario_id: "wineventlog",
  description: "windows-events-0928 开发联调",
  environment: "windows",
  data_link_id: 6,
  target_node_type: "INSTANCE",
  target_object_type: "HOST",
  target_nodes: [
    {
      bk_host_id: 2000059165,
    },
  ],
  data_encoding: "UTF-8",
  params: {
    winlog_name: ["Application", "Security", "System", "1111"],
    winlog_level: ["hello"],
    winlog_event_id: ["444"],
    winlog_source: ["666"],
    winlog_content: ["9999"],
  },
  collector_config_id: 3236,
  bk_biz_id: "100605",
};

// {
//   "collector_config_id": 3237,
//   "collector_config_name": "wind-0930",
//   "bk_data_id": 1577593,
//   "subscription_id": 33576,
//   "task_id_list": [
//       "29027593"
//   ]
// }
