# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making BK-LOG 蓝鲸日志平台 available.
Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.
BK-LOG 蓝鲸日志平台 is licensed under the MIT License.
License for BK-LOG 蓝鲸日志平台:
--------------------------------------------------------------------
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
We undertake not to change the open source license (MIT license) applicable to the current version of
the project delivered to anyone in the future.
"""
from django.utils.translation import gettext as _

from apps.api import BkDataDataFlowApi
from apps.log_search.constants import OPERATORS
from apps.utils import ChoicesEnum

DEFAULT_TIME_FIELD = "timestamp"
DEFAULT_CLUSTERING_FIELD = "log"
NOT_CLUSTERING_FILTER_RULE = " where ip is null"
OPERATOR_AND = "and"
# 聚类不参与sql字段
NOT_CONTAIN_SQL_FIELD_LIST = ["timestamp", "_startTime_", "_endTime_"]
DIST_FIELDS = ["dist_05"]
RENAME_DIST_FIELDS = ["__dist_05"]
DIST_CLUSTERING_FIELDS = [
    "dist_05 AS __dist_05",
]
DEFAULT_SPARK_EXECUTOR_INSTANCES = 8
DEFAULT_SPARK_EXECUTOR_CORES = 2
DEFAULT_SPARK_PSEUDO_SHUFFLE = 200
DEFAULT_SPARK_LOCALITY_WAIT = "0s"

DEFAULT_FLINK_BATCH_SIZE = 100
DEFAULT_FLINK_CPU = 1
DEFAULT_FLINK_MEMORY = 2048
DEFAULT_FLINK_WORKER_NUMS = 2
DEFAULT_FLINK_REPLICAS = 2

STREAM_SOURCE_NODE_TYPE = "stream_source"
DIVERSION_NODE_NAME = _("回流数据")
TSPIDER_STORAGE_NODE_TYPE = "tspider_storage"
TSPIDER_STORAGE_INDEX_FIELDS = ["history_time", "event_time"]
MYSQL_STORAGE_NODE_TYPE = "mysql_storage"

SPLIT_TYPE = "split"


class ActionEnum(object):
    START = "start"
    RESTART = "restart"
    STOP = "stop"


class ActionHandler(object):
    action_handler = {
        ActionEnum.START: BkDataDataFlowApi.start_flow,
        ActionEnum.RESTART: BkDataDataFlowApi.restart_flow,
        ActionEnum.STOP: BkDataDataFlowApi.stop_flow,
    }

    @classmethod
    def get_action_handler(cls, action_num):
        return cls.action_handler.get(action_num, BkDataDataFlowApi.start_flow)


class FlowMode(ChoicesEnum):
    # 预处理flow
    PRE_TREAT_FLOW = "pre_treat_flow"
    # 结果处理flow
    AFTER_TREAT_FLOW = "after_treat_flow"
    # 修改flow的某些节点
    MODIFY_FLOW = "modify_flow"
    # 计算平台rt flow
    AFTER_TREAT_FLOW_BKDATA = "after_treat_flow_bkdata"
    # 在线训练 预测处理 flow
    PREDICT_FLOW = "predict_flow"
    # 日志数量聚合 flow
    LOG_COUNT_AGGREGATION_FLOW = "log_count_aggregation_flow"

    _choices_labels = (
        (PRE_TREAT_FLOW, "templates/flow/pre_treat_flow.json"),
        (AFTER_TREAT_FLOW, "templates/flow/after_treat_flow.json"),
        (MODIFY_FLOW, "templates/flow/modify_flow.json"),
        (AFTER_TREAT_FLOW_BKDATA, "templates/flow/after_treat_flow_bkdata.json"),
        (PREDICT_FLOW, "templates/flow/predict_flow.json"),
        (LOG_COUNT_AGGREGATION_FLOW, "templates/flow/log_count_aggregation_flow.json"),
    )


class NodeType(object):
    REALTIME = "realtime"
    REDIS_KV_SOURCE = "redis_kv_source"
    ELASTIC_STORAGE = "elastic_storage"
    MODEL = "model_ts_custom"
    STREAM_SOURCE = "stream_source"


class RealTimeFlowNode(object):
    PRE_TREAT_NOT_CLUSTERING = "pre_treat_not_clustering"
    PRE_TREAT_SAMPLE_SET = "pre_treat_sample_set"
    AFTER_TREAT_CHANGE_FIELD = "after_treat_change_field"


class RealTimePredictFlowNode(object):
    PREDICT_CLUSTERING = "clustering"
    PREDICT_NOT_CLUSTERING = "not_clustering"
    PREDICT_NODE = "clustering_output"


# 查询字段   __dist_xx
PATTERN_SEARCH_FIELDS = [
    {
        "field_type": "keyword",
        "field_name": field_name,
        "field_alias": "",
        "is_display": False,
        "is_editable": True,
        "tag": "dimension",
        "es_doc_values": True,
        "is_analyzed": False,
        "field_operator": OPERATORS.get("keyword", []),
        "description": None,
    }
    for field_name in RENAME_DIST_FIELDS
]


DEFAULT_MODEL_INPUT_FIELDS = [
    {
        "field_index": 1,
        "data_field_name": "__index__",
        "field_alias": _("系统索引"),
        "components": [],
        "roles": ["system", "index"],
        "data_field_alias": "index",
        "properties": {
            "constraint_type": None,
            "name_inherited": True,
            "value_fixed": False,
            "passthrough": False,
            "role_changeable": False,
            "deletable": False,
            "compatibility": False,
            "extra": {},
            "constraints": {},
            "required": True,
            "complex": False,
        },
        "field_name": "__index__",
        "field_type": "string",
    },
    {
        "field_name": "__id__",
        "field_type": "string",
        "components": ["__group_id__", "timestamp"],
        "field_alias": _("用户索引"),
        "data_field_name": "__id__",
        "data_field_alias": _("用户索引"),
        "roles": ["index"],
        "field_index": 2,
        "properties": {
            "required": True,
            "extra": {},
            "constraint_type": None,
            "compatibility": False,
            "deletable": False,
            "name_inherited": True,
            "complex": True,
            "role_changeable": False,
            "passthrough": False,
            "value_fixed": False,
            "constraints": {},
        },
    },
    {
        "data_field_name": [],
        "data_field_alias": "",
        "field_alias": _("分组字段"),
        "field_type": "string",
        "properties": {
            "name_inherited": True,
            "role_changeable": False,
            "deletable": False,
            "passthrough": False,
            "compatibility": False,
            "complex": False,
            "value_fixed": True,
            "constraints": {},
            "required": True,
            "constraint_type": None,
            "extra": {},
        },
        "roles": ["index_component", "group"],
        "components": [],
        "field_name": "__group_id__",
        "field_index": 3,
    },
    {
        "data_field_name": "log",
        "field_name": "log",
        "field_alias": _("日志内容"),
        "field_type": "string",
        "field_index": 4,
        "data_field_alias": "",
        "components": [],
        "roles": ["passthrough", "feature"],
        "properties": {
            "complex": False,
            "compatibility": False,
            "passthrough": False,
            "required": True,
            "constraint_type": "",
            "role_changeable": False,
            "deletable": False,
            "extra": {},
            "value_fixed": False,
            "name_inherited": False,
            "constraints": {},
        },
    },
    {
        "roles": ["timestamp"],
        "field_index": 5,
        "properties": {
            "constraint_type": "",
            "deletable": False,
            "name_inherited": False,
            "passthrough": False,
            "role_changeable": False,
            "required": True,
            "compatibility": False,
            "constraints": {},
            "extra": {},
            "complex": False,
            "value_fixed": False,
        },
        "field_name": "timestamp",
        "data_field_name": "timestamp",
        "data_field_alias": "",
        "field_alias": _("时间戳"),
        "components": [],
        "field_type": "timestamp",
    },
]


DEFAULT_MODEL_OUTPUT_FIELDS = [
    {
        "data_field_alias": "index",
        "components": [],
        "field_type": "string",
        "properties": {
            "complex": False,
            "constraints": {},
            "extra": {},
            "compatibility": False,
            "constraint_type": None,
            "deletable": False,
            "name_inherited": True,
            "required": True,
            "value_fixed": False,
            "role_changeable": False,
            "passthrough": False,
        },
        "field_alias": _("系统索引"),
        "field_index": 1,
        "roles": ["index"],
        "field_name": "__index__",
        "data_field_name": "__index__",
    },
    {
        "field_alias": _("用户索引"),
        "data_field_alias": _("用户索引"),
        "components": ["__group_id__", "timestamp"],
        "roles": ["index"],
        "properties": {
            "role_changeable": False,
            "name_inherited": True,
            "value_fixed": False,
            "complex": True,
            "deletable": False,
            "passthrough": False,
            "required": True,
            "constraints": {},
            "extra": {},
            "constraint_type": None,
            "compatibility": False,
        },
        "field_name": "__id__",
        "field_index": 2,
        "data_field_name": "__id__",
        "field_type": "string",
    },
    {
        "field_alias": _("分组索引"),
        "roles": ["index_component", "group"],
        "properties": {
            "deletable": False,
            "passthrough": False,
            "complex": False,
            "constraints": {},
            "extra": {},
            "name_inherited": True,
            "compatibility": False,
            "constraint_type": None,
            "role_changeable": False,
            "value_fixed": True,
            "required": True,
        },
        "field_type": "string",
        "field_name": "__group_id__",
        "components": [],
        "field_index": 3,
        "data_field_name": "__group_id__",
        "data_field_alias": _("分组字段"),
    },
    {
        "properties": {
            "name_inherited": False,
            "value_fixed": False,
            "constraint_type": "",
            "deletable": False,
            "extra": {},
            "passthrough": False,
            "compatibility": False,
            "role_changeable": False,
            "required": True,
            "complex": False,
            "constraints": {},
        },
        "field_name": "log_signature",
        "components": [],
        "data_field_name": "",
        "field_alias": "log_signature",
        "field_type": "text",
        "data_field_alias": None,
        "field_index": 5,
        "roles": ["predict_result"],
    },
    {
        "field_name": "timestamp",
        "roles": ["timestamp"],
        "properties": {
            "constraint_type": "",
            "extra": {},
            "compatibility": False,
            "value_fixed": False,
            "passthrough": False,
            "complex": False,
            "role_changeable": False,
            "required": True,
            "constraints": {},
            "deletable": False,
            "name_inherited": True,
        },
        "field_index": 6,
        "data_field_name": "timestamp",
        "components": [],
        "data_field_alias": None,
        "field_type": "timestamp",
        "field_alias": "timestamp",
    },
    {
        "components": [],
        "field_index": 7,
        "properties": {
            "value_fixed": False,
            "required": True,
            "compatibility": False,
            "constraint_type": "",
            "constraints": {},
            "name_inherited": False,
            "role_changeable": False,
            "deletable": False,
            "passthrough": False,
            "complex": False,
            "extra": {},
        },
        "data_field_alias": None,
        "field_type": "string",
        "field_alias": _("日志内容"),
        "roles": ["passthrough", "feature"],
        "data_field_name": "log",
        "field_name": "log",
    },
    {
        "used_by": "user",
        "components": [],
        "field_alias": "pattern",
        "data_field_alias": "",
        "allowed_values": [],
        "roles": ["predict_result"],
        "origin": [],
        "field_container_type": "undefined",
        "output_mark": True,
        "autoPassthrough": False,
        "field_name": "pattern",
        "field_index": 8,
        "data_field_name": "",
        "field_type": "text",
        "description": None,
        "data_field_type": "",
        "default_value": "",
        "sample_value": None,
        "value": "",
        "properties": {
            "value_fixed": False,
            "constraint": [],
            "constraints": {},
            "extra": {},
            "condition": {},
            "role_changeable": False,
            "name_inherited": False,
            "complex": False,
            "passthrough": False,
            "compatibility": False,
            "anonymous": False,
            "label_rules": {"type": "enum", "enum_list": []},
            "deletable": False,
            "is_required": True,
            "constraint_type": "",
        },
    },
    {
        "default_value": "",
        "sample_value": None,
        "value": "",
        "data_field_alias": "",
        "roles": ["predict_result"],
        "origin": [],
        "description": None,
        "used_by": "user",
        "field_index": 9,
        "data_field_name": "",
        "allowed_values": [],
        "autoPassthrough": False,
        "field_name": "is_new",
        "field_alias": "is_new",
        "components": [],
        "field_type": "int",
        "properties": {
            "is_required": True,
            "constraint_type": "",
            "deletable": False,
            "name_inherited": False,
            "complex": False,
            "anonymous": False,
            "role_changeable": False,
            "passthrough": False,
            "constraint": [],
            "value_fixed": False,
            "compatibility": False,
            "condition": {},
            "label_rules": {"type": "enum", "enum_list": []},
            "constraints": {},
            "extra": {},
        },
        "field_container_type": "undefined",
        "output_mark": True,
        "data_field_type": "",
    },
]

CLUSTERING_DEFAULT_MODEL_INPUT_FIELDS = [
    {
        "origin": [],
        "properties": {
            "deletable": False,
            "name_inherited": True,
            "value_fixed": False,
            "passthrough": False,
            "compatibility": False,
            "is_required": True,
            "constraint_type": "",
            "constraints": {},
            "complex": False,
            "extra": {},
            "label_rules": {},
            "condition": {},
            "anonymous": False,
            "constraint": [],
            "role_changeable": False,
        },
        "used_by": "user",
        "components": [],
        "field_container_type": "undefined",
        "data_field_type": "string",
        "description": None,
        "field_name": "__index__",
        "field_alias": "SystemIndex",
        "value": None,
        "field_index": 1,
        "roles": ["system", "index"],
        "default_value": None,
        "data_field_name": "__index__",
        "data_field_alias": "SystemIndex",
        "field_type": "string",
        "allowed_values": [],
        "sample_value": "0.8631498727540149",
    },
    {
        "origin": [],
        "properties": {
            "deletable": False,
            "name_inherited": True,
            "value_fixed": False,
            "passthrough": False,
            "compatibility": False,
            "is_required": True,
            "constraint_type": "",
            "constraints": {},
            "complex": True,
            "extra": {},
            "label_rules": {},
            "condition": {},
            "anonymous": False,
            "constraint": [],
            "role_changeable": False,
        },
        "used_by": "user",
        "components": ["__group_id__", "timestamp"],
        "field_container_type": "complex",
        "data_field_type": "string",
        "description": None,
        "field_name": "__id__",
        "field_alias": "UserIndex",
        "value": None,
        "field_index": 2,
        "roles": ["system", "index", "business"],
        "default_value": None,
        "data_field_name": "__id__",
        "data_field_alias": "UserIndex",
        "field_type": "string",
        "allowed_values": [],
        "sample_value": "X19ncm91cF9ISnZkbWx1,GltZXN0YW1w:MTY3OT==ab",
    },
    {
        "origin": [],
        "properties": {
            "deletable": False,
            "name_inherited": True,
            "value_fixed": False,
            "passthrough": False,
            "compatibility": False,
            "is_required": True,
            "constraint_type": "",
            "constraints": {},
            "complex": True,
            "extra": {},
            "label_rules": {},
            "condition": {},
            "anonymous": False,
            "constraint": [],
            "role_changeable": False,
        },
        "used_by": "user",
        "components": ["__group__"],
        "field_container_type": "complex",
        "data_field_type": "string",
        "description": None,
        "field_name": "__group_id__",
        "field_alias": "GroupIndex",
        "value": None,
        "field_index": 3,
        "roles": ["group", "system", "index_component"],
        "default_value": None,
        "data_field_name": "__group_id__",
        "data_field_alias": "GroupIndex",
        "field_type": "string",
        "allowed_values": [],
        "sample_value": "Y291bnRyeQ==:5Lit5Zu9,cHJvdmluY2U=:5YyX5Lqs",
    },
    {
        "origin": [],
        "properties": {
            "deletable": False,
            "name_inherited": False,
            "value_fixed": False,
            "passthrough": False,
            "compatibility": False,
            "is_required": True,
            "constraint_type": "",
            "constraints": {},
            "complex": False,
            "extra": {},
            "label_rules": {},
            "condition": {},
            "anonymous": False,
            "constraint": [],
            "role_changeable": False,
        },
        "used_by": "user",
        "components": [],
        "field_container_type": "undefined",
        "data_field_type": "",
        "description": None,
        "field_name": "log",
        "field_alias": "log",
        "value": None,
        "field_index": 4,
        "roles": ["passthrough", "feature"],
        "default_value": None,
        "data_field_name": "log",
        "data_field_alias": "",
        "field_type": "string",
        "allowed_values": [],
        "sample_value": None,
    },
    {
        "origin": ["timestamp"],
        "properties": {
            "deletable": False,
            "name_inherited": True,
            "value_fixed": False,
            "passthrough": False,
            "compatibility": False,
            "is_required": True,
            "constraint_type": "",
            "constraints": {},
            "complex": False,
            "extra": {},
            "label_rules": {},
            "condition": {},
            "anonymous": False,
            "constraint": [],
            "role_changeable": False,
        },
        "used_by": "user",
        "components": [],
        "field_container_type": "undefined",
        "data_field_type": "timestamp",
        "description": "timestamp",
        "field_name": "timestamp",
        "field_alias": "Timestamp",
        "value": None,
        "field_index": 5,
        "roles": ["timestamp"],
        "default_value": None,
        "data_field_name": "timestamp",
        "data_field_alias": "Timestamp",
        "field_type": "timestamp",
        "allowed_values": [],
        "sample_value": 1723692903797,
    },
    {
        "origin": [],
        "properties": {
            "deletable": True,
            "name_inherited": True,
            "value_fixed": False,
            "passthrough": False,
            "compatibility": False,
            "is_required": False,
            "constraint_type": "",
            "constraints": {},
            "complex": False,
            "extra": {},
            "label_rules": {},
            "condition": {"condition_value": 99, "condition_type": "lt"},
            "anonymous": False,
            "constraint": [],
            "role_changeable": False,
        },
        "used_by": "user",
        "components": [{"field_name": "", "field_alias": ""}],
        "field_container_type": "group",
        "data_field_type": "any",
        "description": None,
        "field_name": "__group__",
        "field_alias": "GroupComponent",
        "value": None,
        "field_index": 6,
        "roles": ["system", "dynamic", "group_component"],
        "default_value": None,
        "data_field_name": "__group__",
        "data_field_alias": "GroupComponent",
        "field_type": "any",
        "allowed_values": [],
        "sample_value": None,
    },
    {
        "origin": [],
        "properties": {
            "deletable": True,
            "name_inherited": False,
            "value_fixed": False,
            "passthrough": False,
            "compatibility": False,
            "is_required": False,
            "constraint_type": "",
            "constraints": {},
            "complex": True,
            "extra": {},
            "label_rules": {"enum_list": [], "type": "enum"},
            "condition": {"condition_value": "0", "condition_type": "gt"},
            "anonymous": False,
            "constraint": [],
            "role_changeable": False,
        },
        "used_by": "user",
        "components": [],
        "field_container_type": "group",
        "data_field_type": "any",
        "description": None,
        "field_name": "log_group",
        "field_alias": "log_group",
        "value": "",
        "field_index": 7,
        "roles": ["passthrough", "dynamic", "feature"],
        "default_value": "",
        "data_field_name": "log_group",
        "data_field_alias": "log_group",
        "field_type": "any",
        "allowed_values": [],
        "sample_value": None,
    },
]

CLUSTERING_DEFAULT_MODEL_OUTPUT_FIELDS = [
    {
        "origin": [],
        "autoPassthrough": False,
        "properties": {
            "deletable": False,
            "name_inherited": True,
            "value_fixed": False,
            "passthrough": False,
            "compatibility": False,
            "is_required": True,
            "constraint_type": "",
            "constraints": {},
            "complex": False,
            "extra": {},
            "label_rules": {},
            "condition": {},
            "anonymous": False,
            "constraint": [],
            "role_changeable": False,
        },
        "used_by": "user",
        "components": [],
        "field_container_type": "undefined",
        "description": None,
        "field_name": "__index__",
        "output_mark": True,
        "field_alias": "SystemIndex",
        "value": None,
        "field_index": 1,
        "roles": ["system", "index"],
        "default_value": None,
        "data_field_name": "__index__",
        "data_field_alias": "SystemIndex",
        "field_type": "string",
        "allowed_values": [],
        "sample_value": "0.8631498727540149",
    },
    {
        "origin": [],
        "autoPassthrough": False,
        "properties": {
            "deletable": False,
            "name_inherited": True,
            "value_fixed": False,
            "passthrough": False,
            "compatibility": False,
            "is_required": True,
            "constraint_type": "",
            "constraints": {},
            "complex": True,
            "extra": {},
            "label_rules": {},
            "condition": {},
            "anonymous": False,
            "constraint": [],
            "role_changeable": False,
        },
        "used_by": "user",
        "components": ["__group_id__", "timestamp"],
        "field_container_type": "complex",
        "description": None,
        "field_name": "__id__",
        "output_mark": True,
        "field_alias": "UserIndex",
        "value": None,
        "field_index": 2,
        "roles": ["system", "index", "business"],
        "default_value": None,
        "data_field_name": "__id__",
        "data_field_alias": "UserIndex",
        "field_type": "string",
        "allowed_values": [],
        "sample_value": "X19ncm91cF9ISnZkbWx1,GltZXN0YW1w:MTY3OT==ab",
    },
    {
        "origin": [],
        "autoPassthrough": False,
        "properties": {
            "deletable": False,
            "name_inherited": True,
            "value_fixed": False,
            "passthrough": False,
            "compatibility": False,
            "is_required": True,
            "constraint_type": "",
            "constraints": {},
            "complex": True,
            "extra": {},
            "label_rules": {},
            "condition": {},
            "anonymous": False,
            "constraint": [],
            "role_changeable": False,
        },
        "used_by": "user",
        "components": ["__group__"],
        "field_container_type": "complex",
        "description": None,
        "field_name": "__group_id__",
        "output_mark": True,
        "field_alias": "GroupIndex",
        "value": None,
        "field_index": 3,
        "roles": ["group", "system", "index_component"],
        "default_value": None,
        "data_field_name": "__group_id__",
        "data_field_alias": "GroupIndex",
        "field_type": "string",
        "allowed_values": [],
        "sample_value": "Y291bnRyeQ==:5Lit5Zu9,cHJvdmluY2U=:5YyX5Lqs",
    },
    {
        "origin": [],
        "autoPassthrough": False,
        "properties": {
            "deletable": False,
            "name_inherited": False,
            "value_fixed": False,
            "passthrough": False,
            "compatibility": False,
            "is_required": True,
            "constraint_type": "",
            "constraints": {},
            "complex": False,
            "extra": {},
            "label_rules": {},
            "condition": {},
            "anonymous": False,
            "constraint": [],
            "role_changeable": False,
        },
        "used_by": "user",
        "components": [],
        "field_container_type": "undefined",
        "data_field_type": "",
        "description": None,
        "field_name": "log_signature",
        "output_mark": True,
        "field_alias": "log_signature",
        "value": None,
        "field_index": 4,
        "roles": ["predict_result"],
        "default_value": None,
        "data_field_name": "",
        "data_field_alias": "",
        "field_type": "text",
        "allowed_values": [],
        "sample_value": None,
    },
    {
        "origin": ["timestamp"],
        "autoPassthrough": False,
        "properties": {
            "deletable": False,
            "name_inherited": True,
            "value_fixed": False,
            "passthrough": False,
            "compatibility": False,
            "is_required": True,
            "constraint_type": "",
            "constraints": {},
            "complex": False,
            "extra": {},
            "label_rules": {},
            "condition": {},
            "anonymous": False,
            "constraint": [],
            "role_changeable": False,
        },
        "used_by": "user",
        "components": [],
        "field_container_type": "undefined",
        "description": "timestamp",
        "field_name": "timestamp",
        "output_mark": True,
        "field_alias": "Timestamp",
        "value": None,
        "field_index": 5,
        "roles": ["timestamp"],
        "default_value": None,
        "data_field_name": "timestamp",
        "data_field_alias": "Timestamp",
        "field_type": "timestamp",
        "allowed_values": [],
        "sample_value": 1723628598280,
    },
    {
        "origin": [],
        "autoPassthrough": False,
        "properties": {
            "deletable": True,
            "name_inherited": True,
            "value_fixed": False,
            "passthrough": False,
            "compatibility": False,
            "is_required": False,
            "constraint_type": "",
            "constraints": {},
            "complex": False,
            "extra": {},
            "label_rules": {},
            "condition": {"condition_value": 99, "condition_type": "lt"},
            "anonymous": False,
            "constraint": [],
            "role_changeable": False,
        },
        "used_by": "user",
        "components": [],
        "field_container_type": "group",
        "data_field_type": "any",
        "description": None,
        "field_name": "__group__",
        "output_mark": True,
        "field_alias": "GroupComponent",
        "value": None,
        "field_index": 6,
        "roles": ["system", "dynamic", "group_component"],
        "default_value": None,
        "data_field_name": "__group__",
        "data_field_alias": "GroupComponent",
        "field_type": "any",
        "allowed_values": [],
        "sample_value": None,
    },
    {
        "origin": [],
        "autoPassthrough": False,
        "properties": {
            "deletable": False,
            "name_inherited": False,
            "value_fixed": False,
            "passthrough": False,
            "compatibility": False,
            "is_required": True,
            "constraint_type": "",
            "constraints": {},
            "complex": False,
            "extra": {},
            "label_rules": {"enum_list": [], "type": "enum"},
            "condition": {},
            "anonymous": False,
            "constraint": [],
            "role_changeable": False,
        },
        "used_by": "user",
        "components": [],
        "field_container_type": "undefined",
        "data_field_type": "",
        "description": None,
        "field_name": "pattern",
        "output_mark": True,
        "field_alias": "pattern",
        "value": "",
        "field_index": 7,
        "roles": ["predict_result"],
        "default_value": "",
        "data_field_name": "",
        "data_field_alias": "",
        "field_type": "text",
        "allowed_values": [],
        "sample_value": None,
    },
    {
        "origin": [],
        "autoPassthrough": False,
        "properties": {
            "deletable": False,
            "name_inherited": False,
            "value_fixed": False,
            "passthrough": False,
            "compatibility": False,
            "is_required": True,
            "constraint_type": "",
            "constraints": {},
            "complex": False,
            "extra": {},
            "label_rules": {"enum_list": [], "type": "enum"},
            "condition": {},
            "anonymous": False,
            "constraint": [],
            "role_changeable": False,
        },
        "used_by": "user",
        "components": [],
        "field_container_type": "undefined",
        "data_field_type": "",
        "description": None,
        "field_name": "is_new",
        "output_mark": True,
        "field_alias": "is_new",
        "value": "",
        "field_index": 8,
        "roles": ["predict_result"],
        "default_value": "",
        "data_field_name": "",
        "data_field_alias": "",
        "field_type": "int",
        "allowed_values": [],
        "sample_value": None,
    },
    {
        "origin": [],
        "autoPassthrough": True,
        "properties": {
            "deletable": False,
            "name_inherited": False,
            "value_fixed": False,
            "passthrough": False,
            "compatibility": False,
            "is_required": True,
            "constraint_type": "",
            "constraints": {},
            "complex": False,
            "extra": {},
            "label_rules": {},
            "condition": {},
            "anonymous": False,
            "constraint": [],
            "role_changeable": False,
        },
        "used_by": "user",
        "components": [],
        "field_container_type": "undefined",
        "data_field_type": "",
        "description": None,
        "field_name": "log",
        "output_mark": True,
        "field_alias": "日志内容",
        "value": None,
        "field_index": 9,
        "roles": ["passthrough", "feature"],
        "default_value": None,
        "data_field_name": "log",
        "data_field_alias": "",
        "field_type": "string",
        "allowed_values": [],
        "sample_value": None,
    },
    {
        "origin": [],
        "autoPassthrough": True,
        "properties": {
            "deletable": True,
            "name_inherited": False,
            "value_fixed": False,
            "passthrough": False,
            "compatibility": False,
            "is_required": False,
            "constraint_type": "",
            "constraints": {},
            "complex": False,
            "extra": {},
            "label_rules": {"enum_list": [], "type": "enum"},
            "condition": {"condition_value": "0", "condition_type": "gt"},
            "anonymous": False,
            "constraint": [],
            "role_changeable": False,
        },
        "used_by": "user",
        "components": [],
        "field_container_type": "group",
        "data_field_type": "any",
        "description": None,
        "field_name": "log_group",
        "output_mark": True,
        "field_alias": "log_group",
        "value": "",
        "field_index": 10,
        "roles": ["passthrough", "dynamic", "feature"],
        "default_value": "",
        "data_field_name": "log_group",
        "data_field_alias": "log_group",
        "field_type": "any",
        "allowed_values": [],
        "sample_value": None,
    },
]


class OperatorOnlineTaskEnum(object):
    CREATE = "create"
    UPDATE = "update"


class OnlineTaskTrainingArgs(object):
    IS_NEW = 1
    USE_OFFLINE_MODEL = 0
    ST_LIST = "0.875"
    ST_LIST_OLD = "0.9,0.8875,0.875,0.8625,0.85"
    MAX_DIST_LIST = "0.5"
    MAX_DIST_LIST_OLD = "0.1,0.3,0.5,0.7,0.9"
    DEPTH = 7
    MIN_MEMBERS = 1
    DELIMETER = "IlwifFxcXHUzMDAyfFxcXHVmZjFhfFxcO3xcXCx8XFwsfFxcW3xcXF18XFw6fFxcc3xcXCh8XFwpfFxcPXxcXHx8XFx7fFxcfXxcXD58XFw8fFxcfHwnfFxcXHVmZjA4fFxcXHVmZjBjfFxcXHVmZjA5fFxcL3xcXFx1ZmYwY3xcXFx1MzAxMHxcXFx1MzAxMXxcXFxccnxcXFxcbnxcXFxcdHxcXFxcfFxcLS0tfFxcLS18XFxgfFxcLT58XFwhfFxcXHVmZjAxfFxcXHVmZjFmfFxcP3xcXF58XFwkfFxcLiAi"
    MAX_LOG_LENGTH = 1000
    IS_CASE_SENSITIVE = 0
    PREDEFINED_VARIBLES = "WyJVUkw6KGh0dHB8aHR0cHMpXFw6XFwvXFwvW2EtekEtWjAtOVxcLlxcL1xcP1xcOkBcXC1fPSMlXStcXC4oW2EtekEtWl0pezIsNn0oW2EtekEtWjAtOVxcLlxcJlxcL1xcP1xcOkBcXC1fPSMlXSkqIiAsIkRBVEVUSU1FOmRhdGV0aW1lLmRhdGV0aW1lXFwoXFxkezR9LFxcc1xcZHsxLDJ9LFxcc1xcZHsxLDJ9LFxcc1xcZHsxLDJ9LFxcc1xcZHsxLDJ9LFxcc1xcZHsxLDJ9LFxcc1xcZHs1fSxcXHN0emluZm89PFxcd3szLDR9PlxcKT4iICwiREFURVRJTUU6XFxkezEsNH0oLXwvKT8oXFxkezEsMn18XFx3ezMsNH0pKC18Lyk/XFxkezEsNH0oXFxzfC18X3xUKStcXGR7MSwyfTpcXGR7MSwyfTpcXGR7MSwyfSgoLHxcXC58XFxzKT8oXFwrKT9cXGR7Miw2fSk/KFxcK1xcZHsyfShcXDp8XFxzKT9cXGR7Mn0pPyhaKT8iICwiREFURTpcXGR7NH0oXFwtfFxcL3xcXC4pXFxkezEsMn0oXFwtfFxcL3xcXC4pXFxkezEsMn0iICwiVElNRTpcXGR7Mn06XFxkezJ9OlxcZHsyfShcXC5cXGR7Nn0pPyIgLCJQQVRIOihcXC9bYS16QS1aMC05XFwuXy1dKykrIiAsIlBFUklPRDpeWzAtOV0qXFwuP1swLTldKyhbwrV1c1NtTUhoXSkrJCIgLCJOVU1CRVI6XlstK10/WzAtOV0rKFxcLlswLTldKyk/JCIgLCJVVUlEOlswLTlhLWZBLUZdezh9LVswLTlhLWZBLUZdezR9LVswLTlhLWZBLUZdezR9LVswLTlhLWZBLUZdezR9LVswLTlhLWZBLUZdezEyfSIgLCJVVUlEOlswLTlhLWZBLUZdezMyfSIgLCJJUDpeKCgyKDVbMC01XXxbMC00XVxcZCkpfFswLTFdP1xcZHsxLDJ9KShcXC4oKDIoNVswLTVdfFswLTRdXFxkKSl8WzAtMV0/XFxkezEsMn0pKXszfSQiICwiSVAtUE9SVDooKDIoNVswLTVdfFswLTRdXFxkKSl8WzAtMV0/XFxkezEsMn0pKFxcLigoMig1WzAtNV18WzAtNF1cXGQpKXxbMC0xXT9cXGR7MSwyfSkpezN9XFxzPzpcXGR7MSw1fSJd"
