# Generated by Django 4.2.22 on 2025-12-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TGPATask",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False, verbose_name="ID")),
                ("task_id", models.IntegerField(db_index=True, unique=True, verbose_name="后台任务id")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务id")),
                ("log_path", models.TextField(blank=True, null=True, verbose_name="日志路径")),
                ("task_status", models.CharField(max_length=64, null=True, verbose_name="任务状态")),
                ("file_status", models.CharField(max_length=64, null=True, verbose_name="文件状态")),
                ("process_status", models.CharField(default="init", max_length=64, verbose_name="处理状态")),
                ("processed_at", models.DateTimeField(null=True, verbose_name="处理时间")),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
            ],
            options={
                "verbose_name": "TGPA任务",
                "verbose_name_plural": "TGPA任务",
            },
        ),
    ]
