# Generated by Django 4.2.22 on 2025-11-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TGPATask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_id", models.IntegerField(db_index=True, unique=True, verbose_name="任务唯一标识")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务id")),
                ("log_path", models.TextField(blank=True, null=True, verbose_name="日志路径")),
                ("process_status", models.CharField(default="pending", max_length=64, verbose_name="处理状态")),
                ("processed_at", models.DateTimeField(auto_now_add=True, verbose_name="处理时间")),
            ],
            options={
                "verbose_name": "TGPA任务",
                "verbose_name_plural": "TGPA任务",
            },
        ),
    ]
