# Generated by Django 4.2.22 on 2025-11-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tgpa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tgpatask",
            name="error_message",
            field=models.TextField(blank=True, null=True, verbose_name="错误信息"),
        ),
    ]
