# Generated by Django 4.2.22 on 2025-12-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tgpa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TGPAReportSyncRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务id")),
                ("openid_list", models.JSONField(null=True, verbose_name="openid列表")),
                ("file_name_list", models.JSONField(null=True, verbose_name="文件名列表")),
                ("status", models.CharField(default="pending", max_length=64, verbose_name="状态")),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
            ],
            options={
                "verbose_name": "客户端上报同步记录",
                "verbose_name_plural": "客户端上报同步记录",
            },
        ),
        migrations.CreateModel(
            name="TGPAReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务id")),
                ("file_name", models.CharField(max_length=512, verbose_name="文件名")),
                ("openid", models.CharField(blank=True, max_length=128, null=True, verbose_name="openid")),
                ("processed_at", models.DateTimeField(null=True, verbose_name="处理时间")),
                ("process_status", models.CharField(default="pending", max_length=64, verbose_name="处理状态")),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                ("record_id", models.IntegerField(db_index=True, verbose_name="同步记录id")),
            ],
            options={
                "verbose_name": "客户端上报",
                "verbose_name_plural": "客户端上报",
                "ordering": ("-processed_at",),
                "unique_together": {("file_name", "record_id")},
            },
        ),
    ]
