# Generated by Django 4.2.22 on 2025-12-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tgpa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TGPAReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务id")),
                ("last_processed_at", models.DateTimeField(verbose_name="最后处理时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("total_processed_count", models.IntegerField(default=0, verbose_name="累计处理数量")),
                ("last_processed_count", models.IntegerField(default=0, verbose_name="最后一次处理数量")),
                ("last_error_message", models.TextField(blank=True, null=True, verbose_name="最后错误信息")),
                ("last_error_at", models.DateTimeField(blank=True, null=True, verbose_name="最后错误时间")),
            ],
            options={
                "verbose_name": "客户端上报",
                "verbose_name_plural": "客户端上报",
            },
        ),
    ]
