# Generated by Django 4.2.22 on 2025-12-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tgpa", "0002_tgpatask_error_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="tgpatask",
            name="task_status",
            field=models.CharField(max_length=64, null=True, verbose_name="任务状态"),
        ),
        migrations.AlterField(
            model_name="tgpatask",
            name="processed_at",
            field=models.DateTimeField(null=True, verbose_name="处理时间"),
        ),
    ]
