# Generated by Django 4.2.22 on 2026-02-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tgpa", "0002_tgpareportsyncrecord_tgpareport"),
    ]

    operations = [
        migrations.AddField(
            model_name="tgpatask",
            name="task_type",
            field=models.IntegerField(default=8, verbose_name="任务类型"),
        ),
    ]
