# Generated by Django 4.2.22 on 2026-03-20 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("tgpa", "0003_tgpatask_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tgpatask",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name="创建时间"
            ),
            preserve_default=False,
        ),
    ]
