# Generated by Django 4.2.22 on 2025-12-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tgpa", "0003_tgpatask_task_status_alter_tgpatask_processed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tgpatask",
            name="file_status",
            field=models.CharField(max_length=64, null=True, verbose_name="文件状态"),
        ),
    ]
