# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2022 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2022-06-27 13:45
from __future__ import unicode_literals

from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("apm", "0006_auto_20220614_1735"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomServiceConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
                ("app_name", models.CharField(max_length=128, verbose_name="应用名称")),
                ("config_level", models.CharField(max_length=50, verbose_name="配置级别")),
                ("config_key", models.CharField(max_length=255, verbose_name="配置key")),
                ("type", models.CharField(max_length=32, verbose_name="类型")),
                ("name", models.CharField(max_length=258, verbose_name="名称")),
                ("rule", bkmonitor.utils.db.fields.JsonField(verbose_name="匹配规则")),
                ("match_type", models.CharField(max_length=32, verbose_name="匹配类型")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="endpoint",
            name="extra_data",
            field=models.TextField(null=True, verbose_name="额外数据"),
        ),
        migrations.AddField(
            model_name="samplerconfig",
            name="sampler_type",
            field=models.CharField(default="random", max_length=64, verbose_name="采样类型"),
        ),
        migrations.AlterField(
            model_name="apminstancediscover",
            name="discover_key",
            field=models.CharField(max_length=255, verbose_name="应用名称"),
        ),
    ]
