# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-04-14 10:02
from __future__ import unicode_literals

from django.db import migrations

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("apm", "0020_auto_20230309_1547"),
    ]

    operations = [
        migrations.AddField(
            model_name="datalink",
            name="pre_calculate_config",
            field=bkmonitor.utils.db.fields.JsonField(null=True, verbose_name="预计算数据存储配置"),
        ),
    ]
