# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-05-27 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apm", "0021_datalink_pre_calculate_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="EbpfApplicationConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
                ("application_id", models.IntegerField(verbose_name="应用Id")),
            ],
            options={
                "verbose_name": "ebpf应用配置",
            },
        ),
    ]
