# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-07-04 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apm", "0022_ebpfapplicationconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
                ("app_name", models.CharField(max_length=128, verbose_name="应用名称")),
                ("config_level", models.CharField(max_length=50, verbose_name="配置级别")),
                ("config_key", models.CharField(max_length=255, verbose_name="配置key")),
                ("enabled", models.BooleanField(default=True, verbose_name="是否开启license检查")),
                ("expire_time", models.IntegerField(verbose_name="license 过期时间")),
                ("tolerable_expire", models.CharField(max_length=12, verbose_name="容忍过期时间")),
                ("number_nodes", models.IntegerField(verbose_name="可接受探针实例数量")),
                ("tolerable_num_ratio", models.FloatField(default=1.0, verbose_name="可接受探针实例数量倍率")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
