# Generated by Django 3.2.15 on 2023-07-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apm", "0023_auto_20230718_1657"),
        ("apm", "0023_licenseconfig"),
    ]

    operations = [
    ]
