# Generated by Django 3.2.15 on 2023-07-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apm", "0024_auto_20230726_1124"),
    ]

    operations = [
        migrations.AddField(
            model_name="datalink",
            name="elasticsearch_cluster_id",
            field=models.IntegerField(null=True, verbose_name="默认ES集群ID(在快速创建应用、创建默认预计算集群时会用到)"),
        ),
        migrations.AlterField(
            model_name="datalink",
            name="influxdb_cluster_name",
            field=models.CharField(max_length=128, null=True, verbose_name="时序数据存储的influxdb集群名称"),
        ),
        migrations.AlterField(
            model_name="datalink",
            name="kafka_cluster_id",
            field=models.IntegerField(null=True, verbose_name="kafka集群id"),
        ),
        migrations.AlterField(
            model_name="datalink",
            name="metric_transfer_cluster_id",
            field=models.CharField(max_length=128, null=True, verbose_name="Metric Transfer集群id"),
        ),
        migrations.AlterField(
            model_name="datalink",
            name="trace_transfer_cluster_id",
            field=models.CharField(max_length=128, null=True, verbose_name="Trace Es Transfer集群id"),
        ),
    ]
