# Generated by Django 3.2.15 on 2023-08-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0024_merge_0023_auto_20230718_1657_0023_licenseconfig'),
        ('apm', '0025_auto_20230711_1505'),
    ]

    operations = [
    ]
