# Generated by Django 3.2.15 on 2023-08-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apm", "0026_merge_20230801_1918"),
    ]

    operations = [
        migrations.AddField(
            model_name="topoinstance",
            name="sdk_language",
            field=models.CharField(max_length=255, null=True, verbose_name="探针语言"),
        ),
        migrations.AddField(
            model_name="topoinstance",
            name="sdk_name",
            field=models.CharField(max_length=255, null=True, verbose_name="探针类型"),
        ),
        migrations.AddField(
            model_name="topoinstance",
            name="sdk_version",
            field=models.CharField(max_length=255, null=True, verbose_name="探针版本"),
        ),
        migrations.AlterField(
            model_name="normaltypevalueconfig",
            name="type",
            field=models.CharField(
                choices=[
                    ("metrics_batch_size", "每批Metric发送大小"),
                    ("traces_batch_size", "每批Trace发送大小"),
                    ("logs_batch_size", "每批Log发送大小"),
                ],
                max_length=32,
                verbose_name="配置类型",
            ),
        ),
    ]
