# Generated by Django 3.2.15 on 2023-08-02 05:48

from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("apm", "0027_auto_20230802_1027"),
    ]

    operations = [
        migrations.CreateModel(
            name="DbConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
                ("app_name", models.CharField(max_length=128, verbose_name="应用名称")),
                ("config_level", models.CharField(max_length=50, verbose_name="配置级别")),
                ("config_key", models.CharField(max_length=255, verbose_name="配置key")),
                ("db_system", models.CharField(max_length=32, verbose_name="DB类型")),
                ("trace_mode", models.CharField(max_length=32, verbose_name="追踪模式")),
                ("length", models.IntegerField(verbose_name="保留长度")),
                ("predicate_key", models.CharField(max_length=32, verbose_name="发现字段")),
                ("match", bkmonitor.utils.db.fields.JsonField(verbose_name="匹配字段")),
                ("cut_keys", bkmonitor.utils.db.fields.JsonField(verbose_name="剪辑字段")),
                ("drop_keys", bkmonitor.utils.db.fields.JsonField(verbose_name="丢弃字段")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
