# Generated by Django 3.2.15 on 2023-08-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apm", "0029_probeconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbconfig",
            name="threshold",
            field=models.IntegerField(default=500, verbose_name="阈值"),
        ),
        migrations.AlterField(
            model_name="licenseconfig",
            name="expire_time",
            field=models.BigIntegerField(verbose_name="license 过期时间"),
        ),
    ]
