# Generated by Django 3.2.15 on 2023-12-21 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apm", "0032_auto_20231017_1646"),
        ("apm", "0032_auto_20231219_2003"),
    ]

    operations = []
