# Generated by Django 3.2.15 on 2023-12-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apm', '0032_auto_20231124_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='bkdataflowconfig',
            name='deploy_bk_biz_id',
            field=models.IntegerField(default=None, verbose_name='计算平台数据源所在的业务ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bkdataflowconfig',
            name='flow_type',
            field=models.CharField(
                choices=[('tail_sampling', '尾部采样Flow')], default=None, max_length=32, verbose_name='Flow类型'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bkdataflowconfig',
            name='bk_biz_id',
            field=models.IntegerField(verbose_name='监控业务id'),
        ),
    ]
