# Generated by Django 3.2.15 on 2023-11-28 03:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('apm', '0032_alter_normaltypevalueconfig_type'),
        ('apm', '0032_auto_20231017_1646'),
    ]

    operations = []
