# Generated by Django 3.2.15 on 2023-12-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apm", "0033_merge_0032_auto_20231017_1646_0032_auto_20231219_2003"),
        ("apm", "0033_merge_20231128_1157"),
    ]

    operations = [
    ]
