# Generated by Django 3.2.15 on 2024-01-15 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apm", "0033_auto_20240111_1434"),
        ("apm", "0034_merge_20231229_1707"),
    ]

    operations = []
