# Generated by Django 3.2.15 on 2024-01-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm", "0035_merge_20240115_1605"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiledatasource",
            name="retention",
            field=models.IntegerField(null=True, verbose_name="过期时间"),
        ),
    ]
