# Generated by Django 3.2.15 on 2024-04-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm", "0037_apmapplication_is_enabled_profiling"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiledatasource",
            name="profile_bk_biz_id",
            field=models.IntegerField(default=None, verbose_name="Profile数据源创建在 bkbase 的业务 id(非业务下创建会与 bk_biz_id 不一致)"),
            preserve_default=False,
        ),
    ]
