# Generated by Django 3.2.15 on 2024-05-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm", "0038_profiledatasource_profile_bk_biz_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileservice",
            name="sample_type",
            field=models.CharField(max_length=128, null=True, verbose_name="采样类型"),
        ),
    ]
