# Generated by Django 3.2.15 on 2024-05-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm", "0038_profiledatasource_profile_bk_biz_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationHub",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
                ("bcs_cluster_id", models.CharField(max_length=255, verbose_name="BCS 集群 ID")),
                ("app_name", models.CharField(max_length=50, null=True, verbose_name="应用名称")),
                ("app_id", models.IntegerField(null=True, verbose_name="应用 Id")),
                ("custom_report_id", models.IntegerField(null=True, verbose_name="日志自定义上报 ID")),
                ("custom_report_index_set_id", models.IntegerField(null=True, verbose_name="日志定义上报索引集ID")),
                ("metric_data_id", models.IntegerField(null=True, verbose_name="APM Metric DataId")),
                ("trace_data_id", models.IntegerField(null=True, verbose_name="APM Trace DataId")),
                ("profile_data_id", models.IntegerField(null=True, verbose_name="APM Profile DataId")),
                ("log_data_id", models.IntegerField(null=True, verbose_name="APM Log DataId")),
                ("is_finished", models.BooleanField(null=True, default=False, verbose_name="是否已创建完成")),
            ],
            options={
                "verbose_name": "大应用列表",
            },
        ),
    ]
