# Generated by Django 3.2.15 on 2024-06-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm", "0039_profileservice_sample_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileservice",
            name="is_large",
            field=models.BooleanField(default=False, verbose_name="是否是大数据量服务"),
        ),
    ]
