# Generated by Django 3.2.15 on 2024-09-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apm', '0041_apmtopodiscoverrule_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_biz_id', models.IntegerField(verbose_name='业务id')),
                ('app_name', models.CharField(max_length=255, verbose_name='所属应用')),
                ('bk_data_id', models.IntegerField(default=-1, verbose_name='数据id')),
                ('result_table_id', models.CharField(default='', max_length=128, verbose_name='结果表id')),
                ('collector_config_id', models.IntegerField(null=True, verbose_name='索引集id')),
                ('index_set_id', models.IntegerField(null=True, verbose_name='索引集id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='apmapplication',
            name='is_enabled_log',
            field=models.BooleanField(default=False, verbose_name='是否开启 Logs 功能'),
        ),
        migrations.AddField(
            model_name='apmapplication',
            name='is_enabled_metric',
            field=models.BooleanField(default=True, verbose_name='是否开启 Metrics 功能'),
        ),
        migrations.AddField(
            model_name='apmapplication',
            name='is_enabled_trace',
            field=models.BooleanField(default=True, verbose_name='是否开启 Traces 功能'),
        ),
        migrations.AddField(
            model_name='apmapplication',
            name='token',
            field=models.CharField(default='', max_length=256, verbose_name='应用 Token'),
        ),
    ]
