# Generated by Django 3.2.15 on 2024-10-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apm", "0042_add_application_token_and_log_datasource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiledatasource",
            name="profile_bk_biz_id",
            field=models.IntegerField(null=True, verbose_name="Profile数据源创建在 bkbase 的业务 id(非业务下创建会与 bk_biz_id 不一致)"),
        ),
    ]
