# Generated by Django 3.2.15 on 2024-10-07 08:17

import uuid

from django.db import migrations


def old_apm_application_token_fill(apps, schema_editor):
    """
    填充存量 apm 应用的 token
    """
    ApmApplication = apps.get_model("apm", "apmapplication")
    for application in ApmApplication.objects.all():
        try:
            if application.token == "":
                application.token = uuid.uuid4().hex  # 长度 32，(16 个随机字符的 16 进制表示)
                application.save()
        except Exception as e:  # pylint: disable=broad-except
            print("applicaiton({}) token fill error({})".format(application.id, e))
            continue


class Migration(migrations.Migration):
    dependencies = [
        ('apm', '0042_add_application_token_and_log_datasource'),
    ]

    operations = [
        migrations.RunPython(old_apm_application_token_fill),
    ]
