# Generated by Django 3.2.15 on 2024-11-29 08:25

from django.db import migrations, models

from apm.models import ApmTopoDiscoverRule


def update_discover_rules(apps, schema_editor):
    ApmTopoDiscoverRule.init_builtin_config()


class Migration(migrations.Migration):
    dependencies = [
        ('apm', '0043_alter_profiledatasource_profile_bk_biz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apmtopodiscoverrule',
            name='type',
            field=models.CharField(
                choices=[
                    ('category', 'Category'),
                    ('framework', 'Framework'),
                    ('platform', 'Platform'),
                    ('sdk', 'Sdk'),
                ],
                default='category',
                max_length=128,
                verbose_name='服务信息',
            ),
        ),
        migrations.AddField(
            model_name='toponode',
            name='framework',
            field=models.JSONField(null=True, verbose_name='服务框架'),
        ),
        migrations.AddField(
            model_name='toponode',
            name='platform',
            field=models.JSONField(null=True, verbose_name='部署平台'),
        ),
        migrations.AddField(
            model_name='toponode',
            name='sdk',
            field=models.JSONField(null=True, verbose_name='上报sdk'),
        ),
        migrations.AlterField(
            model_name='apmtopodiscoverrule',
            name='endpoint_key',
            field=models.CharField(max_length=255, null=True, verbose_name='接口字段'),
        ),
        migrations.AlterField(
            model_name='apmtopodiscoverrule',
            name='instance_key',
            field=models.CharField(max_length=255, null=True, verbose_name='实例字段'),
        ),
        migrations.AlterField(
            model_name='apmtopodiscoverrule',
            name='predicate_key',
            field=models.CharField(max_length=128, null=True, verbose_name='判断字段'),
        ),
        migrations.AlterField(
            model_name='apmtopodiscoverrule',
            name='topo_kind',
            field=models.CharField(max_length=50, null=True, verbose_name='topo发现类型'),
        ),
        migrations.RunPython(update_discover_rules),
    ]
