# Generated by Django 3.2.15 on 2024-11-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apm', '0043_alter_profiledatasource_profile_bk_biz_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BcsClusterDefaultApplicationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_biz_id', models.IntegerField(verbose_name='业务 ID')),
                ('app_name', models.CharField(max_length=50, verbose_name='应用名称')),
                ('cluster_id', models.CharField(max_length=128, verbose_name='集群 ID')),
            ],
            options={
                'verbose_name': 'BCS 集群中默认上报 APM 应用关联配置',
            },
        ),
    ]
