# Generated by Django 3.2.15 on 2024-12-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apm", "0045_auto_20241203_1450"),
    ]

    operations = [
        migrations.AddField(
            model_name="toponode",
            name="source",
            field=models.JSONField(default=list, verbose_name="服务发现来源"),
        ),
    ]
