# Generated by Django 3.2.15 on 2025-01-23 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apm", "0046_toponode_source"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="endpoint",
            index_together={("bk_biz_id", "app_name")},
        ),
        migrations.AlterIndexTogether(
            name="logdatasource",
            index_together={("bk_biz_id", "app_name")},
        ),
        migrations.AlterIndexTogether(
            name="metricdatasource",
            index_together={("bk_biz_id", "app_name")},
        ),
        migrations.AlterIndexTogether(
            name="profiledatasource",
            index_together={("bk_biz_id", "app_name")},
        ),
        migrations.AlterIndexTogether(
            name="rootendpoint",
            index_together={("bk_biz_id", "app_name")},
        ),
        migrations.AlterIndexTogether(
            name="tracedatasource",
            index_together={("bk_biz_id", "app_name")},
        ),
    ]
