# Generated by Django 3.2.25 on 2025-04-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apm', '0047_auto_20250123_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='apmapplication',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=64, verbose_name='租户ID'),
        ),
        migrations.AlterField(
            model_name='normaltypevalueconfig',
            name='type',
            field=models.CharField(
                choices=[
                    ('metrics_batch_size', '每批Metric发送大小'),
                    ('traces_batch_size', '每批Trace发送大小'),
                    ('logs_batch_size', '每批Log发送大小'),
                    ('db_slow_command_config', 'db慢命令配置'),
                    ('db_config', 'db配置'),
                    ('attributes_config_logs', 'attributes 配置(logs)'),
                ],
                max_length=32,
                verbose_name='配置类型',
            ),
        ),
    ]
