# Generated by Django 3.2.25 on 2025-07-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm", "0048_auto_20250418_1123"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionconfig",
            name="bk_tenant_id",
            field=models.CharField(default="system", max_length=128, verbose_name="租户ID"),
        ),
    ]
