# Generated by Django 3.2.25 on 2025-08-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm", "0049_subscriptionconfig_bk_tenant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="toponode",
            name="is_permanent",
            field=models.BooleanField(default=False, verbose_name="是否永久保存"),
        ),
    ]
