# Generated by Django 3.2.25 on 2025-10-16 06:48

import bkmonitor.utils.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm", "0050_toponode_is_permanent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("config_type", models.CharField(max_length=50, verbose_name="配置类型")),
                ("config_data", bkmonitor.utils.db.fields.JsonField(verbose_name="配置数据")),
            ],
            options={
                "verbose_name": "平台配置",
                "verbose_name_plural": "平台配置",
            },
        )
    ]
