# Generated by Django 4.2.27 on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm", "0051_auto_20251017_1101"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiledatasource",
            name="bkdata_datalink_config",
            field=models.JSONField(default=dict, verbose_name="BkData链路配置"),
        ),
    ]
