# Generated by Django 4.2.27 on 2026-04-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm", "0051_auto_20251017_1101"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiledatasource",
            name="is_v4",
            field=models.BooleanField(default=False, verbose_name="是否使用V4声明式链路创建"),
        )
    ]
