# Generated by Django 3.2.25 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm", "0052_add_profiledatasource_v4"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedTraceDataSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quota", models.IntegerField(default=100, verbose_name="容量上限")),
                ("usage_count", models.IntegerField(default=0, verbose_name="当前用量")),
                ("is_enabled", models.BooleanField(default=False, db_index=True, verbose_name="是否启用")),
                ("bk_data_id", models.IntegerField(default=-1, verbose_name="数据 ID")),
                (
                    "result_table_id",
                    models.CharField(default="", max_length=128, verbose_name="结果表 ID"),
                ),
                ("index_set_id", models.IntegerField(null=True, verbose_name="索引集 ID")),
                (
                    "index_set_name",
                    models.CharField(max_length=512, null=True, verbose_name="索引集名称"),
                ),
            ],
            options={
                "verbose_name": "Trace 共享数据源",
            },
        ),
        migrations.AddField(
            model_name="tracedatasource",
            name="shared_datasource_id",
            field=models.IntegerField(default=None, null=True, verbose_name="共享数据源 ID"),
        ),
        migrations.AddField(
            model_name="metricdatasource",
            name="shared_datasource_id",
            field=models.IntegerField(default=None, null=True, verbose_name="共享数据源 ID"),
        ),
        migrations.AddField(
            model_name="logdatasource",
            name="shared_datasource_id",
            field=models.IntegerField(default=None, null=True, verbose_name="共享数据源 ID"),
        ),
        migrations.AddField(
            model_name="profiledatasource",
            name="shared_datasource_id",
            field=models.IntegerField(default=None, null=True, verbose_name="共享数据源 ID"),
        ),
    ]
