# Generated by Django 4.2.27 on 2026-05-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm", "0054_add_tracedatasource_bkdata_datalink_config"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fieldnormalizerconfig",
            options={"verbose_name": "字段标准化配置", "verbose_name_plural": "字段标准化配置"},
        ),
        migrations.AlterField(
            model_name="normaltypevalueconfig",
            name="type",
            field=models.CharField(
                choices=[
                    ("metrics_batch_size", "每批Metric发送大小"),
                    ("traces_batch_size", "每批Trace发送大小"),
                    ("logs_batch_size", "每批Log发送大小"),
                    ("profiles_batch_size", "每批Profile发送大小"),
                    ("db_slow_command_config", "db慢命令配置"),
                    ("db_config", "db配置"),
                    ("attributes_config_logs", "attributes 配置(logs)"),
                    ("code_relabel_config", "返回码重定义配置"),
                    ("all_app_config", "app全量配置"),
                    ("all_service_config", "service全量配置"),
                    ("all_instance_config", "instance全量配置"),
                ],
                max_length=32,
                verbose_name="配置类型",
            ),
        ),
    ]
