apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qcloud-exporter.fullname" . }}
  labels:
    {{- include "qcloud-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
    credential:
      access_key: {{ .Values.config.credential.secretId | quote }}
      secret_key: {{ .Values.config.credential.secretKey | quote }}
      region: {{ .Values.config.credential.region | quote }}

    rate_limit: {{ .Values.config.rateLimit }}

    products: {{ .Values.config.products | toYaml | nindent 4 }}
