# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2020-05-07 04:42


import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weixin_core", "0002_auto_20181203_0217"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bkweixinuser",
            options={"verbose_name": "微信用户", "verbose_name_plural": "微信用户"},
        ),
        migrations.AlterField(
            model_name="bkweixinuser",
            name="avatar_url",
            field=models.CharField(blank=True, max_length=255, verbose_name="头像"),
        ),
        migrations.AlterField(
            model_name="bkweixinuser",
            name="city",
            field=models.CharField(blank=True, max_length=63, verbose_name="城市"),
        ),
        migrations.AlterField(
            model_name="bkweixinuser",
            name="country",
            field=models.CharField(blank=True, max_length=63, verbose_name="国家"),
        ),
        migrations.AlterField(
            model_name="bkweixinuser",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="加入时间"),
        ),
        migrations.AlterField(
            model_name="bkweixinuser",
            name="email",
            field=models.CharField(blank=True, max_length=128, verbose_name="邮箱"),
        ),
        migrations.AlterField(
            model_name="bkweixinuser",
            name="gender",
            field=models.CharField(blank=True, max_length=15, verbose_name="性别"),
        ),
        migrations.AlterField(
            model_name="bkweixinuser",
            name="mobile",
            field=models.CharField(blank=True, max_length=11, verbose_name="手机号"),
        ),
        migrations.AlterField(
            model_name="bkweixinuser",
            name="nickname",
            field=models.CharField(blank=True, max_length=127, verbose_name="昵称"),
        ),
        migrations.AlterField(
            model_name="bkweixinuser",
            name="openid",
            field=models.CharField(max_length=128, null=True, verbose_name="微信用户应用唯一标识"),
        ),
        migrations.AlterField(
            model_name="bkweixinuser",
            name="province",
            field=models.CharField(blank=True, max_length=63, verbose_name="省份"),
        ),
        migrations.AlterField(
            model_name="bkweixinuser",
            name="qr_code",
            field=models.CharField(blank=True, max_length=128, verbose_name="二维码链接"),
        ),
        migrations.AlterField(
            model_name="bkweixinuser",
            name="userid",
            field=models.CharField(max_length=128, null=True, verbose_name="企业微信用户应用唯一标识"),
        ),
    ]
