# Generated by Django 3.2.15 on 2023-06-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_measure', '0009_metricdatahistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricdatahistory',
            name='metric_id',
            field=models.CharField(db_index=True, max_length=128, verbose_name='指标ID'),
        ),
    ]
