swagger: '2.0'
basePath: /
info:
  version: '1.0'
  title: API Gateway Resources
  description: ''
schemes:
  - http
paths:
  /app/collector/plugin_import_without_frontend/:
    post:
      operationId: plugin_import_without_frontend
      description: 导入插件API
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/collector_plugin/plugin_import_without_frontend/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: plugin_import_without_frontend
    /app/collector/export_plugin/:
      get:
        operationId: export_plugin
        description: 导出插件
        x-bk-apigateway-resource:
          isPublic: false
          allowApplyPermission: false
          matchSubpath: false
          backend:
            type: HTTP
            method: get
            path: /api/v4/collector_plugin/export_plugin/
            matchSubpath: false
          authConfig:
            appVerifiedRequired: true
            userVerifiedRequired: false
            resourcePermissionRequired: true
          descriptionEn: export_plugin