swagger: '2.0'
basePath: /
info:
  version: '1.0'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /app/event/ack_event/:
    post:
      operationId: ack_event
      description: 告警事件确认
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/event/ack_event/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: ack_event
  /app/custom_event/proxy_host_info/:
    get:
      operationId: proxy_host_info
      description: 获取自定义上报的proxy主机信息
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/custom_event/proxy_host_info/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: proxy host info
  /app/alert_info/search_alert_by_event/:
    post:
      operationId: search_alert_by_event
      description: 根据event获取告警处理信息
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/alert_info/search_alert_by_event/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: search alert by event
  /app/application/query_apm_event/:
    post:
      operationId: query_apm_event
      description: 查询APM相关事件信息
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /apm_api/v1/application/query_event/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: query apm event
  /app/event_plugin/deploy_event_plugin/:
    post:
      operationId: deploy_event_plugin
      description: 部署告警源插件
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/event_plugin/deploy_event_plugin/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: deploy event plugin
