swagger: '2.0'
basePath: /
info:
  version: '1.0'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /app/strategy/qos_check/:
    get:
      operationId: get_strategy_qos_status
      description: 获取告警策略流控状态
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/strategy/alarm_strategy_v3/qos_check/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: get_strategy_qos_status
