export const mockChart = {
  useUTC: false,
  animation: false,
  animationThreshold: 1,
  animationDurationUpdate: 0,
  animationDuration: 20,
  animationDelay: 300,
  title: {
    text: '',
    show: false,
  },
  color: [
    '#F0AE69',
    '#689DF3',
    '#6ED0E0',
    '#EF843C',
    '#E24D42',
    '#1F78C1',
    '#BA43A9',
    '#705DA0',
    '#508642',
    '#CCA300',
    '#447EBC',
    '#C15C17',
    '#890F02',
    '#0A437C',
    '#6D1F62',
    '#584477',
    '#B7DBAB',
    '#F4D598',
    '#70DBED',
    '#F9BA8F',
    '#F29191',
    '#82B5D8',
    '#E5A8E2',
    '#AEA2E0',
    '#629E51',
    '#E5AC0E',
    '#64B0C8',
    '#E0752D',
    '#BF1B00',
    '#0A50A1',
    '#962D82',
    '#614D93',
    '#9AC48A',
    '#F2C96D',
    '#65C5DB',
    '#F9934E',
    '#EA6460',
    '#5195CE',
    '#D683CE',
    '#806EB7',
    '#3F6833',
    '#967302',
    '#2F575E',
    '#99440A',
    '#58140C',
    '#052B51',
    '#511749',
    '#3F2B5B',
    '#E0F9D7',
    '#FCEACA',
    '#CFFAFF',
    '#F9E2D2',
    '#FCE2DE',
    '#BADFF4',
    '#F9D9F9',
    '#DEDAF7',
    '#F0AE69',
    '#689DF3',
    '#6ED0E0',
    '#EF843C',
    '#E24D42',
    '#1F78C1',
    '#BA43A9',
    '#705DA0',
    '#508642',
    '#CCA300',
    '#447EBC',
    '#C15C17',
    '#890F02',
    '#0A437C',
    '#6D1F62',
    '#584477',
    '#B7DBAB',
    '#F4D598',
    '#70DBED',
    '#F9BA8F',
    '#F29191',
    '#82B5D8',
    '#E5A8E2',
    '#AEA2E0',
    '#629E51',
    '#E5AC0E',
    '#64B0C8',
    '#E0752D',
    '#BF1B00',
    '#0A50A1',
    '#962D82',
    '#614D93',
    '#9AC48A',
    '#F2C96D',
    '#65C5DB',
    '#F9934E',
    '#EA6460',
    '#5195CE',
    '#D683CE',
    '#806EB7',
    '#3F6833',
    '#967302',
    '#2F575E',
    '#99440A',
    '#58140C',
    '#052B51',
    '#511749',
    '#3F2B5B',
    '#E0F9D7',
    '#FCEACA',
    '#CFFAFF',
    '#F9E2D2',
    '#FCE2DE',
    '#BADFF4',
    '#F9D9F9',
    '#DEDAF7',
  ],
  legend: {
    show: false,
  },
  tooltip: {
    show: true,
    trigger: 'axis',
    axisPointer: {
      type: 'line',
      label: {
        backgroundColor: '#6a7985',
      },
    },
    transitionDuration: 0,
    alwaysShowContent: false,
    backgroundColor: 'rgba(54,58,67,.88)',
    borderWidth: 0,
    textStyle: {
      fontSize: 12,
      color: '#BEC0C6',
    },
    extraCssText: 'max-width: 50%',
  },
  toolbox: {
    showTitle: false,
    itemSize: 0,
    iconStyle: {
      color: '#979ba5',
      borderWidth: 0,
      shadowColor: '#979ba5',
      shadowOffsetX: 0,
      shadowOffsetY: 0,
    },
    feature: {
      saveAsImage: {
        icon: 'path://',
      },
      dataZoom: {
        icon: {
          zoom: 'path://',
          back: 'path://',
        },
        show: true,
        yAxisIndex: false,
        iconStyle: {
          opacity: 0,
        },
      },
      restore: {
        icon: 'path://',
      },
    },
  },
  grid: {
    containLabel: true,
    left: 16,
    right: 16,
    top: 10,
    bottom: 10,
    backgroundColor: 'transparent',
  },
  xAxis: {
    type: 'time',
    boundaryGap: false,
    axisTick: {
      show: false,
    },
    axisLine: {
      show: false,
      lineStyle: {
        color: '#ccd6eb',
        width: 1,
        type: 'solid',
      },
    },
    axisLabel: {
      fontSize: 12,
      color: '#979BA5',
      showMinLabel: false,
      showMaxLabel: false,
      align: 'left',
    },
    splitLine: {
      show: false,
    },
    minInterval: 590000,
    splitNumber: 4,
    scale: true,
    interval: 590000,
    max: 'dataMax',
    min: 'dataMin',
  },
  markLine: [
    {
      z: 100,
    },
  ],
  yAxis: {
    type: 'value',
    axisLine: {
      show: false,
      lineStyle: {
        color: '#ccd6eb',
        width: 1,
        type: 'solid',
      },
    },
    axisTick: {
      show: false,
    },
    axisLabel: {
      color: '#979BA5',
    },
    splitLine: {
      show: true,
      lineStyle: {
        color: '#F0F1F5',
        type: 'dashed',
      },
    },
    scale: false,
    min: 0,
    z: 3,
    splitNumber: 2,
    minInterval: 1,
    max: 'dataMax',
  },
  series: [
    {
      name: '当前-异常率',
      cursor: 'auto',
      data: [
        {
          symbolSize: 6,
          value: [1740557520000, 1.287],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557580000, 0.42],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557640000, 0.833],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557700000, 0.42],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557760000, 2.575],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557820000, 1.731],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557880000, 3.587],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557940000, 1.234],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558000000, 0.881],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558060000, 1.25],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558120000, 0.843],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558180000, 1.271],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558240000, 2.62],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558300000, 1.26],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558360000, 1.276],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558420000, 1.265],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558480000, 1.265],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558540000, 1.244],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558600000, 0.854],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558660000, 1.754],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558720000, 0],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558780000, 1.293],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558840000, 1.694],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558900000, 0.843],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558960000, 1.282],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559020000, 0.843],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559080000, 1.271],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559140000, 0],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559200000, 0.421],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559260000, 1.276],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559320000, 0.423],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559380000, 0.851],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559440000, 0.411],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559500000, 1.276],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559560000, 1.754],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559620000, 1.287],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559680000, 0.851],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559740000, 0.816],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559800000, 1.293],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559860000, 0.847],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559920000, 0.418],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559980000, 2.127],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560040000, 0.84],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560100000, 0.854],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560160000, 0.854],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560220000, 1.694],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560280000, 0.84],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560340000, 2.173],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560400000, 1.754],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560460000, 0],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560520000, 0.416],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560580000, 1.687],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560640000, 1.746],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560700000, 0.819],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560760000, 0.881],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560820000, 1.25],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560880000, 1.687],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560940000, 0.42],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740561000000, 1.265],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740561060000, 0.425],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
      ],
      stack: 'y9twty9d05',
      unit: 'percent',
      z: 4,
      traceData: '',
      dimensions: {},
      color: '#F0AE69',
      type: 'line',
      showSymbol: false,
      symbol: 'circle',
      smooth: 0,
      precision: 6,
      lineStyle: {
        width: 2,
      },
      minBase: 0,
    },
    {
      name: '上周-异常率',
      cursor: 'auto',
      data: [
        {
          symbolSize: 6,
          value: [1740557520000, 1.276],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557580000, 1.709],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557640000, 1.282],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557700000, 0],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557760000, 1.694],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557820000, 1.694],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557880000, 1.282],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557940000, 1.702],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558000000, 1.673],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558060000, 0],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558120000, 0.423],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558180000, 1.666],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558240000, 0.858],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558300000, 0.851],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558360000, 0.858],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558420000, 0.858],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558480000, 2.1],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558540000, 1.298],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558600000, 1.271],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558660000, 1.239],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558720000, 1.276],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558780000, 0.427],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558840000, 0.423],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558900000, 0.833],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558960000, 0.851],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559020000, 1.702],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559080000, 1.255],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559140000, 0.425],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559200000, 1.694],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559260000, 1.255],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559320000, 1.293],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559380000, 0.414],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559440000, 0.858],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559500000, 1.287],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559560000, 1.293],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559620000, 1.709],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559680000, 0.851],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559740000, 0.819],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559800000, 0.865],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559860000, 1.26],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559920000, 1.68],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559980000, 0.854],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560040000, 1.31],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560100000, 0.819],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560160000, 2.145],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560220000, 0.421],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560280000, 1.239],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560340000, 1.793],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560400000, 0.869],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560460000, 0.826],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560520000, 1.694],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560580000, 1.731],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560640000, 2.542],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560700000, 1.255],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560760000, 0],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560820000, 1.282],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560880000, 1.287],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560940000, 3.493],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740561000000, 1.652],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740561060000, 0.421],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
      ],
      stack: 'uf4311b4dz',
      unit: 'percent',
      z: 4,
      traceData: '',
      dimensions: {},
      color: '#689DF3',
      type: 'line',
      showSymbol: false,
      symbol: 'circle',
      smooth: 0,
      precision: 6,
      lineStyle: {
        width: 2,
      },
      minBase: 0,
    },
    {
      name: '2个月前-异常率',
      cursor: 'auto',
      data: [
        {
          symbolSize: 6,
          value: [1740557520000, 0.84],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557580000, 0.836],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557640000, 0.843],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557700000, 1.709],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557760000, 0.84],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557820000, 1.276],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557880000, 2.136],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740557940000, 1.282],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558000000, 0.847],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558060000, 2.164],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558120000, 0],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558180000, 0.843],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558240000, 0],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558300000, 1.709],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558360000, 2.136],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558420000, 0.42],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558480000, 0.836],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558540000, 0],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558600000, 0.843],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558660000, 1.709],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558720000, 1.271],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558780000, 0.418],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558840000, 2.145],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558900000, 0.865],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740558960000, 0],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559020000, 1.724],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559080000, 0.425],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559140000, 0.836],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559200000, 1.271],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559260000, 2.564],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559320000, 0.416],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559380000, 1.271],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559440000, 0.84],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559500000, 0.416],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559560000, 0.847],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559620000, 1.282],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559680000, 0.843],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559740000, 1.694],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559800000, 2.155],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559860000, 1.276],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559920000, 0],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740559980000, 1.282],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560040000, 2.654],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560100000, 1.694],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560160000, 0.84],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560220000, 1.265],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560280000, 1.265],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560340000, 1.265],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560400000, 1.702],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560460000, 0.843],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560520000, 1.694],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560580000, 0],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560640000, 1.31],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560700000, 0.836],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560760000, 1.694],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560820000, 0.421],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560880000, 0.429],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740560940000, 0.847],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740561000000, 0.851],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
        {
          symbolSize: 6,
          value: [1740561060000, 0],
          itemStyle: {
            borderWidth: 6,
            enabled: true,
            shadowBlur: 0,
            opacity: 1,
          },
        },
      ],
      stack: 'nl2kh0uz68',
      unit: 'percent',
      z: 4,
      traceData: '',
      dimensions: {},
      color: '#6ED0E0',
      type: 'line',
      showSymbol: false,
      symbol: 'circle',
      smooth: 0,
      precision: 6,
      lineStyle: {
        width: 2,
      },
      minBase: 0,
    },
  ],
  customData: {
    maxXInterval: 3540000,
    maxSeriesCount: 60,
  },
};
