export const tableData = [
  {
    value: 234,
    proportion: 32.24,
    fluctuation: 10.34,
    color: '#FFB848',
    environment: 'test',
    date_source: '2',
    version: '1.0.0',
    k8s_process: '2222',
  },
  {
    value: 34,
    proportion: 7.24,
    fluctuation: 2.34,
    color: '#67C19B',
    environment: 'dev',
    date_source: '2',
    version: '1.0.1',
    k8s_process: 'process-text',
  },
  {
    value: 134,
    proportion: 0.24,
    fluctuation: 9.34,
    color: '#8684DF',
    environment: 'prod',
    date_source: '2',
    version: '1.0.2',
    k8s_process: 'k8s',
  },
  {
    value: 334,
    proportion: 30.24,
    fluctuation: 67.34,
    color: '#FF74A4',
    environment: 'stag',
    date_source: '2',
    version: '1.3.0',
    k8s_process: 'process',
  },
];
export const panelData = [
  {
    id: '1',
    title: '12.31.342.12',
    list: [
      {
        title: '磁盘空间使用率',
        draging: true,
        instant: false,
        subTitle: 'system.mem.pct_used',
        dashboardId: 'new-metric-chart1',
      },
      {
        title: '磁盘空间使用率',
        draging: true,
        instant: false,
        subTitle: 'system.mem.pct_used',
        dashboardId: 'new-metric-chart1',
      },
      {
        title: '应用程序内存使用占比',
        descrition: '2',
        draging: true,
        instant: false,
        subTitle: 'system.mem.pct_used',
        dashboardId: 'new-metric-chart2',
      },
    ],
  },
  {
    id: '0',
    title: '12.31.342.12',
    list: [
      {
        title: '磁盘空间使用率',
        draging: true,
        instant: false,
        subTitle: 'system.mem.pct_used',
        dashboardId: 'new-metric-chart1',
      },
    ],
  },
  {
    id: '2',
    title: '12.32.43.43',
    list: [
      {
        title: '应用程序内存使用占比',
        descrition: '2',
        draging: true,
        instant: false,
        subTitle: 'system.mem.pct_used',
        dashboardId: 'new-metric-chart3',
      },
      {
        title: '磁盘空间使用率',
        descrition: '2',
        draging: true,
        instant: false,
        subTitle: 'system.mem.pct_used',
        dashboardId: 'new-metric-chart4',
      },
    ],
  },
];
export const metricData = [
  {
    id: 8691268,
    result_table_id: '5000140_bkapm_metric_trpc_demo.__default__',
    result_table_name: 'bkapm_trpc_demo_metric',
    metric_field: 'rpc_server_handled_total',
    metric_field_name: 'rpc_server_handled_total',
    unit: '',
    unit_conversion: 1,
    dimensions: [
      {
        id: 'caller_ip',
        name: 'caller_ip',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'canary',
        name: 'canary',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'callee_service',
        name: 'callee_service',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'caller_service',
        name: 'caller_service',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'version',
        name: 'version',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'container_name',
        name: 'container_name',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'user_ext3',
        name: 'user_ext3',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'target',
        name: 'target',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'callee_con_setid',
        name: 'callee_con_setid',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'caller_container',
        name: 'caller_container',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'callee_ip',
        name: 'callee_ip',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'node',
        name: 'node',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'namespace',
        name: 'namespace',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'code_type',
        name: 'code_type',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'caller_group',
        name: 'caller_group',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'callee_container',
        name: 'callee_container',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'callee_server',
        name: 'callee_server',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'caller_con_setid',
        name: 'caller_con_setid',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'callee_method',
        name: 'callee_method',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'service_name',
        name: 'service_name',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'caller_server',
        name: 'caller_server',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'user_ext1',
        name: 'user_ext1',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'sdk_name',
        name: 'sdk_name',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'city',
        name: 'city',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'caller_method',
        name: 'caller_method',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'region',
        name: 'region',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'code',
        name: 'code',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'user_ext2',
        name: 'user_ext2',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'instance',
        name: 'instance',
        is_dimension: true,
        type: 'string',
      },
      {
        id: 'env_name',
        name: 'env_name',
        is_dimension: true,
        type: 'string',
      },
    ],
    plugin_type: '',
    related_name: 'bkapm_trpc_demo_metric',
    related_id: '9607',
    collect_config: '',
    collect_config_ids: [],
    result_table_label: 'apm',
    data_source_label: 'custom',
    data_type_label: 'time_series',
    data_target: 'none_target',
    default_dimensions: ['bk_target_ip', 'bk_target_cloud_id'],
    default_condition: [],
    description: '',
    collect_interval: 1,
    category_display: '',
    result_table_label_name: 'APM',
    extend_fields: {
      bk_data_id: 1579580,
    },
    use_frequency: 3,
    is_duplicate: 0,
    readable_name: '5000140_bkapm_metric_trpc_demo.rpc_server_handled_total',
    metric_md5: '4f85f1c69b05e2db826e485d8160a26a',
    data_label: '',
    metric_id: 'custom.5000140_bkapm_metric_trpc_demo.__default__.rpc_server_handled_total',
  },
];
