swagger: '2.0'
basePath: /
info:
  version: '1.0'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /v2/monitor_v3/validate_custom_ts_group_name/:
    get:
      operationId: validate_custom_ts_group_name
      description: 校验自定义指标名称是否合法
      tags:
      - custom_metric
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/custom_metric/validate_custom_ts_group_name/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: validate_custom_ts_group_name
