# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
from django.db import models
from django.utils.translation import gettext as _


class TranslateField(models.TextField):
    """翻译字段"""

    def _from_db_value(self, value, expression, connection, context):
        return _(value)

    def _system(self):
        # 内置指标名(system)
        return [
            _('采集器IP'),
            _('主机名'),
            _('设备名'),
            _('CPU使用率'),
            _('CPU空闲率'),
            _('CPU等待IO的时间占比'),
            _('CPU分配给虚拟机的时间占比'),
            _('CPU系统程序使用占比'),
            _('CPU用户程序使用占比'),
            _('业务ID'),
            _('开发商ID'),
            _('采集器云区域ID'),
            _('数据上报时间'),
            _('I/O平均等待时长'),
            _('I/O平均服务时长'),
            _('I/O读次数'),
            _('I/O读速率'),
            _('I/O写次数'),
            _('I/O写速率'),
            _('I/O使用率'),
            _('设备每次I/O平均数据大小'),
            _('平均I/O队列长度'),
            _('时区城市'),
            _('系统启动时间'),
            _('系统总进程数'),
            _('机器时区'),
            _('CPU单核使用率'),
            _('CPU单核空闲率'),
            _('CPU单核等待IO的时间占比'),
            _('CPU单核分配给虚拟机的时间占比'),
            _('CPU单核系统程序使用占比'),
            _('CPU单核用户程序使用占比'),
            _('内存buffered大小'),
            _('内存cached大小'),
            _('物理内存空闲量'),
            _('物理内存总大小'),
            _('应用程序内存可用量'),
            _('应用程序内存可用率'),
            _('应用程序内存使用量'),
            _('应用程序内存使用占比'),
            _('物理内存已用量'),
            _('物理内存已用占比'),
            _('closewait连接数'),
            _('timewait连接数'),
            _('closed连接数'),
            _('closing连接数'),
            _('estab连接数'),
            _('finwait1连接数'),
            _('finwait2连接数'),
            _('lastact连接数'),
            _('listen连接数'),
            _('synrecv连接数'),
            _('synsent连接数'),
            _('udp接收包量'),
            _('udp发送包量'),
            _('磁盘可用空间大小'),
            _('磁盘总空间大小'),
            _('磁盘已用空间大小'),
            _('磁盘空间使用率'),
            _('网卡入包量'),
            _('网卡出包量'),
            _('网卡入流量'),
            _('网卡出流量'),
            _('进程二进制文件名称'),
            _('进程显示名称'),
            _('进程匹配参数正则'),
            _('进程id'),
            _('进程组id'),
            _('父进程ID'),
            _('进程状态'),
            _('进程用户名'),
            _('进程CPU使用率'),
            _('进程内存使用率'),
            _('进程文件句柄数'),
            _('进程使用物理内存'),
            _('进程使用虚拟内存'),
            _('可用inode数量'),
            _('总inode数量'),
            _('已用inode数量'),
            _('已用inode占比'),
            _('SWAP空闲量'),
            _('SWAP总量'),
            _('SWAP已用量'),
            _('SWAP已用占比'),
            _('监听中的端口'),
            _('未监听的端口'),
            _('监听IP不匹配的端口'),
            _('绑定的IP地址'),
            _('协议'),
            _('进程存活状态'),
            _('进程端口状态'),
            _('1分钟平均负载'),
            _('5分钟平均负载'),
            _('15分钟平均负载'),
            _('设备类型'),
            _('挂载点'),
            _('CMDB层级信息'),
            _('目标IP'),
            _('云区域ID'),
            _('网卡入流量比特速率'),
            _('网卡出流量比特速率 '),
            _('网卡出流量比特速率'),
            _('低优先级程序在用户态执行的CPU占比'),
            _('硬件中断数的CPU占比'),
            _('软件中断数的CPU占比'),
            _('内核在虚拟机上运行的CPU占比'),
            _('最大文件描述符'),
            _('登录的用户数'),
            _('正在运行的进程总个数'),
            _('处于等待I/O完成的进程个数'),
            _('系统启动后所创建过的进程数量'),
            _('系统上下文切换次数'),
            _('单核CPU的load'),
            _('网卡错误包'),
            _('网卡丢弃包'),
            _('网卡物理层丢弃'),
            _('设备驱动程序检测到的载波丢失数'),
            _('网卡冲突包'),
            _('swap从硬盘到内存'),
            _('swap从内存到硬盘'),
            _('进程运行时间'),
            _('进程监听端口'),
            _('进程占用用户态时间'),
            _('进程占用系统态时间'),
            _('整体占用时间'),
            'fd_limit_soft',
            'fd_limit_hard',
            _('进程io累计读'),
            _('进程io累计写'),
            _('进程io读速率'),
            _('进程io写速率'),
            _('共享内存使用量'),
            'Agent ID',
            _('采集主机ID'),
            _('目标主机ID'),
        ]

    def _uptimecheck(self):
        # 内置指标名 uptimecheck
        return [
            _('耗时'),
            _('错误码'),
            _('状态'),
            _('目标主机'),
            _('目标端口'),
            _('任务 ID'),
            _('任务类型'),
            _('节点 ID'),
            _('单点可用率'),
            _('业务ID'),
            _('开发商ID'),
            _('采集器云区域ID'),
            _('数据上报时间'),
            _('重试次数'),
            _('任务ID'),
            _('编码类型'),
            _('响应长度'),
            _('媒体类型'),
            _('响应消息'),
            _('请求方法'),
            _('响应状态码'),
            _('请求步骤数'),
            _('请求网址'),
            _('重载次数'),
            _('运行任务数'),
            _('成功事件数'),
            _('启动时间'),
            _('版本'),
            _('失败事件数'),
            _('错误事件数'),
            _('重载时间'),
            _('历史载入任务数'),
            _('采集器IP'),
            _('CMDB层级信息'),
            _('目标地址'),
            _('目标地址类型'),
            _('丢包率'),
            _('最大时延'),
            _('最小时延'),
            _('平均时延'),
            _('上报时间'),
            _('响应时间'),
            _('请求域名解析结果IP'),
            'Agent ID',
            _('采集主机ID'),
            _('目标主机ID'),
            _('节点ID'),
        ]

    def _ping(self):
        # ping server
        return [
            _('业务ID'),
            _('目标IP'),
            _('目标云区域ID'),
            _('采集器IP'),
            _('采集器云区域ID'),
            _('丢包率'),
            _('最大时延'),
            _('最小时延'),
            _('平均时延'),
            _('上报时间'),
        ]

    def _label(self):
        # metadata.models.common.Label
        return [
            # _('APM'),
            _('用户体验'),
            _('业务应用'),
            _('蓝鲸数据平台'),
            _('蓝鲸监控'),
            _('组件'),
            _('用户自定义'),
            _('自定义事件类型'),
            _('数据中心'),
            _('内置事件类型'),
            _('硬件设备'),
            _('主机&云平台'),
            _('主机设备'),
            _('进程'),
            'kubernetes',
            _('日志类型'),
            _('操作系统'),
            _('其他'),
            _('服务'),
            _('服务模块'),
            _('时序数据'),
            _('服务拨测'),
        ]

    def _alert_assign(self):
        # 告警分派
        return [
            _("[内置]第三方告警默认规则组"),
            _("[内置]通知人为空默认规则组"),
        ]

    def _space_type_name(self):
        # 空间名称
        return [
            _("业务"),
            _("蓝鲸业务空间"),
            _("容器项目"),
            _("容器项目空间"),
            _("研发项目"),
            _("蓝盾研发项目空间"),
            _("蓝鲸应用"),
            _("蓝鲸应用空间"),
            _("监控空间"),
            _("监控空间"),
        ]

    def _notice_way(self):
        return [
            _("群机器人"),
        ]
