# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""


from .models import (
    BinarySIPrefix,
    DecimalSIPrefix,
    SimpleCountUnit,
    to_fixed_unit,
    to_percent,
    to_percent_unit,
    TimeUnit,
)

define = [
    {
        "name": "Misc",
        "display": "",
        "formats": [
            {"name": "none", "id": "none", "fn": to_fixed_unit("")},
            {"name": "short", "id": "short", "fn": to_fixed_unit("")},
            {"name": "percent (0-100)", "id": "percent", "fn": to_percent},
            {"name": "percent (0.0-1.0)", "id": "percentunit", "fn": to_percent_unit},
            # { "name": "Humidity (%H)", "id": "humidity", "fn": to_fixed_unit("%H") },
            # { "name": "decibel", "id": "dB", "fn": to_fixed_unit("dB") },
            # { "name": "hexadecimal (0x)", "id": "hex0x", "fn": toHex0x },
            # { "name": "hexadecimal", "id": "hex", "fn": toHex },
            # { "name": "scientific notation", "id": "sci", "fn": sci },
            # { "name": "locale format", "id": "locale", "fn": locale },
            # { "name": "Pixels", "id": "pixel", "fn": to_fixed_unit("px") },
        ],
    },
    # {
    #   "name": "Acceleration",
    #   "formats": [
    #     { "name": "Meters/sec²", "id": "accMS2", "fn": to_fixed_unit("m/sec²") },
    #     { "name": "Feet/sec²", "id": "accFS2", "fn": to_fixed_unit("f/sec²") },
    #     { "name": "G unit", "id": "accG", "fn": to_fixed_unit("g") },
    #   ],
    # },
    # {
    #   "name": "Angle",
    #   "formats": [
    #     { "name": "Degrees (°)", "id": "degree", "fn": to_fixed_unit("°") },
    #     { "name": "Radians", "id": "radian", "fn": to_fixed_unit("rad") },
    #     { "name": "Gradian", "id": "grad", "fn": to_fixed_unit("grad") },
    #     { "name": "Arc Minutes", "id": "arcmin", "fn": to_fixed_unit("arcmin") },
    #     { "name": "Arc Seconds", "id": "arcsec", "fn": to_fixed_unit("arcsec") },
    #   ],
    # },
    # {
    #   "name": "Area",
    #   "formats": [
    #     { "name": "Square Meters (m²)", "id": "areaM2", "fn": to_fixed_unit("m²") },
    #     { "name": "Square Feet (ft²)", "id": "areaF2", "fn": to_fixed_unit("ft²") },
    #     { "name": "Square Miles (mi²)", "id": "areaMI2", "fn": to_fixed_unit("mi²") },
    #   ],
    # },
    # {
    #   "name": "Computation",
    #   "formats": [
    #     { "name": "FLOP/s", "id": "flops", "fn": DecimalSIPrefix("FLOP/s") },
    #     { "name": "MFLOP/s", "id": "mflops", "fn": DecimalSIPrefix("FLOP/s", 2) },
    #     { "name": "GFLOP/s", "id": "gflops", "fn": DecimalSIPrefix("FLOP/s", 3) },
    #     { "name": "TFLOP/s", "id": "tflops", "fn": DecimalSIPrefix("FLOP/s", 4) },
    #     { "name": "PFLOP/s", "id": "pflops", "fn": DecimalSIPrefix("FLOP/s", 5) },
    #     { "name": "EFLOP/s", "id": "eflops", "fn": DecimalSIPrefix("FLOP/s", 6) },
    #     { "name": "ZFLOP/s", "id": "zflops", "fn": DecimalSIPrefix("FLOP/s", 7) },
    #     { "name": "YFLOP/s", "id": "yflops", "fn": DecimalSIPrefix("FLOP/s", 8) },
    #   ],
    # },
    # {
    #   "name": "Concentration",
    #   "formats": [
    #     { "name": "parts-per-million (ppm)", "id": "ppm", "fn": to_fixed_unit("ppm") },
    #     { "name": "parts-per-billion (ppb)", "id": "conppb", "fn": to_fixed_unit("ppb") },
    #     { "name": "nanogram per cubic meter (ng/m³)", "id": "conngm3", "fn": to_fixed_unit("ng/m³") },
    #     { "name": "nanogram per normal cubic meter (ng/Nm³)", "id": "conngNm3", "fn": to_fixed_unit("ng/Nm³") },
    #     { "name": "microgram per cubic meter (μg/m³)", "id": "conμgm3", "fn": to_fixed_unit("μg/m³") },
    #     { "name": "microgram per normal cubic meter (μg/Nm³)", "id": "conμgNm3", "fn": to_fixed_unit("μg/Nm³") },
    #     { "name": "milligram per cubic meter (mg/m³)", "id": "conmgm3", "fn": to_fixed_unit("mg/m³") },
    #     { "name": "milligram per normal cubic meter (mg/Nm³)", "id": "conmgNm3", "fn": to_fixed_unit("mg/Nm³") },
    #     { "name": "gram per cubic meter (g/m³)", "id": "congm3", "fn": to_fixed_unit("g/m³") },
    #     { "name": "gram per normal cubic meter (g/Nm³)", "id": "congNm3", "fn": to_fixed_unit("g/Nm³") },
    #     { "name": "milligrams per decilitre (mg/dL)", "id": "conmgdL", "fn": to_fixed_unit("mg/dL") },
    #     { "name": "millimoles per litre (mmol/L)", "id": "conmmolL", "fn": to_fixed_unit("mmol/L") },
    #   ],
    # },
    # {
    #   "name": "Currency",
    #   "formats": [
    #     { "name": "Dollars ($)", "id": "currencyUSD", "fn": currency("$") },
    #     { "name": "Pounds (£)", "id": "currencyGBP", "fn": currency("£") },
    #     { "name": "Euro (€)", "id": "currencyEUR", "fn": currency("€") },
    #     { "name": "Yen (¥)", "id": "currencyJPY", "fn": currency("¥") },
    #     { "name": "Rubles (₽)", "id": "currencyRUB", "fn": currency("₽") },
    #     { "name": "Hryvnias (₴)", "id": "currencyUAH", "fn": currency("₴") },
    #     { "name": "Real (R$)", "id": "currencyBRL", "fn": currency("R$") },
    #     { "name": "Danish Krone (kr)", "id": "currencyDKK", "fn": currency("kr", true) },
    #     { "name": "Icelandic Króna (kr)", "id": "currencyISK", "fn": currency("kr", true) },
    #     { "name": "Norwegian Krone (kr)", "id": "currencyNOK", "fn": currency("kr", true) },
    #     { "name": "Swedish Krona (kr)", "id": "currencySEK", "fn": currency("kr", true) },
    #     { "name": "Czech koruna (czk)", "id": "currencyCZK", "fn": currency("czk") },
    #     { "name": "Swiss franc (CHF)", "id": "currencyCHF", "fn": currency("CHF") },
    #     { "name": "Polish Złoty (PLN)", "id": "currencyPLN", "fn": currency("PLN") },
    #     { "name": "Bitcoin (฿)", "id": "currencyBTC", "fn": currency("฿") },
    #     { "name": "South African Rand (R)", "id": "currencyZAR", "fn": currency("R") },
    #     { "name": "Indian Rupee (₹)", "id": "currencyINR", "fn": currency("₹") },
    #     { "name": "South Korean Won (₩)", "id": "currencyKRW", "fn": currency("₩") },
    #   ],
    # },
    {
        "name": "Data (IEC)",
        "formats": [
            {"name": "bits", "id": "bits", "fn": BinarySIPrefix("b")},
            {"name": "bytes", "id": "bytes", "fn": BinarySIPrefix("B")},
            {"name": "kibibytes", "id": "kbytes", "fn": BinarySIPrefix("B", 1)},
            {"name": "mebibytes", "id": "mbytes", "fn": BinarySIPrefix("B", 2)},
            {"name": "gibibytes", "id": "gbytes", "fn": BinarySIPrefix("B", 3)},
            {"name": "tebibytes", "id": "tbytes", "fn": BinarySIPrefix("B", 4)},
            {"name": "pebibytes", "id": "pbytes", "fn": BinarySIPrefix("B", 5)},
        ],
    },
    {
        "name": "Data (Metric)",
        "formats": [
            {"name": "bits", "id": "decbits", "fn": DecimalSIPrefix("b")},
            {"name": "bytes", "id": "decbytes", "fn": DecimalSIPrefix("B")},
            {"name": "kilobytes", "id": "deckbytes", "fn": DecimalSIPrefix("B", 1)},
            {"name": "megabytes", "id": "decmbytes", "fn": DecimalSIPrefix("B", 2)},
            {"name": "gigabytes", "id": "decgbytes", "fn": DecimalSIPrefix("B", 3)},
            {"name": "terabytes", "id": "dectbytes", "fn": DecimalSIPrefix("B", 4)},
            {"name": "petabytes", "id": "decpbytes", "fn": DecimalSIPrefix("B", 5)},
        ],
    },
    {
        "name": "Data Rate",
        "formats": [
            {"name": "packets/sec", "id": "pps", "fn": DecimalSIPrefix("pps")},
            {"name": "bits/sec", "id": "bps", "fn": DecimalSIPrefix("bps")},
            {"name": "bytes/sec", "id": "Bps", "fn": DecimalSIPrefix("Bs")},
            {"name": "kilobytes/sec", "id": "KBs", "fn": DecimalSIPrefix("Bs", 1)},
            {"name": "kilobits/sec", "id": "Kbits", "fn": DecimalSIPrefix("bps", 1)},
            {"name": "megabytes/sec", "id": "MBs", "fn": DecimalSIPrefix("Bs", 2)},
            {"name": "megabits/sec", "id": "Mbits", "fn": DecimalSIPrefix("bps", 2)},
            {"name": "gigabytes/sec", "id": "GBs", "fn": DecimalSIPrefix("Bs", 3)},
            {"name": "gigabits/sec", "id": "Gbits", "fn": DecimalSIPrefix("bps", 3)},
            {"name": "terabytes/sec", "id": "TBs", "fn": DecimalSIPrefix("Bs", 4)},
            {"name": "terabits/sec", "id": "Tbits", "fn": DecimalSIPrefix("bps", 4)},
            {"name": "petabytes/sec", "id": "PBs", "fn": DecimalSIPrefix("Bs", 5)},
            {"name": "petabits/sec", "id": "Pbits", "fn": DecimalSIPrefix("bps", 5)},
        ],
    },
    # {
    #   "name": "Date & Time",
    #   "formats": [
    #     { "name": "YYYY-MM-DD HH:mm:ss", "id": "dateTimeAsIso", "fn": dateTimeAsIso },
    #     { "name": "MM/DD/YYYY h:mm:ss a", "id": "dateTimeAsUS", "fn": dateTimeAsUS },
    #     { "name": "From Now", "id": "dateTimeFromNow", "fn": dateTimeFromNow },
    #   ],
    # },
    # {
    #   "name": "Energy",
    #   "formats": [
    #     { "name": "Watt (W)", "id": "watt", "fn": DecimalSIPrefix("W") },
    #     { "name": "Kilowatt (kW)", "id": "kwatt", "fn": DecimalSIPrefix("W", 1) },
    #     { "name": "Megawatt (MW)", "id": "megwatt", "fn": DecimalSIPrefix("W", 2) },
    #     { "name": "Gigawatt (GW)", "id": "gwatt", "fn": DecimalSIPrefix("W", 3) },
    #     { "name": "Milliwatt (mW)", "id": "mwatt", "fn": DecimalSIPrefix("W", -1) },
    #     { "name": "Watt per square meter (W/m²)", "id": "Wm2", "fn": to_fixed_unit("W/m²") },
    #     { "name": "Volt-ampere (VA)", "id": "voltamp", "fn": DecimalSIPrefix("VA") },
    #     { "name": "Kilovolt-ampere (kVA)", "id": "kvoltamp", "fn": DecimalSIPrefix("VA", 1) },
    #     { "name": "Volt-ampere reactive (var)", "id": "voltampreact", "fn": DecimalSIPrefix("var") },
    #     { "name": "Kilovolt-ampere reactive (kvar)", "id": "kvoltampreact", "fn": DecimalSIPrefix("var", 1) },
    #     { "name": "Watt-hour (Wh)", "id": "watth", "fn": DecimalSIPrefix("Wh") },
    #     { "name": "Watt-hour per Kilogram (Wh/kg)", "id": "watthperkg", "fn": DecimalSIPrefix("Wh/kg") },
    #     { "name": "Kilowatt-hour (kWh)", "id": "kwatth", "fn": DecimalSIPrefix("Wh", 1) },
    #     { "name": "Kilowatt-min (kWm)", "id": "kwattm", "fn": DecimalSIPrefix("W-Min", 1) },
    #     { "name": "Ampere-hour (Ah)", "id": "amph", "fn": DecimalSIPrefix("Ah") },
    #     { "name": "Kiloampere-hour (kAh)", "id": "kamph", "fn": DecimalSIPrefix("Ah", 1) },
    #     { "name": "Milliampere-hour (mAh)", "id": "mamph", "fn": DecimalSIPrefix("Ah", -1) },
    #     { "name": "Joule (J)", "id": "joule", "fn": DecimalSIPrefix("J") },
    #     { "name": "Electron volt (eV)", "id": "ev", "fn": DecimalSIPrefix("eV") },
    #     { "name": "Ampere (A)", "id": "amp", "fn": DecimalSIPrefix("A") },
    #     { "name": "Kiloampere (kA)", "id": "kamp", "fn": DecimalSIPrefix("A", 1) },
    #     { "name": "Milliampere (mA)", "id": "mamp", "fn": DecimalSIPrefix("A", -1) },
    #     { "name": "Volt (V)", "id": "volt", "fn": DecimalSIPrefix("V") },
    #     { "name": "Kilovolt (kV)", "id": "kvolt", "fn": DecimalSIPrefix("V", 1) },
    #     { "name": "Millivolt (mV)", "id": "mvolt", "fn": DecimalSIPrefix("V", -1) },
    #     { "name": "Decibel-milliwatt (dBm)", "id": "dBm", "fn": DecimalSIPrefix("dBm") },
    #     { "name": "Ohm (Ω)", "id": "ohm", "fn": DecimalSIPrefix("Ω") },
    #     { "name": "Kiloohm (kΩ)", "id": "kohm", "fn": DecimalSIPrefix("Ω", 1) },
    #     { "name": "Megaohm (MΩ)", "id": "Mohm", "fn": DecimalSIPrefix("Ω", 2) },
    #     { "name": "Farad (F)", "id": "farad", "fn": DecimalSIPrefix("F") },
    #     { "name": "Microfarad (µF)", "id": "µfarad", "fn": DecimalSIPrefix("F", -2) },
    #     { "name": "Nanofarad (nF)", "id": "nfarad", "fn": DecimalSIPrefix("F", -3) },
    #     { "name": "Picofarad (pF)", "id": "pfarad", "fn": DecimalSIPrefix("F", -4) },
    #     { "name": "Femtofarad (fF)", "id": "ffarad", "fn": DecimalSIPrefix("F", -5) },
    #     { "name": "Henry (H)", "id": "henry", "fn": DecimalSIPrefix("H") },
    #     { "name": "Millihenry (mH)", "id": "mhenry", "fn": DecimalSIPrefix("H", -1) },
    #     { "name": "Microhenry (µH)", "id": "µhenry", "fn": DecimalSIPrefix("H", -2) },
    #     { "name": "Lumens (Lm)", "id": "lumens", "fn": DecimalSIPrefix("Lm") },
    #   ],
    # },
    # {
    #   "name": "Flow",
    #   "formats": [
    #     { "name": "Gallons/min (gpm)", "id": "flowgpm", "fn": to_fixed_unit("gpm") },
    #     { "name": "Cubic meters/sec (cms)", "id": "flowcms", "fn": to_fixed_unit("cms") },
    #     { "name": "Cubic feet/sec (cfs)", "id": "flowcfs", "fn": to_fixed_unit("cfs") },
    #     { "name": "Cubic feet/min (cfm)", "id": "flowcfm", "fn": to_fixed_unit("cfm") },
    #     { "name": "Litre/hour", "id": "litreh", "fn": to_fixed_unit("L/h") },
    #     { "name": "Litre/min (L/min)", "id": "flowlpm", "fn": to_fixed_unit("L/min") },
    #     { "name": "milliLitre/min (mL/min)", "id": "flowmlpm", "fn": to_fixed_unit("mL/min") },
    #     { "name": "Lux (lx)", "id": "lux", "fn": to_fixed_unit("lux") },
    #   ],
    # },
    # {
    #   "name": "Force",
    #   "formats": [
    #     { "name": "Newton-meters (Nm)", "id": "forceNm", "fn": DecimalSIPrefix("Nm") },
    #     { "name": "Kilonewton-meters (kNm)", "id": "forcekNm", "fn": DecimalSIPrefix("Nm", 1) },
    #     { "name": "Newtons (N)", "id": "forceN", "fn": DecimalSIPrefix("N") },
    #     { "name": "Kilonewtons (kN)", "id": "forcekN", "fn": DecimalSIPrefix("N", 1) },
    #   ],
    # },
    # {
    #   "name": "Hash Rate",
    #   "formats": [
    #     { "name": "hashes/sec", "id": "Hs", "fn": DecimalSIPrefix("H/s") },
    #     { "name": "kilohashes/sec", "id": "KHs", "fn": DecimalSIPrefix("H/s", 1) },
    #     { "name": "megahashes/sec", "id": "MHs", "fn": DecimalSIPrefix("H/s", 2) },
    #     { "name": "gigahashes/sec", "id": "GHs", "fn": DecimalSIPrefix("H/s", 3) },
    #     { "name": "terahashes/sec", "id": "THs", "fn": DecimalSIPrefix("H/s", 4) },
    #     { "name": "petahashes/sec", "id": "PHs", "fn": DecimalSIPrefix("H/s", 5) },
    #     { "name": "exahashes/sec", "id": "EHs", "fn": DecimalSIPrefix("H/s", 6) },
    #   ],
    # },
    # {
    #   "name": "Mass",
    #   "formats": [
    #     { "name": "milligram (mg)", "id": "massmg", "fn": DecimalSIPrefix("g", -1) },
    #     { "name": "gram (g)", "id": "massg", "fn": DecimalSIPrefix("g") },
    #     { "name": "kilogram (kg)", "id": "masskg", "fn": DecimalSIPrefix("g", 1) },
    #     { "name": "metric ton (t)", "id": "masst", "fn": to_fixed_unit("t") },
    #   ],
    # },
    # {
    #   "name": "length",
    #   "formats": [
    #     { "name": "millimeter (mm)", "id": "lengthmm", "fn": DecimalSIPrefix("m", -1) },
    #     { "name": "feet (ft)", "id": "lengthft", "fn": to_fixed_unit("ft") },
    #     { "name": "meter (m)", "id": "lengthm", "fn": DecimalSIPrefix("m") },
    #     { "name": "kilometer (km)", "id": "lengthkm", "fn": DecimalSIPrefix("m", 1) },
    #     { "name": "mile (mi)", "id": "lengthmi", "fn": to_fixed_unit("mi") },
    #   ],
    # },
    # {
    #   "name": "Pressure",
    #   "formats": [
    #     {"name": "Millibars", "id": "pressurembar", "fn": DecimalSIPrefix("bar", -1)},
    #     {"name": "Bars", "id": "pressurebar", "fn": DecimalSIPrefix("bar")},
    #     {"name": "Kilobars", "id": "pressurekbar", "fn": DecimalSIPrefix("bar", 1)},
    #     {"name": "Hectopascals", "id": "pressurehpa", "fn": to_fixed_unit("hPa")},
    #     {"name": "Kilopascals", "id": "pressurekpa", "fn": to_fixed_unit("kPa")},
    #     {"name": "Inches of mercury", "id": "pressurehg", "fn": to_fixed_unit('"Hg')},
    #     {"name": "PSI", "id": "pressurepsi", "fn": scaledUnits(1000, ["psi", "ksi", "Mpsi"])},
    #   ],
    # },
    # {
    #   "name": "Radiation",
    #   "formats": [
    #     {"name": "Becquerel (Bq)", "id": "radbq", "fn": DecimalSIPrefix("Bq")},
    #     {"name": "curie (Ci)", "id": "radci", "fn": DecimalSIPrefix("Ci")},
    #     {"name": "Gray (Gy)", "id": "radgy", "fn": DecimalSIPrefix("Gy")},
    #     {"name": "rad", "id": "radrad", "fn": DecimalSIPrefix("rad")},
    #     {"name": "Sievert (Sv)", "id": "radsv", "fn": DecimalSIPrefix("Sv")},
    #     {"name": "milliSievert (mSv)", "id": "radmsv", "fn": DecimalSIPrefix("mSv", -1)},
    #     {"name": "microSievert (µSv)", "id": "radusv", "fn": DecimalSIPrefix("µSv", -2)},
    #     {"name": "rem", "id": "radrem", "fn": DecimalSIPrefix("rem")},
    #     {"name": "Exposure (C/kg)", "id": "radexpckg", "fn": DecimalSIPrefix("C/kg")},
    #     {"name": "roentgen (R)", "id": "radr", "fn": DecimalSIPrefix("R")},
    #     {"name": "Sievert/hour (Sv/h)", "id": "radsvh", "fn": DecimalSIPrefix("Sv/h")},
    #     {"name": "milliSievert/hour (mSv/h)", "id": "radmsvh", "fn": DecimalSIPrefix("Sv/h", -1)},
    #     {"name": "microSievert/hour (µSv/h)", "id": "radusvh", "fn": DecimalSIPrefix("Sv/h", -2)},
    #   ],
    # },
    {
        "name": "Temperature",
        "formats": [
            {"name": "Celsius (°C)", "id": "celsius", "fn": to_fixed_unit("°C")},
            {"name": "Fahrenheit (°F)", "id": "fahrenheit", "fn": to_fixed_unit("°F")},
            {"name": "Kelvin (K)", "id": "kelvin", "fn": to_fixed_unit("K")},
        ],
    },
    {
        "name": "Time",
        "formats": [
            {"name": "Hertz (1/s)", "id": "hertz", "fn": DecimalSIPrefix("Hz")},
            {"name": "nanoseconds (ns)", "id": "ns", "fn": TimeUnit()},
            {"name": "microseconds (µs)", "id": "µs", "fn": TimeUnit(suffix_idx=1)},
            {"name": "milliseconds (ms)", "id": "ms", "fn": TimeUnit(suffix_idx=2)},
            {"name": "seconds (s)", "id": "s", "fn": TimeUnit(suffix_idx=3)},
            {"name": "minutes (m)", "id": "m", "fn": TimeUnit(suffix_idx=4)},
            {"name": "hours (h)", "id": "h", "fn": TimeUnit(suffix_idx=5)},
            {"name": "days (d)", "id": "d", "fn": TimeUnit(suffix_idx=6)},
            # {"name": "duration (ms)", "id": "dtdurationms", "fn": toDurationInMilliseconds},
            # {"name": "duration (s)", "id": "dtdurations", "fn": toDurationInSeconds},
            # {"name": "duration (hh:mm:ss)", "id": "dthms", "fn": toDurationInHoursMinutesSeconds},
            # {"name": "Timeticks (s/100)", "id": "timeticks", "fn": toTimeTicks},
            # {"name": "clock (ms)", "id": "clockms", "fn": toClockMilliseconds},
            # {"name": "clock (s)", "id": "clocks", "fn": toClockSeconds},
        ],
    },
    {
        "name": "Throughput",
        "formats": [
            {"name": "counts/sec (cps)", "id": "cps", "fn": SimpleCountUnit("cps")},
            {"name": "ops/sec (ops)", "id": "ops", "fn": SimpleCountUnit("ops")},
            {"name": "requests/sec (rps)", "id": "reqps", "fn": SimpleCountUnit("reqps")},
            {"name": "reads/sec (rps)", "id": "rps", "fn": SimpleCountUnit("rps")},
            {"name": "writes/sec (wps)", "id": "wps", "fn": SimpleCountUnit("wps")},
            {"name": "I/O ops/sec (iops)", "id": "iops", "fn": SimpleCountUnit("iops")},
            {"name": "counts/min (cpm)", "id": "cpm", "fn": SimpleCountUnit("cpm")},
            {"name": "ops/min (opm)", "id": "opm", "fn": SimpleCountUnit("opm")},
            {"name": "reads/min (rpm)", "id": "rpm", "fn": SimpleCountUnit("rpm")},
            {"name": "writes/min (wpm)", "id": "wpm", "fn": SimpleCountUnit("wpm")},
        ],
    },
    # {
    #   "name": "Velocity",
    #   "formats": [
    #     {"name": "meters/second (m/s)", "id": "velocityms", "fn": to_fixed_unit("m/s")},
    #     {"name": "kilometers/hour (km/h)", "id": "velocitykmh", "fn": to_fixed_unit("km/h")},
    #     {"name": "miles/hour (mph)", "id": "velocitymph", "fn": to_fixed_unit("mph")},
    #     {"name": "knot (kn)", "id": "velocityknot", "fn": to_fixed_unit("kn")},
    #   ],
    # },
    # {
    #   "name": "Volume",
    #   "formats": [
    #     {"name": "millilitre (mL)", "id": "mlitre", "fn": DecimalSIPrefix("L", -1)},
    #     {"name": "litre (L)", "id": "litre", "fn": DecimalSIPrefix("L")},
    #     {"name": "cubic meter", "id": "m3", "fn": to_fixed_unit("m³")},
    #     {"name": "Normal cubic meter", "id": "Nm3", "fn": to_fixed_unit("Nm³")},
    #     {"name": "cubic decimeter", "id": "dm3", "fn": to_fixed_unit("dm³")},
    #     {"name": "gallons", "id": "gallons", "fn": to_fixed_unit("gal")},
    #   ],
    # },
]
