# Generated by Django 4.2.29 on 2026-04-14 07:57

import uuid

from django.db import migrations, models

from bk_monitor_base.metadata.config import db_collation


class Migration(migrations.Migration):
    dependencies = [
        ("old_metadata", "0004_databusconfig_bk_data_id_dataidconfig_bk_data_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelationDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建者")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="更新者")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name="唯一标识符"
                    ),
                ),
                (
                    "generation",
                    models.BigIntegerField(default=1, help_text="跟踪资源规格变更次数", verbose_name="generation"),
                ),
                ("namespace", models.CharField(blank=True, db_index=True, max_length=128, verbose_name="命名空间")),
                ("name", models.CharField(max_length=128, verbose_name="资源名称")),
                ("labels", models.JSONField(blank=True, default=dict, verbose_name="资源标签")),
                (
                    "from_resource",
                    models.CharField(help_text="关联的源资源类型名称", max_length=128, verbose_name="源资源类型"),
                ),
                (
                    "to_resource",
                    models.CharField(help_text="关联的目标资源类型名称", max_length=128, verbose_name="目标资源类型"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("static", "静态关联"), ("dynamic", "动态关联")],
                        default="static",
                        help_text="静态关联或动态关联",
                        max_length=32,
                        verbose_name="关联类别",
                    ),
                ),
                (
                    "is_directional",
                    models.BooleanField(
                        default=False, help_text="单向关系使用 from_to_to 格式命名", verbose_name="是否单向关系"
                    ),
                ),
                (
                    "is_belongs_to",
                    models.BooleanField(
                        default=False,
                        help_text="仅对双向关系有效，表示 from_resource 归属于 to_resource",
                        verbose_name="是否归属关系",
                    ),
                ),
            ],
            options={
                "verbose_name": "关联关系定义",
                "verbose_name_plural": "关联关系定义",
                "db_table": "metadata_relationdefinition",
            },
        ),
        migrations.CreateModel(
            name="ResourceDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建者")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="更新者")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name="唯一标识符"
                    ),
                ),
                (
                    "generation",
                    models.BigIntegerField(default=1, help_text="跟踪资源规格变更次数", verbose_name="generation"),
                ),
                ("namespace", models.CharField(blank=True, db_index=True, max_length=128, verbose_name="命名空间")),
                ("name", models.CharField(max_length=128, verbose_name="资源名称")),
                ("labels", models.JSONField(blank=True, default=dict, verbose_name="资源标签")),
                (
                    "fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="资源的字段定义，每个字段包含 namespace, name, required",
                        verbose_name="字段定义列表",
                    ),
                ),
            ],
            options={
                "verbose_name": "资源类型定义",
                "verbose_name_plural": "资源类型定义",
                "db_table": "metadata_resourcedefinition",
            },
        ),
        migrations.CreateModel(
            name="TimeSeriesScope",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group_id", models.IntegerField(db_index=True, verbose_name="自定义时序数据源ID")),
                ("scope_name", models.CharField(db_collation=db_collation, max_length=255, verbose_name="指标分组名")),
                ("dimension_config", models.JSONField(default=dict, verbose_name="分组下的维度配置")),
                ("auto_rules", models.JSONField(default=list, verbose_name="自动分组的匹配规则列表")),
                (
                    "create_from",
                    models.CharField(
                        choices=[("data", "数据自动创建"), ("user", "用户手动创建"), ("default", "默认分组")],
                        db_index=True,
                        default="data",
                        max_length=10,
                        verbose_name="创建来源",
                    ),
                ),
                ("last_modify_time", models.DateTimeField(auto_now=True, verbose_name="最后更新时间")),
            ],
            options={
                "db_table": "metadata_timeseriesscope",
                "verbose_name": "自定义时序数据分组记录",
                "verbose_name_plural": "自定义时序数据分组记录表",
            },
        ),
        migrations.RenameIndex(
            model_name="logsubscriptionconfig",
            new_name="metadata_lo_bk_biz__709b41_idx",
            old_fields=("bk_biz_id", "log_name"),
        ),
        migrations.AlterUniqueTogether(
            name="timeseriesmetric",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="bcsclusterinfo",
            name="operator_ns",
            field=models.CharField(
                default="bkmonitor-operator",
                help_text="bkmonitor-operator-stack Helm Chart 的安装 namespace，每个 namespace 对应一套独立部署",
                max_length=128,
                verbose_name="operator 安装 namespace",
            ),
        ),
        migrations.AddField(
            model_name="databusconfig",
            name="sink_names",
            field=models.JSONField(default=list, help_text="格式为kind:name，便于检索", verbose_name="处理配置列表"),
        ),
        migrations.AddField(
            model_name="dorisstoragebindingconfig",
            name="bkbase_result_table_name",
            field=models.CharField(default="", max_length=255, verbose_name="BKBase结果表名称"),
        ),
        migrations.AddField(
            model_name="dorisstoragebindingconfig",
            name="doris_cluster_name",
            field=models.CharField(default="", max_length=255, verbose_name="Doris集群名称"),
        ),
        migrations.AddField(
            model_name="essnapshotrestore",
            name="repository_name",
            field=models.CharField(blank=True, default="", max_length=128, null=True, verbose_name="所属仓库名称"),
        ),
        migrations.AddField(
            model_name="esstoragebindingconfig",
            name="bkbase_result_table_name",
            field=models.CharField(default="", max_length=255, verbose_name="BKBase结果表名称"),
        ),
        migrations.AddField(
            model_name="resulttable",
            name="labels",
            field=models.JSONField(blank=True, default=dict, verbose_name="扩展标签"),
        ),
        migrations.AddField(
            model_name="resulttableconfig",
            name="bkbase_table_id",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="BKBase结果表ID"),
        ),
        migrations.AddField(
            model_name="timeseriesgroup",
            name="metric_group_dimensions",
            field=models.JSONField(default=list, verbose_name="指标分组的维度key配置"),
        ),
        migrations.AddField(
            model_name="timeseriesmetric",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="创建时间"),
        ),
        migrations.AddField(
            model_name="timeseriesmetric",
            name="field_config",
            field=models.JSONField(default=dict, verbose_name="字段其他配置"),
        ),
        migrations.AddField(
            model_name="timeseriesmetric",
            name="field_scope",
            field=models.CharField(
                db_collation=db_collation, default="default", max_length=255, verbose_name="指标字段数据分组名"
            ),
        ),
        migrations.AddField(
            model_name="timeseriesmetric",
            name="scope_id",
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name="时序分组ID"),
        ),
        migrations.AddField(
            model_name="vmstoragebindingconfig",
            name="bkbase_result_table_name",
            field=models.CharField(default="", max_length=255, verbose_name="BKBase结果表名称"),
        ),
        migrations.AlterField(
            model_name="conditionalsinkconfig",
            name="data_link_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="数据链路名称"),
        ),
        migrations.AlterField(
            model_name="customrelationstatus",
            name="generation",
            field=models.BigIntegerField(default=1, help_text="跟踪资源规格变更次数", verbose_name="generation"),
        ),
        migrations.AlterField(
            model_name="customrelationstatus",
            name="labels",
            field=models.JSONField(blank=True, default=dict, verbose_name="资源标签"),
        ),
        migrations.AlterField(
            model_name="customrelationstatus",
            name="namespace",
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name="命名空间"),
        ),
        migrations.AlterField(
            model_name="databusconfig",
            name="data_link_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="数据链路名称"),
        ),
        migrations.AlterField(
            model_name="dataidconfig",
            name="data_link_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="数据链路名称"),
        ),
        migrations.AlterField(
            model_name="dorisstoragebindingconfig",
            name="data_link_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="数据链路名称"),
        ),
        migrations.AlterField(
            model_name="dorisstoragebindingconfig",
            name="table_id",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="结果表ID"),
        ),
        migrations.AlterField(
            model_name="esfieldqueryaliasoption",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除(已废弃)"),
        ),
        migrations.AlterField(
            model_name="esstoragebindingconfig",
            name="data_link_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="数据链路名称"),
        ),
        migrations.AlterField(
            model_name="esstoragebindingconfig",
            name="table_id",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="结果表ID"),
        ),
        migrations.AlterField(
            model_name="resulttableconfig",
            name="data_link_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="数据链路名称"),
        ),
        migrations.AlterField(
            model_name="resulttableconfig",
            name="table_id",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="结果表ID"),
        ),
        migrations.AlterField(
            model_name="resulttableoption",
            name="name",
            field=models.CharField(
                choices=[
                    ("cmdb_level_config", "cmdb_level_config"),
                    ("es_unique_field_list", "es_unique_field_list"),
                    ("group_info_alias", "group_info_alias"),
                    ("dimension_values", "dimension_values"),
                    ("segmented_query_enable", "分段查询开关"),
                    ("is_split_measurement", "是否为单指标单表"),
                    ("enable_field_black_list", "是否开启指标黑名单"),
                    ("binding_bcs_cluster_id", "绑定BCS集群ID"),
                ],
                max_length=128,
                verbose_name="option名称",
            ),
        ),
        migrations.AlterField(
            model_name="timeseriesmetric",
            name="field_id",
            field=models.AutoField(primary_key=True, serialize=False, verbose_name="字段ID"),
        ),
        migrations.AlterField(
            model_name="timeseriesmetric",
            name="field_name",
            field=models.CharField(db_collation=db_collation, max_length=255, verbose_name="指标字段名称"),
        ),
        migrations.AlterField(
            model_name="timeseriesmetric",
            name="group_id",
            field=models.IntegerField(db_index=True, verbose_name="自定义时序数据源ID"),
        ),
        migrations.AlterField(
            model_name="timeseriesmetric",
            name="tag_list",
            field=models.JSONField(default=[], verbose_name="Tag列表"),
        ),
        migrations.AlterField(
            model_name="vmstoragebindingconfig",
            name="data_link_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="数据链路名称"),
        ),
        migrations.AlterField(
            model_name="vmstoragebindingconfig",
            name="table_id",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="结果表ID"),
        ),
        migrations.AlterUniqueTogether(
            name="essnapshot",
            unique_together={("table_id", "target_snapshot_repository_name")},
        ),
        migrations.AlterUniqueTogether(
            name="timeseriesmetric",
            unique_together={("group_id", "field_scope", "field_name")},
        ),
        migrations.AlterUniqueTogether(
            name="timeseriesscope",
            unique_together={("group_id", "scope_name")},
        ),
        migrations.AlterUniqueTogether(
            name="resourcedefinition",
            unique_together={("namespace", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="relationdefinition",
            unique_together={("namespace", "name")},
        ),
    ]
