CUSTOM_TIME_SERIES_DETAIL = {
    "time_series_group_id": 469,
    "is_readonly": False,
    "create_time": "2025-09-29 16:58:34+0800",
    "create_user": "admin",
    "update_time": "2025-09-29 17:02:24+0800",
    "update_user": "admin",
    "is_deleted": False,
    "bk_tenant_id": "system",
    "bk_data_id": 524947,
    "bk_biz_id": 2,
    "name": "tilapia",
    "scenario": "apm",
    "table_id": "2_bkapm_metric_tilapia.__default__",
    "is_platform": False,
    "data_label": "APM",
    "protocol": "json",
    "desc": "create by system, maybe i shouldn't be here; should be hiding.",
    "auto_discover": True,
    "scenario_display": ["用户体验", "APM"],
    "access_token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "metric_json": [
        {
            "fields": [
                {
                    "scope_id": 1,
                    "scope_name": "内置指标",
                    "field_id": 1,
                    "name": "SayHello_request_bytes_count",
                    "monitor_type": "metric",
                    "unit": "",
                    "description": "",
                    "type": "metric",
                    "aggregate_method": "",
                    "dimension_list": [
                        {"id": "_group", "name": "\u5206\u7ec4"},
                        {"id": "app_name", "name": ""},
                        {"id": "container_name", "name": "\u5bb9\u5668\u540d"},
                        {"id": "env_name", "name": "\u7528\u6237\u73af\u5883"},
                        {"id": "instance", "name": "\u5b9e\u4f8b"},
                        {"id": "monitor_name", "name": "\u76d1\u63a7\u9879\u540d\u79f0"},
                        {"id": "namespace", "name": "\u7269\u7406\u73af\u5883"},
                        {"id": "result_table_id", "name": "\u903b\u8f91\u7ed3\u679c\u8868"},
                        {"id": "scope_name", "name": "\u76d1\u63a7\u5206\u7ec4"},
                        {"id": "sdk_name", "name": "SDK \u540d\u79f0"},
                        {"id": "service_name", "name": "\u670d\u52a1\u540d"},
                        {"id": "target", "name": "\u5b9e\u4f53"},
                        {"id": "version", "name": "SDK \u7248\u672c"},
                    ],
                    "label": ["\u5185\u7f6e\u6307\u6807"],
                },
                {
                    "scope_id": 2,
                    "scope_name": "测试",
                    "field_id": 2,
                    "name": "SayHello_request_count",
                    "monitor_type": "metric",
                    "unit": "",
                    "description": "",
                    "type": "metric",
                    "aggregate_method": "",
                    "dimension_list": [
                        {"id": "_group", "name": "\u5206\u7ec4"},
                        {"id": "app_name", "name": ""},
                        {"id": "container_name", "name": "\u5bb9\u5668\u540d"},
                        {"id": "env_name", "name": "\u7528\u6237\u73af\u5883"},
                        {"id": "instance", "name": "\u5b9e\u4f8b"},
                        {"id": "monitor_name", "name": "\u76d1\u63a7\u9879\u540d\u79f0"},
                        {"id": "namespace", "name": "\u7269\u7406\u73af\u5883"},
                        {"id": "result_table_id", "name": "\u903b\u8f91\u7ed3\u679c\u8868"},
                        {"id": "scope_name", "name": "\u76d1\u63a7\u5206\u7ec4"},
                        {"id": "sdk_name", "name": "SDK \u540d\u79f0"},
                        {"id": "service_name", "name": "\u670d\u52a1\u540d"},
                        {"id": "target", "name": "\u5b9e\u4f53"},
                        {"id": "version", "name": "SDK \u7248\u672c"},
                    ],
                    "label": ["\u5185\u7f6e\u6307\u6807"],
                },
                {
                    "scope_id": 3,
                    "scope_name": "",
                    "field_id": 3,
                    "name": "avg_count",
                    "monitor_type": "metric",
                    "unit": "",
                    "description": "",
                    "type": "metric",
                    "aggregate_method": "",
                    "dimension_list": [
                        {"id": "_group", "name": "分组"},
                        {"id": "app_name", "name": ""},
                        {"id": "container_name", "name": "容器名"},
                        {"id": "env_name", "name": "用户环境"},
                        {"id": "instance", "name": "实例"},
                        {"id": "monitor_name", "name": "监控项名称"},
                        {"id": "namespace", "name": "物理环境"},
                        {"id": "result_table_id", "name": "逻辑结果表"},
                        {"id": "scope_name", "name": "监控分组"},
                        {"id": "sdk_name", "name": "SDK 名称"},
                        {"id": "service_name", "name": "服务名"},
                        {"id": "target", "name": "实体"},
                        {"id": "type", "name": ""},
                        {"id": "version", "name": "SDK 版本"},
                    ],
                    "label": ["oneTwo", "test3", "test33"],
                },
                {
                    "scope_id": 1,
                    "scope_name": "内置指标",
                    "name": "target",
                    "monitor_type": "dimension",
                    "unit": "",
                    "description": "\u5b9e\u4f53",
                    "type": "dimension",
                    "aggregate_method": "",
                },
                {
                    "scope_id": 2,
                    "scope_name": "测试",
                    "name": "target",
                    "monitor_type": "dimension",
                    "unit": "",
                    "description": "\u5b9e\u4f53",
                    "type": "dimension",
                    "aggregate_method": "",
                },
                {
                    "scope_id": 3,
                    "scope_name": "",
                    "name": "target",
                    "monitor_type": "dimension",
                    "unit": "",
                    "description": "\u5b9e\u4f53",
                    "type": "dimension",
                    "aggregate_method": "",
                },
            ]
        }
    ],
    "target": [],
}

CUSTOM_TIME_SERIES_FIELDS = {
    "dimensions": [
        {
            "scope_id": 1,
            "scope_name": "内置指标",
            "name": "target",
            "type": "dimension",
            "description": "实体",
            "disabled": False,
            "hidden": False,
            "common": True,
            "create_time": 1759136325.767246,
            "update_time": 1759136325.767251,
        },
        {
            "scope_id": 2,
            "scope_name": "测试",
            "name": "target",
            "type": "dimension",
            "description": "实体",
            "disabled": False,
            "hidden": False,
            "common": True,
            "create_time": 1759136325.767246,
            "update_time": 1759136325.767251,
        },
        {
            "scope_id": 3,
            "scope_name": "",
            "name": "target",
            "type": "dimension",
            "description": "实体",
            "disabled": False,
            "hidden": False,
            "common": True,
            "create_time": 1759136325.767246,
            "update_time": 1759136325.767251,
        },
    ],
    "metrics": [
        {
            "scope_id": 1,
            "scope_name": "内置指标",
            "field_id": 1,
            "name": "SayHello_request_bytes_count",
            "type": "metric",
            "description": "",
            "disabled": False,
            "unit": "",
            "hidden": False,
            "aggregate_method": "",
            "function": {},
            "interval": 0,
            "dimensions": [
                "_group",
                "app_name",
                "container_name",
                "env_name",
                "instance",
                "monitor_name",
                "namespace",
                "result_table_id",
                "scope_name",
                "sdk_name",
                "service_name",
                "target",
                "version",
            ],
            "create_time": 1759136325.767198,
            "update_time": 1759136325.767232,
        },
        {
            "scope_id": 2,
            "scope_name": "测试",
            "field_id": 2,
            "name": "SayHello_request_count",
            "type": "metric",
            "description": "",
            "disabled": False,
            "unit": "",
            "hidden": False,
            "aggregate_method": "",
            "function": {},
            "interval": 0,
            "dimensions": [
                "_group",
                "app_name",
                "container_name",
                "env_name",
                "instance",
                "monitor_name",
                "namespace",
                "result_table_id",
                "scope_name",
                "sdk_name",
                "service_name",
                "target",
                "version",
            ],
            "create_time": 1759136325.767198,
            "update_time": 1759136325.767232,
        },
        {
            "scope_id": 3,
            "scope_name": "",
            "field_id": 3,
            "name": "avg_count",
            "type": "metric",
            "description": "",
            "disabled": False,
            "unit": "",
            "hidden": False,
            "aggregate_method": "",
            "function": {},
            "interval": 0,
            "dimensions": [
                "_group",
                "app_name",
                "container_name",
                "env_name",
                "instance",
                "monitor_name",
                "namespace",
                "result_table_id",
                "scope_name",
                "sdk_name",
                "service_name",
                "target",
                "type",
                "version",
            ],
            "create_time": 1759136325.767566,
            "update_time": 1759136325.767571,
        },
    ],
}

CUSTOM_TS_GROUPING_RULE_LIST = [
    {
        "scope_id": 1,
        "name": "内置指标",
        "manual_list": ["SayHello_request_bytes_count"],
        "auto_rules": [],
        "metric_count": 1,
        "create_from": "data",
    },
    {
        "scope_id": 2,
        "name": "测试",
        "manual_list": ["SayHello_request_count"],
        "auto_rules": [],
        "metric_count": 1,
        "create_from": "user",
    },
    {
        "scope_id": 3,
        "name": "",
        "manual_list": [],
        "auto_rules": [],
        "metric_count": 1,
        "create_from": "user",
    },
]
