# Generated by Django 4.2.28 on 2026-02-24 12:22

import django.db.models.deletion
from django.db import migrations, models

import bk_monitor_base.infras.db_models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UptimeCheckGroupModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="分组名称")),
                ("logo", models.TextField(blank=True, default="", verbose_name="图片base64形式")),
                ("bk_biz_id", models.IntegerField(default=0, verbose_name="业务ID")),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="修改人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
            ],
            options={
                "verbose_name": "拨测分组",
                "verbose_name_plural": "拨测分组",
                "db_table": "monitor_uptimecheckgroup",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UptimeCheckGroupTaskRelation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "db_table": "monitor_uptimecheckgroup_tasks",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UptimeCheckNodeModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_tenant_id", models.CharField(default="system", max_length=128, verbose_name="租户ID")),
                ("bk_biz_id", models.IntegerField(db_index=True, default=0, verbose_name="业务ID")),
                ("is_common", models.BooleanField(db_index=True, default=False, verbose_name="是否为通用节点")),
                (
                    "biz_scope",
                    bk_monitor_base.infras.db_models.fields.TextJSONField(
                        default=list, help_text="示例: [1, 2, 3]", verbose_name="指定业务可见范围"
                    ),
                ),
                (
                    "ip_type",
                    models.IntegerField(
                        choices=[(0, "all"), (4, "IPv4"), (6, "IPv6")], default=4, verbose_name="IP类型"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="节点名称")),
                ("ip", models.CharField(blank=True, default="", max_length=64, null=True, verbose_name="IP地址")),
                ("bk_host_id", models.IntegerField(blank=True, null=True, verbose_name="主机ID")),
                ("plat_id", models.IntegerField(blank=True, default=0, null=True, verbose_name="云区域ID")),
                (
                    "location",
                    bk_monitor_base.infras.db_models.fields.TextJSONField(
                        default=dict, help_text='示例: {"country": "中国", "city": "北京"}', verbose_name="地区"
                    ),
                ),
                (
                    "carrieroperator",
                    models.CharField(blank=True, default="", max_length=50, null=True, verbose_name="外网运营商"),
                ),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="修改人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
            ],
            options={
                "verbose_name": "拨测节点",
                "verbose_name_plural": "拨测节点",
                "db_table": "monitor_uptimechecknode",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UptimeCheckTaskCollectorLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_id", models.IntegerField(verbose_name="拨测任务ID")),
                ("error_log", models.JSONField(default=dict, verbose_name="错误日志")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="已删除")),
                ("subscription_id", models.IntegerField(default=0, verbose_name="节点管理订阅ID")),
                ("nodeman_task_id", models.IntegerField(default=0, verbose_name="节点管理任务ID")),
            ],
            options={
                "db_table": "monitor_uptimechecktaskcollectorlog",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UptimeCheckTaskModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务ID")),
                ("name", models.CharField(db_index=True, max_length=128, verbose_name="任务名称")),
                (
                    "protocol",
                    models.CharField(
                        choices=[("TCP", "TCP"), ("UDP", "UDP"), ("HTTP", "HTTP(S)"), ("ICMP", "ICMP")],
                        max_length=10,
                        verbose_name="协议",
                    ),
                ),
                ("labels", models.JSONField(blank=True, default=dict, null=True, verbose_name="自定义标签")),
                ("indepentent_dataid", models.BooleanField(default=False, verbose_name="独立业务数据ID")),
                ("check_interval", models.PositiveIntegerField(default=5, verbose_name="拨测周期(分钟)")),
                ("location", models.JSONField(default=dict, verbose_name="地区")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new_draft", "未保存"),
                            ("running", "运行中"),
                            ("stoped", "未启用"),
                            ("starting", "启动中"),
                            ("stoping", "停止中"),
                            ("start_failed", "启动失败"),
                            ("stop_failed", "停止失败"),
                        ],
                        default="new_draft",
                        max_length=20,
                        verbose_name="当前状态",
                    ),
                ),
                (
                    "config",
                    bk_monitor_base.infras.db_models.fields.SymmetricJSONField(
                        blank=True, null=True, using="default", verbose_name="拨测配置"
                    ),
                ),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="修改人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
            ],
            options={
                "verbose_name": "拨测任务",
                "verbose_name_plural": "拨测任务",
                "db_table": "monitor_uptimechecktask",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UptimeCheckTaskSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uptimecheck_id", models.IntegerField(default=0, verbose_name="拨测任务id")),
                ("subscription_id", models.IntegerField(default=0, verbose_name="节点管理订阅ID")),
                ("bk_biz_id", models.IntegerField(default=0, verbose_name="业务ID")),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="修改人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
            ],
            options={
                "db_table": "monitor_uptimechecktasksubscription",
                "managed": True,
                "unique_together": {("uptimecheck_id", "bk_biz_id")},
            },
        ),
        migrations.CreateModel(
            name="UptimeCheckTaskNodeRelation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "node",
                    models.ForeignKey(
                        db_column="uptimechecknode_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uptime_check.uptimechecknodemodel",
                        verbose_name="拨测节点",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        db_column="uptimechecktask_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uptime_check.uptimechecktaskmodel",
                        verbose_name="拨测任务",
                    ),
                ),
            ],
            options={
                "db_table": "monitor_uptimechecktask_nodes",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="uptimechecktaskmodel",
            name="nodes",
            field=models.ManyToManyField(
                related_name="tasks",
                through="uptime_check.UptimeCheckTaskNodeRelation",
                to="uptime_check.uptimechecknodemodel",
                verbose_name="拨测节点",
            ),
        ),
        migrations.AddIndex(
            model_name="uptimechecknodemodel",
            index=models.Index(fields=["name", "bk_biz_id"], name="monitor_upt_name_aca5c8_idx"),
        ),
        migrations.AddField(
            model_name="uptimecheckgrouptaskrelation",
            name="group",
            field=models.ForeignKey(
                db_column="uptimecheckgroup_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="uptime_check.uptimecheckgroupmodel",
                verbose_name="拨测分组",
            ),
        ),
        migrations.AddField(
            model_name="uptimecheckgrouptaskrelation",
            name="task",
            field=models.ForeignKey(
                db_column="uptimechecktask_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="uptime_check.uptimechecktaskmodel",
                verbose_name="拨测任务",
            ),
        ),
        migrations.AddField(
            model_name="uptimecheckgroupmodel",
            name="tasks",
            field=models.ManyToManyField(
                related_name="groups",
                through="uptime_check.UptimeCheckGroupTaskRelation",
                to="uptime_check.uptimechecktaskmodel",
                verbose_name="拨测任务",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="uptimechecktasknoderelation",
            unique_together={("task", "node")},
        ),
        migrations.AlterUniqueTogether(
            name="uptimecheckgrouptaskrelation",
            unique_together={("group", "task")},
        ),
    ]
