# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2020-05-06 07:42


import django.db.models.deletion
from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("monitor_web", "0034_auto_20200416_1322"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomTSItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metric_name", models.CharField(max_length=128, verbose_name="指标名称")),
                ("unit", models.CharField(default="", max_length=16, verbose_name="字段单位")),
                ("metric_display_name", models.CharField(default="", max_length=128, verbose_name="指标别名")),
                ("dimension_list", bkmonitor.utils.db.fields.JsonField(default=[], verbose_name="维度")),
            ],
        ),
        migrations.CreateModel(
            name="CustomTSTable",
            fields=[
                ("time_series_group_id", models.IntegerField(primary_key=True, serialize=False, verbose_name="时序分组ID")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("create_user", models.CharField(blank=True, max_length=32, verbose_name="创建人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("update_user", models.CharField(blank=True, max_length=32, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("bk_data_id", models.IntegerField(verbose_name="数据ID")),
                ("bk_biz_id", models.IntegerField(db_index=True, default=0, verbose_name="业务ID")),
                ("name", models.CharField(max_length=128, verbose_name="名称")),
                ("scenario", models.CharField(db_index=True, max_length=128, verbose_name="监控场景")),
                ("table_id", models.CharField(default="", max_length=128, verbose_name="结果表ID")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="customtsitem",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metric_list",
                to="monitor_web.CustomTSTable",
                verbose_name="自定义时序ID",
            ),
        ),
    ]
