# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2020-06-05 08:32


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor_web", "0035_uptimechecktaskcollectorlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="PluginFunction",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "function_id",
                    models.CharField(
                        choices=["basereport", "exceptionbeat", "processbeat", "bkmonitorbeat"],
                        max_length=32,
                        verbose_name="功能ID",
                    ),
                ),
                ("is_enable", models.BooleanField(default=False, verbose_name="是否启用")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务ID")),
                ("subscription_id", models.IntegerField(blank=True, null=True, verbose_name="订阅ID")),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="pluginfunction",
            unique_together={("function_id", "bk_biz_id")},
        ),
    ]
