# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2020-12-16 11:34


from django.db import migrations, models


def migrate_order_to_metric_group(apps, schema_editor):
    CustomTSTable = apps.get_model("monitor_web", "CustomTSTable")
    CustomTSItem = apps.get_model("monitor_web", "CustomTSItem")
    ApplicationConfig = apps.get_model("monitor", "ApplicationConfig")

    ApplicationConfig.objects.filter()

    tables = CustomTSTable.objects.all()
    for table in tables:
        order_config_key = f"panel_order_custom_report_{table.time_series_group_id}"
        try:
            order = ApplicationConfig.objects.get(key=order_config_key).value
        except ApplicationConfig.DoesNotExist:
            continue
        except ApplicationConfig.MultipleObjectsReturned:
            first = ApplicationConfig.objects.get(key=order_config_key).first()
            ApplicationConfig.objects.filter(key=order_config_key).exclude(id=first.id).delete()
            order = first.value

        metric_labels = {}
        for row in order:
            label = row["title"]

            if row["id"] == "__UNGROUP__":
                label = ""

            for panel in row["panels"]:
                metric_labels[".".join(panel["id"].split(".")[2:])] = [label, panel.get("hidden", False)]
        CustomTSItem.objects.filter(table=table).delete()
        CustomTSItem.objects.bulk_create(
            [
                CustomTSItem(table=table, metric_name=name, label=label[0], hidden=label[1])
                for name, label in metric_labels.items()
            ],
            batch_size=200,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("monitor_web", "0042_auto_20201120_1649"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtsitem",
            name="label",
            field=models.CharField(default="", max_length=32, verbose_name="分组标签", blank=True),
        ),
        migrations.AddField(
            model_name="customtsitem",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="隐藏图表"),
        ),
        migrations.RunPython(migrate_order_to_metric_group),
    ]
