# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2021-03-31 09:49


import json
import logging
from collections import defaultdict

from django.db import migrations
from rest_framework.exceptions import ValidationError

from bkmonitor.strategy.serializers import (
    BkMonitorTimeSeriesSerializer,
    BkMonitorLogSerializer,
    BkMonitorEventSerializer,
    BkLogSearchTimeSeriesSerializer,
    BkLogSearchLogSerializer,
    CustomTimeSeriesSerializer,
    CustomEventSerializer,
    BkDataTimeSeriesSerializer,
)
from constants.data_source import DataTypeLabel, DataSourceLabel
from constants.strategy import SYSTEM_EVENT_RT_TABLE_ID

logger = logging.getLogger(__name__)


def collect_config_migrate(apps, schema_editor):
    """
    采集配置数据模型迁移
    """
    DeploymentConfigVersion = apps.get_model("monitor_web", "DeploymentConfigVersion")
    old_config_versions = DeploymentConfigVersion.objects.filter(is_deleted=False)
    for config_version in old_config_versions:
        config_version.save()


class Migration(migrations.Migration):

    dependencies = [
        ("monitor_web", "0048_auto_20210423_1503"),
    ]

    operations = [
        migrations.RunPython(code=collect_config_migrate),
    ]
