# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-09-16 01:29
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import F


def add_custom_data_label(apps, schema_editor):
    """
    补全自定义上报data_label
    """
    CustomEventGroup = apps.get_model("monitor_web", "CustomEventGroup")
    CustomTSTable = apps.get_model("monitor_web", "CustomTSTable")
    CustomEventGroup.objects.filter(name__regex=r"^[a-zA-Z][a-zA-Z0-9_]*$").update(data_label=F("name"))
    CustomEventGroup.objects.exclude(name__regex=r"^[a-zA-Z][a-zA-Z0-9_]*$").update(data_label=F("bk_data_id"))
    CustomTSTable.objects.filter(name__regex=r"^[a-zA-Z][a-zA-Z0-9_]*$").update(data_label=F("name"))
    CustomTSTable.objects.exclude(name__regex=r"^[a-zA-Z][a-zA-Z0-9_]*$").update(data_label=F("bk_data_id"))


class Migration(migrations.Migration):
    dependencies = [
        ("monitor_web", "0053_merge_20210914_1447"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeventgroup",
            name="data_label",
            field=models.CharField(default="", max_length=128, verbose_name="数据标签"),
        ),
        migrations.AddField(
            model_name="customeventgroup",
            name="is_platform",
            field=models.BooleanField(default=False, verbose_name="平台级"),
        ),
        migrations.AddField(
            model_name="customtstable",
            name="data_label",
            field=models.CharField(default="", max_length=128, verbose_name="数据标签"),
        ),
        migrations.AddField(
            model_name="customtstable",
            name="is_platform",
            field=models.BooleanField(default=False, verbose_name="平台级"),
        ),
        migrations.RunPython(add_custom_data_label),
    ]
