# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-11-10 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitor_web", "0054_auto_20210928_1124"),
        ("monitor_web", "0054_auto_20210916_0929"),
    ]

    operations = []
