# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-03-18 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor_web", "0055_merge_20211110_1534"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sceneviewmodel",
            name="scene_id",
            field=models.CharField(max_length=128, verbose_name="场景ID"),
        ),
    ]
