# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-05-17 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_web', '0057_auto_20220415_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtstable',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='说明'),
        ),
        migrations.AddField(
            model_name='customtstable',
            name='protocol',
            field=models.CharField(default='json', max_length=128, verbose_name='上报协议'),
        ),
    ]
