# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-07-21 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor_web", "0058_auto_20220517_1616"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccessRecord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=64, verbose_name="用户名")),
                ("source", models.CharField(max_length=64, verbose_name="最近一次访问来源")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="useraccessrecord",
            unique_together={("username", "source")},
        ),
    ]
