# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-07-22 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor_web", "0058_auto_20220517_1616"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customtstable",
            name="protocol",
            field=models.CharField(
                choices=[("json", "Json"), ("prometheus", "Prometheus")],
                default="json",
                max_length=128,
                verbose_name="上报协议",
            ),
        ),
    ]
