# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-07-25 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitor_web", "0059_auto_20220722_1436"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PluginFunction",
        ),
    ]
