# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-07-26 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitor_web", "0060_delete_pluginfunction"),
        ("monitor_web", "0059_auto_20220721_2046"),
    ]

    operations = []
