# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-09-21 12:33
from __future__ import unicode_literals

from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_web', '0061_merge_20220726_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTSGroupingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='分组名称')),
                ('time_series_group_id', models.IntegerField(verbose_name='时序分组ID')),
                ('manual_list', bkmonitor.utils.db.fields.JsonField(default=[], verbose_name='手动分组的指标列表')),
                ('auto_rules', bkmonitor.utils.db.fields.JsonField(default=[], verbose_name='自动分组的匹配规则列表')),
            ],
        ),
    ]
