# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-09-30 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor_web", "0061_merge_20220726_2245"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sceneviewmodel",
            name="type",
            field=models.CharField(
                blank=True, choices=[("overview', '概览"), ("detail', '详情")], max_length=16, verbose_name="视图类型"
            ),
        ),
        migrations.AlterField(
            model_name="sceneviewordermodel",
            name="type",
            field=models.CharField(
                blank=True, choices=[("overview", "概览"), ("detail", "详情")], max_length=16, verbose_name="类型"
            ),
        ),
    ]
