# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-10-09 07:33
from __future__ import unicode_literals

from django.db import migrations

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_web', '0063_update_custom_ts_item_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RolePermission',
        ),
        migrations.AlterField(
            model_name='customtsitem',
            name='label',
            field=bkmonitor.utils.db.fields.JsonField(default=[], verbose_name='分组标签'),
        ),
    ]
