# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-10-25 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_web', '0064_auto_20221009_1533'),
        ('monitor_web', '0062_auto_20220930_1926'),
    ]

    operations = []
