# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-11-11 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_web', '0065_merge_20221025_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user', models.CharField(blank=True, max_length=32, verbose_name='创建人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('update_user', models.CharField(blank=True, max_length=32, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('bk_biz_id', models.IntegerField(db_index=True, verbose_name='业务ID')),
                ('type', models.CharField(default='time_series', max_length=32, verbose_name='类型')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('order', models.JSONField(default=list, verbose_name='排序配置')),
            ],
            options={
                'verbose_name': '数据检索收藏组',
                'verbose_name_plural': '数据检索收藏组',
            },
        ),
        migrations.AlterModelOptions(
            name='queryhistory',
            options={'verbose_name': '数据检索收藏记录', 'verbose_name_plural': '数据检索收藏记录'},
        ),
        migrations.AddField(
            model_name='queryhistory',
            name='group_id',
            field=models.IntegerField(default=None, null=True, verbose_name='分组ID'),
        ),
        migrations.AddField(
            model_name='queryhistory',
            name='public',
            field=models.BooleanField(default=True, verbose_name='是否公开'),
        ),
        migrations.AlterField(
            model_name='queryhistory',
            name='name',
            field=models.CharField(max_length=64, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='sceneviewmodel',
            name='type',
            field=models.CharField(
                blank=True, choices=[('overview', '概览'), ('detail', '详情')], max_length=16, verbose_name='视图类型'
            ),
        ),
    ]
