# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-01 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_web', '0066_auto_20221111_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetricListCache',
        ),
        migrations.AddField(
            model_name='useraccessrecord',
            name='bk_biz_id',
            field=models.CharField(default='-1', max_length=32, verbose_name='业务ID'),
        ),
        migrations.AlterField(
            model_name='favoritegroup',
            name='type',
            field=models.CharField(default='metric', max_length=32, verbose_name='类型'),
        ),
        migrations.AlterUniqueTogether(
            name='useraccessrecord',
            unique_together={('username', 'source', 'bk_biz_id')},
        ),
    ]
