# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-06-16 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_web', '0067_auto_20230301_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorplugininfo',
            name='enable_field_blacklist',
            field=models.BooleanField(default=False, verbose_name='是否开启黑名单'),
        ),
    ]
