# Generated by Django 3.2.15 on 2023-12-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_web', '0068_collectorplugininfo_enable_field_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectconfigmeta',
            name='bk_biz_id',
            field=models.IntegerField(db_index=True, verbose_name='业务ID'),
        ),
    ]
