# Generated by Django 3.2.25 on 2025-02-18 16:02

from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('monitor_web', '0069_alter_collectconfigmeta_bk_biz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtsitem',
            name='aggregate_method',
            field=models.CharField(default='', max_length=128, verbose_name='默认聚合方法'),
        ),
        migrations.AddField(
            model_name='customtsitem',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='禁用指标'),
        ),
        migrations.AddField(
            model_name='customtsitem',
            name='function',
            field=models.JSONField(default=dict, verbose_name='指标函数'),
        ),
        migrations.AddField(
            model_name='customtsitem',
            name='interval',
            field=models.IntegerField(default=0, verbose_name='指标周期'),
        ),
        migrations.AddField(
            model_name='customtstable',
            name='auto_discover',
            field=models.BooleanField(default=True, verbose_name='自动发现'),
        ),
        migrations.AlterField(
            model_name='collectconfigmeta',
            name='collect_type',
            field=models.CharField(
                choices=[
                    ('Exporter', 'Exporter'),
                    ('Script', 'Script'),
                    ('JMX', 'JMX'),
                    ('DataDog', 'DataDog'),
                    ('Pushgateway', 'BK-Pull'),
                    ('Built-In', 'BK-Monitor'),
                    ('Log', 'Log'),
                    ('Process', 'Process'),
                    ('SNMP_Trap', 'SNMP_Trap'),
                    ('SNMP', 'SNMP'),
                    ('K8S', 'K8S'),
                ],
                db_index=True,
                max_length=32,
                verbose_name='采集方式',
            ),
        ),
        migrations.AlterField(
            model_name='collectconfigmeta',
            name='target_object_type',
            field=models.CharField(
                choices=[('SERVICE', '服务'), ('HOST', '主机'), ('CLUSTER', '集群')], max_length=32, verbose_name='采集对象类型'
            ),
        ),
        migrations.AlterField(
            model_name='collectorpluginmeta',
            name='plugin_type',
            field=models.CharField(
                choices=[
                    ('Exporter', 'Exporter'),
                    ('Script', 'Script'),
                    ('JMX', 'JMX'),
                    ('DataDog', 'DataDog'),
                    ('Pushgateway', 'BK-Pull'),
                    ('Built-In', 'BK-Monitor'),
                    ('Log', 'Log'),
                    ('Process', 'Process'),
                    ('SNMP_Trap', 'SNMP_Trap'),
                    ('SNMP', 'SNMP'),
                    ('K8S', 'K8S'),
                ],
                db_index=True,
                max_length=32,
                verbose_name='插件类型',
            ),
        ),
        migrations.AlterField(
            model_name='customtsitem',
            name='dimension_list',
            field=bkmonitor.utils.db.fields.JsonField(default=list, verbose_name='维度'),
        ),
        migrations.AlterField(
            model_name='customtsitem',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='隐藏指标'),
        ),
        migrations.AlterField(
            model_name='customtsitem',
            name='label',
            field=bkmonitor.utils.db.fields.JsonField(default=list, verbose_name='分组标签'),
        ),
        migrations.AlterField(
            model_name='deploymentconfigversion',
            name='target_node_type',
            field=models.CharField(
                choices=[
                    ('TOPO', '拓扑'),
                    ('INSTANCE', '实例'),
                    ('SERVICE_TEMPLATE', '服务模板'),
                    ('SET_TEMPLATE', '集群模板'),
                    ('CLUSTER', '集群'),
                    ('DYNAMIC_GROUP', '动态分组'),
                ],
                max_length=32,
                verbose_name='采集目标类型',
            ),
        ),
    ]
