# Generated by Django 3.2.25 on 2025-02-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor_web', '0070_auto_20250219_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTSField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_series_group_id', models.IntegerField(verbose_name='时序分组ID')),
                (
                    'type',
                    models.CharField(
                        choices=[('metric', '指标'), ('dimension', '维度')],
                        default='metric',
                        max_length=16,
                        verbose_name='字段类型',
                    ),
                ),
                ('name', models.CharField(max_length=128, verbose_name='字段名称')),
                ('description', models.CharField(default='', max_length=128, verbose_name='字段描述')),
                ('disabled', models.BooleanField(default=False, verbose_name='禁用字段')),
                ('config', models.JSONField(default=dict, verbose_name='字段配置')),
            ],
        ),
    ]
