# Generated by Django 3.2.25 on 2025-03-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor_web', '0071_auto_20250224_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtsitem',
            name='metric_name',
            field=models.CharField(db_column='metric_name', max_length=128, verbose_name='字段名称'),
        ),
        migrations.RenameField(
            model_name='customtsitem',
            old_name='metric_name',
            new_name='field_name',
        ),
        migrations.AddField(
            model_name='customtsgroupingrule',
            name='index',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
