# Generated by Django 3.2.25 on 2025-03-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor_web', '0072_auto_20250304_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeventgroup',
            name='bk_tenant_id',
            field=models.CharField(db_index=True, default='system', max_length=128, verbose_name='租户ID'),
        ),
    ]
