# Generated by Django 3.2.25 on 2025-03-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor_web', '0072_auto_20250304_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtsfield',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='customtsfield',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
    ]
