# Generated by Django 3.2.25 on 2025-03-28 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('monitor_web', '0073_auto_20250313_1058'),
        ('monitor_web', '0073_customeventgroup_bk_tenant_id'),
    ]

    operations = []
