# Generated by Django 3.2.25 on 2025-04-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor_web', '0074_merge_20250328_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtstable',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=128, verbose_name='租户ID'),
        ),
    ]
