# Generated by Django 3.2.25 on 2025-04-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor_web', '0075_customtstable_bk_tenant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectconfigmeta',
            old_name='plugin',
            new_name='plugin_id',
        ),
        migrations.RenameField(
            model_name='pluginversionhistory',
            old_name='plugin',
            new_name='plugin_id',
        ),
        migrations.AddField(
            model_name='collectorpluginmeta',
            name='id',
            field=models.BigIntegerField(null=True, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='collectconfigmeta',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=128, verbose_name='租户ID'),
        ),
        migrations.AddField(
            model_name='collectorpluginmeta',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=128, verbose_name='租户ID'),
        ),
        migrations.AddField(
            model_name='pluginversionhistory',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=128, verbose_name='租户ID'),
        ),
        migrations.AlterUniqueTogether(
            name='collectorpluginmeta',
            unique_together={('bk_tenant_id', 'plugin_id')},
        ),
        migrations.AlterUniqueTogether(
            name='pluginversionhistory',
            unique_together={('bk_tenant_id', 'plugin_id', 'config_version', 'info_version')},
        ),
        migrations.AlterField(
            model_name='collectconfigmeta',
            name='plugin_id',
            field=models.CharField(max_length=64, verbose_name='插件ID'),
        ),
        migrations.AlterField(
            model_name='pluginversionhistory',
            name='plugin_id',
            field=models.CharField(max_length=64, verbose_name='插件ID'),
        ),
    ]
