# Generated by Django 3.2.25 on 2025-04-08 07:28

from django.db import migrations, models


def migrate_plugin_id_to_id(apps, schema_editor):
    CollectorPluginMeta = apps.get_model("monitor_web", "CollectorPluginMeta")

    plugins = CollectorPluginMeta.objects.all()

    for index, plugin in enumerate(CollectorPluginMeta.objects.all()):
        plugin.id = index + 1

    CollectorPluginMeta.objects.bulk_update(plugins, ["id"])


class Migration(migrations.Migration):
    dependencies = [
        ('monitor_web', '0076_auto_20250408_1522'),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_plugin_id_to_id,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='collectorpluginmeta',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='collectorpluginmeta',
            name='plugin_id',
            field=models.CharField(max_length=64, verbose_name='插件ID'),
        ),
    ]
