# Generated by Django 4.2.27 on 2026-08-20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor_web", "0077_collectorpluginmeta_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeManIntegrationBinding",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("COLLECT_CONFIG", "采集配置"),
                            ("APM_PLATFORM_CONFIG", "APM 平台配置"),
                            ("APM_APPLICATION_CONFIG", "APM 应用配置"),
                            ("APM_LOG_TRACE_CONFIG", "APM 行日志配置"),
                            ("CUSTOM_REPORT", "自定义上报"),
                            ("PING_SERVER", "拨测服务"),
                            ("PROXY_PLUGIN_DEPLOYMENT", "Proxy 插件部署"),
                            ("OFFICIAL_PLUGIN_DEPLOYMENT", "官方插件部署"),
                            ("MONITOR_PLUGIN", "监控插件"),
                        ],
                        max_length=64,
                        verbose_name="资源类型",
                    ),
                ),
                ("resource_key", models.CharField(max_length=255, verbose_name="资源标识")),
                ("owner_bk_tenant_id", models.CharField(max_length=128, verbose_name="资源所属租户")),
                ("execution_bk_tenant_id", models.CharField(max_length=128, verbose_name="执行租户")),
                ("bk_biz_id", models.BigIntegerField(default=0, verbose_name="业务 ID")),
                (
                    "backend_type",
                    models.CharField(
                        choices=[("NODEMAN_V3", "NodeMan V3")],
                        default="NODEMAN_V3",
                        max_length=32,
                        verbose_name="执行后端",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("ACTIVE", "生效"), ("DELETING", "删除中"), ("ORPHANED", "待清理孤儿")],
                        default="ACTIVE",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("generation", models.PositiveBigIntegerField(default=1, verbose_name="期望代次")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "indexes": [models.Index(fields=["state", "updated_at"], name="idx_nodeman_binding_state")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "resource_type",
                            "owner_bk_tenant_id",
                            "execution_bk_tenant_id",
                            "bk_biz_id",
                            "resource_key",
                        ),
                        name="uniq_nodeman_binding_identity",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MonitorNodeManOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("config_meta_id", models.BigIntegerField(blank=True, null=True, verbose_name="采集配置 ID")),
                (
                    "deployment_config_version_id",
                    models.BigIntegerField(blank=True, null=True, verbose_name="采集部署版本 ID"),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("install", "安装"),
                            ("upgrade", "升级"),
                            ("apply", "应用配置"),
                            ("start", "启动"),
                            ("stop", "停止"),
                            ("restart", "重启"),
                            ("uninstall", "卸载"),
                            ("retry", "重试"),
                            ("terminate", "终止"),
                            ("reconcile", "收敛"),
                            ("package_import", "导入插件包"),
                            ("plugin_debug", "插件调试"),
                            ("plugin_export", "插件导出"),
                            ("plugin_retire", "插件退役"),
                        ],
                        max_length=32,
                        verbose_name="操作类型",
                    ),
                ),
                ("generation", models.PositiveBigIntegerField(verbose_name="操作代次")),
                ("request_summary", models.JSONField(default=dict, verbose_name="请求摘要")),
                ("target_count", models.PositiveIntegerField(default=0, verbose_name="目标数量")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("dispatching", "下发中"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("partial_failed", "部分失败"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                            ("unknown", "结果未知"),
                        ],
                        default="dispatching",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="结束时间")),
                ("error_summary", models.TextField(blank=True, default="", verbose_name="错误摘要")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "binding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations",
                        to="monitor_web.nodemanintegrationbinding",
                    ),
                ),
                (
                    "parent_operation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_operations",
                        to="monitor_web.monitornodemanoperation",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["binding", "generation"], name="idx_nodeman_operation_binding"),
                    models.Index(fields=["status", "updated_at"], name="idx_nodeman_operation_status"),
                ]
            },
        ),
        migrations.CreateModel(
            name="MonitorNodeManWorkflow",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "workflow_id",
                    models.CharField(blank=True, max_length=128, null=True, verbose_name="NodeMan Workflow ID"),
                ),
                ("batch_index", models.PositiveIntegerField(verbose_name="批次序号")),
                ("target_summary", models.JSONField(default=dict, verbose_name="目标摘要")),
                ("target_count", models.PositiveIntegerField(default=0, verbose_name="目标数量")),
                (
                    "dispatch_status",
                    models.CharField(
                        choices=[
                            ("prepared", "待提交"),
                            ("submitting", "提交中"),
                            ("submitted", "已提交"),
                            ("definite_failed", "明确提交失败"),
                            ("unknown", "提交结果未知"),
                        ],
                        default="prepared",
                        max_length=32,
                        verbose_name="分发状态",
                    ),
                ),
                ("dispatch_error", models.TextField(blank=True, default="", verbose_name="分发错误")),
                (
                    "raw_status",
                    models.CharField(blank=True, default="", max_length=64, verbose_name="NodeMan 原始状态"),
                ),
                (
                    "normalized_status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("partial_failed", "部分失败"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                            ("unknown", "结果未知"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="归一状态",
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True, verbose_name="最近同步时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "monitor_operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="monitor_web.monitornodemanoperation",
                    ),
                ),
            ],
            options={
                "ordering": ("batch_index",),
                "indexes": [
                    models.Index(fields=["normalized_status", "updated_at"], name="idx_nodeman_workflow_status")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("monitor_operation", "workflow_id"),
                        name="uniq_nodeman_workflow_operation_id",
                    ),
                    models.UniqueConstraint(
                        fields=("monitor_operation", "batch_index"),
                        name="uniq_nodeman_workflow_batch",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NodeManExecutionLease",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("execution_bk_tenant_id", models.CharField(max_length=128, verbose_name="执行租户")),
                ("bk_host_id", models.BigIntegerField(verbose_name="执行主机 ID")),
                ("plugin_name", models.CharField(max_length=128, verbose_name="插件名")),
                ("lease_generation", models.PositiveBigIntegerField(default=0, verbose_name="租约代次")),
                ("acquired_at", models.DateTimeField(blank=True, null=True, verbose_name="获取时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "holder_operation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_leases",
                        to="monitor_web.monitornodemanoperation",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["holder_operation", "updated_at"], name="idx_nodeman_lease_holder")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("execution_bk_tenant_id", "bk_host_id", "plugin_name"),
                        name="uniq_nodeman_execution_lease_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CollectDeploymentTarget",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("config_meta_id", models.BigIntegerField(verbose_name="采集配置 ID")),
                ("generation", models.PositiveBigIntegerField(verbose_name="期望代次")),
                ("identity_key", models.CharField(max_length=255, verbose_name="目标稳定标识")),
                ("observed_target", models.JSONField(default=dict, verbose_name="被观测对象")),
                ("service_instance_id", models.BigIntegerField(blank=True, null=True, verbose_name="服务实例 ID")),
                ("execution_bk_host_id", models.BigIntegerField(verbose_name="执行主机 ID")),
                ("remote_target", models.JSONField(default=dict, verbose_name="远程采集映射")),
                ("plugin_name", models.CharField(max_length=128, verbose_name="Exporter 插件名")),
                (
                    "node_man_plugin_instance_id",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="NodeMan 插件实例标识"),
                ),
                (
                    "bkmonitorbeat_config_instance_id",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="bkmonitorbeat 配置实例标识"),
                ),
                ("desired_present", models.BooleanField(default=True, verbose_name="期望存在")),
                ("desired_enabled", models.BooleanField(default=True, verbose_name="期望启用")),
                ("desired_revision", models.CharField(blank=True, default="", max_length=128, verbose_name="期望版本")),
                (
                    "desired_fingerprint",
                    models.CharField(blank=True, default="", max_length=64, verbose_name="期望快照指纹"),
                ),
                ("applied_present", models.BooleanField(blank=True, null=True, verbose_name="最近应用存在状态")),
                ("applied_enabled", models.BooleanField(blank=True, null=True, verbose_name="最近应用启用状态")),
                (
                    "applied_revision",
                    models.CharField(blank=True, default="", max_length=128, verbose_name="最近应用版本"),
                ),
                (
                    "applied_fingerprint",
                    models.CharField(blank=True, default="", max_length=64, verbose_name="最近应用快照指纹"),
                ),
                ("error_summary", models.TextField(blank=True, default="", verbose_name="错误摘要")),
                ("last_applied_at", models.DateTimeField(blank=True, null=True, verbose_name="最近应用时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collect_targets",
                        to="monitor_web.nodemanintegrationbinding",
                    ),
                ),
                (
                    "last_operation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collect_targets",
                        to="monitor_web.monitornodemanoperation",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["binding", "generation"], name="idx_collect_target_generation")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("binding", "identity_key"),
                        name="uniq_collect_target_identity",
                    )
                ],
            },
        ),
    ]
