# Generated by Django 4.2.27 on 2026-05-27 02:35

import bkmonitor.utils.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monitor_web", "0077_collectorpluginmeta_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UptimeCheckGroup",
        ),
        migrations.DeleteModel(
            name="UptimeCheckNode",
        ),
        migrations.DeleteModel(
            name="UptimeCheckTask",
        ),
        migrations.DeleteModel(
            name="UptimeCheckTaskCollectorLog",
        ),
        migrations.AlterField(
            model_name="collectorpluginconfig",
            name="collector_json",
            field=bkmonitor.utils.db.fields.JsonField(default={}, verbose_name="采集器配置"),
        ),
        migrations.AlterField(
            model_name="collectorpluginconfig",
            name="config_json",
            field=bkmonitor.utils.db.fields.JsonField(default=[], verbose_name="参数配置"),
        ),
    ]
