# Generated by Django 3.2.15 on 2023-06-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_search', '0065_replace_favorite_host_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userindexsetfieldsconfig',
            name='scope',
            field=models.CharField(db_index=True, default='default', max_length=16, verbose_name='范围'),
        ),
        migrations.AlterUniqueTogether(
            name='userindexsetfieldsconfig',
            unique_together={('index_set_id', 'username', 'scope')},
        ),
    ]
