# Generated by Django 3.2.15 on 2023-06-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_search', '0066_auto_20230620_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexsetfieldsconfig',
            name='scope',
            field=models.CharField(db_index=True, default='default', max_length=16, verbose_name='范围'),
        ),
        migrations.AlterUniqueTogether(
            name='indexsetfieldsconfig',
            unique_together={('index_set_id', 'name', 'scope')},
        ),
    ]
