# Generated by Django 3.2.15 on 2023-11-10 09:13

from django.db import migrations, models

import apps.utils.local


class Migration(migrations.Migration):
    dependencies = [
        ('log_search', '0067_auto_20230620_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexsetfieldsconfig',
            name='source_app_code',
            field=models.CharField(
                blank=True, default=apps.utils.local.get_request_app_code, max_length=32, verbose_name='来源系统'
            ),
        ),
        migrations.AddField(
            model_name='userindexsetfieldsconfig',
            name='source_app_code',
            field=models.CharField(
                blank=True, default=apps.utils.local.get_request_app_code, max_length=32, verbose_name='来源系统'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='indexsetfieldsconfig',
            unique_together={('index_set_id', 'name', 'scope', 'source_app_code')},
        ),
        migrations.AlterUniqueTogether(
            name='userindexsetfieldsconfig',
            unique_together={('index_set_id', 'username', 'scope', 'source_app_code')},
        ),
    ]
