# Generated by Django 3.2.15 on 2023-08-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_search', '0067_auto_20230620_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='asynctask',
            name='index_set_ids',
            field=models.JSONField(default=list, null=True, verbose_name='索引集ID列表'),
        ),
        migrations.AddField(
            model_name='asynctask',
            name='index_set_type',
            field=models.CharField(choices=[('single', '单索引集'), ('union', '联合索引集')], default='single', max_length=32, verbose_name='索引集类型'),
        ),
        migrations.AddField(
            model_name='userindexsetsearchhistory',
            name='index_set_ids',
            field=models.JSONField(default=list, null=True, verbose_name='索引集ID列表'),
        ),
        migrations.AddField(
            model_name='userindexsetsearchhistory',
            name='index_set_type',
            field=models.CharField(choices=[('single', '单索引集'), ('union', '联合索引集')], default='single', max_length=32, verbose_name='索引集类型'),
        ),
        migrations.AlterField(
            model_name='asynctask',
            name='index_set_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='索引集id'),
        ),
        migrations.AlterField(
            model_name='asynctask',
            name='scenario_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='接入场景'),
        ),
        migrations.AlterField(
            model_name='userindexsetsearchhistory',
            name='index_set_id',
            field=models.IntegerField(default=None, null=True, verbose_name='索引集ID'),
        ),
    ]
