# Generated by Django 3.2.15 on 2023-08-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_search', '0068_auto_20230802_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='index_set_ids',
            field=models.JSONField(default=list, null=True, verbose_name='索引集ID列表'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='index_set_type',
            field=models.CharField(choices=[('single', '单索引集'), ('union', '联合索引集')], default='single', max_length=32, verbose_name='索引集类型'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='index_set_id',
            field=models.IntegerField(default=None, null=True, verbose_name='索引集ID'),
        ),
    ]
