# Generated by Django 3.2.15 on 2023-11-13 03:40

from django.db import migrations, models

import apps.utils.local


class Migration(migrations.Migration):
    dependencies = [
        ('log_search', '0068_auto_20231110_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='source_app_code',
            field=models.CharField(
                blank=True, default=apps.utils.local.get_request_app_code, max_length=32, verbose_name='来源系统'
            ),
        ),
        migrations.AddField(
            model_name='favoritegroup',
            name='source_app_code',
            field=models.CharField(
                blank=True, default=apps.utils.local.get_request_app_code, max_length=32, verbose_name='来源系统'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('name', 'space_uid', 'source_app_code')},
        ),
        migrations.AlterUniqueTogether(
            name='favoritegroup',
            unique_together={('name', 'space_uid', 'created_by', 'source_app_code')},
        ),
    ]
