# Generated by Django 3.2.15 on 2023-11-24 07:23

from django.db import migrations, models

import apps.utils.local


class Migration(migrations.Migration):
    dependencies = [
        ('log_search', '0069_auto_20231113_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='asynctask',
            name='source_app_code',
            field=models.CharField(
                blank=True, default=apps.utils.local.get_request_app_code, max_length=32, verbose_name='来源系统'
            ),
        ),
    ]
