# Generated by Django 3.2.15 on 2023-11-24 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('log_search', '0070_asynctask_source_app_code'),
        ('log_search', '0070_storageclusterrecord'),
    ]

    operations = []
