# Generated by Django 3.2.15 on 2023-11-20 03:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('log_search', '0069_auto_20231113_1140'),
        ('log_search', '0070_storageclusterrecord'),
    ]

    operations = []
