# Generated by Django 3.2.15 on 2023-12-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_search', '0071_merge_20231124_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteUnionSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, default='', max_length=32, verbose_name='修改者')),
                ('space_uid', models.CharField(max_length=256, verbose_name='空间唯一标识')),
                ('username', models.CharField(db_index=True, max_length=255, verbose_name='用户名')),
                ('name', models.CharField(max_length=64, verbose_name='收藏名称')),
                ('index_set_ids', models.JSONField(verbose_name='索引集ID列表')),
            ],
            options={
                'verbose_name': '联合检索组合收藏',
                'verbose_name_plural': '34_搜索-联合检索组合收藏',
                'ordering': ('-updated_at',),
            },
        ),
    ]
