# Generated by Django 3.2.15 on 2024-03-27 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('log_search', '0072_auto_20231205_1548'),
        ('log_search', '0072_auto_20231228_1420'),
    ]

    operations = []
