# Generated by Django 3.2.15 on 2023-12-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_search', '0072_favoriteunionsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexsetfieldsconfig',
            name='index_set_ids',
            field=models.JSONField(default=list, null=True, verbose_name='索引集ID列表'),
        ),
        migrations.AddField(
            model_name='indexsetfieldsconfig',
            name='index_set_ids_hash',
            field=models.CharField(db_index=True, max_length=32, null=True, verbose_name='索引集ID哈希'),
        ),
        migrations.AddField(
            model_name='indexsetfieldsconfig',
            name='index_set_type',
            field=models.CharField(
                choices=[('single', '单索引集'), ('union', '联合索引集')], default='single', max_length=32, verbose_name='索引集类型'
            ),
        ),
        migrations.AddField(
            model_name='userindexsetfieldsconfig',
            name='index_set_ids',
            field=models.JSONField(default=list, null=True, verbose_name='索引集ID列表'),
        ),
        migrations.AddField(
            model_name='userindexsetfieldsconfig',
            name='index_set_ids_hash',
            field=models.CharField(db_index=True, max_length=32, null=True, verbose_name='索引集ID哈希'),
        ),
        migrations.AddField(
            model_name='userindexsetfieldsconfig',
            name='index_set_type',
            field=models.CharField(
                choices=[('single', '单索引集'), ('union', '联合索引集')], default='single', max_length=32, verbose_name='索引集类型'
            ),
        ),
        migrations.AlterField(
            model_name='indexsetfieldsconfig',
            name='index_set_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='索引集ID'),
        ),
        migrations.AlterField(
            model_name='userindexsetfieldsconfig',
            name='config_id',
            field=models.IntegerField(db_index=True, verbose_name='索引集配置ID'),
        ),
        migrations.AlterField(
            model_name='userindexsetfieldsconfig',
            name='index_set_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='索引集ID'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteunionsearch',
            unique_together={('space_uid', 'username', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='indexsetfieldsconfig',
            unique_together={('index_set_id', 'index_set_ids_hash', 'name', 'scope', 'source_app_code')},
        ),
        migrations.AlterUniqueTogether(
            name='userindexsetfieldsconfig',
            unique_together={('index_set_id', 'index_set_ids_hash', 'username', 'scope', 'source_app_code')},
        ),
    ]
