# Generated by Django 3.2.15 on 2024-05-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_search', '0076_add_bcs_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userindexsetsearchhistory',
            name='from_favorite_id',
            field=models.IntegerField(default=0, verbose_name='检索收藏ID', db_index=True),
        ),
    ]
