# Generated by Django 3.2.15 on 2024-09-09 02:32

from django.db import migrations, models

from apps.log_search.constants import SearchMode


def add_favorite_search_mode(apps, schema_editor):
    Favorite = apps.get_model("log_search", "Favorite")
    favorites = Favorite.objects.all()
    for favorite in favorites:
        params = favorite.params
        try:
            # 若query_string存在，且过滤条件为空
            if params.get("keyword") and params["keyword"] != "*":
                if not params.get("addition", []) and not params.get("host_scopes", {}):
                    favorite.search_mode = SearchMode.SQL.value
                    favorite.save()
                    print(f"add favorite to index[{favorite.index_set_id}] success, search params: {favorite.params}")
                    continue
        except Exception as e:
            print(f"add favorite to index[{favorite.index_set_id}] failed,search params: {favorite.params}, info: {e}")


class Migration(migrations.Migration):
    dependencies = [
        ('log_search', '0077_userindexsetsearchhistory_from_favorite_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='search_mode',
            field=models.CharField(
                choices=[('ui', 'UI模式'), ('sql', 'SQL模式')], default='ui', max_length=32, verbose_name='检索模式'
            ),
        ),
        migrations.AddField(
            model_name='userindexsetsearchhistory',
            name='search_mode',
            field=models.CharField(
                choices=[('ui', 'UI模式'), ('sql', 'SQL模式')], default='ui', max_length=32, verbose_name='检索模式'
            ),
        ),
        migrations.RunPython(add_favorite_search_mode),
    ]
