# Generated by Django 3.2.15 on 2024-10-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_search', '0078_auto_20240909_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIndexSetCustomConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, verbose_name='用户name')),
                ('index_set_id', models.IntegerField(null=True, verbose_name='索引集ID')),
                ('index_set_ids', models.JSONField(default=list, null=True, verbose_name='索引集ID列表')),
                ('index_set_hash', models.CharField(max_length=32, verbose_name='索引集哈希')),
                ('index_set_config', models.JSONField(default=dict, verbose_name='用户索引集配置')),
            ],
            options={
                'verbose_name': '用户索引集自定义配置',
                'verbose_name_plural': '用户索引集自定义配置',
                'unique_together': {('username', 'index_set_hash')},
            },
        ),
    ]
