# Generated by Django 3.2.15 on 2024-10-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_search', '0079_user_index_set_custom_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindexset',
            name='max_analyzed_offset',
            field=models.IntegerField(default=0, verbose_name='日志长文本高亮长度限制'),
        ),
    ]
