# Generated by Django 3.2.15 on 2024-11-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_search', '0080_logindexset_max_analyzed_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindexset',
            name='max_async_count',
            field=models.IntegerField(default=0, verbose_name='日志异步下载最大条数限制'),
        ),
    ]
