# Generated by Django 3.2.15 on 2024-11-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_search', '0081_logindexset_max_async_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='favorite_type',
            field=models.CharField(choices=[('search', '检索'), ('chart', '图表')], default='search', max_length=32, verbose_name='收藏类型'),
        ),
        migrations.AddField(
            model_name='logindexset',
            name='doris_table_id',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='doris表名'),
        ),
        migrations.AddField(
            model_name='logindexset',
            name='support_doris',
            field=models.BooleanField(default=False, verbose_name='是否支持doris存储类型'),
        ),
    ]
