# Generated by Django 3.2.15 on 2024-12-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_search', '0082_auto_20241113_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, default='', max_length=32, verbose_name='修改者')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('deleted_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='删除者')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='用户ID')),
                ('custom_config', models.JSONField(verbose_name='自定义配置')),
            ],
            options={
                'verbose_name': '用户自定义配置',
                'verbose_name_plural': '用户自定义配置',
                'ordering': ('-updated_at',),
            },
        ),
    ]
