# Generated by Django 3.2.15 on 2025-02-17 07:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('log_search', '0083_usercustomconfig'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('name', 'space_uid', 'group_id', 'source_app_code', 'created_by')},
        ),
    ]
