# Generated by Django 4.2 on 2025-04-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_search', '0084_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSetCustomConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, default='', max_length=32, verbose_name='修改者')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('deleted_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='删除者')),
                ('index_set_id', models.IntegerField(null=True, verbose_name='索引集ID')),
                ('index_set_ids', models.JSONField(default=list, null=True, verbose_name='索引集ID列表')),
                ('index_set_hash', models.CharField(max_length=32, unique=True, verbose_name='索引集哈希')),
                ('index_set_custom_config', models.JSONField(default=dict, verbose_name='索引集自定义配置')),
            ],
            options={
                'verbose_name': '索引集自定义配置',
                'verbose_name_plural': '索引集自定义配置',
                'ordering': ('-updated_at',),
            },
        ),
    ]
