# Generated by Django 4.2 on 2025-04-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_search', '0084_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSetCustomConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_set_id', models.IntegerField(null=True, verbose_name='索引集ID')),
                ('index_set_ids', models.JSONField(default=list, null=True, verbose_name='索引集ID列表')),
                ('index_set_hash', models.CharField(max_length=32, unique=True, verbose_name='索引集哈希')),
                ('index_set_config', models.JSONField(default=dict, verbose_name='索引集自定义配置')),
            ],
            options={
                'verbose_name': '索引集自定义配置',
                'verbose_name_plural': '索引集自定义配置',
            },
        ),
    ]
