# Generated by Django 3.2.25 on 2025-04-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_search', '0084_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustomconfig',
            name='user_id',
        ),
    ]
