# Generated by Django 4.2 on 2025-04-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_search', '0085_indexsetcustomconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='bk_tenant_id',
            field=models.CharField(db_index=True, default='system', max_length=64, verbose_name='租户ID'),
        ),
    ]
