# Generated by Django 4.2 on 2025-04-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_search", "0086_space_bk_tenant_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="space_uid",
            field=models.CharField(db_index=True, max_length=256, verbose_name="空间唯一标识"),
        ),
    ]
