# Generated by Django 4.2 on 2025-06-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_search", "0087_alter_space_space_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="logindexsetdata",
            name="scenario_id",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="接入场景"),
        ),
        migrations.AddField(
            model_name="logindexsetdata",
            name="storage_cluster_id",
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name="存储集群ID"),
        ),
    ]
