# Generated by Django 4.2 on 2025-05-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_search", "0087_alter_space_space_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="logindexset",
            name="bk_tenant_id",
            field=models.CharField(db_index=True, default="system", max_length=64, verbose_name="租户ID"),
        ),
    ]
