# Generated by Django 4.2 on 2025-06-20 08:06

from django.db import migrations, models


def add_initial_data(apps, schema_editor):
    LogIndexSetData = apps.get_model("log_search", "LogIndexSetData")
    LogIndexSet = apps.get_model("log_search", "LogIndexSet")
    index_set_ids = LogIndexSetData.objects.values_list("index_set_id", flat=True)
    log_index_sets = LogIndexSet.objects.filter(index_set_id__in=index_set_ids).values(
        "index_set_id", "scenario_id", "storage_cluster_id", "time_field_type", "time_field_unit"
    )
    objs_list = list(LogIndexSetData.objects.filter(index_set_id__in=index_set_ids))
    log_index_sets_dict = {log["index_set_id"]: log for log in log_index_sets}

    for obj in objs_list:
        # 取得对应现有对象的数据并更新
        log_data = log_index_sets_dict.get(obj.index_set_id)
        if log_data:
            obj.scenario_id = log_data["scenario_id"]
            obj.storage_cluster_id = log_data["storage_cluster_id"]
            obj.time_field_type = log_data["time_field_type"]
            obj.time_field_unit = log_data["time_field_unit"]

    LogIndexSetData.objects.bulk_update(
        objs_list, ["scenario_id", "storage_cluster_id", "time_field_type", "time_field_unit"], batch_size=500
    )


class Migration(migrations.Migration):
    dependencies = [
        ("log_search", "0087_alter_space_space_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="logindexsetdata",
            name="scenario_id",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="接入场景"),
        ),
        migrations.AddField(
            model_name="logindexsetdata",
            name="storage_cluster_id",
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name="存储集群ID"),
        ),
        migrations.AddField(
            model_name="logindexsetdata",
            name="time_field_type",
            field=models.CharField(default=None, max_length=32, null=True, verbose_name="时间字段类型"),
        ),
        migrations.AddField(
            model_name="logindexsetdata",
            name="time_field_unit",
            field=models.CharField(default=None, max_length=32, null=True, verbose_name="时间字段单位"),
        ),
        migrations.RunPython(add_initial_data),
    ]
