# Generated by Django 4.2 on 2025-06-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_search", "0088_logindexsetdata_scenario_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logindexset",
            name="query_alias_settings",
            field=models.JSONField(blank=True, null=True, verbose_name="查询别名配置"),
        ),
    ]
