# Generated by Django 4.2.22 on 2025-09-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_search", "0089_logindexset_query_alias_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="logindexset",
            name="is_group",
            field=models.BooleanField(default=False, verbose_name="是否索引组"),
        ),
        migrations.AddField(
            model_name="logindexsetdata",
            name="type",
            field=models.CharField(
                choices=[("result_table", "结果表"), ("index_set", "索引集")],
                default="result_table",
                max_length=64,
                verbose_name="类型",
            ),
        ),
    ]
