# Generated by Django 4.2.22 on 2026-03-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_search", "0090_clear_favorite_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logindexset",
            name="doris_table_id",
            field=models.TextField(default=None, null=True, verbose_name="doris表名"),
        ),
    ]
