# Generated by Django 4.2.22 on 2025-10-22 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("log_search", "0090_clear_favorite_group"),
        ("log_search", "0090_logindexset_is_group_logindexsetdata_type"),
    ]

    operations = []
