# Generated by Django 4.2.22 on 2026-03-31 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_search', '0091_alter_logindexset_doris_table_id'),
        ('log_search', '0091_merge_20251022_1625'),
    ]

    operations = [
    ]
