# Generated by Django 4.2.22 on 2026-03-02 02:02

from django.db import migrations


def forwards_func(apps, schema_editor):
    """
    将符合条件的索引集转为索引组：
    1. 找到 scenario_id=log 且没有 collector_config_id 的索引集
    2. 通过 result_table_id 找到对应的采集项索引集 ID，新增 type=index_set 的 LogIndexSetData 记录
    3. 标记 is_group=True
    """
    LogIndexSet = apps.get_model("log_search", "LogIndexSet")
    LogIndexSetData = apps.get_model("log_search", "LogIndexSetData")
    CollectorConfig = apps.get_model("log_databus", "CollectorConfig")

    # 找到需要转为索引组的索引集：scenario_id=log 且没有 collector_config_id
    index_sets = LogIndexSet.objects.filter(
        scenario_id="log", collector_config_id__isnull=True, is_group=False, is_deleted=False
    )

    # 建立映射：result_table_id -> CollectorConfig 对应的 index_set_id
    rt_id_to_index_set_id = dict(
        CollectorConfig.objects.filter(table_id__isnull=False, index_set_id__isnull=False, is_deleted=False)
        .exclude(table_id="")
        .values_list("table_id", "index_set_id")
    )

    for index_set in index_sets:
        log_index_data_list = list(
            LogIndexSetData.objects.filter(index_set_id=index_set.index_set_id, is_deleted=False)
        )

        to_create = []
        for index_data in log_index_data_list:
            # 通过 result_table_id 找到对应的采集项索引集 ID
            mapped_index_set_id = rt_id_to_index_set_id.get(index_data.result_table_id)
            if mapped_index_set_id:
                print(
                    f"WARNING: Cannot find original collector index set for result_table_id={index_data.result_table_id}, collector may have been deleted, skip"
                )
                continue

            # 新增一条 type=index_set 的记录，原有 type=result_table 的记录保持不变
            to_create.append(
                LogIndexSetData(
                    index_set_id=index_set.index_set_id,
                    result_table_id=str(mapped_index_set_id),
                    scenario_id=index_data.scenario_id,
                    bk_biz_id=index_data.bk_biz_id,
                    type="index_set",
                    apply_status="normal",
                )
            )

        if to_create:
            LogIndexSetData.objects.bulk_create(to_create)

        # 标记为索引组
        index_set.is_group = True
        index_set.save(update_fields=["is_group"])


def reverse_func(apps, schema_editor):
    """
    回滚操作：
    1. 删除迁移新增的 type=index_set 的 LogIndexSetData 记录
    2. 将 is_group=True 且 scenario_id=log 且 collector_config_id 为空的索引集恢复为 is_group=False
    """
    LogIndexSet = apps.get_model("log_search", "LogIndexSet")
    LogIndexSetData = apps.get_model("log_search", "LogIndexSetData")

    index_sets = LogIndexSet.objects.filter(
        scenario_id="log", collector_config_id__isnull=True, is_group=True, is_deleted=False
    )
    for index_set in index_sets:
        # 删除迁移新增的 type=index_set 记录，原有 type=result_table 的记录不受影响
        deleted_count, _ = LogIndexSetData.objects.filter(
            index_set_id=index_set.index_set_id, type="index_set", is_deleted=False
        ).delete()
        index_set.is_group = False
        index_set.save(update_fields=["is_group"])


class Migration(migrations.Migration):
    dependencies = [
        ("log_search", "0091_merge_20251022_1625"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
