# Generated by Django 4.2.22 on 2026-04-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_search", "0092_merge_20260331_1953"),
    ]

    operations = [
        migrations.AddField(
            model_name="logindexset",
            name="is_platform_index",
            field=models.BooleanField(default=False, verbose_name="是否为平台级索引集"),
        ),
        migrations.AddField(
            model_name="logindexset",
            name="platform_index_filter",
            field=models.JSONField(blank=True, default=None, null=True, verbose_name="平台级数据隔离维度"),
        ),
        migrations.AddField(
            model_name="logindexset",
            name="platform_index_visibility",
            field=models.JSONField(blank=True, default=None, null=True, verbose_name="平台级可见范围"),
        ),
    ]
