# Generated by Django 4.2.22 on 2026-06-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_search", "0095_merge_scene_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="asynctask",
            name="download_count",
            field=models.IntegerField(default=0, verbose_name="下载次数"),
        ),
        migrations.AddField(
            model_name="asynctask",
            name="export_total_count",
            field=models.IntegerField(default=0, verbose_name="目标导出数量"),
        ),
        migrations.AddField(
            model_name="asynctask",
            name="exported_count",
            field=models.IntegerField(default=0, verbose_name="已导出数量"),
        ),
    ]
