# Generated by Django 4.2.22 on 2026-07-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_search", "0099_migrate_index_set_user_tags"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="asynctask",
            index=models.Index(fields=["created_by", "export_type", "export_status"], name="export_task_user_run_idx"),
        ),
    ]
