# Generated by Django 4.2.22 on 2026-09-02

from django.db import migrations, models


def initialize_scope(apps, schema_editor):
    favorite_model = apps.get_model("log_search", "Favorite")
    favorite_group_model = apps.get_model("log_search", "FavoriteGroup")
    favorite_model.objects.filter(scope__isnull=True).update(scope={})
    favorite_group_model.objects.filter(scope__isnull=True).update(scope={})


class Migration(migrations.Migration):
    dependencies = [
        ("log_search", "0100_asynctask_add_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="scope",
            field=models.JSONField(blank=True, null=True, verbose_name="收藏作用域"),
        ),
        migrations.AddField(
            model_name="favoritegroup",
            name="scope",
            field=models.JSONField(blank=True, null=True, verbose_name="收藏组作用域"),
        ),
        migrations.RunPython(initialize_scope, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="favorite",
            name="scope",
            field=models.JSONField(blank=True, default=dict, verbose_name="收藏作用域"),
        ),
        migrations.AlterField(
            model_name="favoritegroup",
            name="scope",
            field=models.JSONField(blank=True, default=dict, verbose_name="收藏组作用域"),
        ),
    ]
