# Generated by Django 4.2.22 on 2026-09-22 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("log_search", "0101_favorite_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("space_uid", models.CharField(max_length=256, verbose_name="空间标识")),
                ("created_by", models.CharField(max_length=64, verbose_name="创建者")),
                ("source_app_code", models.CharField(blank=True, default="", max_length=32, verbose_name="来源系统")),
                ("is_external", models.BooleanField(default=False, verbose_name="外部版任务")),
                ("index_set_id", models.IntegerField(verbose_name="索引集ID")),
                ("bk_biz_id", models.IntegerField(blank=True, null=True, verbose_name="业务ID")),
                ("search_params", models.JSONField(verbose_name="冻结查询参数")),
                ("base_dict", models.JSONField(verbose_name="冻结查询体")),
                ("policy", models.JSONField(default=dict, verbose_name="任务策略快照")),
                ("start_time", models.BigIntegerField(verbose_name="起始时间（毫秒，闭区间）")),
                ("end_time", models.BigIntegerField(verbose_name="结束时间（毫秒，开区间）")),
                ("time_tick", models.PositiveBigIntegerField(verbose_name="时间字段最小精度（毫秒）")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待规划"),
                            ("PLANNING", "规划中"),
                            ("READY", "待调度"),
                            ("RUNNING", "执行中"),
                            ("SUCCESS", "成功"),
                            ("FAILED", "失败"),
                            ("CANCELED", "已取消"),
                        ],
                        default="PENDING",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "interval",
                    models.PositiveBigIntegerField(blank=True, null=True, verbose_name="初始统计桶宽（毫秒）"),
                ),
                ("statistics_at", models.DateTimeField(blank=True, null=True, verbose_name="统计时间")),
                ("estimated_total", models.PositiveBigIntegerField(blank=True, null=True, verbose_name="预计总条数")),
                ("actual_total", models.PositiveBigIntegerField(default=0, verbose_name="已导出条数")),
                ("part_total", models.PositiveIntegerField(default=0, verbose_name="有效分片总数")),
                ("part_success", models.PositiveIntegerField(default=0, verbose_name="成功分片数")),
                ("requested_parallelism", models.PositiveSmallIntegerField(default=4, verbose_name="期望并行上限")),
                (
                    "manifest_object_key",
                    models.CharField(blank=True, default="", max_length=1024, verbose_name="清单对象名"),
                ),
                ("manifest_bytes", models.PositiveBigIntegerField(blank=True, null=True, verbose_name="清单字节数")),
                ("error_code", models.CharField(blank=True, default="", max_length=64, verbose_name="错误分类")),
                ("error_detail", models.TextField(blank=True, default="", verbose_name="错误详情")),
                ("planning_started_at", models.DateTimeField(blank=True, null=True, verbose_name="规划开始时间")),
                ("planning_attempts", models.PositiveIntegerField(default=0, verbose_name="规划尝试次数")),
                ("last_dispatched_at", models.DateTimeField(blank=True, null=True, verbose_name="最近投递时间")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始执行时间")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="产物过期时间")),
                ("artifacts_cleaned_at", models.DateTimeField(blank=True, null=True, verbose_name="产物清理时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "分片导出任务",
                "verbose_name_plural": "43_分片导出任务",
                "db_table": "log_export_job",
            },
        ),
        migrations.CreateModel(
            name="ExportPart",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("part_no", models.PositiveIntegerField(verbose_name="分片序号")),
                ("start_time", models.BigIntegerField(verbose_name="起始时间（毫秒，闭区间）")),
                ("end_time", models.BigIntegerField(verbose_name="结束时间（毫秒，开区间）")),
                ("oversized", models.BooleanField(default=False, verbose_name="已到最小时间精度仍超量")),
                ("estimated_rows", models.PositiveBigIntegerField(blank=True, null=True, verbose_name="预计条数")),
                ("estimated_bytes", models.PositiveBigIntegerField(blank=True, null=True, verbose_name="预计字节数")),
                ("actual_rows", models.PositiveBigIntegerField(blank=True, null=True, verbose_name="实际条数")),
                ("actual_bytes", models.PositiveBigIntegerField(blank=True, null=True, verbose_name="实际JSONL字节数")),
                (
                    "compressed_bytes",
                    models.PositiveBigIntegerField(blank=True, null=True, verbose_name="压缩后字节数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "待投递"),
                            ("DISPATCHED", "已投递"),
                            ("RUNNING", "执行中"),
                            ("SUCCESS", "成功"),
                            ("FAILED", "失败"),
                            ("CANCELED", "已取消"),
                        ],
                        default="WAITING",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DOWNLOAD_LOG", "取数"),
                            ("PACKAGE", "打包"),
                            ("UPLOAD", "上传"),
                            ("FINALIZING", "生成清单"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="阶段",
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0, verbose_name="执行次数")),
                ("task_id", models.CharField(blank=True, default="", max_length=255, verbose_name="Celery任务ID")),
                ("object_key", models.CharField(blank=True, default="", max_length=1024, verbose_name="产物对象名")),
                ("checksum", models.CharField(blank=True, default="", max_length=64, verbose_name="产物SHA256")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="本次执行开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="本次执行结束时间")),
                ("error_code", models.CharField(blank=True, default="", max_length=64, verbose_name="错误分类")),
                ("error_detail", models.TextField(blank=True, default="", verbose_name="错误详情")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="parts", to="log_search.exportjob"
                    ),
                ),
            ],
            options={
                "verbose_name": "分片导出子任务",
                "verbose_name_plural": "44_分片导出子任务",
                "db_table": "log_export_part",
            },
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(fields=["created_by", "status", "created_at"], name="export_job_user_status"),
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(fields=["space_uid", "created_at", "id"], name="export_job_space_history"),
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(fields=["status", "last_dispatched_at"], name="export_job_dispatch"),
        ),
        migrations.AddIndex(
            model_name="exportpart",
            index=models.Index(fields=["job", "status"], name="export_part_job_status"),
        ),
        migrations.AddIndex(
            model_name="exportpart",
            index=models.Index(fields=["status", "updated_at"], name="export_part_recover"),
        ),
        migrations.AlterUniqueTogether(
            name="exportpart",
            unique_together={("job", "part_no")},
        ),
    ]
