# Generated by Django 4.2.27 on 2025-12-27 12:21

import functools

from django.db import migrations, models

import bk_monitor_base.config.storage
import bk_monitor_base.domains.uploaded_file.models
import bk_monitor_base.infras.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_tenant_id", models.CharField(max_length=64, verbose_name="租户ID")),
                (
                    "file",
                    models.FileField(
                        storage=functools.partial(
                            bk_monitor_base.infras.storage.get_storage,
                            *(bk_monitor_base.config.storage.StorageName["DEFAULT"],),
                            **{},
                        ),
                        upload_to=bk_monitor_base.domains.uploaded_file.models.generate_upload_path,
                        verbose_name="文件内容",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=bk_monitor_base.domains.uploaded_file.models.generate_token,
                        max_length=128,
                        verbose_name="文件token",
                    ),
                ),
                ("original_filename", models.CharField(max_length=255, verbose_name="原始文件名")),
                ("usage", models.CharField(db_index=True, max_length=64, verbose_name="用途")),
                ("description", models.TextField(blank=True, default="", verbose_name="文件描述")),
                ("created_by", models.CharField(max_length=255, verbose_name="创建用户")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "用户上传文件",
                "verbose_name_plural": "用户上传文件",
                "db_table": "uploaded_file",
                "ordering": ["-created_at"],
            },
        ),
    ]
