# Generated by Django 3.2.15 on 2023-11-14 07:25

from django.db import migrations, models

import apps.utils.local


class Migration(migrations.Migration):
    dependencies = [
        ('log_extract', '0024_tasks_preview_ip_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='source_app_code',
            field=models.CharField(
                blank=True, default=apps.utils.local.get_request_app_code, max_length=32, verbose_name='来源系统'
            ),
        )
    ]
