# Generated by Django 4.2 on 2025-03-31 08:13

import bkcrypto.contrib.django.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('log_extract', '0025_auto_20231114_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractlink',
            name='qcloud_secret_id',
            field=bkcrypto.contrib.django.fields.SymmetricTextField(
                blank=True, default='', help_text='内网链路不需要填写', null=True, using='default', verbose_name='腾讯云SecretId'
            ),
        ),
        migrations.AlterField(
            model_name='extractlink',
            name='qcloud_secret_key',
            field=bkcrypto.contrib.django.fields.SymmetricTextField(
                blank=True, default='', help_text='内网链路不需要填写', null=True, using='default', verbose_name='腾讯云SecretKey'
            ),
        ),
    ]
