# Generated by Django 4.2.22 on 2026-04-09 09:31

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_extract", "0025_auto_20231114_1525"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="target_node_type",
            field=models.CharField(
                choices=[("INSTANCE", "主机实例"), ("TOPO", "拓扑"), ("SERVICE_TEMPLATE", "服务模板")],
                default="INSTANCE",
                max_length=64,
                verbose_name="目标节点类型",
            ),
        ),
        migrations.AddField(
            model_name="tasks",
            name="target_nodes",
            field=apps.models.JsonField(blank=True, default=list, null=True, verbose_name="节点列表"),
        ),
    ]
