# Generated by Django 4.2.17 on 2026-01-09 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DynamicGroupORM",
            fields=[
                ("dynamic_group_id", models.AutoField(primary_key=True, serialize=False, verbose_name="主键")),
                ("dynamic_group_name", models.CharField(max_length=255, verbose_name="名称")),
                ("condition_list", models.JSONField(default=list, verbose_name="分组条件列表")),
                ("object_model_code", models.CharField(max_length=255, verbose_name="对象模型英文标识")),
                ("space_code", models.CharField(default="", max_length=128, verbose_name="权限空间code")),
                ("bk_tenant_id", models.CharField(default="system", max_length=64, verbose_name="租户ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("created_by", models.CharField(blank=True, max_length=100, verbose_name="创建人")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=100, verbose_name="修改人")),
            ],
            options={
                "verbose_name": "动态分组",
                "verbose_name_plural": "动态分组",
                "db_table": "dynamic_group_v2",
                "indexes": [
                    models.Index(fields=["object_model_code"], name="dynamic_gro_object__729849_idx"),
                    models.Index(fields=["space_code"], name="dynamic_gro_space_c_61df89_idx"),
                    models.Index(fields=["bk_tenant_id"], name="dynamic_gro_bk_tena_c9fb46_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DynamicGroupMemberORM",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("member", models.JSONField(default=dict, verbose_name="分组成员")),
                (
                    "dynamic_group",
                    models.ForeignKey(
                        db_column="dynamic_group_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_dynamic_group.dynamicgrouporm",
                        verbose_name="动态分组",
                        db_index=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "动态分组成员",
                "verbose_name_plural": "动态分组成员",
                "db_table": "dynamic_group_member_v2",
            },
        ),
    ]
