export const mockList = [
  {
    collector_config_id: 1624,
    collector_scenario_name: '行日志文件',
    category_name: '进程',
    target_nodes: [
      {
        bk_host_id: 2000058531,
      },
      {
        bk_host_id: 2000058532,
      },
    ],
    status: 'running',
    task_id_list: ['19080889', '19511834', '19511835'],
    target_subscription_diff: {},
    create_clean_able: false,
    bkdata_index_set_ids: [],
    created_at: '2023-12-07 20:51:03+0800',
    created_by: 'jayjhwu',
    updated_at: '2025-08-19 11:35:54+0800',
    updated_by: 'yuxiaogao',
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    bk_biz_id: 100605,
    bkdata_biz_id: null,
    collector_config_name: 'ziijiatest1',
    collector_plugin_id: null,
    bk_app_code: 'bk_log_search',
    collector_scenario_id: 'row',
    custom_type: 'log',
    category_id: 'host_process',
    target_object_type: 'HOST',
    target_node_type: 'INSTANCE',
    description: 'ziijiatest1',
    is_active: true,
    data_link_id: 1,
    bk_data_id: 1580244,
    bk_data_name: '100605_bklog_ziijiatest1',
    table_id: 'ziijiatest1',
    bkbase_table_id: null,
    processing_id: null,
    etl_processor: 'transfer',
    etl_config: 'bk_log_json',
    subscription_id: 21288,
    bkdata_data_id: 1580244,
    index_set_id: 626397,
    data_encoding: 'UTF-8',
    params:
      "{'paths': ['/var/log/messages*'], 'exclude_files': [''], 'conditions': {'type': 'none', 'match_content': None, 'separator': None}, 'tail_files': True, 'ignore_older': 2678400, 'max_bytes': 204800, 'redis_hosts': [], 'syslog_conditions': [], 'encoding': 'UTF-8', 'run_task': True}",
    itsm_ticket_sn: null,
    itsm_ticket_status: 'not_apply',
    can_use_independent_es_cluster: true,
    collector_package_count: 10,
    collector_output_format: null,
    collector_config_overlay: null,
    storage_shards_nums: 2,
    storage_shards_size: 30,
    storage_replies: 0,
    bkdata_data_id_sync_times: 0,
    collector_config_name_en: 'ziijiatest1',
    environment: 'linux',
    bcs_cluster_id: null,
    extra_labels: [],
    add_pod_label: false,
    add_pod_annotation: false,
    yaml_config_enabled: false,
    yaml_config: '',
    rule_id: 0,
    is_display: true,
    log_group_id: null,
    storage_cluster_id: 57,
    storage_cluster_name: 'bklogstag2',
    retention: 7,
    table_id_prefix: '100605_bklog_',
    custom_name: '容器日志上报',
    is_search: true,
    index_set_name: [
      {
        name: 'bk_apm_trace',
      },
      {
        name: 'bk_aiops',
      },
    ],
    tags: [
      {
        name: '数据指纹',
        color: 'green',
        tag_id: 9,
      },
      {
        name: 'tagtag',
        color: 'green',
        tag_id: 9,
      },
      {
        name: 'i am suoyinji name placeholder',
        color: 'green',
        tag_id: 9,
      },
    ],
    permission: {
      search_log_v2: true,
      view_collection_v2: true,
      manage_collection_v2: true,
    },
  },
  {
    collector_config_id: 2965,
    collector_scenario_name: '行日志文件',
    category_name: 'Kubernetes',
    target_nodes: [
      {
        bk_host_id: 2000058532,
      },
    ],
    status: 'success',
    task_id_list: ['27300604'],
    target_subscription_diff: {},
    create_clean_able: true,
    bkdata_index_set_ids: [],
    created_at: '2025-02-24 14:32:34+0800',
    created_by: 'kyliewang',
    updated_at: '2025-08-18 03:31:48+0800',
    updated_by: 'yuxiaogao',
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    bk_biz_id: 100605,
    bkdata_biz_id: null,
    collector_config_name: '全文下载测试',
    collector_plugin_id: null,
    bk_app_code: 'bk_log_search',
    collector_scenario_id: 'row',
    custom_type: 'log',
    category_id: 'kubernetes',
    target_object_type: 'HOST',
    target_node_type: 'INSTANCE',
    description: '全文下载测试',
    is_active: false,
    data_link_id: 2,
    bk_data_id: 1573858,
    bk_data_name: '100605_bklog_test_async_export',
    table_id: 'test_async_export',
    bkbase_table_id: null,
    processing_id: null,
    etl_processor: 'transfer',
    etl_config: 'bk_log_text',
    subscription_id: 32294,
    bkdata_data_id: null,
    index_set_id: 627605,
    data_encoding: 'UTF-8',
    params:
      "{'paths': ['/var/log/*'], 'exclude_files': [], 'conditions': {'type': 'none', 'match_content': None, 'separator': None}, 'tail_files': True, 'ignore_older': 86400, 'max_bytes': 204800, 'redis_hosts': [], 'extra_labels': [], 'syslog_conditions': [], 'kafka_hosts': [], 'kafka_ssl_params': {}, 'kafka_topics': [], 'kafka_group_id': '', 'kafka_initial_offset': 'newest', 'encoding': 'UTF-8', 'run_task': True}",
    itsm_ticket_sn: null,
    itsm_ticket_status: 'not_apply',
    can_use_independent_es_cluster: true,
    collector_package_count: 10,
    collector_output_format: null,
    collector_config_overlay: null,
    storage_shards_nums: 1,
    storage_shards_size: 30,
    storage_replies: 0,
    bkdata_data_id_sync_times: 0,
    collector_config_name_en: 'test_async_export',
    environment: 'linux',
    bcs_cluster_id: null,
    extra_labels: [],
    add_pod_label: false,
    add_pod_annotation: false,
    yaml_config_enabled: false,
    yaml_config: '',
    rule_id: 0,
    is_display: true,
    log_group_id: null,
    storage_cluster_id: 15,
    storage_cluster_name: 'es7_cluster',
    retention: 1,
    table_id_prefix: '100605_bklog_',
    custom_name: '容器日志上报',
    is_search: false,
    index_set_name: [
      {
        name: 'bk_apm_trace',
      },
      {
        name: 'bk_aiops',
      },
    ],
    tags: [
      {
        name: 'ab',
        color: 'green',
        tag_id: 9,
      },
      {
        name: 'cd',
        color: 'green',
        tag_id: 19,
      },
    ],
    permission: {
      search_log_v2: true,
      view_collection_v2: true,
      manage_collection_v2: true,
    },
  },
  {
    collector_config_id: 3143,
    collector_scenario_name: '行日志文件',
    category_name: '进程',
    target_nodes: [
      {
        bk_host_id: 2000058392,
      },
    ],
    status: 'success',
    task_id_list: ['26931061'],
    target_subscription_diff: {},
    create_clean_able: true,
    bkdata_index_set_ids: [],
    created_at: '2025-07-16 14:46:01+0800',
    created_by: 'kyliewang',
    updated_at: '2025-08-18 03:31:48+0800',
    updated_by: 'kyliewang',
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    bk_biz_id: 100605,
    bkdata_biz_id: null,
    collector_config_name: '测试回滚',
    collector_plugin_id: null,
    bk_app_code: 'bk_log_search',
    collector_scenario_id: 'row',
    custom_type: 'log',
    category_id: 'host_process',
    target_object_type: 'HOST',
    target_node_type: 'INSTANCE',
    description: '测试回滚',
    is_active: false,
    data_link_id: 2,
    bk_data_id: 1575606,
    bk_data_name: null,
    table_id: null,
    bkbase_table_id: null,
    processing_id: null,
    etl_processor: 'transfer',
    etl_config: null,
    subscription_id: 33233,
    bkdata_data_id: null,
    index_set_id: null,
    data_encoding: 'UTF-8',
    params:
      "{'paths': ['/var/log/*'], 'exclude_files': [], 'conditions': {'type': 'none', 'match_content': None, 'separator': None}, 'tail_files': True, 'ignore_older': 86400, 'max_bytes': 204800, 'winlog_name': [], 'winlog_level': [], 'winlog_event_id': [], 'redis_hosts': [], 'extra_labels': [], 'syslog_conditions': [], 'kafka_hosts': [], 'kafka_ssl_params': {}, 'kafka_topics': [], 'kafka_group_id': '', 'kafka_initial_offset': 'newest', 'encoding': 'UTF-8', 'run_task': True}",
    itsm_ticket_sn: null,
    itsm_ticket_status: 'not_apply',
    can_use_independent_es_cluster: true,
    collector_package_count: 10,
    collector_output_format: null,
    collector_config_overlay: null,
    storage_shards_nums: null,
    storage_shards_size: null,
    storage_replies: 1,
    bkdata_data_id_sync_times: 0,
    collector_config_name_en: 'test_rollback',
    environment: 'linux',
    bcs_cluster_id: null,
    extra_labels: [],
    add_pod_label: false,
    add_pod_annotation: false,
    yaml_config_enabled: false,
    yaml_config: '',
    rule_id: 0,
    is_display: true,
    log_group_id: null,
    storage_cluster_id: -1,
    storage_cluster_name: '',
    retention: 0,
    custom_name: '容器日志上报',
    is_search: false,
    index_set_name: [
      {
        name: 'bk_apm_trace',
      },
      {
        name: '容器日志采集示例',
      },
    ],
    tags: [
      {
        name: 'place',
        color: 'green',
        tag_id: 9,
      },
      {
        name: 'hello',
        color: 'green',
        tag_id: 19,
      },
    ],
    permission: {
      view_collection_v2: true,
      manage_collection_v2: true,
    },
  },
  {
    collector_config_id: 3141,
    collector_scenario_name: '行日志文件',
    category_name: '进程',
    target_nodes: [
      {
        bk_host_id: 2000058392,
      },
    ],
    status: 'FAILED',
    task_id_list: ['26888952'],
    target_subscription_diff: {},
    create_clean_able: true,
    bkdata_index_set_ids: [],
    created_at: '2025-07-16 11:57:54+0800',
    created_by: 'kyliewang',
    updated_at: '2025-08-18 03:30:03+0800',
    updated_by: 'kyliewang',
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    bk_biz_id: 100605,
    bkdata_biz_id: null,
    collector_config_name: '测试跨集群是否影响原有',
    collector_plugin_id: null,
    bk_app_code: 'bk_log_search',
    collector_scenario_id: 'row',
    custom_type: 'log',
    category_id: 'host_process',
    target_object_type: 'HOST',
    target_node_type: 'INSTANCE',
    description: '测试跨集群是否影响原有',
    is_active: true,
    data_link_id: 2,
    bk_data_id: 1575595,
    bk_data_name: null,
    table_id: 'test_for_new_feature',
    bkbase_table_id: null,
    processing_id: null,
    etl_processor: 'transfer',
    etl_config: null,
    subscription_id: 33232,
    bkdata_data_id: null,
    index_set_id: null,
    data_encoding: 'UTF-8',
    params:
      "{'paths': ['/var/log/*'], 'exclude_files': [], 'conditions': {'type': 'none', 'match_content': None, 'separator': None}, 'tail_files': True, 'ignore_older': 86400, 'max_bytes': 204800, 'winlog_name': [], 'winlog_level': [], 'winlog_event_id': [], 'redis_hosts': [], 'extra_labels': [], 'syslog_conditions': [], 'kafka_hosts': [], 'kafka_ssl_params': {}, 'kafka_topics': [], 'kafka_group_id': '', 'kafka_initial_offset': 'newest', 'encoding': 'UTF-8', 'run_task': True}",
    itsm_ticket_sn: null,
    itsm_ticket_status: 'not_apply',
    can_use_independent_es_cluster: true,
    collector_package_count: 10,
    collector_output_format: null,
    collector_config_overlay: null,
    storage_shards_nums: 3,
    storage_shards_size: 30,
    storage_replies: 1,
    bkdata_data_id_sync_times: 0,
    collector_config_name_en: 'test_for_new_feature',
    environment: 'linux',
    bcs_cluster_id: null,
    extra_labels: [],
    add_pod_label: false,
    add_pod_annotation: false,
    yaml_config_enabled: false,
    yaml_config: '',
    rule_id: 0,
    is_display: true,
    log_group_id: null,
    storage_cluster_id: 21,
    storage_cluster_name: 'bklogtest.sz.es.db',
    retention: 7,
    table_id_prefix: '100605_bklog_',
    custom_name: '容器日志上报',
    is_search: false,
    index_set_name: [
      {
        name: 'bk_apm_trace',
      },
      {
        name: '容器日志采集示例',
      },
    ],
    tags: [
      {
        name: 'i am suoyinji name placeholder',
        color: 'green',
        tag_id: 9,
      },
      {
        name: 'hello_world',
        color: 'green',
        tag_id: 19,
      },
    ],
    permission: {
      view_collection_v2: true,
      manage_collection_v2: true,
    },
  },
  {
    collector_config_id: 3145,
    collector_scenario_name: '行日志文件',
    category_name: '进程',
    target_nodes: [
      {
        bk_host_id: 2000006653,
      },
      {
        bk_host_id: 2000006654,
      },
      {
        bk_host_id: 2000058392,
      },
      {
        bk_host_id: 2000058531,
      },
      {
        bk_host_id: 2000058532,
      },
    ],
    status: 'TERMINATED',
    task_id_list: ['27635544'],
    target_subscription_diff: {},
    create_clean_able: false,
    bkdata_index_set_ids: [],
    created_at: '2025-07-21 10:55:07+0800',
    created_by: 'v_cwcgcui',
    updated_at: '2025-08-12 12:06:39+0800',
    updated_by: 'jayjhwu',
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    bk_biz_id: 100605,
    bkdata_biz_id: null,
    collector_config_name: 'test_mulit_index_v2',
    collector_plugin_id: null,
    bk_app_code: 'bk_log_search',
    collector_scenario_id: 'row',
    custom_type: 'log',
    category_id: 'host_process',
    target_object_type: 'HOST',
    target_node_type: 'INSTANCE',
    description: 'test_mulit_index_v2',
    is_active: true,
    data_link_id: 2,
    bk_data_id: 1575618,
    bk_data_name: '100605_bklog_test_mulit_index_v2',
    table_id: 'test_mulit_index_v2',
    bkbase_table_id: null,
    processing_id: null,
    etl_processor: 'transfer',
    etl_config: 'bk_log_delimiter',
    subscription_id: 33248,
    bkdata_data_id: 1575618,
    index_set_id: 627771,
    data_encoding: 'UTF-8',
    params:
      "{'paths': ['/var/log/messages*'], 'exclude_files': [], 'conditions': {'type': 'none', 'match_content': None, 'separator': None}, 'tail_files': True, 'ignore_older': 86400, 'max_bytes': 204800, 'redis_hosts': [], 'extra_labels': [], 'syslog_conditions': [], 'kafka_hosts': [], 'kafka_ssl_params': {}, 'kafka_topics': [], 'kafka_group_id': '', 'kafka_initial_offset': 'newest', 'encoding': 'UTF-8', 'run_task': True}",
    itsm_ticket_sn: null,
    itsm_ticket_status: 'not_apply',
    can_use_independent_es_cluster: true,
    collector_package_count: 10,
    collector_output_format: null,
    collector_config_overlay: null,
    storage_shards_nums: 3,
    storage_shards_size: 30,
    storage_replies: 1,
    bkdata_data_id_sync_times: 0,
    collector_config_name_en: 'test_mulit_index_v2',
    environment: 'linux',
    bcs_cluster_id: null,
    extra_labels: [],
    add_pod_label: false,
    add_pod_annotation: false,
    yaml_config_enabled: false,
    yaml_config: '',
    rule_id: 0,
    is_display: true,
    log_group_id: null,
    storage_cluster_id: 48,
    storage_cluster_name: 'audit_stag_2',
    retention: 7,
    table_id_prefix: '100605_bklog_',
    custom_name: '容器日志上报',
    is_search: true,
    index_set_name: [
      {
        name: 'bk_apm_trace',
      },
      {
        name: '容器日志采集示例',
      },
    ],
    tags: [
      {
        name: '数据指纹',
        color: 'green',
        tag_id: 9,
      },
      {
        name: 'i am suoyinji name placeholder',
        color: 'green',
        tag_id: 9,
      },
      {
        name: 'tagtag',
        color: 'green',
        tag_id: 9,
      },
    ],
    permission: {
      search_log_v2: true,
      view_collection_v2: true,
      manage_collection_v2: true,
    },
  },
  {
    collector_config_id: 3151,
    collector_scenario_name: '行日志文件',
    category_name: '进程',
    target_nodes: [
      {
        bk_inst_id: 'aad7fedb-0eb9-11eb-ace2-525400a7e3df',
        bk_obj_id: 'DYNAMIC_GROUP',
      },
      {
        bk_inst_id: '9fe24e6e-0e99-11eb-ace2-525400a7e3df',
        bk_obj_id: 'DYNAMIC_GROUP',
      },
    ],
    task_id_list: ['27223664'],
    target_subscription_diff: {},
    create_clean_able: true,
    bkdata_index_set_ids: [],
    created_at: '2025-07-28 17:05:38+0800',
    created_by: 'israelli',
    updated_at: '2025-08-03 03:32:13+0800',
    updated_by: 'israelli',
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    bk_biz_id: 100605,
    bkdata_biz_id: null,
    collector_config_name: 'DYNAMIC_GROUP222',
    collector_plugin_id: null,
    bk_app_code: 'bk_log_search',
    collector_scenario_id: 'row',
    custom_type: 'log',
    category_id: 'host_process',
    target_object_type: 'HOST',
    target_node_type: 'DYNAMIC_GROUP',
    description: 'DYNAMIC_GROUP',
    is_active: true,
    data_link_id: 2,
    bk_data_id: 1575738,
    bk_data_name: null,
    table_id: 'dynamicgroup2222',
    bkbase_table_id: null,
    processing_id: null,
    etl_processor: 'transfer',
    etl_config: 'bk_log_text',
    subscription_id: 33332,
    bkdata_data_id: 1575738,
    index_set_id: 627791,
    data_encoding: 'UTF-8',
    params:
      "{'paths': ['/var/logs'], 'exclude_files': [], 'conditions': {'type': 'none', 'match_content': None, 'separator': None}, 'tail_files': True, 'ignore_older': 86400, 'max_bytes': 204800, 'winlog_name': [], 'winlog_level': [], 'winlog_event_id': [], 'redis_hosts': [], 'extra_labels': [], 'syslog_conditions': [], 'kafka_hosts': [], 'kafka_ssl_params': {}, 'kafka_topics': [], 'kafka_group_id': '', 'kafka_initial_offset': 'newest', 'encoding': 'UTF-8', 'run_task': True}",
    itsm_ticket_sn: null,
    itsm_ticket_status: 'not_apply',
    can_use_independent_es_cluster: true,
    collector_package_count: 10,
    collector_output_format: null,
    collector_config_overlay: null,
    storage_shards_nums: 3,
    storage_shards_size: 30,
    storage_replies: 1,
    bkdata_data_id_sync_times: 0,
    collector_config_name_en: 'DYNAMICGROUP2222',
    environment: 'linux',
    bcs_cluster_id: null,
    extra_labels: [],
    add_pod_label: false,
    add_pod_annotation: false,
    yaml_config_enabled: false,
    yaml_config: '',
    rule_id: 0,
    is_display: true,
    log_group_id: null,
    storage_cluster_id: 42,
    storage_cluster_name: 'bkaudittest_sz_es_svr_ehk_db',
    retention: 7,
    table_id_prefix: '100605_bklog_',
    custom_name: '容器日志上报',
    is_search: true,
    index_set_name: [
      {
        name: '默认索引集',
      },
      {
        name: '容器日志采集示例',
      },
    ],
    tags: [
      {
        name: '无数据',
        color: 'red',
        tag_id: 4,
      },
    ],
    permission: {
      search_log_v2: true,
      view_collection_v2: true,
      manage_collection_v2: true,
    },
  },
];
