# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2022 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2022-03-03 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apm_web", "0003_auto_20220224_1420"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppServiceRelation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.BigIntegerField(verbose_name="业务ID")),
                ("app_name", models.CharField(max_length=50, verbose_name="应用名称")),
                ("service_name", models.CharField(max_length=512, verbose_name="服务名称")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("relate_bk_biz_id", models.BigIntegerField(verbose_name="关联业务ID")),
                ("relate_app_name", models.CharField(max_length=50, verbose_name="关联应用名称")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CMDBServiceRelation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.BigIntegerField(verbose_name="业务ID")),
                ("app_name", models.CharField(max_length=50, verbose_name="应用名称")),
                ("service_name", models.CharField(max_length=512, verbose_name="服务名称")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("template_id", models.BigIntegerField(verbose_name="服务模板ID")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LogServiceRelation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.BigIntegerField(verbose_name="业务ID")),
                ("app_name", models.CharField(max_length=50, verbose_name="应用名称")),
                ("service_name", models.CharField(max_length=512, verbose_name="服务名称")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("log_type", models.CharField(choices=[("other", "其他日志")], max_length=50, verbose_name="日志类型")),
                ("value", models.CharField(max_length=512, verbose_name="日志值")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterIndexTogether(
            name="logservicerelation",
            index_together={("bk_biz_id", "app_name", "service_name")},
        ),
        migrations.AlterIndexTogether(
            name="cmdbservicerelation",
            index_together={("bk_biz_id", "app_name", "service_name")},
        ),
        migrations.AlterIndexTogether(
            name="appservicerelation",
            index_together={("bk_biz_id", "app_name", "service_name")},
        ),
    ]
