# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2022 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2022-05-25 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0007_application_data_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApdexServiceRelation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.BigIntegerField(verbose_name="业务ID")),
                ("app_name", models.CharField(max_length=50, verbose_name="应用名称")),
                ("service_name", models.CharField(max_length=512, verbose_name="服务名称")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("apdex_default", models.IntegerField(verbose_name="默认Apdex")),
                ("apdex_http", models.IntegerField(verbose_name="网页Apdex")),
                ("apdex_db", models.IntegerField(verbose_name="DB Apdex")),
                ("apdex_rpc", models.IntegerField(verbose_name="远程调用Apdex")),
                ("apdex_backend", models.IntegerField(verbose_name="后台服务Apdex")),
                ("apdex_messaging", models.IntegerField(verbose_name="消息队列Apdex")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UriServiceRelation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.BigIntegerField(verbose_name="业务ID")),
                ("app_name", models.CharField(max_length=50, verbose_name="应用名称")),
                ("service_name", models.CharField(max_length=512, verbose_name="服务名称")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("uri", models.CharField(max_length=512, verbose_name="Uri")),
                ("rank", models.IntegerField(verbose_name="排序")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterIndexTogether(
            name="uriservicerelation",
            index_together={("bk_biz_id", "app_name", "service_name")},
        ),
        migrations.AlterIndexTogether(
            name="apdexservicerelation",
            index_together={("bk_biz_id", "app_name", "service_name")},
        ),
    ]
