# Generated by Django 3.2.15 on 2023-09-19 07:15

import bkmonitor.utils.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apm_web', '0015_tracecomparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='plugin_config',
            field=bkmonitor.utils.db.fields.JsonField(blank=True, null=True, verbose_name='log-trace 插件配置'),
        ),
    ]
