# Generated by Django 3.2.15 on 2023-11-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apm_web', '0016_application_plugin_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUploadRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_biz_id', models.BigIntegerField(verbose_name='业务ID')),
                ('app_name', models.CharField(max_length=50, verbose_name='应用名称')),
                (
                    'file_type',
                    models.CharField(
                        choices=[('perf_script', 'perf_script'), ('pprof', 'pprof'), ('jfr', 'jfr')],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ('file_md5', models.CharField(db_index=True, max_length=32, verbose_name='文件MD5')),
                ('profile_id', models.CharField(max_length=128, verbose_name='profile ID')),
                ('operator', models.CharField(max_length=128, verbose_name='操作人')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
        ),
    ]
