# Generated by Django 3.2.15 on 2023-12-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apm_web', '0017_profileuploadrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuploadrecord',
            name='app_name',
            field=models.CharField(max_length=50, null=True, verbose_name='应用名称'),
        ),
        migrations.AddField(
            model_name="profileuploadrecord",
            name="file_name",
            field=models.CharField(default="", max_length=50, verbose_name="新文件名称"),
        ),
        migrations.AddField(
            model_name="profileuploadrecord",
            name="file_size",
            field=models.BigIntegerField(default=0, verbose_name="文件大小"),
        ),
        migrations.AddField(
            model_name="profileuploadrecord",
            name="origin_file_name",
            field=models.CharField(default="", max_length=255, verbose_name="上传文件名称"),
        ),
        migrations.AddField(
            model_name="profileuploadrecord",
            name="service_name",
            field=models.CharField(default="default", max_length=50, verbose_name="服务名称"),
        ),
        migrations.AddField(
            model_name="profileuploadrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "已上传"),
                    ("parsing_failed", "解析失败"),
                    ("parsing_succeed", "解析成功"),
                ],
                default="unknown",
                max_length=36,
                verbose_name="状态",
            ),
        ),
    ]
