# Generated by Django 3.2.15 on 2024-01-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0017_profileuploadrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileuploadrecord",
            name="file_name",
            field=models.CharField(default="", max_length=50, verbose_name="新文件名称"),
        ),
        migrations.AddField(
            model_name="profileuploadrecord",
            name="file_size",
            field=models.BigIntegerField(default=0, verbose_name="文件大小"),
        ),
        migrations.AddField(
            model_name="profileuploadrecord",
            name="origin_file_name",
            field=models.CharField(default="", max_length=255, verbose_name="上传文件名称"),
        ),
        migrations.AddField(
            model_name="profileuploadrecord",
            name="service_name",
            field=models.CharField(default="default", max_length=50, verbose_name="服务名称"),
        ),
        migrations.AddField(
            model_name="profileuploadrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "uploaded"),
                    ("parsing_failed", "parsing_failed"),
                    ("parsing_succeed", "parsing_succeed"),
                ],
                default="unknown",
                max_length=36,
                verbose_name="状态",
            ),
        ),
    ]
