# Generated by Django 3.2.15 on 2024-01-15 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0018_alter_profileuploadrecord_app_name"),
        ("apm_web", "0018_auto_20240109_1013"),
    ]

    operations = []
