# Generated by Django 3.2.15 on 2024-05-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0019_auto_20240312_1750"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileuploadrecord",
            name="data_time",
            field=models.DateTimeField(null=True, verbose_name="文件数据时间"),
        ),
    ]
