# Generated by Django 3.2.15 on 2024-01-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0019_merge_20240115_2145"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="profiling_data_status",
            field=models.CharField(default="no_data", max_length=50, verbose_name="Profiling 数据状态"),
        ),
        migrations.AlterField(
            model_name="profileuploadrecord",
            name="status",
            field=models.CharField(
                choices=[("uploaded", "已上传"), ("parsing_failed", "解析失败"), ("parsing_succeed", "解析成功")],
                default="uploaded",
                max_length=36,
                verbose_name="状态",
            ),
        ),
    ]
