# Generated by Django 3.2.15 on 2024-01-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0020_auto_20240115_2145"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="is_enabled_profiling",
            field=models.BooleanField(default=False, verbose_name="是否开启 Profiling 功能"),
        ),
    ]
