# Generated by Django 3.2.15 on 2024-03-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0020_add_profile_upload_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileuploadrecord",
            name="file_type",
            field=models.CharField(
                choices=[("perf_script", "perf_script"), ("pprof", "pprof"), ("jfr", "jfr")],
                db_index=True,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profileuploadrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "已上传"),
                    ("parsing_failed", "解析失败"),
                    ("parsing_succeed", "已解析"),
                    ("store_succeed", "已存储"),
                    ("store_failed", "存储失败"),
                ],
                default="uploaded",
                max_length=36,
                verbose_name="状态",
            ),
        ),
    ]
