# Generated by Django 3.2.15 on 2024-01-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0021_auto_20240118_1600"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileuploadrecord",
            name="meta_info",
            field=models.JSONField(default=dict, verbose_name="数据元信息"),
        ),
        migrations.AlterField(
            model_name="profileuploadrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "已上传"),
                    ("parsing_failed", "解析失败"),
                    ("parsing_succeed", "已解析"),
                    ("store_succeed", "已存储"),
                    ("store_failed", "存储失败"),
                ],
                default="uploaded",
                max_length=36,
                verbose_name="状态",
            ),
        ),
    ]
