# Generated by Django 3.2.15 on 2024-09-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0021_uservisitrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="is_enabled_log",
            field=models.BooleanField(default=False, verbose_name="是否开启 Log 功能"),
        ),
        migrations.AddField(
            model_name="application",
            name="is_enabled_metric",
            field=models.BooleanField(default=True, verbose_name="是否开启 Metric 功能"),
        ),
        migrations.AddField(
            model_name="application",
            name="log_data_status",
            field=models.CharField(default="disabled", max_length=50, verbose_name="Log 数据状态"),
        ),
        migrations.AddField(
            model_name="application",
            name="metric_data_status",
            field=models.CharField(default="no_data", max_length=50, verbose_name="Metric 数据状态"),
        ),
        migrations.AlterField(
            model_name="application",
            name="profiling_data_status",
            field=models.CharField(default="disabled", max_length=50, verbose_name="Profiling 数据状态"),
        ),
    ]
