# Generated by Django 3.2.15 on 2024-09-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apm_web", "0022_auto_20240924_2126"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="data_status",
            new_name="trace_data_status",
        ),
        migrations.AddField(
            model_name="application",
            name="is_enabled_trace",
            field=models.BooleanField(default=True, verbose_name="是否开启 Trace 功能"),
        ),
    ]
