# Generated by Django 3.2.15 on 2024-03-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0022_auto_20240123_1839"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileuploadrecord",
            name="content",
            field=models.TextField(null=True, verbose_name="运行信息"),
        ),
        migrations.AddField(
            model_name="profileuploadrecord",
            name="file_key",
            field=models.CharField(default=None, max_length=1024, verbose_name="文件存储路径"),
            preserve_default=False,
        ),
    ]
