# Generated by Django 3.2.15 on 2024-03-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0023_auto_20240305_1555"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileuploadrecord",
            name="query_end_time",
            field=models.IntegerField(default=None, verbose_name="查询此文件的 profile 数据时的结束时间"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profileuploadrecord",
            name="query_start_time",
            field=models.IntegerField(default=None, verbose_name="查询此文件的 profile 数据时的开始时间"),
            preserve_default=False,
        ),
    ]
