# Generated by Django 3.2.15 on 2024-10-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apm_web", "0024_alter_apmmetaconfig_level_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="service_count",
            field=models.IntegerField(default=0, verbose_name="服务个数"),
        ),
    ]
