# Generated by Django 3.2.15 on 2024-11-11 13:10

from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("apm_web", "0025_application_service_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeRedefinedConfigRelation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.BigIntegerField(verbose_name="业务ID")),
                ("app_name", models.CharField(max_length=50, verbose_name="应用名称")),
                ("service_name", models.CharField(max_length=512, verbose_name="服务名称")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("created_by", models.CharField(max_length=128, null=True, verbose_name="创建人")),
                ("updated_by", models.CharField(max_length=128, null=True, verbose_name="更新人")),
                ("ret_code_as_exception", models.BooleanField(default=False, verbose_name="非 0 返回码是否当成异常")),
                ("rules", bkmonitor.utils.db.fields.JsonField(blank=True, null=True, verbose_name="匹配规则")),
            ],
            options={
                "abstract": False,
                "index_together": {("bk_biz_id", "app_name", "service_name")},
            },
        ),
    ]
