# Generated by Django 3.2.15 on 2025-01-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0026_coderedefinedconfigrelation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="bk_biz_id",
            field=models.IntegerField(db_index=True, verbose_name="业务id"),
        ),
        migrations.AlterField(
            model_name="applicationrelationinfo",
            name="application_id",
            field=models.IntegerField(db_index=True, verbose_name="应用Id"),
        ),
        migrations.AlterField(
            model_name="applicationrelationinfo",
            name="relation_key",
            field=models.CharField(db_index=True, max_length=255, verbose_name="关联Key"),
        ),
        migrations.AlterIndexTogether(
            name="application",
            index_together={("bk_biz_id", "app_name"), ("update_time", "application_id")},
        ),
        migrations.AlterIndexTogether(
            name="applicationcustomservice",
            index_together={("bk_biz_id", "app_name")},
        ),
        migrations.AlterIndexTogether(
            name="applicationrelationinfo",
            index_together={("application_id", "relation_key")},
        ),
    ]
