# Generated by Django 3.2.25 on 2025-03-17 01:39

from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('apm_web', '0027_auto_20250123_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceDefaultConfigTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_user', models.CharField(blank=True, default='', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(blank=True, default='', max_length=32, verbose_name='最后修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='配置名称')),
                ('bk_biz_id', models.IntegerField(blank=True, null=True, verbose_name='业务id')),
                ('app_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='应用名称')),
                ('trace_config', bkmonitor.utils.db.fields.JsonField(default=dict, verbose_name='trace 配置')),
                ('span_config', bkmonitor.utils.db.fields.JsonField(default=dict, verbose_name='span 配置')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TraceUserAppDefaultConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_user', models.CharField(blank=True, default='', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(blank=True, default='', max_length=32, verbose_name='最后修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('bk_biz_id', models.IntegerField(verbose_name='业务id')),
                ('app_name', models.CharField(max_length=50, verbose_name='应用名称')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('config_template_id', models.IntegerField(default=0, verbose_name='配置模板ID')),
            ],
            options={
                'unique_together': {('bk_biz_id', 'app_name', 'username')},
            },
        ),
        migrations.CreateModel(
            name='TraceUserAppCustomConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_user', models.CharField(blank=True, default='', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(blank=True, default='', max_length=32, verbose_name='最后修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('bk_biz_id', models.IntegerField(verbose_name='业务id')),
                ('app_name', models.CharField(max_length=50, verbose_name='应用名称')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('trace_config', bkmonitor.utils.db.fields.JsonField(default=dict, verbose_name='trace 自定义配置')),
                ('span_config', bkmonitor.utils.db.fields.JsonField(default=dict, verbose_name='span 自定义配置')),
            ],
            options={
                'unique_together': {('bk_biz_id', 'app_name', 'username')},
            },
        ),
    ]
