# Generated by Django 3.2.25 on 2025-04-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apm_web', '0028_eventservicerelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=64, verbose_name='租户ID'),
        ),
        migrations.AlterField(
            model_name='apmmetaconfig',
            name='level_key',
            field=models.CharField(max_length=512, verbose_name='配置目标key'),
        ),
        migrations.AlterField(
            model_name='eventservicerelation',
            name='options',
            field=models.JSONField(default=dict, verbose_name='事件选项'),
        ),
        migrations.AlterField(
            model_name='eventservicerelation',
            name='relations',
            field=models.JSONField(default=list, verbose_name='匹配规则'),
        ),
    ]
