# Generated by Django 3.2.25 on 2025-08-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0029_auto_20250418_1123"),
    ]

    operations = [
        migrations.AddField(
            model_name="logservicerelation",
            name="value_list",
            field=models.JSONField(default=list, verbose_name="日志值列表"),
        ),
    ]
