# Generated by Django 3.2.25 on 2025-08-28 08:06

from django.db import migrations, models

def migrate_value_to_value_list(apps, schema_editor):
    LogServiceRelation = apps.get_model('apm_web', 'LogServiceRelation')
    for record in LogServiceRelation.objects.filter(log_type='bk_log'):
        if record.value and record.value not in record.value_list:
            record.value_list.append(record.value)
            record.save()

class Migration(migrations.Migration):

    dependencies = [
        ('apm_web', '0029_auto_20250418_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='logservicerelation',
            name='value_list',
            field=models.JSONField(default=list, verbose_name='日志值列表'),
        ),
        migrations.RunPython(migrate_value_to_value_list),
    ]
