# Generated by Django 3.2.25 on 2025-08-29 10:06

from django.db import migrations


def migrate_value_to_value_list(apps, schema_editor):
    LogServiceRelation = apps.get_model("apm_web", "LogServiceRelation")
    for record in LogServiceRelation.objects.filter(log_type="bk_log"):
        if record.value and int(record.value) not in record.value_list:
            record.value_list.append(int(record.value))
            record.save()


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0030_logservicerelation_value_list"),
    ]

    operations = [migrations.RunPython(migrate_value_to_value_list)]
