# Generated by Django 3.2.25 on 2025-08-29 10:06

from django.db import migrations


def migrate_value_to_value_list(apps, schema_editor):
    LogServiceRelation = apps.get_model("apm_web", "LogServiceRelation")
    for record in LogServiceRelation.objects.filter(log_type="bk_log"):
        if not record.value:
            continue

        try:
            index_set_id = int(record.value)
            if index_set_id not in record.value_list:
                record.value_list = [index_set_id]
                record.save()
        except ValueError:  # ignore value error, if value is string, not number
            continue


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0030_logservicerelation_value_list"),
    ]

    operations = [migrations.RunPython(migrate_value_to_value_list)]
