# Generated by Django 3.2.25 on 2025-09-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0031_logservicerelation_value_to_value_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="coderedefinedconfigrelation",
            name="callee_method",
            field=models.CharField(blank=True, default="", max_length=512, verbose_name="被调接口"),
        ),
        migrations.AddField(
            model_name="coderedefinedconfigrelation",
            name="callee_server",
            field=models.CharField(blank=True, default="", max_length=512, verbose_name="被调服务"),
        ),
        migrations.AddField(
            model_name="coderedefinedconfigrelation",
            name="callee_service",
            field=models.CharField(blank=True, default="", max_length=512, verbose_name="被调Service"),
        ),
        migrations.AddField(
            model_name="coderedefinedconfigrelation",
            name="code_type_rules",
            field=models.JSONField(default=dict, verbose_name="重定义返回码分组信息"),
        ),
        migrations.AddField(
            model_name="coderedefinedconfigrelation",
            name="enabled",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AddField(
            model_name="coderedefinedconfigrelation",
            name="kind",
            field=models.CharField(
                choices=[("caller", "主调"), ("callee", "被调")], default="caller", max_length=16, verbose_name="类型"
            ),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name="coderedefinedconfigrelation",
            index_together={("bk_biz_id", "app_name", "service_name", "kind")},
        ),
        migrations.RemoveField(
            model_name="coderedefinedconfigrelation",
            name="rules",
        ),
    ]
