# Generated by Django 3.2.25 on 2025-09-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0032_auto_20250903_1533"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyTemplate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="最后修改人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="最后修改时间")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务 ID")),
                ("app_name", models.CharField(db_index=True, max_length=50, verbose_name="应用名称")),
                ("code", models.CharField(max_length=128, verbose_name="模板代号")),
                ("name", models.CharField(db_index=True, max_length=128, verbose_name="模板名称")),
                ("type", models.CharField(default="app", max_length=32, verbose_name="模板类型")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("is_auto_apply", models.BooleanField(default=False, verbose_name="是否自动下发到新服务")),
                ("root_id", models.IntegerField(db_index=True, default=0, verbose_name="根模板 ID")),
                ("parent_id", models.IntegerField(db_index=True, default=0, verbose_name="父模板 ID")),
                ("system", models.CharField(db_index=True, max_length=64, verbose_name="模板类型")),
                (
                    "category",
                    models.CharField(db_index=True, default="DEFAULT", max_length=64, verbose_name="模板分类"),
                ),
                ("monitor_type", models.CharField(default="DEFAULT", max_length=64, verbose_name="监控类型")),
                ("detect", models.JSONField(default=list, verbose_name="触发条件")),
                ("algorithms", models.JSONField(default=list, verbose_name="检测算法")),
                ("user_group_ids", models.JSONField(default=list, verbose_name="告警用户组 ID")),
                ("query_template", models.JSONField(default=dict, verbose_name="查询模板")),
                ("context", models.JSONField(default=dict, verbose_name="策略模板上下文")),
            ],
            options={
                "verbose_name": "告警策略模板",
                "verbose_name_plural": "告警策略模板",
                "index_together": {("bk_biz_id", "app_name", "type")},
            },
        ),
        migrations.CreateModel(
            name="StrategyInstance",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务 ID")),
                ("app_name", models.CharField(db_index=True, max_length=50, verbose_name="应用名称")),
                ("service_name", models.CharField(db_index=True, max_length=512, verbose_name="服务名称")),
                ("strategy_id", models.IntegerField(db_index=True, verbose_name="策略实例 ID")),
                ("md5", models.CharField(db_index=True, default="", max_length=32, verbose_name="策略实例 MD5")),
                ("strategy_template_id", models.IntegerField(db_index=True, verbose_name="策略模板 ID")),
                ("root_strategy_template_id", models.IntegerField(db_index=True, default=0, verbose_name="根模板 ID")),
                ("detect", models.JSONField(default=list, verbose_name="触发条件")),
                ("algorithms", models.JSONField(default=list, verbose_name="检测算法")),
                ("user_group_ids", models.JSONField(default=list, verbose_name="告警用户组 ID")),
                ("context", models.JSONField(default=dict, verbose_name="策略模板上下文")),
            ],
            options={
                "verbose_name": "告警策略实例",
                "verbose_name_plural": "告警策略模板",
                "unique_together": {("bk_biz_id", "app_name", "service_name", "strategy_template_id")},
                "index_together": {("bk_biz_id", "app_name", "service_name")},
            },
        ),
    ]
