# Generated by Django 3.2.25 on 2025-09-20 02:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0032_auto_20250903_1533"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coderedefinedconfigrelation",
            name="ret_code_as_exception",
        ),
    ]
