# Generated by Django 3.2.25 on 2025-09-23 14:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0033_remove_coderedefinedconfigrelation_ret_code_as_exception"),
        ("apm_web", "0033_strategyinstance_strategytemplate"),
    ]

    operations = []
