# Generated by Django 3.2.25 on 2025-10-01 09:26

import bkmonitor.utils.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0033_remove_coderedefinedconfigrelation_ret_code_as_exception"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricCustomGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
                ("app_name", models.CharField(max_length=50, verbose_name="应用名称")),
                ("service_name", models.CharField(max_length=2048, verbose_name="服务名称")),
                ("name", models.CharField(max_length=128, verbose_name="分组名称")),
                ("manual_list", bkmonitor.utils.db.fields.JsonField(default=[], verbose_name="手动分组的指标列表")),
                ("auto_rules", bkmonitor.utils.db.fields.JsonField(default=[], verbose_name="自动分组的匹配规则列表")),
            ],
        ),
        migrations.CreateModel(
            name="MetricField",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
                ("app_name", models.CharField(max_length=50, verbose_name="应用名称")),
                ("service_name", models.CharField(max_length=255, verbose_name="服务名称")),
                ("scope_name", models.CharField(default="default", max_length=2048, verbose_name="监控项分组名称")),
                (
                    "type",
                    models.CharField(
                        choices=[("metric", "指标"), ("dimension", "维度")],
                        default="metric",
                        max_length=16,
                        verbose_name="字段类型",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="字段名称")),
                ("alias", models.CharField(default="", max_length=128, verbose_name="字段别名")),
                ("is_disabled", models.BooleanField(default=False, verbose_name="是否禁用")),
                ("config", models.JSONField(default=dict, verbose_name="字段配置")),
            ],
        ),
    ]
