# Generated by Django 3.2.25 on 2025-10-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0034_merge_20250923_2238"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategytemplate",
            name="auto_applied_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最后一次自动下发时间"),
        ),
    ]
