# Generated by Django 3.2.25 on 2025-10-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0034_metriccustomgroup_metricfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="metriccustomgroup",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="创建时间"),
        ),
        migrations.AddField(
            model_name="metriccustomgroup",
            name="order",
            field=models.IntegerField(default=0, verbose_name="分组顺序"),
        ),
        migrations.AddField(
            model_name="metriccustomgroup",
            name="update_time",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
        ),
        migrations.AddField(
            model_name="metricfield",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="创建时间"),
        ),
        migrations.AddField(
            model_name="metricfield",
            name="update_time",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
        ),
    ]
