# Generated by Django 4.2.27 on 2026-03-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0035_strategytemplate_auto_applied_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="strategyinstance",
            options={"verbose_name": "告警策略实例", "verbose_name_plural": "告警策略实例"},
        ),
        migrations.AddField(
            model_name="apdexservicerelation",
            name="is_global",
            field=models.BooleanField(default=False, verbose_name="是否为全局配置"),
        ),
        migrations.AddField(
            model_name="appservicerelation",
            name="is_global",
            field=models.BooleanField(default=False, verbose_name="是否为全局配置"),
        ),
        migrations.AddField(
            model_name="cmdbservicerelation",
            name="is_global",
            field=models.BooleanField(default=False, verbose_name="是否为全局配置"),
        ),
        migrations.AddField(
            model_name="coderedefinedconfigrelation",
            name="is_global",
            field=models.BooleanField(default=False, verbose_name="是否为全局配置"),
        ),
        migrations.AddField(
            model_name="eventservicerelation",
            name="is_global",
            field=models.BooleanField(default=False, verbose_name="是否为全局配置"),
        ),
        migrations.AddField(
            model_name="logservicerelation",
            name="is_global",
            field=models.BooleanField(default=False, verbose_name="是否为全局配置"),
        ),
        migrations.AddField(
            model_name="uriservicerelation",
            name="is_global",
            field=models.BooleanField(default=False, verbose_name="是否为全局配置"),
        ),
    ]
