# Generated by Django 4.2.27 on 2026-05-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apm_web", "0036_add_is_global_to_servicebase"),
    ]

    operations = [
        migrations.AddField(
            model_name="logservicerelation",
            name="addition",
            field=models.JSONField(default=list, verbose_name="额外过滤信息"),
        ),
    ]
