# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2020-03-30 03:02


from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0082_create_first_uptimecheck_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentimporttask",
            name="process",
            field=models.CharField(
                choices=[
                    ("READY", "任务就绪"),
                    ("UNZIP_FILE", "解压文件"),
                    ("CHECK_COMPONENT_NAME", "校验组件名称"),
                    ("CHECK_COMPONENT_DESC", "校验组件描述"),
                    ("CHECK_INDEX_FILE", "校验指标项文件"),
                    ("CHECK_CONFIG_FILE", "校验配置项文件"),
                    ("PROCESS_LOGO", "读取并压缩LOGO"),
                    ("CHECK_EXPORTER_FILE", "校验二进制exporter"),
                    ("SAVE_COMPONENT", "保存组件配置"),
                    ("FINISHED", "任务流程完成"),
                ],
                default="READY",
                max_length=50,
                verbose_name="任务当前流程",
            ),
        ),
        migrations.AlterField(
            model_name="componentimporttask",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "任务创建成功"),
                    ("RUNNING", "任务正在执行"),
                    ("SUCCESS", "任务执行成功"),
                    ("EXCEPTION", "任务执行过程异常"),
                ],
                default="CREATED",
                max_length=50,
                verbose_name="任务状态",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardmenu",
            name="name",
            field=models.CharField(default="", max_length=32, verbose_name="仪表盘名称"),
        ),
        migrations.AlterField(
            model_name="dashboardview",
            name="graph_type",
            field=models.CharField(
                choices=[("time", "时间序列"), ("top", "TOP排行"), ("status", "状态值")], max_length=32, verbose_name="图表类型"
            ),
        ),
        migrations.AlterField(
            model_name="dashboardview",
            name="name",
            field=models.CharField(default="", max_length=128, verbose_name="视图名称"),
        ),
        migrations.AlterField(
            model_name="datagenerateconfig",
            name="bksql",
            field=models.TextField(default="", verbose_name="bksql描述"),
        ),
        migrations.AlterField(
            model_name="datagenerateconfig",
            name="status",
            field=models.CharField(
                choices=[("starting", "启动中"), ("running", "正在运行"), ("stopping", "停止中"), ("not running", "未启动")],
                default="starting",
                max_length=16,
                verbose_name="作业状态",
            ),
        ),
        migrations.AlterField(
            model_name="exportercomponent",
            name="charset",
            field=models.CharField(
                choices=[("UTF8", "UTF8"), ("GBK", "GBK")], default="UTF8", max_length=20, verbose_name="字符集"
            ),
        ),
        migrations.AlterField(
            model_name="exportercomponent",
            name="component_desc",
            field=models.TextField(blank=True, default="", verbose_name="组件详细描述(md)"),
        ),
        migrations.AlterField(
            model_name="exportercomponent",
            name="logo",
            field=models.TextField(blank=True, default="", verbose_name="logo的base64编码"),
        ),
        migrations.AlterField(
            model_name="exportercomponent",
            name="logo_small",
            field=models.TextField(blank=True, default="", verbose_name="小logo的base64编码"),
        ),
        migrations.AlterField(
            model_name="exportercomponent",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "未保存"), ("SAVED", "已保存")], default="DRAFT", max_length=20, verbose_name="当前状态"
            ),
        ),
        migrations.AlterField(
            model_name="exportercomponent",
            name="version",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="组件版本号（仅限内置组件）"),
        ),
        migrations.AlterField(
            model_name="exporterdeposittask",
            name="charset",
            field=models.CharField(
                choices=[("UTF8", "UTF8"), ("GBK", "GBK")], default="UTF8", max_length=20, verbose_name="字符集"
            ),
        ),
        migrations.AlterField(
            model_name="exporterdeposittask",
            name="component_desc",
            field=models.TextField(blank=True, default="", verbose_name="组件详细描述(md)"),
        ),
        migrations.AlterField(
            model_name="exporterdeposittask",
            name="logo",
            field=models.TextField(blank=True, default="", verbose_name="logo的base64编码"),
        ),
        migrations.AlterField(
            model_name="exporterdeposittask",
            name="logo_small",
            field=models.TextField(blank=True, default="", verbose_name="小logo的base64编码"),
        ),
        migrations.AlterField(
            model_name="exporterdeposittask",
            name="process",
            field=models.CharField(
                choices=[
                    ("READY", "任务就绪"),
                    ("CREATE_RT", "检查并创建结果表"),
                    ("CREATE_DATASET", "检查并创建DataSet"),
                    ("SET_ETL_TEMPLATE", "检查并生成清洗配置"),
                    ("DEPLOY_TSDB", "检查并创建TSDB"),
                    ("START_DISPATCH", "启动入库程序"),
                    ("START_DEPOSIT_TASK", "正在托管exporter"),
                    ("STOP_OLD_DEPOSIT_TASK", "取消老版本配置的IP托管"),
                    ("FINISHED", "任务流程完成"),
                ],
                default="READY",
                max_length=50,
                verbose_name="任务当前流程",
            ),
        ),
        migrations.AlterField(
            model_name="exporterdeposittask",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "任务创建成功"),
                    ("RUNNING", "任务正在执行"),
                    ("SUCCESS", "任务执行成功"),
                    ("FAILED", "任务执行失败"),
                    ("EXCEPTION", "任务执行过程异常"),
                ],
                default="CREATED",
                max_length=50,
                verbose_name="任务状态",
            ),
        ),
        migrations.AlterField(
            model_name="logcollector",
            name="data_id",
            field=models.CharField(default="", max_length=100, verbose_name="数据源ID"),
        ),
        migrations.AlterField(
            model_name="logcollector",
            name="result_table_id",
            field=models.CharField(default="", max_length=100, verbose_name="结果表ID"),
        ),
        migrations.AlterField(
            model_name="logcollectorhost",
            name="status",
            field=models.CharField(
                choices=[("create", "启用中"), ("normal", "正常"), ("stop", "停用中"), ("stopped", "停用"), ("exception", "异常")],
                default="create",
                max_length=20,
                verbose_name="数据上报状态",
            ),
        ),
        migrations.AlterField(
            model_name="metricconf",
            name="conversion_unit",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="转换单位"),
        ),
        migrations.AlterField(
            model_name="operaterecord",
            name="config_title",
            field=models.CharField(default="", max_length=512, verbose_name="配置标题"),
        ),
        migrations.AlterField(
            model_name="operaterecord",
            name="data_ori",
            field=models.TextField(default="{}", verbose_name="修改前数据(JSON)"),
        ),
        migrations.AlterField(
            model_name="operaterecord",
            name="operate_desc",
            field=models.TextField(default="", verbose_name="操作说明"),
        ),
        migrations.AlterField(
            model_name="operaterecord",
            name="operator_name",
            field=models.CharField(default="", max_length=32, verbose_name="操作人昵称"),
        ),
        migrations.AlterField(
            model_name="scenariomenu",
            name="system_menu",
            field=models.CharField(
                blank=True,
                choices=[("", "用户自定义"), ("favorite", "关注"), ("default", "默认分组")],
                default="",
                max_length=32,
                verbose_name="系统菜单栏",
            ),
        ),
        migrations.AlterField(
            model_name="scriptcollectorconfig",
            name="charset",
            field=models.CharField(choices=[("UTF8", "UTF8"), ("GBK", "GBK")], max_length=20, verbose_name="字符集"),
        ),
        migrations.AlterField(
            model_name="scriptcollectorconfig",
            name="script_ext",
            field=models.CharField(
                choices=[
                    ("shell", "shell"),
                    ("bat", "bat"),
                    ("python", "python"),
                    ("perl", "perl"),
                    ("powershell", "powershell"),
                    ("vbs", "vbs"),
                    ("custom", "自定义"),
                ],
                default="shell",
                max_length=20,
                verbose_name="脚本格式",
            ),
        ),
        migrations.AlterField(
            model_name="scriptcollectorconfig",
            name="script_type",
            field=models.CharField(
                choices=[("file", "脚本"), ("cmd", "命令行")], default="file", max_length=20, verbose_name="脚本类型"
            ),
        ),
        migrations.AlterField(
            model_name="scriptcollectorconfig",
            name="status",
            field=models.CharField(
                choices=[("draft", "新建未保存"), ("saved", "已保存")], default="draft", max_length=20, verbose_name="当前状态"
            ),
        ),
        migrations.AlterField(
            model_name="scriptcollectorinstance",
            name="type",
            field=models.CharField(
                choices=[("host", "主机"), ("topo", "拓扑")], default="host", max_length=20, verbose_name="实例类型"
            ),
        ),
        migrations.AlterField(
            model_name="serviceauthorization",
            name="service_type",
            field=models.CharField(choices=[("charts", "图表")], max_length=30, verbose_name="服务类型"),
        ),
        migrations.AlterField(
            model_name="shellcollectorconfig",
            name="charset",
            field=models.CharField(choices=[("UTF8", "UTF8"), ("GBK", "GBK")], max_length=20, verbose_name="字符集"),
        ),
        migrations.AlterField(
            model_name="shellcollectorconfig",
            name="status",
            field=models.CharField(
                choices=[("new draft", "新建未保存"), ("edit draft", "编辑未保存"), ("saved", "已保存"), ("delete failed", "删除失败")],
                default="new draft",
                max_length=20,
                verbose_name="当前状态",
            ),
        ),
        migrations.AlterField(
            model_name="shellcollectordeposittask",
            name="charset",
            field=models.CharField(choices=[("UTF8", "UTF8"), ("GBK", "GBK")], max_length=20, verbose_name="字符集"),
        ),
        migrations.AlterField(
            model_name="shellcollectordeposittask",
            name="process",
            field=models.CharField(
                choices=[
                    ("ready", "任务就绪"),
                    ("create rt", "检查并创建结果表"),
                    ("create dataset", "检查并创建DataSet"),
                    ("set etl template", "检查并生成清洗配置"),
                    ("deploy_tsdb", "检查并创建TSDB"),
                    ("start dispatch", "启动入库程序"),
                    ("start deposit task", "创建脚本托管任务"),
                    ("stop old deposit task", "取消老版本配置的IP托管"),
                    ("finished", "任务流程完成"),
                ],
                default="ready",
                max_length=50,
                verbose_name="任务当前流程",
            ),
        ),
        migrations.AlterField(
            model_name="shellcollectordeposittask",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "任务创建成功"),
                    ("running", "任务正在执行"),
                    ("success", "任务执行成功"),
                    ("failed", "任务执行失败"),
                    ("exception", "任务执行过程异常"),
                ],
                default="created",
                max_length=50,
                verbose_name="任务状态",
            ),
        ),
        migrations.AlterField(
            model_name="uptimecheckgroup",
            name="logo",
            field=models.TextField(blank=True, default="", verbose_name="图片base64形式"),
        ),
        migrations.AlterField(
            model_name="uptimechecknode",
            name="carrieroperator",
            field=models.CharField(blank=True, default="", max_length=50, null=True, verbose_name="外网运营商"),
        ),
        migrations.AlterField(
            model_name="uptimechecknode",
            name="location",
            field=bkmonitor.utils.db.fields.JsonField(default="{}", verbose_name="地区"),
        ),
        migrations.AlterField(
            model_name="uptimechecktask",
            name="location",
            field=bkmonitor.utils.db.fields.JsonField(default="{}", verbose_name="地区"),
        ),
        migrations.AlterField(
            model_name="uptimechecktask",
            name="protocol",
            field=models.CharField(
                choices=[("TCP", "TCP"), ("UDP", "UDP"), ("HTTP", "HTTP(S)")], max_length=10, verbose_name="协议"
            ),
        ),
        migrations.AlterField(
            model_name="uptimechecktask",
            name="status",
            field=models.CharField(
                choices=[
                    ("new_draft", "未保存"),
                    ("running", "运行中"),
                    ("stoped", "未启用"),
                    ("starting", "启动中"),
                    ("stoping", "停止中"),
                    ("start_failed", "启动失败"),
                    ("stop_failed", "停止失败"),
                ],
                default="new_draft",
                max_length=20,
                verbose_name="当前状态",
            ),
        ),
    ]
