# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-02-22 09:02
from __future__ import unicode_literals

from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0095_update_uptimechecktask_udp_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='uptimechecknode',
            name='biz_scope',
            field=bkmonitor.utils.db.fields.JsonField(default=[], verbose_name='指定业务可见范围'),
        ),
        migrations.AddField(
            model_name='uptimechecknode',
            name='bk_host_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='主机ID'),
        ),
        migrations.AddField(
            model_name='uptimechecknode',
            name='ip_type',
            field=bkmonitor.utils.db.fields.JsonField(default=[], verbose_name='IP类型'),
        ),
    ]
