# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-02-24 02:20
from __future__ import unicode_literals

from django.db import migrations

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0096_auto_20230222_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uptimechecknode',
            name='ip_type',
            field=bkmonitor.utils.db.fields.JsonField(default=['IPv4'], verbose_name='IP类型'),
        ),
    ]
