# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-06 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0097_auto_20230224_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uptimechecknode',
            name='ip_type',
        ),
    ]
