# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-06 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0098_remove_uptimechecknode_ip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uptimechecknode',
            name='ip_type',
            field=models.IntegerField(choices=[(0, 'all'), (4, 'IPV4'), (6, 'IPV6')], default=4, verbose_name='IP类型'),
        ),
    ]
