# Generated by Django 3.2.15 on 2023-12-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0101_auto_20230613_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uptimechecknode',
            name='bk_biz_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='业务ID'),
        ),
        migrations.AlterField(
            model_name='uptimechecknode',
            name='is_common',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否为通用节点'),
        ),
        migrations.AlterField(
            model_name='uptimechecktask',
            name='bk_biz_id',
            field=models.IntegerField(db_index=True, verbose_name='业务ID'),
        ),
        migrations.AlterField(
            model_name='uptimechecktask',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='任务名称'),
        ),
        migrations.AlterIndexTogether(
            name='uptimechecknode',
            index_together={('name', 'bk_biz_id')},
        ),
    ]
