# Generated by Django 3.2.15 on 2024-04-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0102_auto_20231216_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uptimechecktask',
            name='name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='任务名称'),
        ),
    ]
