# Generated by Django 3.2.15 on 2024-10-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0103_alter_uptimechecktask_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uptimechecktask',
            name='indepentent_dataid',
            field=models.BooleanField(default=False, verbose_name='独立业务数据ID'),
        ),
        migrations.AddField(
            model_name='uptimechecktask',
            name='labels',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='自定义标签'),
        ),
    ]
