# Generated by Django 3.2.25 on 2025-04-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0104_auto_20241024_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='uptimechecknode',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=128, verbose_name='租户ID'),
        ),
    ]
