# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""


ALL_LABEL_MSG = [
    {
        "index": 1,
        "label_type": "result_table_label",
        "level": 1,
        "parent_label": None,
        "label_id": "applications",
        "label_name": "用户体验",
    },
    {
        "index": 2,
        "label_type": "result_table_label",
        "level": 2,
        "parent_label": "applications",
        "label_id": "application_check",
        "label_name": "业务应用",
    },
    {
        "index": 2,
        "label_type": "result_table_label",
        "level": 2,
        "parent_label": "services",
        "label_id": "component",
        "label_name": "组件",
    },
    {
        "index": 3,
        "label_type": "result_table_label",
        "level": 1,
        "parent_label": None,
        "label_id": "hosts",
        "label_name": "主机",
    },
    {
        "index": 1,
        "label_type": "result_table_label",
        "level": 2,
        "parent_label": "hosts",
        "label_id": "host_process",
        "label_name": "进程",
    },
    {
        "index": 2,
        "label_type": "result_table_label",
        "level": 2,
        "parent_label": "hosts",
        "label_id": "os",
        "label_name": "操作系统",
    },
    {
        "index": 4,
        "label_type": "result_table_label",
        "level": 1,
        "parent_label": None,
        "label_id": "others",
        "label_name": "其他",
    },
    {
        "index": 1,
        "label_type": "result_table_label",
        "level": 2,
        "parent_label": "others",
        "label_id": "other_rt",
        "label_name": "其他",
    },
    {
        "index": 2,
        "label_type": "result_table_label",
        "level": 1,
        "parent_label": None,
        "label_id": "services",
        "label_name": "服务",
    },
    {
        "index": 1,
        "label_type": "result_table_label",
        "level": 2,
        "parent_label": "services",
        "label_id": "service_module",
        "label_name": "服务模块",
    },
    {
        "index": 1,
        "label_type": "result_table_label",
        "level": 2,
        "parent_label": "applications",
        "label_id": "uptimecheck",
        "label_name": "服务拨测",
    },
]

HANDEL_LABEL_MSG = [
    {
        "index": 1,
        "name": "用户体验",
        "id": "applications",
        "children": [
            {"index": 2, "id": "application_check", "name": "业务应用"},
            {"index": 1, "id": "uptimecheck", "name": "服务拨测"},
        ],
    },
    {
        "index": 2,
        "name": "服务",
        "id": "services",
        "children": [
            {"index": 2, "id": "component", "name": "组件"},
            {"index": 1, "id": "service_module", "name": "服务模块"},
        ],
    },
    {
        "index": 3,
        "name": "主机",
        "id": "hosts",
        "children": [{"index": 1, "id": "host_process", "name": "进程"}, {"index": 2, "id": "os", "name": "操作系统"}],
    },
    {"index": 4, "name": "其他", "id": "others", "children": [{"index": 1, "id": "other_rt", "name": "其他"}]},
]

BASE_METRICS = [
    {
        "related_name": "test_host_exporter",
        "metric_field": "host_cpu_idle_percent",
        "related_id": "test_host_exporter",
        "metric_field_name": "CPU\\u7a7a\\u95f2\\u65f6\\u95f4\\u767e\\u5206\\u6bd4",
        "id": 292,
        "unit": "%",
        "dimensions": [
            {"id": "bk_biz_id", "name": "\\u4e1a\\u52a1ID"},
            {"id": "bk_cloud_id", "name": "\\u4e91\\u533a\\u57dfID"},
            {"id": "ip", "name": "\\u91c7\\u96c6\\u5668IP\\u5730\\u5740"},
            {"id": "bk_target_ip", "name": "\\u76ee\\u6807IP"},
            {"id": "bk_target_cloud_id", "name": "\\u76ee\\u6807\\u673a\\u5668\\u4e91\\u533a\\u57dfID"},
        ],
        "collect_config": "test_host_exporter_collect",
        "data_target": "host_target",
        "data_type_label": "time_series",
        "collect_config_ids": [31],
        "description": "",
        "unit_conversion": 1.0,
        "bk_biz_id": 0,
        "data_source_label": "bk_monitor",
        "result_table_id": "exporter_test_host_exporter.cpu",
        "default_condition": [],
        "result_table_name": "CPU\\u6027\\u80fd",
        "result_table_label": "os",
        "default_dimensions": ["bk_target_ip", "bk_target_cloud_id"],
        "plugin_type": "Exporter",
    }
]

UPTIMECHECK_METRICS = [
    {
        "related_name": "ping_baidu",
        "metric_field": "available",
        "related_id": "1",
        "method_list": ["AVG"],
        "metric_field_name": "单点可用率",
        "id": 386,
        "unit": "%",
        "dimensions": [{"id": "task_id", "name": "任务ID"}],
        "collect_config": "",
        "data_target": "none_target",
        "data_type_label": "time_series",
        "result_table_id": "uptimecheck.http",
        "collect_config_ids": "",
        "description": "",
        "unit_conversion": 0.01,
        "bk_biz_id": 2,
        "data_source_label": "bk_monitor",
        "default_condition": [{"key": "task_id", "value_name": "1（ping_baidu）", "method": "eq", "value": 1}],
        "result_table_name": "uptimecheck.http",
        "result_table_label": "uptimecheck",
        "default_dimensions": ["task_id"],
        "plugin_type": "",
    }
]

HOST_INFO = {
    "2": {
        1: {
            "agent_status": 0,
            "ip": "10.0.1.10",
            "plat_id": 0,
            "bk_cloud_id": 0,
            "module_ids": {
                6,
                9,
                12,
                13,
                14,
                15,
                17,
                18,
                19,
                21,
                22,
                23,
                25,
                26,
                28,
                29,
                42,
                43,
                45,
                46,
                47,
                48,
                49,
                50,
                52,
                55,
                56,
                57,
            },
        },
        2: {
            "agent_status": 2,
            "ip": "10.0.1.11",
            "plat_id": 0,
            "bk_cloud_id": 0,
            "module_ids": {5, 9, 10, 12, 13, 16, 17, 19, 21, 28},
        },
        3: {
            "agent_status": 0,
            "ip": "10.0.1.16",
            "plat_id": 0,
            "bk_cloud_id": 0,
            "module_ids": {32, 33, 34, 35, 36, 37, 38, 39, 40, 9, 10, 13, 14, 17, 19, 20, 21, 41, 31, 30, 5},
        },
        1025: {"agent_status": 0, "ip": "10.0.1.69", "plat_id": 0, "bk_cloud_id": 0, "module_ids": {6}},
        1022: {"agent_status": 0, "ip": "10.0.1.8", "plat_id": 0, "bk_cloud_id": 0, "module_ids": {11, 19, 21, 14}},
        1023: {"agent_status": 0, "ip": "10.0.1.4", "plat_id": 0, "bk_cloud_id": 0, "module_ids": {9, 10, 21}},
    }
}

SERVICE_INFO = {
    "2": {
        128: {"host_status": 2, "bk_module_id": 5, "name": "10.0.1.11_fta:solution"},
        1: {"host_status": 0, "bk_module_id": 18, "name": "mysql"},
        2: {"host_status": 0, "bk_module_id": 46, "name": "gse_ops"},
        3: {"host_status": 0, "bk_module_id": 33, "name": "adminserver"},
        4: {"host_status": 0, "bk_module_id": 41, "name": "toposerver"},
        5: {"host_status": 0, "bk_module_id": 50, "name": "gse_task"},
        6: {"host_status": 0, "bk_module_id": 57, "name": "gse_syncdata"},
        7: {"host_status": 0, "bk_module_id": 9, "name": "redis_cluster"},
        8: {"host_status": 2, "bk_module_id": 9, "name": "redis_cluster"},
        9: {"host_status": 0, "bk_module_id": 9, "name": "redis_cluster"},
        10: {"host_status": 0, "bk_module_id": 12, "name": "redis"},
        11: {"host_status": 0, "bk_module_id": 13, "name": "zookeeper"},
        12: {"host_status": 2, "bk_module_id": 13, "name": "zookeeper"},
        13: {"host_status": 0, "bk_module_id": 13, "name": "zookeeper"},
        14: {"host_status": 0, "bk_module_id": 52, "name": "gse_opts"},
        15: {"host_status": 0, "bk_module_id": 20, "name": "rabbitmq"},
        16: {"host_status": 0, "bk_module_id": 36, "name": "eventserver"},
        17: {"host_status": 0, "bk_module_id": 45, "name": "gse_btsvr"},
        18: {"host_status": 0, "bk_module_id": 55, "name": "gse_procmgr"},
        19: {"host_status": 0, "bk_module_id": 23, "name": "appo"},
        20: {"host_status": 0, "bk_module_id": 31, "name": "objectcontroller"},
        21: {"host_status": 0, "bk_module_id": 34, "name": "apiserver"},
        22: {"host_status": 0, "bk_module_id": 37, "name": "webserver"},
        23: {"host_status": 0, "bk_module_id": 39, "name": "hostcontroller"},
        24: {"host_status": 0, "bk_module_id": 47, "name": "gse_alarm"},
        25: {"host_status": 0, "bk_module_id": 40, "name": "procserver"},
        26: {"host_status": 0, "bk_module_id": 42, "name": "gse_api"},
        27: {"host_status": 0, "bk_module_id": 48, "name": "license"},
        28: {"host_status": 0, "bk_module_id": 15, "name": "nginx"},
        29: {"host_status": 0, "bk_module_id": 35, "name": "datacollection"},
        30: {"host_status": 0, "bk_module_id": 56, "name": "gse_dataop"},
        31: {"host_status": 0, "bk_module_id": 21, "name": "consul"},
        32: {"host_status": 2, "bk_module_id": 21, "name": "consul"},
        33: {"host_status": 0, "bk_module_id": 21, "name": "consul"},
        34: {"host_status": 0, "bk_module_id": 25, "name": "esb"},
        35: {"host_status": 0, "bk_module_id": 30, "name": "hostserver"},
        36: {"host_status": 0, "bk_module_id": 32, "name": "proccontroller"},
        37: {"host_status": 0, "bk_module_id": 43, "name": "gse_dba"},
        38: {"host_status": 0, "bk_module_id": 49, "name": "gse_data"},
        39: {"host_status": 0, "bk_module_id": 38, "name": "auditcontroller"},
        40: {"host_status": 0, "bk_module_id": 17, "name": "mongodb"},
        41: {"host_status": 2, "bk_module_id": 17, "name": "mongodb"},
        42: {"host_status": 0, "bk_module_id": 17, "name": "mongodb"},
        133: {"host_status": 0, "bk_module_id": 6, "name": "10.0.1.69_dataapi-celery"},
        130: {"host_status": 0, "bk_module_id": 10, "name": "10.0.1.16_tsdb-proxy_5261"},
        129: {"host_status": 0, "bk_module_id": 19, "name": "10.0.1.16_kafka-java_9092"},
        142: {"host_status": 0, "bk_module_id": 22, "name": "10.0.1.10_paas-console_8004"},
        131: {"host_status": 0, "bk_module_id": 14, "name": "10.0.1.16_es-java_9300,10004"},
        106: {"host_status": 0, "bk_module_id": 14, "name": "10.0.1.10_es-java_9300,10004"},
        107: {"host_status": 0, "bk_module_id": 29, "name": "10.0.1.10_asdf_"},
        108: {"host_status": 0, "bk_module_id": 29, "name": "10.0.1.10_asdf_"},
        111: {"host_status": 2, "bk_module_id": 28, "name": "10.0.1.11_paas-appengine_8000"},
        112: {"host_status": 0, "bk_module_id": 28, "name": "10.0.1.10_paas-appengine_8000"},
        113: {"host_status": 0, "bk_module_id": 26, "name": "10.0.1.10_paas-login_8003"},
        114: {"host_status": 0, "bk_module_id": 5, "name": "10.0.1.16_fta-common:webserver_13021"},
        116: {"host_status": 0, "bk_module_id": 6, "name": "10.0.1.10_dataapi-py_10011"},
        117: {"host_status": 0, "bk_module_id": 21, "name": "10.0.1.8_consul-agent_8301,8500,53"},
        118: {"host_status": 0, "bk_module_id": 14, "name": "10.0.1.8_es-java_9300,10004"},
        119: {"host_status": 0, "bk_module_id": 11, "name": "10.0.1.8_etcd_2379,2380"},
        120: {"host_status": 0, "bk_module_id": 19, "name": "10.0.1.8_kafka-java_9092"},
        121: {"host_status": 0, "bk_module_id": 21, "name": "10.0.1.4_consul-agent_8301,8500,53"},
        122: {"host_status": 0, "bk_module_id": 9, "name": "10.0.1.4_redis-sentinel_16379"},
        123: {"host_status": 0, "bk_module_id": 10, "name": "10.0.1.4_tsdb-proxy_5261"},
        124: {"host_status": 0, "bk_module_id": 19, "name": "10.0.1.10_kafka-java_9092"},
        125: {"host_status": 2, "bk_module_id": 19, "name": "10.0.1.11_kafka-java_9092"},
        126: {"host_status": 2, "bk_module_id": 16, "name": "10.0.1.11_beanstalkd_6380"},
        127: {"host_status": 2, "bk_module_id": 10, "name": "10.0.1.11_tsdb-proxy_5261"},
    }
}

MODULE_SERVICE_CATEGORY_INFO = {
    "2": {
        3: 10,
        4: 10,
        5: 10,
        6: 10,
        7: 10,
        8: 10,
        9: 10,
        10: 10,
        11: 10,
        12: 10,
        13: 10,
        14: 10,
        15: 10,
        16: 10,
        17: 10,
        18: 10,
        19: 10,
        20: 10,
        21: 10,
        22: 10,
        23: 10,
        24: 10,
        25: 10,
        26: 10,
        27: 10,
        28: 38,
        29: 10,
        30: 10,
        31: 10,
        32: 10,
        33: 10,
        34: 10,
        35: 10,
        36: 10,
        37: 10,
        38: 10,
        39: 10,
        40: 10,
        41: 10,
        42: 10,
        43: 10,
        44: 10,
        45: 10,
        46: 10,
        47: 10,
        48: 10,
        49: 10,
        50: 10,
        52: 10,
        54: 10,
        55: 10,
        56: 10,
        57: 10,
        58: 10,
        59: 10,
        60: 10,
        61: 10,
    }
}

TOPO_TREE_INFO = {
    "2": {
        "host_count": 0,
        "node_link": ["biz|2"],
        "default": 0,
        "bk_obj_name": "\u4e1a\u52a1",
        "bk_obj_id": "biz",
        "service_instance_count": 0,
        "child": [
            {
                "node_link": ["biz|2", "set|2"],
                "bk_obj_name": "\u96c6\u7fa4",
                "bk_obj_id": "set",
                "child": [
                    {
                        "node_link": ["biz|2", "set|2", "module|3"],
                        "bk_obj_name": "\u6a21\u5757",
                        "bk_obj_id": "module",
                        "child": [],
                        "bk_inst_id": 3,
                        "bk_inst_name": "\u7a7a\u95f2\u673a",
                    },
                    {
                        "node_link": ["biz|2", "set|2", "module|4"],
                        "bk_obj_name": "\u6a21\u5757",
                        "bk_obj_id": "module",
                        "child": [],
                        "bk_inst_id": 4,
                        "bk_inst_name": "\u6545\u969c\u673a",
                    },
                ],
                "bk_inst_id": 2,
                "bk_inst_name": "\u7a7a\u95f2\u673a\u6c60",
            },
            {
                "host_count": 0,
                "node_link": ["biz|2", "test|2"],
                "default": 0,
                "bk_obj_name": "test",
                "bk_obj_id": "test",
                "service_instance_count": 0,
                "child": [
                    {
                        "host_count": 0,
                        "node_link": ["biz|2", "test|2", "set|6"],
                        "default": 0,
                        "bk_obj_name": "\u96c6\u7fa4",
                        "bk_obj_id": "set",
                        "service_instance_count": 0,
                        "child": [
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|6", "module|28"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 28,
                                "bk_inst_name": "appengine",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|6", "module|23"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 23,
                                "bk_inst_name": "appo",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|6", "module|24"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 24,
                                "bk_inst_name": "appt",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|6", "module|22"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 22,
                                "bk_inst_name": "console",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|6", "module|25"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 25,
                                "bk_inst_name": "esb",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|6", "module|26"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 26,
                                "bk_inst_name": "login",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|6", "module|27"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 27,
                                "bk_inst_name": "paas",
                            },
                        ],
                        "service_template_id": 0,
                        "bk_inst_id": 6,
                        "bk_inst_name": "PaaS\u5e73\u53f0",
                    },
                    {
                        "host_count": 0,
                        "node_link": ["biz|2", "test|2", "set|7"],
                        "default": 0,
                        "bk_obj_name": "\u96c6\u7fa4",
                        "bk_obj_id": "set",
                        "service_instance_count": 0,
                        "child": [
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|7", "module|29"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 29,
                                "bk_inst_name": "job",
                            }
                        ],
                        "service_template_id": 0,
                        "bk_inst_id": 7,
                        "bk_inst_name": "\u4f5c\u4e1a\u5e73\u53f0",
                    },
                    {
                        "host_count": 0,
                        "node_link": ["biz|2", "test|2", "set|5"],
                        "default": 0,
                        "bk_obj_name": "\u96c6\u7fa4",
                        "bk_obj_id": "set",
                        "service_instance_count": 0,
                        "child": [
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|5", "module|16"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 16,
                                "bk_inst_name": "beanstalk",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|5", "module|60"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 60,
                                "bk_inst_name": "ceph-mon",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|5", "module|61"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 61,
                                "bk_inst_name": "ceph-radosgw",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|5", "module|21"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 21,
                                "bk_inst_name": "consul",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|5", "module|14"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 14,
                                "bk_inst_name": "elasticsearch",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|5", "module|11"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 11,
                                "bk_inst_name": "etcd",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|5", "module|10"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 10,
                                "bk_inst_name": "influxdb",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|5", "module|19"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 19,
                                "bk_inst_name": "kafka",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|5", "module|17"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 17,
                                "bk_inst_name": "mongodb",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|5", "module|18"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 18,
                                "bk_inst_name": "mysql",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|5", "module|59"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 59,
                                "bk_inst_name": "nfs",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|5", "module|15"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 15,
                                "bk_inst_name": "nginx",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|5", "module|20"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 20,
                                "bk_inst_name": "rabbitmq",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|5", "module|12"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 12,
                                "bk_inst_name": "redis",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|5", "module|9"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 9,
                                "bk_inst_name": "redis_cluster",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|5", "module|13"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 13,
                                "bk_inst_name": "zookeeper",
                            },
                        ],
                        "service_template_id": 0,
                        "bk_inst_id": 5,
                        "bk_inst_name": "\u516c\u5171\u7ec4\u4ef6",
                    },
                    {
                        "host_count": 0,
                        "node_link": ["biz|2", "test|2", "set|3"],
                        "default": 0,
                        "bk_obj_name": "\u96c6\u7fa4",
                        "bk_obj_id": "set",
                        "service_instance_count": 0,
                        "child": [
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|3", "module|5"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 5,
                                "bk_inst_name": "fta",
                            }
                        ],
                        "service_template_id": 0,
                        "bk_inst_id": 3,
                        "bk_inst_name": "\u6545\u969c\u81ea\u6108",
                    },
                    {
                        "host_count": 0,
                        "node_link": ["biz|2", "test|2", "set|4"],
                        "default": 0,
                        "bk_obj_name": "\u96c6\u7fa4",
                        "bk_obj_id": "set",
                        "service_instance_count": 0,
                        "child": [
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|4", "module|6"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 6,
                                "bk_inst_name": "dataapi",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|4", "module|7"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 7,
                                "bk_inst_name": "databus",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|4", "module|58"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 58,
                                "bk_inst_name": "datamanager",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|4", "module|8"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 8,
                                "bk_inst_name": "monitor",
                            },
                        ],
                        "service_template_id": 0,
                        "bk_inst_id": 4,
                        "bk_inst_name": "\u6570\u636e\u670d\u52a1\u6a21\u5757",
                    },
                    {
                        "host_count": 0,
                        "node_link": ["biz|2", "test|2", "set|9"],
                        "default": 0,
                        "bk_obj_name": "\u96c6\u7fa4",
                        "bk_obj_id": "set",
                        "service_instance_count": 0,
                        "child": [
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|9", "module|47"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 47,
                                "bk_inst_name": "gse_alarm",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|9", "module|42"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 42,
                                "bk_inst_name": "gse_api",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|9", "module|45"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 45,
                                "bk_inst_name": "gse_btsvr",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|9", "module|49"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 49,
                                "bk_inst_name": "gse_data",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|9", "module|56"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 56,
                                "bk_inst_name": "gse_dataop",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|9", "module|43"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 43,
                                "bk_inst_name": "gse_dba",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|9", "module|46"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 46,
                                "bk_inst_name": "gse_ops",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|9", "module|52"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 52,
                                "bk_inst_name": "gse_opts",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|9", "module|44"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 44,
                                "bk_inst_name": "gse_proc",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|9", "module|55"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 55,
                                "bk_inst_name": "gse_procmgr",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|9", "module|57"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 57,
                                "bk_inst_name": "gse_syncdata",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|9", "module|50"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 50,
                                "bk_inst_name": "gse_task",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|9", "module|48"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 48,
                                "bk_inst_name": "license",
                            },
                        ],
                        "service_template_id": 0,
                        "bk_inst_id": 9,
                        "bk_inst_name": "\u7ba1\u63a7\u5e73\u53f0",
                    },
                    {
                        "host_count": 0,
                        "node_link": ["biz|2", "test|2", "set|8"],
                        "default": 0,
                        "bk_obj_name": "\u96c6\u7fa4",
                        "bk_obj_id": "set",
                        "service_instance_count": 0,
                        "child": [
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|8", "module|33"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 33,
                                "bk_inst_name": "adminserver",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|8", "module|34"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 34,
                                "bk_inst_name": "apiserver",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|8", "module|38"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 38,
                                "bk_inst_name": "auditcontroller",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|8", "module|54"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 54,
                                "bk_inst_name": "cmdb-nginx",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|8", "module|35"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 35,
                                "bk_inst_name": "datacollection",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|8", "module|36"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 36,
                                "bk_inst_name": "eventserver",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|8", "module|39"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 39,
                                "bk_inst_name": "hostcontroller",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|8", "module|30"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 30,
                                "bk_inst_name": "hostserver",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|8", "module|31"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 31,
                                "bk_inst_name": "objectcontroller",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|8", "module|32"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 32,
                                "bk_inst_name": "proccontroller",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|8", "module|40"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 40,
                                "bk_inst_name": "procserver",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|8", "module|41"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 41,
                                "bk_inst_name": "toposerver",
                            },
                            {
                                "host_count": 0,
                                "node_link": ["biz|2", "test|2", "set|8", "module|37"],
                                "default": 0,
                                "bk_obj_name": "\u6a21\u5757",
                                "bk_obj_id": "module",
                                "service_instance_count": 0,
                                "child": [],
                                "service_template_id": 0,
                                "bk_inst_id": 37,
                                "bk_inst_name": "webserver",
                            },
                        ],
                        "service_template_id": 0,
                        "bk_inst_id": 8,
                        "bk_inst_name": "\u914d\u7f6e\u5e73\u53f0",
                    },
                ],
                "service_template_id": 0,
                "bk_inst_id": 2,
                "bk_inst_name": "test1",
            },
        ],
        "service_template_id": 0,
        "bk_inst_id": 2,
        "bk_inst_name": "\u84dd\u9cb8",
    }
}

SERVICE_CATEGORY_INFO = {
    "2": {
        1: {
            "bk_root_id": 1,
            "name": "\u6570\u636e\u5e93",
            "is_built_in": False,
            "bk_supplier_account": "0",
            "id": 1,
            "metadata": {"label": {"bk_biz_id": "2"}},
        },
        2: {
            "bk_root_id": 1,
            "name": "Mysql",
            "is_built_in": False,
            "bk_supplier_account": "0",
            "bk_parent_id": 1,
            "id": 2,
            "metadata": {"label": {"bk_biz_id": "2"}},
        },
        3: {
            "bk_root_id": 1,
            "name": "Oracle",
            "is_built_in": False,
            "bk_supplier_account": "0",
            "bk_parent_id": 1,
            "id": 3,
            "metadata": {"label": {"bk_biz_id": "2"}},
        },
        5: {
            "bk_root_id": 1,
            "name": "XXX",
            "is_built_in": False,
            "bk_supplier_account": "0",
            "bk_parent_id": 1,
            "id": 5,
            "metadata": {"label": {"bk_biz_id": "2"}},
        },
        9: {
            "bk_root_id": 9,
            "name": "Default",
            "is_built_in": True,
            "bk_supplier_account": "0",
            "id": 9,
            "metadata": {"label": None},
        },
        10: {
            "bk_root_id": 9,
            "name": "Default",
            "is_built_in": True,
            "bk_supplier_account": "0",
            "bk_parent_id": 9,
            "id": 10,
            "metadata": {"label": None},
        },
        11: {
            "is_built_in": True,
            "metadata": {"label": None},
            "id": 11,
            "name": "\u6570\u636e\u5e93",
            "bk_supplier_account": "0",
        },
        12: {
            "name": "Mysql",
            "is_built_in": True,
            "bk_supplier_account": "0",
            "bk_parent_id": 11,
            "id": 12,
            "metadata": {"label": None},
        },
        13: {
            "name": "Redis",
            "is_built_in": True,
            "bk_supplier_account": "0",
            "bk_parent_id": 11,
            "id": 13,
            "metadata": {"label": None},
        },
        14: {
            "name": "Oracle",
            "is_built_in": True,
            "bk_supplier_account": "0",
            "bk_parent_id": 11,
            "id": 14,
            "metadata": {"label": None},
        },
        15: {
            "name": "SQLServer",
            "is_built_in": True,
            "bk_supplier_account": "0",
            "bk_parent_id": 11,
            "id": 15,
            "metadata": {"label": None},
        },
        16: {
            "name": "MongoDB",
            "is_built_in": True,
            "bk_supplier_account": "0",
            "bk_parent_id": 11,
            "id": 16,
            "metadata": {"label": None},
        },
        17: {
            "name": "Etcd",
            "is_built_in": True,
            "bk_supplier_account": "0",
            "bk_parent_id": 11,
            "id": 17,
            "metadata": {"label": None},
        },
        18: {
            "name": "Zookeeper",
            "is_built_in": True,
            "bk_supplier_account": "0",
            "bk_parent_id": 11,
            "id": 18,
            "metadata": {"label": None},
        },
        19: {
            "is_built_in": True,
            "metadata": {"label": None},
            "id": 19,
            "name": "\u6d88\u606f\u961f\u5217",
            "bk_supplier_account": "0",
        },
        20: {
            "name": "Kafka",
            "is_built_in": True,
            "bk_supplier_account": "0",
            "bk_parent_id": 19,
            "id": 20,
            "metadata": {"label": None},
        },
        21: {
            "name": "RabbitMQ",
            "is_built_in": True,
            "bk_supplier_account": "0",
            "bk_parent_id": 19,
            "id": 21,
            "metadata": {"label": None},
        },
        22: {
            "is_built_in": True,
            "metadata": {"label": None},
            "id": 22,
            "name": "HTTP \u670d\u52a1",
            "bk_supplier_account": "0",
        },
        23: {
            "name": "Nginx",
            "is_built_in": True,
            "bk_supplier_account": "0",
            "bk_parent_id": 22,
            "id": 23,
            "metadata": {"label": None},
        },
        24: {
            "name": "Apache",
            "is_built_in": True,
            "bk_supplier_account": "0",
            "bk_parent_id": 22,
            "id": 24,
            "metadata": {"label": None},
        },
        25: {
            "name": "Tomcat",
            "is_built_in": True,
            "bk_supplier_account": "0",
            "bk_parent_id": 22,
            "id": 25,
            "metadata": {"label": None},
        },
        26: {
            "is_built_in": True,
            "metadata": {"label": None},
            "id": 26,
            "name": "\u5b58\u50a8",
            "bk_supplier_account": "0",
        },
        27: {
            "name": "Ceph",
            "is_built_in": True,
            "bk_supplier_account": "0",
            "bk_parent_id": 26,
            "id": 27,
            "metadata": {"label": None},
        },
        28: {
            "name": "NFS",
            "is_built_in": True,
            "bk_supplier_account": "0",
            "bk_parent_id": 26,
            "id": 28,
            "metadata": {"label": None},
        },
        30: {
            "bk_root_id": 30,
            "name": "bond",
            "is_built_in": False,
            "bk_supplier_account": "0",
            "id": 30,
            "metadata": {"label": {"bk_biz_id": "2"}},
        },
        31: {
            "bk_root_id": 30,
            "name": "bond1",
            "is_built_in": False,
            "bk_supplier_account": "0",
            "bk_parent_id": 30,
            "id": 31,
            "metadata": {"label": {"bk_biz_id": "2"}},
        },
        32: {
            "bk_root_id": 30,
            "name": "bond2",
            "is_built_in": False,
            "bk_supplier_account": "0",
            "bk_parent_id": 30,
            "id": 32,
            "metadata": {"label": {"bk_biz_id": "2"}},
        },
        33: {
            "bk_root_id": 30,
            "name": "bond3",
            "is_built_in": False,
            "bk_supplier_account": "0",
            "bk_parent_id": 30,
            "id": 33,
            "metadata": {"label": {"bk_biz_id": "2"}},
        },
        34: {
            "bk_root_id": 30,
            "name": "tst",
            "is_built_in": False,
            "bk_supplier_account": "0",
            "bk_parent_id": 30,
            "id": 34,
            "metadata": {"label": {"bk_biz_id": "2"}},
        },
        36: {
            "bk_root_id": 36,
            "name": "sssssss",
            "is_built_in": False,
            "bk_supplier_account": "0",
            "id": 36,
            "metadata": {"label": {"bk_biz_id": "2"}},
        },
        37: {
            "bk_root_id": 37,
            "name": "PaaS",
            "is_built_in": False,
            "bk_supplier_account": "0",
            "id": 37,
            "metadata": {"label": {"bk_biz_id": "2"}},
        },
        38: {
            "bk_root_id": 37,
            "name": "esb",
            "is_built_in": False,
            "bk_supplier_account": "0",
            "bk_parent_id": 37,
            "id": 38,
            "metadata": {"label": {"bk_biz_id": "2"}},
        },
        42: {
            "bk_root_id": 42,
            "name": "hito-server-type",
            "is_built_in": False,
            "bk_supplier_account": "0",
            "id": 42,
            "metadata": {"label": {"bk_biz_id": "2"}},
        },
        43: {
            "bk_root_id": 42,
            "name": "server-type-1",
            "is_built_in": False,
            "bk_supplier_account": "0",
            "bk_parent_id": 42,
            "id": 43,
            "metadata": {"label": {"bk_biz_id": "2"}},
        },
    }
}
