# Generated by Django 4.2.23 on 2025-09-16 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ObjectModelGroupORM",
            fields=[
                ("object_model_group_id", models.AutoField(primary_key=True, serialize=False, verbose_name="主键")),
                ("object_model_group_code", models.CharField(max_length=255, unique=True, verbose_name="分组code")),
                ("object_model_group_name", models.CharField(max_length=255, verbose_name="分组名称")),
                ("object_model_group_name_en", models.CharField(max_length=255, null=True, verbose_name="分组名称")),
                (
                    "object_model_group_name_zh_hans",
                    models.CharField(max_length=255, null=True, verbose_name="分组名称"),
                ),
                ("is_default", models.BooleanField(verbose_name="是否内置")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("created_by", models.CharField(blank=True, max_length=100, verbose_name="创建人")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=100, verbose_name="修改人")),
                (
                    "parent_object_model_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="object_model.objectmodelgrouporm",
                        verbose_name="父级分组",
                    ),
                ),
            ],
            options={
                "verbose_name": "对象模型分组",
                "verbose_name_plural": "对象模型分组",
                "db_table": "object_model_group_v2",
                "unique_together": {("parent_object_model_group_id", "object_model_group_name")},
            },
        ),
        migrations.CreateModel(
            name="ObjectModelORM",
            fields=[
                ("object_model_id", models.AutoField(primary_key=True, serialize=False, verbose_name="主键")),
                ("object_model_code", models.CharField(max_length=255, unique=True, verbose_name="对象模型英文标识")),
                ("object_model_name", models.CharField(max_length=255, unique=True, verbose_name="对象模型名称")),
                (
                    "object_model_name_en",
                    models.CharField(max_length=255, null=True, unique=True, verbose_name="对象模型名称"),
                ),
                (
                    "object_model_name_zh_hans",
                    models.CharField(max_length=255, null=True, unique=True, verbose_name="对象模型名称"),
                ),
                ("is_default", models.BooleanField(default=False, verbose_name="是否内置")),
                (
                    "datasource",
                    models.CharField(
                        choices=[("cmdb", "Cmdb"), ("custom", "Custom"), ("legacy", "Legacy")],
                        max_length=32,
                        verbose_name="实例来源",
                    ),
                ),
                ("bk_cmdb_obj_id", models.CharField(default="", max_length=255, verbose_name="cmdb模型id")),
                ("display_fields", models.JSONField(default=list, verbose_name="标识展示字段")),
                ("inst_display_name", models.CharField(default="", max_length=128, verbose_name="实例展示名")),
                ("host_related_field", models.CharField(default="", max_length=255, verbose_name="运行主机关联字段")),
                ("operator_fields", models.JSONField(default=list, verbose_name="负责人字段")),
                ("topo_related_field", models.CharField(default="", max_length=255, verbose_name="IP映射字段")),
                ("port_field", models.CharField(default="", max_length=255, verbose_name="端口映射字段")),
                ("custom_model_field", models.CharField(default="", max_length=255, verbose_name="自定义模型字段")),
                ("model_related_field", models.CharField(default="", max_length=255, verbose_name="关联模型字段")),
                (
                    "related_model_type",
                    models.CharField(
                        choices=[("APM", "Apm"), ("LEGACY", "Legacy"), ("", "Empty")],
                        default="",
                        max_length=8,
                        verbose_name="关联类型",
                    ),
                ),
                (
                    "related_model_code",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="关联模型标识"),
                ),
                ("ar_dimensionality", models.CharField(default="", max_length=64, verbose_name="apm唯一标识列表")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("created_by", models.CharField(blank=True, max_length=100, verbose_name="创建人")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=100, verbose_name="修改人")),
                (
                    "object_model_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="object_model.objectmodelgrouporm",
                        verbose_name="对象模型分组",
                    ),
                ),
            ],
            options={
                "verbose_name": "对象模型",
                "verbose_name_plural": "对象模型",
                "db_table": "object_model_v2",
            },
        ),
        migrations.CreateModel(
            name="ObjectModelUsageRecordORM",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("app_id", models.CharField(max_length=64, verbose_name="关联SaasID")),
                ("app_name", models.CharField(max_length=64, verbose_name="关联Saas名称")),
                ("module_id", models.CharField(max_length=255, verbose_name="关联模块ID")),
                ("module_name", models.CharField(max_length=255, verbose_name="关联模块名称")),
                ("inst_id", models.CharField(max_length=255, verbose_name="关联实例ID")),
                ("inst_name", models.CharField(max_length=255, verbose_name="关联实例名称")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("created_by", models.CharField(blank=True, max_length=100, verbose_name="创建人")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=100, verbose_name="修改人")),
                (
                    "object_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="object_model.objectmodelorm",
                        verbose_name="监控对象ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "对象模型引用记录",
                "verbose_name_plural": "对象模型引用记录",
                "db_table": "object_model_usage_record_v2",
                "unique_together": {("object_model_id", "app_id", "module_id", "inst_id")},
            },
        ),
    ]
