# Generated by Django 4.2.27 on 2026-01-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object_model", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectmodelorm",
            name="attribute_config",
            field=models.JSONField(default=dict, verbose_name="对象模型属性配置"),
        ),
    ]
