# Generated by Django 4.2.23 on 2025-12-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object_model", "0002_objectmodelorm_attribute_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectmodelgrouporm",
            name="bk_tenant_id",
            field=models.CharField(default="system", max_length=64, verbose_name="租户ID"),
        ),
        migrations.AddField(
            model_name="objectmodelorm",
            name="bk_tenant_id",
            field=models.CharField(default="system", max_length=64, verbose_name="租户ID"),
        ),
        migrations.AddField(
            model_name="objectmodelusagerecordorm",
            name="bk_tenant_id",
            field=models.CharField(default="system", max_length=64, verbose_name="租户ID"),
        ),
    ]
