# Generated by Django 4.2.17 on 2026-01-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object_model", "0003_objectmodelgrouporm_bk_tenant_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="objectmodelgrouporm",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="objectmodelusagerecordorm",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="objectmodelgrouporm",
            name="object_model_group_code",
            field=models.CharField(max_length=255, verbose_name="分组code"),
        ),
        migrations.AlterField(
            model_name="objectmodelorm",
            name="object_model_code",
            field=models.CharField(max_length=255, verbose_name="对象模型英文标识"),
        ),
        migrations.AlterField(
            model_name="objectmodelorm",
            name="object_model_name",
            field=models.CharField(max_length=255, verbose_name="对象模型名称"),
        ),
        migrations.AlterField(
            model_name="objectmodelorm",
            name="object_model_name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="对象模型名称"),
        ),
        migrations.AlterField(
            model_name="objectmodelorm",
            name="object_model_name_zh_hans",
            field=models.CharField(max_length=255, null=True, verbose_name="对象模型名称"),
        ),
        migrations.AlterUniqueTogether(
            name="objectmodelgrouporm",
            unique_together={
                ("bk_tenant_id", "object_model_group_code"),
                ("bk_tenant_id", "parent_object_model_group", "object_model_group_name"),
            },
        ),
        migrations.AlterUniqueTogether(
            name="objectmodelorm",
            unique_together={("bk_tenant_id", "object_model_name"), ("bk_tenant_id", "object_model_code")},
        ),
        migrations.AlterUniqueTogether(
            name="objectmodelusagerecordorm",
            unique_together={("bk_tenant_id", "object_model", "app_id", "module_id", "inst_id")},
        ),
    ]
