# Generated by Django 4.2.17 on 2026-03-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object_model", "0004_alter_objectmodelgrouporm_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectmodelgrouporm",
            name="bk_tenant_id",
            field=models.CharField(
                db_index=True,
                default="system",
                help_text="租户标识，用于多租户数据隔离",
                max_length=256,
                verbose_name="租户ID",
            ),
        ),
        migrations.AlterField(
            model_name="objectmodelorm",
            name="bk_tenant_id",
            field=models.CharField(
                db_index=True,
                default="system",
                help_text="租户标识，用于多租户数据隔离",
                max_length=256,
                verbose_name="租户ID",
            ),
        ),
        migrations.AlterField(
            model_name="objectmodelusagerecordorm",
            name="bk_tenant_id",
            field=models.CharField(
                db_index=True,
                default="system",
                help_text="租户标识，用于多租户数据隔离",
                max_length=256,
                verbose_name="租户ID",
            ),
        ),
    ]
