# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2020-05-15 09:41


from django.db import migrations, models
from dns import resolver
from dns.exception import DNSException

from core.errors.errors import MigrateError

MAX_ANOMALY_RECORD_COUNT = 2000000
BACKEND_DOMAIN = "monitor.bkmonitorv3.service.consul"
NEED_STOP_RECORD_COUNT = 500000


def pre_check(apps, *args, **kwargs):
    anomaly_record = apps.get_model("bkmonitor", "AnomalyRecord")
    min_id = getattr(anomaly_record.objects.first(), "id", 0)
    max_id = getattr(anomaly_record.objects.last(), "id", 0)
    count = max_id - min_id
    if count > MAX_ANOMALY_RECORD_COUNT:
        global_config = apps.get_model("bkmonitor", "GlobalConfig")
        reserved_days = global_config.objects.get(key="TS_DATA_SAVED_DAYS").value
        raise MigrateError(
            "\n[ERROR]异常记录数过多,当前数量为{}，您可以按以下流程完成操作:\n"
            "1、减小全局配置中'监控采集数据保存天数'的值来减少存储量,当前值为{};\n"
            "2、清理异常记录至200万以下，操作方法：\n"
            "登录后台执行:\n"
            "workon bkmonitorv3-monitor\n"
            "./bin/manage.sh run_clean\n"
            "3、停止后台进程后部署SaaS;\n"
            "4、部署后台".format(count, reserved_days)
        )
    if count > NEED_STOP_RECORD_COUNT:
        try:
            resolve_items = resolver.resolve(BACKEND_DOMAIN)
            for item in resolve_items:
                if item.address:
                    raise MigrateError("\n[ERROR]后台进程未停止，部署前请先停止后台进程")
        except DNSException:
            pass


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0010_alertcollect_extend_info"),
    ]

    operations = [
        migrations.RunPython(pre_check),
        migrations.AddField(
            model_name="anomalyrecord",
            name="count",
            field=models.IntegerField(default=1, verbose_name="异常汇总数量"),
        ),
    ]
