# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2020-06-16 03:43


import bkmonitor.models.base
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0013_snapshothostindex_append"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="globalconfig",
            options={"verbose_name": "动态配置信息", "verbose_name_plural": "动态配置信息"},
        ),
        migrations.AlterField(
            model_name="snapshothostindex",
            name="description",
            field=bkmonitor.models.base.DescriptionAdapterField(max_length=50, verbose_name="description"),
        ),
    ]
