# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2020-11-06 06:43


import bkmonitor.utils.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0022_basealarm_data_append_oom"),
    ]

    operations = [
        migrations.CreateModel(
            name="report_contents",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report_item", models.IntegerField(db_index=True, verbose_name="订阅报表ID")),
                ("content_title", models.CharField(max_length=512, verbose_name="内容标题")),
                ("content_details", models.TextField(max_length=512, verbose_name="内容说明")),
                ("row_pictures_num", models.IntegerField(default=0, verbose_name="一行几幅图")),
                ("graphs", bkmonitor.utils.db.fields.JsonField(default={}, verbose_name="图表Panels信息")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="report_items",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="最后修改人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="最后修改时间")),
                ("mail_title", models.CharField(max_length=512, verbose_name="邮件标题")),
                ("receivers", bkmonitor.utils.db.fields.JsonField(default={}, verbose_name="接收者")),
                ("managers", bkmonitor.utils.db.fields.JsonField(default={}, verbose_name="管理员")),
                ("frequency", models.CharField(max_length=512, verbose_name="发送频率")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="report_status",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report_item", models.IntegerField(db_index=True, verbose_name="订阅报表ID")),
                ("mail_title", models.CharField(max_length=512, verbose_name="邮件标题")),
                ("create_time", models.DateTimeField(verbose_name="发送时间")),
                ("is_success", models.BooleanField(default=False, verbose_name="是否成功")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="detectalgorithm",
            name="algorithm_type",
            field=models.CharField(
                choices=[
                    ("Threshold", "静态阈值算法"),
                    ("SimpleRingRatio", "简易环比算法"),
                    ("AdvancedRingRatio", "高级环比算法"),
                    ("SimpleYearRound", "简易同比算法"),
                    ("AdvancedYearRound", "高级同比算法"),
                    ("PartialNodes", "部分节点数算法"),
                    ("OsRestart", "主机重启算法"),
                    ("ProcPort", "进程端口算法"),
                    ("PingUnreachable", "Ping不可达算法"),
                    ("YearRoundAmplitude", "同比振幅算法"),
                    ("YearRoundRange", "同比区间算法"),
                    ("RingRatioAmplitude", "环比振幅算法"),
                ],
                max_length=128,
                verbose_name="算法类型",
            ),
        ),
    ]
