# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2020-12-01 09:02


import django.db.models.deletion
from bkcrypto.contrib.django.fields import SymmetricTextField
from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0023_auto_20201120_1649"),
    ]

    operations = [
        migrations.CreateModel(
            name="CacheNode",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cache_type",
                    models.CharField(
                        choices=[("RedisCache", "单例"), ("SentinelRedisCache", "sentinel")],
                        max_length=32,
                        verbose_name="节点类型",
                    ),
                ),
                ("host", models.CharField(max_length=128, verbose_name="host")),
                ("port", models.IntegerField(verbose_name="port")),
                ("password", SymmetricTextField(default="", verbose_name="密码")),
                ("connection_kwargs", bkmonitor.utils.db.fields.JsonField(verbose_name="额外连接信息")),
                ("is_enable", models.BooleanField(default=True, verbose_name="是否启用")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("is_default", models.BooleanField(default=False, verbose_name="默认节点")),
            ],
            options={"verbose_name": "后台缓存节点", "verbose_name_plural": "后台缓存节点", "db_table": "alarm_cachenode"},
        ),
        migrations.CreateModel(
            name="CacheRouter",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("strategy_score", models.IntegerField(db_index=True, verbose_name="策略id路由分组")),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routers",
                        to="bkmonitor.CacheNode",
                        verbose_name="缓存节点",
                    ),
                ),
            ],
            options={"verbose_name": "后台缓存路由", "verbose_name_plural": "后台缓存路由", "db_table": "alarm_cacherouter"},
        ),
    ]
