# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2021-04-14 07:04


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0032_migrate_strategy_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyHistoryModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("strategy_id", models.IntegerField(db_index=True, verbose_name="关联策略ID")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("create_user", models.CharField(max_length=32, verbose_name="创建者")),
                ("content", models.JSONField(default=dict, verbose_name="保存内容")),
                (
                    "operate",
                    models.CharField(
                        choices=[("delete", "删除"), ("create", "创建"), ("update", "更新")],
                        db_index=True,
                        max_length=12,
                        verbose_name="操作",
                    ),
                ),
                ("status", models.BooleanField(default=False, verbose_name="操作状态")),
                ("message", models.TextField(blank=True, default="", verbose_name="错误信息")),
            ],
            options={
                "verbose_name": "策略配置",
                "verbose_name_plural": "策略配置",
                "db_table": "alarm_strategy_history",
                "ordering": ("-create_time",),
            },
        ),
        migrations.AlterField(
            model_name="algorithmmodel",
            name="level",
            field=models.IntegerField(choices=[(1, "致命"), (2, "预警"), (3, "提醒")], default=3, verbose_name="告警级别"),
        ),
        migrations.AlterField(
            model_name="detectmodel",
            name="level",
            field=models.IntegerField(choices=[(1, "致命"), (2, "预警"), (3, "提醒")], default=3, verbose_name="告警级别"),
        ),
    ]
