# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2021-04-19 09:32


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0033_auto_20210414_1504"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="algorithmmodel",
            options={"verbose_name": "检测算法配置V2", "verbose_name_plural": "检测算法配置V2"},
        ),
        migrations.AlterModelOptions(
            name="detectmodel",
            options={"verbose_name": "检测配置V2", "verbose_name_plural": "检测配置V2"},
        ),
        migrations.AlterModelOptions(
            name="itemmodel",
            options={"verbose_name": "监控项配置V2", "verbose_name_plural": "监控项配置V2"},
        ),
        migrations.AlterModelOptions(
            name="queryconfigmodel",
            options={"verbose_name": "查询配置表V2", "verbose_name_plural": "查询配置表V2"},
        ),
        migrations.AlterModelOptions(
            name="strategyhistorymodel",
            options={"ordering": ("-create_time",), "verbose_name": "策略配置操作历史", "verbose_name_plural": "策略配置操作历史"},
        ),
        migrations.AlterModelOptions(
            name="strategymodel",
            options={"verbose_name": "策略配置V2", "verbose_name_plural": "策略配置V2"},
        ),
        migrations.AlterField(
            model_name="detectmodel",
            name="connector",
            field=models.CharField(
                choices=[("and", "AND"), ("or", "OR")], default="and", max_length=4, verbose_name="同级别算法连接符"
            ),
        ),
    ]
