# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2021-06-08 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0037_auto_20210608_1549"),
    ]

    operations = [
        migrations.CreateModel(
            name="DutyArrange",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="最后修改人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="最后修改时间")),
                ("user_group_id", models.IntegerField(verbose_name="关联的告警组")),
                (
                    "duty_type",
                    models.CharField(
                        choices=[("date", "日期"), ("week", "星期")], default="week", max_length=32, verbose_name="值班类型"
                    ),
                ),
                ("work_time", models.CharField(default="all_day", max_length=128, verbose_name="工作时间段")),
                ("users", models.JSONField(default=dict, verbose_name="告警处理值班")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="usergroup",
            name="users",
        ),
    ]
