# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2021-06-11 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0039_auto_20210608_1745"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usergroup",
            options={"ordering": ("-update_time",), "verbose_name": "告警处理组配置", "verbose_name_plural": "告警处理组配置"},
        ),
        migrations.AlterField(
            model_name="dutyarrange",
            name="duty_type",
            field=models.CharField(
                choices=[("date", "日期"), ("week", "星期"), ("always", "不分日夜")],
                default="always",
                max_length=32,
                verbose_name="值班类型",
            ),
        ),
        migrations.AlterField(
            model_name="dutyarrange",
            name="work_time",
            field=models.CharField(default="always", max_length=128, verbose_name="工作时间段"),
        ),
        migrations.AlterField(
            model_name="strategymodel",
            name="type",
            field=models.CharField(
                choices=[("monitor", "监控"), ("fta", "故障自愈")], db_index=True, max_length=12, verbose_name="策略类型"
            ),
        ),
    ]
