# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2021-06-20 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0043_auto_20210616_1513"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convergeinstance",
            name="converge_func",
            field=models.CharField(
                blank=True,
                choices=[
                    ("skip_when_success", "成功后跳过"),
                    ("skip_when_proceed", "执行中跳过"),
                    ("wait_when_proceed", "执行中等待"),
                    ("defense", "异常防御审批"),
                    ("collect", "超出后汇总"),
                    ("trigger", "收敛后处理"),
                    ("collect_alarm", "汇总通知"),
                ],
                db_index=True,
                max_length=128,
                null=True,
                verbose_name="收敛事件类型",
            ),
        ),
    ]
