# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2021-08-13 03:08
from __future__ import unicode_literals

from django.db import migrations, transaction
from django.db.models import Q


@transaction.atomic
def fix_log_search_method(apps, *args, **kwargs):
    """
    多指标策略指标信息修复
    """
    QueryConfigModel = apps.get_model("bkmonitor", "QueryConfigModel")

    query_configs = QueryConfigModel.objects.filter(data_source_label="bk_log_search").filter(
        Q(config__agg_condition__contains={"method": "is one of"})
        | Q(config__agg_condition__contains={"method": "is"})
        | Q(config__agg_condition__contains={"method": "is not"})
        | Q(config__agg_condition__contains={"method": "is not one of"})
    )

    method_mapping = {"is": "eq", "is one of": "eq", "is not": "neq", "is not one of": "neq"}

    for query_config in query_configs:
        agg_condition = query_config.config["agg_condition"]
        for condition in agg_condition:
            condition["method"] = method_mapping.get(condition["method"], condition["method"])

        query_config.save()


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0045_fix_custom_event_metric_id"),
    ]

    operations = [migrations.RunPython(fix_log_search_method)]
