# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2021-06-26 03:19
from __future__ import unicode_literals

from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0046_auto_20210623_1643"),
    ]

    operations = [
        migrations.AddField(
            model_name="actioninstance",
            name="dimensions",
            field=bkmonitor.utils.db.fields.JsonField(default={}, verbose_name="关联的维度信息"),
        ),
        migrations.AddField(
            model_name="actioninstance",
            name="matched_dimension_md5",
            field=models.CharField(default="", max_length=64, verbose_name="匹配策略的维度md5"),
        ),
        migrations.AlterField(
            model_name="actioninstance",
            name="signal",
            field=models.CharField(
                choices=[
                    ("manual", "手动"),
                    ("abnormal", "告警产生时"),
                    ("recovered", "告警恢复时"),
                    ("closed", "告警关闭时"),
                    ("collect", "汇总"),
                ],
                help_text="触发该事件的告警信号，如生成告警，告警恢复，告警关闭",
                max_length=64,
                verbose_name="触发信号",
            ),
        ),
        migrations.AlterField(
            model_name="strategyactionconfigrelation",
            name="signal",
            field=models.CharField(
                choices=[
                    ("manual", "手动"),
                    ("abnormal", "告警产生时"),
                    ("recovered", "告警恢复时"),
                    ("closed", "告警关闭时"),
                    ("collect", "汇总"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
