# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-10-21 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0047_merge_20210927_1502"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticegroup",
            name="webhook_url",
            field=models.CharField(default="", max_length=1024, verbose_name="回调地址"),
        ),
    ]
