# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-07 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0042_new_detectalgorithm_algorithm_unit"),
        ("bkmonitor", "0049_fix_bk_monitor_log_metric_id"),
    ]

    operations = []
