# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2021-07-07 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0050_auto_20210702_2131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actioninstance",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name="主键"),
        ),
        migrations.AlterField(
            model_name="actioninstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "收到"),
                    ("waiting", "审批中"),
                    ("converging", "收敛中"),
                    ("sleep", "收敛处理等待"),
                    ("converged", "收敛结束"),
                    ("running", "处理中"),
                    ("success", "成功"),
                    ("partial_success", "部分成功"),
                    ("failure", "失败"),
                    ("skipped", "跳过"),
                    ("shield", "已屏蔽"),
                ],
                default="received",
                max_length=64,
                verbose_name="执行状态",
            ),
        ),
        migrations.AlterField(
            model_name="actioninstancelog",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name="主键"),
        ),
        migrations.AlterField(
            model_name="convergeinstance",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name="主键"),
        ),
        migrations.AlterField(
            model_name="convergerelation",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name="主键"),
        ),
    ]
