# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-08-04 08:40
from __future__ import unicode_literals

from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0055_merge_20210803_1738"),
    ]

    operations = [
        migrations.AddField(
            model_name="convergerelation",
            name="alerts",
            field=bkmonitor.utils.db.fields.JsonField(default=[], verbose_name="防御的告警列表"),
        ),
        migrations.AddField(
            model_name="convergerelation",
            name="converge_status",
            field=models.CharField(
                choices=[("skipped", "跳过"), ("executed", "执行")], default="skipped", max_length=32, verbose_name="收敛状态"
            ),
        ),
        migrations.AlterField(
            model_name="convergerelation",
            name="related_type",
            field=models.CharField(choices=[("converge", "收敛事件"), ("converge", "处理事件")], db_index=True, max_length=64),
        ),
    ]
