# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-08-11 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0056_auto_20210804_1640"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actioninstance",
            name="generate_uuid",
            field=models.CharField(db_index=True, default="", max_length=32, verbose_name="创建批次"),
        ),
        migrations.AlterField(
            model_name="convergeinstance",
            name="converge_func",
            field=models.CharField(
                blank=True,
                choices=[
                    ("skip_when_success", "成功后跳过"),
                    ("skip_when_proceed", "执行中跳过"),
                    ("wait_when_proceed", "执行中等待"),
                    ("skip_when_exceed", "超出后忽略"),
                    ("defense", "异常防御审批"),
                    ("collect", "超出后汇总"),
                    ("trigger", "收敛后处理"),
                    ("collect_alarm", "汇总通知"),
                ],
                db_index=True,
                max_length=128,
                null=True,
                verbose_name="收敛事件类型",
            ),
        ),
        migrations.AlterField(
            model_name="convergerelation",
            name="related_type",
            field=models.CharField(choices=[("converge", "收敛事件"), ("action", "处理事件")], db_index=True, max_length=64),
        ),
    ]
