# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-08-18 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0057_auto_20210811_1649"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionplugin",
            name="plugin_key",
            field=models.CharField(
                choices=[
                    ("notice", "通知"),
                    ("webhook", "HTTP回调"),
                    ("job", "作业平台"),
                    ("sops", "标准运维"),
                    ("itsm", "流程服务"),
                    ("common", "通用插件"),
                ],
                default="common",
                max_length=64,
                verbose_name="插件key, 一个唯一的确定值",
            ),
        ),
    ]
