# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-09-02 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0044_fix_item_name"),
        ("bkmonitor", "0058_actionplugin_plugin_key"),
    ]

    operations = []
