# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-09-06 10:36
from __future__ import unicode_literals

from django.db import migrations

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0060_merge_20210902_1921"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actioninstance",
            name="action_config",
            field=bkmonitor.utils.db.fields.JsonField(default={}, verbose_name="关联配置信息的快照"),
        ),
        migrations.AlterField(
            model_name="actioninstance",
            name="action_plugin",
            field=bkmonitor.utils.db.fields.JsonField(default={}, verbose_name="事件对应的插件信息"),
        ),
    ]
