# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-09-07 13:07
from __future__ import unicode_literals

from django.db import migrations, models

import bkmonitor.utils.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0061_auto_20210906_1836"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actionconfig",
            name="converge_config",
        ),
        migrations.RemoveField(
            model_name="strategyactionconfigrelation",
            name="is_combined",
        ),
        migrations.AddField(
            model_name="actionconfig",
            name="risk_level",
            field=models.IntegerField(choices=[(1, "高"), (2, "中"), (3, "低")], default=3, verbose_name="危险程度"),
        ),
        migrations.AddField(
            model_name="strategyactionconfigrelation",
            name="options",
            field=bkmonitor.utils.db.fields.JsonField(default={}, verbose_name="高级设置"),
        ),
        migrations.AddField(
            model_name="strategyactionconfigrelation",
            name="relate_type",
            field=models.CharField(
                choices=[("NOTICE", "通知"), ("ACTION", "处理动作")], default="NOTICE", max_length=32, verbose_name="关联类型"
            ),
        ),
        migrations.AlterField(
            model_name="actioninstance",
            name="alert_level",
            field=models.IntegerField(choices=[(1, "致命"), (2, "预警"), (3, "提醒")], default=3, verbose_name="告警级别"),
        ),
        migrations.AlterField(
            model_name="actioninstance",
            name="signal",
            field=models.CharField(
                choices=[
                    ("manual", "手动"),
                    ("abnormal", "告警产生时"),
                    ("recovered", "告警恢复时"),
                    ("closed", "告警关闭时"),
                    ("no_data", "无数据时"),
                    ("collect", "汇总"),
                    ("execute", "执行动作时"),
                ],
                help_text="触发该事件的告警信号，如告警异常，告警恢复，告警关闭等",
                max_length=64,
                verbose_name="触发信号",
            ),
        ),
        migrations.AlterField(
            model_name="strategyactionconfigrelation",
            name="signal",
            field=bkmonitor.utils.db.fields.JsonField(default=[], verbose_name="触发信号"),
        ),
    ]
