# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-09-13 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0062_auto_20210907_2107"),
        ("bkmonitor", "0045_fix_custom_event_metric_id"),
    ]

    operations = []
