# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-10-19 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0063_merge_20210913_1326"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actionconfig",
            name="risk_level",
        ),
        migrations.AddField(
            model_name="usergroup",
            name="action_notice",
            field=models.JSONField(default=list, verbose_name="执行通知配置"),
        ),
        migrations.AddField(
            model_name="usergroup",
            name="alert_notice",
            field=models.JSONField(default=list, verbose_name="告警通知配置"),
        ),
        migrations.AlterField(
            model_name="actioninstance",
            name="signal",
            field=models.CharField(
                choices=[
                    ("manual", "手动"),
                    ("abnormal", "告警产生时"),
                    ("recovered", "告警恢复时"),
                    ("closed", "告警关闭时"),
                    ("no_data", "无数据时"),
                    ("collect", "汇总"),
                    ("execute", "执行动作时"),
                    ("execute_success", "执行成功时"),
                    ("execute_failed", "执行失败时"),
                    ("demo", "调试"),
                ],
                help_text="触发该事件的告警信号，如告警异常，告警恢复，告警关闭等",
                max_length=64,
                verbose_name="触发信号",
            ),
        ),
    ]
