# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-10-26 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0048_auto_20211021_1500"),
        ("bkmonitor", "0065_auto_20211019_2040"),
    ]

    operations = []
