# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-11-10 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0066_merge_20211026_1640"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergroup",
            name="webhook_action_id",
            field=models.IntegerField(default=0, verbose_name="回调套餐ID"),
        ),
        migrations.AlterField(
            model_name="actionconfig",
            name="name",
            field=models.CharField(max_length=128, verbose_name="套餐名称"),
        ),
    ]
