# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-11-16 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0069_upgrade_action_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategyactionconfigrelation",
            name="config_id",
            field=models.IntegerField(db_index=True, verbose_name="响应动作配置ID"),
        ),
        migrations.AlterField(
            model_name="strategyactionconfigrelation",
            name="strategy_id",
            field=models.IntegerField(db_index=True, verbose_name="故障自愈的策略ID"),
        ),
    ]
