# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-11-18 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0070_auto_20211116_1548"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convergeinstance",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="actioninstance",
            name="signal",
            field=models.CharField(
                choices=[
                    ("manual", "手动"),
                    ("abnormal", "告警触发时"),
                    ("recovered", "告警恢复时"),
                    ("closed", "告警关闭时"),
                    ("no_data", "无数据时"),
                    ("collect", "汇总"),
                    ("execute", "执行动作时"),
                    ("execute_success", "执行成功时"),
                    ("execute_failed", "执行失败时"),
                    ("demo", "调试"),
                ],
                help_text="触发该事件的告警信号，如告警异常，告警恢复，告警关闭等",
                max_length=64,
                verbose_name="触发信号",
            ),
        ),
        migrations.AlterModelOptions(
            name="actioninstance",
            options={"verbose_name": "自愈执行动作", "verbose_name_plural": "自愈执行动作"},
        ),
        migrations.AlterIndexTogether(
            name="actioninstance",
            index_together={("create_time", "status"), ("create_time", "signal"), ("status", "signal", "update_time")},
        ),
    ]
