# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-11-19 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0071_auto_20211118_1207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actioninstance",
            name="need_poll",
            field=models.BooleanField(db_index=True, default=False, verbose_name="是否需要创建周期任务"),
        ),
    ]
