# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-11-23 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0072_auto_20211119_1413"),
        ("bkmonitor", "0049_fix_bk_monitor_log_metric_id"),
    ]

    operations = []
