# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-01 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0074_actionconfig_is_builtin"),
        ("bkmonitor", "0074_metricmappingconfigmodel"),
    ]

    operations = []
