# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-07 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0050_merge_20211207_1140"),
        ("bkmonitor", "0074_actionconfig_is_builtin"),
    ]

    operations = []
