# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-29 07:07
from __future__ import unicode_literals

from django.db import migrations, models

import bkmonitor.models.fta.action


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0075_merge_20211207_1142"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convergeinstance",
            name="converge_func",
            field=models.CharField(
                blank=True,
                choices=[
                    ("skip_when_success", "成功后跳过"),
                    ("skip_when_proceed", "执行中跳过"),
                    ("wait_when_proceed", "执行中等待"),
                    ("skip_when_exceed", "超出后忽略"),
                    ("defense", "异常防御审批"),
                    ("collect", "超出后汇总"),
                    ("collect_alarm", "汇总通知"),
                    ("trigger", "收敛后处理"),
                    ("collect_alarm", "汇总通知"),
                ],
                db_index=True,
                max_length=128,
                null=True,
                verbose_name="收敛事件类型",
            ),
        ),
        migrations.AlterField(
            model_name="strategyactionconfigrelation",
            name="options",
            field=models.JSONField(default=bkmonitor.models.fta.action.default_dict, verbose_name="高级设置"),
        ),
        migrations.AlterField(
            model_name="strategyactionconfigrelation",
            name="signal",
            field=models.JSONField(default=bkmonitor.models.fta.action.default_list, verbose_name="触发信号"),
        ),
        migrations.AlterField(
            model_name="strategyactionconfigrelation",
            name="user_groups",
            field=models.JSONField(default=bkmonitor.models.fta.action.default_list, verbose_name="用户组"),
        ),
    ]
