# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-30 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0076_auto_20211229_1507"),
        ("bkmonitor", "0076_auto_20211224_1723"),
    ]

    operations = []
