# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-01-05 09:39
from __future__ import unicode_literals

from django.db import migrations, models

import bkmonitor.models.strategy


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0077_merge_20211230_1522"),
    ]

    operations = [
        migrations.AddField(
            model_name="dutyarrange",
            name="work_day",
            field=models.JSONField(default=bkmonitor.models.strategy.default_work_days, verbose_name="值班日"),
        ),
        migrations.AddField(
            model_name="usergroup",
            name="need_duty",
            field=models.BooleanField(default=False, verbose_name="是否需要轮值"),
        ),
        migrations.AlterField(
            model_name="dutyarrange",
            name="duty_type",
            field=models.CharField(
                choices=[("date", "天"), ("week", "周"), ("month", "月"), ("always", "不分日夜")],
                default="always",
                max_length=32,
                verbose_name="值班类型",
            ),
        ),
    ]
