# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-30 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0077_merge_20211213_1707"),
        ("bkmonitor", "0077_merge_20211230_1522"),
    ]

    operations = []
