# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-01-18 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0079_auto_20220112_1736"),
        ("bkmonitor", "0078_merge_20211231_1058"),
    ]

    operations = []
