# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-02-11 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0079_update_frequency_week_list"),
        ("bkmonitor", "0080_merge_20220121_1524"),
    ]

    operations = []
