# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-03-29 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0051_fix_log_search_metric_id"),
        ("bkmonitor", "0081_merge_20220211_1130"),
    ]

    operations = []
