# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-03-25 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0081_merge_20220211_1130"),
        ("bkmonitor", "0082_auto_20220322_1517"),
    ]

    operations = []
