# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-01 08:13
from __future__ import unicode_literals

import bkmonitor.utils.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0082_merge_20220329_1634"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricListCache",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务ID")),
                ("result_table_id", models.CharField(default="", max_length=256, verbose_name="sql查询表")),
                ("result_table_name", models.CharField(default="", max_length=256, verbose_name="表别名")),
                ("metric_field", models.CharField(default="", max_length=256, verbose_name="指标名")),
                ("metric_field_name", models.CharField(default="", max_length=256, verbose_name="指标别名")),
                ("unit", models.CharField(default="", max_length=256, verbose_name="单位")),
                ("unit_conversion", models.FloatField(default=1.0, verbose_name="单位换算")),
                ("dimensions", bkmonitor.utils.db.fields.JsonField(default=[], verbose_name="维度名")),
                ("plugin_type", models.CharField(default="", max_length=256, verbose_name="插件类型")),
                ("related_name", models.CharField(default="", max_length=256, verbose_name="插件名、拨测任务名")),
                ("related_id", models.CharField(default="", max_length=256, verbose_name="插件id、拨测任务id")),
                ("collect_config", models.TextField(default="", verbose_name="插件采集关联采集配置")),
                ("collect_config_ids", bkmonitor.utils.db.fields.JsonField(verbose_name="插件采集关联采集配置id")),
                ("result_table_label", models.CharField(max_length=128, verbose_name="表标签")),
                ("data_source_label", models.CharField(max_length=128, verbose_name="数据源标签")),
                ("data_type_label", models.CharField(max_length=128, verbose_name="数据类型标签")),
                ("data_target", models.CharField(max_length=128, verbose_name="数据目标标签")),
                ("default_dimensions", bkmonitor.utils.db.fields.JsonField(verbose_name="默认维度列表")),
                ("default_condition", bkmonitor.utils.db.fields.JsonField(verbose_name="默认监控条件")),
                ("description", models.TextField(default="", verbose_name="指标含义")),
                ("collect_interval", models.IntegerField(default=1, verbose_name="指标采集周期")),
                ("category_display", models.CharField(default="", max_length=128, verbose_name="分类显示名")),
                ("result_table_label_name", models.CharField(default="", max_length=255, verbose_name="表标签别名")),
                ("extend_fields", bkmonitor.utils.db.fields.JsonField(default={}, verbose_name="额外字段")),
                ("use_frequency", models.IntegerField(default=0, verbose_name="使用频率")),
                ("last_update", models.DateTimeField(auto_now=True, db_index=True, verbose_name="最近更新时间")),
            ],
        ),
        migrations.AddField(
            model_name="strategymodel",
            name="is_invalid",
            field=models.BooleanField(default=False, verbose_name="是否失效"),
        ),
        migrations.AlterField(
            model_name="eventplugin",
            name="scenario",
            field=models.CharField(
                choices=[("MONITOR", "监控工具"), ("REST_API", "Rest API"), ("EMAIL", "Email")],
                default="MONITOR",
                max_length=64,
                verbose_name="场景",
            ),
        ),
        migrations.AlterField(
            model_name="shield",
            name="category",
            field=models.CharField(
                choices=[
                    ("scope", "范围屏蔽"),
                    ("strategy", "策略屏蔽"),
                    ("event", "事件屏蔽"),
                    ("alert", "告警屏蔽"),
                    ("dimension", "维度屏蔽"),
                ],
                max_length=32,
                verbose_name="屏蔽类型",
            ),
        ),
        migrations.AlterIndexTogether(
            name="metriclistcache",
            index_together={
                ("data_type_label", "data_source_label", "bk_biz_id"),
                ("result_table_id", "metric_field", "bk_biz_id"),
            },
        ),
    ]
