# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-03-30 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0083_merge_20220325_1617"),
        ("bkmonitor", "0082_merge_20220329_1634"),
    ]

    operations = []
