# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-08 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0083_auto_20220406_2105"),
    ]

    operations = [
        migrations.CreateModel(
            name="BCSClusterLabels",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bcs_cluster_id", models.CharField(max_length=128, verbose_name="集群ID")),
                (
                    "label",
                    models.ForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="bkmonitor.BCSLabel"
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="bkmonitor.BCSCluster"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="bcspod",
            name="labels",
            field=models.ManyToManyField(
                blank=True, null=True, through="bkmonitor.BCSPodLabels", to="bkmonitor.BCSLabel"
            ),
        ),
        migrations.AddField(
            model_name="bcscluster",
            name="labels",
            field=models.ManyToManyField(through="bkmonitor.BCSClusterLabels", to="bkmonitor.BCSLabel"),
        ),
    ]
