# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-11 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0084_auto_20220408_1521'),
        ('bkmonitor', '0083_auto_20220401_1613'),
    ]

    operations = [
    ]
