# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-11 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0083_auto_20220406_2105"),
        ("bkmonitor", "0085_auto_20220331_0953"),
    ]

    operations = []
