# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-12 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0086_merge_20220411_1142"),
        ("bkmonitor", "0085_merge_20220411_1112"),
    ]

    operations = []
