# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-18 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0087_merge_20220412_1454"),
    ]

    operations = [
        migrations.AddField(
            model_name="bcscontainer",
            name="resource_usage_cpu",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bcscontainer",
            name="resource_usage_disk",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="bcscontainer",
            name="resource_usage_memory",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="bcspod",
            name="resource_usage_cpu",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bcspod",
            name="resource_usage_disk",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="bcspod",
            name="resource_usage_memory",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="bcsworkload",
            name="resource_usage_cpu",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bcsworkload",
            name="resource_usage_disk",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="bcsworkload",
            name="resource_usage_memory",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="bcscontainer",
            name="resource_limits_cpu",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="bcscontainer",
            name="resource_requests_cpu",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="bcspod",
            name="resource_limits_cpu",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="bcspod",
            name="resource_requests_cpu",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="eventplugin",
            name="scenario",
            field=models.CharField(
                choices=[("MONITOR", "监控工具"), ("REST_API", "Rest API"), ("EMAIL", "电子邮件")],
                default="MONITOR",
                max_length=64,
                verbose_name="场景",
            ),
        ),
    ]
