# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-18 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0087_merge_20220412_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplugin',
            name='plugin_source',
            field=models.CharField(choices=[('builtin', '内置'), ('peripheral', '周边系统'), ('bk_plugin', '蓝鲸插件')], default='builtin', max_length=64, verbose_name='插件来源'),
        ),
    ]
