# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-13 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0083_update_trigger_config"),
        ("bkmonitor", "0087_merge_20220412_1454"),
    ]

    operations = []
