# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-15 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0087_merge_20220412_1454"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventplugin",
            name="scenario",
            field=models.CharField(
                choices=[("MONITOR", "监控工具"), ("REST_API", "Rest API"), ("EMAIL", "电子邮件")],
                default="MONITOR",
                max_length=64,
                verbose_name="场景",
            ),
        ),
    ]
