# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-18 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0088_auto_20220415_1635"),
        ("bkmonitor", "0088_auto_20220418_1530"),
    ]

    operations = []
