# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-20 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0090_strategymodel_invalid_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bcscluster",
            name="name",
            field=models.CharField(default="", max_length=128, verbose_name="集群名称"),
        ),
    ]
