# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-21 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0091_bcscluster_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bcscluster",
            name="bkmonitor_operator_deployed",
            field=models.BooleanField(default=False, verbose_name="bkmonitor operator部署状态", null=True),
        ),
        migrations.AddField(
            model_name="bcscluster",
            name="bkmonitor_operator_first_deployed",
            field=models.DateTimeField(null=True, verbose_name="bkmonitor operator首次部署时间"),
        ),
        migrations.AddField(
            model_name="bcscluster",
            name="bkmonitor_operator_last_deployed",
            field=models.DateTimeField(null=True, verbose_name="bkmonitor operator最后部署时间"),
        ),
        migrations.AddField(
            model_name="bcscluster",
            name="bkmonitor_operator_version",
            field=models.CharField(max_length=64, null=True, verbose_name="bkmonitor operator版本"),
        ),
        migrations.AlterField(
            model_name="bcscluster",
            name="name",
            field=models.CharField(max_length=128, verbose_name="集群名称"),
        ),
        migrations.AlterField(
            model_name="strategylabel",
            name="strategy_id",
            field=models.IntegerField(blank=True, default=0, verbose_name="策略ID"),
        ),
    ]
