# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-24 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0088_auto_20220418_1225"),
        ("bkmonitor", "0092_auto_20220421_1615"),
    ]

    operations = []
