# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-25 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0088_merge_20220413_1042'),
        ('bkmonitor', '0093_merge_20220424_1452'),
    ]

    operations = [
    ]
