# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-26 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0094_bcsnode_taints"),
    ]

    operations = [
        migrations.CreateModel(
            name="BCSMonitor",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(default=0, verbose_name="业务ID")),
                ("bcs_cluster_id", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(null=True)),
                ("status", models.CharField(default="", max_length=32)),
                ("monitor_status", models.CharField(default="", max_length=32)),
                ("last_synced_at", models.DateTimeField(verbose_name="同步时间")),
                ("unique_hash", models.CharField(max_length=32, null=True)),
                ("values_hash", models.CharField(max_length=32, null=True)),
                ("name", models.CharField(max_length=128)),
                ("namespace", models.CharField(max_length=128)),
                ("endpoints", models.CharField(max_length=32)),
                ("monitor_type", models.CharField(max_length=32)),
                ("metric_path", models.TextField()),
                ("metric_port", models.TextField()),
                ("metric_interval", models.TextField()),
                ("original_data", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="BCSMonitorLabels",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bcs_cluster_id", models.CharField(max_length=128, verbose_name="集群ID")),
                (
                    "label",
                    models.ForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="bkmonitor.BCSLabel"
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="bkmonitor.BCSMonitor"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bcsmonitor",
            name="labels",
            field=models.ManyToManyField(through="bkmonitor.BCSMonitorLabels", to="bkmonitor.BCSLabel"),
        ),
        migrations.AlterUniqueTogether(
            name="bcsmonitor",
            unique_together={("bcs_cluster_id", "namespace", "name")},
        ),
    ]
