# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-29 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0088_actioninstance_real_status"),
        ("bkmonitor", "0095_merge_20220426_2155"),
    ]

    operations = []
