# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-05-07 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0096_merge_20220429_1532"),
        ("bkmonitor", "0095_auto_20220426_1038"),
    ]

    operations = []
