# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-05-21 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0098_bk_monitorv3_202205122214"),
        ("bkmonitor", "0098_auto_20220517_2237"),
    ]

    operations = []
