# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-05-23 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0098_auto_20220517_2237"),
        ("bkmonitor", "0099_auto_20220520_1028"),
    ]

    operations = []
