# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-05-24 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0100_merge_20220523_1405"),
        ("bkmonitor", "0099_merge_20220521_2126"),
    ]

    operations = []
