# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-05-24 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0100_merge_20220523_1405"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatisticsMetric",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="指标名称")),
                ("data", models.BinaryField(verbose_name="指标数据")),
                ("update_time", models.IntegerField(verbose_name="指标更新时间")),
            ],
        ),
        migrations.AlterField(
            model_name="eventplugin",
            name="scenario",
            field=models.CharField(
                choices=[("MONITOR", "监控工具"), ("REST_API", "Rest API"), ("EMAIL", "电子邮件")],
                default="MONITOR",
                max_length=64,
                verbose_name="场景",
            ),
        ),
    ]
