# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-05-25 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0101_merge_20220524_1738"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bcscluster",
            name="bk_biz_id",
            field=models.IntegerField(db_index=True, default=0, verbose_name="业务ID"),
        ),
        migrations.AlterField(
            model_name="bcscluster",
            name="status",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="bcscontainer",
            name="bk_biz_id",
            field=models.IntegerField(db_index=True, default=0, verbose_name="业务ID"),
        ),
        migrations.AlterField(
            model_name="bcscontainer",
            name="status",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="bcsmonitor",
            name="bk_biz_id",
            field=models.IntegerField(db_index=True, default=0, verbose_name="业务ID"),
        ),
        migrations.AlterField(
            model_name="bcsmonitor",
            name="status",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="bcsnode",
            name="bk_biz_id",
            field=models.IntegerField(db_index=True, default=0, verbose_name="业务ID"),
        ),
        migrations.AlterField(
            model_name="bcsnode",
            name="status",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="bcspod",
            name="bk_biz_id",
            field=models.IntegerField(db_index=True, default=0, verbose_name="业务ID"),
        ),
        migrations.AlterField(
            model_name="bcspod",
            name="status",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="bcsservice",
            name="bk_biz_id",
            field=models.IntegerField(db_index=True, default=0, verbose_name="业务ID"),
        ),
        migrations.AlterField(
            model_name="bcsservice",
            name="status",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="bcsworkload",
            name="bk_biz_id",
            field=models.IntegerField(db_index=True, default=0, verbose_name="业务ID"),
        ),
        migrations.AlterField(
            model_name="bcsworkload",
            name="status",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="eventplugin",
            name="scenario",
            field=models.CharField(
                choices=[("MONITOR", "监控工具"), ("REST_API", "Rest API"), ("EMAIL", "电子邮件")],
                default="MONITOR",
                max_length=64,
                verbose_name="场景",
            ),
        ),
    ]
