# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-06-13 04:14
from __future__ import unicode_literals

import bkmonitor.utils.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0104_merge_20220608_2003"),
    ]

    operations = [
        migrations.AddField(
            model_name="bcsnode",
            name="resource_usage_cpu",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bcsnode",
            name="resource_usage_disk",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="bcsnode",
            name="resource_usage_memory",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="bcsworkload",
            name="container_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bcscontainer",
            name="resource_limits_cpu",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="bcscontainer",
            name="resource_limits_memory",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bcscontainer",
            name="resource_requests_cpu",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="bcscontainer",
            name="resource_requests_memory",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bcsmonitor",
            name="metric_interval",
            field=bkmonitor.utils.db.fields.JsonField(),
        ),
        migrations.AlterField(
            model_name="bcsmonitor",
            name="metric_path",
            field=bkmonitor.utils.db.fields.JsonField(),
        ),
        migrations.AlterField(
            model_name="bcsmonitor",
            name="metric_port",
            field=bkmonitor.utils.db.fields.JsonField(),
        ),
        migrations.AlterField(
            model_name="bcspod",
            name="resource_limits_cpu",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="bcspod",
            name="resource_limits_memory",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bcspod",
            name="resource_requests_cpu",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="bcspod",
            name="resource_requests_memory",
            field=models.BigIntegerField(default=0),
        ),
    ]
