# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-07-04 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0106_unit_fix"),
    ]

    operations = [
        migrations.CreateModel(
            name="BCSServiceMonitor",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(db_index=True, default=0, verbose_name="业务ID")),
                ("bcs_cluster_id", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(null=True)),
                ("status", models.CharField(db_index=True, default="", max_length=32)),
                ("monitor_status", models.CharField(default="", max_length=32)),
                ("last_synced_at", models.DateTimeField(verbose_name="同步时间")),
                ("unique_hash", models.CharField(max_length=32, null=True, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("namespace", models.CharField(max_length=128)),
                ("endpoints", models.CharField(max_length=32)),
                ("metric_path", models.CharField(max_length=32)),
                ("metric_port", models.CharField(max_length=32)),
                ("metric_interval", models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="BCSServiceMonitorLabels",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bcs_cluster_id", models.CharField(db_index=True, max_length=128, verbose_name="集群ID")),
                (
                    "label",
                    models.ForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="bkmonitor.BCSLabel"
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bkmonitor.BCSServiceMonitor",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="bcsmonitor",
            name="values_hash",
        ),
        migrations.AlterField(
            model_name="bcsworkload",
            name="resource_limits_cpu",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="bcsworkload",
            name="resource_limits_memory",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bcsworkload",
            name="resource_requests_cpu",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="bcsworkload",
            name="resource_requests_memory",
            field=models.BigIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="bcscluster",
            name="values_hash",
        ),
        migrations.AlterIndexTogether(
            name="bcscluster",
            index_together={("bk_biz_id", "bcs_cluster_id")},
        ),
        migrations.RemoveField(
            model_name="bcscontainer",
            name="values_hash",
        ),
        migrations.AlterIndexTogether(
            name="bcscontainer",
            index_together={("bk_biz_id", "bcs_cluster_id")},
        ),
        migrations.RemoveField(
            model_name="bcsnode",
            name="values_hash",
        ),
        migrations.AlterIndexTogether(
            name="bcsnode",
            index_together={("bk_biz_id", "bcs_cluster_id")},
        ),
        migrations.RemoveField(
            model_name="bcspod",
            name="values_hash",
        ),
        migrations.AlterIndexTogether(
            name="bcspod",
            index_together={("bk_biz_id", "bcs_cluster_id")},
        ),
        migrations.RemoveField(
            model_name="bcsservice",
            name="values_hash",
        ),
        migrations.AlterIndexTogether(
            name="bcsservice",
            index_together={("bk_biz_id", "bcs_cluster_id")},
        ),
        migrations.RemoveField(
            model_name="bcsworkload",
            name="values_hash",
        ),
        migrations.AlterIndexTogether(
            name="bcsworkload",
            index_together={("bk_biz_id", "bcs_cluster_id")},
        ),
        migrations.AddField(
            model_name="bcsservicemonitor",
            name="labels",
            field=models.ManyToManyField(through="bkmonitor.BCSServiceMonitorLabels", to="bkmonitor.BCSLabel"),
        ),
        migrations.AlterIndexTogether(
            name="bcsservicemonitor",
            index_together={("bk_biz_id", "bcs_cluster_id")},
        ),
    ]
