# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-08-19 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0111_auto_20220725_1506"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultStrategyBizAccessModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("create_user", models.CharField(max_length=32, verbose_name="创建者")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务ID")),
                ("version", models.CharField(max_length=32, verbose_name="版本")),
                (
                    "access_type",
                    models.CharField(
                        choices=[("os", "os"), ("gse", "gse"), ("k8s", "k8s")], max_length=32, verbose_name="接入类型"
                    ),
                ),
            ],
            options={
                "verbose_name": "默认策略业务接入",
                "verbose_name_plural": "默认策略业务接入",
                "db_table": "alarm_strategy_biz_access",
            },
        ),
        migrations.AlterUniqueTogether(
            name="defaultstrategybizaccessmodel",
            unique_together={("bk_biz_id", "access_type", "version")},
        ),
    ]
