# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-08-09 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0111_auto_20220725_1506"),
    ]

    operations = [
        migrations.AddField(
            model_name="bcscluster",
            name="space_uid",
            field=models.CharField(default="", max_length=64, verbose_name="空间唯一标识"),
        ),
    ]
