# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-09-20 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0113_merge_20220920_1433'),
        ('bkmonitor', '0113_migrate_event_plugin'),
    ]

    operations = []
