# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-09-23 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0114_merge_20220922_2027'),
        ('bkmonitor', '0114_merge_20220920_2100'),
    ]

    operations = []
