# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-09-22 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0113_iam_migration'),
        ('bkmonitor', '0114_merge_20220920_1639'),
    ]

    operations = []
