# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-09-23 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0115_merge_20220923_1537'),
        ('bkmonitor', '0115_iam_migration'),
    ]

    operations = []
