# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-09-28 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0117_merge_20220928_0928'),
        ('bkmonitor', '0115_merge_20220923_1528'),
    ]

    operations = []
