# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-10-09 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0112_auto_20220913_2002'),
        ('bkmonitor', '0117_merge_20220928_0928'),
    ]

    operations = []
