# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-10-24 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0118_merge_20221009_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='metriclistcache',
            name='is_duplicate',
            field=models.IntegerField(default=0, verbose_name='是否重名'),
        )
    ]
