# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-10-24 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0119_auto_20221009_1522'),
        ('bkmonitor', '0119_auto_20221024_1102'),
    ]

    operations = []
