# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-11-07 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0120_merge_20221024_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcspod',
            name='limit_cpu_usage_ratio',
            field=models.FloatField(default=0, null=True, verbose_name='CPU使用率(limit)'),
        ),
        migrations.AddField(
            model_name='bcspod',
            name='limit_memory_usage_ratio',
            field=models.FloatField(default=0, null=True, verbose_name='内存使用率(limit)'),
        ),
        migrations.AddField(
            model_name='bcspod',
            name='request_cpu_usage_ratio',
            field=models.FloatField(default=0, null=True, verbose_name='CPU使用率(request)'),
        ),
        migrations.AddField(
            model_name='bcspod',
            name='request_memory_usage_ratio',
            field=models.FloatField(default=0, null=True, verbose_name='内存使用率(request)'),
        ),
        migrations.AlterField(
            model_name='actioninstance',
            name='signal',
            field=models.CharField(
                choices=[
                    ('manual', '手动处理时'),
                    ('abnormal', '告警触发时'),
                    ('recovered', '告警恢复时'),
                    ('closed', '告警关闭时'),
                    ('no_data', '无数据时'),
                    ('collect', '汇总'),
                    ('execute', '执行动作时'),
                    ('execute_success', '执行成功时'),
                    ('execute_failed', '执行失败时'),
                    ('demo', '调试时'),
                    ('unshielded', '解除屏蔽时'),
                ],
                help_text='触发该事件的告警信号，如告警异常，告警恢复，告警关闭等',
                max_length=64,
                verbose_name='触发信号',
            ),
        ),
        migrations.AlterField(
            model_name='algorithmmodel',
            name='type',
            field=models.CharField(
                choices=[
                    ('Threshold', '静态阈值算法'),
                    ('SimpleRingRatio', '简易环比算法'),
                    ('AdvancedRingRatio', '高级环比算法'),
                    ('SimpleYearRound', '简易同比算法'),
                    ('AdvancedYearRound', '高级同比算法'),
                    ('PartialNodes', '部分节点数算法'),
                    ('OsRestart', '主机重启算法'),
                    ('ProcPort', '进程端口算法'),
                    ('PingUnreachable', 'Ping不可达算法'),
                    ('YearRoundAmplitude', '同比振幅算法'),
                    ('YearRoundRange', '同比区间算法'),
                    ('RingRatioAmplitude', '环比振幅算法'),
                    ('IntelligentDetect', '智能异常检测算法'),
                    ('TimeSeriesForecasting', '时序预测算法'),
                    ('AbnormalCluster', '离群检测算法'),
                ],
                db_index=True,
                max_length=64,
                verbose_name='算法类型',
            ),
        ),
        migrations.AlterField(
            model_name='eventplugin',
            name='status',
            field=models.CharField(
                choices=[
                    ('NO_DATA', '无数据'),
                    ('REMOVE_SOON', '将下架'),
                    ('REMOVED', '已下架'),
                    ('DISABLED', '已停用'),
                    ('AVAILABLE', '可用'),
                    ('DEBUG', '调试中'),
                ],
                default='AVAILABLE',
                max_length=32,
                verbose_name='状态',
            ),
        ),
        migrations.AlterField(
            model_name='eventpluginv2',
            name='ingest_config',
            field=models.JSONField(default=list, verbose_name='接入配置'),
        ),
        migrations.AlterField(
            model_name='eventpluginv2',
            name='status',
            field=models.CharField(
                choices=[
                    ('NO_DATA', '无数据'),
                    ('REMOVE_SOON', '将下架'),
                    ('REMOVED', '已下架'),
                    ('DISABLED', '已停用'),
                    ('AVAILABLE', '可用'),
                    ('DEBUG', '调试中'),
                ],
                default='AVAILABLE',
                max_length=32,
                verbose_name='状态',
            ),
        ),
    ]
