# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-11-12 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0119_merge_20221018_1507'),
        ('bkmonitor', '0120_merge_20221024_2108'),
    ]

    operations = []
