# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-11-17 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0121_auto_20221107_2022'),
        ('bkmonitor', '0121_merge_20221112_1709'),
    ]

    operations = []
