# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-20 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0122_merge_20221117_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcspod',
            name='node_ip',
            field=models.CharField(db_index=True, max_length=16, null=True),
        ),
    ]
