# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2022 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2022-01-05 06:48
from __future__ import unicode_literals

import logging

from django.db import migrations

from constants.data_source import DataSourceLabel

logger = logging.getLogger("bkmonitor")


def delete_apm_metric(apps, schema_editor):

    # 删除APM旧指标
    MetricListCache = apps.get_model("bkmonitor", "MetricListCache")
    metrics = MetricListCache.objects.filter(data_source_label=DataSourceLabel.BK_APM)
    count = metrics.count()
    metrics.delete()
    logger.info(f"[bkmonitor migration 0124_delete_apm_old_metric] {count} useless apm metric deleted")


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0123_auto_20221220_1652"),
    ]

    operations = [migrations.RunPython(delete_apm_metric)]
