# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-01-10 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0123_auto_20221220_1652'),
        ('bkmonitor', '0123_alertassigngroup_alertassignrule'),
    ]

    operations = []
