# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-02-06 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0124_delete_apm_old_metric'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAccessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_user', models.CharField(blank=True, default='', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(blank=True, default='', max_length=32, verbose_name='最后修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('token', models.CharField(max_length=32, verbose_name='鉴权令牌')),
            ],
            options={
                'verbose_name': 'API鉴权令牌访问记录',
                'verbose_name_plural': 'API鉴权令牌访问记录',
                'db_table': 'token_access_record',
            },
        ),
        migrations.AlterIndexTogether(
            name='tokenaccessrecord',
            index_together={('token', 'create_user')},
        ),
    ]
