# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-02-14 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0125_auto_20230112_1855'),
        ('bkmonitor', '0124_delete_apm_old_metric'),
    ]

    operations = []
