# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-01 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0125_auto_20230212_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcscontainer',
            name='node_ip',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bcsnode',
            name='ip',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='bcspod',
            name='node_ip',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bcspod',
            name='pod_ip',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bcsservice',
            name='cluster_ip',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='bcsservice',
            name='external_ip',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='eventpluginv2',
            name='ingest_config',
            field=models.JSONField(default=dict, verbose_name='接入配置'),
        ),
    ]
