# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-02 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0114_auto_20220805_1555'),
        ('bkmonitor', '0125_auto_20230212_2157'),
        ('bkmonitor', '0125_auto_20230206_1159'),
    ]

    operations = []
