# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-02-27 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0125_auto_20230212_2157'),
        ('bkmonitor', '0126_merge_20230214_1640'),
    ]

    operations = []
