# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-01 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0126_auto_20230301_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcsnode',
            name='bk_host_id',
            field=models.IntegerField(null=True),
        ),
    ]
