# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-08 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0124_auto_20230111_1106'),
        ('bkmonitor', '0126_merge_20230302_1937'),
    ]

    operations = []
