# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-10 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0127_merge_20230308_1749'),
        ('bkmonitor', '0124_ascodeimporttask'),
    ]

    operations = []
