# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-03 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0127_bcsnode_bk_host_id'),
        ('bkmonitor', '0126_merge_20230302_1937'),
    ]

    operations = []
