# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-22 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0128_merge_20230310_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategymodel',
            name='bk_biz_id',
            field=models.IntegerField(db_index=True, verbose_name='业务ID'),
        ),
        migrations.AlterIndexTogether(
            name='queryconfigmodel',
            index_together={('data_source_label', 'data_type_label')},
        ),
    ]
