# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-16 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0128_merge_20230303_1849'),
        ('bkmonitor', '0128_merge_20230310_1041'),
    ]

    operations = []
