# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-30 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0129_auto_20230322_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiauthtoken',
            name='type',
            field=models.CharField(
                choices=[
                    ('as_code', 'AsCode'),
                    ('grafana', 'Grafana'),
                    ('uptime_check', 'UptimeCheck'),
                    ('host', 'Host'),
                    ('collect', 'Collect'),
                    ('scene', 'Scene'),
                    ('custom_metric', 'CustomMetric'),
                    ('custom_event', 'CustomEvent'),
                    ('kubernetes', 'Kubernetes'),
                    ('event', 'Event'),
                    ('dashboard', 'Dashboard'),
                    ('apm', 'Apm'),
                ],
                max_length=32,
                verbose_name='鉴权类型',
            ),
        ),
        migrations.AlterField(
            model_name='bcspodmonitor',
            name='metric_path',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='bcsservicemonitor',
            name='metric_path',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='eventpluginv2',
            name='ingest_config',
            field=models.JSONField(default=dict, verbose_name='接入配置'),
        ),
    ]
