# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-23 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0129_auto_20230322_1516'),
        ('bkmonitor', '0129_merge_20230316_1715'),
    ]

    operations = []
