# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-28 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0129_auto_20230322_1516'),
        ('bkmonitor', '0130_merge_20230310_1843'),
    ]

    operations = []
