# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-04-06 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0131_merge_20230328_1830'),
        ('bkmonitor', '0130_auto_20230330_1124'),
    ]

    operations = []
