# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-04-19 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0132_auto_20230412_1801'),
        ('bkmonitor', '0132_merge_20230406_1858'),
    ]

    operations = []
