# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-05-16 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0134_auto_20230508_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_user', models.CharField(blank=True, default='', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(blank=True, default='', max_length=32, verbose_name='最后修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('bk_biz_id', models.IntegerField(db_index=True, verbose_name='业务ID')),
                ('authorized_user', models.CharField(max_length=64, verbose_name='被授权人')),
                (
                    'action_id',
                    models.CharField(
                        choices=[('view_grafana', 'view_grafana'), ('manage_grafana', 'manage_grafana')],
                        db_index=True,
                        max_length=32,
                        verbose_name='操作类型',
                    ),
                ),
                ('resources', models.JSONField(default=list, verbose_name='资源列表')),
                ('expire_time', models.DateTimeField(default=None, null=True, verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '外部权限',
                'verbose_name_plural': '外部权限',
                'db_table': 'external_permission',
            },
        ),
        migrations.CreateModel(
            name='ExternalPermissionApplyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_user', models.CharField(blank=True, default='', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(blank=True, default='', max_length=32, verbose_name='最后修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('bk_biz_id', models.IntegerField(db_index=True, verbose_name='业务ID')),
                ('authorized_users', models.JSONField(default=list, verbose_name='被授权人列表')),
                ('resources', models.JSONField(default=list, verbose_name='资源列表')),
                (
                    'action_id',
                    models.CharField(
                        choices=[('view_grafana', 'view_grafana'), ('manage_grafana', 'manage_grafana')],
                        db_index=True,
                        max_length=32,
                        verbose_name='操作类型',
                    ),
                ),
                (
                    'operate',
                    models.CharField(
                        choices=[('delete', '删除'), ('create', '创建'), ('update', '更新')],
                        db_index=True,
                        max_length=12,
                        verbose_name='操作',
                    ),
                ),
                ('expire_time', models.DateTimeField(default=None, null=True, verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '外部权限授权记录',
                'verbose_name_plural': '外部权限授权记录',
                'db_table': 'external_permission_apply_record',
            },
        ),
        migrations.AlterIndexTogether(
            name='externalpermission',
            index_together={('authorized_user', 'action_id', 'bk_biz_id')},
        ),
    ]
