# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-05-19 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0134_auto_20230508_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportitems',
            name='channels',
            field=models.JSONField(default=list, verbose_name='订阅渠道'),
        ),
    ]
