# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-05-22 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0135_auto_20230519_1738'),
        ('bkmonitor', '0135_auto_20230516_1527'),
    ]

    operations = []
