# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-05-19 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0135_auto_20230519_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventplugin',
            name='scenario',
            field=models.CharField(
                choices=[('MONITOR', '监控工具'), ('REST_API', 'Rest API'), ('EMAIL', 'Email'), ('KAFKA', 'Kafka')],
                default='MONITOR',
                max_length=64,
                verbose_name='场景',
            ),
        ),
        migrations.AlterField(
            model_name='eventpluginv2',
            name='scenario',
            field=models.CharField(
                choices=[('MONITOR', '监控工具'), ('REST_API', 'Rest API'), ('EMAIL', 'Email'), ('KAFKA', 'Kafka')],
                default='MONITOR',
                max_length=64,
                verbose_name='场景',
            ),
        ),
    ]
