# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-06-09 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0137_auto_20230601_1533'),
        ('bkmonitor', '0136_auto_20230519_1759'),
    ]

    operations = []
