# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-06-19 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0138_merge_20230609_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='channels',
            field=models.JSONField(default=list, verbose_name='告警通知渠道配置'),
        ),
    ]
