# Generated by Django 3.2.15 on 2023-06-13 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0138_merge_20230609_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bcsmonitorlabels',
            name='label',
        ),
        migrations.RemoveField(
            model_name='bcsmonitorlabels',
            name='resource',
        ),
        migrations.DeleteModel(
            name='BCSMonitor',
        ),
        migrations.DeleteModel(
            name='BCSMonitorLabels',
        ),
    ]
