# Generated by Django 3.2.15 on 2023-07-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0139_auto_20230613_1211'),
        ('bkmonitor', '0139_auto_20230619_1048'),
    ]

    operations = []
