# Generated by Django 3.2.15 on 2023-08-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0140_merge_0139_auto_20230613_1211_0139_auto_20230619_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachenode',
            name='cluster_name',
            field=models.CharField(default='default', max_length=128, verbose_name='集群名称'),
        ),
        migrations.AddField(
            model_name='cacherouter',
            name='cluster_name',
            field=models.CharField(default='default', max_length=128, verbose_name='集群名称'),
        ),
    ]
