# Generated by Django 3.2.15 on 2023-08-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0140_merge_0139_auto_20230613_1211_0139_auto_20230619_1048'),
    ]

    operations = []
