# Generated by Django 3.2.15 on 2023-08-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0141_auto_20230804_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategymodel',
            name='priority',
            field=models.IntegerField(null=True, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='strategymodel',
            name='priority_group_key',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='优先级分组'),
        ),
    ]
