# Generated by Django 3.2.15 on 2023-09-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0141_auto_20230824_1946'),
        ('bkmonitor', '0142_auto_20230821_1440'),
    ]

    operations = []
