# Generated by Django 3.2.15 on 2023-09-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0142_auto_20230814_1509'),
        ('bkmonitor', '0142_auto_20230821_1440'),
    ]

    operations = []
