# Generated by Django 3.2.15 on 2023-09-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0143_merge_0142_auto_20230814_1509_0142_auto_20230821_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertassigngroup',
            name='app',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='所属应用'),
        ),
        migrations.AddField(
            model_name='alertassigngroup',
            name='hash',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='原始配置摘要'),
        ),
        migrations.AddField(
            model_name='alertassigngroup',
            name='path',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='资源路径'),
        ),
        migrations.AddField(
            model_name='alertassigngroup',
            name='snippet',
            field=models.TextField(blank=True, default='', null=True, verbose_name='配置片段'),
        ),
    ]
