# Generated by Django 3.2.15 on 2023-09-12 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0143_auto_20230907_1552'),
        ('bkmonitor', '0143_merge_0142_auto_20230814_1509_0142_auto_20230821_1440'),
    ]

    operations = []
