# Generated by Django 3.2.15 on 2023-10-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0144_auto_20230913_1540'),
        ('bkmonitor', '0144_merge_20230912_1036'),
    ]

    operations = []
