# Generated by Django 3.2.15 on 2023-10-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0143_merge_0141_auto_20230824_1946_0142_auto_20230821_1440'),
        ('bkmonitor', '0145_merge_20231009_1524'),
    ]

    operations = []
