# Generated by Django 3.2.15 on 2023-10-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0147_usergroup_mention_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='mention_type',
            field=models.IntegerField(default=0, verbose_name='提醒类型'),
        ),
    ]
