# Generated by Django 3.2.15 on 2023-10-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0148_usergroup_mention_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=64, verbose_name='应用')),
                ('name', models.CharField(max_length=255, verbose_name='表名')),
                ('applied', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '监控迁移记录',
                'verbose_name_plural': '监控迁移记录',
                'db_table': 'monitor_migration',
                'unique_together': {('app', 'name')},
            },
        ),
    ]
