# Generated by Django 3.2.15 on 2023-12-15 02:46

from django.db import migrations, models

import bkmonitor.middlewares.source


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0149_monitormigration'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertassigngroup',
            name='source',
            field=models.CharField(
                blank=True,
                default=bkmonitor.middlewares.source.get_source_app_code,
                max_length=32,
                null=True,
                verbose_name='来源系统',
            ),
        ),
    ]
