# Generated by Django 3.2.15 on 2023-12-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0149_monitormigration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_user', models.CharField(blank=True, default='', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(blank=True, default='', max_length=32, verbose_name='最后修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='订阅名称')),
                ('bk_biz_id', models.IntegerField(db_index=True, default=0, verbose_name='业务ID')),
                (
                    'scenario',
                    models.CharField(
                        choices=[('clustering', '日志聚类'), ('dashboard', '仪表盘'), ('scene', '观测场景')],
                        max_length=32,
                        verbose_name='订阅场景',
                    ),
                ),
                ('frequency', models.JSONField(default=dict, verbose_name='发送频率')),
                ('content_config', models.JSONField(default=dict, verbose_name='内容配置')),
                ('scenario_config', models.JSONField(default=dict, verbose_name='场景配置')),
                ('start_time', models.IntegerField(null=True, verbose_name='开始时间')),
                ('end_time', models.IntegerField(null=True, verbose_name='结束时间')),
                (
                    'send_mode',
                    models.CharField(
                        choices=[('periodic', '周期发送'), ('one_time', '只发一次')], max_length=32, verbose_name='发送模式'
                    ),
                ),
                (
                    'subscriber_type',
                    models.CharField(choices=[('self', '仅自己'), ('others', '其他人')], max_length=32, verbose_name='订阅人类型'),
                ),
                ('send_round', models.IntegerField(default=0, verbose_name='最近一次发送轮次')),
                ('is_manager_created', models.BooleanField(default=False, verbose_name='是否管理员创建')),
            ],
            options={
                'verbose_name': '邮件订阅',
                'verbose_name_plural': '邮件订阅',
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='ReportApplyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_user', models.CharField(blank=True, default='', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(blank=True, default='', max_length=32, verbose_name='最后修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('report_id', models.IntegerField(db_index=True, verbose_name='订阅ID')),
                ('bk_biz_id', models.IntegerField(db_index=True, verbose_name='业务ID')),
                ('approvers', models.JSONField(default=list, verbose_name='审批人')),
                ('expire_time', models.DateTimeField(default=None, null=True, verbose_name='过期时间')),
                ('approval_step', models.JSONField(default=list, verbose_name='当前步骤')),
                (
                    'approval_sn',
                    models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='审批单号'),
                ),
                (
                    'approval_url',
                    models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='审批地址'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('RUNNING', '审批中'), ('SUCCESS', '审批成功'), ('FAILED', '审批失败')],
                        default='RUNNING',
                        max_length=32,
                        verbose_name='审批状态',
                    ),
                ),
            ],
            options={
                'verbose_name': '订阅审批记录',
                'verbose_name_plural': '订阅审批记录',
                'db_table': 'report_apply_record',
            },
        ),
        migrations.CreateModel(
            name='ReportChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField(db_index=True, verbose_name='订阅ID')),
                (
                    'channel_name',
                    models.CharField(
                        choices=[('email', '外部邮件'), ('wxbot', '企业微信机器人'), ('user', '内部用户')],
                        max_length=32,
                        verbose_name='渠道名称',
                    ),
                ),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('subscribers', models.JSONField(default=list, verbose_name='订阅人')),
                ('send_text', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='提示文案')),
            ],
            options={
                'verbose_name': '订阅渠道',
                'verbose_name_plural': '订阅渠道',
                'db_table': 'report_channel',
            },
        ),
        migrations.CreateModel(
            name='ReportSendRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField(db_index=True, verbose_name='订阅ID')),
                (
                    'channel_name',
                    models.CharField(
                        choices=[('email', '外部邮件'), ('wxbot', '企业微信机器人'), ('user', '内部用户')],
                        max_length=32,
                        verbose_name='渠道名称',
                    ),
                ),
                ('send_results', models.JSONField(default=list, verbose_name='发送结果详情')),
                (
                    'send_status',
                    models.CharField(
                        choices=[('success', '成功'), ('failed', '失败'), ('partial_failed', '部分失败'), ('no_status', '无')],
                        max_length=32,
                        verbose_name='发送状态',
                    ),
                ),
                ('send_time', models.DateTimeField(verbose_name='发送时间')),
                ('send_round', models.IntegerField(default=0, verbose_name='发送轮次')),
            ],
            options={
                'verbose_name': '订阅发送记录',
                'verbose_name_plural': '订阅发送记录',
                'db_table': 'report_send_record',
                'index_together': {('report_id', 'send_round')},
            },
        ),
    ]
