# Generated by Django 3.2.15 on 2023-11-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0149_monitormigration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_user', models.CharField(blank=True, default='', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(blank=True, default='', max_length=32, verbose_name='最后修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('bk_biz_id', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='业务ID')),
                ('name', models.CharField(max_length=128, verbose_name='轮值规则名称')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否开启')),
                (
                    'category',
                    models.CharField(
                        choices=[('regular', '常规值班'), ('handoff', '交替轮值')],
                        default='regular',
                        max_length=64,
                        verbose_name='轮值类型',
                    ),
                ),
                ('labels', models.JSONField(default=list, verbose_name='标签')),
                ('effective_time', models.CharField(db_index=True, max_length=32, null=True, verbose_name='配置生效时间')),
                (
                    'end_time',
                    models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='配置截止时间'),
                ),
                ('app', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='所属应用')),
                ('path', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='资源路径')),
                ('hash', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='原始配置摘要')),
                ('snippet', models.TextField(blank=True, default='', null=True, verbose_name='配置片段')),
            ],
            options={
                'verbose_name': '轮值规则',
                'verbose_name_plural': '轮值规则',
                'db_table': 'duty_rule',
            },
        ),
        migrations.CreateModel(
            name='DutyRuleRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_biz_id', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='业务ID')),
                ('user_group_id', models.IntegerField(db_index=True, verbose_name='用户组ID')),
                ('duty_rule_id', models.IntegerField(db_index=True, verbose_name='规则ID')),
                ('order', models.IntegerField(default=0, verbose_name='规则的顺序')),
            ],
            options={
                'verbose_name': '用户组轮值关系表',
                'verbose_name_plural': '用户组轮值关系表',
                'db_table': 'duty_rule_relation',
            },
        ),
        migrations.CreateModel(
            name='DutyRuleSnap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_rule_id', models.IntegerField(db_index=True, verbose_name='轮值组ID')),
                ('user_group_id', models.IntegerField(db_index=True, verbose_name='用户组ID')),
                ('first_effective_time', models.CharField(max_length=32, null=True, verbose_name='首次生效时间')),
                ('next_plan_time', models.CharField(max_length=32, null=True, verbose_name='下一次生效时间')),
                ('end_time', models.CharField(max_length=32, null=True, verbose_name='结束时间')),
                ('next_user_index', models.IntegerField(default=0, verbose_name='下一次轮岗用户组')),
                ('rule_snap', models.JSONField(default=dict, verbose_name='当前快照的配置内容')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否生效状态')),
            ],
            options={
                'verbose_name': '轮值规则快照',
                'verbose_name_plural': '轮值规则快照',
                'db_table': 'duty_rule_snap',
            },
        ),
        migrations.AddField(
            model_name='dutyarrange',
            name='duty_rule_id',
            field=models.IntegerField(db_index=True, null=True, verbose_name='轮值规则ID'),
        ),
        migrations.AddField(
            model_name='dutyarrange',
            name='group_number',
            field=models.IntegerField(default=0, verbose_name='每班人数'),
        ),
        migrations.AddField(
            model_name='dutyarrange',
            name='group_type',
            field=models.CharField(
                choices=[('specified', '手动指定'), ('auto', '自动')], default='specified', max_length=64, verbose_name='分组类型'
            ),
        ),
        migrations.AddField(
            model_name='dutyarrange',
            name='hash',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='原始配置摘要'),
        ),
        migrations.AddField(
            model_name='dutyplan',
            name='duty_rule_id',
            field=models.IntegerField(db_index=True, null=True, verbose_name='关联的告警信息'),
        ),
        migrations.AddField(
            model_name='dutyplan',
            name='finished_time',
            field=models.CharField(max_length=32, null=True, verbose_name='当前轮班生效结束时间'),
        ),
        migrations.AddField(
            model_name='dutyplan',
            name='is_effective',
            field=models.IntegerField(db_index=True, default=0, verbose_name='是否有效'),
        ),
        migrations.AddField(
            model_name='dutyplan',
            name='start_time',
            field=models.CharField(default='1970-01-01 00:00:00', max_length=32, verbose_name='当前轮班生效开始时间'),
        ),
        migrations.AddField(
            model_name='dutyplan',
            name='timezone',
            field=models.CharField(default='Asia/Shanghai', max_length=64, verbose_name='时区'),
        ),
        migrations.AddField(
            model_name='dutyplan',
            name='work_times',
            field=models.JSONField(default=list, verbose_name='工作时间段'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='duty_notice',
            field=models.JSONField(default=dict, verbose_name='轮值通知配置'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='duty_rules',
            field=models.JSONField(default=list, verbose_name='轮值规则'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='timezone',
            field=models.CharField(default='Asia/Shanghai', max_length=32, verbose_name='时区'),
        ),
        migrations.AlterField(
            model_name='dutyarrange',
            name='user_group_id',
            field=models.IntegerField(db_index=True, null=True, verbose_name='关联的告警组'),
        ),
        migrations.AlterField(
            model_name='dutyplan',
            name='begin_time',
            field=models.DateTimeField(null=True, verbose_name='当前轮班生效开始时间'),
        ),
        migrations.AlterField(
            model_name='dutyplan',
            name='duty_arrange_id',
            field=models.IntegerField(db_index=True, null=True, verbose_name='轮值组ID'),
        ),
        migrations.AlterField(
            model_name='dutyplan',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否生效状态（已废弃）'),
        ),
    ]
