# Generated by Django 3.2.15 on 2023-11-29 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0149_monitormigration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionApplyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.IntegerField(db_index=True, verbose_name='订阅ID')),
                ('bk_biz_id', models.IntegerField(db_index=True, verbose_name='业务ID')),
                ('approvers', models.JSONField(default=list, verbose_name='审批人列表')),
                ('expire_time', models.DateTimeField(default=None, null=True, verbose_name='过期时间')),
                (
                    'approval_step',
                    models.CharField(
                        choices=[
                            ('no_status', 'no_status'),
                            ('approval', 'approval'),
                            ('success', 'success'),
                            ('failed', 'failed'),
                        ],
                        default='no_status',
                        max_length=32,
                        verbose_name='审批步骤',
                    ),
                ),
                (
                    'approval_sn',
                    models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='审批单号'),
                ),
                (
                    'approval_url',
                    models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='审批地址'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('no_status', 'no_status'),
                            ('approval', 'approval'),
                            ('success', 'success'),
                            ('failed', 'failed'),
                        ],
                        default='no_status',
                        max_length=32,
                        verbose_name='审批状态',
                    ),
                ),
            ],
            options={
                'verbose_name': '订阅审批记录',
                'verbose_name_plural': '订阅审批记录',
                'db_table': 'subscription_apply_record',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.IntegerField(db_index=True, verbose_name='订阅ID')),
                ('channel_name', models.CharField(max_length=512, verbose_name='渠道名称')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('subscribers', models.JSONField(default=list, verbose_name='订阅人')),
            ],
            options={
                'verbose_name': '订阅渠道',
                'verbose_name_plural': '订阅渠道',
                'db_table': 'subscription_channel',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionSendRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.IntegerField(db_index=True, verbose_name='订阅ID')),
                ('channel_name', models.CharField(max_length=512, verbose_name='渠道名称')),
                ('send_results', models.JSONField(default=list, verbose_name='发送结果')),
                ('send_time', models.DateTimeField(null=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '订阅发送记录',
                'verbose_name_plural': '订阅发送记录',
                'db_table': 'subscription_send_record',
            },
        ),
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_user', models.CharField(blank=True, default='', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(blank=True, default='', max_length=32, verbose_name='最后修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('name', models.CharField(max_length=512, verbose_name='订阅名称')),
                ('bk_biz_id', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='业务ID')),
                (
                    'scenario',
                    models.CharField(
                        choices=[('clustering', '日志聚类'), ('dashboard', '仪表盘'), ('scene', '观测场景')],
                        max_length=32,
                        verbose_name='订阅场景',
                    ),
                ),
                ('frequency', models.JSONField(default=dict, verbose_name='发送频率')),
                ('content_config', models.JSONField(default=dict, verbose_name='内容配置')),
                ('scenario_config', models.JSONField(default=dict, verbose_name='场景配置')),
                ('last_send_time', models.DateTimeField(null=True, verbose_name='发送时间')),
                ('time_range', models.CharField(max_length=512, verbose_name='有效时间')),
                ('is_manager_created', models.BooleanField(default=False, verbose_name='是否管理员创建')),
                (
                    'channels',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='bkmonitor.subscriptionchannel',
                        verbose_name='订阅渠道',
                    ),
                ),
            ],
            options={
                'verbose_name': '邮件订阅',
                'verbose_name_plural': '邮件订阅',
                'db_table': 'email_subscription',
            },
        ),
    ]
