# Generated by Django 3.2.15 on 2023-10-28 03:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0145_auto_20231009_1153'),
        ('bkmonitor', '0149_monitormigration'),
    ]

    operations = []
