# Generated by Django 3.2.15 on 2023-12-15 06:40

from django.db import migrations, models

import bkmonitor.models.fta.action


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0149_monitormigration'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertassignrule',
            name='follower_groups',
            field=models.JSONField(default=list, verbose_name='关注人用户组'),
        ),
        migrations.AddField(
            model_name='strategyactionconfigrelation',
            name='follower_groups',
            field=models.JSONField(default=bkmonitor.models.fta.action.default_list, verbose_name='关注人用户组'),
        ),
        migrations.AlterField(
            model_name='alertassignrule',
            name='user_groups',
            field=models.JSONField(default=list, verbose_name='负责人用户组'),
        ),
    ]
