# Generated by Django 3.2.15 on 2023-11-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0150_merge_0145_auto_20231009_1153_0149_monitormigration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyRuleSnap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_rule_id', models.IntegerField(db_index=True, verbose_name='轮值组ID')),
                ('user_group_id', models.IntegerField(db_index=True, verbose_name='用户组ID')),
                ('first_effective_time', models.CharField(max_length=32, null=True, verbose_name='首次生效时间')),
                ('next_plan_time', models.CharField(max_length=32, null=True, verbose_name='下一次生效时间')),
                ('end_time', models.CharField(max_length=32, null=True, verbose_name='结束时间')),
                ('next_user_index', models.IntegerField(default=0, verbose_name='下一次轮岗用户组')),
                ('rule_snap', models.JSONField(default=dict, verbose_name='当前快照的配置内容')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否生效状态')),
            ],
            options={
                'verbose_name': '轮值规则快照',
                'verbose_name_plural': '轮值规则快照',
                'db_table': 'duty_rule_snap',
            },
        ),
        migrations.AddField(
            model_name='dutyplan',
            name='duty_rule_id',
            field=models.IntegerField(db_index=True, null=True, verbose_name='关联的告警信息'),
        ),
        migrations.AddField(
            model_name='dutyplan',
            name='finished_time',
            field=models.CharField(max_length=32, null=True, verbose_name='当前轮班生效结束时间'),
        ),
        migrations.AddField(
            model_name='dutyplan',
            name='is_effective',
            field=models.IntegerField(db_index=True, default=0, verbose_name='是否有效'),
        ),
        migrations.AddField(
            model_name='dutyplan',
            name='start_time',
            field=models.CharField(default='1970-01-01 00:00:00', max_length=32, verbose_name='当前轮班生效开始时间'),
        ),
        migrations.AddField(
            model_name='dutyplan',
            name='timezone',
            field=models.CharField(default='Asia/Shanghai', max_length=64, verbose_name='时区'),
        ),
        migrations.AddField(
            model_name='dutyplan',
            name='work_times',
            field=models.JSONField(default=list, verbose_name='工作时间段'),
        ),
        migrations.AlterField(
            model_name='dutyplan',
            name='begin_time',
            field=models.DateTimeField(null=True, verbose_name='当前轮班生效开始时间'),
        ),
        migrations.AlterField(
            model_name='dutyplan',
            name='duty_arrange_id',
            field=models.IntegerField(db_index=True, null=True, verbose_name='轮值组ID'),
        ),
        migrations.AlterField(
            model_name='dutyplan',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否生效状态（已废弃）'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='timezone',
            field=models.CharField(default='Asia/Shanghai', max_length=32, verbose_name='时区'),
        ),
    ]
