# Generated by Django 3.2.15 on 2023-12-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0150_alertassigngroup_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertassignrule',
            name='user_type',
            field=models.CharField(
                choices=[('main', '负责人'), ('follower', '负责人')], default='main', max_length=32, verbose_name='人员类型'
            ),
        ),
        migrations.AddField(
            model_name='strategyactionconfigrelation',
            name='user_type',
            field=models.CharField(
                choices=[('main', '负责人'), ('follower', '负责人')], default='main', max_length=32, verbose_name='人员类型'
            ),
        ),
        migrations.AlterField(
            model_name='alertassignrule',
            name='user_groups',
            field=models.JSONField(default=list, verbose_name='负责人用户组'),
        ),
    ]
