# Generated by Django 3.2.15 on 2023-11-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0150_auto_20231102_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyPlanSendRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_group_id', models.IntegerField(db_index=True, verbose_name='用户组ID')),
                ('last_send_time', models.IntegerField(default=0, verbose_name='最后发送时间戳')),
                ('notice_config', models.JSONField(default=dict, verbose_name='发送通知配置信息(留作记录)')),
            ],
            options={
                'verbose_name': '用户组排班计划发送表',
                'verbose_name_plural': '用户组排班计划发送表',
                'db_table': 'duty_plan_send_record',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='dutyplan',
            name='last_send_time',
            field=models.IntegerField(default=0, verbose_name='最近一次发送通知时间'),
        ),
    ]
