# Generated by Django 3.2.15 on 2023-12-26 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0150_alter_strategyhistorymodel_create_time'),
        ('bkmonitor', '0150_auto_20231214_1527'),
    ]

    operations = []
