# Generated by Django 3.2.15 on 2023-12-27 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0150_alter_strategyhistorymodel_create_time'),
        ('bkmonitor', '0151_auto_20231219_1701'),
    ]

    operations = []
