# Generated by Django 3.2.15 on 2023-11-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0152_auto_20231116_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyrule',
            name='code_hash',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='配置摘要(ascode)'),
        ),
    ]
