# Generated by Django 3.2.15 on 2023-12-21 02:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0151_auto_20231219_1701'),
        ('bkmonitor', '0153_dutyrule_code_hash'),
    ]

    operations = []
