# Generated by Django 3.2.15 on 2023-12-20 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0150_alertassigngroup_source'),
        ('bkmonitor', '0153_dutyrule_code_hash'),
    ]

    operations = []
