# Generated by Django 3.2.15 on 2023-12-28 03:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0150_alter_strategyhistorymodel_create_time'),
        ('bkmonitor', '0153_dutyrule_code_hash'),
    ]

    operations = []
