# Generated by Django 3.2.15 on 2023-12-28 03:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0152_eventplugininstance_token'),
        ('bkmonitor', '0154_merge_0151_auto_20231219_1701_0153_dutyrule_code_hash'),
        ('bkmonitor', '0154_merge_20231228_1100'),
    ]

    operations = []
