# Generated by Django 3.2.15 on 2023-12-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0154_emailsubscription_subscriptionapplyrecord_subscriptionchannel_subscriptionsendrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsubscription',
            name='last_send_time',
        ),
        migrations.AddField(
            model_name='emailsubscription',
            name='send_mode',
            field=models.CharField(
                choices=[('periodic', '周期发送'), ('one_time', '只发一次')],
                default='periodic',
                max_length=32,
                verbose_name='发送模式',
            ),
        ),
        migrations.AddField(
            model_name='emailsubscription',
            name='send_round',
            field=models.IntegerField(default=0, verbose_name='最近一次发送轮次'),
        ),
        migrations.AddField(
            model_name='emailsubscription',
            name='subscriber_type',
            field=models.CharField(
                choices=[('self', '仅自己'), ('others', '其他人')], default='others', max_length=32, verbose_name='订阅人类型'
            ),
        ),
        migrations.AddField(
            model_name='subscriptionsendrecord',
            name='send_round',
            field=models.IntegerField(default=0, verbose_name='发送轮次'),
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='bk_biz_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='业务ID'),
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='end_time',
            field=models.IntegerField(null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='start_time',
            field=models.IntegerField(null=True, verbose_name='开始时间'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionsendrecord',
            unique_together={('subscription_id', 'channel_name', 'send_round')},
        ),
        migrations.AlterIndexTogether(
            name='subscriptionsendrecord',
            index_together={('subscription_id', 'send_round')},
        ),
    ]
