# Generated by Django 3.2.15 on 2023-12-26 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0150_alter_strategyhistorymodel_create_time'),
        ('bkmonitor', '0150_auto_20231214_1527'),
        ('bkmonitor', '0154_merge_0151_auto_20231219_1701_0153_dutyrule_code_hash'),
    ]

    operations = []
