# Generated by Django 3.2.15 on 2023-12-29 03:36

from django.db import migrations, models

import bkmonitor.middlewares.source


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0154_merge_20231228_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertassigngroup',
            name='source',
            field=models.CharField(
                blank=True,
                default=bkmonitor.middlewares.source.get_source_app_code,
                max_length=32,
                null=True,
                verbose_name='来源系统',
            ),
        ),
        migrations.AddField(
            model_name='alertassignrule',
            name='user_type',
            field=models.CharField(
                choices=[('main', '负责人'), ('follower', '关注人')], default='main', max_length=32, verbose_name='人员类型'
            ),
        ),
        migrations.AddField(
            model_name='strategyactionconfigrelation',
            name='user_type',
            field=models.CharField(
                choices=[('main', '负责人'), ('follower', '关注人')], default='main', max_length=32, verbose_name='人员类型'
            ),
        ),
        migrations.AlterField(
            model_name='alertassignrule',
            name='user_groups',
            field=models.JSONField(default=list, verbose_name='负责人用户组'),
        ),
    ]
