# Generated by Django 3.2.15 on 2024-01-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0150_report_reportapplyrecord_reportchannel_reportsendrecord'),
        ('bkmonitor', '0155_auto_20231229_1136'),
    ]

    operations = [
    ]
