# Generated by Django 3.2.15 on 2024-01-12 03:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0155_auto_20231229_1136'),
        ('bkmonitor', '0155_auto_20231229_1455'),
    ]

    operations = []
