# Generated by Django 3.2.15 on 2023-12-26 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0152_eventplugininstance_token'),
        ('bkmonitor', '0155_merge_20231226_1608'),
    ]

    operations = []
