# Generated by Django 3.2.15 on 2024-01-15 09:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0155_auto_20231229_1455'),
        ('bkmonitor', '0156_migrate_duty_groups'),
    ]

    operations = []
