# Generated by Django 3.2.15 on 2024-01-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0150_report_reportapplyrecord_reportchannel_reportsendrecord'),
        ('bkmonitor', '0158_auto_20240117_1015'),
    ]

    operations = [
    ]
