# Generated by Django 3.2.15 on 2024-04-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0159_merge_20240118_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyplan',
            name='finished_time',
            field=models.CharField(db_index=True, max_length=32, null=True, verbose_name='当前轮班生效结束时间'),
        ),
    ]
