# Generated by Django 3.2.15 on 2024-04-26 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0159_migrate_strategy_dimension'),
        ('bkmonitor', '0160_alter_dutyplan_finished_time'),
        ('bkmonitor', '0160_migrate_real_time_strategy'),
    ]

    operations = []
