# Generated by Django 3.2.15 on 2024-08-13 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0164_auto_20240808_1118'),
        ('bkmonitor', '0164_update_strategy_config'),
    ]

    operations = []
