# Generated by Django 3.2.15 on 2024-11-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0165_merge_20240813_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiauthtoken',
            name='type',
            field=models.CharField(
                choices=[
                    ('as_code', 'AsCode'),
                    ('grafana', 'Grafana'),
                    ('api', 'API'),
                    ('uptime_check', 'UptimeCheck'),
                    ('host', 'Host'),
                    ('collect', 'Collect'),
                    ('scene', 'Scene'),
                    ('custom_metric', 'CustomMetric'),
                    ('custom_event', 'CustomEvent'),
                    ('kubernetes', 'Kubernetes'),
                    ('event', 'Event'),
                    ('dashboard', 'Dashboard'),
                    ('apm', 'Apm'),
                ],
                max_length=32,
                verbose_name='鉴权类型',
            ),
        ),
        migrations.AlterField(
            model_name='shield',
            name='scope_type',
            field=models.CharField(
                choices=[('instance', '实例'), ('ip', 'IP'), ('node', '节点'), ('biz', '业务'), ('dynamic_group', '动态分组')],
                max_length=32,
                verbose_name='屏蔽范围类型',
            ),
        ),
        migrations.AlterIndexTogether(
            name='metriclistcache',
            index_together={
                ('data_label', 'metric_field', 'bk_biz_id'),
                ('result_table_id', 'metric_field', 'bk_biz_id'),
                ('data_type_label', 'data_source_label', 'bk_biz_id'),
            },
        ),
    ]
