# Generated by Django 3.2.15 on 2024-12-25 11:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0168_auto_20241224_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderImageTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='任务ID')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('finish_time', models.DateTimeField(null=True, verbose_name='完成时间')),
                ('image', models.ImageField(null=True, upload_to='render/image/', verbose_name='图片')),
                ('options', models.JSONField(default=dict, verbose_name='图片渲染参数')),
                ('type', models.CharField(choices=[('dashboard', '仪表盘')], max_length=128, verbose_name='类型')),
                (
                    'status',
                    models.CharField(
                        choices=[('pending', '待渲染'), ('rendering', '渲染中'), ('success', '渲染成功'), ('failed', '渲染失败')],
                        max_length=128,
                        verbose_name='状态',
                    ),
                ),
                ('error', models.TextField(default='', verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '渲染图片任务',
                'verbose_name_plural': '渲染图片任务',
                'db_table': 'render_image_task',
            },
        ),
        migrations.AlterField(
            model_name='shield',
            name='label',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='strategymodel',
            name='invalid_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', ''),
                    ('invalid_related_strategy', '关联的策略已失效'),
                    ('deleted_related_strategy', '关联的策略已删除'),
                    ('invalid_unit', '指标和检测算法的单位类型不一致'),
                    ('invalid_target', '监控目标全部失效'),
                    ('invalid_metric', '监控指标不存在'),
                    ('invalid_biz', '策略所属业务不存在'),
                    ('invalid_dashboard_panel', '策略配置的仪表盘图表失效'),
                ],
                default='',
                max_length=32,
                verbose_name='失效类型',
            ),
        ),
        migrations.AlterField(
            model_name='strategymodel',
            name='type',
            field=models.CharField(
                choices=[('monitor', '监控'), ('fta', '故障自愈'), ('dashboard', '仪表盘')],
                db_index=True,
                max_length=12,
                verbose_name='策略类型',
            ),
        ),
    ]
