# Generated by Django 3.2.25 on 2025-01-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0170_auto_20241225_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderimagetask',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='开始时间'),
        ),
    ]
