# Generated by Django 3.2.25 on 2025-02-12 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0175_itemmodel_add_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCSIngress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bk_biz_id', models.IntegerField(db_index=True, default=0, verbose_name='业务ID')),
                ('bcs_cluster_id', models.CharField(db_index=True, max_length=32)),
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(null=True)),
                ('status', models.CharField(db_index=True, default='', max_length=32)),
                ('monitor_status', models.CharField(default='', max_length=32)),
                ('last_synced_at', models.DateTimeField(verbose_name='同步时间')),
                ('unique_hash', models.CharField(max_length=32, null=True, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('namespace', models.CharField(max_length=128)),
                ('class_name', models.CharField(max_length=128)),
                ('service_list', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BCSIngressLabels',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bcs_cluster_id', models.CharField(db_index=True, max_length=128, verbose_name='集群ID')),
                (
                    'label',
                    models.ForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='bkmonitor.bcslabel'
                    ),
                ),
                (
                    'resource',
                    models.ForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='bkmonitor.bcsingress'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='bcsingress',
            name='labels',
            field=models.ManyToManyField(through='bkmonitor.BCSIngressLabels', to='bkmonitor.BCSLabel'),
        ),
        migrations.AlterUniqueTogether(
            name='bcsingress',
            unique_together={('bcs_cluster_id', 'namespace', 'name')},
        ),
        migrations.AlterIndexTogether(
            name='bcsingress',
            index_together={('bk_biz_id', 'bcs_cluster_id')},
        ),
    ]
