# Generated by Django 3.2.25 on 2025-03-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0176_auto_20250212_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiauthtoken',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=64, verbose_name='租户ID'),
        ),
    ]
