# Generated by Django 3.2.25 on 2025-03-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bkmonitor', '0177_apiauthtoken_bk_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiauthtoken',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=128, verbose_name='租户ID'),
        ),
    ]
