# Generated by Django 3.2.25 on 2025-04-08 10:06

from django.db import migrations, models

def insert_initial_data(apps, *args, **kwargs):
    AlgorithmChoiceConfig = apps.get_model("bkmonitor", "AlgorithmChoiceConfig")
    variable_info = {'parameter': [{'variable_name': '$sensitivity', 'variable_alias': '敏感度', 'variable_type': 'parameter', 'value_type': 'int', 'default_value': '5', 'variable_value': None, 'constraint': [[{'allow_null': False, 'input_type': 'int'}]], 'description': '越大越容易检测出离群', 'sensitivity': 'public', 'properties': {'input_type': 'range', 'support': True, 'allow_null': False, 'allow_modified': True, 'is_advanced': False, 'allowed_values_map': [], 'used_by': 'user', 'max': 10, 'min': 0, 'closed': 'all', 'is_required': False, 'placeholder': 'u8d8au5c0fu8d8au5bb9u6613u68c0u6d4bu51fau79bbu7fa4', 'multiple': False}}]}
    AlgorithmChoiceConfig.objects.filter(id=2).update(variable_info=variable_info)


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0178_algorithmchoiceconfig'),
    ]
    operations = [
        migrations.RunPython(insert_initial_data),
    ]
