# Generated by Django 3.2.25 on 2025-04-08 10:06

from django.db import migrations, models

def insert_initial_data(apps, *args, **kwargs):
    AlgorithmChoiceConfig = apps.get_model("bkmonitor", "AlgorithmChoiceConfig")
    AlgorithmChoiceConfig.objects.create(
        id=6,
        alias='日志新类检测',
        name='log_patterns_anomaly_detection_with_dimensions',
        document='日志模式数异常检测是针对最近m天出现的日志新类进行检测，同时也提供日志新类出现后在持续关注的n天内进行规模检测的功能',
        description='',
        is_default=False,
        instruction='>**日志模式数异常检测**是针对最近m天出现的日志新类进行检测，同时也提供日志新类出现后在持续关注的n天内进行规模检测的功能\n ',
        variable_info={'parameter': [{'variable_name': '$model_file_id', 'variable_alias': '模型文件ID', 'variable_type': 'parameter', 'value_type': 'string', 'default_value': '', 'variable_value': '639_after_treat_model_20230704154315604_online_3', 'constraint': [[{'allow_null': False, 'input_type': 'string'}]], 'description': '', 'sensitivity': 'public', 'properties': {}}, {'variable_name': '$new_class_alert_th', 'variable_alias': '新类告警阈值', 'variable_type': 'parameter', 'value_type': 'int', 'default_value': '1', 'variable_value': '1', 'constraint': [[{'allow_null': False, 'input_type': 'int'}]], 'description': '', 'sensitivity': 'public', 'properties': {}}, {'variable_name': '$new_class_interval', 'variable_alias': '新类告警间隔', 'variable_type': 'parameter', 'value_type': 'int', 'default_value': '30', 'variable_value': '30', 'constraint': [[{'allow_null': False, 'input_type': 'int'}]], 'description': '', 'sensitivity': 'public', 'properties': {}}, {'variable_name': '$new_class_scale_alert', 'variable_alias': '是否进行新类规模告警', 'variable_type': 'parameter', 'value_type': 'int', 'default_value': '0', 'variable_value': '1', 'constraint': [[{'allow_null': False, 'input_type': 'int'}]], 'description': '', 'sensitivity': 'public', 'properties': {}}, {'variable_name': '$new_class_scale_alert_interval', 'variable_alias': '新类规模告警持续关注时间', 'variable_type': 'parameter', 'value_type': 'int', 'default_value': '1', 'variable_value': '1', 'constraint': [[{'allow_null': False, 'input_type': 'int'}]], 'description': '', 'sensitivity': 'public', 'properties': {}}, {'variable_name': '$new_class_scale_alert_th', 'variable_alias': '新类规模阈值', 'variable_type': 'parameter', 'value_type': 'int', 'default_value': '500', 'variable_value': '500', 'constraint': [[{'allow_null': False, 'input_type': 'int'}]], 'description': '', 'sensitivity': 'public', 'properties': {}}]},
        ts_freq=0,
        algorithm='IntelligentDetect',
        config={},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0179_algorithmchoiceconfig_update'),
    ]
    operations = [
        migrations.RunPython(insert_initial_data),
    ]
