# Generated by Django 3.2.25 on 2025-05-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0180_algorithmchoiceconfig_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actioninstance",
            name="signal",
            field=models.CharField(
                choices=[
                    ("manual", "手动处理时"),
                    ("abnormal", "告警触发时"),
                    ("recovered", "告警恢复时"),
                    ("closed", "告警关闭时"),
                    ("ack", "告警确认时"),
                    ("no_data", "无数据时"),
                    ("collect", "汇总"),
                    ("execute", "执行动作时"),
                    ("execute_success", "执行成功时"),
                    ("execute_failed", "执行失败时"),
                    ("demo", "调试时"),
                    ("unshielded", "解除屏蔽时"),
                    ("upgrade", "告警升级"),
                    ("incident", "故障生成时"),
                ],
                help_text="触发该事件的告警信号，如告警异常，告警恢复，告警关闭等",
                max_length=64,
                verbose_name="触发信号",
            ),
        ),
    ]
