# Generated by Django 3.2.25 on 2025-06-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0181_auto_20250520_1750"),
    ]

    operations = [
        migrations.AddField(
            model_name="metriclistcache",
            name="bk_tenant_id",
            field=models.CharField(default="system", max_length=128, verbose_name="租户ID"),
        ),
        migrations.AlterIndexTogether(
            name="metriclistcache",
            index_together={
                ("result_table_id", "metric_field", "bk_biz_id"),
                ("data_label", "metric_field", "bk_biz_id"),
                ("data_type_label", "data_source_label", "bk_biz_id"),
                ("bk_tenant_id", "bk_biz_id"),
            },
        ),
    ]
