# Generated by Django 3.2.25 on 2025-06-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0182_auto_20250611_1103"),
    ]

    operations = [
        migrations.AddField(
            model_name="bcscluster",
            name="bk_tenant_id",
            field=models.CharField(default="system", max_length=128, verbose_name="租户ID"),
        ),
    ]
