# Generated by Django 3.2.25 on 2025-04-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0183_bcscluster_bk_tenant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithmchoiceconfig",
            name="is_new_version",
            field=models.BooleanField(default=True, verbose_name="是否最新版本"),
        ),
        migrations.AddField(
            model_name="algorithmchoiceconfig",
            name="version_no",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
