# Generated by Django 3.2.25 on 2025-06-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0183_bcscluster_bk_tenant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportcontents",
            name="height",
            field=models.IntegerField(blank=True, null=True, verbose_name="单图高度"),
        ),
        migrations.AddField(
            model_name="reportcontents",
            name="width",
            field=models.IntegerField(blank=True, null=True, verbose_name="单图宽度"),
        ),
    ]
