# Generated by Django 3.2.25 on 2025-06-30 03:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0184_algorithmchoiceconfig_update"),
        ("bkmonitor", "0184_auto_20250627_1628"),
    ]

    operations = []
