# Generated by Django 3.2.25 on 2025-08-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0185_merge_20250630_1128"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoticeSubscribe",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(db_index=True, max_length=64, verbose_name="用户名")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务ID")),
                ("conditions", models.JSONField(default=list, verbose_name="条件组")),
                ("notice_ways", models.JSONField(default=list, verbose_name="通知方式")),
                (
                    "user_type",
                    models.CharField(
                        choices=[("main", "负责人"), ("follower", "关注人")],
                        default="follower",
                        max_length=32,
                        verbose_name="人员类型",
                    ),
                ),
                ("is_enable", models.BooleanField(default=True, verbose_name="是否启用")),
                ("priority", models.IntegerField(default=-1, verbose_name="优先级")),
            ],
            options={
                "verbose_name": "告警策略订阅",
                "verbose_name_plural": "告警策略订阅",
                "db_table": "notice_subscribe",
            },
        ),
    ]
