# Generated by Django 3.2.25 on 2025-08-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0185_merge_20250630_1128"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryTemplate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="最后修改人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="最后修改时间")),
                ("name", models.CharField(db_index=True, max_length=128, verbose_name="模板名称")),
                ("bk_biz_id", models.IntegerField(db_index=True, default=0, verbose_name="业务 ID")),
                ("space_scope", models.JSONField(default=list, verbose_name="生效范围")),
                (
                    "namespace",
                    models.CharField(db_index=True, default="DEFAULT", max_length=128, verbose_name="命名空间"),
                ),
                ("description", models.TextField(blank=True, default="", verbose_name="模板说明")),
                ("expression", models.TextField(verbose_name="计算公式")),
                ("functions", models.JSONField(default=list, verbose_name="计算函数")),
                ("query_configs", models.JSONField(default=list, verbose_name="查询配置")),
                ("variables", models.JSONField(default=list, verbose_name="模板变量")),
            ],
            options={
                "verbose_name": "查询模板",
                "verbose_name_plural": "查询模板",
                "unique_together": {("bk_biz_id", "name")},
                "index_together": {("bk_biz_id", "namespace", "name"), ("bk_biz_id", "name")},
            },
        ),
    ]
