# Generated by Django 3.2.25 on 2025-08-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0186_auto_20250820_0131"),
    ]

    operations = [
        migrations.AddField(
            model_name="querytemplate",
            name="alias",
            field=models.CharField(blank=True, default="", max_length=256, verbose_name="模板别名"),
        ),
    ]
