# Generated by Django 3.2.25 on 2025-08-28 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0186_auto_20250815_1531"),
        ("bkmonitor", "0187_auto_20250826_1608"),
    ]

    operations = []
