# Generated by Django 3.2.25 on 2025-09-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0188_merge_0186_auto_20250815_1531_0187_auto_20250826_1608"),
    ]

    operations = [
        migrations.AddField(
            model_name="querytemplate",
            name="unit",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="单位"),
        ),
    ]
