# Generated by Django 3.2.25 on 2025-09-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0188_merge_0186_auto_20250815_1531_0187_auto_20250826_1608"),
    ]

    operations = [
        migrations.AddField(
            model_name="querytemplate",
            name="bk_tenant_id",
            field=models.CharField(default="system", max_length=256, null=True, verbose_name="租户ID"),
        ),
        migrations.AlterUniqueTogether(
            name="querytemplate",
            unique_together={("bk_biz_id", "bk_tenant_id", "name")},
        ),
    ]
