# Generated by Django 3.2.25 on 2025-10-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0189_auto_20250924_1809"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticesubscribe",
            name="update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="修改时间"),
        ),
    ]
