# Generated by Django 3.2.25 on 2025-11-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0190_auto_20251020_1137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiauthtoken",
            name="type",
            field=models.CharField(
                choices=[
                    ("as_code", "AsCode"),
                    ("grafana", "Grafana"),
                    ("api", "API"),
                    ("uptime_check", "UptimeCheck"),
                    ("host", "Host"),
                    ("collect", "Collect"),
                    ("scene", "Scene"),
                    ("custom_metric", "CustomMetric"),
                    ("custom_event", "CustomEvent"),
                    ("kubernetes", "Kubernetes"),
                    ("event", "Event"),
                    ("dashboard", "Dashboard"),
                    ("apm", "Apm"),
                    ("incident", "Incident"),
                    ("entity", "Entity"),
                ],
                max_length=32,
                verbose_name="鉴权类型",
            ),
        ),
    ]
