# Generated by Django 3.2.25 on 2025-11-28 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0191_auto_20251106_2021"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="bcspod",
            index_together={("name", "bcs_cluster_id"), ("bk_biz_id", "bcs_cluster_id")},
        ),
    ]
