# Generated by Django 3.2.25 on 2025-06-30 03:28

from django.db import migrations


def update_intelligent(apps, *args, **kwargs):
    AlgorithmChoiceConfig = apps.get_model("bkmonitor", "AlgorithmChoiceConfig")
    description = "单指标异常检测_严格模式在单指标异常检测模式的基础上，新增了对阴跌（缓慢下降）情况的识别。"
    AlgorithmChoiceConfig.objects.filter(id=5).update(description=description)

    variable_info = {
        'parameter': [
            {'variable_name': '$model_file_id', 'variable_alias': '模型文件ID', 'variable_type': 'parameter',
             'value_type': 'string', 'default_value': '',
             'variable_value': '639_after_treat_model_20230704154315604_online_3',
             'constraint': [[{'allow_null': False, 'input_type': 'string'}]], 'description': '日志聚类模型应用的RT',
             'sensitivity': 'public',
             'properties': {}},
            {'variable_name': '$new_class_alert_th', 'variable_alias': '新类告警阈值', 'variable_type': 'parameter',
             'value_type': 'int', 'default_value': '1', 'variable_value': '1',
             'constraint': [[{'allow_null': False, 'input_type': 'int'}]],
             'description': '新类对应的日志产生多少条会告警', 'sensitivity': 'public',
             'properties': {}},
            {'variable_name': '$new_class_interval', 'variable_alias': '新类告警间隔', 'variable_type': 'parameter',
             'value_type': 'int', 'default_value': '30', 'variable_value': '30',
             'constraint': [[{'allow_null': False, 'input_type': 'int'}]],
             'description': '日志距离上一次出现间隔多久产生告警，单位：天', 'sensitivity': 'public',
             'properties': {}}, {'variable_name': '$new_class_scale_alert', 'variable_alias': '是否进行新类规模告警',
                                 'variable_type': 'parameter', 'value_type': 'int', 'default_value': '0',
                                 'variable_value': '1', 'constraint': [[{'allow_null': False, 'input_type': 'int'}]],
                                 'description': '', 'sensitivity': 'public', 'properties': {}},
            {'variable_name': '$new_class_scale_alert_interval', 'variable_alias': '新类规模告警持续关注时间',
             'variable_type': 'parameter', 'value_type': 'int', 'default_value': '1', 'variable_value': '1',
             'constraint': [[{'allow_null': False, 'input_type': 'int'}]],
             'description': '产生新类告警后，持续关注多久，单位：天', 'sensitivity': 'public',
             'properties': {}},
            {'variable_name': '$new_class_scale_alert_th', 'variable_alias': '新类规模阈值',
             'variable_type': 'parameter',
             'value_type': 'int', 'default_value': '500', 'variable_value': '500',
             'constraint': [[{'allow_null': False, 'input_type': 'int'}]],
             'description': '新类告警生成后，在「新类规模告警持续关注时间」内，日志条数大于多少条，产生告警',
             'sensitivity': 'public',
             'properties': {}}]}
    AlgorithmChoiceConfig.objects.filter(id=6).update(variable_info=variable_info)


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0192_auto_20251128_1733"),
    ]

    operations = [
        migrations.RunPython(
            code=update_intelligent,
        )
    ]
