# Generated by Django 3.2.25 on 2025-06-30 03:28

from django.db import migrations


def update_intelligent(apps,  *args, **kwargs):
    AlgorithmChoiceConfig = apps.get_model("bkmonitor", "AlgorithmChoiceConfig")
    description = "单指标异常检测_严格模式在单指标异常检测模式的基础上，新增了对阴跌（缓慢下降）情况的识别。"
    AlgorithmChoiceConfig.objects.filter(id=5).update(description=description)


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0192_auto_20251128_1733"),
    ]

    operations = [
        migrations.RunPython(
            code=update_intelligent,
        )
    ]