# Generated by Django migration for IssueTapdRelation model

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0197_strategylabel_covering_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueTapdRelation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="最后修改人")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务 ID")),
                ("issue_id", models.CharField(max_length=64, verbose_name="Issue ID")),
                ("workspace_id", models.IntegerField(verbose_name="TAPD 项目 ID")),
                ("tapd_id", models.IntegerField(verbose_name="TAPD 单据 ID")),
                (
                    "tapd_type",
                    models.CharField(
                        choices=[("story", "需求"), ("bug", "缺陷")],
                        max_length=16,
                        verbose_name="TAPD 单据类型",
                    ),
                ),
                (
                    "tapd_title",
                    models.CharField(default="", max_length=255, verbose_name="TAPD 单据标题"),
                ),
                (
                    "link_mode",
                    models.CharField(
                        choices=[("create", "新建单据"), ("link", "关联已有")],
                        default="create",
                        max_length=16,
                        verbose_name="关联模式",
                    ),
                ),
                ("sync_status", models.BooleanField(default=False, verbose_name="是否同步单据状态")),
            ],
            options={
                "verbose_name": "Issue TAPD 关联关系",
                "db_table": "bkmonitor_issue_tapd_relation",
            },
        ),
        migrations.AddConstraint(
            model_name="issuetapdrelation",
            constraint=models.UniqueConstraint(
                fields=("bk_biz_id", "issue_id", "workspace_id", "tapd_id"),
                name="uniq_issue_tapd",
            ),
        ),
    ]
