# Generated by Django 4.2.27 on 2026-06-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0199_tapd_workspace_binding"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuetapdrelation",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否删除"),
        ),
    ]
