# Generated by Django 4.2.27 on 2026-07-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0199_tapd_workspace_binding"),
    ]

    operations = [
        migrations.CreateModel(
            name="TapdWorkspaceManualUnbind",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="最后修改人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="最后修改时间")),
                ("bk_tenant_id", models.CharField(default="system", max_length=64, verbose_name="蓝鲸租户ID")),
                ("space_uid", models.CharField(max_length=128, verbose_name="蓝鲸空间唯一标识")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="蓝鲸CMDB业务ID")),
                ("tapd_workspace_id", models.CharField(max_length=64, verbose_name="TAPD项目ID")),
            ],
            options={
                "verbose_name": "TAPD项目手动解绑记录",
                "verbose_name_plural": "TAPD项目手动解绑记录",
                "db_table": "tapd_workspace_manual_unbind",
                "ordering": ["-create_time"],
                "unique_together": {("bk_tenant_id", "space_uid", "tapd_workspace_id")},
            },
        ),
    ]
