# Generated by Django 4.2.27 on 2026-08-05 05:28

import bkmonitor.utils.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0202_align_existing_model_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueSourceAnalysisConfig",
            fields=[
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="最后修改人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="最后修改时间")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("bk_biz_id", models.IntegerField(unique=True, verbose_name="业务 ID")),
                ("bkci_project_id", models.CharField(max_length=128, verbose_name="蓝盾项目 ID")),
                ("repository_alias", models.CharField(max_length=255, verbose_name="蓝盾代码库别名")),
            ],
            options={
                "verbose_name": "Issue 源码分析配置",
                "db_table": "bkmonitor_issue_source_analysis_config",
            },
        ),
        migrations.CreateModel(
            name="IssueSourceAnalysisRule",
            fields=[
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="最后修改人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="最后修改时间")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务 ID")),
                ("name", models.CharField(max_length=128, verbose_name="规则名称")),
                ("priority", models.IntegerField(verbose_name="优先级")),
                ("is_enabled", models.BooleanField(default=False, verbose_name="是否启用")),
                ("is_default", models.BooleanField(default=False, verbose_name="是否默认规则")),
                ("conditions", bkmonitor.utils.db.fields.JsonField(blank=True, default=list, verbose_name="匹配条件")),
                (
                    "repository_alias",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True, verbose_name="蓝盾代码库别名快照"
                    ),
                ),
                ("agent_ids", bkmonitor.utils.db.fields.JsonField(blank=True, default=list, verbose_name="智能体 ID")),
                ("skill_ids", bkmonitor.utils.db.fields.JsonField(blank=True, default=list, verbose_name="Skill ID")),
                (
                    "knowledge_base_ids",
                    bkmonitor.utils.db.fields.JsonField(blank=True, default=list, verbose_name="知识库 ID"),
                ),
            ],
            options={
                "verbose_name": "Issue 源码分析规则",
                "db_table": "bkmonitor_issue_source_analysis_rule",
                "ordering": ["-priority", "id"],
                "indexes": [
                    models.Index(
                        fields=["bk_biz_id", "is_deleted", "is_enabled", "priority"], name="idx_isar_biz_enabled_pri"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="issuesourceanalysisrule",
            constraint=models.UniqueConstraint(fields=("bk_biz_id", "priority"), name="uniq_issue_src_rule_priority"),
        ),
        migrations.AddConstraint(
            model_name="issuesourceanalysisrule",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("is_default", True), ("priority", -1)),
                    models.Q(("is_default", False), ("priority__gte", 0)),
                    _connector="OR",
                ),
                name="ck_issue_src_rule_priority",
            ),
        ),
    ]
