# Generated by Django 4.2.27 on 2026-08-07 09:12

import bkmonitor.models.source_analysis
import bkmonitor.utils.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0203_issue_source_analysis_config_rule"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueSourceAnalysisExecution",
            fields=[
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="最后修改人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="最后修改时间")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "analysis_id",
                    models.CharField(
                        default=bkmonitor.models.source_analysis.generate_analysis_id,
                        max_length=64,
                        unique=True,
                        verbose_name="分析记录 ID",
                    ),
                ),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务 ID")),
                ("issue_id", models.CharField(max_length=64, verbose_name="Issue ID")),
                (
                    "active_key",
                    models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name="活动记录标识"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待执行"),
                            ("running", "分析中"),
                            ("success", "分析完成"),
                            ("failed", "分析失败"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="主状态",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("waiting", "正在创建分析任务"),
                            ("source_preparing", "正在准备源码"),
                            ("analyzing", "正在结合告警证据分析源码"),
                            ("validating", "正在校验分析结果"),
                            ("archiving", "正在归档分析结果"),
                        ],
                        default=None,
                        max_length=32,
                        null=True,
                        verbose_name="执行阶段",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("initial", "首次分析"), ("retry", "失败重试"), ("reanalyze", "重新分析")],
                        default="initial",
                        max_length=16,
                        verbose_name="触发方式",
                    ),
                ),
                ("attempt", models.IntegerField(default=1, verbose_name="尝试次数")),
                (
                    "retry_of_analysis_id",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True, verbose_name="被重试的分析记录 ID"
                    ),
                ),
                ("alert_id", models.CharField(max_length=64, verbose_name="告警 ID")),
                ("rule_id", models.BigIntegerField(blank=True, default=None, null=True, verbose_name="命中规则 ID")),
                (
                    "rule_name",
                    models.CharField(blank=True, default="", max_length=128, verbose_name="命中规则名称快照"),
                ),
                (
                    "rule_priority",
                    models.IntegerField(blank=True, default=None, null=True, verbose_name="命中规则优先级快照"),
                ),
                ("bkci_project_id", models.CharField(max_length=128, verbose_name="蓝盾项目 ID 快照")),
                ("repository_alias", models.CharField(max_length=255, verbose_name="蓝盾代码库别名快照")),
                (
                    "agent_ids",
                    bkmonitor.utils.db.fields.JsonField(blank=True, default=list, verbose_name="智能体 ID 快照"),
                ),
                (
                    "skill_ids",
                    bkmonitor.utils.db.fields.JsonField(blank=True, default=list, verbose_name="Skill ID 快照"),
                ),
                (
                    "knowledge_base_ids",
                    bkmonitor.utils.db.fields.JsonField(blank=True, default=list, verbose_name="知识库 ID 快照"),
                ),
                (
                    "bkfara_task_id",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True, verbose_name="BKFara 任务 ID"
                    ),
                ),
                (
                    "bkci_pipeline_id",
                    models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name="蓝盾流水线 ID"),
                ),
                (
                    "bkci_build_id",
                    models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name="蓝盾构建 ID"),
                ),
                (
                    "failure_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("task_create", "创建分析任务"),
                            ("task_execute", "执行分析任务"),
                            ("source_prepare", "准备源码"),
                            ("ai_analysis", "AI 分析"),
                            ("result_validate", "校验分析结果"),
                            ("result_archive", "归档分析结果"),
                            ("result_fetch", "读取分析结果"),
                            ("result_persist", "持久化分析结果"),
                        ],
                        default=None,
                        max_length=32,
                        null=True,
                        verbose_name="失败阶段",
                    ),
                ),
                (
                    "failure_code",
                    models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name="失败错误码"),
                ),
                ("failure_message", models.TextField(blank=True, default="", verbose_name="失败提示")),
                ("failure_retryable", models.BooleanField(default=None, null=True, verbose_name="是否可重试")),
                (
                    "failure_request_id",
                    models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name="失败请求 ID"),
                ),
                (
                    "result_type",
                    models.CharField(
                        blank=True,
                        choices=[("HIGH_CONFIDENCE", "分析完成"), ("INSUFFICIENT_EVIDENCE", "分析完成（证据不足）")],
                        default=None,
                        max_length=32,
                        null=True,
                        verbose_name="结论类型",
                    ),
                ),
                (
                    "result_schema_version",
                    models.CharField(
                        blank=True, default=None, max_length=16, null=True, verbose_name="结果 Schema 版本"
                    ),
                ),
                (
                    "result_payload",
                    bkmonitor.utils.db.fields.JsonField(
                        blank=True, default=None, null=True, verbose_name="原始分析结果"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, default=None, null=True, verbose_name="开始执行时间")),
                ("finished_at", models.DateTimeField(blank=True, default=None, null=True, verbose_name="终态时间")),
            ],
            options={
                "verbose_name": "Issue 源码分析执行记录",
                "db_table": "bkmonitor_issue_source_analysis_execution",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["bk_biz_id", "issue_id", "-id"], name="idx_isae_biz_issue"),
                    models.Index(fields=["status"], name="idx_isae_status"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="issuesourceanalysisexecution",
            constraint=models.UniqueConstraint(fields=("bk_biz_id", "active_key"), name="uniq_issue_src_exec_active"),
        ),
    ]
