# Generated by Django 4.2.27 on 2026-08-21 07:17

import bkmonitor.utils.db.fields
import bkmonitor.utils.issue_id
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0203_align_existing_model_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueSourceAnalysisConfig",
            fields=[
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="最后修改人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="最后修改时间")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("bk_biz_id", models.IntegerField(unique=True, verbose_name="业务 ID")),
                ("bkci_project_id", models.CharField(max_length=128, verbose_name="蓝盾项目 ID")),
                ("repository_alias", models.CharField(max_length=255, verbose_name="蓝盾代码库别名")),
                (
                    "bkfara_provision_id",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True, verbose_name="BKFara 场景初始化 ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue 源码分析配置",
                "db_table": "bkmonitor_issue_source_analysis_config",
            },
        ),
        migrations.CreateModel(
            name="IssueSourceAnalysisExecution",
            fields=[
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="最后修改人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="最后修改时间")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "analysis_id",
                    models.CharField(
                        default=bkmonitor.utils.issue_id.generate_issue_style_id,
                        max_length=64,
                        unique=True,
                        verbose_name="分析记录 ID",
                    ),
                ),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务 ID")),
                ("issue_id", models.CharField(max_length=64, verbose_name="Issue ID")),
                (
                    "active_key",
                    models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name="活动记录标识"),
                ),
                ("status", models.CharField(default="pending", max_length=32, verbose_name="主状态")),
                (
                    "stage",
                    models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name="执行阶段"),
                ),
                ("trigger_type", models.CharField(default="initial", max_length=16, verbose_name="触发方式")),
                ("attempt", models.IntegerField(default=1, verbose_name="尝试次数")),
                (
                    "retry_of_analysis_id",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True, verbose_name="被重试的分析记录 ID"
                    ),
                ),
                ("alert_id", models.CharField(max_length=64, verbose_name="告警 ID")),
                ("rule_id", models.BigIntegerField(blank=True, default=None, null=True, verbose_name="命中规则 ID")),
                (
                    "rule_priority",
                    models.IntegerField(blank=True, default=None, null=True, verbose_name="命中规则优先级快照"),
                ),
                ("bkci_project_id", models.CharField(max_length=128, verbose_name="蓝盾项目 ID 快照")),
                ("repository_alias", models.CharField(max_length=255, verbose_name="蓝盾代码库别名快照")),
                ("agent_id", models.CharField(max_length=64, verbose_name="智能体 ID 快照")),
                (
                    "skill_ids",
                    bkmonitor.utils.db.fields.JsonField(blank=True, default=list, verbose_name="Skill ID 快照"),
                ),
                (
                    "knowledge_base_ids",
                    bkmonitor.utils.db.fields.JsonField(blank=True, default=list, verbose_name="知识库 ID 快照"),
                ),
                (
                    "bkfara_provision_id",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True, verbose_name="BKFara 场景初始化 ID 快照"
                    ),
                ),
                (
                    "bkfara_task_id",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True, verbose_name="BKFara 分析任务 ID"
                    ),
                ),
                (
                    "failure_stage",
                    models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name="失败阶段"),
                ),
                (
                    "failure_code",
                    models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name="失败错误码"),
                ),
                ("failure_message", models.TextField(blank=True, default="", verbose_name="失败提示")),
                ("failure_retryable", models.BooleanField(default=None, null=True, verbose_name="是否可重试")),
                (
                    "failure_request_id",
                    models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name="失败请求 ID"),
                ),
                (
                    "result_type",
                    models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name="结论类型"),
                ),
                (
                    "result_schema_version",
                    models.CharField(
                        blank=True, default=None, max_length=16, null=True, verbose_name="结果 Schema 版本"
                    ),
                ),
                (
                    "result_payload",
                    bkmonitor.utils.db.fields.JsonField(blank=True, default=None, null=True, verbose_name="分析结果"),
                ),
                ("started_at", models.DateTimeField(blank=True, default=None, null=True, verbose_name="开始执行时间")),
                ("finished_at", models.DateTimeField(blank=True, default=None, null=True, verbose_name="终态时间")),
            ],
            options={
                "verbose_name": "Issue 源码分析执行记录",
                "db_table": "bkmonitor_issue_source_analysis_execution",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="IssueSourceAnalysisRule",
            fields=[
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="最后修改人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="最后修改时间")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务 ID")),
                ("priority", models.IntegerField(verbose_name="优先级")),
                ("is_enabled", models.BooleanField(default=False, verbose_name="是否启用")),
                ("is_default", models.BooleanField(default=False, verbose_name="是否默认规则")),
                ("conditions", bkmonitor.utils.db.fields.JsonField(blank=True, default=list, verbose_name="匹配条件")),
                (
                    "bkci_project_id",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True, verbose_name="蓝盾项目 ID 快照"
                    ),
                ),
                (
                    "repository_alias",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True, verbose_name="蓝盾代码库别名快照"
                    ),
                ),
                ("agent_id", models.CharField(blank=True, default="", max_length=64, verbose_name="智能体 ID")),
                ("skill_ids", bkmonitor.utils.db.fields.JsonField(blank=True, default=list, verbose_name="Skill ID")),
                (
                    "knowledge_base_ids",
                    bkmonitor.utils.db.fields.JsonField(blank=True, default=list, verbose_name="知识库 ID"),
                ),
            ],
            options={
                "verbose_name": "Issue 源码分析规则",
                "db_table": "bkmonitor_issue_source_analysis_rule",
                "ordering": ["-priority", "id"],
                "indexes": [
                    models.Index(
                        fields=["bk_biz_id", "is_deleted", "is_enabled", "priority"], name="idx_isar_biz_enabled_pri"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="issuesourceanalysisrule",
            constraint=models.UniqueConstraint(fields=("bk_biz_id", "priority"), name="uniq_issue_src_rule_priority"),
        ),
        migrations.AddConstraint(
            model_name="issuesourceanalysisrule",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("is_default", True), ("priority", -1)),
                    models.Q(("is_default", False), ("priority__gte", 0)),
                    _connector="OR",
                ),
                name="ck_issue_src_rule_priority",
            ),
        ),
        migrations.AddIndex(
            model_name="issuesourceanalysisexecution",
            index=models.Index(fields=["bk_biz_id", "issue_id", "-id"], name="idx_isae_biz_issue"),
        ),
        migrations.AddIndex(
            model_name="issuesourceanalysisexecution",
            index=models.Index(fields=["status"], name="idx_isae_status"),
        ),
        migrations.AddConstraint(
            model_name="issuesourceanalysisexecution",
            constraint=models.UniqueConstraint(fields=("bk_biz_id", "active_key"), name="uniq_issue_src_exec_active"),
        ),
    ]
