# Generated by Django 4.2.27 on 2026-09-16 08:09

import bkmonitor.utils.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0207_issue_source_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuesourceanalysisexecution",
            name="execution_reference",
            field=bkmonitor.utils.db.fields.JsonField(
                blank=True, default=None, null=True, verbose_name="上游执行定位信息"
            ),
        ),
    ]
