# Generated by Django 4.2.27 on 2026-09-17 04:17

from django.db import migrations, models
from django.db.models import F


def backfill_source_analysis_run_as_user(apps, schema_editor):
    """Preserve the identity semantics used by records created before this field existed."""

    database_alias = schema_editor.connection.alias
    rule_model = apps.get_model("bkmonitor", "IssueSourceAnalysisRule")
    execution_model = apps.get_model("bkmonitor", "IssueSourceAnalysisExecution")

    rule_model.objects.using(database_alias).filter(run_as_user="").exclude(update_user="").update(
        run_as_user=F("update_user")
    )
    execution_model.objects.using(database_alias).filter(run_as_user="").exclude(create_user="").update(
        run_as_user=F("create_user")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0208_issuesourceanalysisexecution_execution_reference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issuesourceanalysisconfig",
            name="bkfara_provision_id",
        ),
        migrations.AddField(
            model_name="issuesourceanalysisexecution",
            name="run_as_user",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="规则执行用户快照"),
        ),
        migrations.AddField(
            model_name="issuesourceanalysisrule",
            name="run_as_user",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="规则执行用户"),
        ),
        migrations.RunPython(backfill_source_analysis_run_as_user, migrations.RunPython.noop),
    ]
