# Generated by Django 4.2.27 on 2026-09-23 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bkmonitor", "0206_item_access_lookback_periods"),
        ("bkmonitor", "0209_source_analysis_run_as_user"),
    ]

    operations = []
