# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""


from django.utils.translation import gettext_lazy as _lazy

ISP_LIST = [
    {"code": "2", "en": "China Unicom", "cn": _lazy("联通")},
    {"code": "3", "en": "China Mobile", "cn": _lazy("移动")},
    {"code": "1", "en": "China Telecom", "cn": _lazy("电信")},
]


CHINESE_PROVINCES = [
    {"code": "110000", "en": _lazy("北京"), "cn": _lazy("北京"), "children": []},
    {"code": "120000", "en": _lazy("天津"), "cn": _lazy("天津"), "children": []},
    {
        "code": "130000",
        "en": _lazy("河北"),
        "cn": _lazy("河北"),
        "children": [
            {"code": "130400", "en": _lazy("邯郸"), "cn": _lazy("邯郸")},
            {"code": "130500", "en": _lazy("邢台"), "cn": _lazy("邢台")},
            {"code": "130800", "en": _lazy("承德"), "cn": _lazy("承德")},
            {"code": "130600", "en": _lazy("保定"), "cn": _lazy("保定")},
            {"code": "130200", "en": _lazy("唐山"), "cn": _lazy("唐山")},
            {"code": "130700", "en": _lazy("张家口"), "cn": _lazy("张家口")},
            {"code": "130100", "en": _lazy("石家庄"), "cn": _lazy("石家庄")},
            {"code": "131000", "en": _lazy("廊坊"), "cn": _lazy("廊坊")},
            {"code": "130300", "en": _lazy("秦皇岛"), "cn": _lazy("秦皇岛")},
            {"code": "139000", "en": _lazy("省直辖县级行政区划"), "cn": _lazy("省直辖县级行政区划")},
            {"code": "130900", "en": _lazy("沧州"), "cn": _lazy("沧州")},
            {"code": "131100", "en": _lazy("衡水"), "cn": _lazy("衡水")},
        ],
    },
    {
        "code": "140000",
        "en": _lazy("山西"),
        "cn": _lazy("山西"),
        "children": [
            {"code": "140900", "en": _lazy("忻州"), "cn": _lazy("忻州")},
            {"code": "140800", "en": _lazy("运城"), "cn": _lazy("运城")},
            {"code": "141100", "en": _lazy("吕梁"), "cn": _lazy("吕梁")},
            {"code": "141000", "en": _lazy("临汾"), "cn": _lazy("临汾")},
            {"code": "140200", "en": _lazy("大同"), "cn": _lazy("大同")},
            {"code": "140600", "en": _lazy("朔州"), "cn": _lazy("朔州")},
            {"code": "140100", "en": _lazy("太原"), "cn": _lazy("太原")},
            {"code": "140500", "en": _lazy("晋城"), "cn": _lazy("晋城")},
            {"code": "140400", "en": _lazy("长治"), "cn": _lazy("长治")},
            {"code": "140300", "en": _lazy("阳泉"), "cn": _lazy("阳泉")},
            {"code": "140700", "en": _lazy("晋中"), "cn": _lazy("晋中")},
        ],
    },
    {
        "code": "150000",
        "en": _lazy("内蒙古"),
        "cn": _lazy("内蒙古"),
        "children": [
            {"code": "150400", "en": _lazy("赤峰"), "cn": _lazy("赤峰")},
            {"code": "150100", "en": _lazy("呼和浩特"), "cn": _lazy("呼和浩特")},
            {"code": "150500", "en": _lazy("通辽"), "cn": _lazy("通辽")},
            {"code": "150900", "en": _lazy("乌兰察布"), "cn": _lazy("乌兰察布")},
            {"code": "150600", "en": _lazy("鄂尔多斯"), "cn": _lazy("鄂尔多斯")},
            {"code": "152200", "en": _lazy("兴安盟"), "cn": _lazy("兴安盟")},
            {"code": "150700", "en": _lazy("呼伦贝尔"), "cn": _lazy("呼伦贝尔")},
            {"code": "150300", "en": _lazy("乌海"), "cn": _lazy("乌海")},
            {"code": "152900", "en": _lazy("阿拉善盟"), "cn": _lazy("阿拉善盟")},
            {"code": "150800", "en": _lazy("巴彦淖尔"), "cn": _lazy("巴彦淖尔")},
            {"code": "150200", "en": _lazy("包头"), "cn": _lazy("包头")},
            {"code": "152500", "en": _lazy("锡林郭勒盟"), "cn": _lazy("锡林郭勒盟")},
        ],
    },
    {
        "code": "210000",
        "en": _lazy("辽宁"),
        "cn": _lazy("辽宁"),
        "children": [
            {"code": "210900", "en": _lazy("阜新"), "cn": _lazy("阜新")},
            {"code": "210800", "en": _lazy("营口"), "cn": _lazy("营口")},
            {"code": "211300", "en": _lazy("朝阳"), "cn": _lazy("朝阳")},
            {"code": "210200", "en": _lazy("大连"), "cn": _lazy("大连")},
            {"code": "211000", "en": _lazy("辽阳"), "cn": _lazy("辽阳")},
            {"code": "211100", "en": _lazy("盘锦"), "cn": _lazy("盘锦")},
            {"code": "210600", "en": _lazy("丹东"), "cn": _lazy("丹东")},
            {"code": "210100", "en": _lazy("沈阳"), "cn": _lazy("沈阳")},
            {"code": "210500", "en": _lazy("本溪"), "cn": _lazy("本溪")},
            {"code": "211400", "en": _lazy("葫芦岛"), "cn": _lazy("葫芦岛")},
            {"code": "211200", "en": _lazy("铁岭"), "cn": _lazy("铁岭")},
            {"code": "210400", "en": _lazy("抚顺"), "cn": _lazy("抚顺")},
            {"code": "210300", "en": _lazy("鞍山"), "cn": _lazy("鞍山")},
            {"code": "210700", "en": _lazy("锦州"), "cn": _lazy("锦州")},
        ],
    },
    {
        "code": "220000",
        "en": _lazy("吉林"),
        "cn": _lazy("吉林"),
        "children": [
            {"code": "220200", "en": _lazy("吉林"), "cn": _lazy("吉林")},
            {"code": "220600", "en": _lazy("白山"), "cn": _lazy("白山")},
            {"code": "220400", "en": _lazy("辽源"), "cn": _lazy("辽源")},
            {"code": "222400", "en": _lazy("延边朝鲜族自治州"), "cn": _lazy("延边朝鲜族自治州")},
            {"code": "220300", "en": _lazy("四平"), "cn": _lazy("四平")},
            {"code": "220800", "en": _lazy("白城"), "cn": _lazy("白城")},
            {"code": "220100", "en": _lazy("长春"), "cn": _lazy("长春")},
            {"code": "220700", "en": _lazy("松原"), "cn": _lazy("松原")},
            {"code": "220500", "en": _lazy("通化"), "cn": _lazy("通化")},
        ],
    },
    {
        "code": "230000",
        "en": _lazy("黑龙江"),
        "cn": _lazy("黑龙江"),
        "children": [
            {"code": "230200", "en": _lazy("齐齐哈尔"), "cn": _lazy("齐齐哈尔")},
            {"code": "232700", "en": _lazy("大兴安岭地区"), "cn": _lazy("大兴安岭地区")},
            {"code": "231200", "en": _lazy("绥化"), "cn": _lazy("绥化")},
            {"code": "230400", "en": _lazy("鹤岗"), "cn": _lazy("鹤岗")},
            {"code": "230300", "en": _lazy("鸡西"), "cn": _lazy("鸡西")},
            {"code": "231000", "en": _lazy("牡丹江"), "cn": _lazy("牡丹江")},
            {"code": "231100", "en": _lazy("黑河"), "cn": _lazy("黑河")},
            {"code": "230900", "en": _lazy("七台河"), "cn": _lazy("七台河")},
            {"code": "230600", "en": _lazy("大庆"), "cn": _lazy("大庆")},
            {"code": "230700", "en": _lazy("伊春"), "cn": _lazy("伊春")},
            {"code": "230100", "en": _lazy("哈尔滨"), "cn": _lazy("哈尔滨")},
            {"code": "230800", "en": _lazy("佳木斯"), "cn": _lazy("佳木斯")},
            {"code": "230500", "en": _lazy("双鸭山"), "cn": _lazy("双鸭山")},
        ],
    },
    {"code": "310000", "en": _lazy("上海"), "cn": _lazy("上海"), "children": []},
    {
        "code": "320000",
        "en": _lazy("江苏"),
        "cn": _lazy("江苏"),
        "children": [
            {"code": "320300", "en": _lazy("徐州"), "cn": _lazy("徐州")},
            {"code": "321100", "en": _lazy("镇江"), "cn": _lazy("镇江")},
            {"code": "321200", "en": _lazy("泰州"), "cn": _lazy("泰州")},
            {"code": "321000", "en": _lazy("扬州"), "cn": _lazy("扬州")},
            {"code": "320200", "en": _lazy("无锡"), "cn": _lazy("无锡")},
            {"code": "320900", "en": _lazy("盐城"), "cn": _lazy("盐城")},
            {"code": "320700", "en": _lazy("连云港"), "cn": _lazy("连云港")},
            {"code": "320800", "en": _lazy("淮安"), "cn": _lazy("淮安")},
            {"code": "320600", "en": _lazy("南通"), "cn": _lazy("南通")},
            {"code": "320500", "en": _lazy("苏州"), "cn": _lazy("苏州")},
            {"code": "320100", "en": _lazy("南京"), "cn": _lazy("南京")},
            {"code": "320400", "en": _lazy("常州"), "cn": _lazy("常州")},
            {"code": "321300", "en": _lazy("宿迁"), "cn": _lazy("宿迁")},
        ],
    },
    {
        "code": "330000",
        "en": _lazy("浙江"),
        "cn": _lazy("浙江"),
        "children": [
            {"code": "330700", "en": _lazy("金华"), "cn": _lazy("金华")},
            {"code": "330300", "en": _lazy("温州"), "cn": _lazy("温州")},
            {"code": "330400", "en": _lazy("嘉兴"), "cn": _lazy("嘉兴")},
            {"code": "331000", "en": _lazy("台州"), "cn": _lazy("台州")},
            {"code": "330100", "en": _lazy("杭州"), "cn": _lazy("杭州")},
            {"code": "331100", "en": _lazy("丽水"), "cn": _lazy("丽水")},
            {"code": "330600", "en": _lazy("绍兴"), "cn": _lazy("绍兴")},
            {"code": "330200", "en": _lazy("宁波"), "cn": _lazy("宁波")},
            {"code": "330800", "en": _lazy("衢州"), "cn": _lazy("衢州")},
            {"code": "330900", "en": _lazy("舟山"), "cn": _lazy("舟山")},
            {"code": "330500", "en": _lazy("湖州"), "cn": _lazy("湖州")},
        ],
    },
    {
        "code": "340000",
        "en": _lazy("安徽"),
        "cn": _lazy("安徽"),
        "children": [
            {"code": "340300", "en": _lazy("蚌埠"), "cn": _lazy("蚌埠")},
            {"code": "341600", "en": _lazy("亳州"), "cn": _lazy("亳州")},
            {"code": "340800", "en": _lazy("安庆"), "cn": _lazy("安庆")},
            {"code": "340700", "en": _lazy("铜陵"), "cn": _lazy("铜陵")},
            {"code": "341200", "en": _lazy("阜阳"), "cn": _lazy("阜阳")},
            {"code": "340200", "en": _lazy("芜湖"), "cn": _lazy("芜湖")},
            {"code": "341800", "en": _lazy("宣城"), "cn": _lazy("宣城")},
            {"code": "340600", "en": _lazy("淮北"), "cn": _lazy("淮北")},
            {"code": "341100", "en": _lazy("滁州"), "cn": _lazy("滁州")},
            {"code": "340100", "en": _lazy("合肥"), "cn": _lazy("合肥")},
            {"code": "340500", "en": _lazy("马鞍山"), "cn": _lazy("马鞍山")},
            {"code": "341500", "en": _lazy("六安"), "cn": _lazy("六安")},
            {"code": "341000", "en": _lazy("黄山"), "cn": _lazy("黄山")},
            {"code": "341300", "en": _lazy("宿州"), "cn": _lazy("宿州")},
            {"code": "341700", "en": _lazy("池州"), "cn": _lazy("池州")},
            {"code": "340400", "en": _lazy("淮南"), "cn": _lazy("淮南")},
        ],
    },
    {
        "code": "350000",
        "en": _lazy("福建"),
        "cn": _lazy("福建"),
        "children": [
            {"code": "350300", "en": _lazy("莆田"), "cn": _lazy("莆田")},
            {"code": "350800", "en": _lazy("龙岩"), "cn": _lazy("龙岩")},
            {"code": "350100", "en": _lazy("福州"), "cn": _lazy("福州")},
            {"code": "350700", "en": _lazy("南平"), "cn": _lazy("南平")},
            {"code": "350500", "en": _lazy("泉州"), "cn": _lazy("泉州")},
            {"code": "350200", "en": _lazy("厦门"), "cn": _lazy("厦门")},
            {"code": "350900", "en": _lazy("宁德"), "cn": _lazy("宁德")},
            {"code": "350600", "en": _lazy("漳州"), "cn": _lazy("漳州")},
            {"code": "350400", "en": _lazy("三明"), "cn": _lazy("三明")},
        ],
    },
    {
        "code": "360000",
        "en": _lazy("江西"),
        "cn": _lazy("江西"),
        "children": [
            {"code": "360300", "en": _lazy("萍乡"), "cn": _lazy("萍乡")},
            {"code": "360200", "en": _lazy("景德镇"), "cn": _lazy("景德镇")},
            {"code": "361100", "en": _lazy("上饶"), "cn": _lazy("上饶")},
            {"code": "361000", "en": _lazy("抚州"), "cn": _lazy("抚州")},
            {"code": "360100", "en": _lazy("南昌"), "cn": _lazy("南昌")},
            {"code": "360500", "en": _lazy("新余"), "cn": _lazy("新余")},
            {"code": "360400", "en": _lazy("九江"), "cn": _lazy("九江")},
            {"code": "360800", "en": _lazy("吉安"), "cn": _lazy("吉安")},
            {"code": "360700", "en": _lazy("赣州"), "cn": _lazy("赣州")},
            {"code": "360600", "en": _lazy("鹰潭"), "cn": _lazy("鹰潭")},
            {"code": "360900", "en": _lazy("宜春"), "cn": _lazy("宜春")},
        ],
    },
    {
        "code": "370000",
        "en": _lazy("山东"),
        "cn": _lazy("山东"),
        "children": [
            {"code": "370800", "en": _lazy("济宁"), "cn": _lazy("济宁")},
            {"code": "371500", "en": _lazy("聊城"), "cn": _lazy("聊城")},
            {"code": "370300", "en": _lazy("淄博"), "cn": _lazy("淄博")},
            {"code": "371100", "en": _lazy("日照"), "cn": _lazy("日照")},
            {"code": "370700", "en": _lazy("潍坊"), "cn": _lazy("潍坊")},
            {"code": "370900", "en": _lazy("泰安"), "cn": _lazy("泰安")},
            {"code": "371400", "en": _lazy("德州"), "cn": _lazy("德州")},
            {"code": "370400", "en": _lazy("枣庄"), "cn": _lazy("枣庄")},
            {"code": "371000", "en": _lazy("威海"), "cn": _lazy("威海")},
            {"code": "371700", "en": _lazy("菏泽"), "cn": _lazy("菏泽")},
            {"code": "370100", "en": _lazy("济南"), "cn": _lazy("济南")},
            {"code": "371300", "en": _lazy("临沂"), "cn": _lazy("临沂")},
            {"code": "370500", "en": _lazy("东营"), "cn": _lazy("东营")},
            {"code": "371600", "en": _lazy("滨州"), "cn": _lazy("滨州")},
            {"code": "370200", "en": _lazy("青岛"), "cn": _lazy("青岛")},
            {"code": "371200", "en": _lazy("莱芜"), "cn": _lazy("莱芜")},
            {"code": "370600", "en": _lazy("烟台"), "cn": _lazy("烟台")},
        ],
    },
    {
        "code": "410000",
        "en": _lazy("河南"),
        "cn": _lazy("河南"),
        "children": [
            {"code": "410300", "en": _lazy("洛阳"), "cn": _lazy("洛阳")},
            {"code": "411400", "en": _lazy("商丘"), "cn": _lazy("商丘")},
            {"code": "410800", "en": _lazy("焦作"), "cn": _lazy("焦作")},
            {"code": "410700", "en": _lazy("新乡"), "cn": _lazy("新乡")},
            {"code": "411200", "en": _lazy("三门峡"), "cn": _lazy("三门峡")},
            {"code": "410200", "en": _lazy("开封"), "cn": _lazy("开封")},
            {"code": "410600", "en": _lazy("鹤壁"), "cn": _lazy("鹤壁")},
            {"code": "411700", "en": _lazy("驻马店"), "cn": _lazy("驻马店")},
            {"code": "411100", "en": _lazy("漯河"), "cn": _lazy("漯河")},
            {"code": "410100", "en": _lazy("郑州"), "cn": _lazy("郑州")},
            {"code": "410500", "en": _lazy("安阳"), "cn": _lazy("安阳")},
            {"code": "411500", "en": _lazy("信阳"), "cn": _lazy("信阳")},
            {"code": "411600", "en": _lazy("周口"), "cn": _lazy("周口")},
            {"code": "411000", "en": _lazy("许昌"), "cn": _lazy("许昌")},
            {"code": "410900", "en": _lazy("濮阳"), "cn": _lazy("濮阳")},
            {"code": "411300", "en": _lazy("南阳"), "cn": _lazy("南阳")},
            {"code": "419000", "en": _lazy("省直辖县级行政区划"), "cn": _lazy("省直辖县级行政区划")},
            {"code": "410400", "en": _lazy("平顶山"), "cn": _lazy("平顶山")},
        ],
    },
    {
        "code": "420000",
        "en": _lazy("湖北"),
        "cn": _lazy("湖北"),
        "children": [
            {"code": "420300", "en": _lazy("十堰"), "cn": _lazy("十堰")},
            {"code": "420700", "en": _lazy("鄂州"), "cn": _lazy("鄂州")},
            {"code": "421300", "en": _lazy("随州"), "cn": _lazy("随州")},
            {"code": "420500", "en": _lazy("宜昌"), "cn": _lazy("宜昌")},
            {"code": "429000", "en": _lazy("省直辖县级行政区划"), "cn": _lazy("省直辖县级行政区划")},
            {"code": "420200", "en": _lazy("黄石"), "cn": _lazy("黄石")},
            {"code": "421200", "en": _lazy("咸宁"), "cn": _lazy("咸宁")},
            {"code": "420600", "en": _lazy("襄阳"), "cn": _lazy("襄阳")},
            {"code": "420800", "en": _lazy("荆门"), "cn": _lazy("荆门")},
            {"code": "421100", "en": _lazy("黄冈"), "cn": _lazy("黄冈")},
            {"code": "420900", "en": _lazy("孝感"), "cn": _lazy("孝感")},
            {"code": "421000", "en": _lazy("荆州"), "cn": _lazy("荆州")},
            {"code": "420100", "en": _lazy("武汉"), "cn": _lazy("武汉")},
            {"code": "422800", "en": _lazy("恩施土家族苗族自治州"), "cn": _lazy("恩施土家族苗族自治州")},
        ],
    },
    {
        "code": "430000",
        "en": _lazy("湖南"),
        "cn": _lazy("湖南"),
        "children": [
            {"code": "430300", "en": _lazy("湘潭"), "cn": _lazy("湘潭")},
            {"code": "430200", "en": _lazy("株洲"), "cn": _lazy("株洲")},
            {"code": "433100", "en": _lazy("湘西土家族苗族自治州"), "cn": _lazy("湘西土家族苗族自治州")},
            {"code": "431100", "en": _lazy("永州"), "cn": _lazy("永州")},
            {"code": "431000", "en": _lazy("郴州"), "cn": _lazy("郴州")},
            {"code": "431200", "en": _lazy("怀化"), "cn": _lazy("怀化")},
            {"code": "430100", "en": _lazy("长沙"), "cn": _lazy("长沙")},
            {"code": "430500", "en": _lazy("邵阳"), "cn": _lazy("邵阳")},
            {"code": "431300", "en": _lazy("娄底"), "cn": _lazy("娄底")},
            {"code": "430400", "en": _lazy("衡阳"), "cn": _lazy("衡阳")},
            {"code": "430800", "en": _lazy("张家界"), "cn": _lazy("张家界")},
            {"code": "430700", "en": _lazy("常德"), "cn": _lazy("常德")},
            {"code": "430600", "en": _lazy("岳阳"), "cn": _lazy("岳阳")},
            {"code": "430900", "en": _lazy("益阳"), "cn": _lazy("益阳")},
        ],
    },
    {
        "code": "440000",
        "en": _lazy("广东"),
        "cn": _lazy("广东"),
        "children": [
            {"code": "441600", "en": _lazy("河源"), "cn": _lazy("河源")},
            {"code": "440700", "en": _lazy("江门"), "cn": _lazy("江门")},
            {"code": "442000", "en": _lazy("中山"), "cn": _lazy("中山")},
            {"code": "440300", "en": _lazy("深圳"), "cn": _lazy("深圳")},
            {"code": "440800", "en": _lazy("湛江"), "cn": _lazy("湛江")},
            {"code": "441400", "en": _lazy("梅州"), "cn": _lazy("梅州")},
            {"code": "440400", "en": _lazy("珠海"), "cn": _lazy("珠海")},
            {"code": "441200", "en": _lazy("肇庆"), "cn": _lazy("肇庆")},
            {"code": "441800", "en": _lazy("清远"), "cn": _lazy("清远")},
            {"code": "441300", "en": _lazy("惠州"), "cn": _lazy("惠州")},
            {"code": "440900", "en": _lazy("茂名"), "cn": _lazy("茂名")},
            {"code": "441500", "en": _lazy("汕尾"), "cn": _lazy("汕尾")},
            {"code": "445300", "en": _lazy("云浮"), "cn": _lazy("云浮")},
            {"code": "440500", "en": _lazy("汕头"), "cn": _lazy("汕头")},
            {"code": "441900", "en": _lazy("东莞"), "cn": _lazy("东莞")},
            {"code": "445100", "en": _lazy("潮州"), "cn": _lazy("潮州")},
            {"code": "440100", "en": _lazy("广州"), "cn": _lazy("广州")},
            {"code": "440600", "en": _lazy("佛山"), "cn": _lazy("佛山")},
            {"code": "445200", "en": _lazy("揭阳"), "cn": _lazy("揭阳")},
            {"code": "440200", "en": _lazy("韶关"), "cn": _lazy("韶关")},
            {"code": "441700", "en": _lazy("阳江"), "cn": _lazy("阳江")},
        ],
    },
    {
        "code": "450000",
        "en": _lazy("广西"),
        "cn": _lazy("广西"),
        "children": [
            {"code": "451100", "en": _lazy("贺州"), "cn": _lazy("贺州")},
            {"code": "450800", "en": _lazy("贵港"), "cn": _lazy("贵港")},
            {"code": "450500", "en": _lazy("北海"), "cn": _lazy("北海")},
            {"code": "451300", "en": _lazy("来宾"), "cn": _lazy("来宾")},
            {"code": "451000", "en": _lazy("百色"), "cn": _lazy("百色")},
            {"code": "450400", "en": _lazy("梧州"), "cn": _lazy("梧州")},
            {"code": "451400", "en": _lazy("崇左"), "cn": _lazy("崇左")},
            {"code": "450900", "en": _lazy("玉林"), "cn": _lazy("玉林")},
            {"code": "450700", "en": _lazy("钦州"), "cn": _lazy("钦州")},
            {"code": "450300", "en": _lazy("桂林"), "cn": _lazy("桂林")},
            {"code": "450600", "en": _lazy("防城港"), "cn": _lazy("防城港")},
            {"code": "451200", "en": _lazy("河池"), "cn": _lazy("河池")},
            {"code": "450200", "en": _lazy("柳州"), "cn": _lazy("柳州")},
            {"code": "450100", "en": _lazy("南宁"), "cn": _lazy("南宁")},
        ],
    },
    {
        "code": "460000",
        "en": _lazy("海南"),
        "cn": _lazy("海南"),
        "children": [
            {"code": "460400", "en": _lazy("儋州"), "cn": _lazy("儋州")},
            {"code": "469000", "en": _lazy("省直辖县级行政区划"), "cn": _lazy("省直辖县级行政区划")},
            {"code": "460100", "en": _lazy("海口"), "cn": _lazy("海口")},
            {"code": "460200", "en": _lazy("三亚"), "cn": _lazy("三亚")},
            {"code": "460300", "en": _lazy("三沙"), "cn": _lazy("三沙")},
        ],
    },
    {"code": "500000", "en": _lazy("重庆"), "cn": _lazy("重庆"), "children": []},
    {
        "code": "510000",
        "en": _lazy("四川"),
        "cn": _lazy("四川"),
        "children": [
            {"code": "510800", "en": _lazy("广元"), "cn": _lazy("广元")},
            {"code": "511500", "en": _lazy("宜宾"), "cn": _lazy("宜宾")},
            {"code": "510300", "en": _lazy("自贡"), "cn": _lazy("自贡")},
            {"code": "513400", "en": _lazy("凉山彝族自治州"), "cn": _lazy("凉山彝族自治州")},
            {"code": "511100", "en": _lazy("乐山"), "cn": _lazy("乐山")},
            {"code": "510700", "en": _lazy("绵阳"), "cn": _lazy("绵阳")},
            {"code": "510900", "en": _lazy("遂宁"), "cn": _lazy("遂宁")},
            {"code": "511400", "en": _lazy("眉山"), "cn": _lazy("眉山")},
            {"code": "510400", "en": _lazy("攀枝花"), "cn": _lazy("攀枝花")},
            {"code": "511900", "en": _lazy("巴中"), "cn": _lazy("巴中")},
            {"code": "511000", "en": _lazy("内江"), "cn": _lazy("内江")},
            {"code": "511700", "en": _lazy("达州"), "cn": _lazy("达州")},
            {"code": "510100", "en": _lazy("成都"), "cn": _lazy("成都")},
            {"code": "511300", "en": _lazy("南充"), "cn": _lazy("南充")},
            {"code": "510500", "en": _lazy("泸州"), "cn": _lazy("泸州")},
            {"code": "513200", "en": _lazy("阿坝藏族羌族自治州"), "cn": _lazy("阿坝藏族羌族自治州")},
            {"code": "511800", "en": _lazy("雅安"), "cn": _lazy("雅安")},
            {"code": "511600", "en": _lazy("广安"), "cn": _lazy("广安")},
            {"code": "512000", "en": _lazy("资阳"), "cn": _lazy("资阳")},
            {"code": "513300", "en": _lazy("甘孜藏族自治州"), "cn": _lazy("甘孜藏族自治州")},
            {"code": "510600", "en": _lazy("德阳"), "cn": _lazy("德阳")},
        ],
    },
    {
        "code": "520000",
        "en": _lazy("贵州"),
        "cn": _lazy("贵州"),
        "children": [
            {"code": "520300", "en": _lazy("遵义"), "cn": _lazy("遵义")},
            {"code": "520100", "en": _lazy("贵阳"), "cn": _lazy("贵阳")},
            {"code": "520500", "en": _lazy("毕节"), "cn": _lazy("毕节")},
            {"code": "522600", "en": _lazy("黔东南苗族侗族自治州"), "cn": _lazy("黔东南苗族侗族自治州")},
            {"code": "520200", "en": _lazy("六盘水"), "cn": _lazy("六盘水")},
            {"code": "522300", "en": _lazy("黔西南布依族苗族自治州"), "cn": _lazy("黔西南布依族苗族自治州")},
            {"code": "520600", "en": _lazy("铜仁"), "cn": _lazy("铜仁")},
            {"code": "522700", "en": _lazy("黔南布依族苗族自治州"), "cn": _lazy("黔南布依族苗族自治州")},
            {"code": "520400", "en": _lazy("安顺"), "cn": _lazy("安顺")},
        ],
    },
    {
        "code": "530000",
        "en": _lazy("云南"),
        "cn": _lazy("云南"),
        "children": [
            {"code": "533300", "en": _lazy("怒江傈僳族自治州"), "cn": _lazy("怒江傈僳族自治州")},
            {"code": "530300", "en": _lazy("曲靖"), "cn": _lazy("曲靖")},
            {"code": "530800", "en": _lazy("普洱"), "cn": _lazy("普洱")},
            {"code": "530700", "en": _lazy("丽江"), "cn": _lazy("丽江")},
            {"code": "532500", "en": _lazy("红河哈尼族彝族自治州"), "cn": _lazy("红河哈尼族彝族自治州")},
            {"code": "530900", "en": _lazy("临沧"), "cn": _lazy("临沧")},
            {"code": "532800", "en": _lazy("西双版纳傣族自治州"), "cn": _lazy("西双版纳傣族自治州")},
            {"code": "533100", "en": _lazy("德宏傣族景颇族自治州"), "cn": _lazy("德宏傣族景颇族自治州")},
            {"code": "530400", "en": _lazy("玉溪"), "cn": _lazy("玉溪")},
            {"code": "532600", "en": _lazy("文山壮族苗族自治州"), "cn": _lazy("文山壮族苗族自治州")},
            {"code": "530100", "en": _lazy("昆明"), "cn": _lazy("昆明")},
            {"code": "532900", "en": _lazy("大理白族自治州"), "cn": _lazy("大理白族自治州")},
            {"code": "530500", "en": _lazy("保山"), "cn": _lazy("保山")},
            {"code": "533400", "en": _lazy("迪庆藏族自治州"), "cn": _lazy("迪庆藏族自治州")},
            {"code": "530600", "en": _lazy("昭通"), "cn": _lazy("昭通")},
            {"code": "532300", "en": _lazy("楚雄彝族自治州"), "cn": _lazy("楚雄彝族自治州")},
        ],
    },
    {
        "code": "540000",
        "en": _lazy("西藏"),
        "cn": _lazy("西藏"),
        "children": [
            {"code": "540300", "en": _lazy("昌都"), "cn": _lazy("昌都")},
            {"code": "542500", "en": _lazy("阿里地区"), "cn": _lazy("阿里地区")},
            {"code": "540200", "en": _lazy("日喀则"), "cn": _lazy("日喀则")},
            {"code": "540500", "en": _lazy("山南"), "cn": _lazy("山南")},
            {"code": "542400", "en": _lazy("那曲地区"), "cn": _lazy("那曲地区")},
            {"code": "540100", "en": _lazy("拉萨"), "cn": _lazy("拉萨")},
            {"code": "540400", "en": _lazy("林芝"), "cn": _lazy("林芝")},
        ],
    },
    {
        "code": "610000",
        "en": _lazy("陕西"),
        "cn": _lazy("陕西"),
        "children": [
            {"code": "610400", "en": _lazy("咸阳"), "cn": _lazy("咸阳")},
            {"code": "610600", "en": _lazy("延安"), "cn": _lazy("延安")},
            {"code": "610900", "en": _lazy("安康"), "cn": _lazy("安康")},
            {"code": "611000", "en": _lazy("商洛"), "cn": _lazy("商洛")},
            {"code": "610200", "en": _lazy("铜川"), "cn": _lazy("铜川")},
            {"code": "610500", "en": _lazy("渭南"), "cn": _lazy("渭南")},
            {"code": "610700", "en": _lazy("汉中"), "cn": _lazy("汉中")},
            {"code": "610100", "en": _lazy("西安"), "cn": _lazy("西安")},
            {"code": "610800", "en": _lazy("榆林"), "cn": _lazy("榆林")},
            {"code": "610300", "en": _lazy("宝鸡"), "cn": _lazy("宝鸡")},
        ],
    },
    {
        "code": "620000",
        "en": _lazy("甘肃"),
        "cn": _lazy("甘肃"),
        "children": [
            {"code": "620600", "en": _lazy("武威"), "cn": _lazy("武威")},
            {"code": "620200", "en": _lazy("嘉峪关"), "cn": _lazy("嘉峪关")},
            {"code": "620700", "en": _lazy("张掖"), "cn": _lazy("张掖")},
            {"code": "621000", "en": _lazy("庆阳"), "cn": _lazy("庆阳")},
            {"code": "620300", "en": _lazy("金昌"), "cn": _lazy("金昌")},
            {"code": "622900", "en": _lazy("临夏回族自治州"), "cn": _lazy("临夏回族自治州")},
            {"code": "621100", "en": _lazy("定西"), "cn": _lazy("定西")},
            {"code": "620100", "en": _lazy("兰州"), "cn": _lazy("兰州")},
            {"code": "620900", "en": _lazy("酒泉"), "cn": _lazy("酒泉")},
            {"code": "623000", "en": _lazy("甘南藏族自治州"), "cn": _lazy("甘南藏族自治州")},
            {"code": "621200", "en": _lazy("陇南"), "cn": _lazy("陇南")},
            {"code": "620400", "en": _lazy("白银"), "cn": _lazy("白银")},
            {"code": "620500", "en": _lazy("天水"), "cn": _lazy("天水")},
            {"code": "620800", "en": _lazy("平凉"), "cn": _lazy("平凉")},
        ],
    },
    {
        "code": "630000",
        "en": _lazy("青海"),
        "cn": _lazy("青海"),
        "children": [
            {"code": "632500", "en": _lazy("海南藏族自治州"), "cn": _lazy("海南藏族自治州")},
            {"code": "632700", "en": _lazy("玉树藏族自治州"), "cn": _lazy("玉树藏族自治州")},
            {"code": "630200", "en": _lazy("海东"), "cn": _lazy("海东")},
            {"code": "632300", "en": _lazy("黄南藏族自治州"), "cn": _lazy("黄南藏族自治州")},
            {"code": "632600", "en": _lazy("果洛藏族自治州"), "cn": _lazy("果洛藏族自治州")},
            {"code": "632800", "en": _lazy("海西蒙古族藏族自治州"), "cn": _lazy("海西蒙古族藏族自治州")},
            {"code": "630100", "en": _lazy("西宁"), "cn": _lazy("西宁")},
            {"code": "632200", "en": _lazy("海北藏族自治州"), "cn": _lazy("海北藏族自治州")},
        ],
    },
    {
        "code": "640000",
        "en": _lazy("宁夏"),
        "cn": _lazy("宁夏"),
        "children": [
            {"code": "640100", "en": _lazy("银川"), "cn": _lazy("银川")},
            {"code": "640200", "en": _lazy("石嘴山"), "cn": _lazy("石嘴山")},
            {"code": "640300", "en": _lazy("吴忠"), "cn": _lazy("吴忠")},
            {"code": "640400", "en": _lazy("固原"), "cn": _lazy("固原")},
            {"code": "640500", "en": _lazy("中卫"), "cn": _lazy("中卫")},
        ],
    },
    {
        "code": "650000",
        "en": _lazy("新疆"),
        "cn": _lazy("新疆"),
        "children": [
            {"code": "659000", "en": _lazy("自治区直辖县级行政区划"), "cn": _lazy("自治区直辖县级行政区划")},
            {"code": "652800", "en": _lazy("巴音郭楞蒙古自治州"), "cn": _lazy("巴音郭楞蒙古自治州")},
            {"code": "654300", "en": _lazy("阿勒泰地区"), "cn": _lazy("阿勒泰地区")},
            {"code": "654200", "en": _lazy("塔城地区"), "cn": _lazy("塔城地区")},
            {"code": "650200", "en": _lazy("克拉玛依"), "cn": _lazy("克拉玛依")},
            {"code": "650100", "en": _lazy("乌鲁木齐"), "cn": _lazy("乌鲁木齐")},
            {"code": "653000", "en": _lazy("克孜勒苏柯尔克孜自治州"), "cn": _lazy("克孜勒苏柯尔克孜自治州")},
            {"code": "652900", "en": _lazy("阿克苏地区"), "cn": _lazy("阿克苏地区")},
            {"code": "650500", "en": _lazy("哈密"), "cn": _lazy("哈密")},
            {"code": "652300", "en": _lazy("昌吉回族自治州"), "cn": _lazy("昌吉回族自治州")},
            {"code": "652700", "en": _lazy("博尔塔拉蒙古自治州"), "cn": _lazy("博尔塔拉蒙古自治州")},
            {"code": "650400", "en": _lazy("吐鲁番"), "cn": _lazy("吐鲁番")},
            {"code": "653100", "en": _lazy("喀什地区"), "cn": _lazy("喀什地区")},
            {"code": "653200", "en": _lazy("和田地区"), "cn": _lazy("和田地区")},
            {"code": "654000", "en": _lazy("伊犁哈萨克自治州"), "cn": _lazy("伊犁哈萨克自治州")},
        ],
    },
    {"code": "710000", "en": _lazy("台湾"), "cn": _lazy("台湾"), "children": []},
    {"code": "810000", "en": _lazy("香港"), "cn": _lazy("香港"), "children": []},
    {"code": "820000", "en": _lazy("澳门"), "cn": _lazy("澳门"), "children": []},
]


COUNTRIES = [
    {"code": "CN", "en": "China", "cn": _lazy("中国"), "children": CHINESE_PROVINCES},
    {"code": "US", "en": "United States of America (USA)", "cn": _lazy("美国"), "children": []},
    {"code": "AR", "en": "Argentina", "cn": _lazy("阿根廷"), "children": []},
    {"code": "AD", "en": "Andorra", "cn": _lazy("安道尔"), "children": []},
    {"code": "AE", "en": "United Arab Emirates", "cn": _lazy("阿联酋"), "children": []},
    {"code": "AF", "en": "Afghanistan", "cn": _lazy("阿富汗"), "children": []},
    {"code": "AG", "en": "Antigua & Barbuda", "cn": _lazy("安提瓜和巴布达"), "children": []},
    {"code": "AI", "en": "Anguilla", "cn": _lazy("安圭拉"), "children": []},
    {"code": "AL", "en": "Albania", "cn": _lazy("阿尔巴尼亚"), "children": []},
    {"code": "AM", "en": "Armenia", "cn": _lazy("亚美尼亚"), "children": []},
    {"code": "AO", "en": "Angola", "cn": _lazy("安哥拉"), "children": []},
    {"code": "AQ", "en": "Antarctica", "cn": _lazy("南极洲"), "children": []},
    {"code": "AS", "en": "American Samoa", "cn": _lazy("美属萨摩亚"), "children": []},
    {"code": "AT", "en": "Austria", "cn": _lazy("奥地利"), "children": []},
    {"code": "AU", "en": "Australia", "cn": _lazy("澳大利亚"), "children": []},
    {"code": "AW", "en": "Aruba", "cn": _lazy("阿鲁巴"), "children": []},
    {"code": "AX", "en": "Aland Island", "cn": _lazy("奥兰群岛"), "children": []},
    {"code": "AZ", "en": "Azerbaijan", "cn": _lazy("阿塞拜疆"), "children": []},
    {"code": "BA", "en": "Bosnia & Herzegovina", "cn": _lazy("波黑"), "children": []},
    {"code": "BB", "en": "Barbados", "cn": _lazy("巴巴多斯"), "children": []},
    {"code": "BD", "en": "Bangladesh", "cn": _lazy("孟加拉"), "children": []},
    {"code": "BE", "en": "Belgium", "cn": _lazy("比利时"), "children": []},
    {"code": "BF", "en": "Burkina", "cn": _lazy("布基纳法索"), "children": []},
    {"code": "BG", "en": "Bulgaria", "cn": _lazy("保加利亚"), "children": []},
    {"code": "BH", "en": "Bahrain", "cn": _lazy("巴林"), "children": []},
    {"code": "BI", "en": "Burundi", "cn": _lazy("布隆迪"), "children": []},
    {"code": "BJ", "en": "Benin", "cn": _lazy("贝宁"), "children": []},
    {"code": "BL", "en": "Saint Barthélemy", "cn": _lazy("圣巴泰勒米岛"), "children": []},
    {"code": "BM", "en": "Bermuda", "cn": _lazy("百慕大"), "children": []},
    {"code": "BN", "en": "Brunei", "cn": _lazy("文莱"), "children": []},
    {"code": "BO", "en": "Bolivia", "cn": _lazy("玻利维亚"), "children": []},
    {"code": "BQ", "en": "Caribbean Netherlands", "cn": _lazy("荷兰加勒比区"), "children": []},
    {"code": "BR", "en": "Brazil", "cn": _lazy("巴西"), "children": []},
    {"code": "BS", "en": "The Bahamas", "cn": _lazy("巴哈马"), "children": []},
    {"code": "BT", "en": "Bhutan", "cn": _lazy("不丹"), "children": []},
    {"code": "BV", "en": "Bouvet Island", "cn": _lazy("布韦岛"), "children": []},
    {"code": "BW", "en": "Botswana", "cn": _lazy("博茨瓦纳"), "children": []},
    {"code": "BY", "en": "Belarus", "cn": _lazy("白俄罗斯"), "children": []},
    {"code": "BZ", "en": "Belize", "cn": _lazy("伯利兹"), "children": []},
    {"code": "CA", "en": "Canada", "cn": _lazy("加拿大"), "children": []},
    {"code": "CC", "en": "Cocos (Keeling) Islands", "cn": _lazy("科科斯群岛"), "children": []},
    {"code": "CD", "en": "Democratic Republic of the Congo", "cn": _lazy("刚果（金）"), "children": []},
    {"code": "CF", "en": "Central African Republic", "cn": _lazy("中非"), "children": []},
    {"code": "CG", "en": "Republic of the Congo", "cn": _lazy("刚果（布）"), "children": []},
    {"code": "CH", "en": "Switzerland", "cn": _lazy("瑞士"), "children": []},
    {"code": "CI", "en": "Cote d'Ivoire", "cn": _lazy("科特迪瓦"), "children": []},
    {"code": "CK", "en": "Cook Islands", "cn": _lazy("库克群岛"), "children": []},
    {"code": "CL", "en": "Chile", "cn": _lazy("智利"), "children": []},
    {"code": "CM", "en": "Cameroon", "cn": _lazy("喀麦隆"), "children": []},
    {"code": "CO", "en": "Colombia", "cn": _lazy("哥伦比亚"), "children": []},
    {"code": "CR", "en": "Costa Rica", "cn": _lazy("哥斯达黎加"), "children": []},
    {"code": "CU", "en": "Cuba", "cn": _lazy("古巴"), "children": []},
    {"code": "CV", "en": "Cape Verde", "cn": _lazy("佛得角"), "children": []},
    {"code": "CW", "en": "Curacao", "cn": _lazy("库拉索"), "children": []},
    {"code": "CX", "en": "Christmas Island", "cn": _lazy("圣诞岛"), "children": []},
    {"code": "CY", "en": "Cyprus", "cn": _lazy("塞浦路斯"), "children": []},
    {"code": "CZ", "en": "Czech Republic", "cn": _lazy("捷克"), "children": []},
    {"code": "DE", "en": "Germany", "cn": _lazy("德国"), "children": []},
    {"code": "DJ", "en": "Djibouti", "cn": _lazy("吉布提"), "children": []},
    {"code": "DK", "en": "Denmark", "cn": _lazy("丹麦"), "children": []},
    {"code": "DM", "en": "Dominica", "cn": _lazy("多米尼克"), "children": []},
    {"code": "DO", "en": "Dominican Republic", "cn": _lazy("多米尼加"), "children": []},
    {"code": "DZ", "en": "Algeria", "cn": _lazy("阿尔及利亚"), "children": []},
    {"code": "EC", "en": "Ecuador", "cn": _lazy("厄瓜多尔"), "children": []},
    {"code": "EE", "en": "Estonia", "cn": _lazy("爱沙尼亚"), "children": []},
    {"code": "EG", "en": "Egypt", "cn": _lazy("埃及"), "children": []},
    {"code": "EH", "en": "Western Sahara", "cn": _lazy("西撒哈拉"), "children": []},
    {"code": "ER", "en": "Eritrea", "cn": _lazy("厄立特里亚"), "children": []},
    {"code": "ES", "en": "Spain", "cn": _lazy("西班牙"), "children": []},
    {"code": "ET", "en": "Ethiopia", "cn": _lazy("埃塞俄比亚"), "children": []},
    {"code": "FI", "en": "Finland", "cn": _lazy("芬兰"), "children": []},
    {"code": "FJ", "en": "Fiji", "cn": _lazy("斐济群岛"), "children": []},
    {"code": "FK", "en": "Falkland Islands", "cn": _lazy("马尔维纳斯群岛（福克兰）"), "children": []},
    {"code": "FM", "en": "Federated States of Micronesia", "cn": _lazy("密克罗尼西亚联邦"), "children": []},
    {"code": "FO", "en": "Faroe Islands", "cn": _lazy("法罗群岛"), "children": []},
    {"code": "FR", "en": "France", "cn": _lazy("法国 法国"), "children": []},
    {"code": "GA", "en": "Gabon", "cn": _lazy("加蓬"), "children": []},
    {"code": "GB", "en": "Great Britain (United Kingdom; England)", "cn": _lazy("英国"), "children": []},
    {"code": "GD", "en": "Grenada", "cn": _lazy("格林纳达"), "children": []},
    {"code": "GE", "en": "Georgia", "cn": _lazy("格鲁吉亚"), "children": []},
    {"code": "GF", "en": "French Guiana", "cn": _lazy("法属圭亚那"), "children": []},
    {"code": "GG", "en": "Guernsey", "cn": _lazy("根西岛"), "children": []},
    {"code": "GH", "en": "Ghana", "cn": _lazy("加纳"), "children": []},
    {"code": "GI", "en": "Gibraltar", "cn": _lazy("直布罗陀"), "children": []},
    {"code": "GL", "en": "Greenland", "cn": _lazy("格陵兰"), "children": []},
    {"code": "GM", "en": "Gambia", "cn": _lazy("冈比亚"), "children": []},
    {"code": "GN", "en": "Guinea", "cn": _lazy("几内亚"), "children": []},
    {"code": "GP", "en": "Guadeloupe", "cn": _lazy("瓜德罗普"), "children": []},
    {"code": "GQ", "en": "Equatorial Guinea", "cn": _lazy("赤道几内亚"), "children": []},
    {"code": "GR", "en": "Greece", "cn": _lazy("希腊"), "children": []},
    {"code": "GS", "en": "South Georgia and the South Sandwich Islands", "cn": _lazy("南乔治亚岛和南桑威奇群岛"), "children": []},
    {"code": "GT", "en": "Guatemala", "cn": _lazy("危地马拉"), "children": []},
    {"code": "GU", "en": "Guam", "cn": _lazy("关岛"), "children": []},
    {"code": "GW", "en": "Guinea-Bissau", "cn": _lazy("几内亚比绍"), "children": []},
    {"code": "GY", "en": "Guyana", "cn": _lazy("圭亚那"), "children": []},
    {"code": "HM", "en": "Heard Island and McDonald Islands", "cn": _lazy("赫德岛和麦克唐纳群岛"), "children": []},
    {"code": "HN", "en": "Honduras", "cn": _lazy("洪都拉斯"), "children": []},
    {"code": "HR", "en": "Croatia", "cn": _lazy("克罗地亚"), "children": []},
    {"code": "HT", "en": "Haiti", "cn": _lazy("海地"), "children": []},
    {"code": "HU", "en": "Hungary", "cn": _lazy("匈牙利"), "children": []},
    {"code": "ID", "en": "Indonesia", "cn": _lazy("印尼"), "children": []},
    {"code": "IE", "en": "Ireland", "cn": _lazy("爱尔兰"), "children": []},
    {"code": "IL", "en": "Israel", "cn": _lazy("以色列"), "children": []},
    {"code": "IM", "en": "Isle of Man", "cn": _lazy("马恩岛"), "children": []},
    {"code": "IN", "en": "India", "cn": _lazy("印度"), "children": []},
    {"code": "IO", "en": "British Indian Ocean Territory", "cn": _lazy("英属印度洋领地"), "children": []},
    {"code": "IQ", "en": "Iraq", "cn": _lazy("伊拉克"), "children": []},
    {"code": "IR", "en": "Iran", "cn": _lazy("伊朗"), "children": []},
    {"code": "IS", "en": "Iceland", "cn": _lazy("冰岛"), "children": []},
    {"code": "IT", "en": "Italy", "cn": _lazy("意大利"), "children": []},
    {"code": "JE", "en": "Jersey", "cn": _lazy("泽西岛"), "children": []},
    {"code": "JM", "en": "Jamaica", "cn": _lazy("牙买加"), "children": []},
    {"code": "JO", "en": "Jordan", "cn": _lazy("约旦"), "children": []},
    {"code": "JP", "en": "Japan", "cn": _lazy("日本"), "children": []},
    {"code": "KE", "en": "Kenya", "cn": _lazy("肯尼亚"), "children": []},
    {"code": "KG", "en": "Kyrgyzstan", "cn": _lazy("吉尔吉斯斯坦"), "children": []},
    {"code": "KH", "en": "Cambodia", "cn": _lazy("柬埔寨"), "children": []},
    {"code": "KI", "en": "Kiribati", "cn": _lazy("基里巴斯"), "children": []},
    {"code": "KM", "en": "The Comoros", "cn": _lazy("科摩罗"), "children": []},
    {"code": "KN", "en": "St. Kitts & Nevis", "cn": _lazy("圣基茨和尼维斯"), "children": []},
    {"code": "KP", "en": "North Korea", "cn": _lazy("朝鲜"), "children": []},
    {"code": "KR", "en": "South Korea", "cn": _lazy("韩国"), "children": []},
    {"code": "KW", "en": "Kuwait", "cn": _lazy("科威特"), "children": []},
    {"code": "KY", "en": "Cayman Islands", "cn": _lazy("开曼群岛"), "children": []},
    {"code": "KZ", "en": "Kazakhstan", "cn": _lazy("哈萨克斯坦"), "children": []},
    {"code": "LA", "en": "Laos", "cn": _lazy("老挝"), "children": []},
    {"code": "LB", "en": "Lebanon", "cn": _lazy("黎巴嫩"), "children": []},
    {"code": "LC", "en": "St. Lucia", "cn": _lazy("圣卢西亚"), "children": []},
    {"code": "LI", "en": "Liechtenstein", "cn": _lazy("列支敦士登"), "children": []},
    {"code": "LK", "en": "Sri Lanka", "cn": _lazy("斯里兰卡"), "children": []},
    {"code": "LR", "en": "Liberia", "cn": _lazy("利比里亚"), "children": []},
    {"code": "LS", "en": "Lesotho", "cn": _lazy("莱索托"), "children": []},
    {"code": "LT", "en": "Lithuania", "cn": _lazy("立陶宛"), "children": []},
    {"code": "LU", "en": "Luxembourg", "cn": _lazy("卢森堡"), "children": []},
    {"code": "LV", "en": "Latvia", "cn": _lazy("拉脱维亚"), "children": []},
    {"code": "LY", "en": "Libya", "cn": _lazy("利比亚"), "children": []},
    {"code": "MA", "en": "Morocco", "cn": _lazy("摩洛哥"), "children": []},
    {"code": "MC", "en": "Monaco", "cn": _lazy("摩纳哥"), "children": []},
    {"code": "MD", "en": "Moldova", "cn": _lazy("摩尔多瓦"), "children": []},
    {"code": "ME", "en": "Montenegro", "cn": _lazy("黑山"), "children": []},
    {"code": "MF", "en": "Saint Martin (France)", "cn": _lazy("法属圣马丁"), "children": []},
    {"code": "MG", "en": "Madagascar", "cn": _lazy("马达加斯加"), "children": []},
    {"code": "MH", "en": "Marshall islands", "cn": _lazy("马绍尔群岛"), "children": []},
    {"code": "MK", "en": "Republic of Macedonia (FYROM)", "cn": _lazy("马其顿"), "children": []},
    {"code": "ML", "en": "Mali", "cn": _lazy("马里"), "children": []},
    {"code": "MM", "en": "Myanmar (Burma)", "cn": _lazy("缅甸"), "children": []},
    {"code": "MN", "en": "Mongolia", "cn": _lazy("蒙古国"), "children": []},
    {"code": "MP", "en": "Northern Mariana Islands", "cn": _lazy("北马里亚纳群岛"), "children": []},
    {"code": "MQ", "en": "Martinique", "cn": _lazy("马提尼克"), "children": []},
    {"code": "MR", "en": "Mauritania", "cn": _lazy("毛里塔尼亚"), "children": []},
    {"code": "MS", "en": "Montserrat", "cn": _lazy("蒙塞拉特岛"), "children": []},
    {"code": "MT", "en": "Malta", "cn": _lazy("马耳他"), "children": []},
    {"code": "MU", "en": "Mauritius", "cn": _lazy("毛里求斯"), "children": []},
    {"code": "MV", "en": "Maldives", "cn": _lazy("马尔代夫"), "children": []},
    {"code": "MW", "en": "Malawi", "cn": _lazy("马拉维"), "children": []},
    {"code": "MX", "en": "Mexico", "cn": _lazy("墨西哥"), "children": []},
    {"code": "MY", "en": "Malaysia", "cn": _lazy("马来西亚"), "children": []},
    {"code": "MZ", "en": "Mozambique", "cn": _lazy("莫桑比克"), "children": []},
    {"code": "NA", "en": "Namibia", "cn": _lazy("纳米比亚"), "children": []},
    {"code": "NC", "en": "New Caledonia", "cn": _lazy("新喀里多尼亚"), "children": []},
    {"code": "NE", "en": "Niger", "cn": _lazy("尼日尔"), "children": []},
    {"code": "NF", "en": "Norfolk Island", "cn": _lazy("诺福克岛"), "children": []},
    {"code": "NG", "en": "Nigeria", "cn": _lazy("尼日利亚"), "children": []},
    {"code": "NI", "en": "Nicaragua", "cn": _lazy("尼加拉瓜"), "children": []},
    {"code": "NL", "en": "Netherlands", "cn": _lazy("荷兰"), "children": []},
    {"code": "NO", "en": "Norway", "cn": _lazy("挪威"), "children": []},
    {"code": "NP", "en": "Nepal", "cn": _lazy("尼泊尔"), "children": []},
    {"code": "NR", "en": "Nauru", "cn": _lazy("瑙鲁"), "children": []},
    {"code": "NU", "en": "Niue", "cn": _lazy("纽埃"), "children": []},
    {"code": "NZ", "en": "New Zealand", "cn": _lazy("新西兰"), "children": []},
    {"code": "OM", "en": "Oman", "cn": _lazy("阿曼"), "children": []},
    {"code": "PA", "en": "Panama", "cn": _lazy("巴拿马"), "children": []},
    {"code": "PE", "en": "Peru", "cn": _lazy("秘鲁"), "children": []},
    {"code": "PF", "en": "French polynesia", "cn": _lazy("法属波利尼西亚"), "children": []},
    {"code": "PG", "en": "Papua New Guinea", "cn": _lazy("巴布亚新几内亚"), "children": []},
    {"code": "PH", "en": "The Philippines", "cn": _lazy("菲律宾"), "children": []},
    {"code": "PK", "en": "Pakistan", "cn": _lazy("巴基斯坦"), "children": []},
    {"code": "PL", "en": "Poland", "cn": _lazy("波兰"), "children": []},
    {"code": "PM", "en": "Saint-Pierre and Miquelon", "cn": _lazy("圣皮埃尔和密克隆"), "children": []},
    {"code": "PN", "en": "Pitcairn Islands", "cn": _lazy("皮特凯恩群岛"), "children": []},
    {"code": "PR", "en": "Puerto Rico", "cn": _lazy("波多黎各"), "children": []},
    {"code": "PS", "en": "Palestinian territories", "cn": _lazy("巴勒斯坦"), "children": []},
    {"code": "PT", "en": "Portugal", "cn": _lazy("葡萄牙"), "children": []},
    {"code": "PW", "en": "Palau", "cn": _lazy("帕劳"), "children": []},
    {"code": "PY", "en": "Paraguay", "cn": _lazy("巴拉圭"), "children": []},
    {"code": "QA", "en": "Qatar", "cn": _lazy("卡塔尔"), "children": []},
    {"code": "RE", "en": "Réunion", "cn": _lazy("留尼汪"), "children": []},
    {"code": "RO", "en": "Romania", "cn": _lazy("罗马尼亚"), "children": []},
    {"code": "RS", "en": "Serbia", "cn": _lazy("塞尔维亚"), "children": []},
    {"code": "RU", "en": "Russian Federation", "cn": _lazy("俄罗斯"), "children": []},
    {"code": "RW", "en": "Rwanda", "cn": _lazy("卢旺达"), "children": []},
    {"code": "SA", "en": "Saudi Arabia", "cn": _lazy("沙特阿拉伯"), "children": []},
    {"code": "SB", "en": "Solomon Islands", "cn": _lazy("所罗门群岛"), "children": []},
    {"code": "SC", "en": "Seychelles", "cn": _lazy("塞舌尔"), "children": []},
    {"code": "SD", "en": "Sudan", "cn": _lazy("苏丹"), "children": []},
    {"code": "SE", "en": "Sweden", "cn": _lazy("瑞典"), "children": []},
    {"code": "SG", "en": "Singapore", "cn": _lazy("新加坡"), "children": []},
    {"code": "SH", "en": "St. Helena & Dependencies", "cn": _lazy("圣赫勒拿"), "children": []},
    {"code": "SI", "en": "Slovenia", "cn": _lazy("斯洛文尼亚"), "children": []},
    {"code": "SJ", "en": "Svalbard and Jan Mayen", "cn": _lazy("斯瓦尔巴群岛和扬马延岛"), "children": []},
    {"code": "SK", "en": "Slovakia", "cn": _lazy("斯洛伐克"), "children": []},
    {"code": "SL", "en": "Sierra Leone", "cn": _lazy("塞拉利昂"), "children": []},
    {"code": "SM", "en": "San Marino", "cn": _lazy("圣马力诺"), "children": []},
    {"code": "SN", "en": "Senegal", "cn": _lazy("塞内加尔"), "children": []},
    {"code": "SO", "en": "Somalia", "cn": _lazy("索马里"), "children": []},
    {"code": "SR", "en": "Suriname", "cn": _lazy("苏里南"), "children": []},
    {"code": "SS", "en": "South Sudan", "cn": _lazy("南苏丹"), "children": []},
    {"code": "ST", "en": "Sao Tome & Principe", "cn": _lazy("圣多美和普林西比"), "children": []},
    {"code": "SV", "en": "El Salvador", "cn": _lazy("萨尔瓦多"), "children": []},
    {"code": "SX", "en": "Sint Maarten", "cn": _lazy("荷属圣马丁"), "children": []},
    {"code": "SY", "en": "Syria", "cn": _lazy("叙利亚"), "children": []},
    {"code": "SZ", "en": "Swaziland", "cn": _lazy("斯威士兰"), "children": []},
    {"code": "TC", "en": "Turks & Caicos Islands", "cn": _lazy("特克斯和凯科斯群岛"), "children": []},
    {"code": "TD", "en": "Chad", "cn": _lazy("乍得"), "children": []},
    {"code": "TF", "en": "French Southern Territories", "cn": _lazy("法属南部领地"), "children": []},
    {"code": "TG", "en": "Togo", "cn": _lazy("多哥"), "children": []},
    {"code": "TH", "en": "Thailand", "cn": _lazy("泰国"), "children": []},
    {"code": "TJ", "en": "Tajikistan", "cn": _lazy("塔吉克斯坦"), "children": []},
    {"code": "TK", "en": "Tokelau", "cn": _lazy("托克劳"), "children": []},
    {"code": "TL", "en": "Timor-Leste (East Timor)", "cn": _lazy("东帝汶"), "children": []},
    {"code": "TM", "en": "Turkmenistan", "cn": _lazy("土库曼斯坦"), "children": []},
    {"code": "TN", "en": "Tunisia", "cn": _lazy("突尼斯"), "children": []},
    {"code": "TO", "en": "Tonga", "cn": _lazy("汤加"), "children": []},
    {"code": "TR", "en": "Turkey", "cn": _lazy("土耳其"), "children": []},
    {"code": "TT", "en": "Trinidad & Tobago", "cn": _lazy("特立尼达和多巴哥"), "children": []},
    {"code": "TV", "en": "Tuvalu", "cn": _lazy("图瓦卢"), "children": []},
    {"code": "TZ", "en": "Tanzania", "cn": _lazy("坦桑尼亚"), "children": []},
    {"code": "UA", "en": "Ukraine", "cn": _lazy("乌克兰"), "children": []},
    {"code": "UG", "en": "Uganda", "cn": _lazy("乌干达"), "children": []},
    {"code": "UM", "en": "United States Minor Outlying Islands", "cn": _lazy("美国本土外小岛屿"), "children": []},
    {"code": "UY", "en": "Uruguay", "cn": _lazy("乌拉圭"), "children": []},
    {"code": "UZ", "en": "Uzbekistan", "cn": _lazy("乌兹别克斯坦"), "children": []},
    {"code": "VA", "en": "Vatican City (The Holy See)", "cn": _lazy("梵蒂冈"), "children": []},
    {"code": "VC", "en": "St. Vincent & the Grenadines", "cn": _lazy("圣文森特和格林纳丁斯"), "children": []},
    {"code": "VE", "en": "Venezuela", "cn": _lazy("委内瑞拉"), "children": []},
    {"code": "VG", "en": "British Virgin Islands", "cn": _lazy("英属维尔京群岛"), "children": []},
    {"code": "VI", "en": "United States Virgin Islands", "cn": _lazy("美属维尔京群岛"), "children": []},
    {"code": "VN", "en": "Vietnam", "cn": _lazy("越南"), "children": []},
    {"code": "VU", "en": "Vanuatu", "cn": _lazy("瓦努阿图"), "children": []},
    {"code": "WF", "en": "Wallis and Futuna", "cn": _lazy("瓦利斯和富图纳"), "children": []},
    {"code": "WS", "en": "Samoa", "cn": _lazy("萨摩亚"), "children": []},
    {"code": "YE", "en": "Yemen", "cn": _lazy("也门"), "children": []},
    {"code": "YT", "en": "Mayotte", "cn": _lazy("马约特"), "children": []},
    {"code": "ZA", "en": "South Africa", "cn": _lazy("南非"), "children": []},
    {"code": "ZM", "en": "Zambia", "cn": _lazy("赞比亚"), "children": []},
    {"code": "ZW", "en": "Zimbabwe", "cn": _lazy("津巴布韦"), "children": []},
]


# 城市名称与省份名称的映射
CHINESE_CITY_MAPPING = {}

for province in CHINESE_PROVINCES:
    CHINESE_CITY_MAPPING[str(province["cn"])] = province["cn"]
    for city in province["children"]:
        CHINESE_CITY_MAPPING[str(city["cn"])] = province["cn"]

CHINESE_PROVINCE_MAP = {province["code"]: province for province in CHINESE_PROVINCES}

COUNTRY_MAP = {country["code"]: country for country in COUNTRIES}

ISP_MAP = {isp["code"]: isp for isp in ISP_LIST}
