paths:
  /app/action/search/:
    post:
      operationId: search_action
      description: 查询处理记录
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          name: default
          method: post
          path: /api/v4/search_action/search_action/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: search_action
