swagger: '2.0'
basePath: /
info:
  version: '1.0'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /app/alarm_strategy/switch/:
    post:
      operationId: switch_alarm_strategy
      description: 启停告警策略
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/alarm_strategy/switch/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: switch alarm strategy
  /app/alarm_strategy/search/:
    post:
      operationId: search_alarm_strategy
      description: 查询告警策略
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/alarm_strategy_v3/search/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: search alarm strategy
  /app/alarm_strategy/switch_by_labels/:
    post:
      operationId: switch_alarm_strategy_by_labels
      description: 根据标签批量启停告警策略
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/alarm_strategy_v3/switch_by_labels/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: switch alarm strategy by labels
  /app/alarm_strategy/save/:
    post:
      operationId: save_alarm_strategy
      description: 保存告警策略
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/alarm_strategy_v3/save/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: save alarm strategy
  /app/alarm_strategy/delete/:
    post:
      operationId: delete_alarm_strategy
      description: 删除告警策略
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/alarm_strategy_v3/delete/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: delete alarm strategy
  /app/alarm_strategy/update_bulk/:
    post:
      operationId: update_partial_strategy
      description: 批量更新策略局部配置
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/alarm_strategy_v3/update_bulk/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: update partial strategy
  /app/alarm_strategy/search_without_biz/:
    post:
      operationId: search_alarm_strategy_without_biz
      description: 查询全业务告警策略
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/alarm_strategy_v3/search_without_biz/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: search alarm strategy without biz
