swagger: '2.0'
basePath: /
info:
  version: '1.0'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /app/apm/create_application/:
    post:
      operationId: apm_create_application
      description: 快速创建APM应用
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /apm_api/v1/application/create_application_simple/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: "create apm application"
  /app/apm/start_application/:
    get:
      operationId: apm_start_application
      description: 开启APM应用数据上报
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /apm_api/v1/application/start_application_simple/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: "start apm application data report"
  /app/apm/stop_application/:
    get:
      operationId: apm_stop_application
      description: 关闭APM应用数据上报
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /apm_api/v1/application/stop_application_simple/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: "stop apm application data report"
  /app/apm/delete_application/:
    post:
      operationId: apm_delete_application
      description: 删除应用
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /apm_api/v1/application/delete_application_simple/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: "delete apm application"
  /app/apm/detail_apm_application/:
    get:
      operationId: detail_apm_application
      description: 应用详情
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /apm_api/v1/application/detail_application/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: "get apm application detail"
  /app/apm/apply_strategies_to_services/:
    post:
      operationId: apply_strategies_to_services
      description: 导入策略到 APM 服务
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/application_web/apply_strategies_to_services/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: "apply strategies to apm services"
