swagger: '2.0'
basePath: /
info:
  version: '1.0'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /app/as_code/import_config/:
    post:
      operationId: as_code_import_config
      description: 导入AsCode配置
      x-bk-apigateway-resource:
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/as_code/import_config/
          matchSubpath: false
        descriptionEn: import AsCode config
  /app/as_code/export_config/:
    post:
      operationId: as_code_export_config
      description: 导出AsCode配置
      x-bk-apigateway-resource:
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/as_code/export_config/
          matchSubpath: false
        descriptionEn: export AsCode config
