swagger: '2.0'
basePath: /
info:
  version: '1.0'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /app/collect_plugin/list/:
    get:
      operationId: collector_plugin_list
      description: 采集插件列表
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/collector_plugin/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: collector_plugin_list
  /app/collect_plugin/{plugin_id}/:
    get:
      operationId: collector_plugin_detail
      description: 获取采集插件详情
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/collector_plugin/{plugin_id}/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: collector_plugin_detail
  /app/collect_plugin/delete/:
    post:
      operationId: collector_plugin_delete
      description: 删除插件
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/collector_plugin/delete/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: collector_plugin_delete