swagger: '2.0'
basePath: /
info:
  version: '1.0'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /app/custom_metric/validate_name/:
    get:
      operationId: validate_custom_ts_group_name
      description: 校验自定义指标名称是否合法
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/custom_metric/validate_custom_ts_group_name/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: validate_custom_ts_group_name
  /app/custom_metric/list/:
    get:
      operationId: custom_time_series
      description: 获取自定义指标列表
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/custom_metric/custom_time_series/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: custom_time_series
  /app/custom_metric/detail/:
    get:
      operationId: custom_time_series_detail
      description: 获取自定义指标详情
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/custom_metric/custom_time_series_detail/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: custom_time_series_detail
  /app/custom_metric/create/:
    post:
      operationId: create_custom_time_series
      description: 创建自定义指标
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/custom_metric/create_custom_time_series/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: create_custom_time_series
  /app/custom_metric/modify/:
    post:
      operationId: modify_custom_time_series
      description: 修改自定义指标
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/custom_metric/modify_custom_time_series/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: modify_custom_time_series
  /app/custom_metric/delete/:
    post:
      operationId: delete_custom_time_series
      description: 删除自定义指标
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/custom_metric/delete_custom_time_series/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: delete_custom_time_series
