swagger: '2.0'
basePath: /
info:
  version: '1.0'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /app/meta/metadata_get_event_group/:
    get:
      operationId: metadata_get_event_group
      description: 查询事件分组具体内容
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v3/meta/get_event_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: metadata get event group
  /app/meta/metadata_delete_event_group/:
    post:
      operationId: metadata_delete_event_group
      description: 删除事件分组
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/meta/delete_event_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: metadata delete event group
  /app/meta/metadata_modify_event_group/:
    post:
      operationId: metadata_modify_event_group
      description: 修改事件分组
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/meta/modify_event_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: metadata modify event group
  /app/meta/metadata_create_event_group/:
    post:
      operationId: metadata_create_event_group
      description: 创建事件分组
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/meta/create_event_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: metadata create event group
  /app/meta/metadata_query_event_group/:
    get:
      operationId: metadata_query_event_group
      description: 查询事件分组
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v3/meta/query_event_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: metadata query event group
  /app/event/get_event_log/:
    get:
      operationId: get_event_log
      description: 查询事件流转记录
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/event/event_log/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: get event log
  /app/event/search_event/:
    post:
      operationId: search_event
      description: 查询事件
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/event/search/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: search event
  /app/custom_event/query_custom_event_group/:
    get:
      operationId: query_custom_event_group
      description: 获取业务下自定义事件列表
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/custom_event/query_custom_event_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: query_custom_event_group
  /app/custom_event/get_custom_event_group/:
    get:
      operationId: get_custom_event_group
      description: 获取自定义事件详情
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/custom_event/get_custom_event_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: get_custom_event_group
  /app/custom_event/validate_custom_event_group_name/:
    get:
      operationId: validate_custom_event_group_name
      description: 校验自定义事件名称是否合法
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v4/custom_event/validate_custom_event_group_name/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: validate_custom_event_group_name
  /app/custom_event/create_custom_event_group/:
    post:
      operationId: create_custom_event_group
      description: 创建自定义事件
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/custom_event/create_custom_event_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: create_custom_event_group
  /app/custom_event/modify_custom_event_group/:
    post:
      operationId: modify_custom_event_group
      description: 修改自定义事件
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/custom_event/modify_custom_event_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: modify_custom_event_group
  /app/custom_event/delete_custom_event_group/:
    post:
      operationId: delete_custom_event_group
      description: 删除自定义事件
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v4/custom_event/delete_custom_event_group/
          matchSubpath: false
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: true
        descriptionEn: delete_custom_event_group
