# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
import pytest

from bkmonitor.utils.kubernetes import translate_timestamp_since
from core.drf_resource import resource
from monitor_web.constants import OVERVIEW_ICON

FILTER = [
    {'id': 'success', 'name': 1, 'status': 'success', 'tips': '正常'},
    {'id': 'failed', 'name': 0, 'status': 'failed', 'tips': '异常'},
    {'id': 'disabled', 'name': 0, 'status': 'disabled', 'tips': '无数据'},
]
SORT = [
    {'id': 'pod_count', 'name': 'Pod数量'},
    {'id': 'system_cpu_summary_usage', 'name': 'CPU使用率'},
    {'id': 'system_mem_pct_used', 'name': '应用内存使用率'},
    {'id': 'system_io_util', 'name': '磁盘IO使用率'},
    {'id': 'system_disk_in_use', 'name': '磁盘空间使用率'},
    {'id': 'system_load_load15', 'name': 'CPU十五分钟负载'},
    {'id': 'endpoint_count', 'name': 'Endpoint数量'},
]

DATA = [
    {
        'age': translate_timestamp_since("2022-01-01T00:00:00Z"),
        'bcs_cluster_id': {
            'target': 'blank',
            'url': (
                '?bizId=100#/k8s?sceneId=kubernetes&dashboardId=cluster&sceneType=detail'
                '&queryData={"selectorSearch":[{"bcs_cluster_id":"BCS-K8S-00002"}]}'
            ),
            'value': 'BCS-K8S-00002',
        },
        'cloud_id': '',
        'endpoint_count': 19,
        'label_list': [],
        'monitor_status': {'text': '正常', 'type': 'success'},
        'name': {'icon': '', 'key': '', 'target': 'null_event', 'url': '', 'value': 'node-2-2-2-2'},
        'node_ip': {'target': 'blank', 'url': '?bizId=100#/performance/detail/2.2.2.2-0', 'value': '2.2.2.2'},
        'node_roles': [],
        'pod_count': {
            'target': 'blank',
            'url': (
                '?bizId=100#/k8s?sceneId=kubernetes&dashboardId=pod&sceneType=detail'
                '&queryData={"selectorSearch":[{"bcs_cluster_id":"BCS-K8S-00002"},{"node_ip":"2.2.2.2"}]}'
            ),
            'value': 16,
        },
        'status': 'Ready',
        'system_cpu_summary_usage': {'label': '', 'status': 'NODATA', 'value': 0},
        'system_disk_in_use': {'label': '15.57%', 'status': 'SUCCESS', 'value': 15.57},
        'system_io_util': {'label': '', 'status': 'NODATA', 'value': 0},
        'system_load_load15': '',
        'system_mem_pct_used': {'label': '52.5%', 'status': 'SUCCESS', 'value': 52.5},
        'taints': [],
        'bk_host_id': None,
    }
]


@pytest.mark.django_db(databases=["default", "monitor_api"])
class TestGetKubernetesNodeList:
    def test_perform_request(
        self,
        monkeypatch_request_performance_data,
        add_bcs_nodes,
    ):
        params = {
            "page": 1,
            "page_size": 10,
            "condition_list": [{"bcs_cluster_id": "BCS-K8S-00002"}],
            "bk_biz_id": 100,
        }
        actual = resource.scene_view.get_kubernetes_node_list(params)
        expect = {
            'columns': [
                {
                    'checked': True,
                    'disabled': True,
                    'id': 'name',
                    'max_width': 300,
                    'min_width': 120,
                    'name': '节点名称',
                    'overview_name': '概览',
                    'type': 'link',
                    'width': 248,
                },
                {
                    'checked': True,
                    'disabled': False,
                    'id': 'pod_count',
                    'min_width': 120,
                    'name': 'Pod数量',
                    'sortable': False,
                    'type': 'link',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'filter_list': [{'text': 'BCS-K8S-00002', 'value': 'BCS-K8S-00002'}],
                    'filterable': True,
                    'id': 'bcs_cluster_id',
                    'min_width': 120,
                    'name': '集群ID',
                    'type': 'link',
                },
                {'checked': True, 'disabled': False, 'id': 'node_ip', 'min_width': 120, 'name': '节点IP', 'type': 'link'},
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'cloud_id',
                    'min_width': 120,
                    'name': '云区域',
                    'type': 'string',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'filter_list': [{'text': 'Ready', 'value': 'Ready'}],
                    'filterable': True,
                    'id': 'status',
                    'min_width': 120,
                    'name': '运行状态',
                    'type': 'string',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'monitor_status',
                    'min_width': 120,
                    'name': '采集状态',
                    'type': 'status',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'header_pre_icon': 'icon-avg',
                    'id': 'system_cpu_summary_usage',
                    'min_width': 120,
                    'name': 'CPU使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'header_pre_icon': 'icon-avg',
                    'id': 'system_mem_pct_used',
                    'min_width': 120,
                    'name': '应用内存使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'system_io_util',
                    'min_width': 120,
                    'name': '磁盘IO使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'header_pre_icon': 'icon-avg',
                    'id': 'system_disk_in_use',
                    'min_width': 120,
                    'name': '磁盘空间使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'system_load_load15',
                    'min_width': 120,
                    'name': 'CPU十五分钟负载',
                    'sortable': False,
                    'type': 'str',
                },
                {'checked': False, 'disabled': False, 'id': 'taints', 'min_width': 120, 'name': '污点', 'type': 'list'},
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'node_roles',
                    'min_width': 120,
                    'name': '角色',
                    'type': 'list',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'endpoint_count',
                    'min_width': 120,
                    'name': 'Endpoint数量',
                    'sortable': False,
                    'type': 'number',
                },
                {'checked': False, 'disabled': False, 'id': 'label_list', 'min_width': 120, 'name': '标签', 'type': 'kv'},
                {'checked': True, 'disabled': False, 'id': 'age', 'min_width': 120, 'name': '存活时间', 'type': 'string'},
            ],
            'condition_list': [
                {
                    'children': [{'id': 'BCS-K8S-00002', 'name': 'BCS-K8S-00002'}],
                    'id': 'bcs_cluster_id',
                    'multiable': False,
                    'name': 'cluster',
                },
                {'children': [{'id': 'Ready', 'name': 'Ready'}], 'id': 'status', 'multiable': False, 'name': 'status'},
                {'children': [], 'id': 'roles', 'multiable': False, 'name': 'roles'},
            ],
            'data': DATA,
            'filter': FILTER,
            'overview_data': {
                'age': '',
                'bcs_cluster_id': '',
                'cloud_id': '',
                'endpoint_count': 19,
                'label_list': '',
                'monitor_status': '',
                'name': {
                    'icon': OVERVIEW_ICON,
                    'key': '',
                    'target': 'null_event',
                    'url': '',
                    'value': '概览',
                },
                'node_ip': '',
                'node_roles': '',
                'pod_count': {
                    'target': 'blank',
                    'url': '?bizId=100#/k8s?sceneId=kubernetes&dashboardId=pod&sceneType=overview',
                    'value': 16,
                },
                'status': '',
                'system_cpu_summary_usage': {'label': '10.55%', 'status': 'SUCCESS', 'value': 10.55},
                'system_disk_in_use': {'label': '16.9%', 'status': 'SUCCESS', 'value': 16.9},
                'system_io_util': {'label': '4.8%', 'status': 'SUCCESS', 'value': 4.8},
                'system_load_load15': 1.19,
                'system_mem_pct_used': {'label': '48.82%', 'status': 'SUCCESS', 'value': 48.82},
                'taints': '',
            },
            'sort': SORT,
            'total': 1,
        }
        assert actual == expect

    def test_perform_request__order_by_system_load_load1(
        self,
        monkeypatch_request_performance_data,
        add_bcs_nodes,
    ):
        params = {
            "page": 1,
            "page_size": 10,
            "condition_list": [{"bcs_cluster_id": "BCS-K8S-00002"}],
            "bk_biz_id": 100,
            "sort": "-system_load_load15",
        }
        actual = resource.scene_view.get_kubernetes_node_list(params)
        expect = {
            'columns': [
                {
                    'checked': True,
                    'disabled': True,
                    'id': 'name',
                    'max_width': 300,
                    'min_width': 120,
                    'name': '节点名称',
                    'overview_name': '概览',
                    'type': 'link',
                    'width': 248,
                },
                {
                    'checked': True,
                    'disabled': False,
                    'id': 'system_load_load15',
                    'min_width': 120,
                    'name': 'CPU十五分钟负载',
                    'sortable': False,
                    'type': 'str',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'id': 'pod_count',
                    'min_width': 120,
                    'name': 'Pod数量',
                    'sortable': False,
                    'type': 'link',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'filter_list': [{'text': 'BCS-K8S-00002', 'value': 'BCS-K8S-00002'}],
                    'filterable': True,
                    'id': 'bcs_cluster_id',
                    'min_width': 120,
                    'name': '集群ID',
                    'type': 'link',
                },
                {'checked': True, 'disabled': False, 'id': 'node_ip', 'min_width': 120, 'name': '节点IP', 'type': 'link'},
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'cloud_id',
                    'min_width': 120,
                    'name': '云区域',
                    'type': 'string',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'filter_list': [{'text': 'Ready', 'value': 'Ready'}],
                    'filterable': True,
                    'id': 'status',
                    'min_width': 120,
                    'name': '运行状态',
                    'type': 'string',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'monitor_status',
                    'min_width': 120,
                    'name': '采集状态',
                    'type': 'status',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'header_pre_icon': 'icon-avg',
                    'id': 'system_cpu_summary_usage',
                    'min_width': 120,
                    'name': 'CPU使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'header_pre_icon': 'icon-avg',
                    'id': 'system_mem_pct_used',
                    'min_width': 120,
                    'name': '应用内存使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'system_io_util',
                    'min_width': 120,
                    'name': '磁盘IO使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'header_pre_icon': 'icon-avg',
                    'id': 'system_disk_in_use',
                    'min_width': 120,
                    'name': '磁盘空间使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {'checked': False, 'disabled': False, 'id': 'taints', 'min_width': 120, 'name': '污点', 'type': 'list'},
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'node_roles',
                    'min_width': 120,
                    'name': '角色',
                    'type': 'list',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'endpoint_count',
                    'min_width': 120,
                    'name': 'Endpoint数量',
                    'sortable': False,
                    'type': 'number',
                },
                {'checked': False, 'disabled': False, 'id': 'label_list', 'min_width': 120, 'name': '标签', 'type': 'kv'},
                {'checked': True, 'disabled': False, 'id': 'age', 'min_width': 120, 'name': '存活时间', 'type': 'string'},
            ],
            'condition_list': [
                {
                    'children': [{'id': 'BCS-K8S-00002', 'name': 'BCS-K8S-00002'}],
                    'id': 'bcs_cluster_id',
                    'multiable': False,
                    'name': 'cluster',
                },
                {'children': [{'id': 'Ready', 'name': 'Ready'}], 'id': 'status', 'multiable': False, 'name': 'status'},
                {'children': [], 'id': 'roles', 'multiable': False, 'name': 'roles'},
            ],
            'data': [
                {
                    'age': translate_timestamp_since('2022-01-01T00:00:00Z'),
                    'bcs_cluster_id': {
                        'target': 'blank',
                        'url': (
                            '?bizId=100#/k8s?sceneId=kubernetes&dashboardId=cluster&sceneType=detail'
                            '&queryData={"selectorSearch":[{"bcs_cluster_id":"BCS-K8S-00002"}]}'
                        ),
                        'value': 'BCS-K8S-00002',
                    },
                    'cloud_id': '',
                    'endpoint_count': 19,
                    'label_list': [],
                    'monitor_status': {'text': '正常', 'type': 'success'},
                    'name': {'icon': '', 'key': '', 'target': 'null_event', 'url': '', 'value': 'node-2-2-2-2'},
                    'node_ip': {
                        'target': 'blank',
                        'url': '?bizId=100#/performance/detail/2.2.2.2-0',
                        'value': '2.2.2.2',
                    },
                    'node_roles': [],
                    'pod_count': {
                        'target': 'blank',
                        'url': (
                            '?bizId=100#/k8s?sceneId=kubernetes&dashboardId=pod&sceneType=detail'
                            '&queryData={"selectorSearch":[{"bcs_cluster_id":"BCS-K8S-00002"},{"node_ip":"2.2.2.2"}]}'
                        ),
                        'value': 16,
                    },
                    'status': 'Ready',
                    'system_cpu_summary_usage': {'label': '', 'status': 'NODATA', 'value': 0},
                    'system_disk_in_use': {'label': '15.57%', 'status': 'SUCCESS', 'value': 15.57},
                    'system_io_util': {'label': '', 'status': 'NODATA', 'value': 0},
                    'system_load_load15': '',
                    'system_mem_pct_used': {'label': '52.5%', 'status': 'SUCCESS', 'value': 52.5},
                    'taints': [],
                    'bk_host_id': None,
                }
            ],
            'filter': FILTER,
            'overview_data': {
                'age': '',
                'bcs_cluster_id': '',
                'cloud_id': '',
                'endpoint_count': 19,
                'label_list': '',
                'monitor_status': '',
                'name': {
                    'icon': OVERVIEW_ICON,
                    'key': '',
                    'target': 'null_event',
                    'url': '',
                    'value': '概览',
                },
                'node_ip': '',
                'node_roles': '',
                'pod_count': {
                    'target': 'blank',
                    'url': '?bizId=100#/k8s?sceneId=kubernetes&dashboardId=pod&sceneType=overview',
                    'value': 16,
                },
                'status': '',
                'system_cpu_summary_usage': {'label': '10.55%', 'status': 'SUCCESS', 'value': 10.55},
                'system_disk_in_use': {'label': '16.9%', 'status': 'SUCCESS', 'value': 16.9},
                'system_io_util': {'label': '4.8%', 'status': 'SUCCESS', 'value': 4.8},
                'system_load_load15': 1.19,
                'system_mem_pct_used': {'label': '48.82%', 'status': 'SUCCESS', 'value': 48.82},
                'taints': '',
            },
            'sort': SORT,
            'total': 1,
        }
        assert actual == expect

    def test_perform_request__order_by_system_cpu_summary_usage(
        self,
        monkeypatch_request_performance_data,
        add_bcs_nodes,
    ):
        params = {
            "page": 1,
            "page_size": 10,
            "condition_list": [{"bcs_cluster_id": "BCS-K8S-00002"}],
            "bk_biz_id": 100,
            "sort": "-system_cpu_summary_usage",
        }
        actual = resource.scene_view.get_kubernetes_node_list(params)
        expect = {
            'columns': [
                {
                    'checked': True,
                    'disabled': True,
                    'id': 'name',
                    'max_width': 300,
                    'min_width': 120,
                    'name': '节点名称',
                    'overview_name': '概览',
                    'type': 'link',
                    'width': 248,
                },
                {
                    'checked': True,
                    'disabled': False,
                    'header_pre_icon': 'icon-avg',
                    'id': 'system_cpu_summary_usage',
                    'min_width': 120,
                    'name': 'CPU使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'id': 'pod_count',
                    'min_width': 120,
                    'name': 'Pod数量',
                    'sortable': False,
                    'type': 'link',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'filter_list': [{'text': 'BCS-K8S-00002', 'value': 'BCS-K8S-00002'}],
                    'filterable': True,
                    'id': 'bcs_cluster_id',
                    'min_width': 120,
                    'name': '集群ID',
                    'type': 'link',
                },
                {'checked': True, 'disabled': False, 'id': 'node_ip', 'min_width': 120, 'name': '节点IP', 'type': 'link'},
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'cloud_id',
                    'min_width': 120,
                    'name': '云区域',
                    'type': 'string',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'filter_list': [{'text': 'Ready', 'value': 'Ready'}],
                    'filterable': True,
                    'id': 'status',
                    'min_width': 120,
                    'name': '运行状态',
                    'type': 'string',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'monitor_status',
                    'min_width': 120,
                    'name': '采集状态',
                    'type': 'status',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'header_pre_icon': 'icon-avg',
                    'id': 'system_mem_pct_used',
                    'min_width': 120,
                    'name': '应用内存使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'system_io_util',
                    'min_width': 120,
                    'name': '磁盘IO使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'header_pre_icon': 'icon-avg',
                    'id': 'system_disk_in_use',
                    'min_width': 120,
                    'name': '磁盘空间使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'system_load_load15',
                    'min_width': 120,
                    'name': 'CPU十五分钟负载',
                    'sortable': False,
                    'type': 'str',
                },
                {'checked': False, 'disabled': False, 'id': 'taints', 'min_width': 120, 'name': '污点', 'type': 'list'},
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'node_roles',
                    'min_width': 120,
                    'name': '角色',
                    'type': 'list',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'endpoint_count',
                    'min_width': 120,
                    'name': 'Endpoint数量',
                    'sortable': False,
                    'type': 'number',
                },
                {'checked': False, 'disabled': False, 'id': 'label_list', 'min_width': 120, 'name': '标签', 'type': 'kv'},
                {'checked': True, 'disabled': False, 'id': 'age', 'min_width': 120, 'name': '存活时间', 'type': 'string'},
            ],
            'condition_list': [
                {
                    'children': [{'id': 'BCS-K8S-00002', 'name': 'BCS-K8S-00002'}],
                    'id': 'bcs_cluster_id',
                    'multiable': False,
                    'name': 'cluster',
                },
                {'children': [{'id': 'Ready', 'name': 'Ready'}], 'id': 'status', 'multiable': False, 'name': 'status'},
                {'children': [], 'id': 'roles', 'multiable': False, 'name': 'roles'},
            ],
            'data': DATA,
            'filter': FILTER,
            'overview_data': {
                'age': '',
                'bcs_cluster_id': '',
                'cloud_id': '',
                'endpoint_count': 19,
                'label_list': '',
                'monitor_status': '',
                'name': {
                    'icon': OVERVIEW_ICON,
                    'key': '',
                    'target': 'null_event',
                    'url': '',
                    'value': '概览',
                },
                'node_ip': '',
                'node_roles': '',
                'pod_count': {
                    'target': 'blank',
                    'url': '?bizId=100#/k8s?sceneId=kubernetes&dashboardId=pod&sceneType=overview',
                    'value': 16,
                },
                'status': '',
                'system_cpu_summary_usage': {'label': '10.55%', 'status': 'SUCCESS', 'value': 10.55},
                'system_disk_in_use': {'label': '16.9%', 'status': 'SUCCESS', 'value': 16.9},
                'system_io_util': {'label': '4.8%', 'status': 'SUCCESS', 'value': 4.8},
                'system_load_load15': 1.19,
                'system_mem_pct_used': {'label': '48.82%', 'status': 'SUCCESS', 'value': 48.82},
                'taints': '',
            },
            'sort': SORT,
            'total': 1,
        }
        assert actual == expect

    def test_perform_request__page_out(
        self,
        monkeypatch_request_performance_data,
        add_bcs_nodes,
    ):
        params = {
            "page": 100,
            "page_size": 10,
            "condition_list": [{"bcs_cluster_id": "BCS-K8S-00002"}],
            "bk_biz_id": 100,
            "sort": "-system_cpu_summary_usage",
        }
        actual = resource.scene_view.get_kubernetes_node_list(params)
        expect = {
            'columns': [
                {
                    'checked': True,
                    'disabled': True,
                    'id': 'name',
                    'max_width': 300,
                    'min_width': 120,
                    'name': '节点名称',
                    'overview_name': '概览',
                    'type': 'link',
                    'width': 248,
                },
                {
                    'checked': True,
                    'disabled': False,
                    'header_pre_icon': 'icon-avg',
                    'id': 'system_cpu_summary_usage',
                    'min_width': 120,
                    'name': 'CPU使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'id': 'pod_count',
                    'min_width': 120,
                    'name': 'Pod数量',
                    'sortable': False,
                    'type': 'link',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'filter_list': [{'text': 'BCS-K8S-00002', 'value': 'BCS-K8S-00002'}],
                    'filterable': True,
                    'id': 'bcs_cluster_id',
                    'min_width': 120,
                    'name': '集群ID',
                    'type': 'link',
                },
                {'checked': True, 'disabled': False, 'id': 'node_ip', 'min_width': 120, 'name': '节点IP', 'type': 'link'},
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'cloud_id',
                    'min_width': 120,
                    'name': '云区域',
                    'type': 'string',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'filter_list': [{'text': 'Ready', 'value': 'Ready'}],
                    'filterable': True,
                    'id': 'status',
                    'min_width': 120,
                    'name': '运行状态',
                    'type': 'string',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'monitor_status',
                    'min_width': 120,
                    'name': '采集状态',
                    'type': 'status',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'header_pre_icon': 'icon-avg',
                    'id': 'system_mem_pct_used',
                    'min_width': 120,
                    'name': '应用内存使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'system_io_util',
                    'min_width': 120,
                    'name': '磁盘IO使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'header_pre_icon': 'icon-avg',
                    'id': 'system_disk_in_use',
                    'min_width': 120,
                    'name': '磁盘空间使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'system_load_load15',
                    'min_width': 120,
                    'name': 'CPU十五分钟负载',
                    'sortable': False,
                    'type': 'str',
                },
                {'checked': False, 'disabled': False, 'id': 'taints', 'min_width': 120, 'name': '污点', 'type': 'list'},
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'node_roles',
                    'min_width': 120,
                    'name': '角色',
                    'type': 'list',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'endpoint_count',
                    'min_width': 120,
                    'name': 'Endpoint数量',
                    'sortable': False,
                    'type': 'number',
                },
                {'checked': False, 'disabled': False, 'id': 'label_list', 'min_width': 120, 'name': '标签', 'type': 'kv'},
                {'checked': True, 'disabled': False, 'id': 'age', 'min_width': 120, 'name': '存活时间', 'type': 'string'},
            ],
            'condition_list': [
                {
                    'children': [{'id': 'BCS-K8S-00002', 'name': 'BCS-K8S-00002'}],
                    'id': 'bcs_cluster_id',
                    'multiable': False,
                    'name': 'cluster',
                },
                {'children': [{'id': 'Ready', 'name': 'Ready'}], 'id': 'status', 'multiable': False, 'name': 'status'},
                {'children': [], 'id': 'roles', 'multiable': False, 'name': 'roles'},
            ],
            'data': [],
            'filter': FILTER,
            'overview_data': {
                'age': '',
                'bcs_cluster_id': '',
                'cloud_id': '',
                'endpoint_count': 19,
                'label_list': '',
                'monitor_status': '',
                'name': {
                    'icon': OVERVIEW_ICON,
                    'key': '',
                    'target': 'null_event',
                    'url': '',
                    'value': '概览',
                },
                'node_ip': '',
                'node_roles': '',
                'pod_count': {
                    'target': 'blank',
                    'url': '?bizId=100#/k8s?sceneId=kubernetes&dashboardId=pod&sceneType=overview',
                    'value': 16,
                },
                'status': '',
                'system_cpu_summary_usage': {'label': '10.55%', 'status': 'SUCCESS', 'value': 10.55},
                'system_disk_in_use': {'label': '16.9%', 'status': 'SUCCESS', 'value': 16.9},
                'system_io_util': {'label': '4.8%', 'status': 'SUCCESS', 'value': 4.8},
                'system_load_load15': 1.19,
                'system_mem_pct_used': {'label': '48.82%', 'status': 'SUCCESS', 'value': 48.82},
                'taints': '',
            },
            'sort': SORT,
            'total': 1,
        }
        assert actual == expect

    def test_perform_request__order_by_pod_count(
        self,
        monkeypatch_request_performance_data,
        add_bcs_nodes,
    ):
        params = {
            "page": 1,
            "page_size": 10,
            "condition_list": [{"bcs_cluster_id": "BCS-K8S-00002"}],
            "bk_biz_id": 100,
            "sort": "-pod_count",
        }
        actual = resource.scene_view.get_kubernetes_node_list(params)
        expect = {
            'columns': [
                {
                    'checked': True,
                    'disabled': True,
                    'id': 'name',
                    'max_width': 300,
                    'min_width': 120,
                    'name': '节点名称',
                    'overview_name': '概览',
                    'type': 'link',
                    'width': 248,
                },
                {
                    'checked': True,
                    'disabled': False,
                    'id': 'pod_count',
                    'min_width': 120,
                    'name': 'Pod数量',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'filter_list': [{'text': 'BCS-K8S-00002', 'value': 'BCS-K8S-00002'}],
                    'filterable': True,
                    'id': 'bcs_cluster_id',
                    'min_width': 120,
                    'name': '集群ID',
                    'type': 'link',
                },
                {'checked': True, 'disabled': False, 'id': 'node_ip', 'min_width': 120, 'name': '节点IP', 'type': 'link'},
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'cloud_id',
                    'min_width': 120,
                    'name': '云区域',
                    'type': 'string',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'filter_list': [{'text': 'Ready', 'value': 'Ready'}],
                    'filterable': True,
                    'id': 'status',
                    'min_width': 120,
                    'name': '运行状态',
                    'type': 'string',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'monitor_status',
                    'min_width': 120,
                    'name': '采集状态',
                    'type': 'status',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'header_pre_icon': 'icon-avg',
                    'id': 'system_cpu_summary_usage',
                    'min_width': 120,
                    'name': 'CPU使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'header_pre_icon': 'icon-avg',
                    'id': 'system_mem_pct_used',
                    'min_width': 120,
                    'name': '应用内存使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'system_io_util',
                    'min_width': 120,
                    'name': '磁盘IO使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'header_pre_icon': 'icon-avg',
                    'id': 'system_disk_in_use',
                    'min_width': 120,
                    'name': '磁盘空间使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'system_load_load15',
                    'min_width': 120,
                    'name': 'CPU十五分钟负载',
                    'sortable': False,
                    'type': 'str',
                },
                {'checked': False, 'disabled': False, 'id': 'taints', 'min_width': 120, 'name': '污点', 'type': 'list'},
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'node_roles',
                    'min_width': 120,
                    'name': '角色',
                    'type': 'list',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'endpoint_count',
                    'min_width': 120,
                    'name': 'Endpoint数量',
                    'sortable': False,
                    'type': 'number',
                },
                {'checked': False, 'disabled': False, 'id': 'label_list', 'min_width': 120, 'name': '标签', 'type': 'kv'},
                {'checked': True, 'disabled': False, 'id': 'age', 'min_width': 120, 'name': '存活时间', 'type': 'string'},
            ],
            'condition_list': [
                {
                    'children': [{'id': 'BCS-K8S-00002', 'name': 'BCS-K8S-00002'}],
                    'id': 'bcs_cluster_id',
                    'multiable': False,
                    'name': 'cluster',
                },
                {'children': [{'id': 'Ready', 'name': 'Ready'}], 'id': 'status', 'multiable': False, 'name': 'status'},
                {'children': [], 'id': 'roles', 'multiable': False, 'name': 'roles'},
            ],
            'data': [
                {
                    'age': translate_timestamp_since('2022-01-01T00:00:00Z'),
                    'bcs_cluster_id': {
                        'target': 'blank',
                        'url': (
                            '?bizId=100#/k8s?sceneId=kubernetes&dashboardId=cluster&sceneType=detail'
                            '&queryData={"selectorSearch":[{"bcs_cluster_id":"BCS-K8S-00002"}]}'
                        ),
                        'value': 'BCS-K8S-00002',
                    },
                    'cloud_id': '',
                    'endpoint_count': 19,
                    'label_list': [],
                    'monitor_status': {'text': '正常', 'type': 'success'},
                    'name': {'icon': '', 'key': '', 'target': 'null_event', 'url': '', 'value': 'node-2-2-2-2'},
                    'node_ip': {
                        'target': 'blank',
                        'url': '?bizId=100#/performance/detail/2.2.2.2-0',
                        'value': '2.2.2.2',
                    },
                    'node_roles': [],
                    'pod_count': {'label': 16, 'status': 'SUCCESS', 'value': 100.0},
                    'status': 'Ready',
                    'system_cpu_summary_usage': {'label': '', 'status': 'NODATA', 'value': 0},
                    'system_disk_in_use': {'label': '15.57%', 'status': 'SUCCESS', 'value': 15.57},
                    'system_io_util': {'label': '', 'status': 'NODATA', 'value': 0},
                    'system_load_load15': '',
                    'system_mem_pct_used': {'label': '52.5%', 'status': 'SUCCESS', 'value': 52.5},
                    'taints': [],
                    'bk_host_id': None,
                }
            ],
            'filter': FILTER,
            'overview_data': {
                'age': '',
                'bcs_cluster_id': '',
                'cloud_id': '',
                'endpoint_count': 19,
                'label_list': '',
                'monitor_status': '',
                'name': {
                    'icon': OVERVIEW_ICON,
                    'key': '',
                    'target': 'null_event',
                    'url': '',
                    'value': '概览',
                },
                'node_ip': '',
                'node_roles': '',
                'pod_count': {'label': 16, 'status': 'SUCCESS', 'value': 100},
                'status': '',
                'system_cpu_summary_usage': {'label': '10.55%', 'status': 'SUCCESS', 'value': 10.55},
                'system_disk_in_use': {'label': '16.9%', 'status': 'SUCCESS', 'value': 16.9},
                'system_io_util': {'label': '4.8%', 'status': 'SUCCESS', 'value': 4.8},
                'system_load_load15': 1.19,
                'system_mem_pct_used': {'label': '48.82%', 'status': 'SUCCESS', 'value': 48.82},
                'taints': '',
            },
            'sort': SORT,
            'total': 1,
        }
        assert actual == expect

    def test_perform_request__filter_roles(
        self,
        monkeypatch_request_performance_data,
        add_bcs_nodes,
    ):
        params = {
            "page": 1,
            "page_size": 10,
            "condition_list": [{"bcs_cluster_id": "BCS-K8S-00000"}, {"roles": "master"}],
            "bk_biz_id": 2,
        }
        results = resource.scene_view.get_kubernetes_node_list(params)
        assert len(results["data"]) == 1
        assert results["data"][0]['node_roles'] == ['control-plane', 'master']

        params = {
            "page": 1,
            "page_size": 10,
            "condition_list": [{"bcs_cluster_id": "BCS-K8S-00000"}, {"roles": "control-plane"}],
            "bk_biz_id": 2,
        }
        results = resource.scene_view.get_kubernetes_node_list(params)
        assert len(results["data"]) == 1
        assert results["data"][0]['node_roles'] == ['control-plane', 'master']

        params = {
            "page": 1,
            "page_size": 10,
            "condition_list": [{"bcs_cluster_id": "BCS-K8S-00002"}, {"roles": ""}],
            "bk_biz_id": 100,
        }
        results = resource.scene_view.get_kubernetes_node_list(params)
        assert len(results["data"]) == 1
        assert results["data"][0]['node_roles'] == []

    def test_perform_request__ci_space(
        self,
        monkeypatch_get_space_detail,
        monkeypatch_get_clusters_by_space_uid,
        monkeypatch_request_performance_data,
        add_bcs_cluster_item_for_update_and_delete,
        add_bcs_nodes,
    ):
        """只返回独立集群，忽略共享集群 ."""
        params = {
            "page": 1,
            "page_size": 10,
            "condition_list": [],
            "bk_biz_id": -3,
        }
        actual = resource.scene_view.get_kubernetes_node_list(params)
        expect = {
            'columns': [
                {
                    'checked': True,
                    'disabled': True,
                    'id': 'name',
                    'max_width': 300,
                    'min_width': 120,
                    'name': '节点名称',
                    'overview_name': '概览',
                    'type': 'link',
                    'width': 248,
                },
                {
                    'checked': True,
                    'disabled': False,
                    'id': 'pod_count',
                    'min_width': 120,
                    'name': 'Pod数量',
                    'sortable': False,
                    'type': 'link',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'filter_list': [
                        {'text': 'BCS-K8S-00000', 'value': 'BCS-K8S-00000'},
                        {'text': 'BCS-K8S-00002', 'value': 'BCS-K8S-00002'},
                    ],
                    'filterable': True,
                    'id': 'bcs_cluster_id',
                    'min_width': 120,
                    'name': '集群ID',
                    'type': 'link',
                },
                {'checked': True, 'disabled': False, 'id': 'node_ip', 'min_width': 120, 'name': '节点IP', 'type': 'link'},
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'cloud_id',
                    'min_width': 120,
                    'name': '云区域',
                    'type': 'string',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'filter_list': [{'text': 'Ready', 'value': 'Ready'}],
                    'filterable': True,
                    'id': 'status',
                    'min_width': 120,
                    'name': '运行状态',
                    'type': 'string',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'monitor_status',
                    'min_width': 120,
                    'name': '采集状态',
                    'type': 'status',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'header_pre_icon': 'icon-avg',
                    'id': 'system_cpu_summary_usage',
                    'min_width': 120,
                    'name': 'CPU使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'header_pre_icon': 'icon-avg',
                    'id': 'system_mem_pct_used',
                    'min_width': 120,
                    'name': '应用内存使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'system_io_util',
                    'min_width': 120,
                    'name': '磁盘IO使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': True,
                    'disabled': False,
                    'header_pre_icon': 'icon-avg',
                    'id': 'system_disk_in_use',
                    'min_width': 120,
                    'name': '磁盘空间使用率',
                    'sortable': False,
                    'type': 'progress',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'system_load_load15',
                    'min_width': 120,
                    'name': 'CPU十五分钟负载',
                    'sortable': False,
                    'type': 'str',
                },
                {'checked': False, 'disabled': False, 'id': 'taints', 'min_width': 120, 'name': '污点', 'type': 'list'},
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'node_roles',
                    'min_width': 120,
                    'name': '角色',
                    'type': 'list',
                },
                {
                    'checked': False,
                    'disabled': False,
                    'id': 'endpoint_count',
                    'min_width': 120,
                    'name': 'Endpoint数量',
                    'sortable': False,
                    'type': 'number',
                },
                {'checked': False, 'disabled': False, 'id': 'label_list', 'min_width': 120, 'name': '标签', 'type': 'kv'},
                {'checked': True, 'disabled': False, 'id': 'age', 'min_width': 120, 'name': '存活时间', 'type': 'string'},
            ],
            'condition_list': [
                {
                    'children': [
                        {'id': 'BCS-K8S-00000', 'name': 'BCS-K8S-00000'},
                    ],
                    'id': 'bcs_cluster_id',
                    'multiable': False,
                    'name': 'cluster',
                },
                {'children': [{'id': 'Ready', 'name': 'Ready'}], 'id': 'status', 'multiable': False, 'name': 'status'},
                {
                    'children': [{'id': 'control-plane,master', 'name': 'control-plane,master'}],
                    'id': 'roles',
                    'multiable': False,
                    'name': 'roles',
                },
            ],
            'data': [
                {
                    'age': translate_timestamp_since('2022-01-01T00:00:00Z'),
                    'bcs_cluster_id': {
                        'target': 'blank',
                        'url': (
                            '?bizId=-3#/k8s?sceneId=kubernetes&dashboardId=cluster&sceneType=detail'
                            '&queryData={"selectorSearch":[{"bcs_cluster_id":"BCS-K8S-00000"}]}'
                        ),
                        'value': 'BCS-K8S-00000',
                    },
                    'cloud_id': '',
                    'endpoint_count': 19,
                    'label_list': [],
                    'monitor_status': {'text': '正常', 'type': 'success'},
                    'name': {'icon': '', 'key': '', 'target': 'null_event', 'url': '', 'value': 'master-1-1-1-1'},
                    'node_ip': {'target': 'blank', 'url': '?bizId=2#/performance/detail/1.1.1.1-0', 'value': '1.1.1.1'},
                    'node_roles': ['control-plane', 'master'],
                    'pod_count': {
                        'target': 'blank',
                        'url': (
                            '?bizId=-3#/k8s?sceneId=kubernetes&dashboardId=pod&sceneType=detail'
                            '&queryData={"selectorSearch":[{"bcs_cluster_id":"BCS-K8S-00000"},{"node_ip":"1.1.1.1"}]}'
                        ),
                        'value': 16,
                    },
                    'status': 'Ready',
                    'system_cpu_summary_usage': {'label': '9.08%', 'status': 'SUCCESS', 'value': 9.08},
                    'system_disk_in_use': {'label': '15.57%', 'status': 'SUCCESS', 'value': 15.57},
                    'system_io_util': {'label': '4.12%', 'status': 'SUCCESS', 'value': 4.12},
                    'system_load_load15': 1.38,
                    'system_mem_pct_used': {'label': '52.5%', 'status': 'SUCCESS', 'value': 52.5},
                    'taints': [],
                    'bk_host_id': None,
                }
            ],
            'filter': FILTER,
            'overview_data': {
                'age': '',
                'bcs_cluster_id': '',
                'cloud_id': '',
                'endpoint_count': 38,
                'label_list': '',
                'monitor_status': '',
                'name': {
                    'icon': OVERVIEW_ICON,
                    'key': '',
                    'target': 'null_event',
                    'url': '',
                    'value': '概览',
                },
                'node_ip': '',
                'node_roles': '',
                'pod_count': {
                    'target': 'blank',
                    'url': '?bizId=-3#/k8s?sceneId=kubernetes&dashboardId=pod&sceneType=overview',
                    'value': 32,
                },
                'status': '',
                'system_cpu_summary_usage': {'label': '10.55%', 'status': 'SUCCESS', 'value': 10.55},
                'system_disk_in_use': {'label': '16.9%', 'status': 'SUCCESS', 'value': 16.9},
                'system_io_util': {'label': '4.8%', 'status': 'SUCCESS', 'value': 4.8},
                'system_load_load15': 1.19,
                'system_mem_pct_used': {'label': '48.82%', 'status': 'SUCCESS', 'value': 48.82},
                'taints': '',
            },
            'sort': SORT,
            'total': 1,
        }
        assert actual == expect
