# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""

BK_PLUGIN_INITIAL_TEMPLATE = """{
    "id":"{{plugin_id}}",
    "name":"{{plugin_name}}",
    "is_builtin":false,
    "is_deleted":false,
    "is_peripheral": true,
    "plugin_source":"bk_plugin",
    "plugin_type":"common",
    "plugin_key":"{{plugin_code}}",
    "has_child":true,
    "description":"{{plugin_description}}",
    "config_schema":{
        "template":{
            "resource_class":"BkPluginMetaResource",
            "name":"插件版本",
            "init_kwargs":{
                "url":"{{plugin_address}}"
            },
            "resource_module":"api.bk_plugin.default",
            "resource_data":"response",
            "mapping":{
                "id":"{{version}}",
                "name":"{{name}}"
            }
        },
        "plugin_url":{
            "mapping":{
                "url":"{{plugin_address}}/",
                "tips":"前往插件"
            }
        },
        "detail":{
            "name":"插件参数",
            "resource_class":"BkPluginDetailResource",
            "resource_module":"api.bk_plugin.default",
            "request_data_mapping": {
                "version": "{{template_id}}"
            },
            "init_kwargs":{
                "url":"{{plugin_address}}"
            },
            "resource_data":"response.inputs",
            "mapping":{
                "key":"{{key}}",
                "name":"{{title}}",
                "value":"{{default}}",
                "category":"{{type}}",
                "placeholder":"{{description}}",
                "required":"{{required}}"
            }
        },
        "content_template_with_url":"蓝鲸插件[{{plugin_name}}]任务【{{action_name}}】处理{{status_display}}, 点击$查看详情$",
        "content_template":"蓝鲸插件[{{plugin_name}}]任务【{{action_name}}】处理{{status_display}}, 请关注！！"
    },
    "backend_config":[
        {
            "function":"create_task",
            "name":"创建任务",
            "resource_class":"BkPluginInvokeResource",
            "resource_module":"api.bk_plugin.default",
            "init_kwargs":{
                "url":"{{plugin_apigw_host}}"
            },
            "inputs":[
                {
                    "key":"inputs",
                    "value":"execute_config.template_detail",
                    "type":"dict",
                    "format":"jmespath"
                },
                {
                    "key":"bk_biz_id",
                    "value":"bk_biz_id",
                    "type":"int",
                    "format":"jmespath"
                },
                {
                    "key":"creator",
                    "value":"operator",
                    "type":"string",
                    "format":"jmespath"
                },
                {
                    "key":"version",
                    "value":"execute_config.template_id",
                    "type":"string",
                    "format":"jmespath"
                }
            ],
            "outputs":[
                {
                    "key":"trace_id",
                    "value":"response.trace_id",
                    "format":"jmespath"
                },
                {
                    "key":"state",
                    "value":"response.data.state",
                    "format":"jmespath"
                },
                {
                    "key":"outputs",
                    "value":"response.data.outputs",
                    "format":"jmespath"
                },
                {
                    "key":"message",
                    "value":"response.data.err",
                    "format":"jmespath"
                },
                {
                    "key":"bkplugin_schedule_url",
                    "value":"{{plugin_address}}/bk_plugin/schedule/{{trace_id}}",
                    "format":"jinja2"
                },
                {
                    "key":"url",
                    "value":"response.data.outputs.url",
                    "format":"jmespath"
                }
            ],
            "finished_rule":{
                "key":"state",
                "method":"in",
                "value":[
                    4,
                    5
                ]
            },
            "success_rule":{
                "key":"state",
                "method":"equal",
                "value":4
            },
            "next_function":"schedule",
            "need_insert_log":true,
            "log_template":"根据套餐【{{action_name}}】的配置已成功创建蓝鲸插件[{{plugin_name}}]任务，点击$查看详情$"
        },
        {
            "function":"schedule",
            "name":"轮询状态",
            "resource_class":"BkPluginScheduleResource",
            "resource_module":"api.bk_plugin.default",
            "init_kwargs":{
                "url":"{{plugin_address}}"
            },
            "inputs":[
                {
                    "key":"trace_id",
                    "value":"pre_node_outputs.trace_id",
                    "type":"string",
                    "format":"jmespath"
                }
            ],
            "outputs":[
                {
                    "key":"state",
                    "value":"response.state",
                    "format":"jmespath"
                },
                {
                    "key":"outputs",
                    "value":"response.outputs",
                    "format":"jmespath"
                },
                {
                    "key":"message",
                    "value":"response.err",
                    "format":"jmespath"
                },
                {
                    "key":"bkplugin_schedule_url",
                    "value":"{{plugin_address}}/bk_plugin/schedule/{{trace_id}}",
                    "format":"jinja2"
                },
                {
                    "key":"url",
                    "value":"response.outputs.url",
                    "format":"jmespath"
                }
            ],
            "finished_rule":{
                "key":"state",
                "method":"in",
                "value":[
                    4,
                    5
                ]
            },
            "success_rule":{
                "key":"state",
                "method":"equal",
                "value":4
            },
            "need_schedule":true,
            "schedule_timedelta":2,
            "next_function":"schedule"
        }
    ]
}
"""
