# Generated by Django 4.2.27 on 2026-01-17 08:07

import bk_monitor_base.domains.strategy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否内置')),
                ('name', models.CharField(max_length=128, verbose_name='套餐名称')),
                ('desc', models.TextField(default='', verbose_name='套餐描述')),
                ('bk_biz_id', models.CharField(max_length=64, verbose_name='业务ID')),
                ('plugin_id', models.CharField(max_length=64, verbose_name='插件ID')),
                ('execute_config', models.TextField(verbose_name='执行任务参数配置')),
                ('app', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='所属应用')),
                ('path', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='资源路径')),
                ('hash', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='原始配置摘要')),
                ('snippet', models.TextField(blank=True, default='', null=True, verbose_name='配置片段')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_user', models.CharField(blank=True, default='', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(blank=True, default='', max_length=32, verbose_name='最后修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '自愈套餐',
                'verbose_name_plural': '自愈套餐',
                'db_table': 'action_config',
                'ordering': ('-update_time', '-id'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlgorithmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.IntegerField(db_index=True, verbose_name='关联策略ID')),
                ('item_id', models.IntegerField(db_index=True, verbose_name='关联监控项ID')),
                ('level', models.IntegerField(choices=[(1, '致命'), (2, '预警'), (3, '提醒')], default=3, verbose_name='告警级别')),
                ('type', models.CharField(choices=[('Threshold', '静态阈值算法'), ('NewSeries', '新序列算法'), ('SimpleRingRatio', '简易环比算法'), ('AdvancedRingRatio', '高级环比算法'), ('SimpleYearRound', '简易同比算法'), ('AdvancedYearRound', '高级同比算法'), ('PartialNodes', '部分节点数算法'), ('OsRestart', '主机重启算法'), ('ProcPort', '进程端口算法'), ('PingUnreachable', 'Ping不可达算法'), ('YearRoundAmplitude', '同比振幅算法'), ('YearRoundRange', '同比区间算法'), ('RingRatioAmplitude', '环比振幅算法'), ('IntelligentDetect', '智能异常检测算法'), ('TimeSeriesForecasting', '时序预测算法'), ('AbnormalCluster', '离群检测算法'), ('MultivariateAnomalyDetection', '多指标异常检测算法'), ('HostAnomalyDetection', '主机异常检测算法')], db_index=True, max_length=64, verbose_name='算法类型')),
                ('unit_prefix', models.CharField(blank=True, default='', max_length=32, verbose_name='算法单位前缀')),
                ('config', models.JSONField(default=dict, verbose_name='算法配置')),
            ],
            options={
                'verbose_name': '检测算法配置V2',
                'verbose_name_plural': '检测算法配置V2',
                'db_table': 'alarm_algorithm_v2',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.IntegerField(db_index=True, verbose_name='关联策略ID')),
                ('level', models.IntegerField(choices=[(1, '致命'), (2, '预警'), (3, '提醒')], default=3, verbose_name='告警级别')),
                ('expression', models.TextField(default='', verbose_name='计算公式')),
                ('trigger_config', models.JSONField(default=dict, verbose_name='触发条件配置')),
                ('recovery_config', models.JSONField(default=dict, verbose_name='恢复条件配置')),
                ('connector', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=4, verbose_name='同级别算法连接符')),
            ],
            options={
                'verbose_name': '检测配置V2',
                'verbose_name_plural': '检测配置V2',
                'db_table': 'alarm_detect_v2',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.IntegerField(db_index=True, verbose_name='关联策略ID')),
                ('name', models.CharField(max_length=256, verbose_name='监控项名称')),
                ('expression', models.TextField(verbose_name='计算公式')),
                ('functions', models.JSONField(default=list, verbose_name='计算函数')),
                ('origin_sql', models.TextField(verbose_name='原始查询语句')),
                ('no_data_config', models.JSONField(default=bk_monitor_base.domains.strategy.models._no_data_config, verbose_name='无数据配置')),
                ('target', models.JSONField(default=bk_monitor_base.domains.strategy.models._default_target, verbose_name='监控目标')),
                ('meta', models.JSONField(default=list, verbose_name='查询配置元数据')),
                ('metric_type', models.CharField(blank=True, default='', max_length=32, verbose_name='指标类型')),
                ('time_delay', models.IntegerField(default=0, verbose_name='策略等待时间')),
            ],
            options={
                'verbose_name': '监控项配置V2',
                'verbose_name_plural': '监控项配置V2',
                'db_table': 'alarm_item_v2',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NoticeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_template', models.TextField(default='', verbose_name='异常通知模板')),
                ('recovery_template', models.TextField(default='', verbose_name='恢复通知模板')),
                ('action_id', models.IntegerField(db_index=True, verbose_name='关联动作ID')),
            ],
            options={
                'verbose_name': '通知模板配置',
                'verbose_name_plural': '通知模板配置',
                'db_table': 'alarm_notice_template',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StrategyActionConfigRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.IntegerField(db_index=True, verbose_name='故障自愈的策略ID')),
                ('config_id', models.IntegerField(db_index=True, verbose_name='响应动作配置ID')),
                ('relate_type', models.CharField(choices=[('NOTICE', '通知'), ('ACTION', '处理动作')], default='NOTICE', max_length=32, verbose_name='关联类型')),
                ('signal', models.JSONField(default=list, verbose_name='触发信号')),
                ('user_groups', models.JSONField(default=list, verbose_name='用户组')),
                ('user_type', models.CharField(choices=[('main', '负责人'), ('follower', '关注人')], default='main', max_length=32, verbose_name='人员类型')),
                ('options', models.JSONField(default=dict, verbose_name='高级设置')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_user', models.CharField(blank=True, default='', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(blank=True, default='', max_length=32, verbose_name='最后修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '策略响应动作配置关联表',
                'verbose_name_plural': '策略响应动作配置关联表',
                'db_table': 'strategy_action_relation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StrategyHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.IntegerField(db_index=True, verbose_name='关联策略ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建者')),
                ('content', models.JSONField(default=dict, verbose_name='保存内容')),
                ('operate', models.CharField(choices=[('delete', '删除'), ('create', '创建'), ('update', '更新')], db_index=True, max_length=12, verbose_name='操作')),
                ('status', models.BooleanField(default=False, verbose_name='操作状态')),
                ('message', models.TextField(blank=True, default='', verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '策略配置操作历史',
                'verbose_name_plural': '策略配置操作历史',
                'db_table': 'alarm_strategy_history',
                'ordering': ['-create_time'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StrategyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='策略名称')),
                ('bk_biz_id', models.IntegerField(db_index=True, verbose_name='业务ID')),
                ('source', models.CharField(default='monitor', max_length=32, verbose_name='来源系统')),
                ('scenario', models.CharField(max_length=32, verbose_name='监控场景')),
                ('type', models.CharField(choices=[('monitor', '监控'), ('fta', '故障自愈'), ('dashboard', '仪表盘')], db_index=True, max_length=12, verbose_name='策略类型')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_invalid', models.BooleanField(default=False, verbose_name='是否失效')),
                ('invalid_type', models.CharField(blank=True, choices=[('', ''), ('invalid_related_strategy', '关联的策略已失效'), ('deleted_related_strategy', '关联的策略已删除'), ('invalid_unit', '指标和检测算法的单位类型不一致'), ('invalid_target', '监控目标全部失效'), ('invalid_metric', '监控指标不存在'), ('invalid_biz', '策略所属业务不存在'), ('invalid_dashboard_panel', '策略配置的仪表盘图表失效')], default='', max_length=32, verbose_name='失效类型')),
                ('create_user', models.CharField(default='', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(default='', max_length=32, verbose_name='最后修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('app', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='所属应用')),
                ('path', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='资源路径')),
                ('hash', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='原始配置摘要')),
                ('snippet', models.TextField(blank=True, default='', null=True, verbose_name='配置片段')),
                ('priority', models.IntegerField(null=True, verbose_name='优先级')),
                ('priority_group_key', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='优先级分组')),
            ],
            options={
                'verbose_name': '策略配置V2',
                'verbose_name_plural': '策略配置V2',
                'db_table': 'alarm_strategy_v2',
                'managed': True,
                'indexes': [models.Index(fields=['is_enabled', 'bk_biz_id', 'scenario'], name='alarm_strat_is_enab_202cd6_idx')],
            },
        ),
        migrations.CreateModel(
            name='StrategyLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=128, verbose_name='策略名称')),
                ('bk_biz_id', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='业务ID')),
                ('strategy_id', models.IntegerField(blank=True, default=0, verbose_name='策略ID')),
            ],
            options={
                'verbose_name': '策略标签',
                'verbose_name_plural': '策略标签',
                'db_table': 'alarm_strategy_label',
                'managed': True,
                'indexes': [models.Index(fields=['label_name', 'strategy_id'], name='alarm_strat_label_n_648bbd_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueryConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.IntegerField(db_index=True, verbose_name='关联策略ID')),
                ('item_id', models.IntegerField(db_index=True, verbose_name='关联监控项ID')),
                ('alias', models.CharField(max_length=12, verbose_name='别名')),
                ('data_source_label', models.CharField(max_length=32, verbose_name='数据来源标签')),
                ('data_type_label', models.CharField(max_length=32, verbose_name='数据类型标签')),
                ('metric_id', models.CharField(max_length=128, verbose_name='指标ID')),
                ('config', models.JSONField(default=dict, verbose_name='查询配置')),
            ],
            options={
                'verbose_name': '查询配置表V2',
                'verbose_name_plural': '查询配置表V2',
                'db_table': 'alarm_query_config_v2',
                'managed': True,
                'indexes': [models.Index(fields=['data_source_label', 'data_type_label'], name='alarm_query_data_so_594385_idx')],
            },
        ),
    ]
