# Generated by Django 4.2.27 on 2026-01-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="用户组名称")),
                ("bk_biz_id", models.IntegerField(blank=True, db_index=True, default=0, verbose_name="业务ID")),
                ("timezone", models.CharField(default="Asia/Shanghai", max_length=32, verbose_name="时区")),
                ("desc", models.TextField(verbose_name="说明/备注")),
                ("source", models.CharField(default="monitor", max_length=32, verbose_name="来源系统")),
                ("need_duty", models.BooleanField(default=False, verbose_name="是否需要轮值")),
                ("channels", models.JSONField(default=list, verbose_name="告警通知渠道配置")),
                ("mention_list", models.JSONField(default=list, verbose_name="告警提醒人")),
                ("mention_type", models.IntegerField(default=0, verbose_name="提醒类型")),
                ("alert_notice", models.JSONField(default=list, verbose_name="告警通知配置")),
                ("action_notice", models.JSONField(default=list, verbose_name="执行通知配置")),
                ("duty_notice", models.JSONField(default=dict, verbose_name="轮值通知配置")),
                ("webhook_action_id", models.IntegerField(default=0, verbose_name="回调套餐ID")),
                ("duty_rules", models.JSONField(default=list, verbose_name="轮值规则")),
                ("app", models.CharField(blank=True, default="", max_length=128, null=True, verbose_name="所属应用")),
                ("path", models.CharField(blank=True, default="", max_length=128, null=True, verbose_name="资源路径")),
                (
                    "hash",
                    models.CharField(blank=True, default="", max_length=64, null=True, verbose_name="原始配置摘要"),
                ),
                ("snippet", models.TextField(blank=True, default="", null=True, verbose_name="配置片段")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="最后修改人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="最后修改时间")),
            ],
            options={
                "verbose_name": "告警处理组配置",
                "verbose_name_plural": "告警处理组配置",
                "db_table": "user_group",
                "ordering": ("-update_time",),
                "managed": True,
                "indexes": [models.Index(fields=["bk_biz_id", "source"], name="user_group_bk_biz__84d1b6_idx")],
            },
        ),
    ]
