# Generated by Django 3.2.15 on 2023-07-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_databus', '0034_auto_20230411_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalinkconfig',
            name='deploy_options',
            field=models.JSONField(default=dict, verbose_name='采集下发选项'),
        ),
    ]
