# Generated by Django 3.2.15 on 2023-07-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_databus', '0035_datalinkconfig_deploy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalinkconfig',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='datalinkconfig',
            name='es_cluster_ids',
            field=models.JSONField(default=list, verbose_name='es集群ID'),
        ),
    ]
