# Generated by Django 3.2.15 on 2024-01-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_databus', '0038_create_bcsstorageclusterconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='containercollectorconfig',
            name='container_name_exclude',
            field=models.TextField(blank=True, default='', null=True, verbose_name='容器名称选择排除'),
        ),
        migrations.AddField(
            model_name='containercollectorconfig',
            name='namespaces_exclude',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='namespace选择排除'),
        ),
        migrations.AlterField(
            model_name='containercollectorconfig',
            name='container_name',
            field=models.TextField(blank=True, default='', null=True, verbose_name='容器名称'),
        ),
    ]
