# Generated by Django 3.2.15 on 2024-04-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_databus', '0039_auto_20240112_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDateFormat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, default='', max_length=32, verbose_name='修改者')),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='transfer格式')),
                ('name', models.CharField(max_length=64, verbose_name='web校验格式（python）')),
                ('description', models.CharField(max_length=64, verbose_name='传递给清洗模块的值')),
                (
                    'es_format',
                    models.CharField(
                        choices=[
                            ('epoch_millis', 'epoch_millis'),
                            ('strict_date_optional_time_nanos', 'strict_date_optional_time_nanos'),
                        ],
                        max_length=32,
                        verbose_name='ES数据格式',
                    ),
                ),
                (
                    'es_type',
                    models.CharField(
                        choices=[('date', 'date'), ('date_nanos', 'date_nanos')], max_length=32, verbose_name='ES数据类型'
                    ),
                ),
                (
                    'timestamp_unit',
                    models.CharField(
                        choices=[
                            ('s', 'seconds'),
                            ('ms', 'milliseconds'),
                            ('µs', 'microseconds'),
                            ('ns', 'nanoseconds'),
                        ],
                        max_length=32,
                        verbose_name='时间格式精度',
                    ),
                ),
            ],
            options={
                'verbose_name': '字段时间格式',
                'verbose_name_plural': '字段时间格式',
                'ordering': ('-updated_at',),
            },
        )
    ]
