# Generated by Django 3.2.15 on 2024-08-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_databus', '0040_auto_20240419_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorconfig',
            name='add_pod_annotation',
            field=models.BooleanField(default=False, verbose_name='是否自动添加pod中的annotations'),
        ),
        migrations.AddField(
            model_name='containercollectorconfig',
            name='match_annotations',
            field=models.JSONField(blank=True, null=True, verbose_name='匹配注解'),
        ),
        migrations.AlterField(
            model_name='archiveconfig',
            name='instance_type',
            field=models.CharField(choices=[('collector_config', '采集项'), ('collector_plugin', '采集插件'), ('index_set', '索引集')], default='collector_config', max_length=64, verbose_name='实例类型'),
        ),
    ]
