# Generated by Django 3.2.15 on 2024-10-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_databus', '0041_auto_20240830_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='containercollectorconfig',
            name='index',
            field=models.IntegerField(default=0, verbose_name='顺序索引'),
        ),
    ]
