# Generated by Django 3.2.15 on 2024-10-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_databus', '0041_auto_20240830_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanstash',
            name='etl_path_regexp',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='etl路径正则配置'),
        ),
    ]
