# Generated by Django 3.2.15 on 2025-01-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_databus', '0041_auto_20240830_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorconfig',
            name='sort_fields',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='排序字段'),
        ),
        migrations.AddField(
            model_name='collectorconfig',
            name='target_fields',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='目标字段'),
        ),
    ]
