# Generated by Django 3.2.15 on 2024-12-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_databus', '0041_auto_20240830_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleantemplate',
            name='alias_settings',
            field=models.JSONField(blank=True, null=True, verbose_name='别名配置'),
        ),
    ]
