# Generated by Django 4.2 on 2025-03-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_databus', '0042_cleantemplate_alias_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorplugin',
            name='is_create_storage',
            field=models.BooleanField(default=True, verbose_name='是否创建存储'),
        ),
    ]
