# Generated by Django 4.2 on 2025-05-19 08:13

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_databus", "0043_collectorplugin_is_create_storage"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogSubscriptionConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("max_rate", models.IntegerField(default=50000, verbose_name="上报速率限制")),
                ("subscription_id", models.IntegerField(verbose_name="节点管理订阅ID")),
                ("collector_config_id", models.IntegerField(verbose_name="采集配置ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
                ("config", apps.models.JsonField(verbose_name="订阅配置")),
            ],
            options={
                "verbose_name": "自定义日志订阅",
                "verbose_name_plural": "自定义日志订阅",
            },
        ),
    ]
