# Generated by Django 4.2 on 2025-08-05 09:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("log_databus", "0043_collectorplugin_is_create_storage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cleantemplate",
            name="alias_settings",
        ),
    ]
