# Generated by Django 4.2 on 2025-05-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_databus", "0043_collectorplugin_is_create_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectorconfig",
            name="bk_tenant_id",
            field=models.CharField(db_index=True, default="system", max_length=64, verbose_name="租户ID"),
        ),
    ]
