# Generated by Django 4.2.22 on 2025-09-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_databus', '0043_collectorplugin_is_create_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalinkconfig',
            name='bk_tenant_id',
            field=models.CharField(default='system', max_length=128, verbose_name='租户ID'),
        ),
    ]
