# Generated by Django 4.2.22 on 2025-11-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_databus', '0044_datalinkconfig_bk_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorconfig',
            name='is_nanos',
            field=models.BooleanField(default=False, verbose_name='采集项是否为纳秒采集'),
        ),
    ]
