# Generated by Django 4.2.22 on 2025-11-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_databus', '0045_collectorconfig_is_nanos'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorconfig',
            name='enable_v4',
            field=models.BooleanField(default=False, verbose_name='采集项是否为v4链路'),
        ),
    ]
