# Generated by Django 4.2.22 on 2026-01-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_databus", "0046_collectorconfig_enable_v4"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrokInfo",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, verbose_name="修改者")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务id")),
                ("name", models.CharField(db_index=True, max_length=128, verbose_name="规则名称")),
                ("pattern", models.TextField(verbose_name="表达式")),
                ("is_builtin", models.BooleanField(default=False, verbose_name="是否内置")),
                ("sample", models.TextField(blank=True, null=True, verbose_name="样例")),
                ("description", models.TextField(blank=True, null=True, verbose_name="描述")),
            ],
            options={
                "verbose_name": "Grok规则",
                "verbose_name_plural": "Grok规则",
                "unique_together": {("name", "bk_biz_id")},
            },
        ),
    ]
