# Generated by Django 4.2.22 on 2026-05-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_databus", "0046_collectorconfig_enable_v4"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectorconfig",
            name="storage_cluster_type",
            field=models.CharField(default="elasticsearch", max_length=32, verbose_name="存储集群类型"),
        ),
    ]
