# Generated by Django 4.2.22 on 2026-01-27

from django.db import migrations


def init_builtin_grok_patterns(apps, schema_editor):
    """
    初始化内置 Grok 规则
    """
    from pygrok import Grok

    GrokInfo = apps.get_model("log_databus", "GrokInfo")

    # 如果已经有内置规则，跳过初始化
    if GrokInfo.objects.filter(is_builtin=True).exists():
        return

    grok = Grok("")
    builtin_patterns = grok.predefined_patterns
    to_create = []
    for pattern_name, pattern in builtin_patterns.items():
        to_create.append(
            GrokInfo(
                name=pattern_name,
                pattern=pattern.regex_str,
                is_builtin=True,
                bk_biz_id=0,
                created_by="system",
                updated_by="system",
            )
        )
    GrokInfo.objects.bulk_create(to_create)


def reverse_init_builtin_grok_patterns(apps, schema_editor):
    """
    回滚操作：删除内置 Grok 规则
    """
    GrokInfo = apps.get_model("log_databus", "GrokInfo")
    GrokInfo.objects.filter(is_builtin=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("log_databus", "0047_grokinfo"),
    ]

    operations = [
        migrations.RunPython(
            init_builtin_grok_patterns,
            reverse_code=reverse_init_builtin_grok_patterns,
        ),
    ]
