# Generated by Django 4.2.22 on 2026-05-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_databus", "0048_init_builtin_grok_patterns"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectorconfig",
            name="storage_cluster_type",
            field=models.CharField(default="elasticsearch", max_length=32, verbose_name="存储集群类型"),
        ),
    ]
