# Generated by Django 4.2.22 on 2026-08-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_databus", "0049_collectorconfig_storage_cluster_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="cleanstash",
            name="clean_template_id",
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name="清洗模板ID"),
        ),
        migrations.AddField(
            model_name="cleantemplate",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="模板描述"),
        ),
        migrations.AddField(
            model_name="cleantemplate",
            name="snapshot",
            field=models.JSONField(blank=True, default=None, null=True, verbose_name="模板草稿快照"),
        ),
        migrations.AddField(
            model_name="cleantemplate",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "草稿"), ("PUBLISHED", "已发布")],
                default="PUBLISHED",
                max_length=32,
                verbose_name="模板状态",
            ),
        ),
        migrations.AddField(
            model_name="collectorconfig",
            name="clean_template_id",
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name="清洗模板ID"),
        ),
    ]
