from typing import Any

host_task_result: dict[str, Any] = {
    "task_id": 1,
    "record_id": 1,
    "instance_id": "host|instance|host|1",
    "create_time": "2025-12-03 22:09:26",
    "pipeline_id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "instance_info": {
        "host": {
            "bk_biz_id": 1,
            "bk_host_id": 1,
            "bk_biz_name": "蓝鲸",
            "bk_cloud_id": 0,
            "bk_host_name": "VM-test-host",
            "bk_cloud_name": "直连区域",
            "bk_host_innerip": "127.0.0.1",
            "bk_supplier_account": "0",
        },
        "service": {},
    },
    "start_time": "2025-12-03 22:09:28",
    "finish_time": "2025-12-03 22:09:48",
    "status": "SUCCESS",
}

host_task_result_detail: dict[str, Any] = {
    "task_id": 1,
    "record_id": 1,
    "instance_id": "host|instance|host|1",
    "create_time": "2025-12-03 18:48:44",
    "pipeline_id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "instance_info": {
        "host": {
            "bk_cpu": 32,
            "bk_mem": 63046,
            "bk_state": "运营中[需告警]",
            "operator": "test_user",
            "bk_biz_id": 1,
            "bk_os_bit": "64-bit",
            "dept_name": "",
            "relations": [{"bk_set_id": 1, "bk_set_name": "", "bk_module_id": 1, "bk_module_name": ""}],
            "bk_host_id": 1,
            "bk_os_name": "linux centos",
            "bk_os_type": "1",
            "bk_agent_id": "00000000000000000000000000000000",
            "bk_biz_name": "蓝鲸",
            "bk_cloud_id": 0,
            "bk_isp_name": None,
            "idc_city_id": "",
            "bk_host_name": "VM-test-host",
            "bk_addressing": "static",
            "bk_cloud_name": "直连区域",
            "bk_cpu_module": "AMD EPYC 9754 128-Core Processor",
            "bk_os_version": "7.9",
            "bk_state_name": None,
            "bk_bak_operator": "test_user2",
            "bk_host_innerip": "127.0.0.1",
            "bk_host_outerip": "",
            "bk_province_name": None,
            "bk_cpu_architecture": "x86",
            "bk_supplier_account": "0",
        },
        "meta": {"GSE_VERSION": "V2"},
        "scope": [{"ip": "127.0.0.1", "bk_cloud_id": 0, "bk_supplier_id": 0}],
        "service": None,
    },
    "start_time": "2025-12-03 18:48:46",
    "finish_time": "2025-12-03 18:49:32",
    "steps": [
        {
            "id": "lgtt",
            "type": "PLUGIN",
            "index": 0,
            "action": "INSTALL",
            "node_name": "[lgtt] 部署插件",
            "extra_info": {},
            "pipeline_id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "status": "SUCCESS",
            "start_time": "2025-12-03 18:48:46",
            "finish_time": "2025-12-03 18:49:07",
            "target_hosts": [
                {
                    "node_name": "[lgtt] 部署插件 0:127.0.0.1",
                    "pipeline_id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                    "status": "SUCCESS",
                    "start_time": "2025-12-03 18:48:46",
                    "finish_time": "2025-12-03 18:49:07",
                    "sub_steps": [
                        {
                            "index": 0,
                            "node_name": "初始化进程状态",
                            "step_code": "init_process_status",
                            "pipeline_id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                            "log": "[2025-12-03 18:48:46 INFO] 开始 初始化进程状态.\n[2025-12-03 18:48:46 INFO] 初始化进程状态 成功",
                            "ex_data": None,
                            "status": "SUCCESS",
                            "start_time": "2025-12-03 18:48:46",
                            "finish_time": "2025-12-03 18:48:46",
                        },
                        {
                            "index": 1,
                            "node_name": "更新插件部署状态为UNKNOWN",
                            "step_code": "update_host_process_status",
                            "pipeline_id": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
                            "log": "[2025-12-03 18:48:47 INFO] 开始 更新插件部署状态为UNKNOWN.\n[2025-12-03 18:48:47 INFO] 更新插件部署状态为UNKNOWN 成功",
                            "ex_data": None,
                            "status": "SUCCESS",
                            "start_time": "2025-12-03 18:48:47",
                            "finish_time": "2025-12-03 18:48:47",
                        },
                        {
                            "index": 2,
                            "node_name": "下发安装包",
                            "step_code": "transfer_package",
                            "pipeline_id": "cccccccccccccccccccccccccccccccc",
                            "log": '[2025-12-03 18:48:47 INFO] 开始 下发安装包.\n[2025-12-03 18:48:47 INFO] 从 [第三方文件源文件-节点管理[biz:1]蓝鲸制品库文件源] 下发文件 [blueking/bknodeman/data/bkee/public/bknodeman/download/linux/x86_64/lgtt-1.2.tgz] 到目标机器路径 [/tmp]\n作业任务ID为 [1]，点击跳转到 <a href="https://job.example.com/api_execute/1" target="_blank">[作业平台]</a>\n[2025-12-03 18:48:53 INFO] 下发安装包 成功',
                            "ex_data": None,
                            "status": "SUCCESS",
                            "start_time": "2025-12-03 18:48:47",
                            "finish_time": "2025-12-03 18:48:53",
                            "inputs": {
                                "instance_info": {
                                    "host": {
                                        "bk_cpu": 32,
                                        "bk_mem": 63046,
                                        "bk_state": "运营中[需告警]",
                                        "operator": "test_user",
                                        "bk_biz_id": 1,
                                        "bk_os_bit": "64-bit",
                                        "dept_name": "",
                                        "relations": [
                                            {
                                                "bk_set_id": 1,
                                                "bk_set_name": "",
                                                "bk_module_id": 1,
                                                "bk_module_name": "",
                                            }
                                        ],
                                        "bk_host_id": 1,
                                        "bk_os_name": "linux centos",
                                        "bk_os_type": "1",
                                        "bk_agent_id": "00000000000000000000000000000000",
                                        "bk_biz_name": "蓝鲸",
                                        "bk_cloud_id": 0,
                                        "bk_isp_name": None,
                                        "idc_city_id": "",
                                        "bk_host_name": "VM-test-host",
                                        "bk_addressing": "static",
                                        "bk_cloud_name": "直连区域",
                                        "bk_cpu_module": "AMD EPYC 9754 128-Core Processor",
                                        "bk_os_version": "7.9",
                                        "bk_state_name": None,
                                        "bk_bak_operator": "test_user2",
                                        "bk_host_innerip": "127.0.0.1",
                                        "bk_host_outerip": "",
                                        "bk_province_name": None,
                                        "bk_cpu_architecture": "x86",
                                        "bk_supplier_account": "0",
                                    },
                                    "meta": {"GSE_VERSION": "V2"},
                                    "scope": [{"ip": "127.0.0.1", "bk_cloud_id": 0, "bk_supplier_id": 0}],
                                    "service": None,
                                }
                            },
                        },
                        {
                            "index": 3,
                            "node_name": "安装插件包",
                            "step_code": "install_package",
                            "pipeline_id": "dddddddddddddddddddddddddddddddd",
                            "log": '[2025-12-03 18:48:53 INFO] 开始 安装插件包.\n[2025-12-03 18:48:54 INFO] 快速执行脚本 update_binary\n作业任务ID为 [1]，点击跳转到 <a href="https://job.example.com/api_execute/1" target="_blank">[作业平台]</a>\n[2025-12-03 18:48:59 INFO] 安装插件包 成功',
                            "ex_data": None,
                            "status": "SUCCESS",
                            "start_time": "2025-12-03 18:48:53",
                            "finish_time": "2025-12-03 18:48:59",
                        },
                        {
                            "index": 4,
                            "node_name": "分配可用端口",
                            "step_code": "job_allocate_port",
                            "pipeline_id": "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
                            "log": "[2025-12-03 18:49:00 INFO] 开始 分配可用端口.\n[2025-12-03 18:49:00 INFO] 分配可用端口 成功",
                            "ex_data": None,
                            "status": "SUCCESS",
                            "start_time": "2025-12-03 18:49:00",
                            "finish_time": "2025-12-03 18:49:00",
                        },
                        {
                            "index": 5,
                            "node_name": "渲染下发配置",
                            "step_code": "render_and_push_config",
                            "pipeline_id": "ffffffffffffffffffffffffffffffff",
                            "log": '[2025-12-03 18:49:00 INFO] 开始 渲染下发配置.\n[2025-12-03 18:49:01 INFO] 下发配置文件 [env.yaml] 到目标机器路径 [/usr/local/gse2_opbk/external_plugins/sub_1_host_1/lgtt/etc]，若下发失败，请检查作业平台所部署的机器是否已安装AGENT\n作业任务ID为 [1]，点击跳转到 <a href="https://job.example.com/api_execute/1" target="_blank">[作业平台]</a>\n[2025-12-03 18:49:06 INFO] 渲染下发配置 成功',
                            "ex_data": None,
                            "status": "SUCCESS",
                            "start_time": "2025-12-03 18:49:00",
                            "finish_time": "2025-12-03 18:49:06",
                        },
                        {
                            "index": 6,
                            "node_name": "重启进程",
                            "step_code": "gse_operate_proc",
                            "pipeline_id": "11111111111111111111111111111111",
                            "log": "[2025-12-03 18:49:07 INFO] 开始 重启进程.\n[2025-12-03 18:49:07 INFO] 重启进程 成功",
                            "ex_data": None,
                            "status": "SUCCESS",
                            "start_time": "2025-12-03 18:49:07",
                            "finish_time": "2025-12-03 18:49:07",
                        },
                        {
                            "index": 7,
                            "node_name": "更新插件部署状态为RUNNING",
                            "step_code": "update_host_process_status",
                            "pipeline_id": "22222222222222222222222222222222",
                            "log": "[2025-12-03 18:49:07 INFO] 开始 更新插件部署状态为RUNNING.\n[2025-12-03 18:49:07 INFO] 更新插件部署状态为RUNNING 成功",
                            "ex_data": None,
                            "status": "SUCCESS",
                            "start_time": "2025-12-03 18:49:07",
                            "finish_time": "2025-12-03 18:49:07",
                        },
                        {
                            "index": 8,
                            "node_name": "重置重试次数",
                            "step_code": "reset_retry_times",
                            "pipeline_id": "33333333333333333333333333333333",
                            "log": "[2025-12-03 18:49:07 INFO] 开始 重置重试次数.\n[2025-12-03 18:49:07 INFO] 重置重试次数 成功",
                            "ex_data": None,
                            "status": "SUCCESS",
                            "start_time": "2025-12-03 18:49:07",
                            "finish_time": "2025-12-03 18:49:07",
                        },
                    ],
                }
            ],
        },
        {
            "id": "bkmonitorbeat",
            "type": "PLUGIN",
            "index": 1,
            "action": "INSTALL",
            "node_name": "[bkmonitorbeat] 下发插件配置",
            "extra_info": {},
            "pipeline_id": "44444444444444444444444444444444",
            "status": "SUCCESS",
            "start_time": "2025-12-03 18:49:08",
            "finish_time": "2025-12-03 18:49:32",
            "target_hosts": [
                {
                    "node_name": "[bkmonitorbeat] 下发插件配置 0:127.0.0.1",
                    "pipeline_id": "44444444444444444444444444444444",
                    "status": "SUCCESS",
                    "start_time": "2025-12-03 18:49:08",
                    "finish_time": "2025-12-03 18:49:32",
                    "sub_steps": [
                        {
                            "index": 0,
                            "node_name": "更新插件部署状态为UNKNOWN",
                            "step_code": "update_host_process_status",
                            "pipeline_id": "44444444444444444444444444444444",
                            "log": "[2025-12-03 18:49:08 INFO] 开始 更新插件部署状态为UNKNOWN.\n[2025-12-03 18:49:08 INFO] 更新插件部署状态为UNKNOWN 成功",
                            "ex_data": None,
                            "status": "SUCCESS",
                            "start_time": "2025-12-03 18:49:08",
                            "finish_time": "2025-12-03 18:49:08",
                        },
                        {
                            "index": 1,
                            "node_name": "渲染下发配置",
                            "step_code": "render_and_push_config",
                            "pipeline_id": "55555555555555555555555555555555",
                            "log": '[2025-12-03 18:49:08 INFO] 开始 渲染下发配置.\n[2025-12-03 18:49:08 INFO] 下发配置文件 [bkmonitorbeat_script_sub_1_host_1.conf] 到目标机器路径 [/usr/local/gse2_opbk/plugins/etc/bkmonitorbeat]，若下发失败，请检查作业平台所部署的机器是否已安装AGENT\n作业任务ID为 [1]，点击跳转到 <a href="https://job.example.com/api_execute/1" target="_blank">[作业平台]</a>\n[2025-12-03 18:49:14 INFO] 渲染下发配置 成功',
                            "ex_data": None,
                            "status": "SUCCESS",
                            "start_time": "2025-12-03 18:49:08",
                            "finish_time": "2025-12-03 18:49:14",
                        },
                        {
                            "index": 2,
                            "node_name": "重载进程",
                            "step_code": "gse_operate_proc",
                            "pipeline_id": "66666666666666666666666666666666",
                            "log": '[2025-12-03 18:49:14 INFO] 开始 重载进程.\n[2025-12-03 18:49:15 INFO] {\n  "meta": {\n    "namespace": "nodeman",\n    "name": "bkmonitorbeat"\n  },\n  "op_type": 8,\n  "nodeman_spec": {\n    "process_status_id": 1,\n    "subscription_instance_id": 1\n  },\n  "hosts": [\n    {\n      "ip": "127.0.0.1",\n      "bk_agent_id": "00000000000000000000000000000000",\n      "bk_cloud_id": 0\n    }\n  ],\n  "spec": {\n    "identity": {\n      "index_key": "",\n      "proc_name": "bkmonitorbeat",\n      "setup_path": "/usr/local/gse2_opbk/plugins/bin",\n      "pid_path": "/var/run/gse2_opbk/bkmonitorbeat.pid",\n      "user": "root"\n    },\n    "control": {\n      "start_cmd": "./start.sh bkmonitorbeat",\n      "stop_cmd": "./stop.sh bkmonitorbeat",\n      "restart_cmd": "./restart.sh bkmonitorbeat",\n      "reload_cmd": "./reload.sh bkmonitorbeat",\n      "kill_cmd": "",\n      "version_cmd": "./bkmonitorbeat -v",\n      "health_cmd": ""\n    },\n    "resource": {\n      "cpu": 10,\n      "mem": 10\n    },\n    "alive_monitor_policy": {\n      "auto_type": 1,\n      "start_check_secs": 9\n    }\n  }\n}\n[2025-12-03 18:49:15 INFO] GSE TASK ID: [O2:20251203104915:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA:1]\n[2025-12-03 18:49:26 INFO] 重载进程 成功',
                            "ex_data": None,
                            "status": "SUCCESS",
                            "start_time": "2025-12-03 18:49:14",
                            "finish_time": "2025-12-03 18:49:26",
                            "inputs": {
                                "instance_info": {
                                    "host": {
                                        "bk_cpu": 32,
                                        "bk_mem": 63046,
                                        "bk_state": "运营中[需告警]",
                                        "operator": "test_user",
                                        "bk_biz_id": 1,
                                        "bk_os_bit": "64-bit",
                                        "dept_name": "",
                                        "relations": [
                                            {
                                                "bk_set_id": 1,
                                                "bk_set_name": "",
                                                "bk_module_id": 1,
                                                "bk_module_name": "",
                                            }
                                        ],
                                        "bk_host_id": 1,
                                        "bk_os_name": "linux centos",
                                        "bk_os_type": "1",
                                        "bk_agent_id": "00000000000000000000000000000000",
                                        "bk_biz_name": "蓝鲸",
                                        "bk_cloud_id": 0,
                                        "bk_isp_name": None,
                                        "idc_city_id": "",
                                        "bk_host_name": "VM-test-host",
                                        "bk_addressing": "static",
                                        "bk_cloud_name": "直连区域",
                                        "bk_cpu_module": "AMD EPYC 9754 128-Core Processor",
                                        "bk_os_version": "7.9",
                                        "bk_state_name": None,
                                        "bk_bak_operator": "test_user2",
                                        "bk_host_innerip": "127.0.0.1",
                                        "bk_host_outerip": "",
                                        "bk_province_name": None,
                                        "bk_cpu_architecture": "x86",
                                        "bk_supplier_account": "0",
                                    },
                                    "meta": {"GSE_VERSION": "V2"},
                                    "scope": [{"ip": "127.0.0.1", "bk_cloud_id": 0, "bk_supplier_id": 0}],
                                    "service": None,
                                }
                            },
                        },
                        {
                            "index": 3,
                            "node_name": "托管进程",
                            "step_code": "gse_operate_proc",
                            "pipeline_id": "77777777777777777777777777777777",
                            "log": '[2025-12-03 18:49:26 INFO] 开始 托管进程.\n[2025-12-03 18:49:26 INFO] {\n  "meta": {\n    "namespace": "nodeman",\n    "name": "bkmonitorbeat"\n  },\n  "op_type": 3,\n  "nodeman_spec": {\n    "process_status_id": 1,\n    "subscription_instance_id": 1\n  },\n  "hosts": [\n    {\n      "ip": "127.0.0.1",\n      "bk_agent_id": "00000000000000000000000000000000",\n      "bk_cloud_id": 0\n    }\n  ],\n  "spec": {\n    "identity": {\n      "index_key": "",\n      "proc_name": "bkmonitorbeat",\n      "setup_path": "/usr/local/gse2_opbk/plugins/bin",\n      "pid_path": "/var/run/gse2_opbk/bkmonitorbeat.pid",\n      "user": "root"\n    },\n    "control": {\n      "start_cmd": "./start.sh bkmonitorbeat",\n      "stop_cmd": "./stop.sh bkmonitorbeat",\n      "restart_cmd": "./restart.sh bkmonitorbeat",\n      "reload_cmd": "./reload.sh bkmonitorbeat",\n      "kill_cmd": "",\n      "version_cmd": "./bkmonitorbeat -v",\n      "health_cmd": ""\n    },\n    "resource": {\n      "cpu": 10,\n      "mem": 10\n    },\n    "alive_monitor_policy": {\n      "auto_type": 1,\n      "start_check_secs": 9\n    }\n  }\n}\n[2025-12-03 18:49:26 INFO] GSE TASK ID: [O2:20251203104926:BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB:1]\n[2025-12-03 18:49:32 INFO] 托管进程 成功',
                            "ex_data": None,
                            "status": "SUCCESS",
                            "start_time": "2025-12-03 18:49:26",
                            "finish_time": "2025-12-03 18:49:32",
                        },
                        {
                            "index": 4,
                            "node_name": "更新插件部署状态为RUNNING",
                            "step_code": "update_host_process_status",
                            "pipeline_id": "88888888888888888888888888888888",
                            "log": "[2025-12-03 18:49:32 INFO] 开始 更新插件部署状态为RUNNING.\n[2025-12-03 18:49:32 INFO] 更新插件部署状态为RUNNING 成功",
                            "ex_data": None,
                            "status": "SUCCESS",
                            "start_time": "2025-12-03 18:49:32",
                            "finish_time": "2025-12-03 18:49:32",
                        },
                        {
                            "index": 5,
                            "node_name": "重置重试次数",
                            "step_code": "reset_retry_times",
                            "pipeline_id": "99999999999999999999999999999999",
                            "log": "[2025-12-03 18:49:32 INFO] 开始 重置重试次数.\n[2025-12-03 18:49:32 INFO] 重置重试次数 成功",
                            "ex_data": None,
                            "status": "SUCCESS",
                            "start_time": "2025-12-03 18:49:32",
                            "finish_time": "2025-12-03 18:49:32",
                        },
                    ],
                }
            ],
        },
    ],
    "status": "SUCCESS",
}


service_task_result: dict[str, Any] = {
    "task_id": 1,
    "record_id": 1,
    "instance_id": "service|instance|service|1",
    "create_time": "2023-02-08 10:42:36",
    "pipeline_id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "instance_info": {
        "host": {
            "bk_biz_id": 1,
            "bk_host_id": 1,
            "bk_biz_name": "蓝鲸",
            "bk_cloud_id": 0,
            "bk_host_name": "VM-test-host",
            "bk_cloud_name": "直连区域",
            "bk_host_innerip": "127.0.0.1",
            "bk_host_innerip_v6": "",
            "bk_supplier_account": "0",
        },
        "service": {"id": 1, "name": "127.0.0.1_influxd_5260", "bk_host_id": 1, "bk_module_id": 1},
    },
    "start_time": "2023-02-08 10:42:36",
    "finish_time": "2023-02-08 10:43:13",
    "status": "SUCCESS",
}

service_task_result_detail: dict[str, Any] = {
    "task_id": 1,
    "record_id": 1,
    "instance_id": "service|instance|service|1",
    "create_time": "2023-02-08 10:42:36",
    "pipeline_id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "instance_info": {
        "host": {
            "bk_state": "运营中[需告警]",
            "operator": "test_user",
            "bk_biz_id": 1,
            "bk_os_bit": "64-bit",
            "bk_host_id": 1,
            "bk_os_name": "linux centos",
            "bk_os_type": "1",
            "bk_agent_id": "",
            "bk_biz_name": "蓝鲸",
            "bk_cloud_id": 0,
            "bk_isp_name": None,
            "bk_host_name": "VM-test-host",
            "bk_addressing": "static",
            "bk_cloud_name": "直连区域",
            "bk_cpu_module": "Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz",
            "bk_os_version": "7.9",
            "bk_state_name": None,
            "bk_bak_operator": "test_user2",
            "bk_host_innerip": "127.0.0.1",
            "bk_host_outerip": "",
            "bk_province_name": None,
            "bk_host_innerip_v6": "",
            "bk_host_outerip_v6": "",
            "bk_supplier_account": "0",
        },
        "scope": [{"bk_obj_id": "module", "bk_inst_id": 1}],
        "process": {
            "influxd": {
                "user": "",
                "timeout": None,
                "pid_file": "",
                "priority": None,
                "proc_num": None,
                "stop_cmd": "",
                "bind_info": [
                    {"ip": "127.0.0.1", "port": "5260", "enable": True, "protocol": "1", "template_row_id": 1}
                ],
                "bk_biz_id": 1,
                "last_time": "2023-02-08T02:41:40.261Z",
                "start_cmd": "",
                "work_path": "",
                "auto_start": False,
                "reload_cmd": "",
                "create_time": "2023-02-08T02:41:40.261Z",
                "description": "",
                "restart_cmd": "",
                "bk_func_name": "influxd",
                "bk_process_id": 1,
                "face_stop_cmd": "",
                "bk_process_name": "influxd",
                "bk_start_check_secs": None,
                "bk_supplier_account": "0",
                "service_instance_id": 1,
                "bk_start_param_regex": "",
            }
        },
        "service": {
            "id": 1,
            "name": "127.0.0.1_influxd_5260",
            "labels": None,
            "creator": "test_user",
            "modifier": "test_user",
            "bk_biz_id": 1,
            "last_time": "2023-02-08T02:41:40.142Z",
            "bk_host_id": 1,
            "create_time": "2023-02-08T02:41:40.142Z",
            "bk_module_id": 1,
            "bk_supplier_account": "0",
            "service_template_id": 1,
        },
    },
    "start_time": "2023-02-08 10:42:36",
    "finish_time": "2023-02-08 10:43:13",
    "steps": [
        {
            "id": "bkmonitorbeat",
            "type": "PLUGIN",
            "action": "INSTALL",
            "node_name": "[bkmonitorbeat] 下发插件配置",
            "extra_info": {},
            "pipeline_id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "status": "PENDING",
            "start_time": None,
            "finish_time": None,
            "target_hosts": [
                {
                    "node_name": "[bkmonitorbeat] 下发插件配置 0:127.0.0.1",
                    "pipeline_id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                    "status": "PENDING",
                    "start_time": None,
                    "finish_time": None,
                    "sub_steps": [
                        {
                            "index": 0,
                            "node_name": "初始化进程状态",
                            "step_code": "init_process_status",
                            "pipeline_id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                            "log": "",
                            "ex_data": None,
                            "status": "PENDING",
                            "start_time": None,
                            "finish_time": None,
                        },
                        {
                            "index": 1,
                            "node_name": "更新插件部署状态为UNKNOWN",
                            "step_code": "update_host_process_status",
                            "pipeline_id": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
                            "log": "",
                            "ex_data": None,
                            "status": "PENDING",
                            "start_time": None,
                            "finish_time": None,
                        },
                        {
                            "index": 2,
                            "node_name": "渲染下发配置",
                            "step_code": "render_and_push_config",
                            "pipeline_id": "cccccccccccccccccccccccccccccccc",
                            "log": "",
                            "ex_data": None,
                            "status": "PENDING",
                            "start_time": None,
                            "finish_time": None,
                            "inputs": {
                                "instance_info": {
                                    "host": {
                                        "bk_state": "运营中[需告警]",
                                        "operator": "test_user",
                                        "bk_biz_id": 1,
                                        "bk_os_bit": "64-bit",
                                        "bk_host_id": 1,
                                        "bk_os_name": "linux centos",
                                        "bk_os_type": "1",
                                        "bk_agent_id": "",
                                        "bk_biz_name": "蓝鲸",
                                        "bk_cloud_id": 0,
                                        "bk_isp_name": None,
                                        "bk_host_name": "VM-test-host",
                                        "bk_addressing": "static",
                                        "bk_cloud_name": "直连区域",
                                        "bk_cpu_module": "Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz",
                                        "bk_os_version": "7.9",
                                        "bk_state_name": None,
                                        "bk_bak_operator": "test_user2",
                                        "bk_host_innerip": "127.0.0.1",
                                        "bk_host_outerip": "",
                                        "bk_province_name": None,
                                        "bk_host_innerip_v6": "",
                                        "bk_host_outerip_v6": "",
                                        "bk_supplier_account": "0",
                                    },
                                    "scope": [{"bk_obj_id": "module", "bk_inst_id": 1}],
                                    "process": {
                                        "influxd": {
                                            "user": "",
                                            "timeout": None,
                                            "pid_file": "",
                                            "priority": None,
                                            "proc_num": None,
                                            "stop_cmd": "",
                                            "bind_info": [
                                                {
                                                    "ip": "127.0.0.1",
                                                    "port": "5260",
                                                    "enable": True,
                                                    "protocol": "1",
                                                    "template_row_id": 1,
                                                }
                                            ],
                                            "bk_biz_id": 1,
                                            "last_time": "2023-02-08T02:41:40.261Z",
                                            "start_cmd": "",
                                            "work_path": "",
                                            "auto_start": False,
                                            "reload_cmd": "",
                                            "create_time": "2023-02-08T02:41:40.261Z",
                                            "description": "",
                                            "restart_cmd": "",
                                            "bk_func_name": "influxd",
                                            "bk_process_id": 1,
                                            "face_stop_cmd": "",
                                            "bk_process_name": "influxd",
                                            "bk_start_check_secs": None,
                                            "bk_supplier_account": "0",
                                            "service_instance_id": 1,
                                            "bk_start_param_regex": "",
                                        }
                                    },
                                    "service": {
                                        "id": 1,
                                        "name": "127.0.0.1_influxd_5260",
                                        "labels": None,
                                        "creator": "test_user",
                                        "modifier": "test_user",
                                        "bk_biz_id": 1,
                                        "last_time": "2023-02-08T02:41:40.142Z",
                                        "bk_host_id": 1,
                                        "create_time": "2023-02-08T02:41:40.142Z",
                                        "bk_module_id": 1,
                                        "bk_supplier_account": "0",
                                        "service_template_id": 1,
                                    },
                                }
                            },
                        },
                        {
                            "index": 3,
                            "node_name": "托管进程",
                            "step_code": "gse_operate_proc",
                            "pipeline_id": "dddddddddddddddddddddddddddddddd",
                            "log": "",
                            "ex_data": None,
                            "status": "PENDING",
                            "start_time": None,
                            "finish_time": None,
                        },
                        {
                            "index": 4,
                            "node_name": "重载进程",
                            "step_code": "gse_operate_proc",
                            "pipeline_id": "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
                            "log": "",
                            "ex_data": None,
                            "status": "PENDING",
                            "start_time": None,
                            "finish_time": None,
                        },
                        {
                            "index": 5,
                            "node_name": "更新插件部署状态为RUNNING",
                            "step_code": "update_host_process_status",
                            "pipeline_id": "ffffffffffffffffffffffffffffffff",
                            "log": "",
                            "ex_data": None,
                            "status": "PENDING",
                            "start_time": None,
                            "finish_time": None,
                        },
                        {
                            "index": 6,
                            "node_name": "重置重试次数",
                            "step_code": "reset_retry_times",
                            "pipeline_id": "00000000000000000000000000000000",
                            "log": "",
                            "ex_data": None,
                            "status": "PENDING",
                            "start_time": None,
                            "finish_time": None,
                        },
                    ],
                }
            ],
        }
    ],
    "status": "SUCCESS",
}
