# Generated by Django 3.2.15 on 2023-08-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_clustering', '0020_auto_20230809_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringconfig',
            name='log_count_aggregation_flow',
            field=models.JSONField(blank=True, null=True, verbose_name='日志数量聚合flow配置'),
        ),
        migrations.AddField(
            model_name='clusteringconfig',
            name='log_count_aggregation_flow_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='日志数量聚合flow_id'),
        ),
        migrations.AddField(
            model_name='clusteringconfig',
            name='new_cls_index_set_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='新聚类类索引集id'),
        ),
    ]
