# Generated by Django 3.2.15 on 2023-08-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_clustering', '0021_auto_20230817_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringconfig',
            name='depth',
            field=models.IntegerField(default=5, verbose_name='搜索树深度'),
        ),
        migrations.AddField(
            model_name='clusteringconfig',
            name='max_child',
            field=models.IntegerField(default=100, verbose_name='搜索树最大子节点数'),
        ),
    ]
