# Generated by Django 3.2.15 on 2023-09-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_clustering', '0022_auto_20230831_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringconfig',
            name='related_space_pre_bk_biz_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='关联空间业务id之前的业务id'),
        ),
    ]
