# Generated by Django 3.2.15 on 2023-10-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_clustering', '0023_clusteringconfig_related_space_pre_bk_biz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringconfig',
            name='clustered_rt',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='聚类结果表'),
        ),
    ]
