# Generated by Django 3.2.23 on 2023-11-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_clustering', '0024_clusteringconfig_clustered_rt'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiopssignatureandpattern',
            name='owners',
            field=models.JSONField(default=list, null=True, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='aiopssignatureandpattern',
            name='remark',
            field=models.JSONField(default=list, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='aiopssignatureandpattern',
            name='label',
            field=models.TextField(default='', verbose_name='标签'),
        ),
    ]
