# Generated by Django 3.2.23 on 2023-11-08 08:24

from django.db import migrations, models


def insert_label_to_remark(apps, schema_editor):
    signature_and_pattern = apps.get_model('log_clustering', 'AiopsSignatureAndPattern')
    # 合并 label到 remark中
    for s in signature_and_pattern.objects.all():
        if not s.label:
            continue
        label = {"username": "", "create_time": 0, "remark": s.label}
        s.remark = [label]
        s.save()


class Migration(migrations.Migration):
    dependencies = [
        ('log_clustering', '0025_auto_20231103_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiopssignatureandpattern',
            name='owners',
            field=models.JSONField(blank=True, default=[], null=True, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='aiopssignatureandpattern',
            name='remark',
            field=models.JSONField(blank=True, default=[], null=True, verbose_name='备注信息'),
        ),
        migrations.RunPython(insert_label_to_remark),
    ]
