# Generated by Django 3.2.15 on 2024-07-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_clustering', '0028_clustering_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturestrategysettings',
            name='alarm_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='告警级别'),
        ),
        migrations.AddField(
            model_name='signaturestrategysettings',
            name='interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='告警间隔'),
        ),
        migrations.AddField(
            model_name='signaturestrategysettings',
            name='sensitivity',
            field=models.IntegerField(blank=True, null=True, verbose_name='敏感度'),
        ),
        migrations.AddField(
            model_name='signaturestrategysettings',
            name='threshold',
            field=models.IntegerField(blank=True, null=True, verbose_name='告警阈值'),
        ),
        migrations.AddField(
            model_name='signaturestrategysettings',
            name='user_groups',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='告警组'),
        ),
    ]
