# Generated by Django 3.2.15 on 2024-08-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_clustering', '0028_clustering_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringconfig',
            name='signature_pattern_rt',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Pattern 结果表'),
        ),
        migrations.AddField(
            model_name='clusteringconfig',
            name='task_details',
            field=models.JSONField(default=dict, verbose_name='任务详情'),
        ),
        migrations.AlterField(
            model_name='aiopssignatureandpattern',
            name='owners',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='aiopssignatureandpattern',
            name='remark',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='clusteringconfig',
            name='group_fields',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='分组字段'),
        ),
        migrations.AlterField(
            model_name='clusteringremark',
            name='owners',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='clusteringremark',
            name='remark',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='clusteringsubscription',
            name='pattern_level',
            field=models.CharField(choices=[('05', 'LEVEL_05')], default='05', max_length=64, verbose_name='敏感度'),
        ),
    ]
