# Generated by Django 3.2.15 on 2024-08-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_clustering', '0030_auto_20240826_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusteringconfig',
            name='new_cls_strategy_output',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='日志新类告警输出结果表'),
        ),
        migrations.AlterField(
            model_name='clusteringconfig',
            name='normal_strategy_output',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='日志数量告警输出结果表'),
        ),
    ]
