# Generated by Django 3.2.15 on 2024-08-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_clustering', '0031_auto_20240826_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringconfig',
            name='access_finished',
            field=models.BooleanField(default=True, verbose_name='是否接入完成'),
        ),
    ]
