# Generated by Django 3.2.15 on 2024-09-12 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('log_clustering', '0032_clusteringconfig_access_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusteringconfig',
            name='task_details',
        ),
    ]
