# Generated by Django 3.2.15 on 2024-09-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_clustering', '0033_remove_clusteringconfig_task_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringconfig',
            name='task_details',
            field=models.JSONField(default=dict, verbose_name='任务详情'),
        ),
    ]
