# Generated by Django 3.2.15 on 2024-10-18 06:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('log_clustering', '0033_auto_20241016_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regextemplate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='regextemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='regextemplate',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='regextemplate',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='regextemplate',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='regextemplate',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='regextemplate',
            name='updated_by',
        ),
    ]
