# Generated by Django 4.2 on 2025-03-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_clustering', '0034_auto_20241018_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringremark',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='clusteringremark',
            name='strategy_id',
            field=models.IntegerField(default=0, verbose_name='策略id'),
        ),
    ]
