# Generated by Django 4.2 on 2025-04-02 08:52

from django.db import migrations, models

import apps.utils.local


class Migration(migrations.Migration):
    dependencies = [
        ('log_clustering', '0035_clusteringremark_strategy_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringremark',
            name='source_app_code',
            field=models.CharField(
                blank=True, default=apps.utils.local.get_external_app_code, max_length=32, verbose_name='来源系统'
            ),
        ),
    ]
