# Generated by Django 3.2.15 on 2024-10-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_clustering', '0035_clusteringtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringconfig',
            name='rule_type',
            field=models.CharField(
                choices=[('customize', '自定义'), ('template', '模板')],
                default='customize',
                max_length=64,
                verbose_name='规则类型',
            ),
        ),
        migrations.AddField(
            model_name='clusteringconfig',
            name='template_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='模板id'),
        ),
    ]
