# Generated by Django 4.2 on 2025-04-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_clustering', '0036_clusteringremark_source_app_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringremark',
            name='notice_group_id',
            field=models.IntegerField(default=0, verbose_name='告警组id'),
        ),
    ]
