# Generated by Django 3.2.15 on 2024-10-11 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('log_clustering', '0036_auto_20241011_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clusteringconfig',
            old_name='template_id',
            new_name='regex_template_id',
        ),
    ]
