# Generated by Django 4.2 on 2025-08-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_clustering", "0037_clusteringremark_notice_group_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiopssignatureandpattern",
            name="origin_log",
            field=models.TextField(default="", verbose_name="原始日志"),
        ),
    ]
