# Generated by Django 3.2.15 on 2024-10-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_clustering', '0037_rename_template_id_clusteringconfig_regex_template_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusteringtemplate',
            name='space_uid',
            field=models.CharField(db_index=True, max_length=256, verbose_name='空间唯一标识'),
        ),
        migrations.AlterField(
            model_name='clusteringtemplate',
            name='template_name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='模板名称'),
        ),
    ]
