# Generated by Django 3.2.15 on 2024-10-14 04:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('log_clustering', '0038_auto_20241011_1815'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClusteringTemplate',
            new_name='RegexTemplate',
        ),
    ]
