# Generated by Django 4.2.22 on 2025-11-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_clustering", "0038_aiopssignatureandpattern_origin_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusteringconfig",
            name="predict_cluster",
            field=models.CharField(blank=True, default="", max_length=64, null=True, verbose_name="预测集群名称"),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="st_list",
            field=models.CharField(default="0.875", max_length=128, verbose_name="相似度阈值"),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="use_mini_link",
            field=models.BooleanField(default=False, verbose_name="是否启用小型化链路"),
        ),
    ]
