# Generated by Django 4.2.22 on 2026-03-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_clustering", "0039_clusteringconfig_predict_cluster_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusteringconfig",
            name="doris_storage",
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name="doris 存储集群"),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="storage_type",
            field=models.CharField(default="elasticsearch", max_length=32, verbose_name="聚类结果存储类型"),
        ),
    ]
