# Generated by Django 4.2.27 on 2025-12-24 13:29

import functools

import django.db.models.deletion
from django.db import migrations, models

import bk_monitor_base.config.storage
import bk_monitor_base.infras.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetricPluginModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_tenant_id", models.CharField(max_length=64, verbose_name="租户ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="归属业务ID")),
                ("is_global", models.BooleanField(default=False, verbose_name="是否全局插件")),
                ("is_internal", models.BooleanField(default=False, verbose_name="是否内置插件")),
                ("plugin_id", models.CharField(max_length=64, verbose_name="插件ID")),
                ("type", models.CharField(max_length=32, verbose_name="插件类型")),
                ("related_params", models.JSONField(default=dict, verbose_name="关联参数")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=255, verbose_name="创建用户")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("label", models.CharField(max_length=64, verbose_name="标签")),
            ],
            options={
                "verbose_name": "指标插件",
                "verbose_name_plural": "指标插件",
                "db_table": "metric_plugin",
                "ordering": ["-created_at"],
                "unique_together": {("bk_tenant_id", "plugin_id")},
            },
        ),
        migrations.CreateModel(
            name="MetricPluginDeploymentModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_tenant_id", models.CharField(max_length=64, verbose_name="租户ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="归属业务ID")),
                ("name", models.CharField(max_length=255, verbose_name="部署名称")),
                ("related_params", models.JSONField(default=dict, verbose_name="关联参数")),
                ("status", models.CharField(default="initializing", max_length=32, verbose_name="状态")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("created_by", models.CharField(blank=True, max_length=255, verbose_name="创建用户")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=255, verbose_name="更新用户")),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployments",
                        to="metric_plugin.metricpluginmodel",
                        verbose_name="插件",
                    ),
                ),
            ],
            options={
                "verbose_name": "指标插件部署项",
                "verbose_name_plural": "指标插件部署项",
                "db_table": "metric_plugin_deployment",
                "ordering": ["-created_at"],
                "unique_together": {("bk_tenant_id", "bk_biz_id", "name")},
            },
        ),
        migrations.CreateModel(
            name="JobTaskInstanceModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_tenant_id", models.CharField(max_length=64, verbose_name="租户ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务ID")),
                (
                    "action",
                    models.CharField(
                        help_text="install/uninstall/update/retry", max_length=32, verbose_name="操作类型"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending",
                        help_text="pending/running/success/failed/canceled",
                        max_length=32,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "instance_id",
                    models.CharField(
                        help_text="目标实例唯一标识，可能是 bk_host_id、ip:bk_cloud_id、container_id、namespace/pod_name 等",
                        max_length=255,
                        verbose_name="实例标识",
                    ),
                ),
                (
                    "instance_info",
                    models.JSONField(
                        default=dict,
                        help_text="目标实例的详细信息，如 bk_host_id, ip, bk_cloud_id,model_id,instance_id 等",
                        verbose_name="实例信息",
                    ),
                ),
                ("current_step", models.CharField(blank=True, default="", max_length=64, verbose_name="当前步骤")),
                (
                    "task_log",
                    models.JSONField(
                        default=list,
                        help_text="任务日志列表，每个条目包含 step, status, messages, job_instance_id, timestamp, extra",
                        verbose_name="任务日志",
                    ),
                ),
                (
                    "execute_params",
                    models.JSONField(
                        default=dict, help_text="存储执行时的参数，如配置文件路径、采集参数等", verbose_name="执行参数"
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("created_by", models.CharField(blank=True, default="", max_length=255, verbose_name="创建用户")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始执行时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
            ],
            options={
                "verbose_name": "Job任务实例",
                "verbose_name_plural": "Job任务实例",
                "db_table": "job_task_instance",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["bk_tenant_id", "bk_biz_id"], name="job_task_in_bk_tena_624205_idx"),
                    models.Index(fields=["instance_id"], name="job_task_in_instanc_b23cc0_idx"),
                    models.Index(fields=["status"], name="job_task_in_status_5f3e59_idx"),
                    models.Index(fields=["action"], name="job_task_in_action_50d031_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MetricPluginVersionModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_tenant_id", models.CharField(max_length=64, verbose_name="租户ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="归属业务ID")),
                ("name", models.CharField(max_length=255, verbose_name="插件名称")),
                ("description_md", models.TextField(blank=True, verbose_name="描述")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        storage=functools.partial(
                            bk_monitor_base.infras.storage.get_storage,
                            *(bk_monitor_base.config.storage.StorageName["DEFAULT"],),
                            **{},
                        ),
                        upload_to="metric_plugin/logo/",
                        verbose_name="logo",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=255, verbose_name="更新用户")),
                ("metrics", models.JSONField(default=list, verbose_name="指标配置")),
                ("enable_metric_discovery", models.BooleanField(default=False, verbose_name="自动发现指标开关")),
                ("params", models.JSONField(verbose_name="参数配置")),
                ("define", models.JSONField(verbose_name="插件定义")),
                ("is_support_remote", models.BooleanField(default=False, verbose_name="是否支持远程采集")),
                ("version", models.CharField(help_text="格式为major.minor", max_length=16, verbose_name="版本")),
                ("version_log", models.TextField(blank=True, verbose_name="版本日志")),
                (
                    "status",
                    models.CharField(
                        choices=[("debug", "DEBUG"), ("release", "RELEASE"), ("unregister", "UNREGISTER")],
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="metric_plugin.metricpluginmodel",
                        verbose_name="插件",
                    ),
                ),
            ],
            options={
                "verbose_name": "指标插件版本",
                "verbose_name_plural": "指标插件版本",
                "db_table": "metric_plugin_version",
                "ordering": ["-version"],
                "unique_together": {("bk_tenant_id", "bk_biz_id", "plugin", "version")},
            },
        ),
        migrations.CreateModel(
            name="MetricPluginDeploymentVersionModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_tenant_id", models.CharField(max_length=64, verbose_name="租户ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="归属业务ID")),
                (
                    "plugin_version",
                    models.CharField(help_text="格式为major.minor", max_length=16, verbose_name="插件版本"),
                ),
                ("version", models.IntegerField(help_text="从1开始，每次更新递增", verbose_name="版本号")),
                ("is_current", models.BooleanField(default=False, verbose_name="是否当前版本")),
                ("params", models.JSONField(default=dict, verbose_name="参数配置")),
                ("target_node_type", models.CharField(max_length=32, verbose_name="目标节点类型")),
                ("target_nodes", models.JSONField(default=list, verbose_name="目标节点")),
                (
                    "remote_node_type",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="远程节点类型"),
                ),
                ("remote_nodes", models.JSONField(default=list, verbose_name="采集节点")),
                ("target_instances", models.JSONField(default=list, verbose_name="目标实例")),
                ("remote_instances", models.JSONField(default=list, verbose_name="远程实例")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("created_by", models.CharField(blank=True, max_length=255, verbose_name="创建用户")),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="metric_plugin.metricplugindeploymentmodel",
                        verbose_name="部署项",
                    ),
                ),
            ],
            options={
                "verbose_name": "指标插件部署版本",
                "verbose_name_plural": "指标插件部署版本",
                "db_table": "metric_plugin_deployment_version",
                "ordering": ["deployment", "-version"],
                "unique_together": {("bk_tenant_id", "bk_biz_id", "deployment", "version")},
            },
        ),
    ]
