# Generated by Django 4.2.27 on 2026-01-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metric_plugin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metricpluginversionmodel",
            name="logo",
            field=models.TextField(blank=True, default="", verbose_name="logo(base64)"),
        ),
    ]
