# Generated by Django 4.2.27 on 2026-04-10 03:47

import bkmonitor.middlewares.source
import bkmonitor.utils.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RumAppConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("config_level", models.CharField(max_length=128, verbose_name="配置级别")),
                ("level_key", models.CharField(max_length=512, verbose_name="配置目标key")),
                ("config_key", models.CharField(max_length=255, verbose_name="config key")),
                ("config_value", bkmonitor.utils.db.fields.JsonField(verbose_name="配置信息")),
            ],
            options={
                "unique_together": {("config_level", "level_key", "config_key")},
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="最后修改人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="最后修改时间")),
                ("application_id", models.BigIntegerField(primary_key=True, serialize=False, verbose_name="应用Id")),
                ("bk_tenant_id", models.CharField(default="system", max_length=64, verbose_name="租户ID")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务id")),
                ("app_name", models.CharField(max_length=50, verbose_name="应用名称")),
                ("app_alias", models.CharField(max_length=128, verbose_name="应用别名")),
                ("description", models.CharField(default="", max_length=255, verbose_name="应用描述")),
                ("client_type", models.CharField(default="web", max_length=32, verbose_name="前端类型")),
                ("metric_result_table_id", models.CharField(default="", max_length=128, verbose_name="聚合指标结果表")),
                ("span_result_table_id", models.CharField(default="", max_length=128, verbose_name="原始日志结果表")),
                ("time_series_group_id", models.IntegerField(default=0, verbose_name="时序分组ID")),
                (
                    "source",
                    models.CharField(
                        default=bkmonitor.middlewares.source.get_source_app_code, max_length=32, verbose_name="来源系统"
                    ),
                ),
                ("apm_application_id", models.BigIntegerField(blank=True, null=True, verbose_name="关联 APM 应用ID")),
                ("data_status", models.CharField(default="no_data", max_length=32, verbose_name="数据状态")),
            ],
            options={
                "ordering": ["-update_time", "-application_id"],
                "index_together": {("update_time", "application_id"), ("bk_biz_id", "app_name")},
            },
        ),
    ]
