# Generated by Django 4.2.27 on 2026-04-10 03:54

import bkmonitor.utils.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RumDataSource",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
                ("app_name", models.CharField(max_length=255, verbose_name="所属应用")),
                ("bk_data_id", models.IntegerField(default=-1, verbose_name="数据id")),
                ("result_table_id", models.CharField(default="", max_length=128, verbose_name="结果表id")),
                ("index_set_id", models.IntegerField(null=True, verbose_name="索引集id")),
                ("index_set_name", models.CharField(max_length=512, null=True, verbose_name="索引集名称")),
            ],
            options={
                "abstract": False,
                "index_together": {("bk_biz_id", "app_name")},
            },
        ),
        migrations.CreateModel(
            name="RumApplication",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_user", models.CharField(blank=True, default="", max_length=32, verbose_name="创建人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_user", models.CharField(blank=True, default="", max_length=32, verbose_name="最后修改人")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="最后修改时间")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
                ("app_name", models.CharField(max_length=50, verbose_name="应用名称")),
                ("app_alias", models.CharField(max_length=128, verbose_name="应用别名")),
                ("description", models.CharField(default="", max_length=255, verbose_name="应用描述")),
                ("type", models.CharField(default="web", max_length=32, verbose_name="前端类型")),
                ("token", models.CharField(default="", max_length=64, verbose_name="前端接入 Token")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("bk_tenant_id", models.CharField(default="system", max_length=64, verbose_name="租户ID")),
            ],
            options={
                "unique_together": {("app_name", "bk_biz_id")},
            },
        ),
        migrations.CreateModel(
            name="RumAppConfig",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
                ("app_name", models.CharField(max_length=128, verbose_name="应用名称")),
                (
                    "config_type",
                    models.CharField(
                        help_text="复合键格式 '大类:小类'，如 apdex:lcp / qps:default / sampler:percentage",
                        max_length=64,
                        verbose_name="配置类型",
                    ),
                ),
                ("config_value", models.IntegerField(verbose_name="配置值")),
                (
                    "scope_type",
                    models.CharField(default="application_level", max_length=255, verbose_name="配置作用类型"),
                ),
                (
                    "scope_key",
                    models.CharField(
                        default="",
                        help_text="APPLICATION_LEVEL 时为 app_name",
                        max_length=255,
                        verbose_name="配置作用点",
                    ),
                ),
            ],
            options={
                "index_together": {("bk_biz_id", "app_name")},
            },
        ),
        migrations.CreateModel(
            name="MetricDataSource",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
                ("app_name", models.CharField(max_length=255, verbose_name="所属应用")),
                ("bk_data_id", models.IntegerField(default=-1, verbose_name="数据id")),
                ("result_table_id", models.CharField(default="", max_length=128, verbose_name="结果表id")),
                ("time_series_group_id", models.IntegerField(default=0, verbose_name="时序分组ID")),
                ("data_label", models.CharField(default="", max_length=128, verbose_name="数据标签")),
                (
                    "bk_data_virtual_metric_config",
                    bkmonitor.utils.db.fields.JsonField(null=True, verbose_name="数据平台虚拟指标配置"),
                ),
            ],
            options={
                "abstract": False,
                "index_together": {("bk_biz_id", "app_name")},
            },
        ),
    ]
