# Generated by Django 4.2.27 on 2026-09-17

import bkmonitor.utils.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataLink",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
                ("kafka_cluster_id", models.IntegerField(verbose_name="kafka集群id", null=True)),
                (
                    "elasticsearch_cluster_id",
                    models.IntegerField(
                        verbose_name="默认ES集群ID(在快速创建应用、创建默认预计算集群时会用到)", null=True
                    ),
                ),
                (
                    "pre_calculate_config",
                    bkmonitor.utils.db.fields.JsonField(verbose_name="RUM 预计算数据存储配置", null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
