{
 "title": "Applicaiton - Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "deepflowio-deepflow-datasource" },
   {
    "name": "cluster",
    "query": {}
   },
   {
    "name": "namespace",
    "query": {}
   },
   {
    "name": "workload",
    "query": {}
   },
   {
    "name": "signal_source",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "使用说明",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  { "title": "应用总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"vtap_app_port\",\"select\":[{\"key\":\"request\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"f5f2a3ae-3099-6b99-005e-8d4562018121\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"PerSecond\"}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"PerSecond\"}]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c16deb2d-fe3c-69ff-01a5-8859e7dfaa51\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"09341d0e-dd98-57ba-6382-47aed3c99012\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"fe90f86c-d46f-8642-8200-d0bb863459cb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"7bd72703-9e5c-d977-0866-5306c09a5f9d\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"06745764-d56f-e0fc-d944-a93769bbbd27\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"region\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a08841f1-af76-acdb-39d3-8d3a791c024e\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"76bcc3ff-77ec-d32d-ed6a-391651b993b2\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"slimit\":\"\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "PerSecond(Avg(request))", "name": "PerSecond(Avg(request))", "type": 1, "unit": "/s" }
     ],
     "returnTags": [
      {
       "displayName": "time_$__interval",
       "isResource": false,
       "name": "`time_$__interval`"
      },
      {
       "displayName": "节点类型",
       "isResource": false,
       "name": "`node_type`"
      },
      {
       "displayName": "图标",
       "isResource": false,
       "name": "`icon_id`"
      },
      {
       "displayName": "Region",
       "isResource": false,
       "name": "region_id"
      },
      {
       "displayName": "Region",
       "isResource": false,
       "name": "region"
      }
     ],
     "sql": "SELECT PerSecond(Avg(`request`)) AS `PerSecond(Avg(request))`, time(time, $__interval) AS `time_$__interval`, node_type(region) AS `node_type`, icon_id(region) AS `icon_id`, region_id, region FROM vtap_app_port WHERE pod_cluster = 'k8s-d-rUL3jSx3ft' AND pod_ns = 'deepflow' AND (pod_group = 'deepflow-mysql' OR pod_group = 'deepflow-grafana' OR pod_group = 'deepflow-server' OR pod_group = 'deepflow-agent' OR pod_group = 'deepflow-app' OR pod_group = 'deepflow-clickhouse') AND signal_source IN (0,3,4) AND time>=1705538829 AND time<=1705560429 GROUP BY `time_$__interval`, region, region_id, `node_type` SLIMIT 20 LIMIT 10000"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"vtap_app_port\",\"select\":[{\"key\":\"rrt_max\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"f5f2a3ae-3099-6b99-005e-8d4562018121\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c16deb2d-fe3c-69ff-01a5-8859e7dfaa51\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"228def66-88ae-f295-d0a2-2e0b9d572442\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c6bd3e65-dc5d-ed9d-d055-048ec27992b3\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"709938cd-ad05-29dc-eee5-193ecdd091b8\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"527b6114-e47b-9004-16cd-885f60e2abb5\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"region\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a08841f1-af76-acdb-39d3-8d3a791c024e\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"76bcc3ff-77ec-d32d-ed6a-391651b993b2\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"slimit\":\"\",\"limit\":\"100\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "Avg(rrt_max)", "name": "Avg(rrt_max)", "type": 3, "unit": "us" }
     ],
     "returnTags": [
      {
       "displayName": "time_$__interval",
       "isResource": false,
       "name": "`time_$__interval`"
      },
      {
       "displayName": "节点类型",
       "isResource": false,
       "name": "`node_type`"
      },
      {
       "displayName": "图标",
       "isResource": false,
       "name": "`icon_id`"
      },
      {
       "displayName": "Region",
       "isResource": false,
       "name": "region_id"
      },
      {
       "displayName": "Region",
       "isResource": false,
       "name": "region"
      }
     ],
     "sql": "SELECT Avg(`rrt_max`) AS `Avg(rrt_max)`, time(time, $__interval) AS `time_$__interval`, node_type(region) AS `node_type`, icon_id(region) AS `icon_id`, region_id, region FROM vtap_app_port WHERE pod_cluster = 'k8s-d-rUL3jSx3ft' AND pod_ns = 'deepflow' AND (pod_group = 'deepflow-mysql' OR pod_group = 'deepflow-grafana' OR pod_group = 'deepflow-server' OR pod_group = 'deepflow-agent' OR pod_group = 'deepflow-app' OR pod_group = 'deepflow-clickhouse') AND signal_source IN (3) AND time>=1705538829 AND time<=1705560429 GROUP BY `time_$__interval`, region, region_id, `node_type` SLIMIT 20 LIMIT 100"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"vtap_app_port\",\"select\":[{\"key\":\"server_error_ratio\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"f5f2a3ae-3099-6b99-005e-8d4562018121\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"PerSecond\"}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"PerSecond\"}]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c16deb2d-fe3c-69ff-01a5-8859e7dfaa51\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"8f4752c3-eb37-e241-11bd-59d90caf2f42\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"67a7b94c-405c-3ba8-8373-523c33498985\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"69e35f27-2495-812e-a815-0b7e746a6771\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"dedef6b4-0fa2-0c0d-c0c4-7b006025aa0c\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"region\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a08841f1-af76-acdb-39d3-8d3a791c024e\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"76bcc3ff-77ec-d32d-ed6a-391651b993b2\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"slimit\":\"\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      {
       "displayName": "PerSecond(Avg(server_error_ratio))",
       "name": "PerSecond(Avg(server_error_ratio))",
       "type": 4,
       "unit": "%/s"
      }
     ],
     "returnTags": [
      {
       "displayName": "time_$__interval",
       "isResource": false,
       "name": "`time_$__interval`"
      },
      {
       "displayName": "节点类型",
       "isResource": false,
       "name": "`node_type`"
      },
      {
       "displayName": "图标",
       "isResource": false,
       "name": "`icon_id`"
      },
      {
       "displayName": "Region",
       "isResource": false,
       "name": "region_id"
      },
      {
       "displayName": "Region",
       "isResource": false,
       "name": "region"
      }
     ],
     "sql": "SELECT PerSecond(Avg(`server_error_ratio`)) AS `PerSecond(Avg(server_error_ratio))`, time(time, $__interval) AS `time_$__interval`, node_type(region) AS `node_type`, icon_id(region) AS `icon_id`, region_id, region FROM vtap_app_port WHERE pod_cluster = 'k8s-d-rUL3jSx3ft' AND pod_ns = 'deepflow' AND (pod_group = 'deepflow-mysql' OR pod_group = 'deepflow-grafana' OR pod_group = 'deepflow-server' OR pod_group = 'deepflow-agent' OR pod_group = 'deepflow-app' OR pod_group = 'deepflow-clickhouse') AND signal_source IN (3) AND time>=1705538829 AND time<=1705560429 GROUP BY `time_$__interval`, region, region_id, `node_type` SLIMIT 20 LIMIT 10000"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"vtap_app_port\",\"select\":[{\"key\":\"client_error_ratio\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"f5f2a3ae-3099-6b99-005e-8d4562018121\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c16deb2d-fe3c-69ff-01a5-8859e7dfaa51\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"6b24f852-ded7-8bf1-f445-208dfaa062a2\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"1773dec6-552e-2696-a9a1-6eebd012c193\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"27fc2a41-ed8a-767d-709a-ac0c129a5831\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"82a76ab6-0e2a-2a72-3e80-b58947db8018\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"region\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a08841f1-af76-acdb-39d3-8d3a791c024e\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"76bcc3ff-77ec-d32d-ed6a-391651b993b2\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"slimit\":\"\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "Avg(client_error_ratio)", "name": "Avg(client_error_ratio)", "type": 4, "unit": "%" }
     ],
     "returnTags": [
      {
       "displayName": "time_$__interval",
       "isResource": false,
       "name": "`time_$__interval`"
      },
      {
       "displayName": "节点类型",
       "isResource": false,
       "name": "`node_type`"
      },
      {
       "displayName": "图标",
       "isResource": false,
       "name": "`icon_id`"
      },
      {
       "displayName": "Region",
       "isResource": false,
       "name": "region_id"
      },
      {
       "displayName": "Region",
       "isResource": false,
       "name": "region"
      }
     ],
     "sql": "SELECT Avg(`client_error_ratio`) AS `Avg(client_error_ratio)`, time(time, $__interval) AS `time_$__interval`, node_type(region) AS `node_type`, icon_id(region) AS `icon_id`, region_id, region FROM vtap_app_port WHERE pod_cluster = 'k8s-d-rUL3jSx3ft' AND pod_ns = 'deepflow-ebpf-istio-demo' AND pod_group = 'reviews-v3' AND signal_source IN (0) AND time>=1705579482 AND time<=1705580382 GROUP BY `time_$__interval`, region, region_id, `node_type` SLIMIT 20 LIMIT 10000"
    }
   ]
  },
  {
   "title": "服务拓扑",
   "type": "deepflowio-topo-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "metaExtra": {
      "common": [
       "tap_side",
       "Enum(tap_side)"
      ],
      "from": [ "auto_service_id_0" ],
      "to": [ "auto_service_id_1" ]
     },
     "queryText": "{\"appType\":\"accessRelationship\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"vtap_app_edge_port\",\"select\":[{\"key\":\"request\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"请求速率\",\"params\":[],\"uuid\":\"2502a864-f210-12d3-8429-ffa9d420521e\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"PerSecond\"}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"PerSecond\"}]}},{\"type\":\"metric\",\"key\":\"rrt\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"平均响应时延\",\"params\":[],\"uuid\":\"69ced02c-2bb1-610f-3110-5888200d7b0c\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"client_error_ratio\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"客户端异常比例\",\"params\":[],\"uuid\":\"3e57e5dd-2530-3c65-3bd0-2c948f8baa1b\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"server_error_ratio\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"服务端异常比例\",\"params\":[],\"uuid\":\"fb175a0c-a3c7-a4d2-22ee-8077f8a2b9b2\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"9d9f9386-f181-ffa2-66c8-d7949a128d40\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"e6a16e9f-11e9-5f24-e354-ba02311fb120\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"81dac0fe-e5e8-7408-d4a9-232c337c73e8\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"72ffb4b3-43b8-dffa-dcad-443ce29dab16\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8a2e2254-6d9a-a394-c9ed-b04f54048c24\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service_0\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"b56a8bb4-f39d-7338-2171-1d61dcb5ccc0\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"from\",\"isResourceType\":true,\"isIpType\":false},{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"061e543e-8414-6ccb-fe69-83debca7c278\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tap_side\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"c85a769b-7fe2-c665-c677-458ff9df387f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"76bcc3ff-77ec-d32d-ed6a-391651b993b2\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"\",\"alias\":\"\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "请求速率", "name": "请求速率", "type": 1, "unit": "/s" },
      { "displayName": "平均响应时延", "name": "平均响应时延", "type": 3, "unit": "us" },
      { "displayName": "客户端异常比例", "name": "客户端异常比例", "type": 4, "unit": "%" },
      { "displayName": "服务端异常比例", "name": "服务端异常比例", "type": 4, "unit": "%" }
     ],
     "returnTags": [
      {
       "displayName": "节点类型",
       "isResource": true,
       "name": "`client_node_type`",
       "role": "client"
      },
      {
       "displayName": "图标",
       "isResource": true,
       "name": "`client_icon_id`",
       "role": "client"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_id_0",
       "role": "client"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_0",
       "role": "client"
      },
      {
       "displayName": "节点类型",
       "isResource": true,
       "name": "`server_node_type`",
       "role": "server"
      },
      {
       "displayName": "图标",
       "isResource": true,
       "name": "`server_icon_id`",
       "role": "server"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_id_1",
       "role": "server"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_1",
       "role": "server"
      },
      {
       "displayName": "TAP Side",
       "isResource": false,
       "name": "Enum(tap_side)"
      },
      {
       "displayName": "TAP Side",
       "isResource": false,
       "name": "tap_side"
      }
     ],
     "sql": "SELECT PerSecond(Avg(`request`)) AS `请求速率`, Avg(`rrt`) AS `平均响应时延`, Avg(`client_error_ratio`) AS `客户端异常比例`, Avg(`server_error_ratio`) AS `服务端异常比例`, node_type(auto_service_0) AS `client_node_type`, icon_id(auto_service_0) AS `client_icon_id`, auto_service_id_0, auto_service_0, node_type(auto_service_1) AS `server_node_type`, icon_id(auto_service_1) AS `server_icon_id`, auto_service_id_1, auto_service_1, Enum(tap_side), tap_side FROM vtap_app_edge_port WHERE (pod_cluster_0 = 'k8s-d-rUL3jSx3ft' OR pod_cluster_1 = 'k8s-d-rUL3jSx3ft') AND (pod_ns_0 = 'deepflow' OR pod_ns_1 = 'deepflow') AND (pod_group_0 = 'deepflow-mysql' OR pod_group_0 = 'deepflow-grafana' OR pod_group_0 = 'deepflow-server' OR pod_group_0 = 'deepflow-agent' OR pod_group_0 = 'deepflow-app' OR pod_group_0 = 'deepflow-clickhouse' OR pod_group_1 = 'deepflow-mysql' OR pod_group_1 = 'deepflow-grafana' OR pod_group_1 = 'deepflow-server' OR pod_group_1 = 'deepflow-agent' OR pod_group_1 = 'deepflow-app' OR pod_group_1 = 'deepflow-clickhouse') AND signal_source IN (3) AND time>=1705538829 AND time<=1705560429 GROUP BY auto_service_0, auto_service_1, tap_side, auto_service_id_0, auto_service_id_1, `client_node_type`, `server_node_type` LIMIT 1000"
    }
   ]
  },
  {
   "title": "请求速率（应用协议）",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"vtap_app_port\",\"select\":[{\"key\":\"request\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"f5f2a3ae-3099-6b99-005e-8d4562018121\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"PerSecond\"}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"PerSecond\"}]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c16deb2d-fe3c-69ff-01a5-8859e7dfaa51\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"228def66-88ae-f295-d0a2-2e0b9d572442\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c6bd3e65-dc5d-ed9d-d055-048ec27992b3\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"709938cd-ad05-29dc-eee5-193ecdd091b8\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"20bf8fe3-78c1-ae41-b256-da6992a52d77\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a08841f1-af76-acdb-39d3-8d3a791c024e\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"76bcc3ff-77ec-d32d-ed6a-391651b993b2\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"slimit\":\"\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${Enum(l7_protocol)}\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "PerSecond(Avg(request))", "name": "PerSecond(Avg(request))", "type": 1, "unit": "/s" }
     ],
     "returnTags": [
      {
       "displayName": "time_$__interval",
       "isResource": false,
       "name": "`time_$__interval`"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "Enum(l7_protocol)"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "l7_protocol"
      }
     ],
     "sql": "SELECT PerSecond(Avg(`request`)) AS `PerSecond(Avg(request))`, time(time, $__interval) AS `time_$__interval`, Enum(l7_protocol), l7_protocol FROM vtap_app_port WHERE pod_cluster = 'k8s-d-rUL3jSx3ft' AND (pod_ns = 'openebs' OR pod_ns = 'ingress' OR pod_ns = 'deepflow' OR pod_ns = 'default' OR pod_ns = 'monitoring' OR pod_ns = 'kube-system' OR pod_ns = 'otel-demo' OR pod_ns = 'istio-system' OR pod_ns = 'open-telemetry' OR pod_ns = 'deepflow-otel-grpc-demo' OR pod_ns = 'deepflow-prometheus-demo' OR pod_ns = 'deepflow-ebpf-istio-demo' OR pod_ns = 'deepflow-telegraf-demo' OR pod_ns = 'deepflow-otel-dubbo-demo' OR pod_ns = 'deepflow-spring-part-demo' OR pod_ns = 'deepflow-ebpf-spring-demo' OR pod_ns = 'deepflow-otel-skywalking-demo' OR pod_ns = 'deepflow-spring-full-demo' OR pod_ns = 'deepflow-otel-spring-demo') AND (pod_group = 'telegraf' OR pod_group = 'influxdb' OR pod_group = 'svc-item' OR pod_group = 'svc-user' OR pod_group = 'foo-svc' OR pod_group = 'coredns' OR pod_group = 'promtail' OR pod_group = 'web-shop' OR pod_group = 'istiod' OR pod_group = 'bar-svc' OR pod_group = 'frontend' OR pod_group = 'nacos' OR pod_group = 'loo-svc' OR pod_group = 'db-demo' OR pod_group = 'reviews-v2' OR pod_group = 'deepflow-mysql' OR pod_group = 'emailservice' OR pod_group = 'dns-autoscaler' OR pod_group = 'deepflow-grafana' OR pod_group = 'deepflow-server' OR pod_group = 'loadgenerator' OR pod_group = 'reviews-v1' OR pod_group = 'adservice' OR pod_group = 'ratings-v1' OR pod_group = 'deepflow-agent' OR pod_group = 'checkoutservice' OR pod_group = 'paymentservice' OR pod_group = 'redis-cart' OR pod_group = 'deepflow-app' OR pod_group = 'cartservice' OR pod_group = 'shippingservice' OR pod_group = 'loo-svc-full' OR pod_group = 'otel-agent' OR pod_group = 'bar-svc-full' OR pod_group = 'reviews-v3' OR pod_group = 'currencyservice' OR pod_group = 'svc-stock' OR pod_group = 'foo-svc-part' OR pod_group = 'loadgenerator-ng' OR pod_group = 'prometheus-k8s' OR pod_group = 'redis-master' OR pod_group = 'svc-order' OR pod_group = 'foo-svc-full' OR pod_group = 'bar-svc-part' OR pod_group = 'details-v1' OR pod_group = 'loo-svc-part' OR pod_group = 'productpage-v1' OR pod_group = 'opentelemetry-demo-redis' OR pod_group = 'productcatalogservice' OR pod_group = 'prometheus-operator' OR pod_group = 'prometheus-adapter' OR pod_group = 'opentelemetry-demo-kafka' OR pod_group = 'alertmanager-main' OR pod_group = 'openebs-ndm-operator' OR pod_group = 'prometheus-alertmanager' OR pod_group = 'deepflow-clickhouse' OR pod_group = 'istio-ingressgateway' OR pod_group = 'recommendationservice' OR pod_group = 'prometheus-server' OR pod_group = 'prometheus-pushgateway' OR pod_group = 'istio-egressgateway' OR pod_group = 'openebs-ndm-node-exporter' OR pod_group = 'opentelemetry-demo-emailservice' OR pod_group = 'opentelemetry-demo-frauddetectionservice' OR pod_group = 'opentelemetry-demo-paymentservice' OR pod_group = 'opentelemetry-demo-jaeger' OR pod_group = 'opentelemetry-demo-currencyservice' OR pod_group = 'opentelemetry-demo-cartservice' OR pod_group = 'opentelemetry-demo-productcatalogservice' OR pod_group = 'opentelemetry-demo-shippingservice' OR pod_group = 'openebs-localpv-provisioner' OR pod_group = 'demo-ingress-nginx-ingress' OR pod_group = 'opentelemetry-demo-ffspostgres' OR pod_group = 'opentelemetry-demo-accountingservice' OR pod_group = 'opentelemetry-demo-featureflagservice' OR pod_group = 'opentelemetry-demo-loadgenerator' OR pod_group = 'openebs-ndm-cluster-exporter' OR pod_group = 'opentelemetry-demo-recommendationservice' OR pod_group = 'opentelemetry-demo-adservice' OR pod_group = 'opentelemetry-demo-checkoutservice' OR pod_group = 'prometheus-kube-state-metrics' OR pod_group = 'opentelemetry-demo-otelcol' OR pod_group = 'opentelemetry-demo-prometheus-server' OR pod_group = 'opentelemetry-demo-quoteservice' OR pod_group = 'opentelemetry-demo-frontend') AND signal_source IN (0) AND time>=1705643483 AND time<=1705644383 GROUP BY `time_$__interval`, l7_protocol SLIMIT 20 LIMIT 10000"
    }
   ]
  },
  {
   "title": "响应时延（应用协议）",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"vtap_app_port\",\"select\":[{\"key\":\"rrt_max\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"f5f2a3ae-3099-6b99-005e-8d4562018121\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c16deb2d-fe3c-69ff-01a5-8859e7dfaa51\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"228def66-88ae-f295-d0a2-2e0b9d572442\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c6bd3e65-dc5d-ed9d-d055-048ec27992b3\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"709938cd-ad05-29dc-eee5-193ecdd091b8\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"1683c0f2-71b4-49fe-7ea7-822103440c75\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a08841f1-af76-acdb-39d3-8d3a791c024e\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"76bcc3ff-77ec-d32d-ed6a-391651b993b2\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"slimit\":\"\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${Enum(l7_protocol)}\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "Avg(rrt_max)", "name": "Avg(rrt_max)", "type": 3, "unit": "us" }
     ],
     "returnTags": [
      {
       "displayName": "time_$__interval",
       "isResource": false,
       "name": "`time_$__interval`"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "Enum(l7_protocol)"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "l7_protocol"
      }
     ],
     "sql": "SELECT Avg(`rrt_max`) AS `Avg(rrt_max)`, time(time, $__interval) AS `time_$__interval`, Enum(l7_protocol), l7_protocol FROM vtap_app_port WHERE pod_cluster = 'k8s-d-rUL3jSx3ft' AND (pod_ns = 'openebs' OR pod_ns = 'ingress' OR pod_ns = 'deepflow' OR pod_ns = 'default' OR pod_ns = 'monitoring' OR pod_ns = 'kube-system' OR pod_ns = 'otel-demo' OR pod_ns = 'istio-system' OR pod_ns = 'open-telemetry' OR pod_ns = 'deepflow-otel-grpc-demo' OR pod_ns = 'deepflow-prometheus-demo' OR pod_ns = 'deepflow-ebpf-istio-demo' OR pod_ns = 'deepflow-telegraf-demo' OR pod_ns = 'deepflow-otel-dubbo-demo' OR pod_ns = 'deepflow-spring-part-demo' OR pod_ns = 'deepflow-ebpf-spring-demo' OR pod_ns = 'deepflow-otel-skywalking-demo' OR pod_ns = 'deepflow-spring-full-demo' OR pod_ns = 'deepflow-otel-spring-demo') AND (pod_group = 'telegraf' OR pod_group = 'influxdb' OR pod_group = 'svc-item' OR pod_group = 'svc-user' OR pod_group = 'foo-svc' OR pod_group = 'coredns' OR pod_group = 'promtail' OR pod_group = 'web-shop' OR pod_group = 'istiod' OR pod_group = 'bar-svc' OR pod_group = 'frontend' OR pod_group = 'nacos' OR pod_group = 'loo-svc' OR pod_group = 'db-demo' OR pod_group = 'reviews-v2' OR pod_group = 'deepflow-mysql' OR pod_group = 'emailservice' OR pod_group = 'dns-autoscaler' OR pod_group = 'deepflow-grafana' OR pod_group = 'deepflow-server' OR pod_group = 'loadgenerator' OR pod_group = 'reviews-v1' OR pod_group = 'adservice' OR pod_group = 'ratings-v1' OR pod_group = 'deepflow-agent' OR pod_group = 'checkoutservice' OR pod_group = 'paymentservice' OR pod_group = 'redis-cart' OR pod_group = 'deepflow-app' OR pod_group = 'cartservice' OR pod_group = 'shippingservice' OR pod_group = 'loo-svc-full' OR pod_group = 'otel-agent' OR pod_group = 'bar-svc-full' OR pod_group = 'reviews-v3' OR pod_group = 'currencyservice' OR pod_group = 'svc-stock' OR pod_group = 'foo-svc-part' OR pod_group = 'loadgenerator-ng' OR pod_group = 'prometheus-k8s' OR pod_group = 'redis-master' OR pod_group = 'svc-order' OR pod_group = 'foo-svc-full' OR pod_group = 'bar-svc-part' OR pod_group = 'details-v1' OR pod_group = 'loo-svc-part' OR pod_group = 'productpage-v1' OR pod_group = 'opentelemetry-demo-redis' OR pod_group = 'productcatalogservice' OR pod_group = 'prometheus-operator' OR pod_group = 'prometheus-adapter' OR pod_group = 'opentelemetry-demo-kafka' OR pod_group = 'alertmanager-main' OR pod_group = 'openebs-ndm-operator' OR pod_group = 'prometheus-alertmanager' OR pod_group = 'deepflow-clickhouse' OR pod_group = 'istio-ingressgateway' OR pod_group = 'recommendationservice' OR pod_group = 'prometheus-server' OR pod_group = 'prometheus-pushgateway' OR pod_group = 'istio-egressgateway' OR pod_group = 'openebs-ndm-node-exporter' OR pod_group = 'opentelemetry-demo-emailservice' OR pod_group = 'opentelemetry-demo-frauddetectionservice' OR pod_group = 'opentelemetry-demo-paymentservice' OR pod_group = 'opentelemetry-demo-jaeger' OR pod_group = 'opentelemetry-demo-currencyservice' OR pod_group = 'opentelemetry-demo-cartservice' OR pod_group = 'opentelemetry-demo-productcatalogservice' OR pod_group = 'opentelemetry-demo-shippingservice' OR pod_group = 'openebs-localpv-provisioner' OR pod_group = 'demo-ingress-nginx-ingress' OR pod_group = 'opentelemetry-demo-ffspostgres' OR pod_group = 'opentelemetry-demo-accountingservice' OR pod_group = 'opentelemetry-demo-featureflagservice' OR pod_group = 'opentelemetry-demo-loadgenerator' OR pod_group = 'openebs-ndm-cluster-exporter' OR pod_group = 'opentelemetry-demo-recommendationservice' OR pod_group = 'opentelemetry-demo-adservice' OR pod_group = 'opentelemetry-demo-checkoutservice' OR pod_group = 'prometheus-kube-state-metrics' OR pod_group = 'opentelemetry-demo-otelcol' OR pod_group = 'opentelemetry-demo-prometheus-server' OR pod_group = 'opentelemetry-demo-quoteservice' OR pod_group = 'opentelemetry-demo-frontend') AND signal_source IN (0) AND time>=1705643483 AND time<=1705644383 GROUP BY `time_$__interval`, l7_protocol SLIMIT 20 LIMIT 10000"
    }
   ]
  },
  {
   "title": "异常比例（应用协议）",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"vtap_app_port\",\"select\":[{\"key\":\"client_error_ratio\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"客户端异常比例\",\"params\":[],\"uuid\":\"f5f2a3ae-3099-6b99-005e-8d4562018121\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[]}},{\"type\":\"metric\",\"key\":\"server_error_ratio\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"服务端异常比例\",\"params\":[],\"uuid\":\"2190e0b8-7262-0ba6-46e2-5791d5de3eab\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c16deb2d-fe3c-69ff-01a5-8859e7dfaa51\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"228def66-88ae-f295-d0a2-2e0b9d572442\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c6bd3e65-dc5d-ed9d-d055-048ec27992b3\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"709938cd-ad05-29dc-eee5-193ecdd091b8\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"f94688a1-5798-3b71-2e93-7d8d74041d2e\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a08841f1-af76-acdb-39d3-8d3a791c024e\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"76bcc3ff-77ec-d32d-ed6a-391651b993b2\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"slimit\":\"\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${Enum(l7_protocol)}\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "客户端异常比例", "name": "客户端异常比例", "type": 4, "unit": "%" },
      { "displayName": "服务端异常比例", "name": "服务端异常比例", "type": 4, "unit": "%" }
     ],
     "returnTags": [
      {
       "displayName": "time_$__interval",
       "isResource": false,
       "name": "`time_$__interval`"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "Enum(l7_protocol)"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "l7_protocol"
      }
     ],
     "sql": "SELECT Avg(`client_error_ratio`) AS `客户端异常比例`, Avg(`server_error_ratio`) AS `服务端异常比例`, time(time, $__interval) AS `time_$__interval`, Enum(l7_protocol), l7_protocol FROM vtap_app_port WHERE pod_cluster = 'k8s-d-rUL3jSx3ft' AND (pod_ns = 'openebs' OR pod_ns = 'ingress' OR pod_ns = 'deepflow' OR pod_ns = 'default' OR pod_ns = 'monitoring' OR pod_ns = 'kube-system' OR pod_ns = 'otel-demo' OR pod_ns = 'istio-system' OR pod_ns = 'open-telemetry' OR pod_ns = 'deepflow-otel-grpc-demo' OR pod_ns = 'deepflow-prometheus-demo' OR pod_ns = 'deepflow-ebpf-istio-demo' OR pod_ns = 'deepflow-telegraf-demo' OR pod_ns = 'deepflow-otel-dubbo-demo' OR pod_ns = 'deepflow-spring-part-demo' OR pod_ns = 'deepflow-ebpf-spring-demo' OR pod_ns = 'deepflow-otel-skywalking-demo' OR pod_ns = 'deepflow-spring-full-demo' OR pod_ns = 'deepflow-otel-spring-demo') AND (pod_group = 'telegraf' OR pod_group = 'influxdb' OR pod_group = 'svc-item' OR pod_group = 'svc-user' OR pod_group = 'foo-svc' OR pod_group = 'coredns' OR pod_group = 'promtail' OR pod_group = 'web-shop' OR pod_group = 'istiod' OR pod_group = 'bar-svc' OR pod_group = 'frontend' OR pod_group = 'nacos' OR pod_group = 'loo-svc' OR pod_group = 'db-demo' OR pod_group = 'reviews-v2' OR pod_group = 'deepflow-mysql' OR pod_group = 'emailservice' OR pod_group = 'dns-autoscaler' OR pod_group = 'deepflow-grafana' OR pod_group = 'deepflow-server' OR pod_group = 'loadgenerator' OR pod_group = 'reviews-v1' OR pod_group = 'adservice' OR pod_group = 'ratings-v1' OR pod_group = 'deepflow-agent' OR pod_group = 'checkoutservice' OR pod_group = 'paymentservice' OR pod_group = 'redis-cart' OR pod_group = 'deepflow-app' OR pod_group = 'cartservice' OR pod_group = 'shippingservice' OR pod_group = 'loo-svc-full' OR pod_group = 'otel-agent' OR pod_group = 'bar-svc-full' OR pod_group = 'reviews-v3' OR pod_group = 'currencyservice' OR pod_group = 'svc-stock' OR pod_group = 'foo-svc-part' OR pod_group = 'loadgenerator-ng' OR pod_group = 'prometheus-k8s' OR pod_group = 'redis-master' OR pod_group = 'svc-order' OR pod_group = 'foo-svc-full' OR pod_group = 'bar-svc-part' OR pod_group = 'details-v1' OR pod_group = 'loo-svc-part' OR pod_group = 'productpage-v1' OR pod_group = 'opentelemetry-demo-redis' OR pod_group = 'productcatalogservice' OR pod_group = 'prometheus-operator' OR pod_group = 'prometheus-adapter' OR pod_group = 'opentelemetry-demo-kafka' OR pod_group = 'alertmanager-main' OR pod_group = 'openebs-ndm-operator' OR pod_group = 'prometheus-alertmanager' OR pod_group = 'deepflow-clickhouse' OR pod_group = 'istio-ingressgateway' OR pod_group = 'recommendationservice' OR pod_group = 'prometheus-server' OR pod_group = 'prometheus-pushgateway' OR pod_group = 'istio-egressgateway' OR pod_group = 'openebs-ndm-node-exporter' OR pod_group = 'opentelemetry-demo-emailservice' OR pod_group = 'opentelemetry-demo-frauddetectionservice' OR pod_group = 'opentelemetry-demo-paymentservice' OR pod_group = 'opentelemetry-demo-jaeger' OR pod_group = 'opentelemetry-demo-currencyservice' OR pod_group = 'opentelemetry-demo-cartservice' OR pod_group = 'opentelemetry-demo-productcatalogservice' OR pod_group = 'opentelemetry-demo-shippingservice' OR pod_group = 'openebs-localpv-provisioner' OR pod_group = 'demo-ingress-nginx-ingress' OR pod_group = 'opentelemetry-demo-ffspostgres' OR pod_group = 'opentelemetry-demo-accountingservice' OR pod_group = 'opentelemetry-demo-featureflagservice' OR pod_group = 'opentelemetry-demo-loadgenerator' OR pod_group = 'openebs-ndm-cluster-exporter' OR pod_group = 'opentelemetry-demo-recommendationservice' OR pod_group = 'opentelemetry-demo-adservice' OR pod_group = 'opentelemetry-demo-checkoutservice' OR pod_group = 'prometheus-kube-state-metrics' OR pod_group = 'opentelemetry-demo-otelcol' OR pod_group = 'opentelemetry-demo-prometheus-server' OR pod_group = 'opentelemetry-demo-quoteservice' OR pod_group = 'opentelemetry-demo-frontend') AND signal_source IN (0) AND time>=1705643483 AND time<=1705644383 GROUP BY `time_$__interval`, l7_protocol SLIMIT 20 LIMIT 10000"
    }
   ]
  },
  { "title": "HTTP 分析", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "请求速率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"vtap_app_port\",\"select\":[{\"key\":\"request\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"f5f2a3ae-3099-6b99-005e-8d4562018121\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"PerSecond\"}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"PerSecond\"}]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c16deb2d-fe3c-69ff-01a5-8859e7dfaa51\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"228def66-88ae-f295-d0a2-2e0b9d572442\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c6bd3e65-dc5d-ed9d-d055-048ec27992b3\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"709938cd-ad05-29dc-eee5-193ecdd091b8\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"HTTP\",\"value\":20}],\"as\":\"\",\"params\":[],\"uuid\":\"1b5ac5be-aa36-30e2-5897-a62d554a1dac\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"aada975e-91ae-bca0-7e1f-5cbf53ab7e9c\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a08841f1-af76-acdb-39d3-8d3a791c024e\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"76bcc3ff-77ec-d32d-ed6a-391651b993b2\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"slimit\":\"\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service}\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "PerSecond(Avg(request))", "name": "PerSecond(Avg(request))", "type": 1, "unit": "/s" }
     ],
     "returnTags": [
      {
       "displayName": "time_60",
       "isResource": false,
       "name": "`time_60`"
      },
      {
       "displayName": "节点类型",
       "isResource": false,
       "name": "`node_type`"
      },
      {
       "displayName": "图标",
       "isResource": false,
       "name": "`icon_id`"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": false,
       "name": "auto_service_id"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": false,
       "name": "auto_service"
      }
     ],
     "sql": "SELECT PerSecond(Avg(`request`)) AS `PerSecond(Avg(request))`, time(time, 60) AS `time_60`, node_type(auto_service) AS `node_type`, icon_id(auto_service) AS `icon_id`, auto_service_id, auto_service FROM vtap_app_port WHERE pod_cluster = 'k8s-d-rUL3jSx3ft' AND (pod_ns = 'openebs' OR pod_ns = 'ingress' OR pod_ns = 'deepflow' OR pod_ns = 'default' OR pod_ns = 'monitoring' OR pod_ns = 'kube-system' OR pod_ns = 'otel-demo' OR pod_ns = 'istio-system' OR pod_ns = 'open-telemetry' OR pod_ns = 'deepflow-otel-grpc-demo' OR pod_ns = 'deepflow-prometheus-demo' OR pod_ns = 'deepflow-ebpf-istio-demo' OR pod_ns = 'deepflow-telegraf-demo' OR pod_ns = 'deepflow-otel-dubbo-demo' OR pod_ns = 'deepflow-spring-part-demo' OR pod_ns = 'deepflow-ebpf-spring-demo' OR pod_ns = 'deepflow-otel-skywalking-demo' OR pod_ns = 'deepflow-spring-full-demo' OR pod_ns = 'deepflow-otel-spring-demo') AND (pod_group = 'telegraf' OR pod_group = 'influxdb' OR pod_group = 'svc-item' OR pod_group = 'svc-user' OR pod_group = 'foo-svc' OR pod_group = 'coredns' OR pod_group = 'promtail' OR pod_group = 'web-shop' OR pod_group = 'istiod' OR pod_group = 'bar-svc' OR pod_group = 'frontend' OR pod_group = 'nacos' OR pod_group = 'loo-svc' OR pod_group = 'db-demo' OR pod_group = 'reviews-v2' OR pod_group = 'deepflow-mysql' OR pod_group = 'emailservice' OR pod_group = 'dns-autoscaler' OR pod_group = 'deepflow-grafana' OR pod_group = 'deepflow-server' OR pod_group = 'loadgenerator' OR pod_group = 'reviews-v1' OR pod_group = 'adservice' OR pod_group = 'ratings-v1' OR pod_group = 'deepflow-agent' OR pod_group = 'checkoutservice' OR pod_group = 'paymentservice' OR pod_group = 'redis-cart' OR pod_group = 'deepflow-app' OR pod_group = 'cartservice' OR pod_group = 'shippingservice' OR pod_group = 'loo-svc-full' OR pod_group = 'otel-agent' OR pod_group = 'bar-svc-full' OR pod_group = 'reviews-v3' OR pod_group = 'currencyservice' OR pod_group = 'svc-stock' OR pod_group = 'foo-svc-part' OR pod_group = 'loadgenerator-ng' OR pod_group = 'prometheus-k8s' OR pod_group = 'redis-master' OR pod_group = 'svc-order' OR pod_group = 'foo-svc-full' OR pod_group = 'bar-svc-part' OR pod_group = 'details-v1' OR pod_group = 'loo-svc-part' OR pod_group = 'productpage-v1' OR pod_group = 'opentelemetry-demo-redis' OR pod_group = 'productcatalogservice' OR pod_group = 'prometheus-operator' OR pod_group = 'prometheus-adapter' OR pod_group = 'opentelemetry-demo-kafka' OR pod_group = 'alertmanager-main' OR pod_group = 'openebs-ndm-operator' OR pod_group = 'prometheus-alertmanager' OR pod_group = 'deepflow-clickhouse' OR pod_group = 'istio-ingressgateway' OR pod_group = 'recommendationservice' OR pod_group = 'prometheus-server' OR pod_group = 'prometheus-pushgateway' OR pod_group = 'istio-egressgateway' OR pod_group = 'openebs-ndm-node-exporter' OR pod_group = 'opentelemetry-demo-emailservice' OR pod_group = 'opentelemetry-demo-frauddetectionservice' OR pod_group = 'opentelemetry-demo-paymentservice' OR pod_group = 'opentelemetry-demo-jaeger' OR pod_group = 'opentelemetry-demo-currencyservice' OR pod_group = 'opentelemetry-demo-cartservice' OR pod_group = 'opentelemetry-demo-productcatalogservice' OR pod_group = 'opentelemetry-demo-shippingservice' OR pod_group = 'openebs-localpv-provisioner' OR pod_group = 'demo-ingress-nginx-ingress' OR pod_group = 'opentelemetry-demo-ffspostgres' OR pod_group = 'opentelemetry-demo-accountingservice' OR pod_group = 'opentelemetry-demo-featureflagservice' OR pod_group = 'opentelemetry-demo-loadgenerator' OR pod_group = 'openebs-ndm-cluster-exporter' OR pod_group = 'opentelemetry-demo-recommendationservice' OR pod_group = 'opentelemetry-demo-adservice' OR pod_group = 'opentelemetry-demo-checkoutservice' OR pod_group = 'prometheus-kube-state-metrics' OR pod_group = 'opentelemetry-demo-otelcol' OR pod_group = 'opentelemetry-demo-prometheus-server' OR pod_group = 'opentelemetry-demo-quoteservice' OR pod_group = 'opentelemetry-demo-frontend') AND signal_source IN (0) AND l7_protocol IN (20) AND time>=1705643483 AND time<=1705644383 GROUP BY `time_60`, auto_service, auto_service_id, `node_type` SLIMIT 20 LIMIT 10000"
    }
   ]
  },
  {
   "title": "响应状态码",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"key\":\"row\",\"func\":\"Count\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"10d8b60a-1de1-988f-a51c-1c4b17725f9b\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Count\",\"params\":[]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"67960c68-e196-a1af-3ac5-3359ca52fd47\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"09c10f4a-20fe-0f38-eda6-15fdadb896cc\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"80eb2f1a-89e8-c618-87ac-d0c6f932b512\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"27ceb8c4-7342-3cbf-be44-52cf50b9896f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_code\",\"func\":\"\",\"op\":\"NOT IN\",\"val\":[{\"value\":\"0\",\"label\":\"0\"},{\"value\":\"200\",\"label\":\"200\"}],\"as\":\"\",\"params\":[],\"uuid\":\"dd0d6077-7928-13e8-d0da-7a75dbcf6315\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"HTTP\",\"value\":20}],\"as\":\"\",\"params\":[],\"uuid\":\"ef54dabf-06d7-550a-4a45-8154fdc28666\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5bb248b1-1428-1cbc-6a49-4704e67ca9cb\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"response_code\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6667be37-2d7f-76d3-9be6-4a86bc6c7a90\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"18e8c440-535f-63b1-0165-7724354bf20e\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"slimit\":\"\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "Count(row)", "name": "Count(row)", "type": 8, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "time_$__interval",
       "isResource": false,
       "name": "`time_$__interval`"
      },
      {
       "displayName": "Response Code",
       "isResource": false,
       "name": "response_code"
      }
     ],
     "sql": "SELECT Count(`row`) AS `Count(row)`, time(time, $__interval) AS `time_$__interval`, response_code FROM l7_flow_log WHERE (pod_cluster_0 = 'k8s-d-rUL3jSx3ft' OR pod_cluster_1 = 'k8s-d-rUL3jSx3ft') AND (pod_ns_0 = 'openebs' OR pod_ns_0 = 'ingress' OR pod_ns_0 = 'deepflow' OR pod_ns_0 = 'default' OR pod_ns_0 = 'monitoring' OR pod_ns_0 = 'kube-system' OR pod_ns_0 = 'otel-demo' OR pod_ns_0 = 'istio-system' OR pod_ns_0 = 'open-telemetry' OR pod_ns_0 = 'deepflow-otel-grpc-demo' OR pod_ns_0 = 'deepflow-prometheus-demo' OR pod_ns_0 = 'deepflow-ebpf-istio-demo' OR pod_ns_0 = 'deepflow-telegraf-demo' OR pod_ns_0 = 'deepflow-otel-dubbo-demo' OR pod_ns_0 = 'deepflow-spring-part-demo' OR pod_ns_0 = 'deepflow-ebpf-spring-demo' OR pod_ns_0 = 'deepflow-otel-skywalking-demo' OR pod_ns_0 = 'deepflow-spring-full-demo' OR pod_ns_0 = 'deepflow-otel-spring-demo' OR pod_ns_1 = 'openebs' OR pod_ns_1 = 'ingress' OR pod_ns_1 = 'deepflow' OR pod_ns_1 = 'default' OR pod_ns_1 = 'monitoring' OR pod_ns_1 = 'kube-system' OR pod_ns_1 = 'otel-demo' OR pod_ns_1 = 'istio-system' OR pod_ns_1 = 'open-telemetry' OR pod_ns_1 = 'deepflow-otel-grpc-demo' OR pod_ns_1 = 'deepflow-prometheus-demo' OR pod_ns_1 = 'deepflow-ebpf-istio-demo' OR pod_ns_1 = 'deepflow-telegraf-demo' OR pod_ns_1 = 'deepflow-otel-dubbo-demo' OR pod_ns_1 = 'deepflow-spring-part-demo' OR pod_ns_1 = 'deepflow-ebpf-spring-demo' OR pod_ns_1 = 'deepflow-otel-skywalking-demo' OR pod_ns_1 = 'deepflow-spring-full-demo' OR pod_ns_1 = 'deepflow-otel-spring-demo') AND (pod_group_0 = 'telegraf' OR pod_group_0 = 'influxdb' OR pod_group_0 = 'svc-item' OR pod_group_0 = 'svc-user' OR pod_group_0 = 'foo-svc' OR pod_group_0 = 'coredns' OR pod_group_0 = 'promtail' OR pod_group_0 = 'web-shop' OR pod_group_0 = 'istiod' OR pod_group_0 = 'bar-svc' OR pod_group_0 = 'frontend' OR pod_group_0 = 'nacos' OR pod_group_0 = 'loo-svc' OR pod_group_0 = 'db-demo' OR pod_group_0 = 'reviews-v2' OR pod_group_0 = 'deepflow-mysql' OR pod_group_0 = 'emailservice' OR pod_group_0 = 'dns-autoscaler' OR pod_group_0 = 'deepflow-grafana' OR pod_group_0 = 'deepflow-server' OR pod_group_0 = 'loadgenerator' OR pod_group_0 = 'reviews-v1' OR pod_group_0 = 'adservice' OR pod_group_0 = 'ratings-v1' OR pod_group_0 = 'deepflow-agent' OR pod_group_0 = 'checkoutservice' OR pod_group_0 = 'paymentservice' OR pod_group_0 = 'redis-cart' OR pod_group_0 = 'deepflow-app' OR pod_group_0 = 'cartservice' OR pod_group_0 = 'shippingservice' OR pod_group_0 = 'loo-svc-full' OR pod_group_0 = 'otel-agent' OR pod_group_0 = 'bar-svc-full' OR pod_group_0 = 'reviews-v3' OR pod_group_0 = 'currencyservice' OR pod_group_0 = 'svc-stock' OR pod_group_0 = 'foo-svc-part' OR pod_group_0 = 'loadgenerator-ng' OR pod_group_0 = 'prometheus-k8s' OR pod_group_0 = 'redis-master' OR pod_group_0 = 'svc-order' OR pod_group_0 = 'foo-svc-full' OR pod_group_0 = 'bar-svc-part' OR pod_group_0 = 'details-v1' OR pod_group_0 = 'loo-svc-part' OR pod_group_0 = 'productpage-v1' OR pod_group_0 = 'opentelemetry-demo-redis' OR pod_group_0 = 'productcatalogservice' OR pod_group_0 = 'prometheus-operator' OR pod_group_0 = 'prometheus-adapter' OR pod_group_0 = 'opentelemetry-demo-kafka' OR pod_group_0 = 'alertmanager-main' OR pod_group_0 = 'openebs-ndm-operator' OR pod_group_0 = 'prometheus-alertmanager' OR pod_group_0 = 'deepflow-clickhouse' OR pod_group_0 = 'istio-ingressgateway' OR pod_group_0 = 'recommendationservice' OR pod_group_0 = 'prometheus-server' OR pod_group_0 = 'prometheus-pushgateway' OR pod_group_0 = 'istio-egressgateway' OR pod_group_0 = 'openebs-ndm-node-exporter' OR pod_group_0 = 'opentelemetry-demo-emailservice' OR pod_group_0 = 'opentelemetry-demo-frauddetectionservice' OR pod_group_0 = 'opentelemetry-demo-paymentservice' OR pod_group_0 = 'opentelemetry-demo-jaeger' OR pod_group_0 = 'opentelemetry-demo-currencyservice' OR pod_group_0 = 'opentelemetry-demo-cartservice' OR pod_group_0 = 'opentelemetry-demo-productcatalogservice' OR pod_group_0 = 'opentelemetry-demo-shippingservice' OR pod_group_0 = 'openebs-localpv-provisioner' OR pod_group_0 = 'demo-ingress-nginx-ingress' OR pod_group_0 = 'opentelemetry-demo-ffspostgres' OR pod_group_0 = 'opentelemetry-demo-accountingservice' OR pod_group_0 = 'opentelemetry-demo-featureflagservice' OR pod_group_0 = 'opentelemetry-demo-loadgenerator' OR pod_group_0 = 'openebs-ndm-cluster-exporter' OR pod_group_0 = 'opentelemetry-demo-recommendationservice' OR pod_group_0 = 'opentelemetry-demo-adservice' OR pod_group_0 = 'opentelemetry-demo-checkoutservice' OR pod_group_0 = 'prometheus-kube-state-metrics' OR pod_group_0 = 'opentelemetry-demo-otelcol' OR pod_group_0 = 'opentelemetry-demo-prometheus-server' OR pod_group_0 = 'opentelemetry-demo-quoteservice' OR pod_group_0 = 'opentelemetry-demo-frontend' OR pod_group_1 = 'telegraf' OR pod_group_1 = 'influxdb' OR pod_group_1 = 'svc-item' OR pod_group_1 = 'svc-user' OR pod_group_1 = 'foo-svc' OR pod_group_1 = 'coredns' OR pod_group_1 = 'promtail' OR pod_group_1 = 'web-shop' OR pod_group_1 = 'istiod' OR pod_group_1 = 'bar-svc' OR pod_group_1 = 'frontend' OR pod_group_1 = 'nacos' OR pod_group_1 = 'loo-svc' OR pod_group_1 = 'db-demo' OR pod_group_1 = 'reviews-v2' OR pod_group_1 = 'deepflow-mysql' OR pod_group_1 = 'emailservice' OR pod_group_1 = 'dns-autoscaler' OR pod_group_1 = 'deepflow-grafana' OR pod_group_1 = 'deepflow-server' OR pod_group_1 = 'loadgenerator' OR pod_group_1 = 'reviews-v1' OR pod_group_1 = 'adservice' OR pod_group_1 = 'ratings-v1' OR pod_group_1 = 'deepflow-agent' OR pod_group_1 = 'checkoutservice' OR pod_group_1 = 'paymentservice' OR pod_group_1 = 'redis-cart' OR pod_group_1 = 'deepflow-app' OR pod_group_1 = 'cartservice' OR pod_group_1 = 'shippingservice' OR pod_group_1 = 'loo-svc-full' OR pod_group_1 = 'otel-agent' OR pod_group_1 = 'bar-svc-full' OR pod_group_1 = 'reviews-v3' OR pod_group_1 = 'currencyservice' OR pod_group_1 = 'svc-stock' OR pod_group_1 = 'foo-svc-part' OR pod_group_1 = 'loadgenerator-ng' OR pod_group_1 = 'prometheus-k8s' OR pod_group_1 = 'redis-master' OR pod_group_1 = 'svc-order' OR pod_group_1 = 'foo-svc-full' OR pod_group_1 = 'bar-svc-part' OR pod_group_1 = 'details-v1' OR pod_group_1 = 'loo-svc-part' OR pod_group_1 = 'productpage-v1' OR pod_group_1 = 'opentelemetry-demo-redis' OR pod_group_1 = 'productcatalogservice' OR pod_group_1 = 'prometheus-operator' OR pod_group_1 = 'prometheus-adapter' OR pod_group_1 = 'opentelemetry-demo-kafka' OR pod_group_1 = 'alertmanager-main' OR pod_group_1 = 'openebs-ndm-operator' OR pod_group_1 = 'prometheus-alertmanager' OR pod_group_1 = 'deepflow-clickhouse' OR pod_group_1 = 'istio-ingressgateway' OR pod_group_1 = 'recommendationservice' OR pod_group_1 = 'prometheus-server' OR pod_group_1 = 'prometheus-pushgateway' OR pod_group_1 = 'istio-egressgateway' OR pod_group_1 = 'openebs-ndm-node-exporter' OR pod_group_1 = 'opentelemetry-demo-emailservice' OR pod_group_1 = 'opentelemetry-demo-frauddetectionservice' OR pod_group_1 = 'opentelemetry-demo-paymentservice' OR pod_group_1 = 'opentelemetry-demo-jaeger' OR pod_group_1 = 'opentelemetry-demo-currencyservice' OR pod_group_1 = 'opentelemetry-demo-cartservice' OR pod_group_1 = 'opentelemetry-demo-productcatalogservice' OR pod_group_1 = 'opentelemetry-demo-shippingservice' OR pod_group_1 = 'openebs-localpv-provisioner' OR pod_group_1 = 'demo-ingress-nginx-ingress' OR pod_group_1 = 'opentelemetry-demo-ffspostgres' OR pod_group_1 = 'opentelemetry-demo-accountingservice' OR pod_group_1 = 'opentelemetry-demo-featureflagservice' OR pod_group_1 = 'opentelemetry-demo-loadgenerator' OR pod_group_1 = 'openebs-ndm-cluster-exporter' OR pod_group_1 = 'opentelemetry-demo-recommendationservice' OR pod_group_1 = 'opentelemetry-demo-adservice' OR pod_group_1 = 'opentelemetry-demo-checkoutservice' OR pod_group_1 = 'prometheus-kube-state-metrics' OR pod_group_1 = 'opentelemetry-demo-otelcol' OR pod_group_1 = 'opentelemetry-demo-prometheus-server' OR pod_group_1 = 'opentelemetry-demo-quoteservice' OR pod_group_1 = 'opentelemetry-demo-frontend') AND signal_source IN (0) AND response_code NOT IN (0,200) AND l7_protocol IN (20) AND time>=1705643483 AND time<=1705644383 GROUP BY `time_$__interval`, response_code SLIMIT 20 LIMIT 10000"
    }
   ]
  },
  {
   "title": "响应时延",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"vtap_app_port\",\"select\":[{\"key\":\"rrt_max\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"平均时延\",\"params\":[],\"uuid\":\"f5f2a3ae-3099-6b99-005e-8d4562018121\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[]}},{\"type\":\"metric\",\"key\":\"rrt_max\",\"func\":\"Percentile\",\"op\":\"\",\"val\":\"\",\"as\":\"P90 时延\",\"params\":[\"90\"],\"uuid\":\"2e5e787f-9cd1-53a1-55c5-7885747e7fe3\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Percentile\",\"params\":[\"90\"]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c16deb2d-fe3c-69ff-01a5-8859e7dfaa51\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"228def66-88ae-f295-d0a2-2e0b9d572442\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c6bd3e65-dc5d-ed9d-d055-048ec27992b3\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"709938cd-ad05-29dc-eee5-193ecdd091b8\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"HTTP\",\"value\":20}],\"as\":\"\",\"params\":[],\"uuid\":\"1b5ac5be-aa36-30e2-5897-a62d554a1dac\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"28f76a78-3d7c-5a62-a764-478cc4343b6c\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a08841f1-af76-acdb-39d3-8d3a791c024e\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"76bcc3ff-77ec-d32d-ed6a-391651b993b2\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"slimit\":\"\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service}\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "平均时延", "name": "平均时延", "type": 3, "unit": "us" },
      { "displayName": "P90 时延", "name": "P90 时延", "type": 3, "unit": "us" }
     ],
     "returnTags": [
      {
       "displayName": "time_60",
       "isResource": false,
       "name": "`time_60`"
      },
      {
       "displayName": "节点类型",
       "isResource": false,
       "name": "`node_type`"
      },
      {
       "displayName": "图标",
       "isResource": false,
       "name": "`icon_id`"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": false,
       "name": "auto_service_id"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": false,
       "name": "auto_service"
      }
     ],
     "sql": "SELECT Avg(`rrt_max`) AS `平均时延`, Percentile(`rrt_max`,0.9) AS `P90 时延`, time(time, 60) AS `time_60`, node_type(auto_service) AS `node_type`, icon_id(auto_service) AS `icon_id`, auto_service_id, auto_service FROM vtap_app_port WHERE pod_cluster = 'k8s-d-rUL3jSx3ft' AND (pod_ns = 'openebs' OR pod_ns = 'ingress' OR pod_ns = 'deepflow' OR pod_ns = 'default' OR pod_ns = 'monitoring' OR pod_ns = 'kube-system' OR pod_ns = 'otel-demo' OR pod_ns = 'istio-system' OR pod_ns = 'open-telemetry' OR pod_ns = 'deepflow-otel-grpc-demo' OR pod_ns = 'deepflow-prometheus-demo' OR pod_ns = 'deepflow-ebpf-istio-demo' OR pod_ns = 'deepflow-telegraf-demo' OR pod_ns = 'deepflow-otel-dubbo-demo' OR pod_ns = 'deepflow-spring-part-demo' OR pod_ns = 'deepflow-ebpf-spring-demo' OR pod_ns = 'deepflow-otel-skywalking-demo' OR pod_ns = 'deepflow-spring-full-demo' OR pod_ns = 'deepflow-otel-spring-demo') AND (pod_group = 'telegraf' OR pod_group = 'influxdb' OR pod_group = 'svc-item' OR pod_group = 'svc-user' OR pod_group = 'foo-svc' OR pod_group = 'coredns' OR pod_group = 'promtail' OR pod_group = 'web-shop' OR pod_group = 'istiod' OR pod_group = 'bar-svc' OR pod_group = 'frontend' OR pod_group = 'nacos' OR pod_group = 'loo-svc' OR pod_group = 'db-demo' OR pod_group = 'reviews-v2' OR pod_group = 'deepflow-mysql' OR pod_group = 'emailservice' OR pod_group = 'dns-autoscaler' OR pod_group = 'deepflow-grafana' OR pod_group = 'deepflow-server' OR pod_group = 'loadgenerator' OR pod_group = 'reviews-v1' OR pod_group = 'adservice' OR pod_group = 'ratings-v1' OR pod_group = 'deepflow-agent' OR pod_group = 'checkoutservice' OR pod_group = 'paymentservice' OR pod_group = 'redis-cart' OR pod_group = 'deepflow-app' OR pod_group = 'cartservice' OR pod_group = 'shippingservice' OR pod_group = 'loo-svc-full' OR pod_group = 'otel-agent' OR pod_group = 'bar-svc-full' OR pod_group = 'reviews-v3' OR pod_group = 'currencyservice' OR pod_group = 'svc-stock' OR pod_group = 'foo-svc-part' OR pod_group = 'loadgenerator-ng' OR pod_group = 'prometheus-k8s' OR pod_group = 'redis-master' OR pod_group = 'svc-order' OR pod_group = 'foo-svc-full' OR pod_group = 'bar-svc-part' OR pod_group = 'details-v1' OR pod_group = 'loo-svc-part' OR pod_group = 'productpage-v1' OR pod_group = 'opentelemetry-demo-redis' OR pod_group = 'productcatalogservice' OR pod_group = 'prometheus-operator' OR pod_group = 'prometheus-adapter' OR pod_group = 'opentelemetry-demo-kafka' OR pod_group = 'alertmanager-main' OR pod_group = 'openebs-ndm-operator' OR pod_group = 'prometheus-alertmanager' OR pod_group = 'deepflow-clickhouse' OR pod_group = 'istio-ingressgateway' OR pod_group = 'recommendationservice' OR pod_group = 'prometheus-server' OR pod_group = 'prometheus-pushgateway' OR pod_group = 'istio-egressgateway' OR pod_group = 'openebs-ndm-node-exporter' OR pod_group = 'opentelemetry-demo-emailservice' OR pod_group = 'opentelemetry-demo-frauddetectionservice' OR pod_group = 'opentelemetry-demo-paymentservice' OR pod_group = 'opentelemetry-demo-jaeger' OR pod_group = 'opentelemetry-demo-currencyservice' OR pod_group = 'opentelemetry-demo-cartservice' OR pod_group = 'opentelemetry-demo-productcatalogservice' OR pod_group = 'opentelemetry-demo-shippingservice' OR pod_group = 'openebs-localpv-provisioner' OR pod_group = 'demo-ingress-nginx-ingress' OR pod_group = 'opentelemetry-demo-ffspostgres' OR pod_group = 'opentelemetry-demo-accountingservice' OR pod_group = 'opentelemetry-demo-featureflagservice' OR pod_group = 'opentelemetry-demo-loadgenerator' OR pod_group = 'openebs-ndm-cluster-exporter' OR pod_group = 'opentelemetry-demo-recommendationservice' OR pod_group = 'opentelemetry-demo-adservice' OR pod_group = 'opentelemetry-demo-checkoutservice' OR pod_group = 'prometheus-kube-state-metrics' OR pod_group = 'opentelemetry-demo-otelcol' OR pod_group = 'opentelemetry-demo-prometheus-server' OR pod_group = 'opentelemetry-demo-quoteservice' OR pod_group = 'opentelemetry-demo-frontend') AND signal_source IN (0) AND l7_protocol IN (20) AND time>=1705643483 AND time<=1705644383 GROUP BY `time_60`, auto_service, auto_service_id, `node_type` SLIMIT 20 LIMIT 10000"
    }
   ]
  },
  {
   "title": "端点列表",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"vtap_app_edge_port\",\"select\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d4ee9d24-88e5-e61b-3b75-04632c0c4ba7\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"c8855acb-4e4b-aa65-6d08-06c06f546982\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"80754042-4f53-2f98-d3c3-abdd3c8f204b\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"endpoint\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"979afd36-4083-d5b9-3613-5ee1bfb6f57e\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"metric\",\"key\":\"request\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"11ec40a4-9b32-81af-201d-aaedce6364f1\",\"subFuncs\":[{\"func\":\"PerSecond\"}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"PerSecond\"}]}},{\"type\":\"metric\",\"key\":\"client_error_ratio\",\"func\":\"Max\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6588a489-2cd6-04dc-4169-71bddd40a539\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Max\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"server_error_ratio\",\"func\":\"Max\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"b56abf09-c508-a7b7-bdb7-a2744976c56f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Max\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"timeout\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"2791fc39-ea75-a7e9-7569-ced6faae0355\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"rrt_max\",\"func\":\"Percentile\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[\"90\"],\"uuid\":\"0efb5384-eb46-d2ae-b287-f7c96c5630fe\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Percentile\",\"params\":[\"90\"]}},{\"type\":\"metric\",\"key\":\"rrt_max\",\"func\":\"Percentile\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[\"99\"],\"uuid\":\"3f0d79ea-ce45-6d10-3ec6-e7c960234718\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Percentile\",\"params\":[\"99\"]}}],\"where\":[{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"HTTP\",\"value\":20}],\"as\":\"\",\"params\":[],\"uuid\":\"f60b0d0f-7a3c-49cd-21b9-b2de67b4e8eb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"3b93b04e-47b7-25c3-b904-0393087c303a\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"0a98cb3c-74d5-d5c2-0a07-54614b34bb11\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"7c1b859c-4c48-ac6b-7376-76f41457fe26\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"b378b0ac-10aa-b008-94a1-e6410216f9ea\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"3869b380-937a-1292-6872-1071ddfbb546\",\"type\":\"metric\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"14f45d17-ea2b-2b57-65c8-4535191bcf39\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"34e873e9-b6a8-d92c-a287-4921503dfbe9\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"endpoint\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"3fd198d5-0df9-2044-4aad-28eb8a8e330b\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"97895847-de97-b26d-9a4a-8b44c1a36831\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"table\",\"alias\":\"\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "PerSecond(Avg(request))", "name": "PerSecond(Avg(request))", "type": 1, "unit": "/s" },
      { "displayName": "Max(client_error_ratio)", "name": "Max(client_error_ratio)", "type": 4, "unit": "%" },
      { "displayName": "Max(server_error_ratio)", "name": "Max(server_error_ratio)", "type": 4, "unit": "%" },
      { "displayName": "Sum(timeout)", "name": "Sum(timeout)", "type": 1, "unit": "" },
      { "displayName": "Percentile(rrt_max,0.9)", "name": "Percentile(rrt_max,0.9)", "type": 3, "unit": "us" },
      { "displayName": "Percentile(rrt_max,0.99)", "name": "Percentile(rrt_max,0.99)", "type": 3, "unit": "us" }
     ],
     "returnTags": [
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_1",
       "role": "server"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "Enum(l7_protocol)"
      },
      {
       "displayName": "Endpoint",
       "isResource": false,
       "name": "endpoint"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_id_1",
       "role": "server"
      },
      {
       "displayName": "节点类型",
       "isResource": true,
       "name": "`server_node_type`",
       "role": "server"
      },
      {
       "displayName": "图标",
       "isResource": true,
       "name": "`server_icon_id`",
       "role": "server"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "l7_protocol"
      }
     ],
     "sql": "SELECT PerSecond(Avg(`request`)) AS `PerSecond(Avg(request))`, Max(`client_error_ratio`) AS `Max(client_error_ratio)`, Max(`server_error_ratio`) AS `Max(server_error_ratio)`, Sum(`timeout`) AS `Sum(timeout)`, Percentile(`rrt_max`,0.9) AS `Percentile(rrt_max,0.9)`, Percentile(`rrt_max`,0.99) AS `Percentile(rrt_max,0.99)`, auto_service_1, Enum(l7_protocol), endpoint, auto_service_id_1, node_type(auto_service_1) AS `server_node_type`, icon_id(auto_service_1) AS `server_icon_id`, l7_protocol FROM vtap_app_edge_port WHERE l7_protocol IN (20) AND signal_source IN (0) AND (pod_cluster_0 = 'k8s-d-rUL3jSx3ft' OR pod_cluster_1 = 'k8s-d-rUL3jSx3ft') AND (pod_ns_0 = 'otel-demo' OR pod_ns_1 = 'otel-demo') AND (pod_group_0 = 'opentelemetry-demo-redis' OR pod_group_0 = 'opentelemetry-demo-kafka' OR pod_group_0 = 'opentelemetry-demo-emailservice' OR pod_group_0 = 'opentelemetry-demo-frauddetectionservice' OR pod_group_0 = 'opentelemetry-demo-paymentservice' OR pod_group_0 = 'opentelemetry-demo-jaeger' OR pod_group_0 = 'opentelemetry-demo-currencyservice' OR pod_group_0 = 'opentelemetry-demo-cartservice' OR pod_group_0 = 'opentelemetry-demo-productcatalogservice' OR pod_group_0 = 'opentelemetry-demo-shippingservice' OR pod_group_0 = 'opentelemetry-demo-ffspostgres' OR pod_group_0 = 'opentelemetry-demo-accountingservice' OR pod_group_0 = 'opentelemetry-demo-featureflagservice' OR pod_group_0 = 'opentelemetry-demo-loadgenerator' OR pod_group_0 = 'opentelemetry-demo-recommendationservice' OR pod_group_0 = 'opentelemetry-demo-adservice' OR pod_group_0 = 'opentelemetry-demo-checkoutservice' OR pod_group_0 = 'opentelemetry-demo-otelcol' OR pod_group_0 = 'opentelemetry-demo-prometheus-server' OR pod_group_0 = 'opentelemetry-demo-quoteservice' OR pod_group_0 = 'opentelemetry-demo-frontend' OR pod_group_1 = 'opentelemetry-demo-redis' OR pod_group_1 = 'opentelemetry-demo-kafka' OR pod_group_1 = 'opentelemetry-demo-emailservice' OR pod_group_1 = 'opentelemetry-demo-frauddetectionservice' OR pod_group_1 = 'opentelemetry-demo-paymentservice' OR pod_group_1 = 'opentelemetry-demo-jaeger' OR pod_group_1 = 'opentelemetry-demo-currencyservice' OR pod_group_1 = 'opentelemetry-demo-cartservice' OR pod_group_1 = 'opentelemetry-demo-productcatalogservice' OR pod_group_1 = 'opentelemetry-demo-shippingservice' OR pod_group_1 = 'opentelemetry-demo-ffspostgres' OR pod_group_1 = 'opentelemetry-demo-accountingservice' OR pod_group_1 = 'opentelemetry-demo-featureflagservice' OR pod_group_1 = 'opentelemetry-demo-loadgenerator' OR pod_group_1 = 'opentelemetry-demo-recommendationservice' OR pod_group_1 = 'opentelemetry-demo-adservice' OR pod_group_1 = 'opentelemetry-demo-checkoutservice' OR pod_group_1 = 'opentelemetry-demo-otelcol' OR pod_group_1 = 'opentelemetry-demo-prometheus-server' OR pod_group_1 = 'opentelemetry-demo-quoteservice' OR pod_group_1 = 'opentelemetry-demo-frontend') AND time>=1705633705 AND time<=1705635505 GROUP BY auto_service_1, l7_protocol, endpoint, auto_service_id_1, `server_node_type` LIMIT 1000"
    }
   ]
  },
  { "title": "SQL 分析", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "请求速率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"vtap_app_port\",\"select\":[{\"key\":\"request\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"f5f2a3ae-3099-6b99-005e-8d4562018121\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"PerSecond\"}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"PerSecond\"}]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c16deb2d-fe3c-69ff-01a5-8859e7dfaa51\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"228def66-88ae-f295-d0a2-2e0b9d572442\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c6bd3e65-dc5d-ed9d-d055-048ec27992b3\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"709938cd-ad05-29dc-eee5-193ecdd091b8\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"MySQL\",\"value\":60},{\"label\":\"PostgreSQL\",\"value\":61}],\"as\":\"\",\"params\":[],\"uuid\":\"1b5ac5be-aa36-30e2-5897-a62d554a1dac\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"aaa14e01-0681-be3b-31e2-45118407d5aa\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a08841f1-af76-acdb-39d3-8d3a791c024e\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"76bcc3ff-77ec-d32d-ed6a-391651b993b2\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"slimit\":\"\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service}\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "PerSecond(Avg(request))", "name": "PerSecond(Avg(request))", "type": 1, "unit": "/s" }
     ],
     "returnTags": [
      {
       "displayName": "time_60",
       "isResource": false,
       "name": "`time_60`"
      },
      {
       "displayName": "节点类型",
       "isResource": false,
       "name": "`node_type`"
      },
      {
       "displayName": "图标",
       "isResource": false,
       "name": "`icon_id`"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": false,
       "name": "auto_service_id"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": false,
       "name": "auto_service"
      }
     ],
     "sql": "SELECT PerSecond(Avg(`request`)) AS `PerSecond(Avg(request))`, time(time, 60) AS `time_60`, node_type(auto_service) AS `node_type`, icon_id(auto_service) AS `icon_id`, auto_service_id, auto_service FROM vtap_app_port WHERE pod_cluster = 'k8s-d-rUL3jSx3ft' AND pod_ns = 'deepflow-otel-dubbo-demo' AND (pod_group = 'svc-item' OR pod_group = 'svc-user' OR pod_group = 'web-shop' OR pod_group = 'nacos' OR pod_group = 'db-demo' OR pod_group = 'loadgenerator' OR pod_group = 'svc-stock' OR pod_group = 'svc-order') AND signal_source IN (0) AND l7_protocol IN (60,61) AND time>=1705643483 AND time<=1705644383 GROUP BY `time_60`, auto_service, auto_service_id, `node_type` SLIMIT 20 LIMIT 10000"
    }
   ]
  },
  {
   "title": "响应异常比例",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"vtap_app_port\",\"select\":[{\"key\":\"client_error_ratio\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"客户端异常比例\",\"params\":[],\"uuid\":\"f5f2a3ae-3099-6b99-005e-8d4562018121\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[]}},{\"type\":\"metric\",\"key\":\"server_error_ratio\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"服务端异常比例\",\"params\":[],\"uuid\":\"6b76ae17-8910-adc2-137b-c6ba69754190\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c16deb2d-fe3c-69ff-01a5-8859e7dfaa51\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"228def66-88ae-f295-d0a2-2e0b9d572442\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c6bd3e65-dc5d-ed9d-d055-048ec27992b3\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"709938cd-ad05-29dc-eee5-193ecdd091b8\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"MySQL\",\"value\":60},{\"label\":\"PostgreSQL\",\"value\":61}],\"as\":\"\",\"params\":[],\"uuid\":\"1b5ac5be-aa36-30e2-5897-a62d554a1dac\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"cfe0b137-1cce-48d2-6eca-fa145459af23\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a08841f1-af76-acdb-39d3-8d3a791c024e\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"76bcc3ff-77ec-d32d-ed6a-391651b993b2\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"slimit\":\"\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service}\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "客户端异常比例", "name": "客户端异常比例", "type": 4, "unit": "%" },
      { "displayName": "服务端异常比例", "name": "服务端异常比例", "type": 4, "unit": "%" }
     ],
     "returnTags": [
      {
       "displayName": "time_60",
       "isResource": false,
       "name": "`time_60`"
      },
      {
       "displayName": "节点类型",
       "isResource": false,
       "name": "`node_type`"
      },
      {
       "displayName": "图标",
       "isResource": false,
       "name": "`icon_id`"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": false,
       "name": "auto_service_id"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": false,
       "name": "auto_service"
      }
     ],
     "sql": "SELECT Avg(`client_error_ratio`) AS `客户端异常比例`, Avg(`server_error_ratio`) AS `服务端异常比例`, time(time, 60) AS `time_60`, node_type(auto_service) AS `node_type`, icon_id(auto_service) AS `icon_id`, auto_service_id, auto_service FROM vtap_app_port WHERE pod_cluster = 'k8s-d-rUL3jSx3ft' AND (pod_ns = 'openebs' OR pod_ns = 'ingress' OR pod_ns = 'deepflow' OR pod_ns = 'default' OR pod_ns = 'monitoring' OR pod_ns = 'kube-system' OR pod_ns = 'otel-demo' OR pod_ns = 'istio-system' OR pod_ns = 'open-telemetry' OR pod_ns = 'deepflow-otel-grpc-demo' OR pod_ns = 'deepflow-prometheus-demo' OR pod_ns = 'deepflow-ebpf-istio-demo' OR pod_ns = 'deepflow-telegraf-demo' OR pod_ns = 'deepflow-otel-dubbo-demo' OR pod_ns = 'deepflow-spring-part-demo' OR pod_ns = 'deepflow-ebpf-spring-demo' OR pod_ns = 'deepflow-otel-skywalking-demo' OR pod_ns = 'deepflow-spring-full-demo' OR pod_ns = 'deepflow-otel-spring-demo') AND (pod_group = 'telegraf' OR pod_group = 'influxdb' OR pod_group = 'svc-item' OR pod_group = 'svc-user' OR pod_group = 'foo-svc' OR pod_group = 'coredns' OR pod_group = 'promtail' OR pod_group = 'web-shop' OR pod_group = 'istiod' OR pod_group = 'bar-svc' OR pod_group = 'frontend' OR pod_group = 'nacos' OR pod_group = 'loo-svc' OR pod_group = 'db-demo' OR pod_group = 'reviews-v2' OR pod_group = 'deepflow-mysql' OR pod_group = 'emailservice' OR pod_group = 'dns-autoscaler' OR pod_group = 'deepflow-grafana' OR pod_group = 'deepflow-server' OR pod_group = 'loadgenerator' OR pod_group = 'reviews-v1' OR pod_group = 'adservice' OR pod_group = 'ratings-v1' OR pod_group = 'deepflow-agent' OR pod_group = 'checkoutservice' OR pod_group = 'paymentservice' OR pod_group = 'redis-cart' OR pod_group = 'deepflow-app' OR pod_group = 'cartservice' OR pod_group = 'shippingservice' OR pod_group = 'loo-svc-full' OR pod_group = 'otel-agent' OR pod_group = 'bar-svc-full' OR pod_group = 'reviews-v3' OR pod_group = 'currencyservice' OR pod_group = 'svc-stock' OR pod_group = 'foo-svc-part' OR pod_group = 'loadgenerator-ng' OR pod_group = 'prometheus-k8s' OR pod_group = 'redis-master' OR pod_group = 'svc-order' OR pod_group = 'foo-svc-full' OR pod_group = 'bar-svc-part' OR pod_group = 'details-v1' OR pod_group = 'loo-svc-part' OR pod_group = 'productpage-v1' OR pod_group = 'opentelemetry-demo-redis' OR pod_group = 'productcatalogservice' OR pod_group = 'prometheus-operator' OR pod_group = 'prometheus-adapter' OR pod_group = 'opentelemetry-demo-kafka' OR pod_group = 'alertmanager-main' OR pod_group = 'openebs-ndm-operator' OR pod_group = 'prometheus-alertmanager' OR pod_group = 'deepflow-clickhouse' OR pod_group = 'istio-ingressgateway' OR pod_group = 'recommendationservice' OR pod_group = 'prometheus-server' OR pod_group = 'prometheus-pushgateway' OR pod_group = 'istio-egressgateway' OR pod_group = 'openebs-ndm-node-exporter' OR pod_group = 'opentelemetry-demo-emailservice' OR pod_group = 'opentelemetry-demo-frauddetectionservice' OR pod_group = 'opentelemetry-demo-paymentservice' OR pod_group = 'opentelemetry-demo-jaeger' OR pod_group = 'opentelemetry-demo-currencyservice' OR pod_group = 'opentelemetry-demo-cartservice' OR pod_group = 'opentelemetry-demo-productcatalogservice' OR pod_group = 'opentelemetry-demo-shippingservice' OR pod_group = 'openebs-localpv-provisioner' OR pod_group = 'demo-ingress-nginx-ingress' OR pod_group = 'opentelemetry-demo-ffspostgres' OR pod_group = 'opentelemetry-demo-accountingservice' OR pod_group = 'opentelemetry-demo-featureflagservice' OR pod_group = 'opentelemetry-demo-loadgenerator' OR pod_group = 'openebs-ndm-cluster-exporter' OR pod_group = 'opentelemetry-demo-recommendationservice' OR pod_group = 'opentelemetry-demo-adservice' OR pod_group = 'opentelemetry-demo-checkoutservice' OR pod_group = 'prometheus-kube-state-metrics' OR pod_group = 'opentelemetry-demo-otelcol' OR pod_group = 'opentelemetry-demo-prometheus-server' OR pod_group = 'opentelemetry-demo-quoteservice' OR pod_group = 'opentelemetry-demo-frontend') AND signal_source IN (0) AND l7_protocol IN (60,61) AND time>=1705643483 AND time<=1705644383 GROUP BY `time_60`, auto_service, auto_service_id, `node_type` SLIMIT 20 LIMIT 10000"
    }
   ]
  },
  {
   "title": "慢调用速率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"vtap_app_port\",\"select\":[{\"key\":\"rrt_max\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"响应时延\",\"params\":[],\"uuid\":\"f5f2a3ae-3099-6b99-005e-8d4562018121\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c16deb2d-fe3c-69ff-01a5-8859e7dfaa51\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"228def66-88ae-f295-d0a2-2e0b9d572442\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c6bd3e65-dc5d-ed9d-d055-048ec27992b3\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"709938cd-ad05-29dc-eee5-193ecdd091b8\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"MySQL\",\"value\":60},{\"label\":\"PostgreSQL\",\"value\":61}],\"as\":\"\",\"params\":[],\"uuid\":\"1b5ac5be-aa36-30e2-5897-a62d554a1dac\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"23b6b48c-3451-2554-a5b5-c38faadfd379\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a08841f1-af76-acdb-39d3-8d3a791c024e\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"76bcc3ff-77ec-d32d-ed6a-391651b993b2\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"slimit\":\"\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service}\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "响应时延", "name": "响应时延", "type": 3, "unit": "us" }
     ],
     "returnTags": [
      {
       "displayName": "time_60",
       "isResource": false,
       "name": "`time_60`"
      },
      {
       "displayName": "节点类型",
       "isResource": false,
       "name": "`node_type`"
      },
      {
       "displayName": "图标",
       "isResource": false,
       "name": "`icon_id`"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": false,
       "name": "auto_service_id"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": false,
       "name": "auto_service"
      }
     ],
     "sql": "SELECT Avg(`rrt_max`) AS `响应时延`, time(time, 60) AS `time_60`, node_type(auto_service) AS `node_type`, icon_id(auto_service) AS `icon_id`, auto_service_id, auto_service FROM vtap_app_port WHERE pod_cluster = 'k8s-d-rUL3jSx3ft' AND pod_ns = 'istio-system' AND (pod_group = 'istiod' OR pod_group = 'istio-ingressgateway' OR pod_group = 'istio-egressgateway') AND signal_source IN (0) AND l7_protocol IN (60,61) AND time>=1705643483 AND time<=1705644383 GROUP BY `time_60`, auto_service, auto_service_id, `node_type` SLIMIT 20 LIMIT 10000"
    }
   ]
  },
  {
   "title": "异常调用列表",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"10d8b60a-1de1-988f-a51c-1c4b17725f9b\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"request_resource\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"e7ae1e8a-a849-ea49-ddd6-1c926bec135d\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"07410918-91a7-9c4c-b094-8db2725c6249\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_exception\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a5631f4b-1188-1ae0-320c-607aa6351b2f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_status\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"241c6823-11d6-fab6-0551-b31c02666195\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"metric\",\"key\":\"log_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"31e943e6-1457-4032-cfb6-19c465f38e02\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"67960c68-e196-a1af-3ac5-3359ca52fd47\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"896b7702-0835-e747-19a5-01aea4d318c9\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"5edc41c5-c911-8034-04c2-e5f4338826a2\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"9c1d9631-4ff0-86cd-65bd-b5bf94e4f657\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"MySQL\",\"value\":60},{\"label\":\"PostgreSQL\",\"value\":61}],\"as\":\"\",\"params\":[],\"uuid\":\"fb2baf2f-bbc5-1fe8-8ab1-23f88b59b50c\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_status\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Server Error\",\"value\":3},{\"label\":\"Client Error\",\"value\":4},{\"label\":\"Unknown\",\"value\":2}],\"as\":\"\",\"params\":[],\"uuid\":\"269cd391-f60a-4560-bfd2-ad9a165a7aa4\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d9aed00c-bfe2-0b8d-faaf-b03dd2e3377d\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6667be37-2d7f-76d3-9be6-4a86bc6c7a90\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"request_resource\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5172d18d-d965-4c59-3390-b5fc79d62e03\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_status\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"bbb7eb60-1a99-f77c-42c7-99d9740c7614\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_exception\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5af2fef0-7171-4512-5578-73c2c4f091d1\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"55db6e28-2419-a6ed-c51f-f0de5e82ca43\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"18e8c440-535f-63b1-0165-7724354bf20e\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"table\",\"alias\":\"\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "Sum(log_count)", "name": "Sum(log_count)", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_1",
       "role": "server"
      },
      {
       "displayName": "Request Resource",
       "isResource": false,
       "name": "request_resource"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "Enum(l7_protocol)"
      },
      {
       "displayName": "Response Exception",
       "isResource": false,
       "name": "response_exception"
      },
      {
       "displayName": "Response Status",
       "isResource": false,
       "name": "Enum(response_status)"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_id_1",
       "role": "server"
      },
      {
       "displayName": "节点类型",
       "isResource": true,
       "name": "`server_node_type`",
       "role": "server"
      },
      {
       "displayName": "图标",
       "isResource": true,
       "name": "`server_icon_id`",
       "role": "server"
      },
      {
       "displayName": "Response Status",
       "isResource": false,
       "name": "response_status"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "l7_protocol"
      }
     ],
     "sql": "SELECT Sum(`log_count`) AS `Sum(log_count)`, auto_service_1, request_resource, Enum(l7_protocol), response_exception, Enum(response_status), auto_service_id_1, node_type(auto_service_1) AS `server_node_type`, icon_id(auto_service_1) AS `server_icon_id`, response_status, l7_protocol FROM l7_flow_log WHERE (pod_cluster_0 = 'k8s-d-rUL3jSx3ft' OR pod_cluster_1 = 'k8s-d-rUL3jSx3ft') AND (pod_ns_0 = 'openebs' OR pod_ns_0 = 'ingress' OR pod_ns_0 = 'deepflow' OR pod_ns_0 = 'default' OR pod_ns_0 = 'monitoring' OR pod_ns_0 = 'kube-system' OR pod_ns_0 = 'otel-demo' OR pod_ns_0 = 'istio-system' OR pod_ns_0 = 'open-telemetry' OR pod_ns_0 = 'deepflow-otel-grpc-demo' OR pod_ns_0 = 'deepflow-prometheus-demo' OR pod_ns_0 = 'deepflow-ebpf-istio-demo' OR pod_ns_0 = 'deepflow-telegraf-demo' OR pod_ns_0 = 'deepflow-otel-dubbo-demo' OR pod_ns_0 = 'deepflow-spring-part-demo' OR pod_ns_0 = 'deepflow-ebpf-spring-demo' OR pod_ns_0 = 'deepflow-otel-skywalking-demo' OR pod_ns_0 = 'deepflow-spring-full-demo' OR pod_ns_0 = 'deepflow-otel-spring-demo' OR pod_ns_1 = 'openebs' OR pod_ns_1 = 'ingress' OR pod_ns_1 = 'deepflow' OR pod_ns_1 = 'default' OR pod_ns_1 = 'monitoring' OR pod_ns_1 = 'kube-system' OR pod_ns_1 = 'otel-demo' OR pod_ns_1 = 'istio-system' OR pod_ns_1 = 'open-telemetry' OR pod_ns_1 = 'deepflow-otel-grpc-demo' OR pod_ns_1 = 'deepflow-prometheus-demo' OR pod_ns_1 = 'deepflow-ebpf-istio-demo' OR pod_ns_1 = 'deepflow-telegraf-demo' OR pod_ns_1 = 'deepflow-otel-dubbo-demo' OR pod_ns_1 = 'deepflow-spring-part-demo' OR pod_ns_1 = 'deepflow-ebpf-spring-demo' OR pod_ns_1 = 'deepflow-otel-skywalking-demo' OR pod_ns_1 = 'deepflow-spring-full-demo' OR pod_ns_1 = 'deepflow-otel-spring-demo') AND (pod_group_0 = 'telegraf' OR pod_group_0 = 'influxdb' OR pod_group_0 = 'svc-item' OR pod_group_0 = 'svc-user' OR pod_group_0 = 'foo-svc' OR pod_group_0 = 'coredns' OR pod_group_0 = 'promtail' OR pod_group_0 = 'web-shop' OR pod_group_0 = 'istiod' OR pod_group_0 = 'bar-svc' OR pod_group_0 = 'frontend' OR pod_group_0 = 'nacos' OR pod_group_0 = 'loo-svc' OR pod_group_0 = 'db-demo' OR pod_group_0 = 'reviews-v2' OR pod_group_0 = 'deepflow-mysql' OR pod_group_0 = 'emailservice' OR pod_group_0 = 'dns-autoscaler' OR pod_group_0 = 'deepflow-grafana' OR pod_group_0 = 'deepflow-server' OR pod_group_0 = 'loadgenerator' OR pod_group_0 = 'reviews-v1' OR pod_group_0 = 'adservice' OR pod_group_0 = 'ratings-v1' OR pod_group_0 = 'deepflow-agent' OR pod_group_0 = 'checkoutservice' OR pod_group_0 = 'paymentservice' OR pod_group_0 = 'redis-cart' OR pod_group_0 = 'deepflow-app' OR pod_group_0 = 'cartservice' OR pod_group_0 = 'shippingservice' OR pod_group_0 = 'otel-agent' OR pod_group_0 = 'loo-svc-full' OR pod_group_0 = 'bar-svc-full' OR pod_group_0 = 'reviews-v3' OR pod_group_0 = 'currencyservice' OR pod_group_0 = 'svc-stock' OR pod_group_0 = 'foo-svc-part' OR pod_group_0 = 'loadgenerator-ng' OR pod_group_0 = 'prometheus-k8s' OR pod_group_0 = 'redis-master' OR pod_group_0 = 'svc-order' OR pod_group_0 = 'foo-svc-full' OR pod_group_0 = 'bar-svc-part' OR pod_group_0 = 'details-v1' OR pod_group_0 = 'loo-svc-part' OR pod_group_0 = 'productpage-v1' OR pod_group_0 = 'opentelemetry-demo-redis' OR pod_group_0 = 'productcatalogservice' OR pod_group_0 = 'prometheus-operator' OR pod_group_0 = 'prometheus-adapter' OR pod_group_0 = 'opentelemetry-demo-kafka' OR pod_group_0 = 'alertmanager-main' OR pod_group_0 = 'openebs-ndm-operator' OR pod_group_0 = 'prometheus-alertmanager' OR pod_group_0 = 'deepflow-clickhouse' OR pod_group_0 = 'istio-ingressgateway' OR pod_group_0 = 'recommendationservice' OR pod_group_0 = 'prometheus-server' OR pod_group_0 = 'prometheus-pushgateway' OR pod_group_0 = 'istio-egressgateway' OR pod_group_0 = 'openebs-ndm-node-exporter' OR pod_group_0 = 'opentelemetry-demo-emailservice' OR pod_group_0 = 'opentelemetry-demo-frauddetectionservice' OR pod_group_0 = 'opentelemetry-demo-paymentservice' OR pod_group_0 = 'opentelemetry-demo-jaeger' OR pod_group_0 = 'opentelemetry-demo-currencyservice' OR pod_group_0 = 'opentelemetry-demo-cartservice' OR pod_group_0 = 'opentelemetry-demo-productcatalogservice' OR pod_group_0 = 'opentelemetry-demo-shippingservice' OR pod_group_0 = 'openebs-localpv-provisioner' OR pod_group_0 = 'demo-ingress-nginx-ingress' OR pod_group_0 = 'opentelemetry-demo-ffspostgres' OR pod_group_0 = 'opentelemetry-demo-accountingservice' OR pod_group_0 = 'opentelemetry-demo-frontendproxy' OR pod_group_0 = 'opentelemetry-demo-featureflagservice' OR pod_group_0 = 'opentelemetry-demo-loadgenerator' OR pod_group_0 = 'openebs-ndm-cluster-exporter' OR pod_group_0 = 'opentelemetry-demo-recommendationservice' OR pod_group_0 = 'opentelemetry-demo-adservice' OR pod_group_0 = 'opentelemetry-demo-checkoutservice' OR pod_group_0 = 'prometheus-kube-state-metrics' OR pod_group_0 = 'opentelemetry-demo-otelcol' OR pod_group_0 = 'opentelemetry-demo-prometheus-server' OR pod_group_0 = 'opentelemetry-demo-quoteservice' OR pod_group_0 = 'opentelemetry-demo-frontend' OR pod_group_1 = 'telegraf' OR pod_group_1 = 'influxdb' OR pod_group_1 = 'svc-item' OR pod_group_1 = 'svc-user' OR pod_group_1 = 'foo-svc' OR pod_group_1 = 'coredns' OR pod_group_1 = 'promtail' OR pod_group_1 = 'web-shop' OR pod_group_1 = 'istiod' OR pod_group_1 = 'bar-svc' OR pod_group_1 = 'frontend' OR pod_group_1 = 'nacos' OR pod_group_1 = 'loo-svc' OR pod_group_1 = 'db-demo' OR pod_group_1 = 'reviews-v2' OR pod_group_1 = 'deepflow-mysql' OR pod_group_1 = 'emailservice' OR pod_group_1 = 'dns-autoscaler' OR pod_group_1 = 'deepflow-grafana' OR pod_group_1 = 'deepflow-server' OR pod_group_1 = 'loadgenerator' OR pod_group_1 = 'reviews-v1' OR pod_group_1 = 'adservice' OR pod_group_1 = 'ratings-v1' OR pod_group_1 = 'deepflow-agent' OR pod_group_1 = 'checkoutservice' OR pod_group_1 = 'paymentservice' OR pod_group_1 = 'redis-cart' OR pod_group_1 = 'deepflow-app' OR pod_group_1 = 'cartservice' OR pod_group_1 = 'shippingservice' OR pod_group_1 = 'otel-agent' OR pod_group_1 = 'loo-svc-full' OR pod_group_1 = 'bar-svc-full' OR pod_group_1 = 'reviews-v3' OR pod_group_1 = 'currencyservice' OR pod_group_1 = 'svc-stock' OR pod_group_1 = 'foo-svc-part' OR pod_group_1 = 'loadgenerator-ng' OR pod_group_1 = 'prometheus-k8s' OR pod_group_1 = 'redis-master' OR pod_group_1 = 'svc-order' OR pod_group_1 = 'foo-svc-full' OR pod_group_1 = 'bar-svc-part' OR pod_group_1 = 'details-v1' OR pod_group_1 = 'loo-svc-part' OR pod_group_1 = 'productpage-v1' OR pod_group_1 = 'opentelemetry-demo-redis' OR pod_group_1 = 'productcatalogservice' OR pod_group_1 = 'prometheus-operator' OR pod_group_1 = 'prometheus-adapter' OR pod_group_1 = 'opentelemetry-demo-kafka' OR pod_group_1 = 'alertmanager-main' OR pod_group_1 = 'openebs-ndm-operator' OR pod_group_1 = 'prometheus-alertmanager' OR pod_group_1 = 'deepflow-clickhouse' OR pod_group_1 = 'istio-ingressgateway' OR pod_group_1 = 'recommendationservice' OR pod_group_1 = 'prometheus-server' OR pod_group_1 = 'prometheus-pushgateway' OR pod_group_1 = 'istio-egressgateway' OR pod_group_1 = 'openebs-ndm-node-exporter' OR pod_group_1 = 'opentelemetry-demo-emailservice' OR pod_group_1 = 'opentelemetry-demo-frauddetectionservice' OR pod_group_1 = 'opentelemetry-demo-paymentservice' OR pod_group_1 = 'opentelemetry-demo-jaeger' OR pod_group_1 = 'opentelemetry-demo-currencyservice' OR pod_group_1 = 'opentelemetry-demo-cartservice' OR pod_group_1 = 'opentelemetry-demo-productcatalogservice' OR pod_group_1 = 'opentelemetry-demo-shippingservice' OR pod_group_1 = 'openebs-localpv-provisioner' OR pod_group_1 = 'demo-ingress-nginx-ingress' OR pod_group_1 = 'opentelemetry-demo-ffspostgres' OR pod_group_1 = 'opentelemetry-demo-accountingservice' OR pod_group_1 = 'opentelemetry-demo-frontendproxy' OR pod_group_1 = 'opentelemetry-demo-featureflagservice' OR pod_group_1 = 'opentelemetry-demo-loadgenerator' OR pod_group_1 = 'openebs-ndm-cluster-exporter' OR pod_group_1 = 'opentelemetry-demo-recommendationservice' OR pod_group_1 = 'opentelemetry-demo-adservice' OR pod_group_1 = 'opentelemetry-demo-checkoutservice' OR pod_group_1 = 'prometheus-kube-state-metrics' OR pod_group_1 = 'opentelemetry-demo-otelcol' OR pod_group_1 = 'opentelemetry-demo-prometheus-server' OR pod_group_1 = 'opentelemetry-demo-quoteservice' OR pod_group_1 = 'opentelemetry-demo-frontend') AND signal_source IN (3) AND l7_protocol IN (60,61) AND response_status IN (3,4,2) AND time>=1705627194 AND time<=1705648794 GROUP BY auto_service_1, request_resource, response_status, response_exception, l7_protocol, auto_service_id_1, `server_node_type` LIMIT 1000"
    }
   ]
  },
  {
   "title": "慢调用列表",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"10d8b60a-1de1-988f-a51c-1c4b17725f9b\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"request_resource\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"e7ae1e8a-a849-ea49-ddd6-1c926bec135d\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"07410918-91a7-9c4c-b094-8db2725c6249\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_status\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"241c6823-11d6-fab6-0551-b31c02666195\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"metric\",\"key\":\"response_duration\",\"func\":\"Max\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"94537aea-0e3f-5d93-ec0b-bbd17e542979\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Max\",\"params\":[]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"67960c68-e196-a1af-3ac5-3359ca52fd47\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"896b7702-0835-e747-19a5-01aea4d318c9\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"5edc41c5-c911-8034-04c2-e5f4338826a2\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"9c1d9631-4ff0-86cd-65bd-b5bf94e4f657\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"MySQL\",\"value\":60},{\"label\":\"PostgreSQL\",\"value\":61}],\"as\":\"\",\"params\":[],\"uuid\":\"fb2baf2f-bbc5-1fe8-8ab1-23f88b59b50c\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"fromSelect94537aea-0e3f-5d93-ec0b-bbd17e542979\",\"func\":\"Max\",\"op\":\">=\",\"val\":\"200000\",\"as\":\"\",\"params\":[],\"uuid\":\"ad65d3a1-d0d2-9888-13b3-f3092bd54f96\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"fromSelect\":{\"type\":\"metric\",\"key\":\"response_duration\",\"func\":\"Max\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"94537aea-0e3f-5d93-ec0b-bbd17e542979\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Max\",\"params\":[]}},\"cache\":{\"func\":\"Max\",\"params\":[],\"subFuncs\":[]}}],\"groupBy\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6667be37-2d7f-76d3-9be6-4a86bc6c7a90\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"request_resource\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5172d18d-d965-4c59-3390-b5fc79d62e03\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_status\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"bbb7eb60-1a99-f77c-42c7-99d9740c7614\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"55db6e28-2419-a6ed-c51f-f0de5e82ca43\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"18e8c440-535f-63b1-0165-7724354bf20e\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"table\",\"alias\":\"\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "Max(response_duration)", "name": "Max(response_duration)", "type": 3, "unit": "us" }
     ],
     "returnTags": [
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_1",
       "role": "server"
      },
      {
       "displayName": "Request Resource",
       "isResource": false,
       "name": "request_resource"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "Enum(l7_protocol)"
      },
      {
       "displayName": "Response Status",
       "isResource": false,
       "name": "Enum(response_status)"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_id_1",
       "role": "server"
      },
      {
       "displayName": "节点类型",
       "isResource": true,
       "name": "`server_node_type`",
       "role": "server"
      },
      {
       "displayName": "图标",
       "isResource": true,
       "name": "`server_icon_id`",
       "role": "server"
      },
      {
       "displayName": "Response Status",
       "isResource": false,
       "name": "response_status"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "l7_protocol"
      }
     ],
     "sql": "SELECT Max(`response_duration`) AS `Max(response_duration)`, auto_service_1, request_resource, Enum(l7_protocol), Enum(response_status), auto_service_id_1, node_type(auto_service_1) AS `server_node_type`, icon_id(auto_service_1) AS `server_icon_id`, response_status, l7_protocol FROM l7_flow_log WHERE (pod_cluster_0 = 'k8s-d-rUL3jSx3ft' OR pod_cluster_1 = 'k8s-d-rUL3jSx3ft') AND (pod_ns_0 = 'deepflow-otel-dubbo-demo' OR pod_ns_1 = 'deepflow-otel-dubbo-demo') AND (pod_group_0 = 'svc-item' OR pod_group_0 = 'svc-user' OR pod_group_0 = 'web-shop' OR pod_group_0 = 'nacos' OR pod_group_0 = 'db-demo' OR pod_group_0 = 'loadgenerator' OR pod_group_0 = 'svc-stock' OR pod_group_0 = 'svc-order' OR pod_group_1 = 'svc-item' OR pod_group_1 = 'svc-user' OR pod_group_1 = 'web-shop' OR pod_group_1 = 'nacos' OR pod_group_1 = 'db-demo' OR pod_group_1 = 'loadgenerator' OR pod_group_1 = 'svc-stock' OR pod_group_1 = 'svc-order') AND signal_source IN (0) AND l7_protocol IN (60,61) AND time>=1705643969 AND time<=1705647569 GROUP BY auto_service_1, request_resource, response_status, l7_protocol, auto_service_id_1, `server_node_type` HAVING Max(`response_duration`)>='200000' LIMIT 1000"
    }
   ]
  },
  { "title": "DNS 分析", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "请求速率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"vtap_app_port\",\"select\":[{\"key\":\"request\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"f5f2a3ae-3099-6b99-005e-8d4562018121\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"PerSecond\"}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"PerSecond\"}]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c16deb2d-fe3c-69ff-01a5-8859e7dfaa51\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"228def66-88ae-f295-d0a2-2e0b9d572442\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c6bd3e65-dc5d-ed9d-d055-048ec27992b3\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"709938cd-ad05-29dc-eee5-193ecdd091b8\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"DNS\",\"value\":120}],\"as\":\"\",\"params\":[],\"uuid\":\"1b5ac5be-aa36-30e2-5897-a62d554a1dac\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6d4af51b-488e-7f5f-e949-4a997977a6a8\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a08841f1-af76-acdb-39d3-8d3a791c024e\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"76bcc3ff-77ec-d32d-ed6a-391651b993b2\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"slimit\":\"\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service}\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "PerSecond(Avg(request))", "name": "PerSecond(Avg(request))", "type": 1, "unit": "/s" }
     ],
     "returnTags": [
      {
       "displayName": "time_60",
       "isResource": false,
       "name": "`time_60`"
      },
      {
       "displayName": "节点类型",
       "isResource": false,
       "name": "`node_type`"
      },
      {
       "displayName": "图标",
       "isResource": false,
       "name": "`icon_id`"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": false,
       "name": "auto_service_id"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": false,
       "name": "auto_service"
      }
     ],
     "sql": "SELECT PerSecond(Avg(`request`)) AS `PerSecond(Avg(request))`, time(time, 60) AS `time_60`, node_type(auto_service) AS `node_type`, icon_id(auto_service) AS `icon_id`, auto_service_id, auto_service FROM vtap_app_port WHERE pod_cluster = 'k8s-d-rUL3jSx3ft' AND pod_ns = 'deepflow' AND (pod_group = 'deepflow-mysql' OR pod_group = 'deepflow-grafana' OR pod_group = 'deepflow-server' OR pod_group = 'deepflow-agent' OR pod_group = 'deepflow-app' OR pod_group = 'deepflow-clickhouse') AND signal_source IN (0) AND l7_protocol IN (120) AND time>=1705643483 AND time<=1705644383 GROUP BY `time_60`, auto_service, auto_service_id, `node_type` SLIMIT 20 LIMIT 10000"
    }
   ]
  },
  {
   "title": "异常比例",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"vtap_app_port\",\"select\":[{\"key\":\"client_error_ratio\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"客户端异常比例\",\"params\":[],\"uuid\":\"f5f2a3ae-3099-6b99-005e-8d4562018121\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[]}},{\"type\":\"metric\",\"key\":\"server_error\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"服务端异常比例\",\"params\":[],\"uuid\":\"4b2e0aa3-8176-d1de-dc6d-f564d854cc21\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c16deb2d-fe3c-69ff-01a5-8859e7dfaa51\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"228def66-88ae-f295-d0a2-2e0b9d572442\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c6bd3e65-dc5d-ed9d-d055-048ec27992b3\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"709938cd-ad05-29dc-eee5-193ecdd091b8\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"DNS\",\"value\":120}],\"as\":\"\",\"params\":[],\"uuid\":\"1b5ac5be-aa36-30e2-5897-a62d554a1dac\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d716705c-9a0b-582b-bd72-72ccfb74b7f9\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a08841f1-af76-acdb-39d3-8d3a791c024e\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"76bcc3ff-77ec-d32d-ed6a-391651b993b2\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"slimit\":\"\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service}\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "客户端异常比例", "name": "客户端异常比例", "type": 4, "unit": "%" },
      { "displayName": "服务端异常比例", "name": "服务端异常比例", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "time_60",
       "isResource": false,
       "name": "`time_60`"
      },
      {
       "displayName": "节点类型",
       "isResource": false,
       "name": "`node_type`"
      },
      {
       "displayName": "图标",
       "isResource": false,
       "name": "`icon_id`"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": false,
       "name": "auto_service_id"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": false,
       "name": "auto_service"
      }
     ],
     "sql": "SELECT Avg(`client_error_ratio`) AS `客户端异常比例`, Avg(`server_error`) AS `服务端异常比例`, time(time, 60) AS `time_60`, node_type(auto_service) AS `node_type`, icon_id(auto_service) AS `icon_id`, auto_service_id, auto_service FROM vtap_app_port WHERE pod_cluster = 'k8s-d-rUL3jSx3ft' AND pod_ns = 'deepflow' AND (pod_group = 'deepflow-mysql' OR pod_group = 'deepflow-grafana' OR pod_group = 'deepflow-server' OR pod_group = 'deepflow-agent' OR pod_group = 'deepflow-app' OR pod_group = 'deepflow-clickhouse') AND signal_source IN (0) AND l7_protocol IN (120) AND time>=1705643483 AND time<=1705644383 GROUP BY `time_60`, auto_service, auto_service_id, `node_type` SLIMIT 20 LIMIT 10000"
    }
   ]
  },
  {
   "title": "响应时延",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"vtap_app_port\",\"select\":[{\"key\":\"rrt_max\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"f5f2a3ae-3099-6b99-005e-8d4562018121\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c16deb2d-fe3c-69ff-01a5-8859e7dfaa51\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"228def66-88ae-f295-d0a2-2e0b9d572442\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c6bd3e65-dc5d-ed9d-d055-048ec27992b3\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"709938cd-ad05-29dc-eee5-193ecdd091b8\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"DNS\",\"value\":120}],\"as\":\"\",\"params\":[],\"uuid\":\"1b5ac5be-aa36-30e2-5897-a62d554a1dac\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"3b306670-5142-226d-a44f-a416c130dbb3\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a08841f1-af76-acdb-39d3-8d3a791c024e\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"76bcc3ff-77ec-d32d-ed6a-391651b993b2\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"slimit\":\"\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service}\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "Avg(rrt_max)", "name": "Avg(rrt_max)", "type": 3, "unit": "us" }
     ],
     "returnTags": [
      {
       "displayName": "time_60",
       "isResource": false,
       "name": "`time_60`"
      },
      {
       "displayName": "节点类型",
       "isResource": false,
       "name": "`node_type`"
      },
      {
       "displayName": "图标",
       "isResource": false,
       "name": "`icon_id`"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": false,
       "name": "auto_service_id"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": false,
       "name": "auto_service"
      }
     ],
     "sql": "SELECT Avg(`rrt_max`) AS `Avg(rrt_max)`, time(time, 60) AS `time_60`, node_type(auto_service) AS `node_type`, icon_id(auto_service) AS `icon_id`, auto_service_id, auto_service FROM vtap_app_port WHERE pod_cluster = 'k8s-d-rUL3jSx3ft' AND pod_ns = 'deepflow' AND (pod_group = 'deepflow-mysql' OR pod_group = 'deepflow-grafana' OR pod_group = 'deepflow-server' OR pod_group = 'deepflow-agent' OR pod_group = 'deepflow-app' OR pod_group = 'deepflow-clickhouse') AND signal_source IN (0) AND l7_protocol IN (120) AND time>=1705643483 AND time<=1705644383 GROUP BY `time_60`, auto_service, auto_service_id, `node_type` SLIMIT 20 LIMIT 10000"
    }
   ]
  },
  {
   "title": "异常调用列表",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"10d8b60a-1de1-988f-a51c-1c4b17725f9b\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"request_resource\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"e7ae1e8a-a849-ea49-ddd6-1c926bec135d\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"07410918-91a7-9c4c-b094-8db2725c6249\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_exception\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a5631f4b-1188-1ae0-320c-607aa6351b2f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_status\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"241c6823-11d6-fab6-0551-b31c02666195\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"metric\",\"key\":\"log_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"31e943e6-1457-4032-cfb6-19c465f38e02\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"67960c68-e196-a1af-3ac5-3359ca52fd47\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"896b7702-0835-e747-19a5-01aea4d318c9\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"5edc41c5-c911-8034-04c2-e5f4338826a2\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"9c1d9631-4ff0-86cd-65bd-b5bf94e4f657\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"DNS\",\"value\":120}],\"as\":\"\",\"params\":[],\"uuid\":\"fb2baf2f-bbc5-1fe8-8ab1-23f88b59b50c\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_status\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Server Error\",\"value\":3},{\"label\":\"Client Error\",\"value\":4},{\"label\":\"Unknown\",\"value\":2}],\"as\":\"\",\"params\":[],\"uuid\":\"269cd391-f60a-4560-bfd2-ad9a165a7aa4\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"07c885ba-04aa-a240-5d87-d28e1d9ae2c9\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6667be37-2d7f-76d3-9be6-4a86bc6c7a90\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"request_resource\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5172d18d-d965-4c59-3390-b5fc79d62e03\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_status\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"bbb7eb60-1a99-f77c-42c7-99d9740c7614\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_exception\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5af2fef0-7171-4512-5578-73c2c4f091d1\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"55db6e28-2419-a6ed-c51f-f0de5e82ca43\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"18e8c440-535f-63b1-0165-7724354bf20e\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"table\",\"alias\":\"\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "Sum(log_count)", "name": "Sum(log_count)", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_1",
       "role": "server"
      },
      {
       "displayName": "Request Resource",
       "isResource": false,
       "name": "request_resource"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "Enum(l7_protocol)"
      },
      {
       "displayName": "Response Exception",
       "isResource": false,
       "name": "response_exception"
      },
      {
       "displayName": "Response Status",
       "isResource": false,
       "name": "Enum(response_status)"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_id_1",
       "role": "server"
      },
      {
       "displayName": "节点类型",
       "isResource": true,
       "name": "`server_node_type`",
       "role": "server"
      },
      {
       "displayName": "图标",
       "isResource": true,
       "name": "`server_icon_id`",
       "role": "server"
      },
      {
       "displayName": "Response Status",
       "isResource": false,
       "name": "response_status"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "l7_protocol"
      }
     ],
     "sql": "SELECT Sum(`log_count`) AS `Sum(log_count)`, auto_service_1, request_resource, Enum(l7_protocol), response_exception, Enum(response_status), auto_service_id_1, node_type(auto_service_1) AS `server_node_type`, icon_id(auto_service_1) AS `server_icon_id`, response_status, l7_protocol FROM l7_flow_log WHERE (pod_cluster_0 = 'k8s-d-rUL3jSx3ft' OR pod_cluster_1 = 'k8s-d-rUL3jSx3ft') AND (pod_ns_0 = 'deepflow' OR pod_ns_1 = 'deepflow') AND (pod_group_0 = 'deepflow-mysql' OR pod_group_0 = 'deepflow-grafana' OR pod_group_0 = 'deepflow-server' OR pod_group_0 = 'deepflow-agent' OR pod_group_0 = 'deepflow-app' OR pod_group_0 = 'deepflow-clickhouse' OR pod_group_1 = 'deepflow-mysql' OR pod_group_1 = 'deepflow-grafana' OR pod_group_1 = 'deepflow-server' OR pod_group_1 = 'deepflow-agent' OR pod_group_1 = 'deepflow-app' OR pod_group_1 = 'deepflow-clickhouse') AND signal_source IN (0) AND l7_protocol IN (120) AND response_status IN (3,4,2) AND time>=1705643483 AND time<=1705644383 GROUP BY auto_service_1, request_resource, response_status, response_exception, l7_protocol, auto_service_id_1, `server_node_type` LIMIT 1000"
    }
   ]
  }
 ]
}