{
 "title": "Network - Flow Log - Cloud",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "deepflowio-deepflow-datasource" },
   {
    "name": "cluster",
    "query": {}
   },
   {
    "name": "namespace",
    "query": {}
   },
   {
    "name": "workload",
    "query": {}
   },
   {
    "name": "vm",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Summary count ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l4_flow_log\",\"select\":[{\"type\":\"metric\",\"key\":\"log_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"0ade37a3-a41d-91db-f054-2d8060e5b47c\",\"subFuncs\":[]}],\"where\":[{\"type\":\"tag\",\"key\":\"chost\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$vm\",\"value\":\"vm\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"cd90bdbe-33b3-a564-23d0-5964e25da42e\",\"subFuncs\":[],\"whereOnly\":true}],\"having\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"61f42035-1e22-cad5-8edb-dd260b28ccb6\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"84f99013-2bf0-3474-6674-bd8e7f9074e5\"}],\"orderBy\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"89f85c9d-4bbd-fb0e-1d7f-2ef8546054f2\",\"sort\":\"asc\"}],\"interval\":\"60\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"Total\",\"showMetrics\":0,\"tracingId\":null}"
    }
   ]
  },
  {
   "title": "Error count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l4_flow_log\",\"select\":[{\"type\":\"metric\",\"key\":\"log_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"Sum(客户端异常)\",\"params\":[],\"uuid\":\"40b7494b-c90b-6897-cf2d-b1b8e5635f28\",\"subFuncs\":[]}],\"where\":[{\"type\":\"tag\",\"key\":\"status\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Client Error\",\"value\":4}],\"as\":\"\",\"params\":[],\"uuid\":\"b64b0548-ee9b-f0c8-ed82-ddadea0b575b\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"chost\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$vm\",\"value\":\"vm\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"009b3624-5f7b-104a-474e-3aceace24c55\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false}],\"having\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"61f42035-1e22-cad5-8edb-dd260b28ccb6\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"20eda8e6-9fdd-1ba5-2430-4b7e63c8884a\",\"subFuncs\":[]}],\"orderBy\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"89f85c9d-4bbd-fb0e-1d7f-2ef8546054f2\",\"sort\":\"asc\"}],\"interval\":\"60\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"Client Error\",\"showMetrics\":0,\"tracingId\":null}"
    },
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l4_flow_log\",\"select\":[{\"type\":\"metric\",\"key\":\"log_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"Sum(服务端异常)\",\"params\":[],\"uuid\":\"40b7494b-c90b-6897-cf2d-b1b8e5635f28\",\"subFuncs\":[]}],\"where\":[{\"type\":\"tag\",\"key\":\"status\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Server Error\",\"value\":3}],\"as\":\"\",\"params\":[],\"uuid\":\"b64b0548-ee9b-f0c8-ed82-ddadea0b575b\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"chost\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$vm\",\"value\":\"vm\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"daa29da0-0138-3870-55d4-ee924024a6a4\",\"subFuncs\":[],\"whereOnly\":true}],\"having\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"61f42035-1e22-cad5-8edb-dd260b28ccb6\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"20eda8e6-9fdd-1ba5-2430-4b7e63c8884a\",\"subFuncs\":[]}],\"orderBy\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"89f85c9d-4bbd-fb0e-1d7f-2ef8546054f2\",\"sort\":\"asc\"}],\"interval\":\"60\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"Server Error\",\"showMetrics\":0,\"tracingId\":null}"
    }
   ]
  },
  {
   "title": "TCP est.conn latency distribution ",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l4_flow_log\",\"select\":[{\"type\":\"metric\",\"key\":\"rtt\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"091d0ef1-38e0-29c9-738c-fc476ecaec0e\",\"subFuncs\":[]}],\"where\":[{\"type\":\"tag\",\"key\":\"chost\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$vm\",\"value\":\"vm\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"25e284ef-1136-dbd9-4851-3776c1032a19\",\"subFuncs\":[],\"whereOnly\":true}],\"having\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"61f42035-1e22-cad5-8edb-dd260b28ccb6\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"84f99013-2bf0-3474-6674-bd8e7f9074e5\"}],\"orderBy\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"89f85c9d-4bbd-fb0e-1d7f-2ef8546054f2\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":-1,\"tracingId\":null}"
    }
   ]
  },
  {
   "title": "TCP data latency distribution",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l4_flow_log\",\"select\":[{\"type\":\"metric\",\"key\":\"art\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"art\",\"params\":[],\"uuid\":\"2a51e545-bd7c-39b3-fba7-c409de96b791\",\"subFuncs\":[]}],\"where\":[{\"type\":\"tag\",\"key\":\"chost\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$vm\",\"value\":\"vm\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"ddb962a4-120e-961e-c7dd-fc2d7824bd38\",\"subFuncs\":[],\"whereOnly\":true}],\"having\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"61f42035-1e22-cad5-8edb-dd260b28ccb6\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"84f99013-2bf0-3474-6674-bd8e7f9074e5\"}],\"orderBy\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"89f85c9d-4bbd-fb0e-1d7f-2ef8546054f2\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"100\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":null}"
    }
   ]
  },
  {
   "title": "Flow log ",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l4_flow_log\",\"select\":[{\"type\":\"tag\",\"key\":\"resource_gl0_0\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"30f43432-66f7-df29-4dab-a33c95246490\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"resource_gl0_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9e480127-4afc-a283-a028-5c3841af5192\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"start_time\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8262e45b-525e-3297-4048-e7bce4ad6ded\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"protocol\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8ebe6891-2745-0fe4-5858-44648827a278\",\"subFuncs\":[],\"cache\":{\"func\":\"Enum\",\"params\":[]}},{\"type\":\"tag\",\"key\":\"client_port\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8adc65aa-0f44-f65b-5699-abb8f176ca0b\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"server_port\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"cbd3cba6-21f8-380a-d921-02fabcd2676a\",\"subFuncs\":[],\"cache\":{\"func\":\"Enum\",\"params\":[]}},{\"type\":\"tag\",\"key\":\"tap_side\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6dd53832-601a-9951-c1b9-63795ea24af1\",\"subFuncs\":[],\"cache\":{\"func\":\"Enum\",\"params\":[]}},{\"type\":\"tag\",\"key\":\"status\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"42bd700a-d26a-c9b2-9582-9d0f1f8f3fe8\",\"subFuncs\":[],\"cache\":{\"func\":\"Enum\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"byte_tx\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"278a3327-43d5-767d-2e47-7c275b37fa86\",\"subFuncs\":[]},{\"type\":\"metric\",\"key\":\"byte_rx\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"896235de-d2f2-2fcd-e52a-53e2ea36dde7\",\"subFuncs\":[]},{\"type\":\"metric\",\"key\":\"retrans_tx\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"ee78f470-aed2-fbe4-f880-557d4a5d377c\",\"subFuncs\":[]},{\"type\":\"metric\",\"key\":\"retrans_rx\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"e42d8336-a5d1-f23a-eb43-13bb336b074b\",\"subFuncs\":[]},{\"type\":\"metric\",\"key\":\"rtt\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5a9a3884-1fe7-2421-1ae1-fbdd62a3ad2a\",\"subFuncs\":[]},{\"type\":\"metric\",\"key\":\"art\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"320eec8d-d25f-8e39-d677-502d08a8feb2\",\"subFuncs\":[]}],\"where\":[{\"type\":\"tag\",\"key\":\"chost\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$vm\",\"value\":\"vm\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"c7c77c5d-fc54-a720-540e-2d17c7adaba1\",\"subFuncs\":[],\"whereOnly\":true}],\"having\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"988ffa7a-4570-7f87-c676-7758d7d2701a\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9f39300f-1734-bc16-4b1f-d17fbdfb0d7e\"}],\"orderBy\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d986f27a-13e7-0508-b0d8-95f49cbae215\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"500\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":null}"
    }
   ]
  }
 ]
}