# Generated by Django 4.2.27 on 2025-12-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpaceResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("space_type_id", models.CharField(max_length=64, verbose_name="空间类型英文名称")),
                ("space_id", models.CharField(max_length=128, verbose_name="空间英文名称")),
                ("bk_tenant_id", models.CharField(default="system", max_length=256, null=True, verbose_name="租户ID")),
                (
                    "resource_type",
                    models.CharField(
                        help_text="关联的资源类型，必须属于某个空间类型", max_length=128, verbose_name="资源类型"
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        help_text="关联的资源的唯一标识，如关联BCS项目ID，BKCC业务ID等",
                        max_length=64,
                        null=True,
                        verbose_name="关联的资源唯一标识",
                    ),
                ),
                (
                    "dimension_values",
                    models.TextField(
                        default="[]",
                        help_text="关键维度值，格式如[{'project_id': 'testproject', 'cluster_id': 'BCS-K8S-1000', 'namespace': 'test'}]",
                        verbose_name="关键维度对应的值",
                    ),
                ),
                ("creator", models.CharField(max_length=64, verbose_name="创建者")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="更新者")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "空间资源",
                "verbose_name_plural": "空间资源详情",
                "db_table": "metadata_spaceresource",
                "managed": True,
                "unique_together": {("space_type_id", "space_id", "resource_type", "resource_id")},
            },
        ),
        migrations.CreateModel(
            name="SpaceModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("space_type_id", models.CharField(max_length=64, verbose_name="空间类型 ID")),
                (
                    "space_id",
                    models.CharField(
                        help_text="空间类型下唯一, BKCC是业务ID，其他类型是项目Code",
                        max_length=128,
                        verbose_name="空间 ID",
                    ),
                ),
                ("bk_tenant_id", models.CharField(default="system", max_length=256, null=True, verbose_name="租户ID")),
                (
                    "space_name",
                    models.CharField(help_text="空间类型下唯一", max_length=256, verbose_name="空间中文名称"),
                ),
                (
                    "space_code",
                    models.CharField(
                        blank=True,
                        help_text="针对容器和研发类型，会多存储存储code这个字段",
                        max_length=64,
                        null=True,
                        verbose_name="空间英文名称",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("normal", "正常"), ("disabled", "停用")],
                        default="normal",
                        max_length=32,
                        verbose_name="空间状态",
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(
                        default="Asia/Shanghai",
                        help_text="时区，默认为Asia/Shanghai",
                        max_length=32,
                        verbose_name="时区",
                    ),
                ),
                (
                    "language",
                    models.CharField(default="zh-hans", help_text="使用的语言", max_length=16, verbose_name="默认语言"),
                ),
                ("is_bcs_valid", models.BooleanField(default=False, verbose_name="BCS 是否可用")),
                ("is_global", models.BooleanField(default=False, verbose_name="跨业务管理可用")),
                ("creator", models.CharField(max_length=64, verbose_name="创建者")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="更新者")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "空间信息",
                "verbose_name_plural": "空间信息",
                "db_table": "metadata_space",
                "managed": True,
                "unique_together": {("space_type_id", "space_id"), ("space_type_id", "space_name", "bk_tenant_id")},
            },
        ),
    ]
