# Generated by Django 3.2.25 on 2025-06-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("agent_code", models.CharField(db_index=True, max_length=128, verbose_name="智能体代码")),
                ("agent_name", models.CharField(max_length=128, verbose_name="智能体名称")),
                ("llm_model_name", models.CharField(max_length=128, verbose_name="LLM模型名称")),
                ("non_thinking_llm_model_name", models.CharField(max_length=128, verbose_name="非深度思考模型")),
                ("role_prompt", models.TextField(blank=True, null=True, verbose_name="角色提示词")),
                ("knowledgebase_ids", models.JSONField(default=list, verbose_name="知识库ID列表")),
                ("tool_codes", models.JSONField(default=list, verbose_name="工具列表")),
                ("opening_mark", models.TextField(blank=True, null=True, verbose_name="智能体开场白")),
            ],
            options={
                "verbose_name": "智能体配置",
                "verbose_name_plural": "智能体配置",
            },
        ),
    ]
