name: "[BKLog] Backend Test"

defaults:
  run:
    working-directory: bklog

on:
  push:
    paths:
      - 'bklog/**'
  pull_request:
    paths:
      - 'bklog/**'
  schedule:
    - cron: "0 10 * * *"
jobs:
  run:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: bklog
    container:
      image: python:3.6.8
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Run Test
      run: |
        source scripts/test_env.sh
        sed -i '/APIGW_ENABLED/d' dev.env.yml
        pip install --upgrade pip setuptools
        pip install -r requirements.txt
        pip install coverage
        pip uninstall pycrypto -y
        pip uninstall pycryptodome -y
        pip install pycryptodome
        python manage.py test apps.tests
