name: "[BKLog] Backend Test"

permissions:
  contents: read

defaults:
  run:
    working-directory: bklog

on:
  push:
    paths:
      - 'bklog/**'
  pull_request:
    paths:
      - 'bklog/**'
  schedule:
    - cron: "0 10 * * *"

# https://github.com/actions/checkout/issues/1590
env:
    ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  run:
    # runs-on: ubuntu-20.04
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: bklog
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.10'
    - name: Run Test
      run: |
        source scripts/test_env.sh
        sed -i '/APIGW_ENABLED/d' dev.env.yml
        pip install --upgrade pip setuptools
        pip install -r requirements.txt
        pip install coverage
        pip uninstall pycrypto -y
        pip uninstall pycryptodome -y
        pip install pycryptodome
        python manage.py test apps.tests
